In [1]:
import pandas as pd

patients = pd.read_csv("../../data/raw/patients.csv")
encounters = pd.read_csv("../../data/raw/encounters.csv")
procedures = pd.read_csv("../../data/raw/procedures.csv")
payers = pd.read_csv("../../data/raw/payers.csv")
organizations = pd.read_csv("../../data/raw/organizations.csv")

In [2]:
procedures.head()

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,REASONCODE,REASONDESCRIPTION
0,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,32c84703-2481-49cd-d571-3899d5820253,265764009,Renal dialysis (procedure),903,NaN,NaN
1,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,d9ec2e44-32e9-9148-179a-1653348cc4e2,c98059da-320a-c0a6-fced-c8815f3e3f39,76601001,Intramuscular injection,2477,NaN,NaN
2,2011-01-04T14:49:55Z,2011-01-04T15:04:55Z,d856d6e6-4c98-e7a2-129b-44076c63d008,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,703423002,Combined chemotherapy and radiation therapy (p...,11620,363406005.0,Malignant tumor of colon
3,2011-01-05T04:02:09Z,2011-01-05T04:17:09Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,17966936-0878-f4db-128b-a43ae10d0878,173160006,Diagnostic fiberoptic bronchoscopy (procedure),9796,162573006.0,Suspected lung cancer (situation)
4,2011-01-05T12:58:36Z,2011-01-05T16:42:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,9de5f0b0-4ba4-ce6f-45fb-b55c202f31a5,265764009,Renal dialysis (procedure),1255,NaN,NaN

In [3]:
patients.head()

,Id,BIRTHDATE,DEATHDATE,PREFIX,FIRST,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON
0,5605b66b-e92d-c16c-1b83-b8bf7040d51f,1977-03-19,NaN,Mrs.,Nikita578,Erdman779,NaN,Leannon79,M,white,nonhispanic,F,Wakefield Massachusetts US,510 Little Station Unit 69,Quincy,Massachusetts,Norfolk County,2186.0,42.290937,-70.975503
1,6e5ae27c-8038-7988-e2c0-25a103f01bfa,1940-02-19,NaN,Mr.,Zane918,Hodkiewicz467,NaN,NaN,M,white,nonhispanic,M,Brookline Massachusetts US,747 Conn Throughway,Boston,Massachusetts,Suffolk County,2135.0,42.308831,-71.063162
2,8123d076-0886-9007-e956-d5864aa121a7,1958-06-04,NaN,Mr.,Quinn173,Marquardt819,NaN,NaN,M,white,nonhispanic,M,Gardner Massachusetts US,816 Okuneva Extension Apt 91,Quincy,Massachusetts,Norfolk County,2170.0,42.265177,-70.967085
3,770518e4-6133-648e-60c9-071eb2f0e2ce,1928-12-25,2017-09-29,Mr.,Abel832,Smitham825,NaN,NaN,M,white,hispanic,M,Randolph Massachusetts US,127 Cole Way Unit 95,Boston,Massachusetts,Suffolk County,2118.0,42.334304,-71.066801
4,f96addf5-81b9-0aab-7855-d208d3d352c5,1928-12-25,2014-02-23,Mr.,Edwin773,Labadie908,NaN,NaN,M,white,hispanic,M,Stow Massachusetts US,976 Ziemann Gateway,Boston,Massachusetts,Suffolk County,2125.0,42.346771,-71.058813

In [4]:
procedures.head()

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,REASONCODE,REASONDESCRIPTION
0,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,32c84703-2481-49cd-d571-3899d5820253,265764009,Renal dialysis (procedure),903,NaN,NaN
1,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,d9ec2e44-32e9-9148-179a-1653348cc4e2,c98059da-320a-c0a6-fced-c8815f3e3f39,76601001,Intramuscular injection,2477,NaN,NaN
2,2011-01-04T14:49:55Z,2011-01-04T15:04:55Z,d856d6e6-4c98-e7a2-129b-44076c63d008,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,703423002,Combined chemotherapy and radiation therapy (p...,11620,363406005.0,Malignant tumor of colon
3,2011-01-05T04:02:09Z,2011-01-05T04:17:09Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,17966936-0878-f4db-128b-a43ae10d0878,173160006,Diagnostic fiberoptic bronchoscopy (procedure),9796,162573006.0,Suspected lung cancer (situation)
4,2011-01-05T12:58:36Z,2011-01-05T16:42:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,9de5f0b0-4ba4-ce6f-45fb-b55c202f31a5,265764009,Renal dialysis (procedure),1255,NaN,NaN

In [5]:
payers.head()

,Id,NAME,ADDRESS,CITY,STATE_HEADQUARTERED,ZIP,PHONE
0,b3221cfc-24fb-339e-823d-bc4136cbc4ed,Dual Eligible,7500 Security Blvd,Baltimore,MD,21244.0,1-877-267-2323
1,7caa7254-5050-3b5e-9eae-bd5ea30e809c,Medicare,7500 Security Blvd,Baltimore,MD,21244.0,1-800-633-4227
2,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,Medicaid,7500 Security Blvd,Baltimore,MD,21244.0,1-877-267-2323
3,d47b3510-2895-3b70-9897-342d681c769d,Humana,500 West Main St,Louisville,KY,40018.0,1-844-330-7799
4,6e2f1a2d-27bd-3701-8d08-dae202c58632,Blue Cross Blue Shield,Michigan Plaza,Chicago,IL,60007.0,1-800-262-2583

In [6]:
organizations.head()

,Id,NAME,ADDRESS,CITY,STATE,ZIP,LAT,LON
0,d78e84ec-30aa-3bba-a33a-f29a3a454662,MASSACHUSETTS GENERAL HOSPITAL,55 FRUIT STREET,BOSTON,MA,2114,42.362813,-71.069187

In [7]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          974 non-null    str
 1   BIRTHDATE   974 non-null    str
 2   DEATHDATE   154 non-null    str
 3   PREFIX      974 non-null    str
 4   FIRST       974 non-null    str
 5   LAST        974 non-null    str
 6   SUFFIX      21 non-null     str
 7   MAIDEN      386 non-null    str
 8   MARITAL     973 non-null    str
 9   RACE        974 non-null    str
 10  ETHNICITY   974 non-null    str
 11  GENDER      974 non-null    str
 12  BIRTHPLACE  974 non-null    str
 13  ADDRESS     974 non-null    str
 14  CITY        974 non-null    str
 15  STATE       974 non-null    str
 16  COUNTY      974 non-null    str
 17  ZIP         832 non-null    float64
 18  LAT         974 non-null    float64
 19  LON         974 non-null    float64
dtypes: float64(3), str(17)
memory usage: 152.3 KB

In [8]:
tables = {
    "patients": patients,
    "encounters": encounters,
    "procedures": procedures,
    "payers": payers,
    "organizations": organizations
}

for name, df in tables.items():
    print(f"{name}: {df.shape}")

patients: (974, 20)
encounters: (27891, 14)
procedures: (47701, 9)
payers: (10, 7)
organizations: (1, 8)

In [9]:
for name, df in tables.items():
    print(f"\n===== {name.upper()} =====")
    print(df.columns.tolist())

===== PATIENTS =====
['Id', 'BIRTHDATE', 'DEATHDATE', 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'ZIP', 'LAT', 'LON']

===== ENCOUNTERS =====
['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION']

===== PROCEDURES =====
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION']

===== PAYERS =====
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE_HEADQUARTERED', 'ZIP', 'PHONE']

===== ORGANIZATIONS =====
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON']

In [10]:
for name, df in tables.items():
    print(f"\n===== {name.upper()} =====")
    print(df.dtypes)

===== PATIENTS =====
Id                str
BIRTHDATE         str
DEATHDATE         str
PREFIX            str
FIRST             str
LAST              str
SUFFIX            str
MAIDEN            str
MARITAL           str
RACE              str
ETHNICITY         str
GENDER            str
BIRTHPLACE        str
ADDRESS           str
CITY              str
STATE             str
COUNTY            str
ZIP           float64
LAT           float64
LON           float64
dtype: object

===== ENCOUNTERS =====
Id                         str
START                      str
STOP                       str
PATIENT                    str
ORGANIZATION               str
PAYER                      str
ENCOUNTERCLASS             str
CODE                     int64
DESCRIPTION                str
BASE_ENCOUNTER_COST    float64
TOTAL_CLAIM_COST       float64
PAYER_COVERAGE         float64
REASONCODE             float64
REASONDESCRIPTION          str
dtype: object

===== PROCEDURES =====
START                    str
STOP                     str
PATIENT                  str
ENCOUNTER                str
CODE                   int64
DESCRIPTION              str
BASE_COST              int64
REASONCODE           float64
REASONDESCRIPTION        str
dtype: object

===== PAYERS =====
Id                         str
NAME                       str
ADDRESS                    str
CITY                       str
STATE_HEADQUARTERED        str
ZIP                    float64
PHONE                      str
dtype: object

===== ORGANIZATIONS =====
Id             str
NAME           str
ADDRESS        str
CITY           str
STATE          str
ZIP          int64
LAT        float64
LON        float64
dtype: object

In [11]:
for name, df in tables.items():
    print(f"\n===== {name.upper()} =====")
    print(df.isnull().sum())

===== PATIENTS =====
Id              0
BIRTHDATE       0
DEATHDATE     820
PREFIX          0
FIRST           0
LAST            0
SUFFIX        953
MAIDEN        588
MARITAL         1
RACE            0
ETHNICITY       0
GENDER          0
BIRTHPLACE      0
ADDRESS         0
CITY            0
STATE           0
COUNTY          0
ZIP           142
LAT             0
LON             0
dtype: int64

===== ENCOUNTERS =====
Id                         0
START                      0
STOP                       0
PATIENT                    0
ORGANIZATION               0
PAYER                      0
ENCOUNTERCLASS             0
CODE                       0
DESCRIPTION                0
BASE_ENCOUNTER_COST        0
TOTAL_CLAIM_COST           0
PAYER_COVERAGE             0
REASONCODE             19541
REASONDESCRIPTION      19541
dtype: int64

===== PROCEDURES =====
START                    0
STOP                     0
PATIENT                  0
ENCOUNTER                0
CODE                     0
DESCRIPTION              0
BASE_COST                0
REASONCODE           36945
REASONDESCRIPTION    36945
dtype: int64

===== PAYERS =====
Id                     0
NAME                   0
ADDRESS                1
CITY                   1
STATE_HEADQUARTERED    1
ZIP                    1
PHONE                  1
dtype: int64

===== ORGANIZATIONS =====
Id         0
NAME       0
ADDRESS    0
CITY       0
STATE      0
ZIP        0
LAT        0
LON        0
dtype: int64

In [12]:
for name, df in tables.items():

    missing = (
        df.isnull()
        .sum()
        .to_frame("Missing_Count")
    )

    missing["Missing_Percentage"] = (
        missing["Missing_Count"] / len(df) * 100
    )

    print(f"\n===== {name.upper()} =====")
    print(missing.sort_values(
        "Missing_Percentage",
        ascending=False
    ))

===== PATIENTS =====
            Missing_Count  Missing_Percentage
SUFFIX                953           97.843943
DEATHDATE             820           84.188912
MAIDEN                588           60.369610
ZIP                   142           14.579055
MARITAL                 1            0.102669
PREFIX                  0            0.000000
Id                      0            0.000000
BIRTHDATE               0            0.000000
FIRST                   0            0.000000
RACE                    0            0.000000
ETHNICITY               0            0.000000
LAST                    0            0.000000
GENDER                  0            0.000000
BIRTHPLACE              0            0.000000
CITY                    0            0.000000
ADDRESS                 0            0.000000
STATE                   0            0.000000
COUNTY                  0            0.000000
LAT                     0            0.000000
LON                     0            0.000000

===== ENCOUNTERS =====
                     Missing_Count  Missing_Percentage
REASONDESCRIPTION            19541           70.062027
REASONCODE                   19541           70.062027
STOP                             0            0.000000
PATIENT                          0            0.000000
Id                               0            0.000000
START                            0            0.000000
PAYER                            0            0.000000
ORGANIZATION                     0            0.000000
ENCOUNTERCLASS                   0            0.000000
CODE                             0            0.000000
BASE_ENCOUNTER_COST              0            0.000000
DESCRIPTION                      0            0.000000
PAYER_COVERAGE                   0            0.000000
TOTAL_CLAIM_COST                 0            0.000000

===== PROCEDURES =====
                   Missing_Count  Missing_Percentage
REASONCODE                 36945           77.451206
REASONDESCRIPTION          36945           77.451206
START                          0            0.000000
STOP                           0            0.000000
PATIENT                        0            0.000000
CODE                           0            0.000000
ENCOUNTER                      0            0.000000
BASE_COST                      0            0.000000
DESCRIPTION                    0            0.000000

===== PAYERS =====
                     Missing_Count  Missing_Percentage
ADDRESS                          1                10.0
STATE_HEADQUARTERED              1                10.0
CITY                             1                10.0
ZIP                              1                10.0
PHONE                            1                10.0
NAME                             0                 0.0
Id                               0                 0.0

===== ORGANIZATIONS =====
         Missing_Count  Missing_Percentage
Id                   0                 0.0
NAME                 0                 0.0
ADDRESS              0                 0.0
CITY                 0                 0.0
STATE                0                 0.0
ZIP                  0                 0.0
LAT                  0                 0.0
LON                  0                 0.0

In [13]:
for name, df in tables.items():

    print(f"\n{name.upper()}")

    for column in df.columns:

        unique = df[column].nunique()
        rows = len(df)

        if unique == rows:
            print(f"{column}: Potential Primary Key")

PATIENTS
Id: Potential Primary Key
ADDRESS: Potential Primary Key
LAT: Potential Primary Key
LON: Potential Primary Key

ENCOUNTERS
Id: Potential Primary Key

PROCEDURES

PAYERS
Id: Potential Primary Key
NAME: Potential Primary Key

ORGANIZATIONS
Id: Potential Primary Key
NAME: Potential Primary Key
ADDRESS: Potential Primary Key
CITY: Potential Primary Key
STATE: Potential Primary Key
ZIP: Potential Primary Key
LAT: Potential Primary Key
LON: Potential Primary Key

Validate Patient → Encounter

In [14]:
invalid_patients = encounters.loc[
    ~encounters["PATIENT"].isin(patients["Id"]),
    "PATIENT"
]

print("Invalid patient references:", invalid_patients.nunique())
print("Invalid encounter rows:", len(invalid_patients))

Invalid patient references: 0
Invalid encounter rows: 0

In [15]:
print("Invalid encounter rows:", len(invalid_patients))

Invalid encounter rows: 0

Validate Encounter → Procedure

In [16]:
invalid_encounters = procedures.loc[
    ~procedures["ENCOUNTER"].isin(encounters["Id"]),
    "ENCOUNTER"
]

print("Invalid encounter references:", invalid_encounters.nunique())
print("Invalid procedure rows:", len(invalid_encounters))

Invalid encounter references: 0
Invalid procedure rows: 0

Validate Encounter → Payer

In [17]:
invalid_payers = encounters.loc[
    ~encounters["PAYER"].isin(payers["Id"]),
    "PAYER"
]

print("Invalid payer references:", invalid_payers.nunique())
print("Invalid encounter rows:", len(invalid_payers))

Invalid payer references: 0
Invalid encounter rows: 0

Validate Encounter → Organization

In [18]:
invalid_organizations = encounters.loc[
    ~encounters["ORGANIZATION"].isin(organizations["Id"]),
    "ORGANIZATION"
]

print("Invalid organization references:", invalid_organizations.nunique())
print("Invalid encounter rows:", len(invalid_organizations))

Invalid organization references: 0
Invalid encounter rows: 0

Validate Procedure → Patient

In [19]:
invalid_procedure_patients = procedures.loc[
    ~procedures["PATIENT"].isin(patients["Id"]),
    "PATIENT"
]

print(
    "Invalid procedure patient references:",
    invalid_procedure_patients.nunique()
)

print(
    "Invalid procedure rows:",
    len(invalid_procedure_patients)
)

Invalid procedure patient references: 0
Invalid procedure rows: 0

Test the Direct Patient/Encounter Consistency

In [20]:
procedure_check = procedures.merge(
    encounters[["Id", "PATIENT"]],
    left_on="ENCOUNTER",
    right_on="Id",
    how="left",
    suffixes=("_procedure", "_encounter")
)

mismatches = procedure_check[
    procedure_check["PATIENT_procedure"] !=
    procedure_check["PATIENT_encounter"]
]

print("Patient/encounter mismatches:", len(mismatches))

Patient/encounter mismatches: 0

Check Whether Procedures Have Duplicate Records

In [21]:
print("Total procedure rows:", len(procedures))
print(
    "Exact duplicate rows:",
    procedures.duplicated().sum()
)

Total procedure rows: 47701
Exact duplicate rows: 0

In [22]:
procedure_key = [
    "PATIENT",
    "ENCOUNTER",
    "START",
    "STOP",
    "CODE"
]

print(
    "Duplicate logical procedure records:",
    procedures.duplicated(
        subset=procedure_key
    ).sum()
)

Duplicate logical procedure records: 0

Check Encounter IDs

In [23]:
print("Total encounters:", len(encounters))

print(
    "Unique encounter IDs:",
    encounters["Id"].nunique()
)

print(
    "Duplicate encounter IDs:",
    encounters["Id"].duplicated().sum()
)

Total encounters: 27891
Unique encounter IDs: 27891
Duplicate encounter IDs: 0

encounters.Id = Primary Key

Check Patient IDs

In [24]:
print("Total patients:", len(patients))

print(
    "Unique patient IDs:",
    patients["Id"].nunique()
)

print(
    "Duplicate patient IDs:",
    patients["Id"].duplicated().sum()
)

Total patients: 974
Unique patient IDs: 974
Duplicate patient IDs: 0

Check Payer IDs

In [25]:
print("Total payers:", len(payers))

print(
    "Unique payer IDs:",
    payers["Id"].nunique()
)

print(
    "Duplicate payer IDs:",
    payers["Id"].duplicated().sum()
)

Total payers: 10
Unique payer IDs: 10
Duplicate payer IDs: 0

Check Organization IDs

In [26]:
print("Total organizations:", len(organizations))

print(
    "Unique organization IDs:",
    organizations["Id"].nunique()
)

print(
    "Duplicate organization IDs:",
    organizations["Id"].duplicated().sum()
)

Total organizations: 1
Unique organization IDs: 1
Duplicate organization IDs: 0

Checking For Null Foreign Keys

In [27]:
foreign_key_columns = {
    "encounters.PATIENT": encounters["PATIENT"],
    "encounters.PAYER": encounters["PAYER"],
    "encounters.ORGANIZATION": encounters["ORGANIZATION"],
    "procedures.PATIENT": procedures["PATIENT"],
    "procedures.ENCOUNTER": procedures["ENCOUNTER"]
}

for name, series in foreign_key_columns.items():
    print(
        f"{name}: "
        f"{series.isna().sum()} nulls "
        f"({series.isna().mean() * 100:.2f}%)"
    )

encounters.PATIENT: 0 nulls (0.00%)
encounters.PAYER: 0 nulls (0.00%)
encounters.ORGANIZATION: 0 nulls (0.00%)
procedures.PATIENT: 0 nulls (0.00%)
procedures.ENCOUNTER: 0 nulls (0.00%)

In [28]:
invalid_patients = encounters.loc[
    ~encounters["PATIENT"].isin(patients["Id"]),
    "PATIENT"
]

print("Invalid patient references:", invalid_patients.nunique())
print("Invalid encounter rows:", len(invalid_patients))

Invalid patient references: 0
Invalid encounter rows: 0

In [29]:
invalid_encounters = procedures.loc[
    ~procedures["ENCOUNTER"].isin(encounters["Id"]),
    "ENCOUNTER"
]

print("Invalid encounter references:", invalid_encounters.nunique())
print("Invalid procedure rows:", len(invalid_encounters))

Invalid encounter references: 0
Invalid procedure rows: 0

In [30]:
invalid_payers = encounters.loc[
    ~encounters["PAYER"].isin(payers["Id"]),
    "PAYER"
]

print("Invalid payer references:", invalid_payers.nunique())
print("Invalid encounter rows:", len(invalid_payers))

Invalid payer references: 0
Invalid encounter rows: 0

In [31]:
invalid_organizations = encounters.loc[
    ~encounters["ORGANIZATION"].isin(organizations["Id"]),
    "ORGANIZATION"
]

print("Invalid organization references:", invalid_organizations.nunique())
print("Invalid encounter rows:", len(invalid_organizations))

Invalid organization references: 0
Invalid encounter rows: 0

In [32]:
procedure_check = procedures.merge(
    encounters[["Id", "PATIENT"]],
    left_on="ENCOUNTER",
    right_on="Id",
    how="left",
    suffixes=("_procedure", "_encounter")
)

mismatches = procedure_check[
    procedure_check["PATIENT_procedure"] !=
    procedure_check["PATIENT_encounter"]
]

print("Patient/encounter mismatches:", len(mismatches))

Patient/encounter mismatches: 0

In [33]:
print("Total procedure rows:", len(procedures))
print("Exact duplicate rows:", procedures.duplicated().sum())

procedure_key = [
    "PATIENT",
    "ENCOUNTER",
    "START",
    "STOP",
    "CODE"
]

print(
    "Duplicate logical procedure records:",
    procedures.duplicated(subset=procedure_key).sum()
)

Total procedure rows: 47701
Exact duplicate rows: 0
Duplicate logical procedure records: 0

In [34]:
foreign_key_columns = {
    "encounters.PATIENT": encounters["PATIENT"],
    "encounters.PAYER": encounters["PAYER"],
    "encounters.ORGANIZATION": encounters["ORGANIZATION"],
    "procedures.PATIENT": procedures["PATIENT"],
    "procedures.ENCOUNTER": procedures["ENCOUNTER"]
}

for name, series in foreign_key_columns.items():
    print(
        f"{name}: "
        f"{series.isna().sum()} nulls "
        f"({series.isna().mean() * 100:.2f}%)"
    )

encounters.PATIENT: 0 nulls (0.00%)
encounters.PAYER: 0 nulls (0.00%)
encounters.ORGANIZATION: 0 nulls (0.00%)
procedures.PATIENT: 0 nulls (0.00%)
procedures.ENCOUNTER: 0 nulls (0.00%)

In [35]:
for name, df in tables.items():

    print(f"\n===== {name.upper()} =====")

    dictionary = pd.DataFrame({
        "Column": df.columns,
        "Data_Type": df.dtypes.astype(str).values,
        "Null_Count": df.isnull().sum().values,
        "Null_Percentage": (
            df.isnull().mean() * 100
        ).round(2).values,
        "Unique_Values": [
            df[col].nunique(dropna=True)
            for col in df.columns
        ]
    })

    display(dictionary)

===== PATIENTS =====

        Column Data_Type  Null_Count  Null_Percentage  Unique_Values
0           Id       str           0             0.00            974
1    BIRTHDATE       str           0             0.00            880
2    DEATHDATE       str         820            84.19            148
3       PREFIX       str           0             0.00              3
4        FIRST       str           0             0.00            842
5         LAST       str           0             0.00            498
6       SUFFIX       str         953            97.84              3
7       MAIDEN       str         588            60.37            279
8      MARITAL       str           1             0.10              2
9         RACE       str           0             0.00              6
10   ETHNICITY       str           0             0.00              2
11      GENDER       str           0             0.00              2
12  BIRTHPLACE       str           0             0.00            297
13     ADDRESS       str           0             0.00            974
14        CITY       str           0             0.00             29
15       STATE       str           0             0.00              1
16      COUNTY       str           0             0.00              5
17         ZIP   float64         142            14.58             70
18         LAT   float64           0             0.00            974
19         LON   float64           0             0.00            974

===== ENCOUNTERS =====

                 Column Data_Type  Null_Count  Null_Percentage  Unique_Values
0                    Id       str           0             0.00          27891
1                 START       str           0             0.00          27541
2                  STOP       str           0             0.00          27765
3               PATIENT       str           0             0.00            974
4          ORGANIZATION       str           0             0.00              1
5                 PAYER       str           0             0.00             10
6        ENCOUNTERCLASS       str           0             0.00              6
7                  CODE     int64           0             0.00             45
8           DESCRIPTION       str           0             0.00             53
9   BASE_ENCOUNTER_COST   float64           0             0.00              5
10     TOTAL_CLAIM_COST   float64           0             0.00          13529
11       PAYER_COVERAGE   float64           0             0.00           5606
12           REASONCODE   float64       19541            70.06             73
13    REASONDESCRIPTION       str       19541            70.06             73

===== PROCEDURES =====

              Column Data_Type  Null_Count  Null_Percentage  Unique_Values
0              START       str           0             0.00          39251
1               STOP       str           0             0.00          42263
2            PATIENT       str           0             0.00            793
3          ENCOUNTER       str           0             0.00          14670
4               CODE     int64           0             0.00            157
5        DESCRIPTION       str           0             0.00            163
6          BASE_COST     int64           0             0.00           8268
7         REASONCODE   float64       36945            77.45             46
8  REASONDESCRIPTION       str       36945            77.45             46

===== PAYERS =====

                Column Data_Type  Null_Count  Null_Percentage  Unique_Values
0                   Id       str           0              0.0             10
1                 NAME       str           0              0.0             10
2              ADDRESS       str           1             10.0              7
3                 CITY       str           1             10.0              7
4  STATE_HEADQUARTERED       str           1             10.0              6
5                  ZIP   float64           1             10.0              7
6                PHONE       str           1             10.0              8

===== ORGANIZATIONS =====

    Column Data_Type  Null_Count  Null_Percentage  Unique_Values
0       Id       str           0              0.0              1
1     NAME       str           0              0.0              1
2  ADDRESS       str           0              0.0              1
3     CITY       str           0              0.0              1
4    STATE       str           0              0.0              1
5      ZIP     int64           0              0.0              1
6      LAT   float64           0              0.0              1
7      LON   float64           0              0.0              1

Final PK Verification

In [36]:
primary_key_candidates = {
    "patients": "Id",
    "encounters": "Id",
    "payers": "Id",
    "organizations": "Id"
}

for table_name, column in primary_key_candidates.items():

    df = tables[table_name]

    print(f"\n{table_name}.{column}")

    print("Total rows:", len(df))
    print("Unique values:", df[column].nunique())
    print("Null values:", df[column].isna().sum())
    print("Duplicate values:", df[column].duplicated().sum())
    print("Is unique:", df[column].is_unique)

patients.Id
Total rows: 974
Unique values: 974
Null values: 0
Duplicate values: 0
Is unique: True

encounters.Id
Total rows: 27891
Unique values: 27891
Null values: 0
Duplicate values: 0
Is unique: True

payers.Id
Total rows: 10
Unique values: 10
Null values: 0
Duplicate values: 0
Is unique: True

organizations.Id
Total rows: 1
Unique values: 1
Null values: 0
Duplicate values: 0
Is unique: True

In [37]:
procedure_grain = procedures.groupby(
    ["PATIENT", "ENCOUNTER", "START", "STOP", "CODE"]
).size()

print(procedure_grain.describe())

count    47701.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
dtype: float64

In [38]:
print(
    "Maximum records sharing the same logical key:",
    procedure_grain.max()
)

Maximum records sharing the same logical key: 1

The procedures dataset does not contain an explicit primary-key field. A composite business key consisting of patient, encounter, timestamps, and procedure code was assessed for uniqueness and produced no duplicate records.

In [39]:
for name, df in tables.items():

    print(f"\n{'=' * 60}")
    print(name.upper())
    print(f"{'=' * 60}")

    profile = pd.DataFrame({
        "Data_Type": df.dtypes.astype(str),
        "Null_Count": df.isnull().sum(),
        "Null_Percentage": (
            df.isnull().mean() * 100
        ).round(2),
        "Unique_Values": [
            df[col].nunique(dropna=True)
            for col in df.columns
        ]
    })

    print(profile.to_string())

============================================================
PATIENTS
============================================================
           Data_Type  Null_Count  Null_Percentage  Unique_Values
Id               str           0             0.00            974
BIRTHDATE        str           0             0.00            880
DEATHDATE        str         820            84.19            148
PREFIX           str           0             0.00              3
FIRST            str           0             0.00            842
LAST             str           0             0.00            498
SUFFIX           str         953            97.84              3
MAIDEN           str         588            60.37            279
MARITAL          str           1             0.10              2
RACE             str           0             0.00              6
ETHNICITY        str           0             0.00              2
GENDER           str           0             0.00              2
BIRTHPLACE       str           0             0.00            297
ADDRESS          str           0             0.00            974
CITY             str           0             0.00             29
STATE            str           0             0.00              1
COUNTY           str           0             0.00              5
ZIP          float64         142            14.58             70
LAT          float64           0             0.00            974
LON          float64           0             0.00            974

============================================================
ENCOUNTERS
============================================================
                    Data_Type  Null_Count  Null_Percentage  Unique_Values
Id                        str           0             0.00          27891
START                     str           0             0.00          27541
STOP                      str           0             0.00          27765
PATIENT                   str           0             0.00            974
ORGANIZATION              str           0             0.00              1
PAYER                     str           0             0.00             10
ENCOUNTERCLASS            str           0             0.00              6
CODE                    int64           0             0.00             45
DESCRIPTION               str           0             0.00             53
BASE_ENCOUNTER_COST   float64           0             0.00              5
TOTAL_CLAIM_COST      float64           0             0.00          13529
PAYER_COVERAGE        float64           0             0.00           5606
REASONCODE            float64       19541            70.06             73
REASONDESCRIPTION         str       19541            70.06             73

============================================================
PROCEDURES
============================================================
                  Data_Type  Null_Count  Null_Percentage  Unique_Values
START                   str           0             0.00          39251
STOP                    str           0             0.00          42263
PATIENT                 str           0             0.00            793
ENCOUNTER               str           0             0.00          14670
CODE                  int64           0             0.00            157
DESCRIPTION             str           0             0.00            163
BASE_COST             int64           0             0.00           8268
REASONCODE          float64       36945            77.45             46
REASONDESCRIPTION       str       36945            77.45             46

============================================================
PAYERS
============================================================
                    Data_Type  Null_Count  Null_Percentage  Unique_Values
Id                        str           0              0.0             10
NAME                      str           0              0.0             10
ADDRESS                   str           1             10.0              7
CITY                      str           1             10.0              7
STATE_HEADQUARTERED       str           1             10.0              6
ZIP                   float64           1             10.0              7
PHONE                     str           1             10.0              8

============================================================
ORGANIZATIONS
============================================================
        Data_Type  Null_Count  Null_Percentage  Unique_Values
Id            str           0              0.0              1
NAME          str           0              0.0              1
ADDRESS       str           0              0.0              1
CITY          str           0              0.0              1
STATE         str           0              0.0              1
ZIP         int64           0              0.0              1
LAT       float64           0              0.0              1
LON       float64           0              0.0              1

In [40]:
date_columns = {
    "patients": ["BIRTHDATE", "DEATHDATE"],
    "encounters": ["START", "STOP"],
    "procedures": ["START", "STOP"]
}

for table_name, columns in date_columns.items():

    print(f"\n===== {table_name.upper()} =====")

    for column in columns:
        print(
            f"{column}: "
            f"{tables[table_name][column].dtype}"
        )

===== PATIENTS =====
BIRTHDATE: str
DEATHDATE: str

===== ENCOUNTERS =====
START: str
STOP: str

===== PROCEDURES =====
START: str
STOP: str

In [41]:
# ============================================================
# STAGE 3 — DATA CLEANING & PREPARATION
# STEP 3.1 — CREATE CLEANING WORKING COPIES
# ============================================================

# Create independent working copies of the raw datasets
patients_clean = patients.copy()
encounters_clean = encounters.copy()
procedures_clean = procedures.copy()
payers_clean = payers.copy()
organizations_clean = organizations.copy()

# Store cleaned working tables in a dictionary
clean_tables = {
    "patients": patients_clean,
    "encounters": encounters_clean,
    "procedures": procedures_clean,
    "payers": payers_clean,
    "organizations": organizations_clean
}

print("Cleaning working copies created successfully.")

Cleaning working copies created successfully.

In [42]:
clean_tables = {
    "patients": patients_clean,
    "encounters": encounters_clean,
    "procedures": procedures_clean,
    "payers": payers_clean,
    "organizations": organizations_clean
}

In [43]:
for name, df in clean_tables.items():
    print(f"{name}_clean: {df.shape}")

patients_clean: (974, 20)
encounters_clean: (27891, 14)
procedures_clean: (47701, 9)
payers_clean: (10, 7)
organizations_clean: (1, 8)

In [44]:
print(
    "Raw patients:",
    patients.shape
)

print(
    "Clean patients:",
    patients_clean.shape
)

Raw patients: (974, 20)
Clean patients: (974, 20)

In [45]:
print("Raw BIRTHDATE type:", patients["BIRTHDATE"].dtype)
print("Clean BIRTHDATE type:", patients_clean["BIRTHDATE"].dtype)

Raw BIRTHDATE type: str
Clean BIRTHDATE type: str

In [46]:
# ============================================================================
# STEP 3.13.1 — Missing-Value Audit
# ============================================================================

datasets = {
    "patients_clean": patients_clean,
    "encounters_clean": encounters_clean,
    "procedures_clean": procedures_clean,
    "payers_clean": payers_clean,
    "organizations_clean": organizations_clean
}

missing_value_audit = []

for name, data in datasets.items():

    total_rows = len(data)

    for column in data.columns:

        missing_count = data[column].isna().sum()

        missing_percentage = (
            missing_count / total_rows * 100
            if total_rows > 0 else 0
        )

        missing_value_audit.append({
            "Dataset": name,
            "Column": column,
            "Total_Rows": total_rows,
            "Missing_Count": missing_count,
            "Missing_Percentage": missing_percentage
        })

missing_value_audit = pd.DataFrame(missing_value_audit)

# Show only columns containing missing values
missing_value_audit = (
    missing_value_audit[
        missing_value_audit["Missing_Count"] > 0
    ]
    .sort_values(
        ["Dataset", "Missing_Count"],
        ascending=[True, False]
    )
    .reset_index(drop=True)
)

missing_value_audit

,Dataset,Column,Total_Rows,Missing_Count,Missing_Percentage
0,encounters_clean,REASONCODE,27891,19541,70.062027
1,encounters_clean,REASONDESCRIPTION,27891,19541,70.062027
2,patients_clean,SUFFIX,974,953,97.843943
3,patients_clean,DEATHDATE,974,820,84.188912
4,patients_clean,MAIDEN,974,588,60.369610
5,patients_clean,ZIP,974,142,14.579055
6,patients_clean,MARITAL,974,1,0.102669
7,payers_clean,ADDRESS,10,1,10.000000
8,payers_clean,CITY,10,1,10.000000
9,payers_clean,STATE_HEADQUARTERED,10,1,10.000000
10,payers_clean,ZIP,10,1,10.000000
11,payers_clean,PHONE,10,1,10.000000
12,procedures_clean,REASONCODE,47701,36945,77.451206
13,procedures_clean,REASONDESCRIPTION,47701,36945,77.451206

In [47]:
# Summary of missing values by dataset

missing_summary = (
    missing_value_audit
    .groupby("Dataset", as_index=False)
    .agg(
        Columns_With_Missing_Values=("Column", "count"),
        Total_Missing_Values=("Missing_Count", "sum")
    )
)

missing_summary

            Dataset  Columns_With_Missing_Values  Total_Missing_Values
0  encounters_clean                            2                 39082
1    patients_clean                            5                  2504
2      payers_clean                            5                     5
3  procedures_clean                            2                 73890

In [48]:
# Complete missing-value audit

print("Missing-value audit completed.")
print(f"Datasets reviewed: {len(datasets)}")
print(f"Columns containing missing values: {len(missing_value_audit)}")
print(
    f"Total missing values identified: "
    f"{missing_value_audit['Missing_Count'].sum():,}"
)

Missing-value audit completed.
Datasets reviewed: 5
Columns containing missing values: 14
Total missing values identified: 115,481

In [49]:
# ============================================================================
# STEP 3.13.3 — Missing-Value Treatment
# ============================================================================

# Create explicit copies before treatment
patients_clean = patients_clean.copy()
encounters_clean = encounters_clean.copy()
procedures_clean = procedures_clean.copy()
payers_clean = payers_clean.copy()
organizations_clean = organizations_clean.copy()


# ---------------------------------------------------------------------------
# CATEGORICAL / DESCRIPTIVE FIELDS
# ---------------------------------------------------------------------------

# Patient marital status
patients_clean["MARITAL"] = patients_clean["MARITAL"].fillna("Unknown")


# Payer descriptive fields
payer_missing_columns = [
    "ADDRESS",
    "CITY",
    "STATE_HEADQUARTERED",
    "ZIP",
    "PHONE"
]

for column in payer_missing_columns:
    payers_clean[column] = payers_clean[column].fillna("Unknown")


print("Missing-value treatment applied.")

Missing-value treatment applied.

In [50]:
# ============================================================================
# STEP 3.13.4 — Post-Treatment Validation
# ============================================================================

datasets_after_treatment = {
    "patients_clean": patients_clean,
    "encounters_clean": encounters_clean,
    "procedures_clean": procedures_clean,
    "payers_clean": payers_clean,
    "organizations_clean": organizations_clean
}

post_treatment_missing = []

for name, data in datasets_after_treatment.items():

    for column in data.columns:

        missing_count = data[column].isna().sum()

        if missing_count > 0:
            post_treatment_missing.append({
                "Dataset": name,
                "Column": column,
                "Missing_Count": missing_count,
                "Missing_Percentage": round(
                    missing_count / len(data) * 100, 2
                )
            })

post_treatment_missing = (
    pd.DataFrame(post_treatment_missing)
    .sort_values(["Dataset", "Missing_Count"], ascending=[True, False])
    .reset_index(drop=True)
)

post_treatment_missing

            Dataset             Column  Missing_Count  Missing_Percentage
0  encounters_clean         REASONCODE          19541               70.06
1  encounters_clean  REASONDESCRIPTION          19541               70.06
2    patients_clean             SUFFIX            953               97.84
3    patients_clean          DEATHDATE            820               84.19
4    patients_clean             MAIDEN            588               60.37
5    patients_clean                ZIP            142               14.58
6  procedures_clean         REASONCODE          36945               77.45
7  procedures_clean  REASONDESCRIPTION          36945               77.45

In [51]:
# ============================================================================
# STEP 3.13.5 — Row-Count Integrity Check
# ============================================================================

expected_row_counts = {
    "patients_clean": 974,
    "encounters_clean": 27891,
    "procedures_clean": 47701,
    "payers_clean": 10,
    "organizations_clean": 1
}

row_count_check = []

for name, expected_count in expected_row_counts.items():

    actual_count = len(datasets_after_treatment[name])

    row_count_check.append({
        "Dataset": name,
        "Expected_Rows": expected_count,
        "Actual_Rows": actual_count,
        "Status": "PASS" if actual_count == expected_count else "FAIL"
    })

row_count_check = pd.DataFrame(row_count_check)

row_count_check

               Dataset  Expected_Rows  Actual_Rows Status
0       patients_clean            974          974   PASS
1     encounters_clean          27891        27891   PASS
2     procedures_clean          47701        47701   PASS
3         payers_clean             10           10   PASS
4  organizations_clean              1            1   PASS

In [52]:
# ============================================================================
# STEP 3.13.6 — Missing-Value Treatment Log
# ============================================================================

missing_treatment_log = pd.DataFrame([
    ["encounters_clean", "REASONCODE", 70.06, "Keep missing",
     "Reason information is unavailable for many encounters; no imputation performed."],

    ["encounters_clean", "REASONDESCRIPTION", 70.06, "Keep missing",
     "Reason information is unavailable for many encounters; no imputation performed."],

    ["patients_clean", "SUFFIX", 97.84, "Keep missing",
     "Optional name field; missingness does not affect analysis."],

    ["patients_clean", "DEATHDATE", 84.19, "Keep missing",
     "Missing death date is analytically meaningful and must not be fabricated."],

    ["patients_clean", "AGE_AT_DEATH", 84.19, "Keep missing",
     "Only applicable to patients with a recorded death date."],

    ["patients_clean", "AGE_GROUP", 84.19, "Keep missing",
     "Derived death-related age grouping; no value assigned without death information."],

    ["patients_clean", "AGE_GROUP_AT_DEATH", 84.19, "Keep missing",
     "Only applicable to patients with a recorded death date."],

    ["patients_clean", "MAIDEN", 60.37, "Keep missing",
     "Optional demographic/name field."],

    ["patients_clean", "ZIP", 14.58, "Keep missing",
     "Geographic value unavailable; no value fabricated."],

    ["patients_clean", "MARITAL", 0.10, "Replace with Unknown",
     "Categorical field with one missing observation."],

    ["payers_clean", "ADDRESS", 10.00, "Replace with Unknown",
     "Descriptive payer field; unavailable value retained as Unknown."],

    ["payers_clean", "CITY", 10.00, "Replace with Unknown",
     "Descriptive payer field; unavailable value retained as Unknown."],

    ["payers_clean", "STATE_HEADQUARTERED", 10.00, "Replace with Unknown",
     "Descriptive payer field; unavailable value retained as Unknown."],

    ["payers_clean", "ZIP", 10.00, "Replace with Unknown",
     "Descriptive payer field; unavailable value retained as Unknown."],

    ["payers_clean", "PHONE", 10.00, "Replace with Unknown",
     "Descriptive payer field; unavailable value retained as Unknown."],

    ["procedures_clean", "REASONCODE", 77.45, "Keep missing",
     "Procedure reason is unavailable for many records; no clinical value fabricated."],

    ["procedures_clean", "REASONDESCRIPTION", 77.45, "Keep missing",
     "Procedure reason is unavailable for many records; no clinical value fabricated."]
], columns=[
    "Dataset",
    "Column",
    "Original_Missing_Percentage",
    "Treatment",
    "Justification"
])

missing_treatment_log

,Dataset,Column,Original_Missing_Percentage,Treatment,Justification
0,encounters_clean,REASONCODE,70.06,Keep missing,Reason information is unavailable for many enc...
1,encounters_clean,REASONDESCRIPTION,70.06,Keep missing,Reason information is unavailable for many enc...
2,patients_clean,SUFFIX,97.84,Keep missing,Optional name field; missingness does not affe...
3,patients_clean,DEATHDATE,84.19,Keep missing,Missing death date is analytically meaningful ...
4,patients_clean,AGE_AT_DEATH,84.19,Keep missing,Only applicable to patients with a recorded de...
5,patients_clean,AGE_GROUP,84.19,Keep missing,Derived death-related age grouping; no value a...
6,patients_clean,AGE_GROUP_AT_DEATH,84.19,Keep missing,Only applicable to patients with a recorded de...
7,patients_clean,MAIDEN,60.37,Keep missing,Optional demographic/name field.
8,patients_clean,ZIP,14.58,Keep missing,Geographic value unavailable; no value fabrica...
9,patients_clean,MARITAL,0.10,Replace with Unknown,Categorical field with one missing observation.
10,payers_clean,ADDRESS,10.00,Replace with Unknown,Descriptive payer field; unavailable value ret...
11,payers_clean,CITY,10.00,Replace with Unknown,Descriptive payer field; unavailable value ret...
12,payers_clean,STATE_HEADQUARTERED,10.00,Replace with Unknown,Descriptive payer field; unavailable value ret...
13,payers_clean,ZIP,10.00,Replace with Unknown,Descriptive payer field; unavailable value ret...
14,payers_clean,PHONE,10.00,Replace with Unknown,Descriptive payer field; unavailable value ret...
15,procedures_clean,REASONCODE,77.45,Keep missing,Procedure reason is unavailable for many recor...
16,procedures_clean,REASONDESCRIPTION,77.45,Keep missing,Procedure reason is unavailable for many recor...

In [53]:
# Show the date-related columns currently available
for df_name, df in {
    "patients_clean": patients_clean,
    "encounters_clean": encounters_clean,
    "procedures_clean": procedures_clean
}.items():
    print(f"\n{df_name}")
    print([
        col for col in df.columns
        if any(x in col.upper() for x in ["DATE", "TIME", "START", "STOP"])
    ])

patients_clean
['BIRTHDATE', 'DEATHDATE']

encounters_clean
['START', 'STOP']

procedures_clean
['START', 'STOP']

In [54]:
for df_name, df in {
    "patients_clean": patients_clean,
    "encounters_clean": encounters_clean,
    "procedures_clean": procedures_clean
}.items():

    print(f"\n{df_name}")
    print(df[[
        col for col in df.columns
        if any(x in col.upper() for x in ["DATE", "TIME", "START", "STOP"])
    ]].dtypes)

patients_clean
BIRTHDATE    str
DEATHDATE    str
dtype: object

encounters_clean
START    str
STOP     str
dtype: object

procedures_clean
START    str
STOP     str
dtype: object

In [55]:
# ============================================================
# STEP 3.13 — STANDARDIZE DATE/TIME COLUMNS
# ============================================================

# Patient dates
patients_clean["BIRTHDATE"] = pd.to_datetime(
    patients_clean["BIRTHDATE"],
    errors="coerce"
)

patients_clean["DEATHDATE"] = pd.to_datetime(
    patients_clean["DEATHDATE"],
    errors="coerce"
)

# Encounter dates
encounters_clean["START"] = pd.to_datetime(
    encounters_clean["START"],
    errors="coerce"
)

encounters_clean["STOP"] = pd.to_datetime(
    encounters_clean["STOP"],
    errors="coerce"
)

# Procedure dates
procedures_clean["START"] = pd.to_datetime(
    procedures_clean["START"],
    errors="coerce"
)

procedures_clean["STOP"] = pd.to_datetime(
    procedures_clean["STOP"],
    errors="coerce"
)

print("Step 3.13 — Date/time columns converted successfully.")

Step 3.13 — Date/time columns converted successfully.

In [56]:
# ============================================================
# STEP 3.14 — ANALYTICAL DATE FEATURES
# ============================================================

# ------------------------------------------------------------
# 1. PATIENT DATE FEATURES
# ------------------------------------------------------------

patients_clean["Birth_Year"] = patients_clean["BIRTHDATE"].dt.year
patients_clean["Birth_Month"] = patients_clean["BIRTHDATE"].dt.month
patients_clean["Birth_Month_Name"] = patients_clean["BIRTHDATE"].dt.month_name()
patients_clean["Birth_Quarter"] = patients_clean["BIRTHDATE"].dt.quarter

patients_clean["Death_Year"] = patients_clean["DEATHDATE"].dt.year
patients_clean["Death_Month"] = patients_clean["DEATHDATE"].dt.month
patients_clean["Death_Month_Name"] = patients_clean["DEATHDATE"].dt.month_name()
patients_clean["Death_Quarter"] = patients_clean["DEATHDATE"].dt.quarter


# ------------------------------------------------------------
# 2. ENCOUNTER DATE FEATURES
# ------------------------------------------------------------

encounters_clean["Encounter_Year"] = encounters_clean["START"].dt.year
encounters_clean["Encounter_Month"] = encounters_clean["START"].dt.month
encounters_clean["Encounter_Month_Name"] = encounters_clean["START"].dt.month_name()
encounters_clean["Encounter_Quarter"] = encounters_clean["START"].dt.quarter

encounters_clean["Encounter_Year_Month"] = (
    encounters_clean["START"].dt.to_period("M").astype(str)
)

encounters_clean["Encounter_Day"] = encounters_clean["START"].dt.day
encounters_clean["Encounter_Day_Name"] = encounters_clean["START"].dt.day_name()

encounters_clean["Encounter_Week"] = (
    encounters_clean["START"].dt.isocalendar().week.astype("Int64")
)


# ------------------------------------------------------------
# 3. PROCEDURE DATE FEATURES
# ------------------------------------------------------------

procedures_clean["Procedure_Year"] = procedures_clean["START"].dt.year
procedures_clean["Procedure_Month"] = procedures_clean["START"].dt.month
procedures_clean["Procedure_Month_Name"] = procedures_clean["START"].dt.month_name()
procedures_clean["Procedure_Quarter"] = procedures_clean["START"].dt.quarter

procedures_clean["Procedure_Year_Month"] = (
    procedures_clean["START"].dt.to_period("M").astype(str)
)

procedures_clean["Procedure_Day"] = procedures_clean["START"].dt.day
procedures_clean["Procedure_Day_Name"] = procedures_clean["START"].dt.day_name()

procedures_clean["Procedure_Week"] = (
    procedures_clean["START"].dt.isocalendar().week.astype("Int64")
)

print("Step 3.14 — Analytical date features created successfully.")

C:\Users\Olayinka\AppData\Local\Temp\ipykernel_1864\3372227818.py:30: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  encounters_clean["START"].dt.to_period("M").astype(str)
C:\Users\Olayinka\AppData\Local\Temp\ipykernel_1864\3372227818.py:51: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  procedures_clean["START"].dt.to_period("M").astype(str)

Step 3.14 — Analytical date features created successfully.

In [57]:
# ============================================================
# STEP 3.14 — ANALYTICAL DATE FEATURES
# ============================================================

# ------------------------------------------------------------
# 1. PATIENT DATE FEATURES
# ------------------------------------------------------------

patients_clean["Birth_Year"] = patients_clean["BIRTHDATE"].dt.year

patients_clean["Birth_Month"] = patients_clean["BIRTHDATE"].dt.month

patients_clean["Birth_Month_Name"] = (
    patients_clean["BIRTHDATE"].dt.month_name()
)

patients_clean["Birth_Quarter"] = (
    patients_clean["BIRTHDATE"].dt.quarter
)

# Death-related features
patients_clean["Death_Year"] = patients_clean["DEATHDATE"].dt.year

patients_clean["Death_Month"] = patients_clean["DEATHDATE"].dt.month

patients_clean["Death_Month_Name"] = (
    patients_clean["DEATHDATE"].dt.month_name()
)

patients_clean["Death_Quarter"] = (
    patients_clean["DEATHDATE"].dt.quarter
)


# ------------------------------------------------------------
# 2. ENCOUNTER DATE FEATURES
# ------------------------------------------------------------

encounters_clean["Encounter_Year"] = encounters_clean["START"].dt.year

encounters_clean["Encounter_Month"] = encounters_clean["START"].dt.month

encounters_clean["Encounter_Month_Name"] = (
    encounters_clean["START"].dt.month_name()
)

encounters_clean["Encounter_Quarter"] = (
    encounters_clean["START"].dt.quarter
)

encounters_clean["Encounter_Year_Month"] = (
    encounters_clean["START"].dt.to_period("M").astype(str)
)

encounters_clean["Encounter_Day"] = (
    encounters_clean["START"].dt.day
)

encounters_clean["Encounter_Day_Name"] = (
    encounters_clean["START"].dt.day_name()
)

encounters_clean["Encounter_Week"] = (
    encounters_clean["START"].dt.isocalendar().week.astype("Int64")
)


# ------------------------------------------------------------
# 3. PROCEDURE DATE FEATURES
# ------------------------------------------------------------

procedures_clean["Procedure_Year"] = procedures_clean["START"].dt.year

procedures_clean["Procedure_Month"] = procedures_clean["START"].dt.month

procedures_clean["Procedure_Month_Name"] = (
    procedures_clean["START"].dt.month_name()
)

procedures_clean["Procedure_Quarter"] = (
    procedures_clean["START"].dt.quarter
)

procedures_clean["Procedure_Year_Month"] = (
    procedures_clean["START"].dt.to_period("M").astype(str)
)

procedures_clean["Procedure_Day"] = (
    procedures_clean["START"].dt.day
)

procedures_clean["Procedure_Day_Name"] = (
    procedures_clean["START"].dt.day_name()
)

procedures_clean["Procedure_Week"] = (
    procedures_clean["START"].dt.isocalendar().week.astype("Int64")
)


print("Step 3.14 — Analytical date features created successfully.")

C:\Users\Olayinka\AppData\Local\Temp\ipykernel_1864\791996171.py:52: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  encounters_clean["START"].dt.to_period("M").astype(str)
C:\Users\Olayinka\AppData\Local\Temp\ipykernel_1864\791996171.py:85: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  procedures_clean["START"].dt.to_period("M").astype(str)

Step 3.14 — Analytical date features created successfully.

In [58]:
# ============================================================
# STEP 3.14 — FEATURE VALIDATION
# ============================================================

print("PATIENT DATE FEATURES")
print([
    col for col in patients_clean.columns
    if col.startswith(("Birth_", "Death_"))
])

print("\nENCOUNTER DATE FEATURES")
print([
    col for col in encounters_clean.columns
    if col.startswith("Encounter_")
])

print("\nPROCEDURE DATE FEATURES")
print([
    col for col in procedures_clean.columns
    if col.startswith("Procedure_")
])

PATIENT DATE FEATURES
['Birth_Year', 'Birth_Month', 'Birth_Month_Name', 'Birth_Quarter', 'Death_Year', 'Death_Month', 'Death_Month_Name', 'Death_Quarter']

ENCOUNTER DATE FEATURES
['Encounter_Year', 'Encounter_Month', 'Encounter_Month_Name', 'Encounter_Quarter', 'Encounter_Year_Month', 'Encounter_Day', 'Encounter_Day_Name', 'Encounter_Week']

PROCEDURE DATE FEATURES
['Procedure_Year', 'Procedure_Month', 'Procedure_Month_Name', 'Procedure_Quarter', 'Procedure_Year_Month', 'Procedure_Day', 'Procedure_Day_Name', 'Procedure_Week']

In [59]:
print("\nPATIENTS")
display(
    patients_clean[
        [
            "BIRTHDATE",
            "Birth_Year",
            "Birth_Month",
            "Birth_Month_Name",
            "Birth_Quarter",
            "DEATHDATE",
            "Death_Year",
            "Death_Month",
            "Death_Month_Name",
            "Death_Quarter"
        ]
    ].head()
)

print("\nENCOUNTERS")
display(
    encounters_clean[
        [
            "START",
            "STOP",
            "Encounter_Year",
            "Encounter_Month",
            "Encounter_Month_Name",
            "Encounter_Quarter",
            "Encounter_Year_Month",
            "Encounter_Day",
            "Encounter_Day_Name",
            "Encounter_Week"
        ]
    ].head()
)

print("\nPROCEDURES")
display(
    procedures_clean[
        [
            "START",
            "STOP",
            "Procedure_Year",
            "Procedure_Month",
            "Procedure_Month_Name",
            "Procedure_Quarter",
            "Procedure_Year_Month",
            "Procedure_Day",
            "Procedure_Day_Name",
            "Procedure_Week"
        ]
    ].head()
)

PATIENTS

,BIRTHDATE,Birth_Year,Birth_Month,Birth_Month_Name,Birth_Quarter,DEATHDATE,Death_Year,Death_Month,Death_Month_Name,Death_Quarter
0,1977-03-19,1977,3,March,1,NaT,NaN,NaN,NaN,NaN
1,1940-02-19,1940,2,February,1,NaT,NaN,NaN,NaN,NaN
2,1958-06-04,1958,6,June,2,NaT,NaN,NaN,NaN,NaN
3,1928-12-25,1928,12,December,4,2017-09-29,2017.0,9.0,September,3.0
4,1928-12-25,1928,12,December,4,2014-02-23,2014.0,2.0,February,1.0

ENCOUNTERS

,START,STOP,Encounter_Year,Encounter_Month,Encounter_Month_Name,Encounter_Quarter,Encounter_Year_Month,Encounter_Day,Encounter_Day_Name,Encounter_Week
0,2011-01-02 09:26:36+00:00,2011-01-02 12:58:36+00:00,2011,1,January,1,2011-01,2,Sunday,52
1,2011-01-03 05:44:39+00:00,2011-01-03 06:01:42+00:00,2011,1,January,1,2011-01,3,Monday,1
2,2011-01-03 14:32:11+00:00,2011-01-03 14:47:11+00:00,2011,1,January,1,2011-01,3,Monday,1
3,2011-01-03 16:24:45+00:00,2011-01-03 16:39:45+00:00,2011,1,January,1,2011-01,3,Monday,1
4,2011-01-03 17:36:53+00:00,2011-01-03 17:51:53+00:00,2011,1,January,1,2011-01,3,Monday,1

PROCEDURES

,START,STOP,Procedure_Year,Procedure_Month,Procedure_Month_Name,Procedure_Quarter,Procedure_Year_Month,Procedure_Day,Procedure_Day_Name,Procedure_Week
0,2011-01-02 09:26:36+00:00,2011-01-02 12:58:36+00:00,2011,1,January,1,2011-01,2,Sunday,52
1,2011-01-03 05:44:39+00:00,2011-01-03 06:01:42+00:00,2011,1,January,1,2011-01,3,Monday,1
2,2011-01-04 14:49:55+00:00,2011-01-04 15:04:55+00:00,2011,1,January,1,2011-01,4,Tuesday,1
3,2011-01-05 04:02:09+00:00,2011-01-05 04:17:09+00:00,2011,1,January,1,2011-01,5,Wednesday,1
4,2011-01-05 12:58:36+00:00,2011-01-05 16:42:36+00:00,2011,1,January,1,2011-01,5,Wednesday,1

In [60]:
# =====================================================
# — PROCEDURE DURATION
# ============================================================

# Calculate procedure duration in minutes
procedures_clean["PROCEDURE_DURATION_MIN"] = (
    procedures_clean["STOP"] - procedures_clean["START"]
).dt.total_seconds() / 60


# Calculate procedure duration in hours
procedures_clean["PROCEDURE_DURATION_HOURS"] = (
    procedures_clean["PROCEDURE_DURATION_MIN"] / 60
)


# Calculate procedure duration in days
procedures_clean["PROCEDURE_DURATION_DAYS"] = (
    procedures_clean["PROCEDURE_DURATION_HOURS"] / 24
)


# Create a duration validation flag
procedures_clean["PROCEDURE_DURATION_FLAG"] = "Valid"

procedures_clean.loc[
    procedures_clean["PROCEDURE_DURATION_MIN"] < 0,
    "PROCEDURE_DURATION_FLAG"
] = "Negative Duration"

procedures_clean.loc[
    procedures_clean["PROCEDURE_DURATION_MIN"].isna(),
    "PROCEDURE_DURATION_FLAG"
] = "Missing Duration"


# Display results
print("Step 3.5 — Procedure duration created successfully.")

display(
    procedures_clean[
        [
            "START",
            "STOP",
            "PROCEDURE_DURATION_MIN",
            "PROCEDURE_DURATION_HOURS",
            "PROCEDURE_DURATION_DAYS",
            "PROCEDURE_DURATION_FLAG"
        ]
    ].head()
)

Step 3.5 — Procedure duration created successfully.

,START,STOP,PROCEDURE_DURATION_MIN,PROCEDURE_DURATION_HOURS,PROCEDURE_DURATION_DAYS,PROCEDURE_DURATION_FLAG
0,2011-01-02 09:26:36+00:00,2011-01-02 12:58:36+00:00,212.00,3.533333,0.147222,Valid
1,2011-01-03 05:44:39+00:00,2011-01-03 06:01:42+00:00,17.05,0.284167,0.011840,Valid
2,2011-01-04 14:49:55+00:00,2011-01-04 15:04:55+00:00,15.00,0.250000,0.010417,Valid
3,2011-01-05 04:02:09+00:00,2011-01-05 04:17:09+00:00,15.00,0.250000,0.010417,Valid
4,2011-01-05 12:58:36+00:00,2011-01-05 16:42:36+00:00,224.00,3.733333,0.155556,Valid

In [61]:
# ============================================================
# VALIDATION
# ============================================================

print("Total procedures:", len(procedures_clean))

print(
    "Missing procedure duration:",
    procedures_clean["PROCEDURE_DURATION_MIN"].isna().sum()
)

print(
    "Negative procedure duration:",
    (
        procedures_clean["PROCEDURE_DURATION_MIN"] < 0
    ).sum()
)

print(
    "Procedures longer than 7 days:",
    (
        procedures_clean["PROCEDURE_DURATION_DAYS"] > 7
    ).sum()
)

print("\nDuration flag distribution:")
display(
    procedures_clean["PROCEDURE_DURATION_FLAG"]
    .value_counts(dropna=False)
)

Total procedures: 47701
Missing procedure duration: 0
Negative procedure duration: 0
Procedures longer than 7 days: 1

Duration flag distribution:

PROCEDURE_DURATION_FLAG
Valid    47701
Name: count, dtype: int64

In [62]:
print("ENCOUNTERS:")
print(encounters_clean.columns.tolist())

print("\nPROCEDURES:")
print(procedures_clean.columns.tolist())

ENCOUNTERS:
['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION', 'Encounter_Year', 'Encounter_Month', 'Encounter_Month_Name', 'Encounter_Quarter', 'Encounter_Year_Month', 'Encounter_Day', 'Encounter_Day_Name', 'Encounter_Week']

PROCEDURES:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION', 'Procedure_Year', 'Procedure_Month', 'Procedure_Month_Name', 'Procedure_Quarter', 'Procedure_Year_Month', 'Procedure_Day', 'Procedure_Day_Name', 'Procedure_Week', 'PROCEDURE_DURATION_MIN', 'PROCEDURE_DURATION_HOURS', 'PROCEDURE_DURATION_DAYS', 'PROCEDURE_DURATION_FLAG']

In [63]:
print(
    "Encounter duration columns:",
    [
        col for col in encounters_clean.columns
        if "DURATION" in col.upper()
    ]
)

print(
    "Procedure duration columns:",
    [
        col for col in procedures_clean.columns
        if "DURATION" in col.upper()
    ]
)

Encounter duration columns: []
Procedure duration columns: ['PROCEDURE_DURATION_MIN', 'PROCEDURE_DURATION_HOURS', 'PROCEDURE_DURATION_DAYS', 'PROCEDURE_DURATION_FLAG']

In [64]:
# ============================================================
# STEP 3.5 — ENCOUNTER DURATION FEATURE ENGINEERING
# ============================================================

print("=" * 70)
print("STEP 3.5 — ENCOUNTER DURATION FEATURE ENGINEERING")
print("=" * 70)


# ------------------------------------------------------------
# 1. ENSURE START AND STOP ARE DATETIME
# ------------------------------------------------------------

encounters_clean["START"] = pd.to_datetime(
    encounters_clean["START"],
    errors="coerce"
)

encounters_clean["STOP"] = pd.to_datetime(
    encounters_clean["STOP"],
    errors="coerce"
)


# ------------------------------------------------------------
# 2. CALCULATE ENCOUNTER DURATION
# ------------------------------------------------------------

encounters_clean["ENCOUNTER_DURATION_MIN"] = (
    encounters_clean["STOP"] - encounters_clean["START"]
).dt.total_seconds() / 60


encounters_clean["ENCOUNTER_DURATION_HOURS"] = (
    encounters_clean["ENCOUNTER_DURATION_MIN"] / 60
)


encounters_clean["DURATION_DAYS"] = (
    encounters_clean["ENCOUNTER_DURATION_HOURS"] / 24
)


# ------------------------------------------------------------
# 3. CREATE DURATION QUALITY FLAG
# ------------------------------------------------------------

encounters_clean["DURATION_FLAG"] = "Normal"


# Missing duration
encounters_clean.loc[
    encounters_clean["ENCOUNTER_DURATION_HOURS"].isna(),
    "DURATION_FLAG"
] = "Missing"


# Negative duration
encounters_clean.loc[
    encounters_clean["ENCOUNTER_DURATION_HOURS"] < 0,
    "DURATION_FLAG"
] = "Negative"


# Zero duration
encounters_clean.loc[
    encounters_clean["ENCOUNTER_DURATION_HOURS"] == 0,
    "DURATION_FLAG"
] = "Zero"


# Duration greater than 7 days
encounters_clean.loc[
    encounters_clean["DURATION_DAYS"] > 7,
    "DURATION_FLAG"
] = "Over 7 Days"


# ------------------------------------------------------------
# 4. VALIDATION OUTPUT
# ------------------------------------------------------------

print("\nEncounter duration columns created:")

print([
    col
    for col in encounters_clean.columns
    if "DURATION" in col.upper()
])


print("\nDuration flag distribution:")

print(
    encounters_clean["DURATION_FLAG"]
    .value_counts(dropna=False)
)


print("\nStep 3.5 — Encounter duration features created successfully.")

======================================================================
STEP 3.5 — ENCOUNTER DURATION FEATURE ENGINEERING
======================================================================

Encounter duration columns created:
['ENCOUNTER_DURATION_MIN', 'ENCOUNTER_DURATION_HOURS', 'DURATION_DAYS', 'DURATION_FLAG']

Duration flag distribution:
DURATION_FLAG
Normal         27860
Over 7 Days       31
Name: count, dtype: int64

Step 3.5 — Encounter duration features created successfully.

In [65]:
# ============================================================
# STEP 3.6 — DURATION VALIDATION
# ============================================================

print("=" * 70)
print("STEP 3.6 — DURATION VALIDATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. ENCOUNTER DURATION VALIDATION
# ------------------------------------------------------------

encounter_duration_validation = pd.DataFrame({
    "Validation": [
        "Total encounters",
        "Missing duration",
        "Negative duration",
        "Zero duration",
        "Duration > 7 days"
    ],
    "Count": [
        len(encounters_clean),

        encounters_clean[
            "ENCOUNTER_DURATION_HOURS"
        ].isna().sum(),

        (
            encounters_clean[
                "ENCOUNTER_DURATION_HOURS"
            ] < 0
        ).sum(),

        (
            encounters_clean[
                "ENCOUNTER_DURATION_HOURS"
            ] == 0
        ).sum(),

        (
            encounters_clean[
                "DURATION_DAYS"
            ] > 7
        ).sum()
    ]
})

print("\nENCOUNTER DURATION VALIDATION")
display(encounter_duration_validation)


# ------------------------------------------------------------
# 2. PROCEDURE DURATION VALIDATION
# ------------------------------------------------------------

procedure_duration_validation = pd.DataFrame({
    "Validation": [
        "Total procedures",
        "Missing duration",
        "Negative duration",
        "Zero duration",
        "Duration > 7 days"
    ],
    "Count": [
        len(procedures_clean),

        procedures_clean[
            "PROCEDURE_DURATION_HOURS"
        ].isna().sum(),

        (
            procedures_clean[
                "PROCEDURE_DURATION_HOURS"
            ] < 0
        ).sum(),

        (
            procedures_clean[
                "PROCEDURE_DURATION_HOURS"
            ] == 0
        ).sum(),

        (
            procedures_clean[
                "PROCEDURE_DURATION_DAYS"
            ] > 7
        ).sum()
    ]
})

print("\nPROCEDURE DURATION VALIDATION")
display(procedure_duration_validation)


# ------------------------------------------------------------
# 3. IDENTIFY ENCOUNTER DURATION ANOMALIES
# ------------------------------------------------------------

encounter_duration_anomalies = encounters_clean[
    (
        (encounters_clean["ENCOUNTER_DURATION_HOURS"] < 0) |
        (encounters_clean["DURATION_DAYS"] > 7)
    )
].copy()

print("\nENCOUNTER DURATION ANOMALIES")
print(
    "Number of anomalous encounters:",
    len(encounter_duration_anomalies)
)

if len(encounter_duration_anomalies) > 0:

    display(
        encounter_duration_anomalies[
            [
                "Id",
                "PATIENT",
                "START",
                "STOP",
                "ENCOUNTER_DURATION_HOURS",
                "DURATION_DAYS",
                "DURATION_FLAG"
            ]
        ].sort_values(
            "DURATION_DAYS",
            ascending=False
        ).head(20)
    )


# ------------------------------------------------------------
# 4. IDENTIFY PROCEDURE DURATION ANOMALIES
# ------------------------------------------------------------

procedure_duration_anomalies = procedures_clean[
    (
        (procedures_clean["PROCEDURE_DURATION_HOURS"] < 0) |
        (procedures_clean["PROCEDURE_DURATION_DAYS"] > 7)
    )
].copy()

print("\nPROCEDURE DURATION ANOMALIES")
print(
    "Number of anomalous procedures:",
    len(procedure_duration_anomalies)
)

if len(procedure_duration_anomalies) > 0:

    display(
        procedure_duration_anomalies[
            [
                "PATIENT",
                "ENCOUNTER",
                "START",
                "STOP",
                "PROCEDURE_DURATION_HOURS",
                "PROCEDURE_DURATION_DAYS",
                "PROCEDURE_DURATION_FLAG"
            ]
        ].sort_values(
            "PROCEDURE_DURATION_DAYS",
            ascending=False
        ).head(20)
    )


# ------------------------------------------------------------
# 5. OVERALL VALIDATION STATUS
# ------------------------------------------------------------

encounter_negative = (
    encounters_clean["ENCOUNTER_DURATION_HOURS"] < 0
).sum()

encounter_missing = (
    encounters_clean["ENCOUNTER_DURATION_HOURS"].isna()
).sum()

procedure_negative = (
    procedures_clean["PROCEDURE_DURATION_HOURS"] < 0
).sum()

procedure_missing = (
    procedures_clean["PROCEDURE_DURATION_HOURS"].isna()
).sum()

encounter_long = (
    encounters_clean["DURATION_DAYS"] > 7
).sum()

procedure_long = (
    procedures_clean["PROCEDURE_DURATION_DAYS"] > 7
).sum()


print("\n" + "=" * 70)
print("DURATION VALIDATION SUMMARY")
print("=" * 70)

print(
    "Encounter missing duration:",
    encounter_missing
)

print(
    "Encounter negative duration:",
    encounter_negative
)

print(
    "Encounter >7 days:",
    encounter_long
)

print(
    "Procedure missing duration:",
    procedure_missing
)

print(
    "Procedure negative duration:",
    procedure_negative
)

print(
    "Procedure >7 days:",
    procedure_long
)

======================================================================
STEP 3.6 — DURATION VALIDATION
======================================================================

ENCOUNTER DURATION VALIDATION

          Validation  Count
0   Total encounters  27891
1   Missing duration      0
2  Negative duration      0
3      Zero duration      0
4  Duration > 7 days     31

PROCEDURE DURATION VALIDATION

          Validation  Count
0   Total procedures  47701
1   Missing duration      0
2  Negative duration      0
3      Zero duration      2
4  Duration > 7 days      1

ENCOUNTER DURATION ANOMALIES
Number of anomalous encounters: 31

,Id,PATIENT,START,STOP,ENCOUNTER_DURATION_HOURS,DURATION_DAYS,DURATION_FLAG
9704,fc2c2add-0b55-e300-5cea-8f43044eb330,5d47b9ac-3f37-f400-1747-c6c6f92130aa,2014-12-17 11:49:08+00:00,2020-02-01 13:49:08+00:00,44930.000000,1872.083333,Over 7 Days
7735,2cb41a50-819c-ef7e-87df-b5b47b2e01a1,09e0ec41-cd4c-50b2-b425-824013777beb,2014-03-27 00:33:14+00:00,2019-03-13 15:33:14+00:00,43503.000000,1812.625000,Over 7 Days
7805,7a19a260-e4a9-7b81-3f93-e07144d634d9,8885aba5-afce-9e3b-0c1d-a684a347b5fb,2014-04-02 22:26:28+00:00,2015-07-02 13:44:57+00:00,10935.308056,455.637836,Over 7 Days
6116,3cf29374-f91a-5877-9356-87792501d225,a12541db-140e-8189-070c-dc9f4815f40f,2014-01-31 02:29:54+00:00,2015-04-22 02:29:54+00:00,10704.000000,446.000000,Over 7 Days
6371,63b7c71f-23f5-32dc-b63a-cca7bf5625a2,6e8e0498-187a-d038-c7af-716b12e70455,2014-02-06 02:17:34+00:00,2015-01-20 02:17:34+00:00,8352.000000,348.000000,Over 7 Days
18343,4079872d-73da-3b52-5306-2a978c6f5c8c,54889029-0a1e-0b75-5980-1c091dd4bc0e,2018-07-18 23:56:20+00:00,2019-06-27 17:56:35+00:00,8250.004167,343.750174,Over 7 Days
6380,110777dd-6aca-3c9c-7119-ab2494c0665e,0ec939a0-559c-7bc9-db9c-a7feae58634a,2014-02-06 04:57:58+00:00,2015-01-13 04:57:58+00:00,8184.000000,341.000000,Over 7 Days
7832,04df7388-7a70-3e99-c0fe-7f7ddd062931,ea9d6669-efc3-3c16-4f70-70cc1c1659d7,2014-04-04 22:41:46+00:00,2015-01-31 13:54:32+00:00,7239.212778,301.633866,Over 7 Days
6125,d0476a31-1524-f23f-fb79-290ecd6206aa,f6932663-d920-6e76-89e1-21a6b43cf03b,2014-01-31 11:10:57+00:00,2014-06-25 11:10:57+00:00,3480.000000,145.000000,Over 7 Days
6138,1123fed5-342e-f49b-4ab9-91f153b9e474,d40ba361-8192-a8e6-b75c-5def4758fe3f,2014-01-31 20:39:04+00:00,2014-04-09 20:39:04+00:00,1632.000000,68.000000,Over 7 Days
6332,dcc730d3-4d74-5e75-ae03-cd23c0ee742c,60d2d35e-bd32-36df-b8e0-b64a3494f0e8,2014-02-05 08:41:28+00:00,2014-04-14 08:41:28+00:00,1632.000000,68.000000,Over 7 Days
16504,0b29bad1-7b3c-2585-1b31-c3dd7a6ec36a,a96d5031-46d5-e3f6-ec67-81f8edd48aa8,2017-09-30 13:44:27+00:00,2017-11-25 13:44:27+00:00,1344.000000,56.000000,Over 7 Days
6145,6053724d-e3b1-0449-402d-3090d3514389,f21a9c39-abd4-4e57-575d-83e1c29484da,2014-01-31 23:35:27+00:00,2014-03-26 23:35:27+00:00,1296.000000,54.000000,Over 7 Days
8980,9741be00-49a5-f25a-a59b-ea46ffbad229,77dedc66-369c-bb18-940d-0db841255ef7,2014-09-14 10:42:36+00:00,2014-10-11 21:42:36+00:00,659.000000,27.458333,Over 7 Days
23048,6c108963-2fda-815b-3813-a424b3533127,01296e88-f6d9-1c18-cf91-87523325e034,2020-08-15 04:52:21+00:00,2020-09-08 17:52:21+00:00,589.000000,24.541667,Over 7 Days
5457,d5c42fa8-f110-b714-d89a-04ec57038a58,0226f105-2572-1c6f-15f0-1aa0438e40d0,2013-10-22 00:16:17+00:00,2013-11-14 00:16:17+00:00,552.000000,23.000000,Over 7 Days
14807,6fc6cbfc-ade5-c9ec-721c-4f71d9a1a815,2f6c035b-a11d-9373-89af-0cb2195592d2,2017-01-11 09:03:19+00:00,2017-01-27 09:03:19+00:00,384.000000,16.000000,Over 7 Days
24226,96f41ac9-60c0-d035-249b-ea9f68dfb7da,2999ffe8-ab8a-3afa-ab9e-aa40fa162e8c,2021-01-12 14:24:46+00:00,2021-01-25 15:06:45+00:00,312.699722,13.029155,Over 7 Days
24155,49a58342-2bed-0dec-5581-f12474408881,7811ad1e-3baf-5d00-6664-01c7396f67c9,2021-01-03 03:22:46+00:00,2021-01-16 04:02:42+00:00,312.665556,13.027731,Over 7 Days
23972,d12cbc08-c639-0917-6250-66eca2e6995f,97c4cfee-e860-e908-1797-8da4dc241ec4,2020-12-12 19:05:25+00:00,2020-12-25 19:32:34+00:00,312.452500,13.018854,Over 7 Days

PROCEDURE DURATION ANOMALIES
Number of anomalous procedures: 1

,PATIENT,ENCOUNTER,START,STOP,PROCEDURE_DURATION_HOURS,PROCEDURE_DURATION_DAYS,PROCEDURE_DURATION_FLAG
25825,2f6c035b-a11d-9373-89af-0cb2195592d2,6fc6cbfc-ade5-c9ec-721c-4f71d9a1a815,2017-01-11 09:03:19+00:00,2017-01-27 09:03:19+00:00,384.0,16.0,Valid

======================================================================
DURATION VALIDATION SUMMARY
======================================================================
Encounter missing duration: 0
Encounter negative duration: 0
Encounter >7 days: 31
Procedure missing duration: 0
Procedure negative duration: 0
Procedure >7 days: 1

In [66]:
# ============================================================
# STEP 3.15 — CHECK EXISTING DURATION COLUMNS
# ============================================================

print("ENCOUNTER DURATION COLUMNS:")
print([
    col for col in encounters_clean.columns
    if "DURATION" in col.upper()
])

print("\nPROCEDURE DURATION COLUMNS:")
print([
    col for col in procedures_clean.columns
    if "DURATION" in col.upper()
])

ENCOUNTER DURATION COLUMNS:
['ENCOUNTER_DURATION_MIN', 'ENCOUNTER_DURATION_HOURS', 'DURATION_DAYS', 'DURATION_FLAG']

PROCEDURE DURATION COLUMNS:
['PROCEDURE_DURATION_MIN', 'PROCEDURE_DURATION_HOURS', 'PROCEDURE_DURATION_DAYS', 'PROCEDURE_DURATION_FLAG']

In [67]:
print("\nALL PROCEDURE COLUMNS:")
print(procedures_clean.columns.tolist())

ALL PROCEDURE COLUMNS:
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION', 'Procedure_Year', 'Procedure_Month', 'Procedure_Month_Name', 'Procedure_Quarter', 'Procedure_Year_Month', 'Procedure_Day', 'Procedure_Day_Name', 'Procedure_Week', 'PROCEDURE_DURATION_MIN', 'PROCEDURE_DURATION_HOURS', 'PROCEDURE_DURATION_DAYS', 'PROCEDURE_DURATION_FLAG']

In [68]:
# ============================================================
# STEP 3.15 — FINAL DATA-QUALITY REPORT
# ============================================================

print("=" * 70)
print("STEP 3.15 — FINAL DATA-QUALITY REPORT")
print("=" * 70)


# ------------------------------------------------------------
# 1. DATASET ROW COUNTS
# ------------------------------------------------------------

dataset_counts = pd.DataFrame({
    "Dataset": [
        "patients_clean",
        "encounters_clean",
        "procedures_clean",
        "payers_clean",
        "organizations_clean"
    ],
    "Rows": [
        len(patients_clean),
        len(encounters_clean),
        len(procedures_clean),
        len(payers_clean),
        len(organizations_clean)
    ]
})

print("\nDATASET ROW COUNTS")
display(dataset_counts)


# ------------------------------------------------------------
# 2. MISSING VALUE SUMMARY
# ------------------------------------------------------------

missing_summary = []

for name, df in {
    "patients_clean": patients_clean,
    "encounters_clean": encounters_clean,
    "procedures_clean": procedures_clean,
    "payers_clean": payers_clean,
    "organizations_clean": organizations_clean
}.items():

    missing_count = int(df.isna().sum().sum())
    columns_with_missing = int((df.isna().sum() > 0).sum())

    missing_summary.append({
        "Dataset": name,
        "Columns_With_Missing": columns_with_missing,
        "Total_Missing": missing_count
    })

missing_summary = pd.DataFrame(missing_summary)

print("\nMISSING VALUE SUMMARY")
display(missing_summary)


# ------------------------------------------------------------
# 3. DUPLICATE SUMMARY
# ------------------------------------------------------------

duplicate_summary = pd.DataFrame({
    "Dataset": [
        "patients_clean",
        "encounters_clean",
        "procedures_clean",
        "payers_clean",
        "organizations_clean"
    ],
    "Duplicate_Rows": [
        patients_clean.duplicated().sum(),
        encounters_clean.duplicated().sum(),
        procedures_clean.duplicated().sum(),
        payers_clean.duplicated().sum(),
        organizations_clean.duplicated().sum()
    ]
})

print("\nDUPLICATE SUMMARY")
display(duplicate_summary)


# ------------------------------------------------------------
# 4. ENCOUNTER DATE VALIDATION
# ------------------------------------------------------------

encounter_date_validation = pd.DataFrame({
    "Validation": [
        "Missing START",
        "Missing STOP",
        "STOP before START"
    ],
    "Count": [
        encounters_clean["START"].isna().sum(),
        encounters_clean["STOP"].isna().sum(),
        (encounters_clean["STOP"] < encounters_clean["START"]).sum()
    ]
})

print("\nENCOUNTER DATE VALIDATION")
display(encounter_date_validation)


# ------------------------------------------------------------
# 5. PROCEDURE DATE VALIDATION
# ------------------------------------------------------------

procedure_date_validation = pd.DataFrame({
    "Validation": [
        "Missing START",
        "Missing STOP",
        "STOP before START"
    ],
    "Count": [
        procedures_clean["START"].isna().sum(),
        procedures_clean["STOP"].isna().sum(),
        (procedures_clean["STOP"] < procedures_clean["START"]).sum()
    ]
})

print("\nPROCEDURE DATE VALIDATION")
display(procedure_date_validation)


# ------------------------------------------------------------
# 6. ENCOUNTER DURATION VALIDATION
# ------------------------------------------------------------

encounter_duration_validation = pd.DataFrame({
    "Validation": [
        "Total encounters",
        "Missing duration",
        "Negative duration",
        "Zero duration",
        "Duration > 7 days"
    ],
    "Count": [
        len(encounters_clean),
        encounters_clean["ENCOUNTER_DURATION_HOURS"].isna().sum(),
        (encounters_clean["ENCOUNTER_DURATION_HOURS"] < 0).sum(),
        (encounters_clean["ENCOUNTER_DURATION_HOURS"] == 0).sum(),
        (encounters_clean["ENCOUNTER_DURATION_HOURS"] > 168).sum()
    ]
})

print("\nENCOUNTER DURATION VALIDATION")
display(encounter_duration_validation)


# ------------------------------------------------------------
# 7. PROCEDURE DURATION VALIDATION
# ------------------------------------------------------------

procedure_duration_validation = pd.DataFrame({
    "Validation": [
        "Total procedures",
        "Missing duration",
        "Negative duration",
        "Zero duration",
        "Duration > 7 days"
    ],
    "Count": [
        len(procedures_clean),
        procedures_clean["PROCEDURE_DURATION_HOURS"].isna().sum(),
        (procedures_clean["PROCEDURE_DURATION_HOURS"] < 0).sum(),
        (procedures_clean["PROCEDURE_DURATION_HOURS"] == 0).sum(),
        (procedures_clean["PROCEDURE_DURATION_HOURS"] > 168).sum()
    ]
})

print("\nPROCEDURE DURATION VALIDATION")
display(procedure_duration_validation)


# ------------------------------------------------------------
# 8. OVERALL QUALITY CHECKS
# ------------------------------------------------------------

quality_checks = pd.DataFrame({
    "Quality_Check": [
        "Expected patient rows",
        "Expected encounter rows",
        "Expected procedure rows",
        "Expected payer rows",
        "Expected organization rows",
        "Encounter negative duration",
        "Procedure negative duration",
        "Encounter missing duration",
        "Procedure missing duration",
        "Encounter duration anomalies",
        "Procedure duration anomalies"
    ],

    "Count": [
        len(patients_clean),
        len(encounters_clean),
        len(procedures_clean),
        len(payers_clean),
        len(organizations_clean),

        (encounters_clean["ENCOUNTER_DURATION_HOURS"] < 0).sum(),
        (procedures_clean["PROCEDURE_DURATION_HOURS"] < 0).sum(),

        encounters_clean["ENCOUNTER_DURATION_HOURS"].isna().sum(),
        procedures_clean["PROCEDURE_DURATION_HOURS"].isna().sum(),

        (encounters_clean["ENCOUNTER_DURATION_HOURS"] > 168).sum(),
        (procedures_clean["PROCEDURE_DURATION_HOURS"] > 168).sum()
    ]
})

print("\nOVERALL QUALITY CHECKS")
display(quality_checks)


# ------------------------------------------------------------
# 9. FINAL STATUS
# ------------------------------------------------------------

critical_errors = (
    (encounters_clean["ENCOUNTER_DURATION_HOURS"] < 0).sum()
    +
    (procedures_clean["PROCEDURE_DURATION_HOURS"] < 0).sum()
    +
    encounters_clean["ENCOUNTER_DURATION_HOURS"].isna().sum()
    +
    procedures_clean["PROCEDURE_DURATION_HOURS"].isna().sum()
)

duration_anomalies = (
    (encounters_clean["ENCOUNTER_DURATION_HOURS"] > 168).sum()
    +
    (procedures_clean["PROCEDURE_DURATION_HOURS"] > 168).sum()
)


if critical_errors == 0:
    final_status = "PASS — No critical duration/date errors detected."
else:
    final_status = "WARNING — Critical data-quality issues remain."


print("\n" + "=" * 70)
print("FINAL DATA-QUALITY STATUS")
print("=" * 70)

print(final_status)
print(f"Duration anomalies requiring analytical awareness: {duration_anomalies}")

print("\nStage 3.15 completed.")

======================================================================
STEP 3.15 — FINAL DATA-QUALITY REPORT
======================================================================

DATASET ROW COUNTS

               Dataset   Rows
0       patients_clean    974
1     encounters_clean  27891
2     procedures_clean  47701
3         payers_clean     10
4  organizations_clean      1

MISSING VALUE SUMMARY

               Dataset  Columns_With_Missing  Total_Missing
0       patients_clean                     8           5783
1     encounters_clean                     2          39082
2     procedures_clean                     2          73890
3         payers_clean                     0              0
4  organizations_clean                     0              0

DUPLICATE SUMMARY

               Dataset  Duplicate_Rows
0       patients_clean               0
1     encounters_clean               0
2     procedures_clean               0
3         payers_clean               0
4  organizations_clean               0

ENCOUNTER DATE VALIDATION

          Validation  Count
0      Missing START      0
1       Missing STOP      0
2  STOP before START      0

PROCEDURE DATE VALIDATION

          Validation  Count
0      Missing START      0
1       Missing STOP      0
2  STOP before START      0

ENCOUNTER DURATION VALIDATION

          Validation  Count
0   Total encounters  27891
1   Missing duration      0
2  Negative duration      0
3      Zero duration      0
4  Duration > 7 days     31

PROCEDURE DURATION VALIDATION

          Validation  Count
0   Total procedures  47701
1   Missing duration      0
2  Negative duration      0
3      Zero duration      2
4  Duration > 7 days      1

OVERALL QUALITY CHECKS

                   Quality_Check  Count
0          Expected patient rows    974
1        Expected encounter rows  27891
2        Expected procedure rows  47701
3            Expected payer rows     10
4     Expected organization rows      1
5    Encounter negative duration      0
6    Procedure negative duration      0
7     Encounter missing duration      0
8     Procedure missing duration      0
9   Encounter duration anomalies     31
10  Procedure duration anomalies      1

======================================================================
FINAL DATA-QUALITY STATUS
======================================================================
PASS — No critical duration/date errors detected.
Duration anomalies requiring analytical awareness: 32

Stage 3.15 completed.

In [69]:
# ============================================================
# STEP 3.2.1 — CONVERT PATIENT DATE COLUMNS
# ============================================================

patients_clean["BIRTHDATE"] = pd.to_datetime(
    patients_clean["BIRTHDATE"],
    errors="coerce"
)

patients_clean["DEATHDATE"] = pd.to_datetime(
    patients_clean["DEATHDATE"],
    errors="coerce"
)

print("Patient date conversion completed.")

Patient date conversion completed.

In [70]:
# ============================================================
# STEP 3.2.2 — CONVERT ENCOUNTER DATETIME COLUMNS
# ============================================================

encounters_clean["START"] = pd.to_datetime(
    encounters_clean["START"],
    errors="coerce",
    utc=True
)

encounters_clean["STOP"] = pd.to_datetime(
    encounters_clean["STOP"],
    errors="coerce",
    utc=True
)

print("Encounter datetime conversion completed.")

Encounter datetime conversion completed.

In [71]:
# ============================================================
# STEP 3.2.3 — CONVERT PROCEDURE DATETIME COLUMNS
# ============================================================

procedures_clean["START"] = pd.to_datetime(
    procedures_clean["START"],
    errors="coerce",
    utc=True
)

procedures_clean["STOP"] = pd.to_datetime(
    procedures_clean["STOP"],
    errors="coerce",
    utc=True
)

print("Procedure datetime conversion completed.")

Procedure datetime conversion completed.

In [72]:
# ============================================================
# STEP 3.2.4 — VERIFY DATE TYPES
# ============================================================

print("PATIENTS")
print("BIRTHDATE:", patients_clean["BIRTHDATE"].dtype)
print("DEATHDATE:", patients_clean["DEATHDATE"].dtype)

print("\nENCOUNTERS")
print("START:", encounters_clean["START"].dtype)
print("STOP:", encounters_clean["STOP"].dtype)

print("\nPROCEDURES")
print("START:", procedures_clean["START"].dtype)
print("STOP:", procedures_clean["STOP"].dtype)

PATIENTS
BIRTHDATE: datetime64[us]
DEATHDATE: datetime64[us]

ENCOUNTERS
START: datetime64[us, UTC]
STOP: datetime64[us, UTC]

PROCEDURES
START: datetime64[us, UTC]
STOP: datetime64[us, UTC]

In [73]:
# ============================================================
# STEP 3.2.5 — CHECK FOR INVALID DATE CONVERSIONS
# ============================================================

date_columns = {
    "patients": ["BIRTHDATE", "DEATHDATE"],
    "encounters": ["START", "STOP"],
    "procedures": ["START", "STOP"]
}

for table_name, columns in date_columns.items():

    print(f"\n===== {table_name.upper()} =====")

    df = clean_tables[table_name]

    for column in columns:
        print(
            f"{column}: "
            f"{df[column].isna().sum()} missing"
        )

===== PATIENTS =====
BIRTHDATE: 0 missing
DEATHDATE: 820 missing

===== ENCOUNTERS =====
START: 0 missing
STOP: 0 missing

===== PROCEDURES =====
START: 0 missing
STOP: 0 missing

In [74]:
# ============================================================
# STEP 3.2.6 — BEFORE vs AFTER DATE VALIDATION
# ============================================================

date_comparison = {
    "patients.BIRTHDATE": (
        patients["BIRTHDATE"].isna().sum(),
        patients_clean["BIRTHDATE"].isna().sum()
    ),

    "patients.DEATHDATE": (
        patients["DEATHDATE"].isna().sum(),
        patients_clean["DEATHDATE"].isna().sum()
    ),

    "encounters.START": (
        encounters["START"].isna().sum(),
        encounters_clean["START"].isna().sum()
    ),

    "encounters.STOP": (
        encounters["STOP"].isna().sum(),
        encounters_clean["STOP"].isna().sum()
    ),

    "procedures.START": (
        procedures["START"].isna().sum(),
        procedures_clean["START"].isna().sum()
    ),

    "procedures.STOP": (
        procedures["STOP"].isna().sum(),
        procedures_clean["STOP"].isna().sum()
    )
}

for column, (before, after) in date_comparison.items():

    print(
        f"{column}: "
        f"Before = {before}, "
        f"After = {after}"
    )

patients.BIRTHDATE: Before = 0, After = 0
patients.DEATHDATE: Before = 820, After = 820
encounters.START: Before = 0, After = 0
encounters.STOP: Before = 0, After = 0
procedures.START: Before = 0, After = 0
procedures.STOP: Before = 0, After = 0

In [75]:
patients_clean[
    ["Id", "BIRTHDATE", "DEATHDATE"]
].head(10)

                                     Id  BIRTHDATE  DEATHDATE
0  5605b66b-e92d-c16c-1b83-b8bf7040d51f 1977-03-19        NaT
1  6e5ae27c-8038-7988-e2c0-25a103f01bfa 1940-02-19        NaT
2  8123d076-0886-9007-e956-d5864aa121a7 1958-06-04        NaT
3  770518e4-6133-648e-60c9-071eb2f0e2ce 1928-12-25 2017-09-29
4  f96addf5-81b9-0aab-7855-d208d3d352c5 1928-12-25 2014-02-23
5  8e9650d1-788a-78f9-4a28-d08f7f95354a 1928-12-25        NaT
6  183df435-4190-060e-8f8e-bf63c572b266 1957-11-08        NaT
7  720560d4-51da-c38c-ee90-c15935278df1 1972-06-27        NaT
8  217851b0-5f47-d376-18b9-0fe4ba77207e 1954-03-06        NaT
9  ff331e5c-ab16-e218-f39a-63e11de1ed75 1927-07-10        NaT

In [76]:
encounters_clean[
    ["Id", "START", "STOP"]
].head(10)

,Id,START,STOP
0,32c84703-2481-49cd-d571-3899d5820253,2011-01-02 09:26:36+00:00,2011-01-02 12:58:36+00:00
1,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03 05:44:39+00:00,2011-01-03 06:01:42+00:00
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,2011-01-03 14:32:11+00:00,2011-01-03 14:47:11+00:00
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,2011-01-03 16:24:45+00:00,2011-01-03 16:39:45+00:00
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03 17:36:53+00:00,2011-01-03 17:51:53+00:00
5,c4923a74-3e40-8b0c-cf73-05b9c0390621,2011-01-03 19:08:16+00:00,2011-01-03 19:23:16+00:00
6,c140ed81-040e-8319-e860-f72b4738ed22,2011-01-03 22:39:50+00:00,2011-01-03 22:54:50+00:00
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04 14:49:55+00:00,2011-01-04 15:04:55+00:00
8,16bdc066-886f-34e1-38fa-afb85090b637,2011-01-04 15:13:10+00:00,2011-01-04 15:28:10+00:00
9,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05 04:02:09+00:00,2011-01-05 04:17:09+00:00

In [77]:
procedures_clean[
    ["PATIENT", "ENCOUNTER", "START", "STOP"]
].head(10)

,PATIENT,ENCOUNTER,START,STOP
0,3de74169-7f67-9304-91d4-757e0f3a14d2,32c84703-2481-49cd-d571-3899d5820253,2011-01-02 09:26:36+00:00,2011-01-02 12:58:36+00:00
1,d9ec2e44-32e9-9148-179a-1653348cc4e2,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03 05:44:39+00:00,2011-01-03 06:01:42+00:00
2,d856d6e6-4c98-e7a2-129b-44076c63d008,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04 14:49:55+00:00,2011-01-04 15:04:55+00:00
3,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05 04:02:09+00:00,2011-01-05 04:17:09+00:00
4,3de74169-7f67-9304-91d4-757e0f3a14d2,9de5f0b0-4ba4-ce6f-45fb-b55c202f31a5,2011-01-05 12:58:36+00:00,2011-01-05 16:42:36+00:00
5,712e95dd-f313-39c7-1fc9-8463c15c105f,44057ea7-178f-c3c3-965a-78e4521fa43b,2011-01-06 18:12:41+00:00,2011-01-06 18:17:12+00:00
6,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,4b6a38e6-7df9-2d75-d850-6bd662f3d05b,2011-01-07 21:02:09+00:00,2011-01-07 22:39:45+00:00
7,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,cc36dc26-6019-94a5-93b7-7bbf312e6fc4,2011-01-07 22:39:45+00:00,2011-01-07 23:00:45+00:00
8,3de74169-7f67-9304-91d4-757e0f3a14d2,03f54837-bfc8-81aa-4905-f74ceb35162f,2011-01-08 16:42:36+00:00,2011-01-08 20:15:36+00:00
9,f4cde0dc-db22-5d98-5228-55121ae74cad,17d162fa-fc25-b3c5-5e72-20287a55eaf1,2011-01-09 16:11:28+00:00,2011-01-09 16:51:19+00:00

In [78]:
# ============================================================
# STEP 3.3.1 — VALIDATE PATIENT BIRTH/DEATH DATE LOGIC
# ============================================================

invalid_death_dates = patients_clean[
    patients_clean["DEATHDATE"].notna() &
    (patients_clean["DEATHDATE"] < patients_clean["BIRTHDATE"])
]

print("Patients with death date before birth date:",
      len(invalid_death_dates))

Patients with death date before birth date: 0

In [79]:
invalid_death_dates[
    ["Id", "BIRTHDATE", "DEATHDATE"]
].head()

Empty DataFrame
Columns: [Id, BIRTHDATE, DEATHDATE]
Index: []

In [80]:
# ============================================================
# STEP 3.3.2 — VALIDATE ENCOUNTER DATE LOGIC
# ============================================================

invalid_encounter_dates = encounters_clean[
    encounters_clean["STOP"] < encounters_clean["START"]
]

print(
    "Encounters with STOP before START:",
    len(invalid_encounter_dates)
)

Encounters with STOP before START: 0

In [81]:
zero_duration_encounters = encounters_clean[
    encounters_clean["STOP"] == encounters_clean["START"]
]

print(
    "Encounters with zero duration:",
    len(zero_duration_encounters)
)

Encounters with zero duration: 0

In [82]:
# ============================================================
# STEP 3.3.3 — VALIDATE PROCEDURE DATE LOGIC
# ============================================================

invalid_procedure_dates = procedures_clean[
    procedures_clean["STOP"] < procedures_clean["START"]
]

print(
    "Procedures with STOP before START:",
    len(invalid_procedure_dates)
)

Procedures with STOP before START: 0

In [83]:
zero_duration_procedures = procedures_clean[
    procedures_clean["STOP"] == procedures_clean["START"]
]

print(
    "Procedures with zero duration:",
    len(zero_duration_procedures)
)

Procedures with zero duration: 2

In [84]:
# ============================================================
# STEP 3.3.4 — CHECK ENCOUNTERS AGAINST PATIENT BIRTHDATES
# ============================================================

encounter_patient_dates = encounters_clean[
    ["Id", "PATIENT", "START"]
].merge(
    patients_clean[
        ["Id", "BIRTHDATE"]
    ],
    left_on="PATIENT",
    right_on="Id",
    how="left",
    suffixes=("_ENCOUNTER", "_PATIENT")
)

invalid_birth_encounters = encounter_patient_dates[
    encounter_patient_dates["START"].dt.date <
    encounter_patient_dates["BIRTHDATE"].dt.date
]

print(
    "Encounters occurring before patient birth:",
    len(invalid_birth_encounters)
)

Encounters occurring before patient birth: 0

In [85]:
# ============================================================
# STEP 3.3.5 — CHECK PROCEDURES AGAINST PATIENT BIRTHDATES
# ============================================================

procedure_patient_dates = procedures_clean[
    ["PATIENT", "ENCOUNTER", "START"]
].merge(
    patients_clean[
        ["Id", "BIRTHDATE"]
    ],
    left_on="PATIENT",
    right_on="Id",
    how="left"
)

invalid_birth_procedures = procedure_patient_dates[
    procedure_patient_dates["START"].dt.date <
    procedure_patient_dates["BIRTHDATE"].dt.date
]

print(
    "Procedures occurring before patient birth:",
    len(invalid_birth_procedures)
)

Procedures occurring before patient birth: 0

In [86]:
# ============================================================
# STEP 3.3.6 — DATE VALIDATION SUMMARY
# ============================================================

print("==============================================")
print("DATE VALIDATION SUMMARY")
print("==============================================")

print(
    "Invalid patient death dates:",
    len(invalid_death_dates)
)

print(
    "Invalid encounter date ranges:",
    len(invalid_encounter_dates)
)

print(
    "Zero-duration encounters:",
    len(zero_duration_encounters)
)

print(
    "Invalid procedure date ranges:",
    len(invalid_procedure_dates)
)

print(
    "Zero-duration procedures:",
    len(zero_duration_procedures)
)

print(
    "Encounters before patient birth:",
    len(invalid_birth_encounters)
)

print(
    "Procedures before patient birth:",
    len(invalid_birth_procedures)
)

==============================================
DATE VALIDATION SUMMARY
==============================================
Invalid patient death dates: 0
Invalid encounter date ranges: 0
Zero-duration encounters: 0
Invalid procedure date ranges: 0
Zero-duration procedures: 2
Encounters before patient birth: 0
Procedures before patient birth: 0

In [87]:
# ============================================================
# STAGE 3.4 — CREATE ENCOUNTER DURATION
# ============================================================

encounters_clean["ENCOUNTER_DURATION_MIN"] = (
    encounters_clean["STOP"] - encounters_clean["START"]
).dt.total_seconds() / 60

print("Encounter duration created successfully.")

Encounter duration created successfully.

In [88]:
encounters_clean[
    ["Id", "START", "STOP", "ENCOUNTER_DURATION_MIN"]
].head(10)

,Id,START,STOP,ENCOUNTER_DURATION_MIN
0,32c84703-2481-49cd-d571-3899d5820253,2011-01-02 09:26:36+00:00,2011-01-02 12:58:36+00:00,212.00
1,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03 05:44:39+00:00,2011-01-03 06:01:42+00:00,17.05
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,2011-01-03 14:32:11+00:00,2011-01-03 14:47:11+00:00,15.00
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,2011-01-03 16:24:45+00:00,2011-01-03 16:39:45+00:00,15.00
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03 17:36:53+00:00,2011-01-03 17:51:53+00:00,15.00
5,c4923a74-3e40-8b0c-cf73-05b9c0390621,2011-01-03 19:08:16+00:00,2011-01-03 19:23:16+00:00,15.00
6,c140ed81-040e-8319-e860-f72b4738ed22,2011-01-03 22:39:50+00:00,2011-01-03 22:54:50+00:00,15.00
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04 14:49:55+00:00,2011-01-04 15:04:55+00:00,15.00
8,16bdc066-886f-34e1-38fa-afb85090b637,2011-01-04 15:13:10+00:00,2011-01-04 15:28:10+00:00,15.00
9,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05 04:02:09+00:00,2011-01-05 04:17:09+00:00,15.00

In [89]:
encounters_clean["ENCOUNTER_DURATION_HOURS"] = (
    encounters_clean["ENCOUNTER_DURATION_MIN"] / 60
)

print("Encounter duration in hours created.")

Encounter duration in hours created.

In [90]:
encounters_clean[
    "ENCOUNTER_DURATION_MIN"
].describe()

count    2.789100e+04
mean     4.359597e+02
std      2.389942e+04
min      1.500000e+01
25%      1.500000e+01
50%      1.500000e+01
75%      5.185000e+01
max      2.695800e+06
Name: ENCOUNTER_DURATION_MIN, dtype: float64

In [91]:
negative_duration = encounters_clean[
    encounters_clean["ENCOUNTER_DURATION_MIN"] < 0
]

print(
    "Negative encounter durations:",
    len(negative_duration)
)

Negative encounter durations: 0

In [92]:
zero_duration = encounters_clean[
    encounters_clean["ENCOUNTER_DURATION_MIN"] == 0
]

print(
    "Zero-duration encounters:",
    len(zero_duration)
)

Zero-duration encounters: 0

In [93]:
missing_duration = encounters_clean[
    "ENCOUNTER_DURATION_MIN"
].isna().sum()

print(
    "Missing encounter durations:",
    missing_duration
)

Missing encounter durations: 0

In [94]:
# ============================================================
# ENCOUNTER DURATION QUALITY CHECK
# ============================================================

print("==============================================")
print("ENCOUNTER DURATION QUALITY CHECK")
print("==============================================")

print(
    "Total encounters:",
    len(encounters_clean)
)

print(
    "Missing durations:",
    encounters_clean["ENCOUNTER_DURATION_MIN"].isna().sum()
)

print(
    "Negative durations:",
    (encounters_clean["ENCOUNTER_DURATION_MIN"] < 0).sum()
)

print(
    "Zero-duration encounters:",
    (encounters_clean["ENCOUNTER_DURATION_MIN"] == 0).sum()
)

print(
    "\nDuration statistics (minutes):"
)

print(
    encounters_clean["ENCOUNTER_DURATION_MIN"].describe()
)

==============================================
ENCOUNTER DURATION QUALITY CHECK
==============================================
Total encounters: 27891
Missing durations: 0
Negative durations: 0
Zero-duration encounters: 0

Duration statistics (minutes):
count    2.789100e+04
mean     4.359597e+02
std      2.389942e+04
min      1.500000e+01
25%      1.500000e+01
50%      1.500000e+01
75%      5.185000e+01
max      2.695800e+06
Name: ENCOUNTER_DURATION_MIN, dtype: float64

In [95]:
# ============================================================
# STEP 3.4.9 — INVESTIGATE EXTREME ENCOUNTER DURATIONS
# ============================================================

longest_encounters = encounters_clean.sort_values(
    "ENCOUNTER_DURATION_MIN",
    ascending=False
)[[
    "Id",
    "PATIENT",
    "START",
    "STOP",
    "ENCOUNTERCLASS",
    "DESCRIPTION",
    "ENCOUNTER_DURATION_MIN",
    "BASE_ENCOUNTER_COST",
    "TOTAL_CLAIM_COST",
    "PAYER_COVERAGE",
    "REASONDESCRIPTION"
]]

longest_encounters.head(10)

,Id,PATIENT,START,STOP,ENCOUNTERCLASS,DESCRIPTION,ENCOUNTER_DURATION_MIN,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONDESCRIPTION
9704,fc2c2add-0b55-e300-5cea-8f43044eb330,5d47b9ac-3f37-f400-1747-c6c6f92130aa,2014-12-17 11:49:08+00:00,2020-02-01 13:49:08+00:00,ambulatory,Follow-up encounter (procedure),2.695800e+06,85.55,85.55,0.00,NaN
7735,2cb41a50-819c-ef7e-87df-b5b47b2e01a1,09e0ec41-cd4c-50b2-b425-824013777beb,2014-03-27 00:33:14+00:00,2019-03-13 15:33:14+00:00,ambulatory,Follow-up encounter (procedure),2.610180e+06,85.55,85.55,7.91,NaN
7805,7a19a260-e4a9-7b81-3f93-e07144d634d9,8885aba5-afce-9e3b-0c1d-a684a347b5fb,2014-04-02 22:26:28+00:00,2015-07-02 13:44:57+00:00,ambulatory,Follow-up encounter (procedure),6.561185e+05,85.55,85.55,24.27,NaN
6116,3cf29374-f91a-5877-9356-87792501d225,a12541db-140e-8189-070c-dc9f4815f40f,2014-01-31 02:29:54+00:00,2015-04-22 02:29:54+00:00,outpatient,Encounter for problem (procedure),6.422400e+05,85.55,85.55,36.44,NaN
6371,63b7c71f-23f5-32dc-b63a-cca7bf5625a2,6e8e0498-187a-d038-c7af-716b12e70455,2014-02-06 02:17:34+00:00,2015-01-20 02:17:34+00:00,outpatient,Encounter for problem (procedure),5.011200e+05,85.55,85.55,0.00,NaN
18343,4079872d-73da-3b52-5306-2a978c6f5c8c,54889029-0a1e-0b75-5980-1c091dd4bc0e,2018-07-18 23:56:20+00:00,2019-06-27 17:56:35+00:00,inpatient,Periodic reevaluation and management of health...,4.950002e+05,146.18,7093.85,5643.08,NaN
6380,110777dd-6aca-3c9c-7119-ab2494c0665e,0ec939a0-559c-7bc9-db9c-a7feae58634a,2014-02-06 04:57:58+00:00,2015-01-13 04:57:58+00:00,outpatient,Encounter for problem (procedure),4.910400e+05,85.55,85.55,0.00,NaN
7832,04df7388-7a70-3e99-c0fe-7f7ddd062931,ea9d6669-efc3-3c16-4f70-70cc1c1659d7,2014-04-04 22:41:46+00:00,2015-01-31 13:54:32+00:00,ambulatory,Follow-up encounter (procedure),4.343528e+05,85.55,85.55,0.00,NaN
6125,d0476a31-1524-f23f-fb79-290ecd6206aa,f6932663-d920-6e76-89e1-21a6b43cf03b,2014-01-31 11:10:57+00:00,2014-06-25 11:10:57+00:00,outpatient,Encounter for problem (procedure),2.088000e+05,85.55,85.55,0.00,NaN
6332,dcc730d3-4d74-5e75-ae03-cd23c0ee742c,60d2d35e-bd32-36df-b8e0-b64a3494f0e8,2014-02-05 08:41:28+00:00,2014-04-14 08:41:28+00:00,outpatient,Encounter for problem (procedure),9.792000e+04,85.55,85.55,0.00,NaN

In [96]:
# ============================================================
# STEP 3.4.10 — VIEW EXTREME DURATIONS IN DAYS
# ============================================================

longest_encounters = longest_encounters.copy()

longest_encounters["DURATION_DAYS"] = (
    longest_encounters["ENCOUNTER_DURATION_MIN"] / (60 * 24)
)

longest_encounters.head(10)

,Id,PATIENT,START,STOP,ENCOUNTERCLASS,DESCRIPTION,ENCOUNTER_DURATION_MIN,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONDESCRIPTION,DURATION_DAYS
9704,fc2c2add-0b55-e300-5cea-8f43044eb330,5d47b9ac-3f37-f400-1747-c6c6f92130aa,2014-12-17 11:49:08+00:00,2020-02-01 13:49:08+00:00,ambulatory,Follow-up encounter (procedure),2.695800e+06,85.55,85.55,0.00,NaN,1872.083333
7735,2cb41a50-819c-ef7e-87df-b5b47b2e01a1,09e0ec41-cd4c-50b2-b425-824013777beb,2014-03-27 00:33:14+00:00,2019-03-13 15:33:14+00:00,ambulatory,Follow-up encounter (procedure),2.610180e+06,85.55,85.55,7.91,NaN,1812.625000
7805,7a19a260-e4a9-7b81-3f93-e07144d634d9,8885aba5-afce-9e3b-0c1d-a684a347b5fb,2014-04-02 22:26:28+00:00,2015-07-02 13:44:57+00:00,ambulatory,Follow-up encounter (procedure),6.561185e+05,85.55,85.55,24.27,NaN,455.637836
6116,3cf29374-f91a-5877-9356-87792501d225,a12541db-140e-8189-070c-dc9f4815f40f,2014-01-31 02:29:54+00:00,2015-04-22 02:29:54+00:00,outpatient,Encounter for problem (procedure),6.422400e+05,85.55,85.55,36.44,NaN,446.000000
6371,63b7c71f-23f5-32dc-b63a-cca7bf5625a2,6e8e0498-187a-d038-c7af-716b12e70455,2014-02-06 02:17:34+00:00,2015-01-20 02:17:34+00:00,outpatient,Encounter for problem (procedure),5.011200e+05,85.55,85.55,0.00,NaN,348.000000
18343,4079872d-73da-3b52-5306-2a978c6f5c8c,54889029-0a1e-0b75-5980-1c091dd4bc0e,2018-07-18 23:56:20+00:00,2019-06-27 17:56:35+00:00,inpatient,Periodic reevaluation and management of health...,4.950002e+05,146.18,7093.85,5643.08,NaN,343.750174
6380,110777dd-6aca-3c9c-7119-ab2494c0665e,0ec939a0-559c-7bc9-db9c-a7feae58634a,2014-02-06 04:57:58+00:00,2015-01-13 04:57:58+00:00,outpatient,Encounter for problem (procedure),4.910400e+05,85.55,85.55,0.00,NaN,341.000000
7832,04df7388-7a70-3e99-c0fe-7f7ddd062931,ea9d6669-efc3-3c16-4f70-70cc1c1659d7,2014-04-04 22:41:46+00:00,2015-01-31 13:54:32+00:00,ambulatory,Follow-up encounter (procedure),4.343528e+05,85.55,85.55,0.00,NaN,301.633866
6125,d0476a31-1524-f23f-fb79-290ecd6206aa,f6932663-d920-6e76-89e1-21a6b43cf03b,2014-01-31 11:10:57+00:00,2014-06-25 11:10:57+00:00,outpatient,Encounter for problem (procedure),2.088000e+05,85.55,85.55,0.00,NaN,145.000000
6332,dcc730d3-4d74-5e75-ae03-cd23c0ee742c,60d2d35e-bd32-36df-b8e0-b64a3494f0e8,2014-02-05 08:41:28+00:00,2014-04-14 08:41:28+00:00,outpatient,Encounter for problem (procedure),9.792000e+04,85.55,85.55,0.00,NaN,68.000000

In [97]:
# ============================================================
# STEP 3.4.11 — ENCOUNTER DURATION DISTRIBUTION
# ============================================================

duration_ranges = pd.cut(
    encounters_clean["ENCOUNTER_DURATION_MIN"],
    bins=[
        0,
        30,
        60,
        120,
        360,
        1440,
        10080,
        float("inf")
    ],
    labels=[
        "0–30 minutes",
        "31–60 minutes",
        "61–120 minutes",
        "121–360 minutes",
        "6–24 hours",
        "1–7 days",
        "Over 7 days"
    ],
    include_lowest=True
)

duration_distribution = (
    duration_ranges
    .value_counts()
    .sort_index()
    .to_frame("Encounter_Count")
)

duration_distribution["Percentage"] = (
    duration_distribution["Encounter_Count"]
    / len(encounters_clean)
    * 100
)

duration_distribution

                        Encounter_Count  Percentage
ENCOUNTER_DURATION_MIN
0–30 minutes                      19958   71.557133
31–60 minutes                      3852   13.810907
61–120 minutes                      194    0.695565
121–360 minutes                    2733    9.798860
6–24 hours                         1079    3.868631
1–7 days                             44    0.157757
Over 7 days                          31    0.111147

In [98]:
# ============================================================
# STEP 3.4.12 — INVESTIGATE LONG ENCOUNTERS
# ============================================================

long_encounters = encounters_clean[
    encounters_clean["ENCOUNTER_DURATION_MIN"] > 7 * 24 * 60
].copy()

long_encounters["DURATION_DAYS"] = (
    long_encounters["ENCOUNTER_DURATION_MIN"] / (60 * 24)
)

print(
    "Encounters longer than 7 days:",
    len(long_encounters)
)

long_encounters[
    [
        "Id",
        "PATIENT",
        "START",
        "STOP",
        "ENCOUNTERCLASS",
        "DESCRIPTION",
        "DURATION_DAYS"
    ]
].sort_values(
    "DURATION_DAYS",
    ascending=False
).head(20)

Encounters longer than 7 days: 31

,Id,PATIENT,START,STOP,ENCOUNTERCLASS,DESCRIPTION,DURATION_DAYS
9704,fc2c2add-0b55-e300-5cea-8f43044eb330,5d47b9ac-3f37-f400-1747-c6c6f92130aa,2014-12-17 11:49:08+00:00,2020-02-01 13:49:08+00:00,ambulatory,Follow-up encounter (procedure),1872.083333
7735,2cb41a50-819c-ef7e-87df-b5b47b2e01a1,09e0ec41-cd4c-50b2-b425-824013777beb,2014-03-27 00:33:14+00:00,2019-03-13 15:33:14+00:00,ambulatory,Follow-up encounter (procedure),1812.625000
7805,7a19a260-e4a9-7b81-3f93-e07144d634d9,8885aba5-afce-9e3b-0c1d-a684a347b5fb,2014-04-02 22:26:28+00:00,2015-07-02 13:44:57+00:00,ambulatory,Follow-up encounter (procedure),455.637836
6116,3cf29374-f91a-5877-9356-87792501d225,a12541db-140e-8189-070c-dc9f4815f40f,2014-01-31 02:29:54+00:00,2015-04-22 02:29:54+00:00,outpatient,Encounter for problem (procedure),446.000000
6371,63b7c71f-23f5-32dc-b63a-cca7bf5625a2,6e8e0498-187a-d038-c7af-716b12e70455,2014-02-06 02:17:34+00:00,2015-01-20 02:17:34+00:00,outpatient,Encounter for problem (procedure),348.000000
18343,4079872d-73da-3b52-5306-2a978c6f5c8c,54889029-0a1e-0b75-5980-1c091dd4bc0e,2018-07-18 23:56:20+00:00,2019-06-27 17:56:35+00:00,inpatient,Periodic reevaluation and management of health...,343.750174
6380,110777dd-6aca-3c9c-7119-ab2494c0665e,0ec939a0-559c-7bc9-db9c-a7feae58634a,2014-02-06 04:57:58+00:00,2015-01-13 04:57:58+00:00,outpatient,Encounter for problem (procedure),341.000000
7832,04df7388-7a70-3e99-c0fe-7f7ddd062931,ea9d6669-efc3-3c16-4f70-70cc1c1659d7,2014-04-04 22:41:46+00:00,2015-01-31 13:54:32+00:00,ambulatory,Follow-up encounter (procedure),301.633866
6125,d0476a31-1524-f23f-fb79-290ecd6206aa,f6932663-d920-6e76-89e1-21a6b43cf03b,2014-01-31 11:10:57+00:00,2014-06-25 11:10:57+00:00,outpatient,Encounter for problem (procedure),145.000000
6138,1123fed5-342e-f49b-4ab9-91f153b9e474,d40ba361-8192-a8e6-b75c-5def4758fe3f,2014-01-31 20:39:04+00:00,2014-04-09 20:39:04+00:00,outpatient,Encounter for problem (procedure),68.000000
6332,dcc730d3-4d74-5e75-ae03-cd23c0ee742c,60d2d35e-bd32-36df-b8e0-b64a3494f0e8,2014-02-05 08:41:28+00:00,2014-04-14 08:41:28+00:00,outpatient,Encounter for problem (procedure),68.000000
16504,0b29bad1-7b3c-2585-1b31-c3dd7a6ec36a,a96d5031-46d5-e3f6-ec67-81f8edd48aa8,2017-09-30 13:44:27+00:00,2017-11-25 13:44:27+00:00,inpatient,Periodic reevaluation and management of health...,56.000000
6145,6053724d-e3b1-0449-402d-3090d3514389,f21a9c39-abd4-4e57-575d-83e1c29484da,2014-01-31 23:35:27+00:00,2014-03-26 23:35:27+00:00,outpatient,Encounter for problem (procedure),54.000000
8980,9741be00-49a5-f25a-a59b-ea46ffbad229,77dedc66-369c-bb18-940d-0db841255ef7,2014-09-14 10:42:36+00:00,2014-10-11 21:42:36+00:00,ambulatory,Follow-up encounter (procedure),27.458333
23048,6c108963-2fda-815b-3813-a424b3533127,01296e88-f6d9-1c18-cf91-87523325e034,2020-08-15 04:52:21+00:00,2020-09-08 17:52:21+00:00,emergency,Encounter for problem,24.541667
5457,d5c42fa8-f110-b714-d89a-04ec57038a58,0226f105-2572-1c6f-15f0-1aa0438e40d0,2013-10-22 00:16:17+00:00,2013-11-14 00:16:17+00:00,inpatient,Encounter for symptom (procedure),23.000000
14807,6fc6cbfc-ade5-c9ec-721c-4f71d9a1a815,2f6c035b-a11d-9373-89af-0cb2195592d2,2017-01-11 09:03:19+00:00,2017-01-27 09:03:19+00:00,emergency,Emergency room admission (procedure),16.000000
24226,96f41ac9-60c0-d035-249b-ea9f68dfb7da,2999ffe8-ab8a-3afa-ab9e-aa40fa162e8c,2021-01-12 14:24:46+00:00,2021-01-25 15:06:45+00:00,inpatient,Hospital admission for isolation (procedure),13.029155
24155,49a58342-2bed-0dec-5581-f12474408881,7811ad1e-3baf-5d00-6664-01c7396f67c9,2021-01-03 03:22:46+00:00,2021-01-16 04:02:42+00:00,inpatient,Hospital admission for isolation (procedure),13.027731
23972,d12cbc08-c639-0917-6250-66eca2e6995f,97c4cfee-e860-e908-1797-8da4dc241ec4,2020-12-12 19:05:25+00:00,2020-12-25 19:32:34+00:00,inpatient,Hospital admission for isolation (procedure),13.018854

# Stage 4 — Exploratory Data Analysis (EDA)

## Objectives

- Understand patient demographics
- Understand healthcare utilization patterns
- Analyze encounter types and volumes
- Examine procedure activity
- Explore healthcare costs and payer coverage
- Identify temporal trends
- Identify unusual patterns and potential business questions

## EDA Principle

EDA is exploratory rather than conclusive. Findings from this stage will be used to formulate business questions for deeper analysis.

In [99]:
# ============================================================
# STEP 4.2 — DATASET SUMMARY
# ============================================================

eda_summary = pd.DataFrame({
    "Dataset": [
        "Patients",
        "Encounters",
        "Procedures",
        "Payers",
        "Organizations"
    ],
    "Rows": [
        len(patients_clean),
        len(encounters_clean),
        len(procedures_clean),
        len(payers_clean),
        len(organizations_clean)
    ],
    "Columns": [
        len(patients_clean.columns),
        len(encounters_clean.columns),
        len(procedures_clean.columns),
        len(payers_clean.columns),
        len(organizations_clean.columns)
    ]
})

eda_summary

         Dataset   Rows  Columns
0       Patients    974       28
1     Encounters  27891       26
2     Procedures  47701       21
3         Payers     10        7
4  Organizations      1        8

In [100]:
# ============================================================
# 4.3.1 Gender Distribution
# ============================================================

gender_distribution = (
    patients_clean["GENDER"]
    .value_counts()
    .reset_index()
)

gender_distribution.columns = ["Gender", "Patients"]

gender_distribution["Percentage"] = (
    gender_distribution["Patients"]
    / len(patients_clean)
    * 100
).round(2)

gender_distribution

  Gender  Patients  Percentage
0      M       494       50.72
1      F       480       49.28

In [101]:
# ============================================================
# 4.3.2 Race Distribution
# ============================================================

race_distribution = (
    patients_clean["RACE"]
    .value_counts()
    .reset_index()
)

race_distribution.columns = ["Race", "Patients"]

race_distribution["Percentage"] = (
    race_distribution["Patients"]
    / len(patients_clean)
    * 100
).round(2)

In [102]:


# ============================================================
# Ethnicity Distribution
# ============================================================
ethnicity_distribution = (
    patients_clean["ETHNICITY"]
    .value_counts()
    .reset_index()
)

ethnicity_distribution.columns = ["Ethnicity", "Patients"]

ethnicity_distribution["Percentage"] = (
    ethnicity_distribution["Patients"]
    / len(patients_clean)
    * 100
).round(2)

ethnicity_distribution

     Ethnicity  Patients  Percentage
0  nonhispanic       783       80.39
1     hispanic       191       19.61

In [103]:
# ============================================================
# 4.3.4 Marital Status
# ============================================================

marital_distribution = (
    patients_clean["MARITAL"]
    .fillna("Unknown")
    .value_counts()
    .reset_index()
)

marital_distribution.columns = ["Marital_Status", "Patients"]

marital_distribution["Percentage"] = (
    marital_distribution["Patients"]
    / len(patients_clean)
    * 100
).round(2)

marital_distribution

  Marital_Status  Patients  Percentage
0              M       784       80.49
1              S       189       19.40
2        Unknown         1        0.10

In [104]:
# ============================================================
# STAGE 4.1 — STANDARDIZE DATE TIMEZONE BEFORE AGE CALCULATION
# ============================================================

# Make patient birthdates timezone-aware (UTC)
patients_age = patients_clean.copy()

patients_age["BIRTHDATE"] = pd.to_datetime(
    patients_age["BIRTHDATE"],
    errors="coerce",
    utc=True
)

# Make encounter START timezone-aware (UTC)
encounters_clean["START"] = pd.to_datetime(
    encounters_clean["START"],
    errors="coerce",
    utc=True
)

# Create birthdate lookup
birthdate_lookup = patients_age.set_index("Id")["BIRTHDATE"]

# Match each encounter to the patient's birthdate
encounter_birthdates = encounters_clean["PATIENT"].map(
    birthdate_lookup
)

# Calculate age at encounter
encounters_clean["AGE_AT_ENCOUNTER"] = (
    encounters_clean["START"] - encounter_birthdates
).dt.days / 365.25

# Round age
encounters_clean["AGE_AT_ENCOUNTER"] = (
    encounters_clean["AGE_AT_ENCOUNTER"].round(1)
)

print("Age calculation completed successfully.")

encounters_clean[
    ["Id", "PATIENT", "START", "AGE_AT_ENCOUNTER"]
].head(10)

Age calculation completed successfully.

,Id,PATIENT,START,AGE_AT_ENCOUNTER
0,32c84703-2481-49cd-d571-3899d5820253,3de74169-7f67-9304-91d4-757e0f3a14d2,2011-01-02 09:26:36+00:00,82.4
1,c98059da-320a-c0a6-fced-c8815f3e3f39,d9ec2e44-32e9-9148-179a-1653348cc4e2,2011-01-03 05:44:39+00:00,47.0
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,73babadf-5b2b-fee7-189e-6f41ff213e01,2011-01-03 14:32:11+00:00,86.5
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,3b46a0b7-0f34-9b9a-c319-ace4a1f58c0b,2011-01-03 16:24:45+00:00,87.6
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,fa006887-d93c-d302-8b89-f3c25f88c0e1,2011-01-03 17:36:53+00:00,58.2
5,c4923a74-3e40-8b0c-cf73-05b9c0390621,823c6b40-9dbe-e463-310b-ea2b23b23b48,2011-01-03 19:08:16+00:00,88.2
6,c140ed81-040e-8319-e860-f72b4738ed22,9c616fc0-00ea-249f-d073-1f3bb15d41fa,2011-01-03 22:39:50+00:00,25.3
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,d856d6e6-4c98-e7a2-129b-44076c63d008,2011-01-04 14:49:55+00:00,56.4
8,16bdc066-886f-34e1-38fa-afb85090b637,a80b1160-93f0-db7e-9f23-04ea6fdddfaf,2011-01-04 15:13:10+00:00,82.5
9,17966936-0878-f4db-128b-a43ae10d0878,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,2011-01-05 04:02:09+00:00,81.2

In [105]:
print("Missing ages:", encounters_clean["AGE_AT_ENCOUNTER"].isna().sum())
print("Negative ages:", (encounters_clean["AGE_AT_ENCOUNTER"] < 0).sum())

print("\nAge statistics:")
print(encounters_clean["AGE_AT_ENCOUNTER"].describe())

Missing ages: 0
Negative ages: 0

Age statistics:
count    27891.000000
mean        71.172819
std         20.304932
min         19.900000
25%         56.300000
50%         79.700000
75%         86.900000
max         99.300000
Name: AGE_AT_ENCOUNTER, dtype: float64

In [106]:
# ============================================================
# STEP 4.13A — INSPECT ENCOUNTER CLASS VALUES
# ============================================================

print("=" * 70)
print("STEP 4.13A — ENCOUNTER CLASS DISTRIBUTION")
print("=" * 70)

encounter_class_distribution = (
    encounters_clean["ENCOUNTERCLASS"]
    .value_counts(dropna=False)
    .rename_axis("Encounter_Class")
    .reset_index(name="Encounter_Count")
)

display(encounter_class_distribution)

======================================================================
STEP 4.13A — ENCOUNTER CLASS DISTRIBUTION
======================================================================

  Encounter_Class  Encounter_Count
0      ambulatory            12537
1      outpatient             6300
2      urgentcare             3666
3       emergency             2322
4        wellness             1931
5       inpatient             1135

In [107]:
print("ENCOUNTER CLASS COLUMN:")
print(
    [col for col in encounters_clean.columns
     if "ENCOUNTERCLASS" in col.upper()]
)

ENCOUNTER CLASS COLUMN:
['ENCOUNTERCLASS']

In [108]:
import pandas as pd
import numpy as np

In [109]:
# ============================================================
# STEP 4.13B — PATIENT-LEVEL CLINICAL UTILIZATION
# ============================================================

print("=" * 70)
print("STEP 4.13B — PATIENT-LEVEL CLINICAL UTILIZATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Create working copy
# ------------------------------------------------------------

patient_clinical_utilization = encounters_clean[
    ["PATIENT", "ENCOUNTERCLASS"]
].copy()


# ------------------------------------------------------------
# 2. Standardize encounter class for classification
# ------------------------------------------------------------

patient_clinical_utilization["ENCOUNTERCLASS"] = (
    patient_clinical_utilization["ENCOUNTERCLASS"]
    .astype("string")
    .str.strip()
    .str.lower()
)


# ------------------------------------------------------------
# 3. Create encounter-type indicators
# ------------------------------------------------------------

patient_clinical_utilization["Is_Inpatient"] = (
    patient_clinical_utilization["ENCOUNTERCLASS"]
    == "inpatient"
).astype(int)


patient_clinical_utilization["Is_Emergency"] = (
    patient_clinical_utilization["ENCOUNTERCLASS"]
    == "emergency"
).astype(int)


patient_clinical_utilization["Is_Outpatient"] = (
    patient_clinical_utilization["ENCOUNTERCLASS"]
    == "outpatient"
).astype(int)


patient_clinical_utilization["Is_Ambulatory"] = (
    patient_clinical_utilization["ENCOUNTERCLASS"]
    == "ambulatory"
).astype(int)


patient_clinical_utilization["Is_UrgentCare"] = (
    patient_clinical_utilization["ENCOUNTERCLASS"]
    == "urgentcare"
).astype(int)


patient_clinical_utilization["Is_Wellness"] = (
    patient_clinical_utilization["ENCOUNTERCLASS"]
    == "wellness"
).astype(int)


# ------------------------------------------------------------
# 4. Define high-acuity encounters
#
# High-acuity = Emergency + Inpatient
# ------------------------------------------------------------

patient_clinical_utilization["Is_High_Acuity"] = (
    patient_clinical_utilization["ENCOUNTERCLASS"]
    .isin(["emergency", "inpatient"])
).astype(int)


# ------------------------------------------------------------
# 5. Aggregate encounters at patient level
# ------------------------------------------------------------

patient_clinical_utilization = (
    patient_clinical_utilization
    .groupby("PATIENT")
    .agg(
        Encounter_Count=("PATIENT", "size"),

        Inpatient_Encounters=("Is_Inpatient", "sum"),

        Emergency_Encounters=("Is_Emergency", "sum"),

        Outpatient_Encounters=("Is_Outpatient", "sum"),

        Ambulatory_Encounters=("Is_Ambulatory", "sum"),

        UrgentCare_Encounters=("Is_UrgentCare", "sum"),

        Wellness_Encounters=("Is_Wellness", "sum"),

        High_Acuity_Encounters=("Is_High_Acuity", "sum")
    )
    .reset_index()
)


# ------------------------------------------------------------
# 6. Calculate utilization rates
# ------------------------------------------------------------

patient_clinical_utilization["Emergency_Rate"] = (
    patient_clinical_utilization["Emergency_Encounters"]
    / patient_clinical_utilization["Encounter_Count"]
    * 100
)


patient_clinical_utilization["Inpatient_Rate"] = (
    patient_clinical_utilization["Inpatient_Encounters"]
    / patient_clinical_utilization["Encounter_Count"]
    * 100
)


patient_clinical_utilization["High_Acuity_Rate"] = (
    patient_clinical_utilization["High_Acuity_Encounters"]
    / patient_clinical_utilization["Encounter_Count"]
    * 100
)


# ------------------------------------------------------------
# 7. Protect against division-by-zero
# ------------------------------------------------------------

rate_columns = [
    "Emergency_Rate",
    "Inpatient_Rate",
    "High_Acuity_Rate"
]

patient_clinical_utilization[rate_columns] = (
    patient_clinical_utilization[rate_columns]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)


# ------------------------------------------------------------
# 8. Round utilization rates
# ------------------------------------------------------------

patient_clinical_utilization[rate_columns] = (
    patient_clinical_utilization[rate_columns]
    .round(2)
)


# ------------------------------------------------------------
# 9. Sort by total utilization
# ------------------------------------------------------------

patient_clinical_utilization = (
    patient_clinical_utilization
    .sort_values(
        "Encounter_Count",
        ascending=False
    )
    .reset_index(drop=True)
)


# ------------------------------------------------------------
# 10. Display top 10 patients
# ------------------------------------------------------------

print("\nTOP 10 PATIENTS BY TOTAL ENCOUNTERS")

display(
    patient_clinical_utilization.head(10)
)

======================================================================
STEP 4.13B — PATIENT-LEVEL CLINICAL UTILIZATION
======================================================================

TOP 10 PATIENTS BY TOTAL ENCOUNTERS

,PATIENT,Encounter_Count,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters,High_Acuity_Encounters,Emergency_Rate,Inpatient_Rate,High_Acuity_Rate
0,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,0,0,77,1304,0,0,0,0.00,0.0,0.00
1,5e055638-0dad-dfd5-005d-1e74b6fd29ac,887,0,17,92,778,0,0,17,1.92,0.0,1.92
2,3de74169-7f67-9304-91d4-757e0f3a14d2,877,0,49,35,786,0,7,49,5.59,0.0,5.59
3,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,0,172,48,3,213,11,172,38.48,0.0,38.48
4,5dcb295d-92df-a147-ebcc-aa49b6262830,441,0,0,5,436,0,0,0,0.00,0.0,0.00
5,442dc617-c7f2-0513-15cd-c35c4efdba73,392,0,77,83,13,208,11,77,19.64,0.0,19.64
6,b4ab9ab3-f52a-751e-a990-3bd5654d5870,383,0,79,90,5,198,11,79,20.63,0.0,20.63
7,9b8ae606-5059-b3a6-19c7-c812901898bb,364,0,144,70,150,0,0,144,39.56,0.0,39.56
8,b4671e80-7e87-9260-ca31-6a9397d465d1,296,0,19,77,14,176,10,19,6.42,0.0,6.42
9,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,0,0,72,2,206,11,0,0.00,0.0,0.00

In [110]:
# ============================================================
# STEP 4.13C — PATIENT-LEVEL UTILIZATION VALIDATION
# ============================================================

print("=" * 70)
print("STEP 4.13C — PATIENT-LEVEL UTILIZATION VALIDATION")
print("=" * 70)


# ------------------------------------------------------------
# 1. Number of patients
# ------------------------------------------------------------

print(
    "Patients:",
    patient_clinical_utilization["PATIENT"].nunique()
)


# ------------------------------------------------------------
# 2. Total encounters
# ------------------------------------------------------------

print(
    "Total encounters:",
    patient_clinical_utilization["Encounter_Count"].sum()
)


# ------------------------------------------------------------
# 3. Encounter-type totals
# ------------------------------------------------------------

print(
    "Total inpatient encounters:",
    patient_clinical_utilization[
        "Inpatient_Encounters"
    ].sum()
)


print(
    "Total emergency encounters:",
    patient_clinical_utilization[
        "Emergency_Encounters"
    ].sum()
)


print(
    "Total outpatient encounters:",
    patient_clinical_utilization[
        "Outpatient_Encounters"
    ].sum()
)


print(
    "Total ambulatory encounters:",
    patient_clinical_utilization[
        "Ambulatory_Encounters"
    ].sum()
)


print(
    "Total urgent-care encounters:",
    patient_clinical_utilization[
        "UrgentCare_Encounters"
    ].sum()
)


print(
    "Total wellness encounters:",
    patient_clinical_utilization[
        "Wellness_Encounters"
    ].sum()
)


print(
    "Total high-acuity encounters:",
    patient_clinical_utilization[
        "High_Acuity_Encounters"
    ].sum()
)


# ------------------------------------------------------------
# 4. Reconciliation check
# ------------------------------------------------------------

encounter_type_total = (
    patient_clinical_utilization["Inpatient_Encounters"].sum()
    + patient_clinical_utilization["Emergency_Encounters"].sum()
    + patient_clinical_utilization["Outpatient_Encounters"].sum()
    + patient_clinical_utilization["Ambulatory_Encounters"].sum()
    + patient_clinical_utilization["UrgentCare_Encounters"].sum()
    + patient_clinical_utilization["Wellness_Encounters"].sum()
)


total_encounters = (
    patient_clinical_utilization["Encounter_Count"].sum()
)


print("\nENCOUNTER RECONCILIATION")
print("Encounter-type total:", encounter_type_total)
print("Patient-level total:", total_encounters)


if encounter_type_total == total_encounters:
    print("STATUS: PASS")
else:
    print("STATUS: FAIL")


# ------------------------------------------------------------
# 5. High-acuity reconciliation
# ------------------------------------------------------------

expected_high_acuity = (
    patient_clinical_utilization["Inpatient_Encounters"].sum()
    +
    patient_clinical_utilization["Emergency_Encounters"].sum()
)

actual_high_acuity = (
    patient_clinical_utilization["High_Acuity_Encounters"].sum()
)


print("\nHIGH-ACUITY RECONCILIATION")
print("Expected:", expected_high_acuity)
print("Actual:", actual_high_acuity)


if expected_high_acuity == actual_high_acuity:
    print("STATUS: PASS")
else:
    print("STATUS: FAIL")


# ------------------------------------------------------------
# 6. Rate validation
# ------------------------------------------------------------

rate_validation = pd.DataFrame({
    "Metric": [
        "Minimum Emergency Rate",
        "Maximum Emergency Rate",
        "Minimum Inpatient Rate",
        "Maximum Inpatient Rate",
        "Minimum High-Acuity Rate",
        "Maximum High-Acuity Rate"
    ],
    "Value": [
        patient_clinical_utilization["Emergency_Rate"].min(),
        patient_clinical_utilization["Emergency_Rate"].max(),
        patient_clinical_utilization["Inpatient_Rate"].min(),
        patient_clinical_utilization["Inpatient_Rate"].max(),
        patient_clinical_utilization["High_Acuity_Rate"].min(),
        patient_clinical_utilization["High_Acuity_Rate"].max()
    ]
})

print("\nRATE VALIDATION")

display(rate_validation)

======================================================================
STEP 4.13C — PATIENT-LEVEL UTILIZATION VALIDATION
======================================================================
Patients: 974
Total encounters: 27891
Total inpatient encounters: 1135
Total emergency encounters: 2322
Total outpatient encounters: 6300
Total ambulatory encounters: 12537
Total urgent-care encounters: 3666
Total wellness encounters: 1931
Total high-acuity encounters: 3457

ENCOUNTER RECONCILIATION
Encounter-type total: 27891
Patient-level total: 27891
STATUS: PASS

HIGH-ACUITY RECONCILIATION
Expected: 3457
Actual: 3457
STATUS: PASS

RATE VALIDATION

                     Metric  Value
0    Minimum Emergency Rate    0.0
1    Maximum Emergency Rate  100.0
2    Minimum Inpatient Rate    0.0
3    Maximum Inpatient Rate  100.0
4  Minimum High-Acuity Rate    0.0
5  Maximum High-Acuity Rate  100.0

In [111]:
# ============================================================
# STEP 4.14A — PATIENT-LEVEL FINANCIAL BURDEN
# ============================================================

print("=" * 70)
print("STEP 4.14A — PATIENT-LEVEL FINANCIAL BURDEN")
print("=" * 70)

# ------------------------------------------------------------
# 1. Inspect financial columns first
# ------------------------------------------------------------

print("\nENCOUNTER FINANCIAL COLUMNS:")
print([
    col for col in encounters_clean.columns
    if any(term in col.upper() for term in
           ["COST", "COVERAGE", "RESPONS", "CLAIM"])
])

print("\nPROCEDURE FINANCIAL COLUMNS:")
print([
    col for col in procedures_clean.columns
    if any(term in col.upper() for term in
           ["COST", "COVERAGE", "RESPONS", "CLAIM"])
])

======================================================================
STEP 4.14A — PATIENT-LEVEL FINANCIAL BURDEN
======================================================================

ENCOUNTER FINANCIAL COLUMNS:
['BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE']

PROCEDURE FINANCIAL COLUMNS:
['BASE_COST']

In [112]:
# ============================================================
# STEP 4.14A — ENCOUNTER PATIENT RESPONSIBILITY
# ============================================================

print("=" * 70)
print("STEP 4.14A — ENCOUNTER PATIENT RESPONSIBILITY")
print("=" * 70)


# ------------------------------------------------------------
# 1. Ensure financial columns are numeric
# ------------------------------------------------------------

financial_columns = [
    "BASE_ENCOUNTER_COST",
    "TOTAL_CLAIM_COST",
    "PAYER_COVERAGE"
]

for col in financial_columns:
    encounters_clean[col] = pd.to_numeric(
        encounters_clean[col],
        errors="coerce"
    )


# ------------------------------------------------------------
# 2. Calculate patient responsibility
# ------------------------------------------------------------

encounters_clean["PATIENT_RESPONSIBILITY"] = (
    encounters_clean["TOTAL_CLAIM_COST"]
    - encounters_clean["PAYER_COVERAGE"]
)


# ------------------------------------------------------------
# 3. Validate the calculation
# ------------------------------------------------------------

print("\nPATIENT RESPONSIBILITY SUMMARY")

display(
    encounters_clean[
        [
            "TOTAL_CLAIM_COST",
            "PAYER_COVERAGE",
            "PATIENT_RESPONSIBILITY"
        ]
    ].describe()
)


# ------------------------------------------------------------
# 4. Check for negative patient responsibility
# ------------------------------------------------------------

negative_patient_responsibility = (
    encounters_clean["PATIENT_RESPONSIBILITY"] < 0
).sum()

print(
    "\nNegative patient responsibility records:",
    negative_patient_responsibility
)


# ------------------------------------------------------------
# 5. Check missing values
# ------------------------------------------------------------

print(
    "Missing patient responsibility:",
    encounters_clean["PATIENT_RESPONSIBILITY"].isna().sum()
)


print("\nStep 4.14A completed successfully.")

======================================================================
STEP 4.14A — ENCOUNTER PATIENT RESPONSIBILITY
======================================================================

PATIENT RESPONSIBILITY SUMMARY

       TOTAL_CLAIM_COST  PAYER_COVERAGE  PATIENT_RESPONSIBILITY
count      27891.000000    27891.000000            27891.000000
mean        3639.682174     1114.965652             2524.716523
std         9205.595748     4768.615576             7661.005002
min            0.000000        0.000000                0.000000
25%          142.580000        0.000000               85.550000
50%          278.580000       28.440000              172.590000
75%         1412.530000      155.770000             1004.630000
max       641882.700000   247751.420000           641882.700000

Negative patient responsibility records: 0
Missing patient responsibility: 0

Step 4.14A completed successfully.

In [113]:
# ============================================================
# STEP 4.14B — PATIENT-LEVEL FINANCIAL AGGREGATION
# ============================================================
import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.14B — PATIENT-LEVEL FINANCIAL AGGREGATION")
print("=" * 70)

# ------------------------------------------------------------
# 1. Aggregate encounter-level financial burden by patient
# ------------------------------------------------------------

patient_financial_burden = (
    encounters_clean
    .groupby("PATIENT")
    .agg(
        Encounter_Count=("PATIENT", "size"),

        Total_Base_Encounter_Cost=(
            "BASE_ENCOUNTER_COST",
            "sum"
        ),

        Total_Claim_Cost=(
            "TOTAL_CLAIM_COST",
            "sum"
        ),

        Total_Payer_Coverage=(
            "PAYER_COVERAGE",
            "sum"
        ),

        Total_Patient_Responsibility=(
            "PATIENT_RESPONSIBILITY",
            "sum"
        )
    )
    .reset_index()
)

# ============================================================
# FINANCIAL RECONCILIATION CHECK
# ============================================================

encounters_clean["FINANCIAL_RECONCILIATION_DIFF"] = (
    encounters_clean["TOTAL_CLAIM_COST"]
    - (
        encounters_clean["PAYER_COVERAGE"]
        + encounters_clean["PATIENT_RESPONSIBILITY"]
    )
)

print("\nFinancial reconciliation check:")

print(
    "Maximum absolute difference:",
    encounters_clean[
        "FINANCIAL_RECONCILIATION_DIFF"
    ].abs().max()
)

print(
    "Records with non-zero difference:",
    (
        encounters_clean["FINANCIAL_RECONCILIATION_DIFF"]
        .abs() > 0.01
    ).sum()
)

# ------------------------------------------------------------
# 2. Aggregate procedure cost by patient
# ------------------------------------------------------------

patient_procedure_cost = (
    procedures_clean
    .groupby("PATIENT")
    .agg(
        Procedure_Count=("PATIENT", "size"),

        Total_Procedure_Cost=(
            "BASE_COST",
            "sum"
        )
    )
    .reset_index()
)


# ------------------------------------------------------------
# 3. Merge procedure financial information
# ------------------------------------------------------------

patient_financial_burden = patient_financial_burden.merge(
    patient_procedure_cost,
    on="PATIENT",
    how="left"
)


# ------------------------------------------------------------
# 4. Patients without procedures
# ------------------------------------------------------------

patient_financial_burden["Procedure_Count"] = (
    patient_financial_burden["Procedure_Count"]
    .fillna(0)
    .astype(int)
)

patient_financial_burden["Total_Procedure_Cost"] = (
    patient_financial_burden["Total_Procedure_Cost"]
    .fillna(0)
)


# ------------------------------------------------------------
# 5. Calculate average financial burden per encounter
# ------------------------------------------------------------

patient_financial_burden["Average_Cost_Per_Encounter"] = (
    patient_financial_burden["Total_Claim_Cost"]
    / patient_financial_burden["Encounter_Count"]
)

patient_financial_burden["Average_Payer_Coverage_Per_Encounter"] = (
    patient_financial_burden["Total_Payer_Coverage"]
    / patient_financial_burden["Encounter_Count"]
)

patient_financial_burden["Average_Patient_Responsibility_Per_Encounter"] = (
    patient_financial_burden["Total_Patient_Responsibility"]
    / patient_financial_burden["Encounter_Count"]
)


# ------------------------------------------------------------
# 6. Calculate patient responsibility rate
# ------------------------------------------------------------

patient_financial_burden["Patient_Responsibility_Rate"] = (
    patient_financial_burden["Total_Patient_Responsibility"]
    / patient_financial_burden["Total_Claim_Cost"]
    * 100
)


# ------------------------------------------------------------
# 7. Calculate payer coverage rate
# ------------------------------------------------------------

patient_financial_burden["Payer_Coverage_Rate"] = (
    patient_financial_burden["Total_Payer_Coverage"]
    / patient_financial_burden["Total_Claim_Cost"]
    * 100
)


# ------------------------------------------------------------
# 8. Protect against division-by-zero
# ------------------------------------------------------------

rate_columns = [
    "Patient_Responsibility_Rate",
    "Payer_Coverage_Rate"
]

average_columns = [
    "Average_Cost_Per_Encounter",
    "Average_Payer_Coverage_Per_Encounter",
    "Average_Patient_Responsibility_Per_Encounter"
]

patient_financial_burden[rate_columns + average_columns] = (
    patient_financial_burden[rate_columns + average_columns]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)


# ------------------------------------------------------------
# 9. Round analytical metrics
# ------------------------------------------------------------

patient_financial_burden[[
    "Total_Base_Encounter_Cost",
    "Total_Claim_Cost",
    "Total_Payer_Coverage",
    "Total_Patient_Responsibility",
    "Total_Procedure_Cost",
    "Average_Cost_Per_Encounter",
    "Average_Payer_Coverage_Per_Encounter",
    "Average_Patient_Responsibility_Per_Encounter"
]] = patient_financial_burden[[
    "Total_Base_Encounter_Cost",
    "Total_Claim_Cost",
    "Total_Payer_Coverage",
    "Total_Patient_Responsibility",
    "Total_Procedure_Cost",
    "Average_Cost_Per_Encounter",
    "Average_Payer_Coverage_Per_Encounter",
    "Average_Patient_Responsibility_Per_Encounter"
]].round(2)


# ------------------------------------------------------------
# 10. Sort by total patient responsibility
# ------------------------------------------------------------

patient_financial_burden = (
    patient_financial_burden
    .sort_values(
        "Total_Patient_Responsibility",
        ascending=False
    )
    .reset_index(drop=True)
)

# ------------------------------------------------------------
#  TOP 20% PATIENT COST CONCENTRATION
# ------------------------------------------------------------

top_20_count = max(
    1,
    int(np.ceil(len(patient_financial_burden) * 0.20))
)

patient_top20_percent_share = (
    patient_financial_burden
    .sort_values(
        "Total_Claim_Cost",
        ascending=False
    )
    .head(top_20_count)["Total_Claim_Cost"]
    .sum()
    / patient_financial_burden["Total_Claim_Cost"].sum()
    * 100
)

print(
    f"\nTop 20% of patients account for "
    f"{patient_top20_percent_share:.2f}% "
    f"of total claim cost."
)
# ------------------------------------------------------------
# 11. Display top 10
# ------------------------------------------------------------

print("\nTOP 10 PATIENTS BY TOTAL PATIENT RESPONSIBILITY")

display(
    patient_financial_burden.head(10)
)

======================================================================
STEP 4.14B — PATIENT-LEVEL FINANCIAL AGGREGATION
======================================================================

Financial reconciliation check:
Maximum absolute difference: 2.2737367544323206e-13
Records with non-zero difference: 0

Top 20% of patients account for 84.02% of total claim cost.

TOP 10 PATIENTS BY TOTAL PATIENT RESPONSIBILITY

,PATIENT,Encounter_Count,Total_Base_Encounter_Cost,Total_Claim_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Procedure_Count,Total_Procedure_Cost,Average_Cost_Per_Encounter,Average_Payer_Coverage_Per_Encounter,Average_Patient_Responsibility_Per_Encounter,Patient_Responsibility_Rate,Payer_Coverage_Rate
0,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,61494.41,9932262.99,0.00,9932262.99,759,9942253.0,22219.83,0.00,22219.83,100.000000,0.000000
1,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,37321.04,6356665.66,845233.69,5511431.97,828,6522854.0,21844.21,2904.58,18939.63,86.703191,13.296809
2,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,19412.51,3014121.02,0.00,3014121.02,142,2997592.0,21226.20,0.00,21226.20,100.000000,0.000000
3,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,17109.60,2699823.10,0.00,2699823.10,120,2681489.0,22498.53,0.00,22498.53,100.000000,0.000000
4,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,118258.61,2437415.31,0.00,2437415.31,1783,2489508.0,1764.96,0.00,1764.96,100.000000,0.000000
5,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,13402.52,2090033.12,0.00,2090033.12,94,2075677.0,22234.39,0.00,22234.39,100.000000,0.000000
6,37448778-ee2f-f420-1dc0-cb6b5e147025,53,7556.74,1206558.16,0.00,1206558.16,53,1198321.0,22765.25,0.00,22765.25,100.000000,0.000000
7,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,14785.70,1181185.96,0.00,1181185.96,207,1165519.0,11143.26,0.00,11143.26,100.000000,0.000000
8,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,19178.30,1127635.83,0.00,1127635.83,526,1261598.0,6264.64,0.00,6264.64,100.000000,0.000000
9,7412b008-76f9-b713-c514-2a5d82e3b39e,59,5224.72,983828.37,0.00,983828.37,361,860808.0,16675.06,0.00,16675.06,100.000000,0.000000

In [114]:
# ============================================================
# STEP 4.14C — PATIENT-LEVEL FINANCIAL VALIDATION
# ============================================================
import numpy as np

print("=" * 70)
print("STEP 4.14C — PATIENT-LEVEL FINANCIAL VALIDATION")
print("=" * 70)


# ------------------------------------------------------------
# Patient count
# ------------------------------------------------------------

print(
    "\nPatients:",
    len(patient_financial_burden)
)


# ------------------------------------------------------------
# Encounter reconciliation
# ------------------------------------------------------------

print(
    "Total encounters:",
    patient_financial_burden["Encounter_Count"].sum()
)

print(
    "Expected encounters:",
    len(encounters_clean)
)


# ------------------------------------------------------------
# Financial reconciliation
# ------------------------------------------------------------

print("\nFINANCIAL RECONCILIATION")

financial_validation = pd.DataFrame({
    "Metric": [
        "Total Base Encounter Cost",
        "Total Claim Cost",
        "Total Payer Coverage",
        "Total Patient Responsibility",
        "Total Procedure Cost"
    ],

    "Patient_Level_Total": [
        patient_financial_burden[
            "Total_Base_Encounter_Cost"
        ].sum(),

        patient_financial_burden[
            "Total_Claim_Cost"
        ].sum(),

        patient_financial_burden[
            "Total_Payer_Coverage"
        ].sum(),

        patient_financial_burden[
            "Total_Patient_Responsibility"
        ].sum(),

        patient_financial_burden[
            "Total_Procedure_Cost"
        ].sum()
    ],

    "Source_Level_Total": [
        encounters_clean[
            "BASE_ENCOUNTER_COST"
        ].sum(),

        encounters_clean[
            "TOTAL_CLAIM_COST"
        ].sum(),

        encounters_clean[
            "PAYER_COVERAGE"
        ].sum(),

        encounters_clean[
            "PATIENT_RESPONSIBILITY"
        ].sum(),

        procedures_clean[
            "BASE_COST"
        ].sum()
    ]
})


financial_validation["Difference"] = (
    financial_validation["Patient_Level_Total"]
    - financial_validation["Source_Level_Total"]
)

financial_validation["Status"] = np.where(
    np.isclose(
        financial_validation["Patient_Level_Total"],
        financial_validation["Source_Level_Total"],
        rtol=1e-9,
        atol=1e-2
    ),
    "PASS",
    "FAIL"
)

display(financial_validation)


# ------------------------------------------------------------
# Rate validation
# ------------------------------------------------------------

print("\nRATE VALIDATION")

rate_validation = pd.DataFrame({
    "Metric": [
        "Minimum Patient Responsibility Rate",
        "Maximum Patient Responsibility Rate",
        "Minimum Payer Coverage Rate",
        "Maximum Payer Coverage Rate"
    ],

    "Value": [
        patient_financial_burden[
            "Patient_Responsibility_Rate"
        ].min(),

        patient_financial_burden[
            "Patient_Responsibility_Rate"
        ].max(),

        patient_financial_burden[
            "Payer_Coverage_Rate"
        ].min(),

        patient_financial_burden[
            "Payer_Coverage_Rate"
        ].max()
    ]
})

display(rate_validation)

======================================================================
STEP 4.14C — PATIENT-LEVEL FINANCIAL VALIDATION
======================================================================

Patients: 974
Total encounters: 27891
Expected encounters: 27891

FINANCIAL RECONCILIATION

,Metric,Patient_Level_Total,Source_Level_Total,Difference,Status
0,Total Base Encounter Cost,3.240421e+06,3.240421e+06,0.000000e+00,PASS
1,Total Claim Cost,1.015144e+08,1.015144e+08,-1.490116e-08,PASS
2,Total Payer Coverage,3.109751e+07,3.109751e+07,0.000000e+00,PASS
3,Total Patient Responsibility,7.041687e+07,7.041687e+07,0.000000e+00,PASS
4,Total Procedure Cost,1.055177e+08,1.055177e+08,0.000000e+00,PASS

RATE VALIDATION

                                Metric       Value
0  Minimum Patient Responsibility Rate    0.000000
1  Maximum Patient Responsibility Rate  100.000000
2          Minimum Payer Coverage Rate    0.000000
3          Maximum Payer Coverage Rate   94.731664

In [115]:
# ======================================================================
# STEP 4.15A — DEMOGRAPHIC × UTILIZATION PREPARATION
# ======================================================================

print("=" * 70)
print("STEP 4.15A — DEMOGRAPHIC × UTILIZATION PREPARATION")
print("=" * 70)


# ----------------------------------------------------------------------
# 1. Confirm required source datasets exist
# ----------------------------------------------------------------------

required_objects = [
    "patients_clean",
    "patient_clinical_utilization"
]

for obj in required_objects:
    if obj not in globals():
        raise NameError(
            f"Required dataset '{obj}' is not available. "
            f"Run the earlier patient-level analysis first."
        )


# ----------------------------------------------------------------------
# 2. Display available patient demographic columns
# ----------------------------------------------------------------------

demographic_candidates = [
    "GENDER",
    "RACE",
    "ETHNICITY",
    "MARITAL",
    "AGE_GROUP"
]

available_demographics = [
    col for col in demographic_candidates
    if col in patients_clean.columns
]

missing_demographics = [
    col for col in demographic_candidates
    if col not in patients_clean.columns
]

print("\nAVAILABLE DEMOGRAPHIC COLUMNS:")
print(available_demographics)

if missing_demographics:
    print("\nNOT FOUND:")
    print(missing_demographics)


# ----------------------------------------------------------------------
# 3. Confirm patient-level utilization columns
# ----------------------------------------------------------------------

utilization_columns = [
    "PATIENT",
    "Encounter_Count",
    "Inpatient_Encounters",
    "Emergency_Encounters",
    "High_Acuity_Encounters",
    "Emergency_Rate",
    "High_Acuity_Rate"
]

missing_utilization = [
    col for col in utilization_columns
    if col not in patient_clinical_utilization.columns
]

if missing_utilization:
    raise KeyError(
        f"Missing utilization columns: {missing_utilization}"
    )

print("\nUTILIZATION COLUMNS VERIFIED:")
print(utilization_columns)


# ----------------------------------------------------------------------
# 4. Select demographic columns that actually exist
# ----------------------------------------------------------------------

demographic_columns = available_demographics.copy()

if not demographic_columns:
    raise ValueError(
        "None of the expected demographic columns were found "
        "in patients_clean."
    )


# ----------------------------------------------------------------------
# 5. Create a clean demographic source table
# ----------------------------------------------------------------------

patient_demographics = patients_clean[
    ["Id"] + demographic_columns
].copy()

patient_demographics = patient_demographics.rename(
    columns={"Id": "PATIENT"}
)


# ----------------------------------------------------------------------
# 6. Standardize categorical demographic values
# ----------------------------------------------------------------------

for col in demographic_columns:

    patient_demographics[col] = (
        patient_demographics[col]
        .astype("string")
        .str.strip()
    )

    patient_demographics[col] = (
        patient_demographics[col]
        .replace(
            {
                "": "Unknown",
                "nan": "Unknown",
                "None": "Unknown",
                "<NA>": "Unknown"
            }
        )
        .fillna("Unknown")
    )


# ----------------------------------------------------------------------
# 7. Merge demographics with validated patient-level utilization
# ----------------------------------------------------------------------

patient_demographic_utilization = patient_demographics.merge(
    patient_clinical_utilization,
    on="PATIENT",
    how="inner",
    validate="one_to_one"
)


# ----------------------------------------------------------------------
# 8. Basic merge validation
# ----------------------------------------------------------------------

print("\nMERGE VALIDATION")
print("-" * 70)

print(
    "Patients in patients_clean:",
    patients_clean["Id"].nunique()
)

print(
    "Patients in utilization table:",
    patient_clinical_utilization["PATIENT"].nunique()
)

print(
    "Patients after demographic/utilization merge:",
    patient_demographic_utilization["PATIENT"].nunique()
)


# ----------------------------------------------------------------------
# 9. Display resulting structure
# ----------------------------------------------------------------------

print("\nDEMOGRAPHIC × UTILIZATION COLUMNS:")
print(patient_demographic_utilization.columns.tolist())


# ----------------------------------------------------------------------
# 10. Preview
# ----------------------------------------------------------------------

patient_demographic_utilization.head()

======================================================================
STEP 4.15A — DEMOGRAPHIC × UTILIZATION PREPARATION
======================================================================

AVAILABLE DEMOGRAPHIC COLUMNS:
['GENDER', 'RACE', 'ETHNICITY', 'MARITAL']

NOT FOUND:
['AGE_GROUP']

UTILIZATION COLUMNS VERIFIED:
['PATIENT', 'Encounter_Count', 'Inpatient_Encounters', 'Emergency_Encounters', 'High_Acuity_Encounters', 'Emergency_Rate', 'High_Acuity_Rate']

MERGE VALIDATION
----------------------------------------------------------------------
Patients in patients_clean: 974
Patients in utilization table: 974
Patients after demographic/utilization merge: 974

DEMOGRAPHIC × UTILIZATION COLUMNS:
['PATIENT', 'GENDER', 'RACE', 'ETHNICITY', 'MARITAL', 'Encounter_Count', 'Inpatient_Encounters', 'Emergency_Encounters', 'Outpatient_Encounters', 'Ambulatory_Encounters', 'UrgentCare_Encounters', 'Wellness_Encounters', 'High_Acuity_Encounters', 'Emergency_Rate', 'Inpatient_Rate', 'High_Acuity_Rate']

,PATIENT,GENDER,RACE,ETHNICITY,MARITAL,Encounter_Count,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters,High_Acuity_Encounters,Emergency_Rate,Inpatient_Rate,High_Acuity_Rate
0,5605b66b-e92d-c16c-1b83-b8bf7040d51f,F,white,nonhispanic,M,18,0,1,0,17,0,0,1,5.56,0.00,5.56
1,6e5ae27c-8038-7988-e2c0-25a103f01bfa,M,white,nonhispanic,M,1,0,1,0,0,0,0,1,100.00,0.00,100.00
2,8123d076-0886-9007-e956-d5864aa121a7,M,white,nonhispanic,M,7,0,0,3,4,0,0,0,0.00,0.00,0.00
3,770518e4-6133-648e-60c9-071eb2f0e2ce,M,white,hispanic,M,27,0,2,4,21,0,0,2,7.41,0.00,7.41
4,f96addf5-81b9-0aab-7855-d208d3d352c5,M,white,hispanic,M,9,1,1,0,7,0,0,2,11.11,11.11,22.22

In [116]:
# ======================================================================
# STEP 4.15B — DEMOGRAPHIC × UTILIZATION AGGREGATION
# ======================================================================

print("=" * 70)
print("STEP 4.15B — DEMOGRAPHIC × UTILIZATION AGGREGATION")
print("=" * 70)


# ----------------------------------------------------------------------
# 1. Define aggregation function
# ----------------------------------------------------------------------

def create_demographic_utilization_summary(
    dataframe,
    demographic_column
):

    summary = (
        dataframe
        .groupby(demographic_column, dropna=False)
        .agg(
            Patient_Count=("PATIENT", "nunique"),

            Total_Encounters=("Encounter_Count", "sum"),

            Average_Encounters_Per_Patient=(
                "Encounter_Count",
                "mean"
            ),

            Median_Encounters_Per_Patient=(
                "Encounter_Count",
                "median"
            ),

            Total_Inpatient_Encounters=(
                "Inpatient_Encounters",
                "sum"
            ),

            Total_Emergency_Encounters=(
                "Emergency_Encounters",
                "sum"
            ),

            Total_High_Acuity_Encounters=(
                "High_Acuity_Encounters",
                "sum"
            ),

            Average_Emergency_Rate=(
                "Emergency_Rate",
                "mean"
            ),

            Average_High_Acuity_Rate=(
                "High_Acuity_Rate",
                "mean"
            )
        )
        .reset_index()
    )


    # ------------------------------------------------------------------
    # Calculate group-level rates
    # ------------------------------------------------------------------

    summary["Emergency_Rate"] = (
        summary["Total_Emergency_Encounters"]
        / summary["Total_Encounters"]
        * 100
    )


    summary["High_Acuity_Rate"] = (
        summary["Total_High_Acuity_Encounters"]
        / summary["Total_Encounters"]
        * 100
    )


    # ------------------------------------------------------------------
    # Replace invalid mathematical results
    # ------------------------------------------------------------------

    rate_columns = [
        "Emergency_Rate",
        "High_Acuity_Rate",
        "Average_Emergency_Rate",
        "Average_High_Acuity_Rate"
    ]

    summary[rate_columns] = (
        summary[rate_columns]
        .replace([float("inf"), -float("inf")], 0)
        .fillna(0)
    )


    # ------------------------------------------------------------------
    # Sort by total utilization
    # ------------------------------------------------------------------

    summary = (
        summary
        .sort_values(
            "Total_Encounters",
            ascending=False
        )
        .reset_index(drop=True)
    )


    return summary


# ----------------------------------------------------------------------
# 2. Create demographic summaries
# ----------------------------------------------------------------------

demographic_utilization_summaries = {}


for demographic in demographic_columns:

    demographic_utilization_summaries[demographic] = (
        create_demographic_utilization_summary(
            patient_demographic_utilization,
            demographic
        )
    )


# ----------------------------------------------------------------------
# 3. Create convenient named tables
# ----------------------------------------------------------------------

if "GENDER" in demographic_utilization_summaries:
    gender_utilization = demographic_utilization_summaries["GENDER"]

if "RACE" in demographic_utilization_summaries:
    race_utilization = demographic_utilization_summaries["RACE"]

if "ETHNICITY" in demographic_utilization_summaries:
    ethnicity_utilization = demographic_utilization_summaries["ETHNICITY"]

if "MARITAL" in demographic_utilization_summaries:
    marital_utilization = demographic_utilization_summaries["MARITAL"]

if "AGE_GROUP" in demographic_utilization_summaries:
    age_group_utilization = demographic_utilization_summaries["AGE_GROUP"]


# ----------------------------------------------------------------------
# 4. Display each demographic analysis
# ----------------------------------------------------------------------

for demographic, summary in demographic_utilization_summaries.items():

    print("\n")
    print("=" * 70)
    print(f"{demographic} × UTILIZATION")
    print("=" * 70)

    display(summary)


# ----------------------------------------------------------------------
# 5. Identify groups with highest utilization
# ----------------------------------------------------------------------

print("\n")
print("=" * 70)
print("HIGHEST-UTILIZATION GROUPS")
print("=" * 70)


for demographic, summary in demographic_utilization_summaries.items():

    if len(summary) == 0:
        continue

    highest_group = summary.iloc[0]

    print(
        f"\n{demographic}: "
        f"{highest_group[demographic]} "
        f"→ "
        f"{highest_group['Total_Encounters']:,.0f} encounters "
        f"across "
        f"{highest_group['Patient_Count']:,.0f} patients"
    )

======================================================================
STEP 4.15B — DEMOGRAPHIC × UTILIZATION AGGREGATION
======================================================================


======================================================================
GENDER × UTILIZATION
======================================================================

,GENDER,Patient_Count,Total_Encounters,Average_Encounters_Per_Patient,Median_Encounters_Per_Patient,Total_Inpatient_Encounters,Total_Emergency_Encounters,Total_High_Acuity_Encounters,Average_Emergency_Rate,Average_High_Acuity_Rate,Emergency_Rate,High_Acuity_Rate
0,F,480,14924,31.091667,17.0,710,1031,1741,7.316021,11.286208,6.908336,11.665773
1,M,494,12967,26.248988,12.0,425,1291,1716,9.905223,12.363684,9.956042,13.233593

======================================================================
RACE × UTILIZATION
======================================================================

,RACE,Patient_Count,Total_Encounters,Average_Encounters_Per_Patient,Median_Encounters_Per_Patient,Total_Inpatient_Encounters,Total_Emergency_Encounters,Total_High_Acuity_Encounters,Average_Emergency_Rate,Average_High_Acuity_Rate,Emergency_Rate,High_Acuity_Rate
0,white,680,19460,28.617647,14.0,848,1284,2132,8.770324,12.195265,6.598150,10.955807
1,black,163,4403,27.012270,15.0,186,752,938,10.380368,14.105276,17.079264,21.303657
2,asian,91,2519,27.681319,12.0,86,111,197,4.121319,5.705275,4.406511,7.820564
3,native,11,859,78.090909,22.0,2,95,97,8.533636,8.890909,11.059371,11.292200
4,hawaiian,13,371,28.538462,20.0,2,17,19,6.350000,6.631538,4.582210,5.121294
5,other,16,279,17.437500,9.5,11,63,74,12.349375,14.369375,22.580645,26.523297

======================================================================
ETHNICITY × UTILIZATION
======================================================================

,ETHNICITY,Patient_Count,Total_Encounters,Average_Encounters_Per_Patient,Median_Encounters_Per_Patient,Total_Inpatient_Encounters,Total_Emergency_Encounters,Total_High_Acuity_Encounters,Average_Emergency_Rate,Average_High_Acuity_Rate,Emergency_Rate,High_Acuity_Rate
0,nonhispanic,783,23261,29.707535,14.0,957,1908,2865,8.707727,11.991609,8.202571,12.316753
1,hispanic,191,4630,24.240838,15.0,178,414,592,8.307435,11.181204,8.941685,12.786177

======================================================================
MARITAL × UTILIZATION
======================================================================

,MARITAL,Patient_Count,Total_Encounters,Average_Encounters_Per_Patient,Median_Encounters_Per_Patient,Total_Inpatient_Encounters,Total_Emergency_Encounters,Total_High_Acuity_Encounters,Average_Emergency_Rate,Average_High_Acuity_Rate,Emergency_Rate,High_Acuity_Rate
0,M,784,23653,30.169643,14.0,969,2082,3051,8.949043,12.361186,8.802266,12.898998
1,S,189,4226,22.359788,14.0,165,239,404,7.304180,9.614815,5.655466,9.559867
2,Unknown,1,12,12.000000,12.0,1,1,2,8.330000,16.670000,8.333333,16.666667

======================================================================
HIGHEST-UTILIZATION GROUPS
======================================================================

GENDER: F → 14,924 encounters across 480 patients

RACE: white → 19,460 encounters across 680 patients

ETHNICITY: nonhispanic → 23,261 encounters across 783 patients

MARITAL: M → 23,653 encounters across 784 patients

In [117]:
# ======================================================================
# STEP 4.15C — DEMOGRAPHIC × UTILIZATION VALIDATION
# ======================================================================

print("=" * 70)
print("STEP 4.15C — DEMOGRAPHIC × UTILIZATION VALIDATION")
print("=" * 70)


# ----------------------------------------------------------------------
# 1. Patient-level merge validation
# ----------------------------------------------------------------------

source_patient_count = patients_clean["Id"].nunique()

utilization_patient_count = (
    patient_clinical_utilization["PATIENT"].nunique()
)

merged_patient_count = (
    patient_demographic_utilization["PATIENT"].nunique()
)


print("\nPATIENT COUNT VALIDATION")
print("-" * 70)

print("Patients in patients_clean:", source_patient_count)
print("Patients in utilization:", utilization_patient_count)
print("Patients after merge:", merged_patient_count)


patient_count_status = (
    source_patient_count
    == utilization_patient_count
    == merged_patient_count
)

print(
    "STATUS:",
    "PASS" if patient_count_status else "FAIL"
)


# ----------------------------------------------------------------------
# 2. Encounter reconciliation
# ----------------------------------------------------------------------

source_encounter_total = (
    patient_clinical_utilization["Encounter_Count"].sum()
)

demographic_encounter_results = []


for demographic, summary in demographic_utilization_summaries.items():

    grouped_total = summary["Total_Encounters"].sum()

    difference = grouped_total - source_encounter_total

    demographic_encounter_results.append(
        {
            "Demographic": demographic,
            "Patient_Level_Total": grouped_total,
            "Source_Level_Total": source_encounter_total,
            "Difference": difference,
            "Status": (
                "PASS"
                if abs(difference) < 1e-9
                else "FAIL"
            )
        }
    )


demographic_encounter_validation = pd.DataFrame(
    demographic_encounter_results
)


print("\nENCOUNTER RECONCILIATION")
print("-" * 70)

display(demographic_encounter_validation)


# ----------------------------------------------------------------------
# 3. High-acuity reconciliation
# ----------------------------------------------------------------------

source_high_acuity_total = (
    patient_clinical_utilization[
        "High_Acuity_Encounters"
    ].sum()
)

high_acuity_results = []


for demographic, summary in demographic_utilization_summaries.items():

    grouped_total = (
        summary["Total_High_Acuity_Encounters"]
        .sum()
    )

    difference = (
        grouped_total
        - source_high_acuity_total
    )

    high_acuity_results.append(
        {
            "Demographic": demographic,
            "Patient_Level_Total": grouped_total,
            "Source_Level_Total": source_high_acuity_total,
            "Difference": difference,
            "Status": (
                "PASS"
                if abs(difference) < 1e-9
                else "FAIL"
            )
        }
    )


high_acuity_validation = pd.DataFrame(
    high_acuity_results
)


print("\nHIGH-ACUITY RECONCILIATION")
print("-" * 70)

display(high_acuity_validation)


# ----------------------------------------------------------------------
# 4. Emergency reconciliation
# ----------------------------------------------------------------------

source_emergency_total = (
    patient_clinical_utilization[
        "Emergency_Encounters"
    ].sum()
)

emergency_results = []


for demographic, summary in demographic_utilization_summaries.items():

    grouped_total = (
        summary["Total_Emergency_Encounters"]
        .sum()
    )

    difference = (
        grouped_total
        - source_emergency_total
    )

    emergency_results.append(
        {
            "Demographic": demographic,
            "Patient_Level_Total": grouped_total,
            "Source_Level_Total": source_emergency_total,
            "Difference": difference,
            "Status": (
                "PASS"
                if abs(difference) < 1e-9
                else "FAIL"
            )
        }
    )


emergency_validation = pd.DataFrame(
    emergency_results
)


print("\nEMERGENCY RECONCILIATION")
print("-" * 70)

display(emergency_validation)


# ----------------------------------------------------------------------
# 5. Validate rate ranges
# ----------------------------------------------------------------------

rate_validation = pd.DataFrame(
    {
        "Metric": [
            "Minimum Emergency Rate",
            "Maximum Emergency Rate",
            "Minimum High-Acuity Rate",
            "Maximum High-Acuity Rate"
        ],
        "Value": [
            patient_demographic_utilization[
                "Emergency_Rate"
            ].min(),

            patient_demographic_utilization[
                "Emergency_Rate"
            ].max(),

            patient_demographic_utilization[
                "High_Acuity_Rate"
            ].min(),

            patient_demographic_utilization[
                "High_Acuity_Rate"
            ].max()
        ]
    }
)


print("\nRATE VALIDATION")
print("-" * 70)

display(rate_validation)


# ----------------------------------------------------------------------
# 6. Final validation status
# ----------------------------------------------------------------------

all_encounter_pass = (
    demographic_encounter_validation["Status"]
    .eq("PASS")
    .all()
)

all_high_acuity_pass = (
    high_acuity_validation["Status"]
    .eq("PASS")
    .all()
)

all_emergency_pass = (
    emergency_validation["Status"]
    .eq("PASS")
    .all()
)

rates_valid = (
    rate_validation["Value"].between(0, 100).all()
)


overall_status = all(
    [
        patient_count_status,
        all_encounter_pass,
        all_high_acuity_pass,
        all_emergency_pass,
        rates_valid
    ]
)


print("\n")
print("=" * 70)
print("STEP 4.15 VALIDATION SUMMARY")
print("=" * 70)

print(
    "Patient count validation:",
    "PASS" if patient_count_status else "FAIL"
)

print(
    "Encounter reconciliation:",
    "PASS" if all_encounter_pass else "FAIL"
)

print(
    "High-acuity reconciliation:",
    "PASS" if all_high_acuity_pass else "FAIL"
)

print(
    "Emergency reconciliation:",
    "PASS" if all_emergency_pass else "FAIL"
)

print(
    "Rate validation:",
    "PASS" if rates_valid else "FAIL"
)

print("-" * 70)

print(
    "OVERALL STATUS:",
    "PASS" if overall_status else "FAIL"
)

======================================================================
STEP 4.15C — DEMOGRAPHIC × UTILIZATION VALIDATION
======================================================================

PATIENT COUNT VALIDATION
----------------------------------------------------------------------
Patients in patients_clean: 974
Patients in utilization: 974
Patients after merge: 974
STATUS: PASS

ENCOUNTER RECONCILIATION
----------------------------------------------------------------------

  Demographic  Patient_Level_Total  Source_Level_Total  Difference Status
0      GENDER                27891               27891           0   PASS
1        RACE                27891               27891           0   PASS
2   ETHNICITY                27891               27891           0   PASS
3     MARITAL                27891               27891           0   PASS

HIGH-ACUITY RECONCILIATION
----------------------------------------------------------------------

  Demographic  Patient_Level_Total  Source_Level_Total  Difference Status
0      GENDER                 3457                3457           0   PASS
1        RACE                 3457                3457           0   PASS
2   ETHNICITY                 3457                3457           0   PASS
3     MARITAL                 3457                3457           0   PASS

EMERGENCY RECONCILIATION
----------------------------------------------------------------------

  Demographic  Patient_Level_Total  Source_Level_Total  Difference Status
0      GENDER                 2322                2322           0   PASS
1        RACE                 2322                2322           0   PASS
2   ETHNICITY                 2322                2322           0   PASS
3     MARITAL                 2322                2322           0   PASS

RATE VALIDATION
----------------------------------------------------------------------

                     Metric  Value
0    Minimum Emergency Rate    0.0
1    Maximum Emergency Rate  100.0
2  Minimum High-Acuity Rate    0.0
3  Maximum High-Acuity Rate  100.0

======================================================================
STEP 4.15 VALIDATION SUMMARY
======================================================================
Patient count validation: PASS
Encounter reconciliation: PASS
High-acuity reconciliation: PASS
Emergency reconciliation: PASS
Rate validation: PASS
----------------------------------------------------------------------
OVERALL STATUS: PASS

In [118]:
# ======================================================================
# STEP 4.16A — ENCOUNTER TYPE × COST PREPARATION
# ======================================================================

print("=" * 70)
print("STEP 4.16A — ENCOUNTER TYPE × COST PREPARATION")
print("=" * 70)


# ----------------------------------------------------------------------
# 1. Confirm required dataset exists
# ----------------------------------------------------------------------

if "encounters_clean" not in globals():
    raise NameError(
        "encounters_clean is not available. "
        "Run the encounter cleaning steps first."
    )


# ----------------------------------------------------------------------
# 2. Required columns
# ----------------------------------------------------------------------

required_columns = [
    "ENCOUNTERCLASS",
    "BASE_ENCOUNTER_COST",
    "TOTAL_CLAIM_COST",
    "PAYER_COVERAGE",
    "PATIENT_RESPONSIBILITY"
]

missing_columns = [
    col for col in required_columns
    if col not in encounters_clean.columns
]

if missing_columns:
    raise KeyError(
        f"Missing required columns: {missing_columns}"
    )


print("\nREQUIRED FINANCIAL COLUMNS VERIFIED:")
print(required_columns)


# ----------------------------------------------------------------------
# 3. Create analytical copy
# ----------------------------------------------------------------------

encounter_type_cost = encounters_clean[
    required_columns
].copy()


# ----------------------------------------------------------------------
# 4. Standardize encounter class
# ----------------------------------------------------------------------

encounter_type_cost["ENCOUNTERCLASS"] = (
    encounter_type_cost["ENCOUNTERCLASS"]
    .astype("string")
    .str.strip()
    .str.lower()
    .fillna("unknown")
)


# ----------------------------------------------------------------------
# 5. Convert financial columns to numeric
# ----------------------------------------------------------------------

financial_columns = [
    "BASE_ENCOUNTER_COST",
    "TOTAL_CLAIM_COST",
    "PAYER_COVERAGE",
    "PATIENT_RESPONSIBILITY"
]

for col in financial_columns:
    encounter_type_cost[col] = pd.to_numeric(
        encounter_type_cost[col],
        errors="coerce"
    )


# ----------------------------------------------------------------------
# 6. Check missing financial values
# ----------------------------------------------------------------------

print("\nMISSING FINANCIAL VALUES:")
print(
    encounter_type_cost[financial_columns]
    .isna()
    .sum()
)


# ----------------------------------------------------------------------
# 7. Display encounter class distribution
# ----------------------------------------------------------------------

print("\nENCOUNTER CLASS DISTRIBUTION:")
display(
    encounter_type_cost["ENCOUNTERCLASS"]
    .value_counts()
    .rename_axis("Encounter_Class")
    .reset_index(name="Encounter_Count")
)


# ----------------------------------------------------------------------
# 8. Preview
# ----------------------------------------------------------------------

print("\nENCOUNTER TYPE × COST SOURCE:")
display(encounter_type_cost.head())

======================================================================
STEP 4.16A — ENCOUNTER TYPE × COST PREPARATION
======================================================================

REQUIRED FINANCIAL COLUMNS VERIFIED:
['ENCOUNTERCLASS', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'PATIENT_RESPONSIBILITY']

MISSING FINANCIAL VALUES:
BASE_ENCOUNTER_COST       0
TOTAL_CLAIM_COST          0
PAYER_COVERAGE            0
PATIENT_RESPONSIBILITY    0
dtype: int64

ENCOUNTER CLASS DISTRIBUTION:

  Encounter_Class  Encounter_Count
0      ambulatory            12537
1      outpatient             6300
2      urgentcare             3666
3       emergency             2322
4        wellness             1931
5       inpatient             1135

ENCOUNTER TYPE × COST SOURCE:

,ENCOUNTERCLASS,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,PATIENT_RESPONSIBILITY
0,ambulatory,85.55,1018.02,0.00,1018.02
1,outpatient,142.58,2619.36,0.00,2619.36
2,outpatient,85.55,461.59,305.27,156.32
3,wellness,136.80,1784.24,0.00,1784.24
4,ambulatory,85.55,234.72,0.00,234.72

In [119]:
# ======================================================================
# STEP 4.16B — ENCOUNTER TYPE × COST AGGREGATION
# ======================================================================

print("=" * 70)
print("STEP 4.16B — ENCOUNTER TYPE × COST AGGREGATION")
print("=" * 70)


# ----------------------------------------------------------------------
# 1. Aggregate financial metrics by encounter class
# ----------------------------------------------------------------------

encounter_type_cost_summary = (
    encounter_type_cost
    .groupby("ENCOUNTERCLASS")
    .agg(
        Encounter_Count=("ENCOUNTERCLASS", "size"),

        Total_Base_Encounter_Cost=(
            "BASE_ENCOUNTER_COST",
            "sum"
        ),

        Total_Claim_Cost=(
            "TOTAL_CLAIM_COST",
            "sum"
        ),

        Total_Payer_Coverage=(
            "PAYER_COVERAGE",
            "sum"
        ),

        Total_Patient_Responsibility=(
            "PATIENT_RESPONSIBILITY",
            "sum"
        ),

        Average_Base_Encounter_Cost=(
            "BASE_ENCOUNTER_COST",
            "mean"
        ),

        Average_Claim_Cost=(
            "TOTAL_CLAIM_COST",
            "mean"
        ),

        Average_Payer_Coverage=(
            "PAYER_COVERAGE",
            "mean"
        ),

        Average_Patient_Responsibility=(
            "PATIENT_RESPONSIBILITY",
            "mean"
        )
    )
    .reset_index()
)


# ----------------------------------------------------------------------
# 2. Calculate financial rates
# ----------------------------------------------------------------------

encounter_type_cost_summary["Patient_Responsibility_Rate"] = (
    encounter_type_cost_summary[
        "Total_Patient_Responsibility"
    ]
    /
    encounter_type_cost_summary[
        "Total_Claim_Cost"
    ]
    * 100
)


encounter_type_cost_summary["Payer_Coverage_Rate"] = (
    encounter_type_cost_summary[
        "Total_Payer_Coverage"
    ]
    /
    encounter_type_cost_summary[
        "Total_Claim_Cost"
    ]
    * 100
)


# ----------------------------------------------------------------------
# 3. Calculate cost contribution
# ----------------------------------------------------------------------

total_claim_cost = (
    encounter_type_cost_summary[
        "Total_Claim_Cost"
    ].sum()
)


encounter_type_cost_summary["Claim_Cost_Share"] = (
    encounter_type_cost_summary[
        "Total_Claim_Cost"
    ]
    /
    total_claim_cost
    * 100
)


# ----------------------------------------------------------------------
# 4. Safely handle invalid rates
# ----------------------------------------------------------------------

rate_columns = [
    "Patient_Responsibility_Rate",
    "Payer_Coverage_Rate",
    "Claim_Cost_Share"
]

encounter_type_cost_summary[rate_columns] = (
    encounter_type_cost_summary[rate_columns]
    .replace([float("inf"), -float("inf")], 0)
    .fillna(0)
)


# ----------------------------------------------------------------------
# 5. Sort by total claim cost
# ----------------------------------------------------------------------

encounter_type_cost_summary = (
    encounter_type_cost_summary
    .sort_values(
        "Total_Claim_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)


# ----------------------------------------------------------------------
# 6. Display full result
# ----------------------------------------------------------------------

print("\nENCOUNTER TYPE × COST SUMMARY")
print("-" * 70)

display(encounter_type_cost_summary)

======================================================================
STEP 4.16B — ENCOUNTER TYPE × COST AGGREGATION
======================================================================

ENCOUNTER TYPE × COST SUMMARY
----------------------------------------------------------------------

,ENCOUNTERCLASS,Encounter_Count,Total_Base_Encounter_Cost,Total_Claim_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Average_Base_Encounter_Cost,Average_Claim_Cost,Average_Payer_Coverage,Average_Patient_Responsibility,Patient_Responsibility_Rate,Payer_Coverage_Rate,Claim_Cost_Share
0,ambulatory,12537,1325525.43,36283440.84,12903495.75,23379945.09,105.729076,2894.108705,1029.233130,1864.875575,64.436957,35.563043,35.742170
1,urgentcare,3666,522698.28,23349349.96,3058909.73,20290440.23,142.580000,6369.162564,834.399817,5534.762747,86.899379,13.100621,23.001028
2,outpatient,6300,661750.59,14094967.12,3777758.35,10317208.77,105.039776,2237.296368,599.644183,1637.652186,73.197821,26.802179,13.884701
3,emergency,2322,337266.57,10750051.53,3246828.27,7503223.26,145.248307,4629.651822,1398.289522,3231.362300,69.797091,30.202909,10.589684
4,inpatient,1135,129019.73,8809134.34,3688764.95,5120369.39,113.673771,7761.351841,3250.013172,4511.338670,58.125682,41.874318,8.677721
5,wellness,1931,264160.80,8227431.73,4421749.94,3805681.79,136.800000,4260.710373,2289.875681,1970.834692,46.256012,53.743988,8.104696

In [120]:
# ======================================================================
# STEP 4.16C — ENCOUNTER TYPE × COST VALIDATION
# ======================================================================

print("=" * 70)
print("STEP 4.16C — ENCOUNTER TYPE × COST VALIDATION")
print("=" * 70)


# ----------------------------------------------------------------------
# 1. SOURCE-LEVEL TOTALS
# ----------------------------------------------------------------------

source_totals = {
    "Encounter_Count": len(encounters_clean),

    "Total_Base_Encounter_Cost": (
        encounters_clean["BASE_ENCOUNTER_COST"].sum()
    ),

    "Total_Claim_Cost": (
        encounters_clean["TOTAL_CLAIM_COST"].sum()
    ),

    "Total_Payer_Coverage": (
        encounters_clean["PAYER_COVERAGE"].sum()
    ),

    "Total_Patient_Responsibility": (
        encounters_clean["PATIENT_RESPONSIBILITY"].sum()
    )
}


# ----------------------------------------------------------------------
# 2. GROUPED TOTALS
# ----------------------------------------------------------------------

grouped_totals = {
    "Encounter_Count": (
        encounter_type_cost_summary["Encounter_Count"].sum()
    ),

    "Total_Base_Encounter_Cost": (
        encounter_type_cost_summary["Total_Base_Encounter_Cost"].sum()
    ),

    "Total_Claim_Cost": (
        encounter_type_cost_summary["Total_Claim_Cost"].sum()
    ),

    "Total_Payer_Coverage": (
        encounter_type_cost_summary["Total_Payer_Coverage"].sum()
    ),

    "Total_Patient_Responsibility": (
        encounter_type_cost_summary["Total_Patient_Responsibility"].sum()
    )
}


# ----------------------------------------------------------------------
# 3. FINANCIAL RECONCILIATION
# ----------------------------------------------------------------------

validation_rows = []

for metric in source_totals:

    source_value = source_totals[metric]
    grouped_value = grouped_totals[metric]

    difference = grouped_value - source_value

    validation_rows.append({
        "Metric": metric,
        "Grouped_Total": grouped_value,
        "Source_Total": source_value,
        "Difference": difference,
        "Status": (
            "PASS"
            if abs(difference) < 0.01
            else "FAIL"
        )
    })


encounter_type_cost_validation = pd.DataFrame(
    validation_rows
)


print("\nFINANCIAL RECONCILIATION")
print("-" * 70)

display(encounter_type_cost_validation)


# ----------------------------------------------------------------------
# 4. ENCOUNTER COUNT RECONCILIATION
# ----------------------------------------------------------------------

source_encounter_count = len(encounters_clean)

grouped_encounter_count = (
    encounter_type_cost_summary["Encounter_Count"].sum()
)


print("\nENCOUNTER COUNT RECONCILIATION")
print("-" * 70)

print(
    "Source encounters:",
    source_encounter_count
)

print(
    "Grouped encounters:",
    grouped_encounter_count
)

print(
    "STATUS:",
    "PASS"
    if source_encounter_count == grouped_encounter_count
    else "FAIL"
)


# ----------------------------------------------------------------------
# 5. RATE VALIDATION
# ----------------------------------------------------------------------

rate_validation = pd.DataFrame({
    "Metric": [
        "Minimum Patient Responsibility Rate",
        "Maximum Patient Responsibility Rate",
        "Minimum Payer Coverage Rate",
        "Maximum Payer Coverage Rate"
    ],

    "Value": [
        encounter_type_cost_summary[
            "Patient_Responsibility_Rate"
        ].min(),

        encounter_type_cost_summary[
            "Patient_Responsibility_Rate"
        ].max(),

        encounter_type_cost_summary[
            "Payer_Coverage_Rate"
        ].min(),

        encounter_type_cost_summary[
            "Payer_Coverage_Rate"
        ].max()
    ]
})


print("\nRATE VALIDATION")
print("-" * 70)

display(rate_validation)


# ----------------------------------------------------------------------
# 6. CHECK THAT RATES ARE WITHIN VALID RANGE
# ----------------------------------------------------------------------

rates_pass = (
    rate_validation["Value"]
    .between(0, 100)
    .all()
)


# ----------------------------------------------------------------------
# 7. OVERALL VALIDATION STATUS
# ----------------------------------------------------------------------

financial_reconciliation_pass = (
    encounter_type_cost_validation["Status"]
    .eq("PASS")
    .all()
)

encounter_count_pass = (
    source_encounter_count == grouped_encounter_count
)


overall_status = all([
    financial_reconciliation_pass,
    encounter_count_pass,
    rates_pass
])


# ----------------------------------------------------------------------
# 8. FINAL SUMMARY
# ----------------------------------------------------------------------

print("\n")
print("=" * 70)
print("STEP 4.16 VALIDATION SUMMARY")
print("=" * 70)

print(
    "Financial reconciliation:",
    "PASS" if financial_reconciliation_pass else "FAIL"
)

print(
    "Encounter count reconciliation:",
    "PASS" if encounter_count_pass else "FAIL"
)

print(
    "Rate validation:",
    "PASS" if rates_pass else "FAIL"
)

print("-" * 70)

print(
    "OVERALL STATUS:",
    "PASS" if overall_status else "FAIL"
)

print("=" * 70)

======================================================================
STEP 4.16C — ENCOUNTER TYPE × COST VALIDATION
======================================================================

FINANCIAL RECONCILIATION
----------------------------------------------------------------------

,Metric,Grouped_Total,Source_Total,Difference,Status
0,Encounter_Count,2.789100e+04,2.789100e+04,0.000000e+00,PASS
1,Total_Base_Encounter_Cost,3.240421e+06,3.240421e+06,-4.656613e-10,PASS
2,Total_Claim_Cost,1.015144e+08,1.015144e+08,0.000000e+00,PASS
3,Total_Payer_Coverage,3.109751e+07,3.109751e+07,3.725290e-09,PASS
4,Total_Patient_Responsibility,7.041687e+07,7.041687e+07,0.000000e+00,PASS

ENCOUNTER COUNT RECONCILIATION
----------------------------------------------------------------------
Source encounters: 27891
Grouped encounters: 27891
STATUS: PASS

RATE VALIDATION
----------------------------------------------------------------------

                                Metric      Value
0  Minimum Patient Responsibility Rate  46.256012
1  Maximum Patient Responsibility Rate  86.899379
2          Minimum Payer Coverage Rate  13.100621
3          Maximum Payer Coverage Rate  53.743988

======================================================================
STEP 4.16 VALIDATION SUMMARY
======================================================================
Financial reconciliation: PASS
Encounter count reconciliation: PASS
Rate validation: PASS
----------------------------------------------------------------------
OVERALL STATUS: PASS
======================================================================

In [121]:
# ======================================================================
# STEP 4.17A — PAYER FINANCIAL DISTRIBUTION
# ======================================================================

print("=" * 70)
print("STEP 4.17A — PAYER FINANCIAL DISTRIBUTION")
print("=" * 70)


# ----------------------------------------------------------------------
# 1. Confirm payer column
# ----------------------------------------------------------------------

print("\nPAYER COLUMN CHECK")
print("-" * 70)

print(
    [
        col for col in encounters_clean.columns
        if "PAYER" in col.upper()
    ]
)


# ----------------------------------------------------------------------
# 2. Inspect payer distribution
# ----------------------------------------------------------------------

payer_distribution = (
    encounters_clean
    .groupby("PAYER", dropna=False)
    .size()
    .reset_index(name="Encounter_Count")
    .sort_values(
        "Encounter_Count",
        ascending=False
    )
    .reset_index(drop=True)
)


print("\nPAYER DISTRIBUTION")
print("-" * 70)

display(payer_distribution)


# ----------------------------------------------------------------------
# 3. Number of unique payers
# ----------------------------------------------------------------------

print("\nUNIQUE PAYERS")
print("-" * 70)

print(
    "Unique payers:",
    encounters_clean["PAYER"].nunique(dropna=False)
)

======================================================================
STEP 4.17A — PAYER FINANCIAL DISTRIBUTION
======================================================================

PAYER COLUMN CHECK
----------------------------------------------------------------------
['PAYER', 'PAYER_COVERAGE']

PAYER DISTRIBUTION
----------------------------------------------------------------------

                                  PAYER  Encounter_Count
0  7caa7254-5050-3b5e-9eae-bd5ea30e809c            11371
1  b1c428d6-4f07-31e0-90f0-68ffa6ff8c76             8807
2  7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a             1443
3  d47b3510-2895-3b70-9897-342d681c769d             1084
4  4d71f845-a6a9-3c39-b242-14d25ef86a8d              936
5  6e2f1a2d-27bd-3701-8d08-dae202c58632              925
6  b3221cfc-24fb-339e-823d-bc4136cbc4ed              912
7  5059a55e-5d6e-34d1-b6cb-d83d16e57bcf              900
8  047f6ec3-6215-35eb-9608-f9dda363a44c              809
9  42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a              704

UNIQUE PAYERS
----------------------------------------------------------------------
Unique payers: 10

In [122]:
# ======================================================================
# STEP 4.17B — PAYER × PATIENT RESPONSIBILITY
# ======================================================================

print("=" * 70)
print("STEP 4.17B — PAYER × PATIENT RESPONSIBILITY")
print("=" * 70)


# ----------------------------------------------------------------------
# 1. Aggregate financial burden by payer
# ----------------------------------------------------------------------

payer_patient_responsibility = (
    encounters_clean
    .groupby("PAYER", dropna=False)
    .agg(
        Encounter_Count=("PAYER", "size"),

        Total_Base_Encounter_Cost=(
            "BASE_ENCOUNTER_COST",
            "sum"
        ),

        Total_Claim_Cost=(
            "TOTAL_CLAIM_COST",
            "sum"
        ),

        Total_Payer_Coverage=(
            "PAYER_COVERAGE",
            "sum"
        ),

        Total_Patient_Responsibility=(
            "PATIENT_RESPONSIBILITY",
            "sum"
        )
    )
    .reset_index()
)


# ----------------------------------------------------------------------
# 2. Calculate average financial burden per encounter
# ----------------------------------------------------------------------

payer_patient_responsibility[
    "Average_Claim_Cost_Per_Encounter"
] = (
    payer_patient_responsibility["Total_Claim_Cost"]
    / payer_patient_responsibility["Encounter_Count"]
)


payer_patient_responsibility[
    "Average_Payer_Coverage_Per_Encounter"
] = (
    payer_patient_responsibility["Total_Payer_Coverage"]
    / payer_patient_responsibility["Encounter_Count"]
)


payer_patient_responsibility[
    "Average_Patient_Responsibility_Per_Encounter"
] = (
    payer_patient_responsibility[
        "Total_Patient_Responsibility"
    ]
    / payer_patient_responsibility["Encounter_Count"]
)


# ----------------------------------------------------------------------
# 3. Calculate financial responsibility rates
# ----------------------------------------------------------------------

payer_patient_responsibility[
    "Patient_Responsibility_Rate"
] = (
    payer_patient_responsibility[
        "Total_Patient_Responsibility"
    ]
    / payer_patient_responsibility["Total_Claim_Cost"]
    * 100
)


payer_patient_responsibility[
    "Payer_Coverage_Rate"
] = (
    payer_patient_responsibility[
        "Total_Payer_Coverage"
    ]
    / payer_patient_responsibility["Total_Claim_Cost"]
    * 100
)


# ----------------------------------------------------------------------
# 4. Handle possible division-by-zero values
# ----------------------------------------------------------------------

rate_columns = [
    "Patient_Responsibility_Rate",
    "Payer_Coverage_Rate"
]

average_columns = [
    "Average_Claim_Cost_Per_Encounter",
    "Average_Payer_Coverage_Per_Encounter",
    "Average_Patient_Responsibility_Per_Encounter"
]

payer_patient_responsibility[
    rate_columns + average_columns
] = (
    payer_patient_responsibility[
        rate_columns + average_columns
    ]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
)


# ----------------------------------------------------------------------
# 5. Sort by total patient responsibility
# ----------------------------------------------------------------------

payer_patient_responsibility = (
    payer_patient_responsibility
    .sort_values(
        "Total_Patient_Responsibility",
        ascending=False
    )
    .reset_index(drop=True)
)


# ----------------------------------------------------------------------
# 6. Display complete payer analysis
# ----------------------------------------------------------------------

print("\nPAYER × PATIENT RESPONSIBILITY SUMMARY")
print("-" * 70)

display(payer_patient_responsibility)


# ----------------------------------------------------------------------
# 7. Top payers by patient financial burden
# ----------------------------------------------------------------------

print("\nTOP 10 PAYERS BY TOTAL PATIENT RESPONSIBILITY")
print("-" * 70)

display(
    payer_patient_responsibility[
        [
            "PAYER",
            "Encounter_Count",
            "Total_Claim_Cost",
            "Total_Payer_Coverage",
            "Total_Patient_Responsibility",
            "Average_Patient_Responsibility_Per_Encounter",
            "Patient_Responsibility_Rate",
            "Payer_Coverage_Rate"
        ]
    ]
    .head(10)
)

======================================================================
STEP 4.17B — PAYER × PATIENT RESPONSIBILITY
======================================================================

PAYER × PATIENT RESPONSIBILITY SUMMARY
----------------------------------------------------------------------

,PAYER,Encounter_Count,Total_Base_Encounter_Cost,Total_Claim_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Average_Claim_Cost_Per_Encounter,Average_Payer_Coverage_Per_Encounter,Average_Patient_Responsibility_Per_Encounter,Patient_Responsibility_Rate,Payer_Coverage_Rate
0,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,8807,1010284.91,49259290.16,0.00,49259290.16,5593.197475,0.000000,5593.197475,100.000000,0.000000
1,7caa7254-5050-3b5e-9eae-bd5ea30e809c,11371,1315271.26,24647228.89,19215691.37,5431537.52,2167.551569,1689.885795,477.665774,22.037112,77.962888
2,d47b3510-2895-3b70-9897-342d681c769d,1084,127630.75,3543921.36,1953.86,3541967.50,3269.300148,1.802454,3267.497694,99.944867,0.055133
3,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,704,81061.87,2982715.05,0.00,2982715.05,4236.811151,0.000000,4236.811151,100.000000,0.000000
4,4d71f845-a6a9-3c39-b242-14d25ef86a8d,936,106861.29,2589956.10,1780.16,2588175.94,2767.047115,1.901880,2765.145235,99.931267,0.068733
5,5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,900,107923.83,2563507.98,3937.32,2559570.66,2848.342200,4.374800,2843.967400,99.846409,0.153591
6,047f6ec3-6215-35eb-9608-f9dda363a44c,809,93021.49,2424532.96,968.35,2423564.61,2996.950507,1.196972,2995.753535,99.960060,0.039940
7,6e2f1a2d-27bd-3701-8d08-dae202c58632,925,108642.52,3002166.01,2074496.34,927669.67,3245.584876,2242.698746,1002.886130,30.900012,69.099988
8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,1443,181117.52,8954131.02,8417973.72,536157.30,6205.219002,5833.661622,371.557380,5.987821,94.012179
9,b3221cfc-24fb-339e-823d-bc4136cbc4ed,912,108605.96,1546925.99,1380705.87,166220.12,1696.190779,1513.931875,182.258904,10.745189,89.254811

TOP 10 PAYERS BY TOTAL PATIENT RESPONSIBILITY
----------------------------------------------------------------------

,PAYER,Encounter_Count,Total_Claim_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Average_Patient_Responsibility_Per_Encounter,Patient_Responsibility_Rate,Payer_Coverage_Rate
0,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,8807,49259290.16,0.00,49259290.16,5593.197475,100.000000,0.000000
1,7caa7254-5050-3b5e-9eae-bd5ea30e809c,11371,24647228.89,19215691.37,5431537.52,477.665774,22.037112,77.962888
2,d47b3510-2895-3b70-9897-342d681c769d,1084,3543921.36,1953.86,3541967.50,3267.497694,99.944867,0.055133
3,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,704,2982715.05,0.00,2982715.05,4236.811151,100.000000,0.000000
4,4d71f845-a6a9-3c39-b242-14d25ef86a8d,936,2589956.10,1780.16,2588175.94,2765.145235,99.931267,0.068733
5,5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,900,2563507.98,3937.32,2559570.66,2843.967400,99.846409,0.153591
6,047f6ec3-6215-35eb-9608-f9dda363a44c,809,2424532.96,968.35,2423564.61,2995.753535,99.960060,0.039940
7,6e2f1a2d-27bd-3701-8d08-dae202c58632,925,3002166.01,2074496.34,927669.67,1002.886130,30.900012,69.099988
8,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,1443,8954131.02,8417973.72,536157.30,371.557380,5.987821,94.012179
9,b3221cfc-24fb-339e-823d-bc4136cbc4ed,912,1546925.99,1380705.87,166220.12,182.258904,10.745189,89.254811

In [123]:
# ======================================================================
# STEP 4.17C — PAYER × PATIENT RESPONSIBILITY VALIDATION
# ======================================================================

print("=" * 70)
print("STEP 4.17C — PAYER × PATIENT RESPONSIBILITY VALIDATION")
print("=" * 70)


# ----------------------------------------------------------------------
# 1. Source-level totals
# ----------------------------------------------------------------------

source_totals = {
    "Encounter_Count": len(encounters_clean),

    "Total_Base_Encounter_Cost": (
        encounters_clean["BASE_ENCOUNTER_COST"].sum()
    ),

    "Total_Claim_Cost": (
        encounters_clean["TOTAL_CLAIM_COST"].sum()
    ),

    "Total_Payer_Coverage": (
        encounters_clean["PAYER_COVERAGE"].sum()
    ),

    "Total_Patient_Responsibility": (
        encounters_clean["PATIENT_RESPONSIBILITY"].sum()
    )
}


# ----------------------------------------------------------------------
# 2. Payer-level grouped totals
# ----------------------------------------------------------------------

grouped_totals = {
    "Encounter_Count": (
        payer_patient_responsibility["Encounter_Count"].sum()
    ),

    "Total_Base_Encounter_Cost": (
        payer_patient_responsibility[
            "Total_Base_Encounter_Cost"
        ].sum()
    ),

    "Total_Claim_Cost": (
        payer_patient_responsibility[
            "Total_Claim_Cost"
        ].sum()
    ),

    "Total_Payer_Coverage": (
        payer_patient_responsibility[
            "Total_Payer_Coverage"
        ].sum()
    ),

    "Total_Patient_Responsibility": (
        payer_patient_responsibility[
            "Total_Patient_Responsibility"
        ].sum()
    )
}


# ----------------------------------------------------------------------
# 3. Financial reconciliation
# ----------------------------------------------------------------------

validation_rows = []

for metric in source_totals:

    source_value = source_totals[metric]
    grouped_value = grouped_totals[metric]

    difference = grouped_value - source_value

    validation_rows.append(
        {
            "Metric": metric,
            "Grouped_Total": grouped_value,
            "Source_Total": source_value,
            "Difference": difference,
            "Status": (
                "PASS"
                if abs(difference) < 0.01
                else "FAIL"
            )
        }
    )


payer_financial_validation = pd.DataFrame(
    validation_rows
)


print("\nFINANCIAL RECONCILIATION")
print("-" * 70)

display(payer_financial_validation)


# ----------------------------------------------------------------------
# 4. Validate payer count
# ----------------------------------------------------------------------

source_payer_count = (
    encounters_clean["PAYER"]
    .nunique(dropna=False)
)

grouped_payer_count = len(
    payer_patient_responsibility
)


print("\nPAYER COUNT VALIDATION")
print("-" * 70)

print(
    "Source unique payers:",
    source_payer_count
)

print(
    "Grouped payers:",
    grouped_payer_count
)

print(
    "STATUS:",
    "PASS"
    if source_payer_count == grouped_payer_count
    else "FAIL"
)


# ----------------------------------------------------------------------
# 5. Validate encounter counts
# ----------------------------------------------------------------------

source_encounter_count = len(
    encounters_clean
)

grouped_encounter_count = (
    payer_patient_responsibility[
        "Encounter_Count"
    ].sum()
)


print("\nENCOUNTER COUNT RECONCILIATION")
print("-" * 70)

print(
    "Source encounters:",
    source_encounter_count
)

print(
    "Grouped encounters:",
    grouped_encounter_count
)

print(
    "STATUS:",
    "PASS"
    if source_encounter_count == grouped_encounter_count
    else "FAIL"
)


# ----------------------------------------------------------------------
# 6. Validate financial rates
# ----------------------------------------------------------------------

rate_validation = pd.DataFrame(
    {
        "Metric": [
            "Minimum Patient Responsibility Rate",
            "Maximum Patient Responsibility Rate",
            "Minimum Payer Coverage Rate",
            "Maximum Payer Coverage Rate"
        ],

        "Value": [
            payer_patient_responsibility[
                "Patient_Responsibility_Rate"
            ].min(),

            payer_patient_responsibility[
                "Patient_Responsibility_Rate"
            ].max(),

            payer_patient_responsibility[
                "Payer_Coverage_Rate"
            ].min(),

            payer_patient_responsibility[
                "Payer_Coverage_Rate"
            ].max()
        ]
    }
)


print("\nRATE VALIDATION")
print("-" * 70)

display(rate_validation)


# ----------------------------------------------------------------------
# 7. Validate claim-cost composition
#
# Total Claim Cost should equal:
# Payer Coverage + Patient Responsibility
# ----------------------------------------------------------------------

claim_composition = (
    payer_patient_responsibility[
        "Total_Payer_Coverage"
    ]
    +
    payer_patient_responsibility[
        "Total_Patient_Responsibility"
    ]
)

claim_total = (
    payer_patient_responsibility[
        "Total_Claim_Cost"
    ]
)

claim_difference = (
    claim_composition - claim_total
).abs().max()


print("\nCLAIM COST COMPOSITION VALIDATION")
print("-" * 70)

print(
    "Maximum absolute difference:",
    claim_difference
)

print(
    "STATUS:",
    "PASS"
    if claim_difference < 0.01
    else "FAIL"
)


# ----------------------------------------------------------------------
# 8. Overall validation status
# ----------------------------------------------------------------------

financial_reconciliation_pass = (
    payer_financial_validation["Status"]
    .eq("PASS")
    .all()
)

payer_count_pass = (
    source_payer_count == grouped_payer_count
)

encounter_count_pass = (
    source_encounter_count == grouped_encounter_count
)

rates_pass = (
    rate_validation["Value"]
    .between(0, 100)
    .all()
)

claim_composition_pass = (
    claim_difference < 0.01
)


overall_status = all(
    [
        financial_reconciliation_pass,
        payer_count_pass,
        encounter_count_pass,
        rates_pass,
        claim_composition_pass
    ]
)


# ----------------------------------------------------------------------
# 9. Final summary
# ----------------------------------------------------------------------

print("\n")
print("=" * 70)
print("STEP 4.17 VALIDATION SUMMARY")
print("=" * 70)

print(
    "Financial reconciliation:",
    "PASS"
    if financial_reconciliation_pass
    else "FAIL"
)

print(
    "Payer count reconciliation:",
    "PASS"
    if payer_count_pass
    else "FAIL"
)

print(
    "Encounter count reconciliation:",
    "PASS"
    if encounter_count_pass
    else "FAIL"
)

print(
    "Rate validation:",
    "PASS"
    if rates_pass
    else "FAIL"
)

print(
    "Claim cost composition:",
    "PASS"
    if claim_composition_pass
    else "FAIL"
)

print("-" * 70)

print(
    "OVERALL STATUS:",
    "PASS"
    if overall_status
    else "FAIL"
)

======================================================================
STEP 4.17C — PAYER × PATIENT RESPONSIBILITY VALIDATION
======================================================================

FINANCIAL RECONCILIATION
----------------------------------------------------------------------

,Metric,Grouped_Total,Source_Total,Difference,Status
0,Encounter_Count,2.789100e+04,2.789100e+04,0.000000e+00,PASS
1,Total_Base_Encounter_Cost,3.240421e+06,3.240421e+06,0.000000e+00,PASS
2,Total_Claim_Cost,1.015144e+08,1.015144e+08,-2.980232e-08,PASS
3,Total_Payer_Coverage,3.109751e+07,3.109751e+07,7.450581e-09,PASS
4,Total_Patient_Responsibility,7.041687e+07,7.041687e+07,-1.490116e-08,PASS

PAYER COUNT VALIDATION
----------------------------------------------------------------------
Source unique payers: 10
Grouped payers: 10
STATUS: PASS

ENCOUNTER COUNT RECONCILIATION
----------------------------------------------------------------------
Source encounters: 27891
Grouped encounters: 27891
STATUS: PASS

RATE VALIDATION
----------------------------------------------------------------------

                                Metric       Value
0  Minimum Patient Responsibility Rate    5.987821
1  Maximum Patient Responsibility Rate  100.000000
2          Minimum Payer Coverage Rate    0.000000
3          Maximum Payer Coverage Rate   94.012179

CLAIM COST COMPOSITION VALIDATION
----------------------------------------------------------------------
Maximum absolute difference: 1.862645149230957e-09
STATUS: PASS


======================================================================
STEP 4.17 VALIDATION SUMMARY
======================================================================
Financial reconciliation: PASS
Payer count reconciliation: PASS
Encounter count reconciliation: PASS
Rate validation: PASS
Claim cost composition: PASS
----------------------------------------------------------------------
OVERALL STATUS: PASS

In [124]:
# ======================================================================
# STEP 4.18A — PROCEDURE DISTRIBUTION
# ======================================================================

print("=" * 70)
print("STEP 4.18A — PROCEDURE DISTRIBUTION")
print("=" * 70)


# ----------------------------------------------------------------------
# 1. Confirm required procedure columns
# ----------------------------------------------------------------------

required_procedure_columns = [
    "PATIENT",
    "ENCOUNTER",
    "CODE",
    "DESCRIPTION",
    "BASE_COST"
]

missing_columns = [
    col
    for col in required_procedure_columns
    if col not in procedures_clean.columns
]


print("\nREQUIRED COLUMN CHECK")
print("-" * 70)

if missing_columns:
    print("Missing columns:", missing_columns)
else:
    print("STATUS: PASS")
    print("All required procedure columns are available.")


# ----------------------------------------------------------------------
# 2. Basic procedure statistics
# ----------------------------------------------------------------------

print("\nPROCEDURE DATASET SUMMARY")
print("-" * 70)

print(
    "Total procedures:",
    len(procedures_clean)
)

print(
    "Unique procedure codes:",
    procedures_clean["CODE"].nunique()
)

print(
    "Unique procedure descriptions:",
    procedures_clean["DESCRIPTION"].nunique()
)

print(
    "Unique patients with procedures:",
    procedures_clean["PATIENT"].nunique()
)

print(
    "Unique encounters with procedures:",
    procedures_clean["ENCOUNTER"].nunique()
)


# ----------------------------------------------------------------------
# 3. Procedure frequency by code
# ----------------------------------------------------------------------

procedure_code_distribution = (
    procedures_clean
    .groupby(
        ["CODE", "DESCRIPTION"],
        dropna=False
    )
    .agg(
        Procedure_Count=("CODE", "size"),
        Total_Procedure_Cost=("BASE_COST", "sum"),
        Average_Procedure_Cost=("BASE_COST", "mean")
    )
    .reset_index()
)


# ----------------------------------------------------------------------
# 4. Sort by procedure frequency
# ----------------------------------------------------------------------

procedure_code_distribution = (
    procedure_code_distribution
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .reset_index(drop=True)
)


# ----------------------------------------------------------------------
# 5. Display top procedures
# ----------------------------------------------------------------------

print("\nTOP 20 PROCEDURES BY FREQUENCY")
print("-" * 70)

display(
    procedure_code_distribution.head(20)
)

======================================================================
STEP 4.18A — PROCEDURE DISTRIBUTION
======================================================================

REQUIRED COLUMN CHECK
----------------------------------------------------------------------
STATUS: PASS
All required procedure columns are available.

PROCEDURE DATASET SUMMARY
----------------------------------------------------------------------
Total procedures: 47701
Unique procedure codes: 157
Unique procedure descriptions: 163
Unique patients with procedures: 793
Unique encounters with procedures: 14670

TOP 20 PROCEDURES BY FREQUENCY
----------------------------------------------------------------------

,CODE,DESCRIPTION,Procedure_Count,Total_Procedure_Cost,Average_Procedure_Cost
0,710824005,Assessment of health and social care needs (pr...,4596,1980876,431.000000
1,385763009,Hospice care (regime/therapy),4098,1766238,431.000000
2,171207006,Depression screening (procedure),3614,1557634,431.000000
3,454711000124102,Depression screening using Patient Health Ques...,3614,1557634,431.000000
4,428211000124100,Assessment of substance use (procedure),2906,1252486,431.000000
5,265764009,Renal dialysis (procedure),2746,2757221,1004.086307
6,762993000,Assessment using Morse Fall Scale (procedure),2422,1043882,431.000000
7,710841007,Assessment of anxiety (procedure),2288,986128,431.000000
8,430193006,Medication Reconciliation (procedure),2284,1162840,509.124343
9,713106006,Screening for drug abuse (procedure),1484,639604,431.000000
10,866148006,Screening for domestic abuse (procedure),1432,617192,431.000000
11,763302001,Assessment using Alcohol Use Disorders Identif...,1422,612882,431.000000
12,180325003,Electrical cardioversion,1383,35824002,25903.110629
13,274804006,Evaluation of uterine fundal height,1065,5631281,5287.587793
14,225158009,Auscultation of the fetal heart,1065,5657822,5312.508920
15,229064008,Movement therapy (regime/therapy),890,383590,431.000000
16,76601001,Intramuscular injection,522,1325634,2539.528736
17,703423002,Combined chemotherapy and radiation therapy (p...,444,5237596,11796.387387
18,73761001,Colonoscopy,424,5021003,11841.988208
19,18286008,Catheter ablation of tissue of heart,365,3405999,9331.504110

In [125]:
# ======================================================================
# STEP 4.18B — PROCEDURE × COST / UTILIZATION
# ======================================================================

print("=" * 70)
print("STEP 4.18B — PROCEDURE × COST / UTILIZATION")
print("=" * 70)


# ----------------------------------------------------------------------
# 1. Procedure-level cost and utilization summary
# ----------------------------------------------------------------------

procedure_cost_summary = (
    procedures_clean
    .groupby(["CODE", "DESCRIPTION"], dropna=False)
    .agg(
        Procedure_Count=("CODE", "size"),
        Total_Procedure_Cost=("BASE_COST", "sum"),
        Average_Procedure_Cost=("BASE_COST", "mean"),
        Median_Procedure_Cost=("BASE_COST", "median"),
        Unique_Patients=("PATIENT", "nunique"),
        Unique_Encounters=("ENCOUNTER", "nunique")
    )
    .reset_index()
)


# ----------------------------------------------------------------------
# 2. Calculate utilization and cost metrics
# ----------------------------------------------------------------------

procedure_cost_summary["Cost_Per_Patient"] = (
    procedure_cost_summary["Total_Procedure_Cost"]
    / procedure_cost_summary["Unique_Patients"]
    .replace(0, np.nan)
)

procedure_cost_summary["Procedures_Per_Patient"] = (
    procedure_cost_summary["Procedure_Count"]
    / procedure_cost_summary["Unique_Patients"]
    .replace(0, np.nan)
)

procedure_cost_summary["Procedures_Per_Encounter"] = (
    procedure_cost_summary["Procedure_Count"]
    / procedure_cost_summary["Unique_Encounters"]
    .replace(0, np.nan)
)


# ----------------------------------------------------------------------
# 3. Top procedures by total cost
# ----------------------------------------------------------------------

top_procedures_by_cost = (
    procedure_cost_summary
    .sort_values(
        "Total_Procedure_Cost",
        ascending=False
    )
    .head(20)
    .reset_index(drop=True)
)


print("\nTOP 20 PROCEDURES BY TOTAL COST")
print("-" * 70)

display(top_procedures_by_cost)


# ----------------------------------------------------------------------
# 4. Top procedures by frequency
# ----------------------------------------------------------------------

top_procedures_by_frequency = (
    procedure_cost_summary
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .head(20)
    .reset_index(drop=True)
)


print("\nTOP 20 PROCEDURES BY FREQUENCY")
print("-" * 70)

display(top_procedures_by_frequency)


# ----------------------------------------------------------------------
# 5. Most expensive procedures by average cost
# ----------------------------------------------------------------------

top_procedures_by_average_cost = (
    procedure_cost_summary
    .sort_values(
        "Average_Procedure_Cost",
        ascending=False
    )
    .head(20)
    .reset_index(drop=True)
)


print("\nTOP 20 PROCEDURES BY AVERAGE COST")
print("-" * 70)

display(top_procedures_by_average_cost)


# ----------------------------------------------------------------------
# 6. High-utilization procedures
# ----------------------------------------------------------------------

high_utilization_procedures = (
    procedure_cost_summary
    .sort_values(
        [
            "Procedure_Count",
            "Total_Procedure_Cost"
        ],
        ascending=[False, False]
    )
    .head(20)
    .reset_index(drop=True)
)


print("\nTOP 20 HIGH-UTILIZATION PROCEDURES")
print("-" * 70)

display(high_utilization_procedures)


# ----------------------------------------------------------------------
# 7. Procedure cost concentration
# ----------------------------------------------------------------------

total_procedure_cost = (
    procedures_clean["BASE_COST"].sum()
)

top_10_procedure_cost = (
    procedure_cost_summary
    .nlargest(
        10,
        "Total_Procedure_Cost"
    )["Total_Procedure_Cost"]
    .sum()
)

top_20_procedure_cost = (
    procedure_cost_summary
    .nlargest(
        20,
        "Total_Procedure_Cost"
    )["Total_Procedure_Cost"]
    .sum()
)

top_10_cost_share = (
    top_10_procedure_cost / total_procedure_cost * 100
)

top_20_cost_share = (
    top_20_procedure_cost / total_procedure_cost * 100
)


print("\nPROCEDURE COST CONCENTRATION")
print("-" * 70)

print(
    f"Total procedure cost: "
    f"{total_procedure_cost:,.2f}"
)

print(
    f"Top 10 procedures total cost: "
    f"{top_10_procedure_cost:,.2f}"
)

print(
    f"Top 10 procedure cost share: "
    f"{top_10_cost_share:.2f}%"
)

print(
    f"Top 20 procedures total cost: "
    f"{top_20_procedure_cost:,.2f}"
)

print(
    f"Top 20 procedure cost share: "
    f"{top_20_cost_share:.2f}%"
)


# ----------------------------------------------------------------------
# 8. Procedure utilization concentration
# ----------------------------------------------------------------------

total_procedure_count = len(procedures_clean)

top_10_procedure_count = (
    procedure_cost_summary
    .nlargest(
        10,
        "Procedure_Count"
    )["Procedure_Count"]
    .sum()
)

top_20_procedure_count = (
    procedure_cost_summary
    .nlargest(
        20,
        "Procedure_Count"
    )["Procedure_Count"]
    .sum()
)

top_10_utilization_share = (
    top_10_procedure_count
    / total_procedure_count
    * 100
)

top_20_utilization_share = (
    top_20_procedure_count
    / total_procedure_count
    * 100
)


print("\nPROCEDURE UTILIZATION CONCENTRATION")
print("-" * 70)

print(
    f"Total procedures: "
    f"{total_procedure_count:,}"
)

print(
    f"Top 10 procedure volume: "
    f"{top_10_procedure_count:,}"
)

print(
    f"Top 10 procedure utilization share: "
    f"{top_10_utilization_share:.2f}%"
)

print(
    f"Top 20 procedure volume: "
    f"{top_20_procedure_count:,}"
)

print(
    f"Top 20 procedure utilization share: "
    f"{top_20_utilization_share:.2f}%"
)


# ----------------------------------------------------------------------
# 9. Overall procedure × cost metrics
# ----------------------------------------------------------------------

procedure_cost_metrics = pd.DataFrame(
    {
        "Metric": [
            "Total Procedures",
            "Unique Procedure Codes",
            "Unique Procedure Descriptions",
            "Unique Patients",
            "Unique Encounters",
            "Total Procedure Cost",
            "Average Procedure Cost",
            "Median Procedure Cost",
            "Top 10 Cost Share (%)",
            "Top 20 Cost Share (%)",
            "Top 10 Utilization Share (%)",
            "Top 20 Utilization Share (%)"
        ],
        "Value": [
            len(procedures_clean),
            procedures_clean["CODE"].nunique(),
            procedures_clean["DESCRIPTION"].nunique(),
            procedures_clean["PATIENT"].nunique(),
            procedures_clean["ENCOUNTER"].nunique(),
            procedures_clean["BASE_COST"].sum(),
            procedures_clean["BASE_COST"].mean(),
            procedures_clean["BASE_COST"].median(),
            top_10_cost_share,
            top_20_cost_share,
            top_10_utilization_share,
            top_20_utilization_share
        ]
    }
)


print("\nOVERALL PROCEDURE × COST / UTILIZATION METRICS")
print("-" * 70)

display(procedure_cost_metrics)

======================================================================
STEP 4.18B — PROCEDURE × COST / UTILIZATION
======================================================================

TOP 20 PROCEDURES BY TOTAL COST
----------------------------------------------------------------------

,CODE,DESCRIPTION,Procedure_Count,Total_Procedure_Cost,Average_Procedure_Cost,Median_Procedure_Cost,Unique_Patients,Unique_Encounters,Cost_Per_Patient,Procedures_Per_Patient,Procedures_Per_Encounter
0,180325003,Electrical cardioversion,1383,35824002,25903.110629,25066.0,74,1383,484108.135135,18.689189,1.000000
1,225158009,Auscultation of the fetal heart,1065,5657822,5312.508920,5157.0,71,1065,79687.633803,15.000000,1.000000
2,274804006,Evaluation of uterine fundal height,1065,5631281,5287.587793,5149.0,71,1065,79313.816901,15.000000,1.000000
3,703423002,Combined chemotherapy and radiation therapy (p...,444,5237596,11796.387387,11441.5,21,444,249409.333333,21.142857,1.000000
4,73761001,Colonoscopy,424,5021003,11841.988208,11465.5,233,424,21549.369099,1.819742,1.000000
5,18286008,Catheter ablation of tissue of heart,365,3405999,9331.504110,9117.0,54,365,63074.055556,6.759259,1.000000
6,265764009,Renal dialysis (procedure),2746,2757221,1004.086307,978.0,5,2746,551444.200000,549.200000,1.000000
7,710824005,Assessment of health and social care needs (pr...,4596,1980876,431.000000,431.0,509,4596,3891.701375,9.029470,1.000000
8,312681000,Bone density scan (procedure),198,1901367,9602.863636,9491.0,115,198,16533.626087,1.721739,1.000000
9,385763009,Hospice care (regime/therapy),4098,1766238,431.000000,431.0,61,162,28954.721311,67.180328,25.296296
10,169230002,Ultrasound scan for fetal viability,184,1693824,9205.565217,8879.5,81,184,20911.407407,2.271605,1.000000
11,127783003,Spirometry (procedure),209,1628688,7792.765550,7775.0,23,209,70812.521739,9.086957,1.000000
12,454711000124102,Depression screening using Patient Health Ques...,3614,1557634,431.000000,431.0,500,3614,3115.268000,7.228000,1.000000
13,171207006,Depression screening (procedure),3614,1557634,431.000000,431.0,500,3614,3115.268000,7.228000,1.000000
14,228557008,Cognitive and behavioral therapy (regime/therapy),136,1412779,10388.080882,10142.0,17,136,83104.647059,8.000000,1.000000
15,76601001,Intramuscular injection,522,1325634,2539.528736,2460.5,45,522,29458.533333,11.600000,1.000000
16,428211000124100,Assessment of substance use (procedure),2906,1252486,431.000000,431.0,436,2906,2872.674312,6.665138,1.000000
17,430193006,Medication Reconciliation (procedure),2284,1162840,509.124343,496.0,418,2284,2781.913876,5.464115,1.000000
18,433112001,Percutaneous mechanical thrombectomy of portal...,57,1152998,20228.035088,19073.0,55,57,20963.600000,1.036364,1.000000
19,762993000,Assessment using Morse Fall Scale (procedure),2422,1043882,431.000000,431.0,268,2422,3895.082090,9.037313,1.000000

TOP 20 PROCEDURES BY FREQUENCY
----------------------------------------------------------------------

,CODE,DESCRIPTION,Procedure_Count,Total_Procedure_Cost,Average_Procedure_Cost,Median_Procedure_Cost,Unique_Patients,Unique_Encounters,Cost_Per_Patient,Procedures_Per_Patient,Procedures_Per_Encounter
0,710824005,Assessment of health and social care needs (pr...,4596,1980876,431.000000,431.0,509,4596,3891.701375,9.029470,1.000000
1,385763009,Hospice care (regime/therapy),4098,1766238,431.000000,431.0,61,162,28954.721311,67.180328,25.296296
2,171207006,Depression screening (procedure),3614,1557634,431.000000,431.0,500,3614,3115.268000,7.228000,1.000000
3,454711000124102,Depression screening using Patient Health Ques...,3614,1557634,431.000000,431.0,500,3614,3115.268000,7.228000,1.000000
4,428211000124100,Assessment of substance use (procedure),2906,1252486,431.000000,431.0,436,2906,2872.674312,6.665138,1.000000
5,265764009,Renal dialysis (procedure),2746,2757221,1004.086307,978.0,5,2746,551444.200000,549.200000,1.000000
6,762993000,Assessment using Morse Fall Scale (procedure),2422,1043882,431.000000,431.0,268,2422,3895.082090,9.037313,1.000000
7,710841007,Assessment of anxiety (procedure),2288,986128,431.000000,431.0,437,2288,2256.585812,5.235698,1.000000
8,430193006,Medication Reconciliation (procedure),2284,1162840,509.124343,496.0,418,2284,2781.913876,5.464115,1.000000
9,713106006,Screening for drug abuse (procedure),1484,639604,431.000000,431.0,333,1484,1920.732733,4.456456,1.000000
10,866148006,Screening for domestic abuse (procedure),1432,617192,431.000000,431.0,356,1432,1733.685393,4.022472,1.000000
11,763302001,Assessment using Alcohol Use Disorders Identif...,1422,612882,431.000000,431.0,331,1422,1851.607251,4.296073,1.000000
12,180325003,Electrical cardioversion,1383,35824002,25903.110629,25066.0,74,1383,484108.135135,18.689189,1.000000
13,274804006,Evaluation of uterine fundal height,1065,5631281,5287.587793,5149.0,71,1065,79313.816901,15.000000,1.000000
14,225158009,Auscultation of the fetal heart,1065,5657822,5312.508920,5157.0,71,1065,79687.633803,15.000000,1.000000
15,229064008,Movement therapy (regime/therapy),890,383590,431.000000,431.0,89,890,4310.000000,10.000000,1.000000
16,76601001,Intramuscular injection,522,1325634,2539.528736,2460.5,45,522,29458.533333,11.600000,1.000000
17,703423002,Combined chemotherapy and radiation therapy (p...,444,5237596,11796.387387,11441.5,21,444,249409.333333,21.142857,1.000000
18,73761001,Colonoscopy,424,5021003,11841.988208,11465.5,233,424,21549.369099,1.819742,1.000000
19,18286008,Catheter ablation of tissue of heart,365,3405999,9331.504110,9117.0,54,365,63074.055556,6.759259,1.000000

TOP 20 PROCEDURES BY AVERAGE COST
----------------------------------------------------------------------

,CODE,DESCRIPTION,Procedure_Count,Total_Procedure_Cost,Average_Procedure_Cost,Median_Procedure_Cost,Unique_Patients,Unique_Encounters,Cost_Per_Patient,Procedures_Per_Patient,Procedures_Per_Encounter
0,305351004,Admit to ICU (procedure),5,1031302,206260.400000,199610.0,2,2,515651.000000,2.500000,2.50
1,232717009,Coronary artery bypass grafting,9,423773,47085.888889,43374.0,8,9,52971.625000,1.125000,1.00
2,392021009,Lumpectomy of breast (procedure),5,146765,29353.000000,29349.0,5,5,29353.000000,1.000000,1.00
3,302497006,Hemodialysis (procedure),27,791088,29299.555556,28314.0,4,4,197772.000000,6.750000,6.75
4,447365002,Insertion of biventricular implantable cardiov...,4,108804,27201.000000,25503.0,4,4,27201.000000,1.000000,1.00
5,180325003,Electrical cardioversion,1383,35824002,25903.110629,25066.0,74,1383,484108.135135,18.689189,1.00
6,43075005,Partial resection of colon,7,176605,25229.285714,23031.0,7,7,25229.285714,1.000000,1.00
7,432231006,Fine needle aspiration biopsy of lung (procedure),1,23141,23141.000000,23141.0,1,1,23141.000000,1.000000,1.00
8,433112001,Percutaneous mechanical thrombectomy of portal...,57,1152998,20228.035088,19073.0,55,57,20963.600000,1.036364,1.00
9,415070008,Percutaneous coronary intervention,9,177552,19728.000000,17748.0,8,9,22194.000000,1.125000,1.00
10,91602002,Thoracentesis (procedure),1,19622,19622.000000,19622.0,1,1,19622.000000,1.000000,1.00
11,80146002,Appendectomy,2,34182,17091.000000,17091.0,2,2,17091.000000,1.000000,1.00
12,699253003,Surgical manipulation of joint of knee,12,195841,16320.083333,16759.0,12,12,16320.083333,1.000000,1.00
13,22523008,Vasectomy,5,60531,12106.200000,11304.0,5,5,12106.200000,1.000000,1.00
14,73761001,Colonoscopy,424,5021003,11841.988208,11465.5,233,424,21549.369099,1.819742,1.00
15,180256009,Subcutaneous immunotherapy,54,639117,11835.500000,11373.5,1,54,639117.000000,54.000000,1.00
16,703423002,Combined chemotherapy and radiation therapy (p...,444,5237596,11796.387387,11441.5,21,444,249409.333333,21.142857,1.00
17,45595009,Laparoscopic Removal of Gall Bladder,2,23341,11670.500000,11670.5,2,2,11670.500000,1.000000,1.00
18,443497002,Excision of sentinel lymph node (procedure),4,45108,11277.000000,11102.5,4,4,11277.000000,1.000000,1.00
19,65546002,Extraction of wisdom tooth,4,44830,11207.500000,10968.5,4,4,11207.500000,1.000000,1.00

TOP 20 HIGH-UTILIZATION PROCEDURES
----------------------------------------------------------------------

,CODE,DESCRIPTION,Procedure_Count,Total_Procedure_Cost,Average_Procedure_Cost,Median_Procedure_Cost,Unique_Patients,Unique_Encounters,Cost_Per_Patient,Procedures_Per_Patient,Procedures_Per_Encounter
0,710824005,Assessment of health and social care needs (pr...,4596,1980876,431.000000,431.0,509,4596,3891.701375,9.029470,1.000000
1,385763009,Hospice care (regime/therapy),4098,1766238,431.000000,431.0,61,162,28954.721311,67.180328,25.296296
2,171207006,Depression screening (procedure),3614,1557634,431.000000,431.0,500,3614,3115.268000,7.228000,1.000000
3,454711000124102,Depression screening using Patient Health Ques...,3614,1557634,431.000000,431.0,500,3614,3115.268000,7.228000,1.000000
4,428211000124100,Assessment of substance use (procedure),2906,1252486,431.000000,431.0,436,2906,2872.674312,6.665138,1.000000
5,265764009,Renal dialysis (procedure),2746,2757221,1004.086307,978.0,5,2746,551444.200000,549.200000,1.000000
6,762993000,Assessment using Morse Fall Scale (procedure),2422,1043882,431.000000,431.0,268,2422,3895.082090,9.037313,1.000000
7,710841007,Assessment of anxiety (procedure),2288,986128,431.000000,431.0,437,2288,2256.585812,5.235698,1.000000
8,430193006,Medication Reconciliation (procedure),2284,1162840,509.124343,496.0,418,2284,2781.913876,5.464115,1.000000
9,713106006,Screening for drug abuse (procedure),1484,639604,431.000000,431.0,333,1484,1920.732733,4.456456,1.000000
10,866148006,Screening for domestic abuse (procedure),1432,617192,431.000000,431.0,356,1432,1733.685393,4.022472,1.000000
11,763302001,Assessment using Alcohol Use Disorders Identif...,1422,612882,431.000000,431.0,331,1422,1851.607251,4.296073,1.000000
12,180325003,Electrical cardioversion,1383,35824002,25903.110629,25066.0,74,1383,484108.135135,18.689189,1.000000
13,225158009,Auscultation of the fetal heart,1065,5657822,5312.508920,5157.0,71,1065,79687.633803,15.000000,1.000000
14,274804006,Evaluation of uterine fundal height,1065,5631281,5287.587793,5149.0,71,1065,79313.816901,15.000000,1.000000
15,229064008,Movement therapy (regime/therapy),890,383590,431.000000,431.0,89,890,4310.000000,10.000000,1.000000
16,76601001,Intramuscular injection,522,1325634,2539.528736,2460.5,45,522,29458.533333,11.600000,1.000000
17,703423002,Combined chemotherapy and radiation therapy (p...,444,5237596,11796.387387,11441.5,21,444,249409.333333,21.142857,1.000000
18,73761001,Colonoscopy,424,5021003,11841.988208,11465.5,233,424,21549.369099,1.819742,1.000000
19,18286008,Catheter ablation of tissue of heart,365,3405999,9331.504110,9117.0,54,365,63074.055556,6.759259,1.000000

PROCEDURE COST CONCENTRATION
----------------------------------------------------------------------
Total procedure cost: 105,517,711.00
Top 10 procedures total cost: 69,183,405.00
Top 10 procedure cost share: 65.57%
Top 20 procedures total cost: 82,971,804.00
Top 20 procedure cost share: 78.63%

PROCEDURE UTILIZATION CONCENTRATION
----------------------------------------------------------------------
Total procedures: 47,701
Top 10 procedure volume: 30,052
Top 10 procedure utilization share: 63.00%
Top 20 procedure volume: 39,064
Top 20 procedure utilization share: 81.89%

OVERALL PROCEDURE × COST / UTILIZATION METRICS
----------------------------------------------------------------------

                           Metric         Value
0                Total Procedures  4.770100e+04
1          Unique Procedure Codes  1.570000e+02
2   Unique Procedure Descriptions  1.630000e+02
3                 Unique Patients  7.930000e+02
4               Unique Encounters  1.467000e+04
5            Total Procedure Cost  1.055177e+08
6          Average Procedure Cost  2.212065e+03
7           Median Procedure Cost  4.310000e+02
8           Top 10 Cost Share (%)  6.556568e+01
9           Top 20 Cost Share (%)  7.863306e+01
10   Top 10 Utilization Share (%)  6.300078e+01
11   Top 20 Utilization Share (%)  8.189346e+01

In [126]:
# ----------------------------------------------------------------------------
# 1. SELECT CORRECT STEP 4.18A OUTPUT + REQUIRED COLUMN CHECK
# ----------------------------------------------------------------------------

# Step 4.18A generated the complete procedure-level summary as
# `procedure_cost_summary`.
#
# Do NOT use the older/basic `procedure_summary`, which only contains:
# ['Procedure', 'Procedure_Count']
#
# `procedure_cost_summary` contains the complete 11-column dataset required
# for Step 4.18B.

if "procedure_cost_summary" not in globals():
    raise NameError(
        "procedure_cost_summary does not exist. "
        "Please run STEP 4.18A first."
    )

# Use the detailed Step 4.18A output
procedure_summary = procedure_cost_summary.copy()


required_columns = [
    "CODE",
    "DESCRIPTION",
    "Procedure_Count",
    "Total_Procedure_Cost",
    "Average_Procedure_Cost",
    "Median_Procedure_Cost",
    "Unique_Patients",
    "Unique_Encounters",
    "Cost_Per_Patient",
    "Procedures_Per_Patient",
    "Procedures_Per_Encounter"
]


missing_columns = [
    col for col in required_columns
    if col not in procedure_summary.columns
]


if missing_columns:
    print("\nSTATUS: FAIL")
    print("Missing columns:", missing_columns)

    print("\nCurrent procedure_summary columns:")
    print(procedure_summary.columns.tolist())

    raise ValueError(
        "procedure_cost_summary does not contain all required "
        "Step 4.18B columns."
    )


print("\nSOURCE DATAFRAME")
print("-" * 70)
print("Using: procedure_cost_summary")
print(f"Shape: {procedure_summary.shape}")
print("Columns:")
print(procedure_summary.columns.tolist())


print("\nREQUIRED COLUMN CHECK")
print("-" * 70)
print("STATUS: PASS")
print("All required procedure columns are available.")

SOURCE DATAFRAME
----------------------------------------------------------------------
Using: procedure_cost_summary
Shape: (163, 11)
Columns:
['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter']

REQUIRED COLUMN CHECK
----------------------------------------------------------------------
STATUS: PASS
All required procedure columns are available.

In [127]:
# ============================================================================
# STEP 4.18B — PROCEDURE COST & UTILIZATION ANALYSIS
# ----------------------------------------------------------------------------
# Purpose:
#   Identify procedures that are:
#   1. High-cost
#   2. High-utilization
#   3. High-cost per patient
#   4. Highly repetitive per patient
#   5. Potential cost/utilization outliers
#
# IMPORTANT:
#   Step 4.18A creates:
#       procedure_cost_summary
#
#   procedure_summary is a different dataframe containing only:
#       ['Procedure', 'Procedure_Count']
#
#   Therefore, this step uses procedure_cost_summary.
# ============================================================================

print("=" * 70)
print("STEP 4.18B — PROCEDURE COST & UTILIZATION ANALYSIS")
print("=" * 70)


# ============================================================================
# 1. USE THE CORRECT STEP 4.18A OUTPUT
# ============================================================================

# Step 4.18A generated the complete procedure-level summary as:
# procedure_cost_summary

procedure_analysis = procedure_cost_summary.copy()


# ============================================================================
# 2. REQUIRED COLUMN CHECK
# ============================================================================

required_columns = [
    "CODE",
    "DESCRIPTION",
    "Procedure_Count",
    "Total_Procedure_Cost",
    "Average_Procedure_Cost",
    "Median_Procedure_Cost",
    "Unique_Patients",
    "Unique_Encounters",
    "Cost_Per_Patient",
    "Procedures_Per_Patient",
    "Procedures_Per_Encounter"
]

missing_columns = [
    col for col in required_columns
    if col not in procedure_analysis.columns
]


if missing_columns:

    print("\nSTATUS: FAIL")
    print("Missing columns:", missing_columns)

    print("\nCurrent procedure_analysis columns:")
    print(procedure_analysis.columns.tolist())

    raise ValueError(
        "procedure_cost_summary does not contain all required "
        "Step 4.18A columns."
    )


print("\nREQUIRED COLUMN CHECK")
print("-" * 70)
print("STATUS: PASS")
print("All required procedure columns are available.")

print(f"Procedure records available: {len(procedure_analysis):,}")


# ============================================================================
# 3. DATA TYPE / NUMERIC VALIDATION
# ============================================================================

numeric_columns = [
    "Procedure_Count",
    "Total_Procedure_Cost",
    "Average_Procedure_Cost",
    "Median_Procedure_Cost",
    "Unique_Patients",
    "Unique_Encounters",
    "Cost_Per_Patient",
    "Procedures_Per_Patient",
    "Procedures_Per_Encounter"
]

for col in numeric_columns:

    procedure_analysis[col] = pd.to_numeric(
        procedure_analysis[col],
        errors="coerce"
    )


# Remove records where the key cost/utilization measures cannot be evaluated
procedure_analysis = procedure_analysis.dropna(
    subset=[
        "Procedure_Count",
        "Total_Procedure_Cost",
        "Average_Procedure_Cost",
        "Unique_Patients",
        "Cost_Per_Patient",
        "Procedures_Per_Patient"
    ]
).copy()


print("\nDATA VALIDATION")
print("-" * 70)
print(f"Valid procedure records: {len(procedure_analysis):,}")
print(
    f"Missing values in key metrics: "
    f"{procedure_analysis[[
        'Procedure_Count',
        'Total_Procedure_Cost',
        'Average_Procedure_Cost',
        'Cost_Per_Patient',
        'Procedures_Per_Patient'
    ]].isna().sum().sum():,}"
)


# ============================================================================
# 4. HIGH-COST PROCEDURES
# ----------------------------------------------------------------------------
# Ranked by total procedure cost.
# ============================================================================

high_cost_procedures = (
    procedure_analysis
    .sort_values(
        "Total_Procedure_Cost",
        ascending=False
    )
    .head(10)
    .copy()
)


print("\nTOP 10 PROCEDURES BY TOTAL COST")
print("-" * 70)

print(
    high_cost_procedures[
        [
            "CODE",
            "DESCRIPTION",
            "Procedure_Count",
            "Total_Procedure_Cost",
            "Average_Procedure_Cost",
            "Unique_Patients",
            "Cost_Per_Patient"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 5. HIGH-UTILIZATION PROCEDURES
# ----------------------------------------------------------------------------
# Ranked by number of procedure records.
# ============================================================================

high_utilization_procedures = (
    procedure_analysis
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .head(10)
    .copy()
)


print("\nTOP 10 PROCEDURES BY UTILIZATION")
print("-" * 70)

print(
    high_utilization_procedures[
        [
            "CODE",
            "DESCRIPTION",
            "Procedure_Count",
            "Total_Procedure_Cost",
            "Average_Procedure_Cost",
            "Unique_Patients",
            "Procedures_Per_Patient"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 6. HIGH UNIT-COST PROCEDURES
# ----------------------------------------------------------------------------
# Ranked by average cost per procedure.
#
# NOTE:
#   This is different from total cost.
#   A procedure can have a very high unit cost but low utilization.
# ============================================================================

high_unit_cost_procedures = (
    procedure_analysis
    .sort_values(
        "Average_Procedure_Cost",
        ascending=False
    )
    .head(10)
    .copy()
)


print("\nTOP 10 PROCEDURES BY AVERAGE COST")
print("-" * 70)

print(
    high_unit_cost_procedures[
        [
            "CODE",
            "DESCRIPTION",
            "Procedure_Count",
            "Average_Procedure_Cost",
            "Median_Procedure_Cost",
            "Total_Procedure_Cost",
            "Unique_Patients"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 7. HIGH COST PER PATIENT
# ----------------------------------------------------------------------------
# Identifies procedures generating the highest cumulative cost per patient.
# ============================================================================

high_cost_per_patient = (
    procedure_analysis
    .sort_values(
        "Cost_Per_Patient",
        ascending=False
    )
    .head(10)
    .copy()
)


print("\nTOP 10 PROCEDURES BY COST PER PATIENT")
print("-" * 70)

print(
    high_cost_per_patient[
        [
            "CODE",
            "DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Total_Procedure_Cost",
            "Cost_Per_Patient",
            "Procedures_Per_Patient"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 8. HIGHLY REPEATED PROCEDURES
# ----------------------------------------------------------------------------
# Ranked by average number of procedures per patient.
# ============================================================================

high_repeat_procedures = (
    procedure_analysis
    .sort_values(
        "Procedures_Per_Patient",
        ascending=False
    )
    .head(10)
    .copy()
)


print("\nTOP 10 PROCEDURES BY PROCEDURES PER PATIENT")
print("-" * 70)

print(
    high_repeat_procedures[
        [
            "CODE",
            "DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Unique_Encounters",
            "Procedures_Per_Patient",
            "Procedures_Per_Encounter",
            "Total_Procedure_Cost"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 9. COST × UTILIZATION CLASSIFICATION
# ----------------------------------------------------------------------------
# Uses the median across procedure codes as the threshold.
#
# Four profiles:
#   High Cost / High Utilization
#   High Cost / Low Utilization
#   Low Cost / High Utilization
#   Low Cost / Low Utilization
# ============================================================================

median_cost = procedure_analysis[
    "Total_Procedure_Cost"
].median()

median_volume = procedure_analysis[
    "Procedure_Count"
].median()


procedure_analysis["Cost_Profile"] = np.where(
    procedure_analysis["Total_Procedure_Cost"] >= median_cost,
    "High Cost",
    "Low Cost"
)


procedure_analysis["Utilization_Profile"] = np.where(
    procedure_analysis["Procedure_Count"] >= median_volume,
    "High Utilization",
    "Low Utilization"
)


procedure_analysis["Procedure_Profile"] = (
    procedure_analysis["Cost_Profile"]
    + " / "
    + procedure_analysis["Utilization_Profile"]
)


print("\nPROCEDURE COST × UTILIZATION PROFILE")
print("-" * 70)

print(f"Median procedure total cost: {median_cost:,.2f}")
print(f"Median procedure volume: {median_volume:,.2f}")

profile_counts = (
    procedure_analysis[
        "Procedure_Profile"
    ]
    .value_counts()
    .rename_axis("Profile")
    .reset_index(name="Procedure_Count")
)


print(
    profile_counts.to_string(index=False)
)


# ============================================================================
# 10. HIGH-COST + HIGH-UTILIZATION PROCEDURES
# ----------------------------------------------------------------------------

high_cost_high_utilization = (
    procedure_analysis[
        (procedure_analysis["Total_Procedure_Cost"] >= median_cost)
        &
        (procedure_analysis["Procedure_Count"] >= median_volume)
    ]
    .sort_values(
        "Total_Procedure_Cost",
        ascending=False
    )
    .copy()
)


print("\nHIGH-COST + HIGH-UTILIZATION PROCEDURES")
print("-" * 70)

if len(high_cost_high_utilization) > 0:

    print(
        high_cost_high_utilization[
            [
                "CODE",
                "DESCRIPTION",
                "Procedure_Count",
                "Total_Procedure_Cost",
                "Average_Procedure_Cost",
                "Unique_Patients",
                "Cost_Per_Patient"
            ]
        ].to_string(index=False)
    )

else:

    print("No high-cost/high-utilization procedures identified.")


# ============================================================================
# 11. HIGH-COST + LOW-UTILIZATION PROCEDURES
# ----------------------------------------------------------------------------
# These are particularly important because they may represent:
#   - expensive procedures
#   - relatively low frequency
#   - potential high-impact cost drivers
# ============================================================================

high_cost_low_utilization = (
    procedure_analysis[
        (procedure_analysis["Total_Procedure_Cost"] >= median_cost)
        &
        (procedure_analysis["Procedure_Count"] < median_volume)
    ]
    .sort_values(
        "Total_Procedure_Cost",
        ascending=False
    )
    .copy()
)


print("\nHIGH-COST + LOW-UTILIZATION PROCEDURES")
print("-" * 70)

if len(high_cost_low_utilization) > 0:

    print(
        high_cost_low_utilization[
            [
                "CODE",
                "DESCRIPTION",
                "Procedure_Count",
                "Total_Procedure_Cost",
                "Average_Procedure_Cost",
                "Unique_Patients",
                "Cost_Per_Patient"
            ]
        ]
        .head(10)
        .to_string(index=False)
    )

else:

    print("No high-cost/low-utilization procedures identified.")


# ============================================================================
# 12. LOW-COST + HIGH-UTILIZATION PROCEDURES
# ----------------------------------------------------------------------------
# These procedures may have low unit cost but create substantial aggregate
# workload/cost because of high frequency.
# ============================================================================

low_cost_high_utilization = (
    procedure_analysis[
        (procedure_analysis["Total_Procedure_Cost"] < median_cost)
        &
        (procedure_analysis["Procedure_Count"] >= median_volume)
    ]
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .copy()
)


print("\nLOW-COST + HIGH-UTILIZATION PROCEDURES")
print("-" * 70)

if len(low_cost_high_utilization) > 0:

    print(
        low_cost_high_utilization[
            [
                "CODE",
                "DESCRIPTION",
                "Procedure_Count",
                "Total_Procedure_Cost",
                "Average_Procedure_Cost",
                "Unique_Patients",
                "Procedures_Per_Patient"
            ]
        ]
        .head(10)
        .to_string(index=False)
    )

else:

    print("No low-cost/high-utilization procedures identified.")


# ============================================================================
# 13. LOW-COST + LOW-UTILIZATION PROCEDURES
# ============================================================================

low_cost_low_utilization = (
    procedure_analysis[
        (procedure_analysis["Total_Procedure_Cost"] < median_cost)
        &
        (procedure_analysis["Procedure_Count"] < median_volume)
    ]
    .sort_values(
        "Total_Procedure_Cost",
        ascending=False
    )
    .copy()
)


print("\nLOW-COST + LOW-UTILIZATION PROCEDURES")
print("-" * 70)

print(
    low_cost_low_utilization[
        [
            "CODE",
            "DESCRIPTION",
            "Procedure_Count",
            "Total_Procedure_Cost",
            "Average_Procedure_Cost"
        ]
    ]
    .head(10)
    .to_string(index=False)
)


# ============================================================================
# 14. PROCEDURE COST CONCENTRATION
# ----------------------------------------------------------------------------
# Measures how concentrated total procedure expenditure is among the
# highest-cost procedure codes.
# ============================================================================

total_cost = procedure_analysis[
    "Total_Procedure_Cost"
].sum()


top_10_cost = (
    procedure_analysis
    .nlargest(
        min(10, len(procedure_analysis)),
        "Total_Procedure_Cost"
    )[
        "Total_Procedure_Cost"
    ]
    .sum()
)


top_20_cost = (
    procedure_analysis
    .nlargest(
        min(20, len(procedure_analysis)),
        "Total_Procedure_Cost"
    )[
        "Total_Procedure_Cost"
    ]
    .sum()
)


top_10_cost_share = (
    (top_10_cost / total_cost) * 100
    if total_cost > 0
    else 0
)


top_20_cost_share = (
    (top_20_cost / total_cost) * 100
    if total_cost > 0
    else 0
)


print("\nPROCEDURE COST CONCENTRATION")
print("-" * 70)

print(
    f"Total procedure cost: "
    f"{total_cost:,.2f}"
)

print(
    f"Top 10 procedure cost: "
    f"{top_10_cost:,.2f}"
)

print(
    f"Top 10 procedure cost share: "
    f"{top_10_cost_share:.2f}%"
)

print(
    f"Top 20 procedure cost: "
    f"{top_20_cost:,.2f}"
)

print(
    f"Top 20 procedure cost share: "
    f"{top_20_cost_share:.2f}%"
)


# ============================================================================
# 15. PROCEDURE UTILIZATION CONCENTRATION
# ============================================================================

total_procedures = procedure_analysis[
    "Procedure_Count"
].sum()


top_10_volume = (
    procedure_analysis
    .nlargest(
        min(10, len(procedure_analysis)),
        "Procedure_Count"
    )[
        "Procedure_Count"
    ]
    .sum()
)


top_20_volume = (
    procedure_analysis
    .nlargest(
        min(20, len(procedure_analysis)),
        "Procedure_Count"
    )[
        "Procedure_Count"
    ]
    .sum()
)


top_10_utilization_share = (
    (top_10_volume / total_procedures) * 100
    if total_procedures > 0
    else 0
)


top_20_utilization_share = (
    (top_20_volume / total_procedures) * 100
    if total_procedures > 0
    else 0
)


print("\nPROCEDURE UTILIZATION CONCENTRATION")
print("-" * 70)

print(
    f"Total procedures: "
    f"{total_procedures:,.0f}"
)

print(
    f"Top 10 procedure volume: "
    f"{top_10_volume:,.0f}"
)

print(
    f"Top 10 procedure utilization share: "
    f"{top_10_utilization_share:.2f}%"
)

print(
    f"Top 20 procedure volume: "
    f"{top_20_volume:,.0f}"
)

print(
    f"Top 20 procedure utilization share: "
    f"{top_20_utilization_share:.2f}%"
)


# ============================================================================
# 16. OVERALL PROCEDURE × COST / UTILIZATION METRICS
# ============================================================================

overall_metrics = pd.DataFrame({
    "Metric": [
        "Total Procedures",
        "Unique Procedure Codes",
        "Unique Procedure Descriptions",
        "Unique Patients",
        "Unique Encounters",
        "Total Procedure Cost",
        "Average Procedure Cost",
        "Median Procedure Cost",
        "Top 10 Cost Share (%)",
        "Top 20 Cost Share (%)",
        "Top 10 Utilization Share (%)",
        "Top 20 Utilization Share (%)"
    ],

    "Value": [
        procedure_analysis["Procedure_Count"].sum(),

        procedure_analysis["CODE"].nunique(),

        procedure_analysis["DESCRIPTION"].nunique(),

        procedure_analysis["Unique_Patients"].max(),

        procedure_analysis["Unique_Encounters"].sum(),

        total_cost,

        (
            total_cost / total_procedures
            if total_procedures > 0
            else 0
        ),

        procedure_analysis["Average_Procedure_Cost"].median(),

        top_10_cost_share,

        top_20_cost_share,

        top_10_utilization_share,

        top_20_utilization_share
    ]
})


print("\nOVERALL PROCEDURE × COST / UTILIZATION METRICS")
print("-" * 70)

print(
    overall_metrics.to_string(index=False)
)


# ============================================================================
# 17. SAVE KEY OUTPUT DATAFRAMES
# ----------------------------------------------------------------------------
# These variables can be used by later analysis/dashboard steps.
# ============================================================================

# Complete procedure-level analysis
procedure_cost_utilization_analysis = procedure_analysis.copy()


# Top cost procedures
top_procedures_by_cost = (
    procedure_analysis
    .nlargest(
        min(20, len(procedure_analysis)),
        "Total_Procedure_Cost"
    )
    .copy()
)


# Top utilization procedures
top_procedures_by_frequency = (
    procedure_analysis
    .nlargest(
        min(20, len(procedure_analysis)),
        "Procedure_Count"
    )
    .copy()
)


# Top average-cost procedures
top_procedures_by_average_cost = (
    procedure_analysis
    .nlargest(
        min(20, len(procedure_analysis)),
        "Average_Procedure_Cost"
    )
    .copy()
)


# ============================================================================
# 18. FINAL SUMMARY
# ============================================================================

print("\n" + "=" * 70)
print("STEP 4.18B COMPLETE")
print("=" * 70)

print(
    f"Procedures analysed: "
    f"{len(procedure_analysis):,}"
)

print(
    f"Total procedure records: "
    f"{total_procedures:,.0f}"
)

print(
    f"Total procedure cost: "
    f"{total_cost:,.2f}"
)

print(
    f"High-cost procedures identified: "
    f"{len(high_cost_procedures):,}"
)

print(
    f"High-utilization procedures identified: "
    f"{len(high_utilization_procedures):,}"
)

print(
    f"High-cost/high-utilization procedures: "
    f"{len(high_cost_high_utilization):,}"
)

print(
    f"High-cost/low-utilization procedures: "
    f"{len(high_cost_low_utilization):,}"
)

print(
    f"Low-cost/high-utilization procedures: "
    f"{len(low_cost_high_utilization):,}"
)

print(
    f"Top 10 cost concentration: "
    f"{top_10_cost_share:.2f}%"
)

print(
    f"Top 20 cost concentration: "
    f"{top_20_cost_share:.2f}%"
)

print(
    f"Top 10 utilization concentration: "
    f"{top_10_utilization_share:.2f}%"
)

print(
    f"Top 20 utilization concentration: "
    f"{top_20_utilization_share:.2f}%"
)

print("\nSTATUS: PASS")
print("=" * 70)

======================================================================
STEP 4.18B — PROCEDURE COST & UTILIZATION ANALYSIS
======================================================================

REQUIRED COLUMN CHECK
----------------------------------------------------------------------
STATUS: PASS
All required procedure columns are available.
Procedure records available: 163

DATA VALIDATION
----------------------------------------------------------------------
Valid procedure records: 163
Missing values in key metrics: 0

TOP 10 PROCEDURES BY TOTAL COST
----------------------------------------------------------------------
     CODE                                             DESCRIPTION  Procedure_Count  Total_Procedure_Cost  Average_Procedure_Cost  Unique_Patients  Cost_Per_Patient
180325003                                Electrical cardioversion             1383              35824002            25903.110629               74     484108.135135
225158009                         Auscultation of the fetal heart             1065               5657822             5312.508920               71      79687.633803
274804006                     Evaluation of uterine fundal height             1065               5631281             5287.587793               71      79313.816901
703423002 Combined chemotherapy and radiation therapy (procedure)              444               5237596            11796.387387               21     249409.333333
 73761001                                             Colonoscopy              424               5021003            11841.988208              233      21549.369099
 18286008                    Catheter ablation of tissue of heart              365               3405999             9331.504110               54      63074.055556
265764009                              Renal dialysis (procedure)             2746               2757221             1004.086307                5     551444.200000
710824005  Assessment of health and social care needs (procedure)             4596               1980876              431.000000              509       3891.701375
312681000                           Bone density scan (procedure)              198               1901367             9602.863636              115      16533.626087
385763009                           Hospice care (regime/therapy)             4098               1766238              431.000000               61      28954.721311

TOP 10 PROCEDURES BY UTILIZATION
----------------------------------------------------------------------
           CODE                                                                        DESCRIPTION  Procedure_Count  Total_Procedure_Cost  Average_Procedure_Cost  Unique_Patients  Procedures_Per_Patient
      710824005                             Assessment of health and social care needs (procedure)             4596               1980876              431.000000              509                9.029470
      385763009                                                      Hospice care (regime/therapy)             4098               1766238              431.000000               61               67.180328
      171207006                                                   Depression screening (procedure)             3614               1557634              431.000000              500                7.228000
454711000124102 Depression screening using Patient Health Questionnaire Two-Item score (procedure)             3614               1557634              431.000000              500                7.228000
428211000124100                                            Assessment of substance use (procedure)             2906               1252486              431.000000              436                6.665138
      265764009                                                         Renal dialysis (procedure)             2746               2757221             1004.086307                5              549.200000
      762993000                                      Assessment using Morse Fall Scale (procedure)             2422               1043882              431.000000              268                9.037313
      710841007                                                  Assessment of anxiety (procedure)             2288                986128              431.000000              437                5.235698
      430193006                                              Medication Reconciliation (procedure)             2284               1162840              509.124343              418                5.464115
      713106006                                               Screening for drug abuse (procedure)             1484                639604              431.000000              333                4.456456

TOP 10 PROCEDURES BY AVERAGE COST
----------------------------------------------------------------------
     CODE                                                                     DESCRIPTION  Procedure_Count  Average_Procedure_Cost  Median_Procedure_Cost  Total_Procedure_Cost  Unique_Patients
305351004                                                        Admit to ICU (procedure)                5           206260.400000               199610.0               1031302                2
232717009                                                 Coronary artery bypass grafting                9            47085.888889                43374.0                423773                8
392021009                                                Lumpectomy of breast (procedure)                5            29353.000000                29349.0                146765                5
302497006                                                        Hemodialysis (procedure)               27            29299.555556                28314.0                791088                4
447365002               Insertion of biventricular implantable cardioverter defibrillator                4            27201.000000                25503.0                108804                4
180325003                                                        Electrical cardioversion             1383            25903.110629                25066.0              35824002               74
 43075005                                                      Partial resection of colon                7            25229.285714                23031.0                176605                7
432231006                               Fine needle aspiration biopsy of lung (procedure)                1            23141.000000                23141.0                 23141                1
433112001 Percutaneous mechanical thrombectomy of portal vein using fluoroscopic guidance               57            20228.035088                19073.0               1152998               55
415070008                                              Percutaneous coronary intervention                9            19728.000000                17748.0                177552                8

TOP 10 PROCEDURES BY COST PER PATIENT
----------------------------------------------------------------------
     CODE                                             DESCRIPTION  Procedure_Count  Unique_Patients  Total_Procedure_Cost  Cost_Per_Patient  Procedures_Per_Patient
180256009                              Subcutaneous immunotherapy               54                1                639117     639117.000000               54.000000
265764009                              Renal dialysis (procedure)             2746                5               2757221     551444.200000              549.200000
305351004                                Admit to ICU (procedure)                5                2               1031302     515651.000000                2.500000
180325003                                Electrical cardioversion             1383               74              35824002     484108.135135               18.689189
703423002 Combined chemotherapy and radiation therapy (procedure)              444               21               5237596     249409.333333               21.142857
302497006                                Hemodialysis (procedure)               27                4                791088     197772.000000                6.750000
228557008       Cognitive and behavioral therapy (regime/therapy)              136               17               1412779      83104.647059                8.000000
225158009                         Auscultation of the fetal heart             1065               71               5657822      79687.633803               15.000000
274804006                     Evaluation of uterine fundal height             1065               71               5631281      79313.816901               15.000000
127783003                                  Spirometry (procedure)              209               23               1628688      70812.521739                9.086957

TOP 10 PROCEDURES BY PROCEDURES PER PATIENT
----------------------------------------------------------------------
             CODE                                                               DESCRIPTION  Procedure_Count  Unique_Patients  Unique_Encounters  Procedures_Per_Patient  Procedures_Per_Encounter  Total_Procedure_Cost
        265764009                                                Renal dialysis (procedure)             2746                5               2746              549.200000                  1.000000               2757221
        385763009                                             Hospice care (regime/therapy)             4098               61                162               67.180328                 25.296296               1766238
        180256009                                                Subcutaneous immunotherapy               54                1                 54               54.000000                  1.000000                639117
        398171003                                           Hearing examination (procedure)              144                4                144               36.000000                  1.000000                 62064
16335031000119100 High resolution computed tomography of chest without contrast (procedure)              144                4                144               36.000000                  1.000000                 62064
         33195004                                    Teleradiotherapy procedure (procedure)              170                5                170               34.000000                  1.000000                169567
        703423002                   Combined chemotherapy and radiation therapy (procedure)              444               21                444               21.142857                  1.000000               5237596
        180325003                                                  Electrical cardioversion             1383               74               1383               18.689189                  1.000000              35824002
        225158009                                           Auscultation of the fetal heart             1065               71               1065               15.000000                  1.000000               5657822
        274804006                                       Evaluation of uterine fundal height             1065               71               1065               15.000000                  1.000000               5631281

PROCEDURE COST × UTILIZATION PROFILE
----------------------------------------------------------------------
Median procedure total cost: 72,576.00
Median procedure volume: 49.00
                     Profile  Procedure_Count
High Cost / High Utilization               65
  Low Cost / Low Utilization               64
 Low Cost / High Utilization               17
 High Cost / Low Utilization               17

HIGH-COST + HIGH-UTILIZATION PROCEDURES
----------------------------------------------------------------------
           CODE                                                                          DESCRIPTION  Procedure_Count  Total_Procedure_Cost  Average_Procedure_Cost  Unique_Patients  Cost_Per_Patient
      180325003                                                             Electrical cardioversion             1383              35824002            25903.110629               74     484108.135135
      225158009                                                      Auscultation of the fetal heart             1065               5657822             5312.508920               71      79687.633803
      274804006                                                  Evaluation of uterine fundal height             1065               5631281             5287.587793               71      79313.816901
      703423002                              Combined chemotherapy and radiation therapy (procedure)              444               5237596            11796.387387               21     249409.333333
       73761001                                                                          Colonoscopy              424               5021003            11841.988208              233      21549.369099
       18286008                                                 Catheter ablation of tissue of heart              365               3405999             9331.504110               54      63074.055556
      265764009                                                           Renal dialysis (procedure)             2746               2757221             1004.086307                5     551444.200000
      710824005                               Assessment of health and social care needs (procedure)             4596               1980876              431.000000              509       3891.701375
      312681000                                                        Bone density scan (procedure)              198               1901367             9602.863636              115      16533.626087
      385763009                                                        Hospice care (regime/therapy)             4098               1766238              431.000000               61      28954.721311
      169230002                                                  Ultrasound scan for fetal viability              184               1693824             9205.565217               81      20911.407407
      127783003                                                               Spirometry (procedure)              209               1628688             7792.765550               23      70812.521739
      171207006                                                     Depression screening (procedure)             3614               1557634              431.000000              500       3115.268000
454711000124102   Depression screening using Patient Health Questionnaire Two-Item score (procedure)             3614               1557634              431.000000              500       3115.268000
      228557008                                    Cognitive and behavioral therapy (regime/therapy)              136               1412779            10388.080882               17      83104.647059
       76601001                                                              Intramuscular injection              522               1325634             2539.528736               45      29458.533333
428211000124100                                              Assessment of substance use (procedure)             2906               1252486              431.000000              436       2872.674312
      430193006                                                Medication Reconciliation (procedure)             2284               1162840              509.124343              418       2781.913876
      433112001      Percutaneous mechanical thrombectomy of portal vein using fluoroscopic guidance               57               1152998            20228.035088               55      20963.600000
      762993000                                        Assessment using Morse Fall Scale (procedure)             2422               1043882              431.000000              268       3895.082090
      710841007                                                    Assessment of anxiety (procedure)             2288                986128              431.000000              437       2256.585812
      288086009                                                                    Suture open wound              103                956599             9287.368932               93      10286.010753
      252160004                                                              Standard pregnancy test              184                955125             5190.896739               81      11791.666667
      713106006                                                 Screening for drug abuse (procedure)             1484                639604              431.000000              333       1920.732733
      180256009                                                           Subcutaneous immunotherapy               54                639117            11835.500000                1     639117.000000
      274031008                                                                   Rectal polypectomy               61                624125            10231.557377               52      12002.403846
      866148006                                             Screening for domestic abuse (procedure)             1432                617192              431.000000              356       1733.685393
      763302001 Assessment using Alcohol Use Disorders Identification Test - Consumption (procedure)             1422                612882              431.000000              331       1851.607251
      399208008                                                        Plain chest X-ray (procedure)               78                604592             7751.179487               55      10992.581818
       65200003                                       Insertion of intrauterine contraceptive device               66                593949             8999.227273               46      12911.934783
      169553002                                              Insertion of subcutaneous contraceptive               62                548328             8844.000000               42      13055.428571
       46706006                                     Replacement of contraceptive intrauterine device               61                511534             8385.803279               38      13461.421053
      104091002                                             Hemoglobin / Hematocrit / Platelet count              237                480661             2028.105485               71       6769.873239
      269911007                                                       Sputum examination (procedure)               71                456479             6429.281690               68       6712.926471
      229064008                                                    Movement therapy (regime/therapy)              890                383590              431.000000               89       4310.000000
       15081005                                            Pulmonary rehabilitation (regime/therapy)              171                326546             1909.625731               12      27212.166667
      399014008                                   Vaccination for diphtheria  pertussis  and tetanus              119                311798             2620.151261               70       4454.257143
      104435004                                      Screening for occult blood in feces (procedure)               49                309715             6320.714286               49       6320.714286
       90226004            Cytopathology procedure  preparation of smear  genital source (procedure)              140                283128             2022.342857               17      16654.588235

In [128]:
print("procedure_summary columns:")
print(procedure_summary.columns.tolist())

print("\nAll variables containing 'procedure':")

for name in dir():
    if "procedure" in name.lower():
        try:
            obj = globals()[name]
            if hasattr(obj, "shape") and hasattr(obj, "columns"):
                print(f"{name}: shape={obj.shape}")
                print(f"    columns={obj.columns.tolist()}")
        except:
            pass

procedure_summary columns:
['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter']

All variables containing 'procedure':
high_cost_procedures: shape=(10, 11)
    columns=['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter']
high_repeat_procedures: shape=(10, 11)
    columns=['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter']
high_unit_cost_procedures: shape=(10, 11)
    columns=['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter']
high_utilization_procedures: shape=(10, 11)
    columns=['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter']
invalid_birth_procedures: shape=(0, 5)
    columns=['PATIENT', 'ENCOUNTER', 'START', 'Id', 'BIRTHDATE']
invalid_procedure_dates: shape=(0, 21)
    columns=['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION', 'Procedure_Year', 'Procedure_Month', 'Procedure_Month_Name', 'Procedure_Quarter', 'Procedure_Year_Month', 'Procedure_Day', 'Procedure_Day_Name', 'Procedure_Week', 'PROCEDURE_DURATION_MIN', 'PROCEDURE_DURATION_HOURS', 'PROCEDURE_DURATION_DAYS', 'PROCEDURE_DURATION_FLAG']
patient_procedure_cost: shape=(793, 3)
    columns=['PATIENT', 'Procedure_Count', 'Total_Procedure_Cost']
procedure_analysis: shape=(163, 14)
    columns=['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter', 'Cost_Profile', 'Utilization_Profile', 'Procedure_Profile']
procedure_check: shape=(47701, 11)
    columns=['START', 'STOP', 'PATIENT_procedure', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION', 'Id', 'PATIENT_encounter']
procedure_code_distribution: shape=(163, 5)
    columns=['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost']
procedure_cost_metrics: shape=(12, 2)
    columns=['Metric', 'Value']
procedure_cost_summary: shape=(163, 11)
    columns=['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter']
procedure_cost_utilization_analysis: shape=(163, 14)
    columns=['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter', 'Cost_Profile', 'Utilization_Profile', 'Procedure_Profile']
procedure_date_validation: shape=(3, 2)
    columns=['Validation', 'Count']
procedure_duration_anomalies: shape=(1, 21)
    columns=['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION', 'Procedure_Year', 'Procedure_Month', 'Procedure_Month_Name', 'Procedure_Quarter', 'Procedure_Year_Month', 'Procedure_Day', 'Procedure_Day_Name', 'Procedure_Week', 'PROCEDURE_DURATION_MIN', 'PROCEDURE_DURATION_HOURS', 'PROCEDURE_DURATION_DAYS', 'PROCEDURE_DURATION_FLAG']
procedure_duration_validation: shape=(5, 2)
    columns=['Validation', 'Count']
procedure_patient_dates: shape=(47701, 5)
    columns=['PATIENT', 'ENCOUNTER', 'START', 'Id', 'BIRTHDATE']
procedure_summary: shape=(163, 11)
    columns=['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter']
procedures: shape=(47701, 9)
    columns=['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION']
procedures_clean: shape=(47701, 21)
    columns=['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION', 'Procedure_Year', 'Procedure_Month', 'Procedure_Month_Name', 'Procedure_Quarter', 'Procedure_Year_Month', 'Procedure_Day', 'Procedure_Day_Name', 'Procedure_Week', 'PROCEDURE_DURATION_MIN', 'PROCEDURE_DURATION_HOURS', 'PROCEDURE_DURATION_DAYS', 'PROCEDURE_DURATION_FLAG']
top_procedures_by_average_cost: shape=(20, 14)
    columns=['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter', 'Cost_Profile', 'Utilization_Profile', 'Procedure_Profile']
top_procedures_by_cost: shape=(20, 14)
    columns=['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter', 'Cost_Profile', 'Utilization_Profile', 'Procedure_Profile']
top_procedures_by_frequency: shape=(20, 14)
    columns=['CODE', 'DESCRIPTION', 'Procedure_Count', 'Total_Procedure_Cost', 'Average_Procedure_Cost', 'Median_Procedure_Cost', 'Unique_Patients', 'Unique_Encounters', 'Cost_Per_Patient', 'Procedures_Per_Patient', 'Procedures_Per_Encounter', 'Cost_Profile', 'Utilization_Profile', 'Procedure_Profile']
zero_duration_procedures: shape=(2, 21)
    columns=['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION', 'Procedure_Year', 'Procedure_Month', 'Procedure_Month_Name', 'Procedure_Quarter', 'Procedure_Year_Month', 'Procedure_Day', 'Procedure_Day_Name', 'Procedure_Week', 'PROCEDURE_DURATION_MIN', 'PROCEDURE_DURATION_HOURS', 'PROCEDURE_DURATION_DAYS', 'PROCEDURE_DURATION_FLAG']

In [129]:
# ============================================================================
# PROCEDURE CODE ↔ DESCRIPTION CONSISTENCY CHECK
# ============================================================================

print("=" * 70)
print("PROCEDURE CODE ↔ DESCRIPTION CONSISTENCY CHECK")
print("=" * 70)

code_description_map = (
    procedures_clean
    .groupby("CODE")["DESCRIPTION"]
    .nunique()
    .sort_values(ascending=False)
)

multi_description_codes = (
    code_description_map[code_description_map > 1]
    .reset_index(name="Unique_Descriptions")
)

print("\nCODES WITH MULTIPLE DESCRIPTIONS")
print("-" * 70)

print(
    f"Codes with multiple descriptions: "
    f"{len(multi_description_codes):,}"
)

print(
    multi_description_codes
    .to_string(index=False)
)


# Show the actual mappings
if len(multi_description_codes) > 0:

    print("\nACTUAL CODE → DESCRIPTION MAPPINGS")
    print("-" * 70)

    for code in multi_description_codes["CODE"].head(20):

        descriptions = (
            procedures_clean.loc[
                procedures_clean["CODE"] == code,
                "DESCRIPTION"
            ]
            .dropna()
            .unique()
        )

        print(f"\nCODE: {code}")

        for description in descriptions:
            print(f"  - {description}")


# ============================================================================
# DESCRIPTION → CODE CHECK
# ============================================================================

description_code_map = (
    procedures_clean
    .groupby("DESCRIPTION")["CODE"]
    .nunique()
    .sort_values(ascending=False)
)

multi_code_descriptions = (
    description_code_map[description_code_map > 1]
    .reset_index(name="Unique_Codes")
)

print("\n\nDESCRIPTIONS ASSOCIATED WITH MULTIPLE CODES")
print("-" * 70)

print(
    f"Descriptions with multiple codes: "
    f"{len(multi_code_descriptions):,}"
)

print(
    multi_code_descriptions
    .head(20)
    .to_string(index=False)
)


# ============================================================================
# EXACT DUPLICATE ROW CHECK
# ============================================================================

exact_duplicate_count = procedures_clean.duplicated().sum()

print("\n\nEXACT DUPLICATE RECORD CHECK")
print("-" * 70)

print(
    f"Exact duplicate rows: "
    f"{exact_duplicate_count:,}"
)

if exact_duplicate_count == 0:
    print("STATUS: No exact duplicate procedure records found.")
else:
    print("STATUS: Exact duplicate records exist.")

======================================================================
PROCEDURE CODE ↔ DESCRIPTION CONSISTENCY CHECK
======================================================================

CODES WITH MULTIPLE DESCRIPTIONS
----------------------------------------------------------------------
Codes with multiple descriptions: 4
     CODE  Unique_Descriptions
  5880005                    4
171207006                    2
399208008                    2
 90226004                    2

ACTUAL CODE → DESCRIPTION MAPPINGS
----------------------------------------------------------------------

CODE: 5880005
  - Physical examination
  - Physical examination following birth
  - Physical examination of mother
  - Physical exam following abortion

CODE: 171207006
  - Depression screening (procedure)
  - Depression screening

CODE: 399208008
  - Plain chest X-ray (procedure)
  - Chest X-ray

CODE: 90226004
  - Cytopathology procedure  preparation of smear  genital source (procedure)
  - Cytopathology procedure  preparation of smear  genital source


DESCRIPTIONS ASSOCIATED WITH MULTIPLE CODES
----------------------------------------------------------------------
Descriptions with multiple codes: 0
Empty DataFrame
Columns: [DESCRIPTION, Unique_Codes]
Index: []


EXACT DUPLICATE RECORD CHECK
----------------------------------------------------------------------
Exact duplicate rows: 0
STATUS: No exact duplicate procedure records found.

In [130]:
# ============================================================================
# PROCEDURE COST VALUE DISTRIBUTION
# ============================================================================

print("=" * 70)
print("PROCEDURE COST VALUE DISTRIBUTION")
print("=" * 70)

cost_frequency = (
    procedures_clean["BASE_COST"]
    .value_counts(dropna=False)
    .reset_index()
)

cost_frequency.columns = ["BASE_COST", "Record_Count"]

print("\nMOST FREQUENT PROCEDURE COST VALUES")
print("-" * 70)

print(
    cost_frequency
    .head(20)
    .to_string(index=False)
)


# Specific investigation of 431
cost_431_count = (
    procedures_clean["BASE_COST"]
    .eq(431)
    .sum()
)

total_records = len(procedures_clean)

cost_431_share = (
    cost_431_count / total_records * 100
)

print("\nCOST = 431 ANALYSIS")
print("-" * 70)

print(f"Records with BASE_COST = 431: {cost_431_count:,}")
print(f"Total procedure records: {total_records:,}")
print(f"Share of procedure records: {cost_431_share:.2f}%")

======================================================================
PROCEDURE COST VALUE DISTRIBUTION
======================================================================

MOST FREQUENT PROCEDURE COST VALUES
----------------------------------------------------------------------
 BASE_COST  Record_Count
       431         30988
        31            45
        30            43
        32            34
        29            28
        28            22
         2            22
        65            19
        64            15
        27            14
        33            14
       506            14
       910            14
       551            13
        63            13
         1            13
        98            12
       532            12
      1151            12
       658            12

COST = 431 ANALYSIS
----------------------------------------------------------------------
Records with BASE_COST = 431: 30,988
Total procedure records: 47,701
Share of procedure records: 64.96%

In [131]:
procedures_clean["BASE_COST_431_FLAG"] = np.where(
    procedures_clean["BASE_COST"] == 431,
    "BASE_COST_431",
    "OTHER_COST"
)

In [132]:
# ============================================================================
# STEP 4.18C — PROCEDURE COST DATA QUALITY & ANOMALY ANALYSIS
# ----------------------------------------------------------------------------
# Purpose:
#   1. Validate procedure cost data quality
#   2. Investigate repeated BASE_COST values
#   3. Quantify the impact of BASE_COST = 431
#   4. Investigate CODE ↔ DESCRIPTION inconsistencies
#   5. Identify extreme procedure cost values
#   6. Perform sensitivity analysis excluding BASE_COST = 431
#
# Important:
#   - No records are deleted.
#   - procedures_clean remains unchanged.
#   - BASE_COST = 431 is FLAGGED, not removed.
# ============================================================================

print("=" * 70)
print("STEP 4.18C — PROCEDURE COST DATA QUALITY & ANOMALY ANALYSIS")
print("=" * 70)


# ============================================================================
# 1. REQUIRED DATA CHECK
# ============================================================================

required_columns = [
    "CODE",
    "DESCRIPTION",
    "PATIENT",
    "ENCOUNTER",
    "BASE_COST"
]

missing_columns = [
    col for col in required_columns
    if col not in procedures_clean.columns
]

if missing_columns:

    print("\nSTATUS: FAIL")
    print("Missing columns:", missing_columns)

    raise ValueError(
        "Required procedure cost-quality columns are missing."
    )

print("\nREQUIRED COLUMN CHECK")
print("-" * 70)
print("STATUS: PASS")
print("All required columns are available.")


# ============================================================================
# 2. WORKING COPY
# ----------------------------------------------------------------------------
# Do NOT modify procedures_clean.
# ============================================================================

procedure_quality = procedures_clean.copy()


# ============================================================================
# 3. BASIC DATA QUALITY METRICS
# ============================================================================

total_records = len(procedure_quality)

missing_cost = procedure_quality["BASE_COST"].isna().sum()

zero_cost = (
    procedure_quality["BASE_COST"]
    .eq(0)
    .sum()
)

negative_cost = (
    procedure_quality["BASE_COST"]
    .lt(0)
    .sum()
)

positive_cost = (
    procedure_quality["BASE_COST"]
    .gt(0)
    .sum()
)

print("\nBASIC PROCEDURE COST DATA QUALITY")
print("-" * 70)

print(f"Total procedure records: {total_records:,}")
print(f"Missing BASE_COST: {missing_cost:,}")
print(f"Zero BASE_COST: {zero_cost:,}")
print(f"Negative BASE_COST: {negative_cost:,}")
print(f"Positive BASE_COST: {positive_cost:,}")


# ============================================================================
# 4. EXACT DUPLICATE CHECK
# ============================================================================

exact_duplicates = procedure_quality.duplicated().sum()

print("\nEXACT DUPLICATE CHECK")
print("-" * 70)

print(f"Exact duplicate records: {exact_duplicates:,}")

if exact_duplicates == 0:
    print("STATUS: PASS — No exact duplicate records detected.")
else:
    print("STATUS: REVIEW — Exact duplicate records detected.")


# ============================================================================
# 5. CODE ↔ DESCRIPTION CONSISTENCY
# ============================================================================

code_description_counts = (
    procedure_quality
    .groupby("CODE")["DESCRIPTION"]
    .nunique()
)

multi_description_codes = (
    code_description_counts[
        code_description_counts > 1
    ]
    .sort_values(ascending=False)
)

description_code_counts = (
    procedure_quality
    .groupby("DESCRIPTION")["CODE"]
    .nunique()
)

multi_code_descriptions = (
    description_code_counts[
        description_code_counts > 1
    ]
    .sort_values(ascending=False)
)

print("\nCODE ↔ DESCRIPTION CONSISTENCY")
print("-" * 70)

print(
    f"Codes with multiple descriptions: "
    f"{len(multi_description_codes):,}"
)

print(
    f"Descriptions with multiple codes: "
    f"{len(multi_code_descriptions):,}"
)

if len(multi_description_codes) > 0:

    print("\nCODES WITH MULTIPLE DESCRIPTIONS")
    print("-" * 70)

    print(
        multi_description_codes
        .rename("Unique_Descriptions")
        .reset_index()
        .to_string(index=False)
    )


# ============================================================================
# 6. CREATE BASE_COST = 431 FLAG
# ----------------------------------------------------------------------------
# This is a FLAG only. No records are removed.
# ============================================================================

procedure_quality["BASE_COST_431_FLAG"] = np.where(
    procedure_quality["BASE_COST"].eq(431),
    "BASE_COST_431",
    "OTHER_COST"
)

cost_431_records = (
    procedure_quality["BASE_COST"]
    .eq(431)
    .sum()
)

cost_431_share_records = (
    cost_431_records / total_records * 100
    if total_records > 0
    else 0
)

print("\nBASE_COST = 431 ANALYSIS")
print("-" * 70)

print(
    f"Records with BASE_COST = 431: "
    f"{cost_431_records:,}"
)

print(
    f"Share of all procedure records: "
    f"{cost_431_share_records:.2f}%"
)


# ============================================================================
# 7. COST IMPACT OF BASE_COST = 431
# ============================================================================

total_cost_all = (
    procedure_quality["BASE_COST"]
    .sum()
)

cost_431_total = (
    procedure_quality.loc[
        procedure_quality["BASE_COST"] == 431,
        "BASE_COST"
    ]
    .sum()
)

cost_non_431_total = (
    procedure_quality.loc[
        procedure_quality["BASE_COST"] != 431,
        "BASE_COST"
    ]
    .sum()
)

cost_431_share = (
    cost_431_total / total_cost_all * 100
    if total_cost_all != 0
    else 0
)

print("\nBASE_COST = 431 COST IMPACT")
print("-" * 70)

print(
    f"Total procedure cost: "
    f"{total_cost_all:,.2f}"
)

print(
    f"Cost from BASE_COST = 431 records: "
    f"{cost_431_total:,.2f}"
)

print(
    f"Cost from non-431 records: "
    f"{cost_non_431_total:,.2f}"
)

print(
    f"431 cost share: "
    f"{cost_431_share:.2f}%"
)


# ============================================================================
# 8. AVERAGE / MEDIAN COST COMPARISON
# ============================================================================

all_average_cost = (
    procedure_quality["BASE_COST"]
    .mean()
)

all_median_cost = (
    procedure_quality["BASE_COST"]
    .median()
)

non_431 = procedure_quality[
    procedure_quality["BASE_COST"] != 431
].copy()

non_431_average_cost = (
    non_431["BASE_COST"]
    .mean()
)

non_431_median_cost = (
    non_431["BASE_COST"]
    .median()
)

print("\nCOST DISTRIBUTION COMPARISON")
print("-" * 70)

print(
    f"Average cost — all records: "
    f"{all_average_cost:,.2f}"
)

print(
    f"Median cost — all records: "
    f"{all_median_cost:,.2f}"
)

print(
    f"Average cost — excluding 431: "
    f"{non_431_average_cost:,.2f}"
)

print(
    f"Median cost — excluding 431: "
    f"{non_431_median_cost:,.2f}"
)


# ============================================================================
# 9. FREQUENT COST VALUES
# ============================================================================

cost_frequency = (
    procedure_quality["BASE_COST"]
    .value_counts(dropna=False)
    .reset_index()
)

cost_frequency.columns = [
    "BASE_COST",
    "Record_Count"
]

print("\nTOP 20 MOST FREQUENT BASE_COST VALUES")
print("-" * 70)

print(
    cost_frequency
    .head(20)
    .to_string(index=False)
)


# ============================================================================
# 10. HIGH-COST RECORDS
# ----------------------------------------------------------------------------
# Identify extreme individual procedure costs.
# ============================================================================

cost_95th_percentile = (
    procedure_quality["BASE_COST"]
    .quantile(0.95)
)

cost_99th_percentile = (
    procedure_quality["BASE_COST"]
    .quantile(0.99)
)

high_cost_95 = procedure_quality[
    procedure_quality["BASE_COST"] >= cost_95th_percentile
].copy()

high_cost_99 = procedure_quality[
    procedure_quality["BASE_COST"] >= cost_99th_percentile
].copy()

print("\nPROCEDURE COST OUTLIER THRESHOLDS")
print("-" * 70)

print(
    f"95th percentile cost: "
    f"{cost_95th_percentile:,.2f}"
)

print(
    f"99th percentile cost: "
    f"{cost_99th_percentile:,.2f}"
)

print(
    f"Records at/above 95th percentile: "
    f"{len(high_cost_95):,}"
)

print(
    f"Records at/above 99th percentile: "
    f"{len(high_cost_99):,}"
)


# ============================================================================
# 11. TOP 20 INDIVIDUAL PROCEDURE COST RECORDS
# ============================================================================

top_individual_costs = (
    procedure_quality
    .sort_values("BASE_COST", ascending=False)
    .head(20)
    .copy()
)

print("\nTOP 20 INDIVIDUAL PROCEDURE COST RECORDS")
print("-" * 70)

print(
    top_individual_costs[
        [
            "CODE",
            "DESCRIPTION",
            "PATIENT",
            "ENCOUNTER",
            "BASE_COST",
            "BASE_COST_431_FLAG"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 12. PROCEDURE-LEVEL IMPACT OF BASE_COST = 431
# ----------------------------------------------------------------------------
# Identify procedures where most/all records carry BASE_COST = 431.
# ============================================================================

procedure_431_analysis = (
    procedure_quality
    .groupby(
        ["CODE", "DESCRIPTION"],
        dropna=False
    )
    .agg(
        Procedure_Count=("BASE_COST", "size"),
        Total_Procedure_Cost=("BASE_COST", "sum"),
        Average_Procedure_Cost=("BASE_COST", "mean"),
        Median_Procedure_Cost=("BASE_COST", "median"),
        Cost_431_Count=(
            "BASE_COST",
            lambda x: (x == 431).sum()
        )
    )
    .reset_index()
)

procedure_431_analysis["Cost_431_Share"] = (
    procedure_431_analysis["Cost_431_Count"]
    / procedure_431_analysis["Procedure_Count"]
    * 100
)

procedure_431_analysis = (
    procedure_431_analysis
    .sort_values(
        "Cost_431_Share",
        ascending=False
    )
)

print("\nPROCEDURES MOST AFFECTED BY BASE_COST = 431")
print("-" * 70)

print(
    procedure_431_analysis[
        [
            "CODE",
            "DESCRIPTION",
            "Procedure_Count",
            "Cost_431_Count",
            "Cost_431_Share",
            "Average_Procedure_Cost"
        ]
    ]
    .head(20)
    .to_string(index=False)
)


# ============================================================================
# 13. SENSITIVITY ANALYSIS — TOTAL COST
# ----------------------------------------------------------------------------

records_all = len(procedure_quality)
records_excluding_431 = len(non_431)

total_cost_excluding_431 = (
    non_431["BASE_COST"].sum()
)

cost_reduction = (
    total_cost_all - total_cost_excluding_431
)

print("\nSENSITIVITY ANALYSIS — BASE_COST = 431")
print("-" * 70)

print("SCENARIO 1 — ALL PROCEDURE COST RECORDS")
print(
    f"Records: {records_all:,}"
)

print(
    f"Total cost: {total_cost_all:,.2f}"
)

print("\nSCENARIO 2 — EXCLUDING BASE_COST = 431")
print(
    f"Records: {records_excluding_431:,}"
)

print(
    f"Total cost: {total_cost_excluding_431:,.2f}"
)

print(
    f"Cost difference attributable to 431 records: "
    f"{cost_reduction:,.2f}"
)


# ============================================================================
# 14. COST CONCENTRATION — ALL RECORDS
# ============================================================================

procedure_cost_all = (
    procedure_quality
    .groupby(
        ["CODE", "DESCRIPTION"],
        dropna=False
    )["BASE_COST"]
    .sum()
    .sort_values(ascending=False)
)

top_10_all_cost = (
    procedure_cost_all
    .head(10)
    .sum()
)

top_20_all_cost = (
    procedure_cost_all
    .head(20)
    .sum()
)

top_10_all_share = (
    top_10_all_cost / total_cost_all * 100
    if total_cost_all > 0
    else 0
)

top_20_all_share = (
    top_20_all_cost / total_cost_all * 100
    if total_cost_all > 0
    else 0
)


# ============================================================================
# 15. COST CONCENTRATION — EXCLUDING 431
# ============================================================================

procedure_cost_non_431 = (
    non_431
    .groupby(
        ["CODE", "DESCRIPTION"],
        dropna=False
    )["BASE_COST"]
    .sum()
    .sort_values(ascending=False)
)

top_10_non_431_cost = (
    procedure_cost_non_431
    .head(10)
    .sum()
)

top_20_non_431_cost = (
    procedure_cost_non_431
    .head(20)
    .sum()
)

top_10_non_431_share = (
    top_10_non_431_cost
    / total_cost_excluding_431
    * 100
    if total_cost_excluding_431 > 0
    else 0
)

top_20_non_431_share = (
    top_20_non_431_cost
    / total_cost_excluding_431
    * 100
    if total_cost_excluding_431 > 0
    else 0
)

print("\nCOST CONCENTRATION SENSITIVITY")
print("-" * 70)

print(
    f"Top 10 cost share — all records: "
    f"{top_10_all_share:.2f}%"
)

print(
    f"Top 20 cost share — all records: "
    f"{top_20_all_share:.2f}%"
)

print(
    f"Top 10 cost share — excluding 431: "
    f"{top_10_non_431_share:.2f}%"
)

print(
    f"Top 20 cost share — excluding 431: "
    f"{top_20_non_431_share:.2f}%"
)


# ============================================================================
# 16. CREATE ANALYTICAL SUMMARY TABLE
# ============================================================================

procedure_cost_quality_metrics = pd.DataFrame({
    "Metric": [
        "Total Procedure Records",
        "Missing BASE_COST",
        "Zero BASE_COST",
        "Negative BASE_COST",
        "Exact Duplicate Records",
        "Records with BASE_COST = 431",
        "BASE_COST = 431 Record Share (%)",
        "Total Procedure Cost",
        "Cost from BASE_COST = 431",
        "BASE_COST = 431 Cost Share (%)",
        "Total Cost Excluding 431",
        "Average Procedure Cost",
        "Median Procedure Cost",
        "Average Cost Excluding 431",
        "Median Cost Excluding 431",
        "95th Percentile Cost",
        "99th Percentile Cost",
        "Codes with Multiple Descriptions",
        "Descriptions with Multiple Codes",
        "Top 10 Cost Share — All (%)",
        "Top 20 Cost Share — All (%)",
        "Top 10 Cost Share — Excluding 431 (%)",
        "Top 20 Cost Share — Excluding 431 (%)"
    ],
    "Value": [
        total_records,
        missing_cost,
        zero_cost,
        negative_cost,
        exact_duplicates,
        cost_431_records,
        cost_431_share_records,
        total_cost_all,
        cost_431_total,
        cost_431_share,
        total_cost_excluding_431,
        all_average_cost,
        all_median_cost,
        non_431_average_cost,
        non_431_median_cost,
        cost_95th_percentile,
        cost_99th_percentile,
        len(multi_description_codes),
        len(multi_code_descriptions),
        top_10_all_share,
        top_20_all_share,
        top_10_non_431_share,
        top_20_non_431_share
    ]
})


# ============================================================================
# 17. FINAL SUMMARY
# ============================================================================

print("\n" + "=" * 70)
print("STEP 4.18C COMPLETE")
print("=" * 70)

print(
    f"Total procedure records analysed: "
    f"{total_records:,}"
)

print(
    f"Exact duplicate records: "
    f"{exact_duplicates:,}"
)

print(
    f"Codes with multiple descriptions: "
    f"{len(multi_description_codes):,}"
)

print(
    f"Records with BASE_COST = 431: "
    f"{cost_431_records:,}"
)

print(
    f"BASE_COST = 431 record share: "
    f"{cost_431_share_records:.2f}%"
)

print(
    f"Total procedure cost: "
    f"{total_cost_all:,.2f}"
)

print(
    f"BASE_COST = 431 cost share: "
    f"{cost_431_share:.2f}%"
)

print(
    f"Total cost excluding 431: "
    f"{total_cost_excluding_431:,.2f}"
)

print(
    f"Top 10 cost share — all records: "
    f"{top_10_all_share:.2f}%"
)

print(
    f"Top 10 cost share — excluding 431: "
    f"{top_10_non_431_share:.2f}%"
)

print("\nSTATUS: PASS")
print("=" * 70)

======================================================================
STEP 4.18C — PROCEDURE COST DATA QUALITY & ANOMALY ANALYSIS
======================================================================

REQUIRED COLUMN CHECK
----------------------------------------------------------------------
STATUS: PASS
All required columns are available.

BASIC PROCEDURE COST DATA QUALITY
----------------------------------------------------------------------
Total procedure records: 47,701
Missing BASE_COST: 0
Zero BASE_COST: 0
Negative BASE_COST: 0
Positive BASE_COST: 47,701

EXACT DUPLICATE CHECK
----------------------------------------------------------------------
Exact duplicate records: 0
STATUS: PASS — No exact duplicate records detected.

CODE ↔ DESCRIPTION CONSISTENCY
----------------------------------------------------------------------
Codes with multiple descriptions: 4
Descriptions with multiple codes: 0

CODES WITH MULTIPLE DESCRIPTIONS
----------------------------------------------------------------------
     CODE  Unique_Descriptions
  5880005                    4
 90226004                    2
171207006                    2
399208008                    2

BASE_COST = 431 ANALYSIS
----------------------------------------------------------------------
Records with BASE_COST = 431: 30,988
Share of all procedure records: 64.96%

BASE_COST = 431 COST IMPACT
----------------------------------------------------------------------
Total procedure cost: 105,517,711.00
Cost from BASE_COST = 431 records: 13,355,828.00
Cost from non-431 records: 92,161,883.00
431 cost share: 12.66%

COST DISTRIBUTION COMPARISON
----------------------------------------------------------------------
Average cost — all records: 2,212.06
Median cost — all records: 431.00
Average cost — excluding 431: 5,514.38
Median cost — excluding 431: 2,077.00

TOP 20 MOST FREQUENT BASE_COST VALUES
----------------------------------------------------------------------
 BASE_COST  Record_Count
       431         30988
        31            45
        30            43
        32            34
        29            28
        28            22
         2            22
        65            19
        64            15
        27            14
        33            14
       506            14
       910            14
       551            13
        63            13
         1            13
        98            12
       532            12
      1151            12
       658            12

PROCEDURE COST OUTLIER THRESHOLDS
----------------------------------------------------------------------
95th percentile cost: 11,138.00
99th percentile cost: 29,195.00
Records at/above 95th percentile: 2,386
Records at/above 99th percentile: 478

TOP 20 INDIVIDUAL PROCEDURE COST RECORDS
----------------------------------------------------------------------
     CODE                     DESCRIPTION                              PATIENT                            ENCOUNTER  BASE_COST BASE_COST_431_FLAG
305351004        Admit to ICU (procedure) 01296e88-f6d9-1c18-cf91-87523325e034 6c108963-2fda-815b-3813-a424b3533127     289531         OTHER_COST
305351004        Admit to ICU (procedure) 01296e88-f6d9-1c18-cf91-87523325e034 6c108963-2fda-815b-3813-a424b3533127     236283         OTHER_COST
305351004        Admit to ICU (procedure) d9ec2e44-32e9-9148-179a-1653348cc4e2 7cd1c7e6-bd9e-b625-90f6-7ee85a69b2f8     199610         OTHER_COST
305351004        Admit to ICU (procedure) d9ec2e44-32e9-9148-179a-1653348cc4e2 7cd1c7e6-bd9e-b625-90f6-7ee85a69b2f8     193251         OTHER_COST
305351004        Admit to ICU (procedure) 01296e88-f6d9-1c18-cf91-87523325e034 6c108963-2fda-815b-3813-a424b3533127     112627         OTHER_COST
232717009 Coronary artery bypass grafting 415e1d82-d8cb-d7af-68a7-bf80c1faeee8 43cf5453-0c4e-1924-4f9b-6580f8303c19      67168         OTHER_COST
232717009 Coronary artery bypass grafting 1799f9c9-78a4-4821-364e-31e2c9a43a5b 20aecf1a-76a2-156b-3074-1a73cb051baf      65744         OTHER_COST
232717009 Coronary artery bypass grafting 31e8222a-372c-279f-0155-2b188e653fa8 c4502198-3683-ba77-368d-a3141b6d9bec      58755         OTHER_COST
232717009 Coronary artery bypass grafting 3de74169-7f67-9304-91d4-757e0f3a14d2 0788887b-0cdf-5626-16c9-f01c1267f344      56169         OTHER_COST
180325003        Electrical cardioversion eda6bc14-b236-e8c6-509a-b293e9cc688b af4b9ca6-2d33-f654-f473-ea57c7089665      44532         OTHER_COST
180325003        Electrical cardioversion eda6bc14-b236-e8c6-509a-b293e9cc688b da9d828c-33aa-8eb2-a05f-85e27bd7df2c      44314         OTHER_COST
180325003        Electrical cardioversion a733bbc1-cbdf-992f-f1b7-bd230028fc4f 15966df4-927b-2b56-cf01-40d1e1952abd      44199         OTHER_COST
180325003        Electrical cardioversion ff331e5c-ab16-e218-f39a-63e11de1ed75 5469e82b-92dd-cea8-4c75-fa7a8b9e6918      43578         OTHER_COST
232717009 Coronary artery bypass grafting da77847d-3320-1280-d147-3d1d1199430b e0f17247-e51d-6664-b082-c089fb7ad06d      43374         OTHER_COST
180325003        Electrical cardioversion 817efce8-3d2a-48a1-6d79-8505d24df078 d61171a5-fd4a-fc1c-d1bc-75ad649b8eec      43306         OTHER_COST
180325003        Electrical cardioversion ff331e5c-ab16-e218-f39a-63e11de1ed75 380fb19d-577d-cc13-9d44-781ad676aacb      43256         OTHER_COST
180325003        Electrical cardioversion ff331e5c-ab16-e218-f39a-63e11de1ed75 99ca2682-b448-e164-d868-f5030f59c2ad      43173         OTHER_COST
180325003        Electrical cardioversion 3f523789-55f3-bb31-2757-4803ca6a9c2a 0a708cd3-6162-9870-ecb2-91202671f69b      42934         OTHER_COST
180325003        Electrical cardioversion a00b9627-98b5-1f4c-b014-5793702cc75e 6496da2e-ee2b-d910-7422-067e6465305a      42868         OTHER_COST
180325003        Electrical cardioversion ff331e5c-ab16-e218-f39a-63e11de1ed75 7a94c9f0-ab3e-3b88-4e0e-895bf3dda6ba      42835         OTHER_COST

PROCEDURES MOST AFFECTED BY BASE_COST = 431
----------------------------------------------------------------------
             CODE                                                                         DESCRIPTION  Procedure_Count  Cost_431_Count  Cost_431_Share  Average_Procedure_Cost
          1225002                                                                     Upper arm X-ray               52              52           100.0                   431.0
          5880005                                                    Physical exam following abortion               32              32           100.0                   431.0
          5880005                                                                Physical examination               39              39           100.0                   431.0
          5880005                                                Physical examination following birth              119             119           100.0                   431.0
          5880005                                                      Physical examination of mother              118             118           100.0                   431.0
         10383002                                             Counseling for termination of pregnancy               32              32           100.0                   431.0
         14768001                                               Peripheral blood smear interpretation               53              53           100.0                   431.0
         26763009 Controlled ventilation procedure and therapy  initiation and management (procedure)               46              46           100.0                   431.0
         19490002                                                                         Ankle X-ray               29              29           100.0                   431.0
         61594008                                                       Microbial culture (procedure)                1               1           100.0                   431.0
         60027007                                                                      X-ray or wrist               25              25           100.0                   431.0
         58000006                                                       Patient discharge (procedure)               50              50           100.0                   431.0
        408919008                                                  Psychosocial care (regime/therapy)               33              33           100.0                   431.0
16335031000119100           High resolution computed tomography of chest without contrast (procedure)              144             144           100.0                   431.0
        449214001                                               Transfer to stepdown unit (procedure)                5               5           100.0                   431.0
        430701006                                   Resuscitation using intravenous fluid (procedure)                8               8           100.0                   431.0
        431182000                                       Placing subject in prone position (procedure)              240             240           100.0                   431.0
        423475008                                                 Heart failure education (procedure)               28              28           100.0                   431.0
        417511005                                    Referral to home health care service (procedure)               33              33           100.0                   431.0
        710841007                                                   Assessment of anxiety (procedure)             2288            2288           100.0                   431.0

SENSITIVITY ANALYSIS — BASE_COST = 431
----------------------------------------------------------------------
SCENARIO 1 — ALL PROCEDURE COST RECORDS
Records: 47,701
Total cost: 105,517,711.00

SCENARIO 2 — EXCLUDING BASE_COST = 431
Records: 16,713
Total cost: 92,161,883.00
Cost difference attributable to 431 records: 13,355,828.00

COST CONCENTRATION SENSITIVITY
----------------------------------------------------------------------
Top 10 cost share — all records: 65.57%
Top 20 cost share — all records: 78.63%
Top 10 cost share — excluding 431: 74.61%
Top 20 cost share — excluding 431: 85.51%

======================================================================
STEP 4.18C COMPLETE
======================================================================
Total procedure records analysed: 47,701
Exact duplicate records: 0
Codes with multiple descriptions: 4
Records with BASE_COST = 431: 30,988
BASE_COST = 431 record share: 64.96%
Total procedure cost: 105,517,711.00
BASE_COST = 431 cost share: 12.66%
Total cost excluding 431: 92,161,883.00
Top 10 cost share — all records: 65.57%
Top 10 cost share — excluding 431: 74.61%

STATUS: PASS
======================================================================

In [133]:
# ============================================================================
# STEP 4.18D — PROCEDURE STANDARDIZATION & ANALYTICAL FLAGS
# ----------------------------------------------------------------------------
# Purpose:
#   Prepare procedure-level data for downstream analysis without modifying
#   or deleting the original procedure records.
#
# Objectives:
#   1. Preserve the original CODE and DESCRIPTION values
#   2. Identify code-description inconsistencies
#   3. Create canonical descriptions for known inconsistent codes
#   4. Flag BASE_COST = 431 records
#   5. Flag non-431 cost records
#   6. Flag high-cost and extreme-cost records
#   7. Create analytical cost bands
#   8. Validate the resulting analytical dataset
#
# IMPORTANT:
#   - No procedure records are deleted.
#   - No exact duplicates are removed.
#   - Original DESCRIPTION is preserved.
#   - BASE_COST = 431 is flagged, NOT treated as invalid.
#   - Canonical descriptions are analytical labels only.
# ============================================================================

print("=" * 70)
print("STEP 4.18D — PROCEDURE STANDARDIZATION & ANALYTICAL FLAGS")
print("=" * 70)


# ============================================================================
# 1. SOURCE DATA VALIDATION
# ============================================================================

required_columns = [
    "CODE",
    "DESCRIPTION",
    "BASE_COST",
    "PATIENT",
    "ENCOUNTER"
]

missing_columns = [
    col for col in required_columns
    if col not in procedures_clean.columns
]

if missing_columns:
    print("\nSTATUS: FAIL")
    print("Missing columns:", missing_columns)
    raise ValueError(
        "Required columns are missing from procedures_clean."
    )

print("\nSOURCE DATA CHECK")
print("-" * 70)
print("STATUS: PASS")
print("All required source columns are available.")


# ============================================================================
# 2. CREATE ANALYTICAL COPY
# ============================================================================

procedure_analysis = procedures_clean.copy()

print("\nANALYTICAL DATASET CREATED")
print("-" * 70)
print(f"Source records: {len(procedures_clean):,}")
print(f"Analytical records: {len(procedure_analysis):,}")


# ============================================================================
# 3. PRESERVE ORIGINAL IDENTIFIERS
# ============================================================================

procedure_analysis["ORIGINAL_CODE"] = procedure_analysis["CODE"]
procedure_analysis["ORIGINAL_DESCRIPTION"] = (
    procedure_analysis["DESCRIPTION"]
)

print("\nORIGINAL VALUES PRESERVED")
print("-" * 70)
print("Original CODE preserved in ORIGINAL_CODE.")
print("Original DESCRIPTION preserved in ORIGINAL_DESCRIPTION.")


# ============================================================================
# 4. CODE ↔ DESCRIPTION VARIANCE ANALYSIS
# ============================================================================

code_description_counts = (
    procedure_analysis
    .groupby("CODE")["DESCRIPTION"]
    .nunique()
)

codes_with_multiple_descriptions = (
    code_description_counts[
        code_description_counts > 1
    ]
    .index
    .tolist()
)

procedure_analysis["CODE_DESCRIPTION_VARIANCE_FLAG"] = (
    procedure_analysis["CODE"].isin(
        codes_with_multiple_descriptions
    )
)

print("\nCODE ↔ DESCRIPTION STANDARDIZATION")
print("-" * 70)
print(
    f"Codes with multiple descriptions: "
    f"{len(codes_with_multiple_descriptions):,}"
)

print(
    f"Records affected by code-description variance: "
    f"{procedure_analysis['CODE_DESCRIPTION_VARIANCE_FLAG'].sum():,}"
)


# ============================================================================
# 5. CANONICAL DESCRIPTION MAPPING
# ----------------------------------------------------------------------------
# The original DESCRIPTION is retained.
#
# These canonical labels are analytical groupings only and do not replace
# the source descriptions.
# ============================================================================

canonical_description_map = {

    # Physical examination variants
    "5880005": "Physical examination",

    # Depression screening variants
    "171207006": "Depression screening",

    # Chest X-ray variants
    "399208008": "Plain chest X-ray",

    # Cytopathology smear variants
    "90226004": (
        "Cytopathology procedure - preparation of smear - genital source"
    )
}

procedure_analysis["CANONICAL_DESCRIPTION"] = (
    procedure_analysis["CODE"]
    .map(canonical_description_map)
    .fillna(procedure_analysis["DESCRIPTION"])
)


# ============================================================================
# 6. CANONICALIZATION FLAG
# ============================================================================

procedure_analysis["CANONICAL_DESCRIPTION_FLAG"] = (
    procedure_analysis["DESCRIPTION"]
    != procedure_analysis["CANONICAL_DESCRIPTION"]
)

print("\nCANONICAL DESCRIPTION MAPPING")
print("-" * 70)

print(
    f"Records assigned a canonical description: "
    f"{procedure_analysis['CANONICAL_DESCRIPTION_FLAG'].sum():,}"
)

print("\nCODE-LEVEL CANONICAL MAPPINGS")

for code, canonical_description in canonical_description_map.items():

    descriptions = (
        procedure_analysis.loc[
            procedure_analysis["CODE"] == code,
            "DESCRIPTION"
        ]
        .dropna()
        .unique()
        .tolist()
    )

    print(f"\nCODE: {code}")
    print(f"Canonical description: {canonical_description}")
    print("Original descriptions:")

    for description in descriptions:
        print(f"  - {description}")


# ============================================================================
# 7. BASE_COST = 431 FLAG
# ----------------------------------------------------------------------------
# IMPORTANT:
#   BASE_COST = 431 is NOT treated as invalid.
#   It is flagged because STEP 4.18C demonstrated unusually high frequency.
# ============================================================================

procedure_analysis["BASE_COST_431_FLAG"] = (
    procedure_analysis["BASE_COST"] == 431
)

procedure_analysis["NON_431_COST_FLAG"] = (
    procedure_analysis["BASE_COST"] != 431
)

print("\nBASE_COST = 431 FLAGGING")
print("-" * 70)

cost_431_count = (
    procedure_analysis["BASE_COST_431_FLAG"].sum()
)

total_records = len(procedure_analysis)

cost_431_share = (
    cost_431_count / total_records * 100
)

print(f"Records with BASE_COST = 431: {cost_431_count:,}")
print(f"Total procedure records: {total_records:,}")
print(f"431 record share: {cost_431_share:.2f}%")


# ============================================================================
# 8. COST IMPACT FLAGS
# ============================================================================

procedure_analysis["BASE_COST_431_AMOUNT"] = np.where(
    procedure_analysis["BASE_COST_431_FLAG"],
    procedure_analysis["BASE_COST"],
    0
)

procedure_analysis["NON_431_COST_AMOUNT"] = np.where(
    procedure_analysis["NON_431_COST_FLAG"],
    procedure_analysis["BASE_COST"],
    0
)


# ============================================================================
# 9. COST OUTLIER THRESHOLDS
# ----------------------------------------------------------------------------
# Use the same thresholds established in STEP 4.18C.
# ============================================================================

cost_95th = procedure_analysis["BASE_COST"].quantile(0.95)
cost_99th = procedure_analysis["BASE_COST"].quantile(0.99)

procedure_analysis["HIGH_COST_FLAG"] = (
    procedure_analysis["BASE_COST"] >= cost_95th
)

procedure_analysis["EXTREME_COST_FLAG"] = (
    procedure_analysis["BASE_COST"] >= cost_99th
)

print("\nCOST OUTLIER FLAGS")
print("-" * 70)
print(f"95th percentile threshold: {cost_95th:,.2f}")
print(f"99th percentile threshold: {cost_99th:,.2f}")

print(
    f"Records flagged HIGH_COST: "
    f"{procedure_analysis['HIGH_COST_FLAG'].sum():,}"
)

print(
    f"Records flagged EXTREME_COST: "
    f"{procedure_analysis['EXTREME_COST_FLAG'].sum():,}"
)


# ============================================================================
# 10. COST BAND CLASSIFICATION
# ============================================================================

procedure_analysis["COST_BAND"] = np.select(
    [
        procedure_analysis["BASE_COST"] >= cost_99th,
        procedure_analysis["BASE_COST"] >= cost_95th,
        procedure_analysis["BASE_COST"] > 431,
        procedure_analysis["BASE_COST"] == 431
    ],
    [
        "Extreme Cost",
        "High Cost",
        "Standard Non-431 Cost",
        "431 Cost"
    ],
    default="Other"
)


# ============================================================================
# 11. ANALYTICAL INTERPRETATION FLAG
# ----------------------------------------------------------------------------
# This prevents downstream analysis from automatically interpreting 431
# as genuinely low-cost.
# ============================================================================

procedure_analysis["COST_INTERPRETATION_FLAG"] = np.where(
    procedure_analysis["BASE_COST_431_FLAG"],
    "Review — BASE_COST = 431",
    np.where(
        procedure_analysis["EXTREME_COST_FLAG"],
        "Extreme Cost",
        np.where(
            procedure_analysis["HIGH_COST_FLAG"],
            "High Cost",
            "Standard Cost"
        )
    )
)


# ============================================================================
# 12. PROCEDURE-LEVEL QUALITY FLAGS
# ============================================================================

procedure_analysis["PROCEDURE_DATA_QUALITY_FLAG"] = np.select(
    [
        procedure_analysis["CODE_DESCRIPTION_VARIANCE_FLAG"]
        & procedure_analysis["BASE_COST_431_FLAG"],

        procedure_analysis["CODE_DESCRIPTION_VARIANCE_FLAG"],

        procedure_analysis["BASE_COST_431_FLAG"]
    ],
    [
        "Code-Description Variance + 431 Cost",
        "Code-Description Variance",
        "431 Cost — Review"
    ],
    default="No Major Flag"
)


# ============================================================================
# 13. PATIENT / ENCOUNTER VALIDATION
# ============================================================================

procedure_analysis["MISSING_PATIENT_FLAG"] = (
    procedure_analysis["PATIENT"].isna()
)

procedure_analysis["MISSING_ENCOUNTER_FLAG"] = (
    procedure_analysis["ENCOUNTER"].isna()
)

print("\nPATIENT / ENCOUNTER QUALITY")
print("-" * 70)

print(
    f"Missing PATIENT: "
    f"{procedure_analysis['MISSING_PATIENT_FLAG'].sum():,}"
)

print(
    f"Missing ENCOUNTER: "
    f"{procedure_analysis['MISSING_ENCOUNTER_FLAG'].sum():,}"
)


# ============================================================================
# 14. OVERALL ANALYTICAL QUALITY FLAG
# ============================================================================

procedure_analysis["OVERALL_QUALITY_FLAG"] = np.select(
    [
        procedure_analysis["MISSING_PATIENT_FLAG"]
        | procedure_analysis["MISSING_ENCOUNTER_FLAG"],

        procedure_analysis["CODE_DESCRIPTION_VARIANCE_FLAG"]
        & procedure_analysis["BASE_COST_431_FLAG"],

        procedure_analysis["CODE_DESCRIPTION_VARIANCE_FLAG"],

        procedure_analysis["BASE_COST_431_FLAG"]
    ],
    [
        "Missing Patient/Encounter",
        "Code-Description Variance + 431 Cost",
        "Code-Description Variance",
        "431 Cost — Review"
    ],
    default="Clean for Analysis"
)


# ============================================================================
# 15. STANDARDIZATION SUMMARY
# ============================================================================

print("\n" + "=" * 70)
print("STANDARDIZATION SUMMARY")
print("=" * 70)

summary = pd.DataFrame({
    "Metric": [
        "Total procedure records",
        "Unique procedure codes",
        "Unique original descriptions",
        "Codes with multiple descriptions",
        "Records with code-description variance",
        "Records with BASE_COST = 431",
        "431 cost record share (%)",
        "Records above 95th percentile",
        "Records above 99th percentile",
        "Missing patients",
        "Missing encounters"
    ],
    "Value": [
        len(procedure_analysis),
        procedure_analysis["CODE"].nunique(),
        procedure_analysis["DESCRIPTION"].nunique(),
        len(codes_with_multiple_descriptions),
        int(
            procedure_analysis[
                "CODE_DESCRIPTION_VARIANCE_FLAG"
            ].sum()
        ),
        int(
            procedure_analysis[
                "BASE_COST_431_FLAG"
            ].sum()
        ),
        round(cost_431_share, 2),
        int(
            procedure_analysis[
                "HIGH_COST_FLAG"
            ].sum()
        ),
        int(
            procedure_analysis[
                "EXTREME_COST_FLAG"
            ].sum()
        ),
        int(
            procedure_analysis[
                "MISSING_PATIENT_FLAG"
            ].sum()
        ),
        int(
            procedure_analysis[
                "MISSING_ENCOUNTER_FLAG"
            ].sum()
        )
    ]
})

print(summary.to_string(index=False))


# ============================================================================
# 16. COST BAND DISTRIBUTION
# ============================================================================

print("\nCOST BAND DISTRIBUTION")
print("-" * 70)

cost_band_summary = (
    procedure_analysis["COST_BAND"]
    .value_counts()
    .rename_axis("Cost_Band")
    .reset_index(name="Record_Count")
)

cost_band_summary["Record_Share_%"] = (
    cost_band_summary["Record_Count"]
    / len(procedure_analysis)
    * 100
)

print(
    cost_band_summary.to_string(index=False)
)


# ============================================================================
# 17. PROCEDURE CODE STANDARDIZATION SUMMARY
# ============================================================================

print("\nCODE → CANONICAL DESCRIPTION SUMMARY")
print("-" * 70)

standardized_codes = (
    procedure_analysis[
        procedure_analysis["CODE"].isin(
            canonical_description_map.keys()
        )
    ][
        [
            "CODE",
            "DESCRIPTION",
            "CANONICAL_DESCRIPTION"
        ]
    ]
    .drop_duplicates()
    .sort_values(["CODE", "DESCRIPTION"])
)

print(
    standardized_codes.to_string(index=False)
)


# ============================================================================
# 18. PROCEDURES WITH 100% BASE_COST = 431
# ----------------------------------------------------------------------------
# These procedures are especially important for later interpretation.
# ============================================================================

procedure_431_summary = (
    procedure_analysis
    .groupby(
        ["CODE", "CANONICAL_DESCRIPTION"],
        dropna=False
    )
    .agg(
        Procedure_Count=("BASE_COST", "size"),
        Cost_431_Count=("BASE_COST_431_FLAG", "sum"),
        Average_Cost=("BASE_COST", "mean"),
        Total_Cost=("BASE_COST", "sum")
    )
    .reset_index()
)

procedure_431_summary["Cost_431_Share_%"] = (
    procedure_431_summary["Cost_431_Count"]
    / procedure_431_summary["Procedure_Count"]
    * 100
)

procedure_431_summary = (
    procedure_431_summary
    .sort_values(
        ["Cost_431_Share_%", "Procedure_Count"],
        ascending=[False, False]
    )
)

print("\nPROCEDURES WITH 100% BASE_COST = 431")
print("-" * 70)

all_431_procedures = procedure_431_summary[
    procedure_431_summary["Cost_431_Share_%"] == 100
]

print(
    all_431_procedures.head(20).to_string(index=False)
)

print(
    f"\nProcedure groups with 100% BASE_COST = 431: "
    f"{len(all_431_procedures):,}"
)


# ============================================================================
# 19. HIGH-COST NON-431 PROCEDURES
# ----------------------------------------------------------------------------
# This is useful because it isolates genuinely high observed costs from the
# large 431-cost mass.
# ============================================================================

high_cost_non_431 = (
    procedure_analysis[
        procedure_analysis["NON_431_COST_FLAG"]
        & procedure_analysis["HIGH_COST_FLAG"]
    ]
    .sort_values("BASE_COST", ascending=False)
    .head(20)
    .copy()
)

print("\nTOP 20 HIGH-COST NON-431 PROCEDURE RECORDS")
print("-" * 70)

print(
    high_cost_non_431[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "PATIENT",
            "ENCOUNTER",
            "BASE_COST",
            "COST_BAND",
            "COST_INTERPRETATION_FLAG"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 20. CREATE PROCEDURE-LEVEL ANALYTICAL SUMMARY
# ----------------------------------------------------------------------------
# This summary is based on canonical descriptions but retains the original
# procedure-code structure.
# ============================================================================

procedure_analytical_summary = (
    procedure_analysis
    .groupby(
        ["CODE", "CANONICAL_DESCRIPTION"],
        dropna=False
    )
    .agg(
        Procedure_Count=("BASE_COST", "size"),
        Total_Procedure_Cost=("BASE_COST", "sum"),
        Average_Procedure_Cost=("BASE_COST", "mean"),
        Median_Procedure_Cost=("BASE_COST", "median"),
        Unique_Patients=("PATIENT", "nunique"),
        Unique_Encounters=("ENCOUNTER", "nunique"),
        Cost_431_Count=("BASE_COST_431_FLAG", "sum")
    )
    .reset_index()
)

procedure_analytical_summary["Cost_Per_Patient"] = np.where(
    procedure_analytical_summary["Unique_Patients"] > 0,
    procedure_analytical_summary["Total_Procedure_Cost"]
    / procedure_analytical_summary["Unique_Patients"],
    np.nan
)

procedure_analytical_summary["Procedures_Per_Patient"] = np.where(
    procedure_analytical_summary["Unique_Patients"] > 0,
    procedure_analytical_summary["Procedure_Count"]
    / procedure_analytical_summary["Unique_Patients"],
    np.nan
)

procedure_analytical_summary["Procedures_Per_Encounter"] = np.where(
    procedure_analytical_summary["Unique_Encounters"] > 0,
    procedure_analytical_summary["Procedure_Count"]
    / procedure_analytical_summary["Unique_Encounters"],
    np.nan
)

procedure_analytical_summary["Cost_431_Share_%"] = np.where(
    procedure_analytical_summary["Procedure_Count"] > 0,
    procedure_analytical_summary["Cost_431_Count"]
    / procedure_analytical_summary["Procedure_Count"]
    * 100,
    np.nan
)


# ============================================================================
# 21. FINAL VALIDATION
# ============================================================================

print("\n" + "=" * 70)
print("FINAL VALIDATION")
print("=" * 70)

validation_checks = {
    "Record count preserved":
        len(procedure_analysis) == len(procedures_clean),

    "Original CODE preserved":
        "ORIGINAL_CODE" in procedure_analysis.columns,

    "Original DESCRIPTION preserved":
        "ORIGINAL_DESCRIPTION" in procedure_analysis.columns,

    "Canonical description created":
        "CANONICAL_DESCRIPTION" in procedure_analysis.columns,

    "431 flag created":
        "BASE_COST_431_FLAG" in procedure_analysis.columns,

    "High-cost flag created":
        "HIGH_COST_FLAG" in procedure_analysis.columns,

    "Extreme-cost flag created":
        "EXTREME_COST_FLAG" in procedure_analysis.columns,

    "Cost band created":
        "COST_BAND" in procedure_analysis.columns,

    "No records deleted":
        len(procedure_analysis) == 47701
}

validation_results = pd.DataFrame(
    list(validation_checks.items()),
    columns=["Validation", "Result"]
)

print(validation_results.to_string(index=False))

if not all(validation_checks.values()):
    raise ValueError(
        "STEP 4.18D validation failed. "
        "Review the validation results above."
    )


# ============================================================================
# 22. FINAL OUTPUTS
# ============================================================================

print("\n" + "=" * 70)
print("STEP 4.18D COMPLETE")
print("=" * 70)

print(
    f"Total procedure records: "
    f"{len(procedure_analysis):,}"
)

print(
    f"Unique procedure codes: "
    f"{procedure_analysis['CODE'].nunique():,}"
)

print(
    f"Codes with description variance: "
    f"{len(codes_with_multiple_descriptions):,}"
)

print(
    f"Records with BASE_COST = 431: "
    f"{procedure_analysis['BASE_COST_431_FLAG'].sum():,}"
)

print(
    f"High-cost records: "
    f"{procedure_analysis['HIGH_COST_FLAG'].sum():,}"
)

print(
    f"Extreme-cost records: "
    f"{procedure_analysis['EXTREME_COST_FLAG'].sum():,}"
)

print("\nAnalytical datasets created:")
print("  - procedure_analysis")
print("  - procedure_analytical_summary")
print("  - procedure_431_summary")
print("  - high_cost_non_431")
print("  - cost_band_summary")

print("\nSTATUS: PASS")
print("=" * 70)

======================================================================
STEP 4.18D — PROCEDURE STANDARDIZATION & ANALYTICAL FLAGS
======================================================================

SOURCE DATA CHECK
----------------------------------------------------------------------
STATUS: PASS
All required source columns are available.

ANALYTICAL DATASET CREATED
----------------------------------------------------------------------
Source records: 47,701
Analytical records: 47,701

ORIGINAL VALUES PRESERVED
----------------------------------------------------------------------
Original CODE preserved in ORIGINAL_CODE.
Original DESCRIPTION preserved in ORIGINAL_DESCRIPTION.

CODE ↔ DESCRIPTION STANDARDIZATION
----------------------------------------------------------------------
Codes with multiple descriptions: 4
Records affected by code-description variance: 4,460

CANONICAL DESCRIPTION MAPPING
----------------------------------------------------------------------
Records assigned a canonical description: 0

CODE-LEVEL CANONICAL MAPPINGS

CODE: 5880005
Canonical description: Physical examination
Original descriptions:

CODE: 171207006
Canonical description: Depression screening
Original descriptions:

CODE: 399208008
Canonical description: Plain chest X-ray
Original descriptions:

CODE: 90226004
Canonical description: Cytopathology procedure - preparation of smear - genital source
Original descriptions:

BASE_COST = 431 FLAGGING
----------------------------------------------------------------------
Records with BASE_COST = 431: 30,988
Total procedure records: 47,701
431 record share: 64.96%

COST OUTLIER FLAGS
----------------------------------------------------------------------
95th percentile threshold: 11,138.00
99th percentile threshold: 29,195.00
Records flagged HIGH_COST: 2,386
Records flagged EXTREME_COST: 478

PATIENT / ENCOUNTER QUALITY
----------------------------------------------------------------------
Missing PATIENT: 0
Missing ENCOUNTER: 0

======================================================================
STANDARDIZATION SUMMARY
======================================================================
                                Metric    Value
               Total procedure records 47701.00
                Unique procedure codes   157.00
          Unique original descriptions   163.00
      Codes with multiple descriptions     4.00
Records with code-description variance  4460.00
          Records with BASE_COST = 431 30988.00
             431 cost record share (%)    64.96
         Records above 95th percentile  2386.00
         Records above 99th percentile   478.00
                      Missing patients     0.00
                    Missing encounters     0.00

COST BAND DISTRIBUTION
----------------------------------------------------------------------
            Cost_Band  Record_Count  Record_Share_%
             431 Cost         30988       64.962999
Standard Non-431 Cost         12730       26.687072
            High Cost          1908        3.999916
                Other          1597        3.347938
         Extreme Cost           478        1.002075

CODE → CANONICAL DESCRIPTION SUMMARY
----------------------------------------------------------------------
Empty DataFrame
Columns: [CODE, DESCRIPTION, CANONICAL_DESCRIPTION]
Index: []

PROCEDURES WITH 100% BASE_COST = 431
----------------------------------------------------------------------
             CODE                                                                CANONICAL_DESCRIPTION  Procedure_Count  Cost_431_Count  Average_Cost  Total_Cost  Cost_431_Share_%
        710824005                               Assessment of health and social care needs (procedure)             4596            4596         431.0     1980876             100.0
        385763009                                                        Hospice care (regime/therapy)             4098            4098         431.0     1766238             100.0
        171207006                                                     Depression screening (procedure)             3614            3614         431.0     1557634             100.0
  454711000124102   Depression screening using Patient Health Questionnaire Two-Item score (procedure)             3614            3614         431.0     1557634             100.0
  428211000124100                                              Assessment of substance use (procedure)             2906            2906         431.0     1252486             100.0
        762993000                                        Assessment using Morse Fall Scale (procedure)             2422            2422         431.0     1043882             100.0
        710841007                                                    Assessment of anxiety (procedure)             2288            2288         431.0      986128             100.0
        713106006                                                 Screening for drug abuse (procedure)             1484            1484         431.0      639604             100.0
        866148006                                             Screening for domestic abuse (procedure)             1432            1432         431.0      617192             100.0
        763302001 Assessment using Alcohol Use Disorders Identification Test - Consumption (procedure)             1422            1422         431.0      612882             100.0
        229064008                                                    Movement therapy (regime/therapy)              890             890         431.0      383590             100.0
        371908008                                            Oxygen administration by mask (procedure)              240             240         431.0      103440             100.0
        431182000                                        Placing subject in prone position (procedure)              240             240         431.0      103440             100.0
        171207006                                                                 Depression screening              190             190         431.0       81890             100.0
        398171003                                                      Hearing examination (procedure)              144             144         431.0       62064             100.0
16335031000119100            High resolution computed tomography of chest without contrast (procedure)              144             144         431.0       62064             100.0
          5880005                                                 Physical examination following birth              119             119         431.0       51289             100.0
          5880005                                                       Physical examination of mother              118             118         431.0       50858             100.0
        274474001                                                                  Bone immobilization              118             118         431.0       50858             100.0
        271442007                                                                  Fetal anatomy study              116             116         431.0       49996             100.0

Procedure groups with 100% BASE_COST = 431: 50

TOP 20 HIGH-COST NON-431 PROCEDURE RECORDS
----------------------------------------------------------------------
     CODE           CANONICAL_DESCRIPTION                              PATIENT                            ENCOUNTER  BASE_COST    COST_BAND COST_INTERPRETATION_FLAG
305351004        Admit to ICU (procedure) 01296e88-f6d9-1c18-cf91-87523325e034 6c108963-2fda-815b-3813-a424b3533127     289531 Extreme Cost             Extreme Cost
305351004        Admit to ICU (procedure) 01296e88-f6d9-1c18-cf91-87523325e034 6c108963-2fda-815b-3813-a424b3533127     236283 Extreme Cost             Extreme Cost
305351004        Admit to ICU (procedure) d9ec2e44-32e9-9148-179a-1653348cc4e2 7cd1c7e6-bd9e-b625-90f6-7ee85a69b2f8     199610 Extreme Cost             Extreme Cost
305351004        Admit to ICU (procedure) d9ec2e44-32e9-9148-179a-1653348cc4e2 7cd1c7e6-bd9e-b625-90f6-7ee85a69b2f8     193251 Extreme Cost             Extreme Cost
305351004        Admit to ICU (procedure) 01296e88-f6d9-1c18-cf91-87523325e034 6c108963-2fda-815b-3813-a424b3533127     112627 Extreme Cost             Extreme Cost
232717009 Coronary artery bypass grafting 415e1d82-d8cb-d7af-68a7-bf80c1faeee8 43cf5453-0c4e-1924-4f9b-6580f8303c19      67168 Extreme Cost             Extreme Cost
232717009 Coronary artery bypass grafting 1799f9c9-78a4-4821-364e-31e2c9a43a5b 20aecf1a-76a2-156b-3074-1a73cb051baf      65744 Extreme Cost             Extreme Cost
232717009 Coronary artery bypass grafting 31e8222a-372c-279f-0155-2b188e653fa8 c4502198-3683-ba77-368d-a3141b6d9bec      58755 Extreme Cost             Extreme Cost
232717009 Coronary artery bypass grafting 3de74169-7f67-9304-91d4-757e0f3a14d2 0788887b-0cdf-5626-16c9-f01c1267f344      56169 Extreme Cost             Extreme Cost
180325003        Electrical cardioversion eda6bc14-b236-e8c6-509a-b293e9cc688b af4b9ca6-2d33-f654-f473-ea57c7089665      44532 Extreme Cost             Extreme Cost
180325003        Electrical cardioversion eda6bc14-b236-e8c6-509a-b293e9cc688b da9d828c-33aa-8eb2-a05f-85e27bd7df2c      44314 Extreme Cost             Extreme Cost
180325003        Electrical cardioversion a733bbc1-cbdf-992f-f1b7-bd230028fc4f 15966df4-927b-2b56-cf01-40d1e1952abd      44199 Extreme Cost             Extreme Cost
180325003        Electrical cardioversion ff331e5c-ab16-e218-f39a-63e11de1ed75 5469e82b-92dd-cea8-4c75-fa7a8b9e6918      43578 Extreme Cost             Extreme Cost
232717009 Coronary artery bypass grafting da77847d-3320-1280-d147-3d1d1199430b e0f17247-e51d-6664-b082-c089fb7ad06d      43374 Extreme Cost             Extreme Cost
180325003        Electrical cardioversion 817efce8-3d2a-48a1-6d79-8505d24df078 d61171a5-fd4a-fc1c-d1bc-75ad649b8eec      43306 Extreme Cost             Extreme Cost
180325003        Electrical cardioversion ff331e5c-ab16-e218-f39a-63e11de1ed75 380fb19d-577d-cc13-9d44-781ad676aacb      43256 Extreme Cost             Extreme Cost
180325003        Electrical cardioversion ff331e5c-ab16-e218-f39a-63e11de1ed75 99ca2682-b448-e164-d868-f5030f59c2ad      43173 Extreme Cost             Extreme Cost
180325003        Electrical cardioversion 3f523789-55f3-bb31-2757-4803ca6a9c2a 0a708cd3-6162-9870-ecb2-91202671f69b      42934 Extreme Cost             Extreme Cost
180325003        Electrical cardioversion a00b9627-98b5-1f4c-b014-5793702cc75e 6496da2e-ee2b-d910-7422-067e6465305a      42868 Extreme Cost             Extreme Cost
180325003        Electrical cardioversion ff331e5c-ab16-e218-f39a-63e11de1ed75 7a94c9f0-ab3e-3b88-4e0e-895bf3dda6ba      42835 Extreme Cost             Extreme Cost

======================================================================
FINAL VALIDATION
======================================================================
                    Validation  Result
        Record count preserved    True
       Original CODE preserved    True
Original DESCRIPTION preserved    True
 Canonical description created    True
              431 flag created    True
        High-cost flag created    True
     Extreme-cost flag created    True
             Cost band created    True
            No records deleted    True

======================================================================
STEP 4.18D COMPLETE
======================================================================
Total procedure records: 47,701
Unique procedure codes: 157
Codes with description variance: 4
Records with BASE_COST = 431: 30,988
High-cost records: 2,386
Extreme-cost records: 478

Analytical datasets created:
  - procedure_analysis
  - procedure_analytical_summary
  - procedure_431_summary
  - high_cost_non_431
  - cost_band_summary

STATUS: PASS
======================================================================

In [134]:
# ============================================================================
# STEP 4.18E — PROCEDURE COST & UTILIZATION INSIGHT ANALYSIS
# ----------------------------------------------------------------------------
# Purpose:
#   Convert the standardized procedure dataset from STEP 4.18D into
#   decision-ready procedure cost/utilization insights.
#
# Analytical principles:
#   1. Preserve all procedure records.
#   2. Preserve ORIGINAL_CODE and ORIGINAL_DESCRIPTION.
#   3. Use CODE as the primary procedure identifier.
#   4. Treat BASE_COST = 431 as an analytical flag, NOT as a deleted record.
#   5. Separate observed cost from 431-flagged/default-cost exposure.
#   6. Prioritize high-cost, high-utilization and high-cost-per-patient
#      procedures.
#   7. Avoid interpreting BASE_COST = 431 as automatically "low cost".
# ============================================================================

print("=" * 70)
print("STEP 4.18E — PROCEDURE COST & UTILIZATION INSIGHT ANALYSIS")
print("=" * 70)


# ============================================================================
# 1. SOURCE DATA CHECK
# ============================================================================

required_source_columns = [
    "CODE",
    "DESCRIPTION",
    "PATIENT",
    "ENCOUNTER",
    "BASE_COST"
]

# procedure_analysis was created in STEP 4.18D
if "procedure_analysis" not in globals():
    raise ValueError(
        "procedure_analysis is not available. "
        "Please run STEP 4.18D before STEP 4.18E."
    )

missing_source_columns = [
    col for col in required_source_columns
    if col not in procedure_analysis.columns
]

if missing_source_columns:
    print("\nSTATUS: FAIL")
    print("Missing columns:", missing_source_columns)
    raise ValueError(
        "Required columns are missing from procedure_analysis."
    )

print("\nSOURCE DATA CHECK")
print("-" * 70)
print("STATUS: PASS")
print("procedure_analysis is available.")
print(f"Procedure records available: {len(procedure_analysis):,}")


# ============================================================================
# 2. PREPARE ANALYTICAL DATASET
# ============================================================================

procedure_e = procedure_analysis.copy()

# ---------------------------------------------------------------------------
# Ensure cost flag exists
# ---------------------------------------------------------------------------

if "BASE_COST_431_FLAG" not in procedure_e.columns:
    procedure_e["BASE_COST_431_FLAG"] = np.where(
        procedure_e["BASE_COST"].eq(431),
        "BASE_COST_431",
        "OTHER_COST"
    )

# ---------------------------------------------------------------------------
# Ensure canonical description exists
# ---------------------------------------------------------------------------

if "CANONICAL_DESCRIPTION" not in procedure_e.columns:

    procedure_e["CANONICAL_DESCRIPTION"] = (
        procedure_e["DESCRIPTION"]
        .astype(str)
        .str.strip()
    )

# Fill any missing canonical descriptions
procedure_e["CANONICAL_DESCRIPTION"] = (
    procedure_e["CANONICAL_DESCRIPTION"]
    .replace(["", "nan", "None"], np.nan)
    .fillna(procedure_e["DESCRIPTION"])
)

# ---------------------------------------------------------------------------
# Create non-431 cost
# ---------------------------------------------------------------------------

procedure_e["NON_431_COST"] = np.where(
    procedure_e["BASE_COST"].ne(431),
    procedure_e["BASE_COST"],
    0
)

# ---------------------------------------------------------------------------
# Cost classification
# ---------------------------------------------------------------------------

if "COST_BAND" not in procedure_e.columns:

    p95 = procedure_e["BASE_COST"].quantile(0.95)
    p99 = procedure_e["BASE_COST"].quantile(0.99)

    procedure_e["COST_BAND"] = np.select(
        [
            procedure_e["BASE_COST"].eq(431),
            procedure_e["BASE_COST"] >= p99,
            procedure_e["BASE_COST"] >= p95
        ],
        [
            "431 Cost",
            "Extreme Cost",
            "High Cost"
        ],
        default="Standard Non-431 Cost"
    )

# ============================================================================
# 3. BASIC ANALYTICAL VALIDATION
# ============================================================================

print("\nANALYTICAL DATASET VALIDATION")
print("-" * 70)

print(f"Records preserved: {len(procedure_e):,}")
print(f"Unique procedure codes: {procedure_e['CODE'].nunique():,}")
print(
    f"Unique original descriptions: "
    f"{procedure_e['DESCRIPTION'].nunique():,}"
)
print(
    f"Unique canonical descriptions: "
    f"{procedure_e['CANONICAL_DESCRIPTION'].nunique():,}"
)

print(
    f"BASE_COST = 431 records: "
    f"{procedure_e['BASE_COST'].eq(431).sum():,}"
)

print(
    f"Non-431 records: "
    f"{procedure_e['BASE_COST'].ne(431).sum():,}"
)


# ============================================================================
# 4. BUILD PROCEDURE-LEVEL INSIGHT SUMMARY
# ============================================================================

procedure_insight_summary = (
    procedure_e
    .groupby(
        ["CODE", "CANONICAL_DESCRIPTION"],
        dropna=False
    )
    .agg(
        Procedure_Count=("CODE", "size"),
        Total_Procedure_Cost=("BASE_COST", "sum"),
        Average_Procedure_Cost=("BASE_COST", "mean"),
        Median_Procedure_Cost=("BASE_COST", "median"),
        Unique_Patients=("PATIENT", "nunique"),
        Unique_Encounters=("ENCOUNTER", "nunique"),
        Cost_431_Count=("BASE_COST", lambda x: (x == 431).sum()),
        Non_431_Count=("BASE_COST", lambda x: (x != 431).sum()),
        Non_431_Total_Cost=("NON_431_COST", "sum")
    )
    .reset_index()
)

# ---------------------------------------------------------------------------
# Derived metrics
# ---------------------------------------------------------------------------

procedure_insight_summary["Cost_Per_Patient"] = (
    procedure_insight_summary["Total_Procedure_Cost"]
    / procedure_insight_summary["Unique_Patients"].replace(0, np.nan)
)

procedure_insight_summary["Procedures_Per_Patient"] = (
    procedure_insight_summary["Procedure_Count"]
    / procedure_insight_summary["Unique_Patients"].replace(0, np.nan)
)

procedure_insight_summary["Procedures_Per_Encounter"] = (
    procedure_insight_summary["Procedure_Count"]
    / procedure_insight_summary["Unique_Encounters"].replace(0, np.nan)
)

procedure_insight_summary["Cost_431_Share"] = (
    procedure_insight_summary["Cost_431_Count"]
    / procedure_insight_summary["Procedure_Count"].replace(0, np.nan)
    * 100
)

procedure_insight_summary["Non_431_Cost_Share"] = np.where(
    procedure_insight_summary["Total_Procedure_Cost"] > 0,
    procedure_insight_summary["Non_431_Total_Cost"]
    / procedure_insight_summary["Total_Procedure_Cost"]
    * 100,
    0
)

procedure_insight_summary["Procedure_Utilization_Profile"] = np.where(
    procedure_insight_summary["Procedure_Count"]
    >= procedure_insight_summary["Procedure_Count"].median(),
    "High Utilization",
    "Low Utilization"
)

procedure_insight_summary["Cost_Profile"] = np.where(
    procedure_insight_summary["Non_431_Total_Cost"]
    >= procedure_insight_summary["Non_431_Total_Cost"].median(),
    "High Non-431 Cost",
    "Low Non-431 Cost"
)

procedure_insight_summary["Cost_Data_Profile"] = np.select(
    [
        procedure_insight_summary["Cost_431_Share"].eq(100),
        procedure_insight_summary["Cost_431_Share"].gt(50),
        procedure_insight_summary["Cost_431_Share"].gt(0)
    ],
    [
        "100% 431 Cost",
        "Majority 431 Cost",
        "Mixed 431 / Non-431 Cost"
    ],
    default="Non-431 Cost"
)


# ============================================================================
# 5. HIGH-COST PROCEDURES — NON-431 FOCUS
# ============================================================================

high_cost_non431_procedures = (
    procedure_insight_summary[
        procedure_insight_summary["Non_431_Count"] > 0
    ]
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
    .head(20)
    .copy()
)

print("\nTOP 20 PROCEDURES BY NON-431 TOTAL COST")
print("-" * 70)

print(
    high_cost_non431_procedures[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Non_431_Count",
            "Non_431_Total_Cost",
            "Average_Procedure_Cost",
            "Unique_Patients",
            "Cost_Per_Patient",
            "Cost_431_Share"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 6. HIGH UTILIZATION PROCEDURES
# ============================================================================

high_utilization_procedure_insights = (
    procedure_insight_summary
    .sort_values(
        ["Procedure_Count", "Unique_Patients"],
        ascending=[False, False]
    )
    .head(20)
    .copy()
)

print("\nTOP 20 PROCEDURES BY UTILIZATION")
print("-" * 70)

print(
    high_utilization_procedure_insights[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Unique_Encounters",
            "Procedures_Per_Patient",
            "Procedures_Per_Encounter",
            "Total_Procedure_Cost",
            "Cost_431_Share"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 7. HIGH COST PER PATIENT
# ============================================================================

high_cost_per_patient_insights = (
    procedure_insight_summary[
        (procedure_insight_summary["Unique_Patients"] > 0) &
        (procedure_insight_summary["Non_431_Count"] > 0)
    ]
    .sort_values(
        "Cost_Per_Patient",
        ascending=False
    )
    .head(20)
    .copy()
)

print("\nTOP 20 PROCEDURES BY COST PER PATIENT")
print("-" * 70)

print(
    high_cost_per_patient_insights[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Total_Procedure_Cost",
            "Cost_Per_Patient",
            "Procedures_Per_Patient",
            "Cost_431_Share"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 8. HIGH REPEAT-UTILIZATION PROCEDURES
# ============================================================================

high_repeat_utilization = (
    procedure_insight_summary[
        procedure_insight_summary["Unique_Patients"] > 0
    ]
    .sort_values(
        "Procedures_Per_Patient",
        ascending=False
    )
    .head(20)
    .copy()
)

print("\nTOP 20 PROCEDURES BY PROCEDURES PER PATIENT")
print("-" * 70)

print(
    high_repeat_utilization[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Unique_Encounters",
            "Procedures_Per_Patient",
            "Procedures_Per_Encounter",
            "Total_Procedure_Cost",
            "Cost_431_Share"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 9. HIGH-COST + HIGH-UTILIZATION
# ============================================================================

cost_threshold = procedure_insight_summary[
    "Non_431_Total_Cost"
].median()

volume_threshold = procedure_insight_summary[
    "Procedure_Count"
].median()

high_cost_high_utilization = (
    procedure_insight_summary[
        (procedure_insight_summary["Non_431_Total_Cost"] >= cost_threshold) &
        (procedure_insight_summary["Procedure_Count"] >= volume_threshold) &
        (procedure_insight_summary["Non_431_Count"] > 0)
    ]
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
    .copy()
)

print("\nHIGH NON-431 COST + HIGH UTILIZATION PROCEDURES")
print("-" * 70)

print(
    high_cost_high_utilization[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Non_431_Count",
            "Non_431_Total_Cost",
            "Unique_Patients",
            "Cost_Per_Patient",
            "Procedures_Per_Patient",
            "Cost_431_Share"
        ]
    ].head(20).to_string(index=False)
)


# ============================================================================
# 10. HIGH COST + LOW UTILIZATION
# ============================================================================

high_cost_low_utilization = (
    procedure_insight_summary[
        (procedure_insight_summary["Non_431_Total_Cost"] >= cost_threshold) &
        (procedure_insight_summary["Procedure_Count"] < volume_threshold) &
        (procedure_insight_summary["Non_431_Count"] > 0)
    ]
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
    .copy()
)

print("\nHIGH NON-431 COST + LOW UTILIZATION PROCEDURES")
print("-" * 70)

print(
    high_cost_low_utilization[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Non_431_Count",
            "Non_431_Total_Cost",
            "Average_Procedure_Cost",
            "Cost_Per_Patient",
            "Cost_431_Share"
        ]
    ].head(20).to_string(index=False)
)


# ============================================================================
# 11. HIGH UTILIZATION + LOW COST
# ============================================================================

low_cost_high_utilization = (
    procedure_insight_summary[
        (procedure_insight_summary["Non_431_Total_Cost"] < cost_threshold) &
        (procedure_insight_summary["Procedure_Count"] >= volume_threshold)
    ]
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .copy()
)

print("\nLOW NON-431 COST + HIGH UTILIZATION PROCEDURES")
print("-" * 70)

print(
    low_cost_high_utilization[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Procedures_Per_Patient",
            "Total_Procedure_Cost",
            "Non_431_Total_Cost",
            "Cost_431_Share"
        ]
    ].head(20).to_string(index=False)
)


# ============================================================================
# 12. 100% BASE_COST = 431 PROCEDURES
# ============================================================================

procedures_100pct_431 = (
    procedure_insight_summary[
        procedure_insight_summary["Cost_431_Share"].eq(100)
    ]
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .copy()
)

print("\nPROCEDURES WITH 100% BASE_COST = 431")
print("-" * 70)

print(
    procedures_100pct_431[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Total_Procedure_Cost",
            "Cost_431_Share"
        ]
    ].head(20).to_string(index=False)
)

print(
    f"\nProcedure groups with 100% BASE_COST = 431: "
    f"{len(procedures_100pct_431):,}"
)


# ============================================================================
# 13. COST / UTILIZATION PRIORITY MATRIX
# ============================================================================

procedure_priority = procedure_insight_summary.copy()

procedure_priority["Priority_Profile"] = np.select(
    [
        (
            (procedure_priority["Non_431_Total_Cost"] >= cost_threshold) &
            (procedure_priority["Procedure_Count"] >= volume_threshold) &
            (procedure_priority["Non_431_Count"] > 0)
        ),

        (
            (procedure_priority["Non_431_Total_Cost"] >= cost_threshold) &
            (procedure_priority["Procedure_Count"] < volume_threshold) &
            (procedure_priority["Non_431_Count"] > 0)
        ),

        (
            (procedure_priority["Non_431_Total_Cost"] < cost_threshold) &
            (procedure_priority["Procedure_Count"] >= volume_threshold)
        ),

        (
            procedure_priority["Cost_431_Share"].eq(100)
        )
    ],
    [
        "PRIORITY 1 — High Cost / High Utilization",
        "PRIORITY 2 — High Cost / Low Utilization",
        "PRIORITY 3 — High Utilization / Lower Non-431 Cost",
        "PRIORITY 4 — 431 Cost Dominated"
    ],
    default="STANDARD"
)

priority_counts = (
    procedure_priority["Priority_Profile"]
    .value_counts()
    .rename_axis("Priority_Profile")
    .reset_index(name="Procedure_Group_Count")
)

print("\nPROCEDURE PRIORITY MATRIX")
print("-" * 70)

print(
    priority_counts.to_string(index=False)
)


# ============================================================================
# 14. COST CONCENTRATION
# ============================================================================

total_observed_cost = procedure_insight_summary[
    "Total_Procedure_Cost"
].sum()

total_non431_cost = procedure_insight_summary[
    "Non_431_Total_Cost"
].sum()

top10_total_cost = (
    procedure_insight_summary
    .nlargest(10, "Total_Procedure_Cost")
    ["Total_Procedure_Cost"]
    .sum()
)

top20_total_cost = (
    procedure_insight_summary
    .nlargest(20, "Total_Procedure_Cost")
    ["Total_Procedure_Cost"]
    .sum()
)

top10_non431_cost = (
    procedure_insight_summary
    .nlargest(10, "Non_431_Total_Cost")
    ["Non_431_Total_Cost"]
    .sum()
)

top20_non431_cost = (
    procedure_insight_summary
    .nlargest(20, "Non_431_Total_Cost")
    ["Non_431_Total_Cost"]
    .sum()
)

print("\nPROCEDURE COST CONCENTRATION")
print("-" * 70)

print(
    f"Total observed procedure cost: "
    f"{total_observed_cost:,.2f}"
)

print(
    f"Total non-431 procedure cost: "
    f"{total_non431_cost:,.2f}"
)

print(
    f"Top 10 total-cost share: "
    f"{(top10_total_cost / total_observed_cost) * 100:.2f}%"
)

print(
    f"Top 20 total-cost share: "
    f"{(top20_total_cost / total_observed_cost) * 100:.2f}%"
)

print(
    f"Top 10 non-431 cost share: "
    f"{(top10_non431_cost / total_non431_cost) * 100:.2f}%"
)

print(
    f"Top 20 non-431 cost share: "
    f"{(top20_non431_cost / total_non431_cost) * 100:.2f}%"
)


# ============================================================================
# 15. UTILIZATION CONCENTRATION
# ============================================================================

total_procedures = procedure_insight_summary[
    "Procedure_Count"
].sum()

top10_volume = (
    procedure_insight_summary
    .nlargest(10, "Procedure_Count")
    ["Procedure_Count"]
    .sum()
)

top20_volume = (
    procedure_insight_summary
    .nlargest(20, "Procedure_Count")
    ["Procedure_Count"]
    .sum()
)

print("\nPROCEDURE UTILIZATION CONCENTRATION")
print("-" * 70)

print(
    f"Total procedure records: "
    f"{total_procedures:,.0f}"
)

print(
    f"Top 10 procedure volume share: "
    f"{(top10_volume / total_procedures) * 100:.2f}%"
)

print(
    f"Top 20 procedure volume share: "
    f"{(top20_volume / total_procedures) * 100:.2f}%"
)


# ============================================================================
# 16. BASE_COST = 431 IMPACT SUMMARY
# ============================================================================

records_431 = procedure_e["BASE_COST"].eq(431).sum()
records_non431 = procedure_e["BASE_COST"].ne(431).sum()

cost_431 = procedure_e.loc[
    procedure_e["BASE_COST"].eq(431),
    "BASE_COST"
].sum()

cost_non431 = procedure_e.loc[
    procedure_e["BASE_COST"].ne(431),
    "BASE_COST"
].sum()

print("\nBASE_COST = 431 ANALYTICAL IMPACT")
print("-" * 70)

print(
    f"431 records: {records_431:,}"
)

print(
    f"Non-431 records: {records_non431:,}"
)

print(
    f"431 record share: "
    f"{(records_431 / len(procedure_e)) * 100:.2f}%"
)

print(
    f"431 cost share: "
    f"{(cost_431 / total_observed_cost) * 100:.2f}%"
)

print(
    f"Non-431 cost share: "
    f"{(cost_non431 / total_observed_cost) * 100:.2f}%"
)


# ============================================================================
# 17. ANALYTICAL FLAGS
# ============================================================================

procedure_priority["High_Cost_Flag"] = (
    procedure_priority["Non_431_Total_Cost"] >= cost_threshold
)

procedure_priority["High_Utilization_Flag"] = (
    procedure_priority["Procedure_Count"] >= volume_threshold
)

procedure_priority["High_Cost_Per_Patient_Flag"] = (
    procedure_priority["Cost_Per_Patient"]
    >= procedure_priority["Cost_Per_Patient"].median()
)

procedure_priority["High_Repeat_Utilization_Flag"] = (
    procedure_priority["Procedures_Per_Patient"]
    >= procedure_priority["Procedures_Per_Patient"].median()
)

procedure_priority["431_Dominated_Flag"] = (
    procedure_priority["Cost_431_Share"].eq(100)
)


# ============================================================================
# 18. FINAL DECISION-READY DATASET
# ============================================================================

procedure_priority = procedure_priority.sort_values(
    [
        "Priority_Profile",
        "Non_431_Total_Cost",
        "Procedure_Count"
    ],
    ascending=[True, False, False]
).reset_index(drop=True)


# ============================================================================
# 19. OVERALL ANALYTICAL METRICS
# ============================================================================

procedure_insight_metrics = pd.DataFrame({
    "Metric": [
        "Total Procedure Records",
        "Unique Procedure Codes",
        "Unique Canonical Descriptions",
        "Total Observed Procedure Cost",
        "Total Non-431 Procedure Cost",
        "431 Record Share (%)",
        "431 Cost Share (%)",
        "Top 10 Total Cost Share (%)",
        "Top 20 Total Cost Share (%)",
        "Top 10 Non-431 Cost Share (%)",
        "Top 20 Non-431 Cost Share (%)",
        "Top 10 Utilization Share (%)",
        "Top 20 Utilization Share (%)",
        "High Cost / High Utilization Groups",
        "High Cost / Low Utilization Groups",
        "Low Cost / High Utilization Groups",
        "431-Dominated Groups"
    ],
    "Value": [
        total_procedures,
        procedure_insight_summary["CODE"].nunique(),
        procedure_insight_summary["CANONICAL_DESCRIPTION"].nunique(),
        total_observed_cost,
        total_non431_cost,
        (records_431 / len(procedure_e)) * 100,
        (cost_431 / total_observed_cost) * 100,
        (top10_total_cost / total_observed_cost) * 100,
        (top20_total_cost / total_observed_cost) * 100,
        (top10_non431_cost / total_non431_cost) * 100,
        (top20_non431_cost / total_non431_cost) * 100,
        (top10_volume / total_procedures) * 100,
        (top20_volume / total_procedures) * 100,
        (
            procedure_priority["Priority_Profile"]
            .eq("PRIORITY 1 — High Cost / High Utilization")
            .sum()
        ),
        (
            procedure_priority["Priority_Profile"]
            .eq("PRIORITY 2 — High Cost / Low Utilization")
            .sum()
        ),
        (
            procedure_priority["Priority_Profile"]
            .eq("PRIORITY 3 — High Utilization / Lower Non-431 Cost")
            .sum()
        ),
        (
            procedure_priority["Priority_Profile"]
            .eq("PRIORITY 4 — 431 Cost Dominated")
            .sum()
        )
    ]
})


# ============================================================================
# 20. FINAL VALIDATION
# ============================================================================

print("\n" + "=" * 70)
print("FINAL VALIDATION")
print("=" * 70)

validation_results = pd.DataFrame({
    "Validation": [
        "Record count preserved",
        "No records deleted",
        "Original CODE preserved",
        "Original DESCRIPTION preserved",
        "BASE_COST = 431 flag available",
        "Non-431 cost available",
        "Procedure-level summary created",
        "Priority profile created"
    ],
    "Result": [
        len(procedure_e) == len(procedure_analysis),
        True,
        "ORIGINAL_CODE" in procedure_e.columns,
        "ORIGINAL_DESCRIPTION" in procedure_e.columns,
        "BASE_COST_431_FLAG" in procedure_e.columns,
        "NON_431_COST" in procedure_e.columns,
        len(procedure_insight_summary) > 0,
        "Priority_Profile" in procedure_priority.columns
    ]
})

print(validation_results.to_string(index=False))


# ============================================================================
# 21. FINAL OUTPUT SUMMARY
# ============================================================================

print("\n" + "=" * 70)
print("STEP 4.18E COMPLETE")
print("=" * 70)

print(
    f"Total procedure records: "
    f"{len(procedure_e):,}"
)

print(
    f"Unique procedure codes: "
    f"{procedure_insight_summary['CODE'].nunique():,}"
)

print(
    f"Total observed procedure cost: "
    f"{total_observed_cost:,.2f}"
)

print(
    f"Total non-431 procedure cost: "
    f"{total_non431_cost:,.2f}"
)

print(
    f"431 record share: "
    f"{(records_431 / len(procedure_e)) * 100:.2f}%"
)

print(
    f"431 cost share: "
    f"{(cost_431 / total_observed_cost) * 100:.2f}%"
)

print(
    f"Top 10 non-431 cost concentration: "
    f"{(top10_non431_cost / total_non431_cost) * 100:.2f}%"
)

print(
    f"Top 20 non-431 cost concentration: "
    f"{(top20_non431_cost / total_non431_cost) * 100:.2f}%"
)

print(
    f"Priority 1 groups: "
    f"{(
        procedure_priority['Priority_Profile']
        .eq('PRIORITY 1 — High Cost / High Utilization')
    ).sum():,}"
)

print(
    f"Priority 2 groups: "
    f"{(
        procedure_priority['Priority_Profile']
        .eq('PRIORITY 2 — High Cost / Low Utilization')
    ).sum():,}"
)

print(
    f"431-dominated groups: "
    f"{(
        procedure_priority['Priority_Profile']
        .eq('PRIORITY 4 — 431 Cost Dominated')
    ).sum():,}"
)


# ============================================================================
# DATASETS CREATED
# ============================================================================

print("\nANALYTICAL DATASETS CREATED:")
print("  - procedure_e")
print("  - procedure_insight_summary")
print("  - high_cost_non431_procedures")
print("  - high_utilization_procedure_insights")
print("  - high_cost_per_patient_insights")
print("  - high_repeat_utilization")
print("  - high_cost_high_utilization")
print("  - high_cost_low_utilization")
print("  - low_cost_high_utilization")
print("  - procedures_100pct_431")
print("  - procedure_priority")
print("  - procedure_insight_metrics")

print("\nSTATUS: PASS")
print("=" * 70)

======================================================================
STEP 4.18E — PROCEDURE COST & UTILIZATION INSIGHT ANALYSIS
======================================================================

SOURCE DATA CHECK
----------------------------------------------------------------------
STATUS: PASS
procedure_analysis is available.
Procedure records available: 47,701

ANALYTICAL DATASET VALIDATION
----------------------------------------------------------------------
Records preserved: 47,701
Unique procedure codes: 157
Unique original descriptions: 163
Unique canonical descriptions: 163
BASE_COST = 431 records: 30,988
Non-431 records: 16,713

TOP 20 PROCEDURES BY NON-431 TOTAL COST
----------------------------------------------------------------------
     CODE                                                           CANONICAL_DESCRIPTION  Procedure_Count  Non_431_Count  Non_431_Total_Cost  Average_Procedure_Cost  Unique_Patients  Cost_Per_Patient  Cost_431_Share
180325003                                                        Electrical cardioversion             1383           1383            35824002            25903.110629               74     484108.135135        0.000000
225158009                                                 Auscultation of the fetal heart             1065           1065             5657822             5312.508920               71      79687.633803        0.000000
274804006                                             Evaluation of uterine fundal height             1065           1065             5631281             5287.587793               71      79313.816901        0.000000
703423002                         Combined chemotherapy and radiation therapy (procedure)              444            444             5237596            11796.387387               21     249409.333333        0.000000
 73761001                                                                     Colonoscopy              424            424             5021003            11841.988208              233      21549.369099        0.000000
 18286008                                            Catheter ablation of tissue of heart              365            365             3405999             9331.504110               54      63074.055556        0.000000
265764009                                                      Renal dialysis (procedure)             2746           2746             2757221             1004.086307                5     551444.200000        0.000000
312681000                                                   Bone density scan (procedure)              198            198             1901367             9602.863636              115      16533.626087        0.000000
169230002                                             Ultrasound scan for fetal viability              184            184             1693824             9205.565217               81      20911.407407        0.000000
127783003                                                          Spirometry (procedure)              209            209             1628688             7792.765550               23      70812.521739        0.000000
228557008                               Cognitive and behavioral therapy (regime/therapy)              136            136             1412779            10388.080882               17      83104.647059        0.000000
 76601001                                                         Intramuscular injection              522            522             1325634             2539.528736               45      29458.533333        0.000000
430193006                                           Medication Reconciliation (procedure)             2284           2278             1160254              509.124343              418       2781.913876        0.262697
433112001 Percutaneous mechanical thrombectomy of portal vein using fluoroscopic guidance               57             57             1152998            20228.035088               55      20963.600000        0.000000
305351004                                                        Admit to ICU (procedure)                5              5             1031302           206260.400000                2     515651.000000        0.000000
288086009                                                               Suture open wound              103            103              956599             9287.368932               93      10286.010753        0.000000
252160004                                                         Standard pregnancy test              184            184              955125             5190.896739               81      11791.666667        0.000000
302497006                                                        Hemodialysis (procedure)               27             27              791088            29299.555556                4     197772.000000        0.000000
180256009                                                      Subcutaneous immunotherapy               54             54              639117            11835.500000                1     639117.000000        0.000000
274031008                                                              Rectal polypectomy               61             61              624125            10231.557377               52      12002.403846        0.000000

TOP 20 PROCEDURES BY UTILIZATION
----------------------------------------------------------------------
           CODE                                                                CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Unique_Encounters  Procedures_Per_Patient  Procedures_Per_Encounter  Total_Procedure_Cost  Cost_431_Share
      710824005                               Assessment of health and social care needs (procedure)             4596              509               4596                9.029470                  1.000000               1980876      100.000000
      385763009                                                        Hospice care (regime/therapy)             4098               61                162               67.180328                 25.296296               1766238      100.000000
      171207006                                                     Depression screening (procedure)             3614              500               3614                7.228000                  1.000000               1557634      100.000000
454711000124102   Depression screening using Patient Health Questionnaire Two-Item score (procedure)             3614              500               3614                7.228000                  1.000000               1557634      100.000000
428211000124100                                              Assessment of substance use (procedure)             2906              436               2906                6.665138                  1.000000               1252486      100.000000
      265764009                                                           Renal dialysis (procedure)             2746                5               2746              549.200000                  1.000000               2757221        0.000000
      762993000                                        Assessment using Morse Fall Scale (procedure)             2422              268               2422                9.037313                  1.000000               1043882      100.000000
      710841007                                                    Assessment of anxiety (procedure)             2288              437               2288                5.235698                  1.000000                986128      100.000000
      430193006                                                Medication Reconciliation (procedure)             2284              418               2284                5.464115                  1.000000               1162840        0.262697
      713106006                                                 Screening for drug abuse (procedure)             1484              333               1484                4.456456                  1.000000                639604      100.000000
      866148006                                             Screening for domestic abuse (procedure)             1432              356               1432                4.022472                  1.000000                617192      100.000000
      763302001 Assessment using Alcohol Use Disorders Identification Test - Consumption (procedure)             1422              331               1422                4.296073                  1.000000                612882      100.000000
      180325003                                                             Electrical cardioversion             1383               74               1383               18.689189                  1.000000              35824002        0.000000
      225158009                                                      Auscultation of the fetal heart             1065               71               1065               15.000000                  1.000000               5657822        0.000000
      274804006                                                  Evaluation of uterine fundal height             1065               71               1065               15.000000                  1.000000               5631281        0.000000
      229064008                                                    Movement therapy (regime/therapy)              890               89                890               10.000000                  1.000000                383590      100.000000
       76601001                                                              Intramuscular injection              522               45                522               11.600000                  1.000000               1325634        0.000000
      703423002                              Combined chemotherapy and radiation therapy (procedure)              444               21                444               21.142857                  1.000000               5237596        0.000000
       73761001                                                                          Colonoscopy              424              233                424                1.819742                  1.000000               5021003        0.000000
       18286008                                                 Catheter ablation of tissue of heart              365               54                365                6.759259                  1.000000               3405999        0.000000

TOP 20 PROCEDURES BY COST PER PATIENT
----------------------------------------------------------------------
     CODE                                             CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Total_Procedure_Cost  Cost_Per_Patient  Procedures_Per_Patient  Cost_431_Share
180256009                                        Subcutaneous immunotherapy               54                1                639117     639117.000000               54.000000             0.0
265764009                                        Renal dialysis (procedure)             2746                5               2757221     551444.200000              549.200000             0.0
305351004                                          Admit to ICU (procedure)                5                2               1031302     515651.000000                2.500000             0.0
180325003                                          Electrical cardioversion             1383               74              35824002     484108.135135               18.689189             0.0
703423002           Combined chemotherapy and radiation therapy (procedure)              444               21               5237596     249409.333333               21.142857             0.0
302497006                                          Hemodialysis (procedure)               27                4                791088     197772.000000                6.750000             0.0
228557008                 Cognitive and behavioral therapy (regime/therapy)              136               17               1412779      83104.647059                8.000000             0.0
225158009                                   Auscultation of the fetal heart             1065               71               5657822      79687.633803               15.000000             0.0
274804006                               Evaluation of uterine fundal height             1065               71               5631281      79313.816901               15.000000             0.0
127783003                                            Spirometry (procedure)              209               23               1628688      70812.521739                9.086957             0.0
 18286008                              Catheter ablation of tissue of heart              365               54               3405999      63074.055556                6.759259             0.0
232717009                                   Coronary artery bypass grafting                9                8                423773      52971.625000                1.125000             0.0
 33195004                            Teleradiotherapy procedure (procedure)              170                5                169567      33913.400000               34.000000             0.0
 76601001                                           Intramuscular injection              522               45               1325634      29458.533333               11.600000             0.0
392021009                                  Lumpectomy of breast (procedure)                5                5                146765      29353.000000                1.000000             0.0
 15081005                         Pulmonary rehabilitation (regime/therapy)              171               12                326546      27212.166667               14.250000             0.0
447365002 Insertion of biventricular implantable cardioverter defibrillator                4                4                108804      27201.000000                1.000000             0.0
 43075005                                        Partial resection of colon                7                7                176605      25229.285714                1.000000             0.0
432231006                 Fine needle aspiration biopsy of lung (procedure)                1                1                 23141      23141.000000                1.000000             0.0
415070008                                Percutaneous coronary intervention                9                8                177552      22194.000000                1.125000             0.0

TOP 20 PROCEDURES BY PROCEDURES PER PATIENT
----------------------------------------------------------------------
             CODE                                                     CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Unique_Encounters  Procedures_Per_Patient  Procedures_Per_Encounter  Total_Procedure_Cost  Cost_431_Share
        265764009                                                Renal dialysis (procedure)             2746                5               2746              549.200000                  1.000000               2757221             0.0
        385763009                                             Hospice care (regime/therapy)             4098               61                162               67.180328                 25.296296               1766238           100.0
        180256009                                                Subcutaneous immunotherapy               54                1                 54               54.000000                  1.000000                639117             0.0
        398171003                                           Hearing examination (procedure)              144                4                144               36.000000                  1.000000                 62064           100.0
16335031000119100 High resolution computed tomography of chest without contrast (procedure)              144                4                144               36.000000                  1.000000                 62064           100.0
         33195004                                    Teleradiotherapy procedure (procedure)              170                5                170               34.000000                  1.000000                169567             0.0
        703423002                   Combined chemotherapy and radiation therapy (procedure)              444               21                444               21.142857                  1.000000               5237596             0.0
        180325003                                                  Electrical cardioversion             1383               74               1383               18.689189                  1.000000              35824002             0.0
        225158009                                           Auscultation of the fetal heart             1065               71               1065               15.000000                  1.000000               5657822             0.0
        274804006                                       Evaluation of uterine fundal height             1065               71               1065               15.000000                  1.000000               5631281             0.0
        182777000                                    Monitoring of patient (regime/therapy)               29                2                 29               14.500000                  1.000000                 12499           100.0
         15081005                                 Pulmonary rehabilitation (regime/therapy)              171               12                171               14.250000                  1.000000                326546             0.0
        367336001                                                  Chemotherapy (procedure)               40                3                 40               13.333333                  1.000000                 17240           100.0
         76601001                                                   Intramuscular injection              522               45                522               11.600000                  1.000000               1325634             0.0
        229064008                                         Movement therapy (regime/therapy)              890               89                890               10.000000                  1.000000                383590           100.0
        127783003                                                    Spirometry (procedure)              209               23                209                9.086957                  1.000000               1628688             0.0
        762993000                             Assessment using Morse Fall Scale (procedure)             2422              268               2422                9.037313                  1.000000               1043882           100.0
        710824005                    Assessment of health and social care needs (procedure)             4596              509               4596                9.029470                  1.000000               1980876           100.0
         90226004 Cytopathology procedure  preparation of smear  genital source (procedure)              140               17                140                8.235294                  1.000000                283128             0.0
         35025007                                     Manual pelvic examination (procedure)              140               17                140                8.235294                  1.000000                 19677             0.0

HIGH NON-431 COST + HIGH UTILIZATION PROCEDURES
----------------------------------------------------------------------
     CODE                                                           CANONICAL_DESCRIPTION  Procedure_Count  Non_431_Count  Non_431_Total_Cost  Unique_Patients  Cost_Per_Patient  Procedures_Per_Patient  Cost_431_Share

In [135]:
# ============================================================================
# STEP 4.18F — PROCEDURE STANDARDIZATION VALIDATION & CLINICAL/COST SEGMENTATION
# ----------------------------------------------------------------------------
# Purpose:
#   Validate procedure standardization, preserve source integrity, and create
#   clinically and financially meaningful analytical segments.
#
# Principles:
#   - DO NOT delete procedure records.
#   - DO NOT modify ORIGINAL_CODE or ORIGINAL_DESCRIPTION.
#   - Treat BASE_COST = 431 as an analytical flag, not automatically invalid.
#   - Use CODE as the stable procedure identifier.
#   - Validate canonical description consistency.
#   - Separate 431-dominated activity from meaningful non-431 cost analysis.
#   - Preserve both volume and financial perspectives.
# ============================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.18F — PROCEDURE STANDARDIZATION VALIDATION &")
print("CLINICAL/COST SEGMENTATION")
print("=" * 70)


# ============================================================================
# 1. SOURCE DATA CHECK
# ============================================================================

required_columns = [
    "CODE",
    "DESCRIPTION",
    "ORIGINAL_CODE",
    "ORIGINAL_DESCRIPTION",
    "BASE_COST",
    "BASE_COST_431_FLAG",
    "COST_BAND",
    "COST_INTERPRETATION_FLAG",
    "PATIENT",
    "ENCOUNTER",
    "CANONICAL_DESCRIPTION"
]

missing_columns = [
    col for col in required_columns
    if col not in procedure_analysis.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

df = procedure_analysis.copy()

print("\nSOURCE DATA CHECK")
print("-" * 70)
print("STATUS: PASS")
print(f"Procedure records available: {len(df):,}")


# ============================================================================
# 2. RECORD PRESERVATION CHECK
# ============================================================================

source_record_count = len(df)

print("\nRECORD PRESERVATION")
print("-" * 70)
print(f"Source records: {source_record_count:,}")
print(f"Analytical records: {len(df):,}")
print(
    f"Record count preserved: "
    f"{source_record_count == len(df)}"
)

if source_record_count != len(df):
    raise ValueError(
        "Record count changed unexpectedly."
    )


# ============================================================================
# 3. ORIGINAL VALUE PRESERVATION
# ============================================================================

original_code_preserved = (
    df["ORIGINAL_CODE"].notna().all()
)

original_description_preserved = (
    df["ORIGINAL_DESCRIPTION"].notna().all()
)

print("\nORIGINAL VALUE PRESERVATION")
print("-" * 70)
print(
    f"Original CODE preserved: "
    f"{original_code_preserved}"
)
print(
    f"Original DESCRIPTION preserved: "
    f"{original_description_preserved}"
)


# ============================================================================
# 4. CODE → DESCRIPTION STANDARDIZATION VALIDATION
# ============================================================================

code_description_summary = (
    df.groupby("CODE")
      .agg(
          Unique_Original_Descriptions=(
              "ORIGINAL_DESCRIPTION",
              "nunique"
          ),
          Unique_Canonical_Descriptions=(
              "CANONICAL_DESCRIPTION",
              "nunique"
          ),
          Procedure_Count=("CODE", "size")
      )
      .reset_index()
)

code_variance = code_description_summary[
    code_description_summary[
        "Unique_Original_Descriptions"
    ] > 1
].copy()

canonical_variance = code_description_summary[
    code_description_summary[
        "Unique_Canonical_Descriptions"
    ] > 1
].copy()

print("\nCODE → DESCRIPTION STANDARDIZATION VALIDATION")
print("-" * 70)

print(
    "Codes with multiple original descriptions:",
    len(code_variance)
)

print(
    "Codes with multiple canonical descriptions:",
    len(canonical_variance)
)

print("\nCODES WITH ORIGINAL DESCRIPTION VARIANCE")
print("-" * 70)

if len(code_variance) > 0:
    print(
        code_variance[
            [
                "CODE",
                "Unique_Original_Descriptions",
                "Unique_Canonical_Descriptions",
                "Procedure_Count"
            ]
        ].to_string(index=False)
    )
else:
    print("None")


print("\nCODES WITH MULTIPLE CANONICAL DESCRIPTIONS")
print("-" * 70)

if len(canonical_variance) > 0:
    print(
        canonical_variance[
            [
                "CODE",
                "Unique_Original_Descriptions",
                "Unique_Canonical_Descriptions",
                "Procedure_Count"
            ]
        ].to_string(index=False)
    )
else:
    print("None")


# ============================================================================
# 5. CANONICAL DESCRIPTION QUALITY
# ============================================================================

missing_canonical = (
    df["CANONICAL_DESCRIPTION"]
    .isna()
    .sum()
)

blank_canonical = (
    df["CANONICAL_DESCRIPTION"]
    .astype(str)
    .str.strip()
    .eq("")
    .sum()
)

print("\nCANONICAL DESCRIPTION QUALITY")
print("-" * 70)
print(f"Missing canonical descriptions: {missing_canonical:,}")
print(f"Blank canonical descriptions: {blank_canonical:,}")

canonical_quality_pass = (
    missing_canonical == 0
    and blank_canonical == 0
)

print(
    "Canonical description availability:",
    "PASS" if canonical_quality_pass else "REVIEW"
)


# ============================================================================
# 6. EXPLICIT REVIEW OF THE FOUR KNOWN VARIANT CODES
# ============================================================================

known_variant_codes = [
    "5880005",
    "171207006",
    "399208008",
    "90226004"
]

variant_review = (
    df[
        df["CODE"].astype(str).isin(known_variant_codes)
    ]
    .groupby("CODE")
    .agg(
        Original_Descriptions=(
            "ORIGINAL_DESCRIPTION",
            lambda x: sorted(
                pd.Series(x.dropna())
                .astype(str)
                .unique()
                .tolist()
            )
        ),
        Canonical_Descriptions=(
            "CANONICAL_DESCRIPTION",
            lambda x: sorted(
                pd.Series(x.dropna())
                .astype(str)
                .unique()
                .tolist()
            )
        ),
        Procedure_Count=("CODE", "size")
    )
    .reset_index()
)

print("\nKNOWN DESCRIPTION-VARIANT CODES")
print("-" * 70)

if len(variant_review) > 0:
    for _, row in variant_review.iterrows():

        print(f"\nCODE: {row['CODE']}")
        print(
            f"Procedure records: "
            f"{row['Procedure_Count']:,}"
        )

        print("Original descriptions:")

        for desc in row["Original_Descriptions"]:
            print(f"  - {desc}")

        print("Canonical descriptions:")

        for desc in row["Canonical_Descriptions"]:
            print(f"  - {desc}")


# ============================================================================
# 7. BASE_COST = 431 SEGMENTATION
# ============================================================================

df["IS_431_COST"] = (
    pd.to_numeric(
        df["BASE_COST"],
        errors="coerce"
    ) == 431
)

df["IS_NON_431_COST"] = ~df["IS_431_COST"]

print("\nBASE_COST = 431 SEGMENTATION")
print("-" * 70)

count_431 = int(df["IS_431_COST"].sum())
count_non_431 = int(df["IS_NON_431_COST"].sum())

print(f"431 records: {count_431:,}")
print(f"Non-431 records: {count_non_431:,}")
print(
    f"431 record share: "
    f"{count_431 / len(df) * 100:.2f}%"
)


# ============================================================================
# 8. COST AGGREGATION
# ============================================================================

total_cost = df["BASE_COST"].sum()

cost_431 = df.loc[
    df["IS_431_COST"],
    "BASE_COST"
].sum()

cost_non_431 = df.loc[
    df["IS_NON_431_COST"],
    "BASE_COST"
].sum()

print("\nCOST SEGMENTATION")
print("-" * 70)
print(f"Total procedure cost: {total_cost:,.2f}")
print(f"431 cost: {cost_431:,.2f}")
print(f"Non-431 cost: {cost_non_431:,.2f}")
print(
    f"431 cost share: "
    f"{cost_431 / total_cost * 100:.2f}%"
)
print(
    f"Non-431 cost share: "
    f"{cost_non_431 / total_cost * 100:.2f}%"
)


# ============================================================================
# 9. PROCEDURE-LEVEL CLINICAL / COST SEGMENTATION
# ============================================================================

procedure_segmentation = (
    df.groupby(
        [
            "CODE",
            "CANONICAL_DESCRIPTION"
        ],
        dropna=False
    )
    .agg(
        Procedure_Count=("CODE", "size"),
        Unique_Patients=("PATIENT", "nunique"),
        Unique_Encounters=("ENCOUNTER", "nunique"),
        Total_Cost=("BASE_COST", "sum"),
        Average_Cost=("BASE_COST", "mean"),
        Median_Cost=("BASE_COST", "median"),
        Cost_431_Count=("IS_431_COST", "sum"),
        Non_431_Count=("IS_NON_431_COST", "sum"),
        Non_431_Cost=(
            "BASE_COST",
            lambda x: x[x != 431].sum()
        )
    )
    .reset_index()
)

procedure_segmentation[
    "Cost_431_Share"
] = (
    procedure_segmentation["Cost_431_Count"]
    / procedure_segmentation["Procedure_Count"]
    * 100
)

procedure_segmentation[
    "Procedures_Per_Patient"
] = (
    procedure_segmentation["Procedure_Count"]
    / procedure_segmentation["Unique_Patients"]
)

procedure_segmentation[
    "Procedures_Per_Encounter"
] = (
    procedure_segmentation["Procedure_Count"]
    / procedure_segmentation["Unique_Encounters"]
)

procedure_segmentation[
    "Cost_Per_Patient"
] = (
    procedure_segmentation["Total_Cost"]
    / procedure_segmentation["Unique_Patients"]
)


# ============================================================================
# 10. COST INTENSITY SEGMENTS
# ============================================================================

non_431_cost_values = (
    df.loc[
        df["IS_NON_431_COST"],
        "BASE_COST"
    ]
)

if len(non_431_cost_values) > 0:

    p50_non431 = non_431_cost_values.quantile(0.50)
    p75_non431 = non_431_cost_values.quantile(0.75)
    p95_non431 = non_431_cost_values.quantile(0.95)
    p99_non431 = non_431_cost_values.quantile(0.99)

else:

    p50_non431 = 0
    p75_non431 = 0
    p95_non431 = 0
    p99_non431 = 0


def assign_cost_intensity(row):

    if row["Cost_431_Share"] == 100:
        return "431_DOMINATED"

    if row["Non_431_Cost"] == 0:
        return "431_DOMINATED"

    avg_cost = row["Average_Cost"]

    if avg_cost >= p99_non431:
        return "EXTREME_NON_431_COST"

    if avg_cost >= p95_non431:
        return "HIGH_NON_431_COST"

    if avg_cost >= p75_non431:
        return "MODERATE_NON_431_COST"

    return "STANDARD_NON_431_COST"


procedure_segmentation[
    "Cost_Intensity"
] = procedure_segmentation.apply(
    assign_cost_intensity,
    axis=1
)


# ============================================================================
# 11. UTILIZATION INTENSITY SEGMENTS
# ============================================================================

procedure_volume_q75 = (
    procedure_segmentation[
        "Procedure_Count"
    ].quantile(0.75)
)

procedure_volume_q95 = (
    procedure_segmentation[
        "Procedure_Count"
    ].quantile(0.95)
)

repeat_q75 = (
    procedure_segmentation[
        "Procedures_Per_Patient"
    ].quantile(0.75)
)

repeat_q95 = (
    procedure_segmentation[
        "Procedures_Per_Patient"
    ].quantile(0.95)
)


def assign_utilization_intensity(row):

    volume = row["Procedure_Count"]
    repeat_rate = row["Procedures_Per_Patient"]

    if (
        volume >= procedure_volume_q95
        or repeat_rate >= repeat_q95
    ):
        return "EXTREME_UTILIZATION"

    if (
        volume >= procedure_volume_q75
        or repeat_rate >= repeat_q75
    ):
        return "HIGH_UTILIZATION"

    return "STANDARD_UTILIZATION"


procedure_segmentation[
    "Utilization_Intensity"
] = procedure_segmentation.apply(
    assign_utilization_intensity,
    axis=1
)


# ============================================================================
# 12. PRIORITY SEGMENT
# ============================================================================

def assign_priority(row):

    cost = row["Cost_Intensity"]
    utilization = row["Utilization_Intensity"]

    if cost in [
        "EXTREME_NON_431_COST",
        "HIGH_NON_431_COST"
    ] and utilization in [
        "EXTREME_UTILIZATION",
        "HIGH_UTILIZATION"
    ]:
        return "PRIORITY 1 — HIGH COST / HIGH UTILIZATION"

    if cost in [
        "EXTREME_NON_431_COST",
        "HIGH_NON_431_COST"
    ]:
        return "PRIORITY 2 — HIGH COST / LOWER UTILIZATION"

    if utilization in [
        "EXTREME_UTILIZATION",
        "HIGH_UTILIZATION"
    ]:
        return "PRIORITY 3 — HIGH UTILIZATION / LOWER COST"

    if row["Cost_431_Share"] == 100:
        return "PRIORITY 4 — 431 COST DOMINATED"

    return "STANDARD"


procedure_segmentation[
    "Priority_Profile"
] = procedure_segmentation.apply(
    assign_priority,
    axis=1
)


# ============================================================================
# 13. HIGH COST / HIGH UTILIZATION
# ============================================================================

high_cost_high_utilization = (
    procedure_segmentation[
        procedure_segmentation[
            "Priority_Profile"
        ]
        == "PRIORITY 1 — HIGH COST / HIGH UTILIZATION"
    ]
    .sort_values(
        "Non_431_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)


# ============================================================================
# 14. HIGH COST / LOWER UTILIZATION
# ============================================================================

high_cost_low_utilization = (
    procedure_segmentation[
        procedure_segmentation[
            "Priority_Profile"
        ]
        == "PRIORITY 2 — HIGH COST / LOWER UTILIZATION"
    ]
    .sort_values(
        "Non_431_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)


# ============================================================================
# 15. HIGH UTILIZATION / LOWER COST
# ============================================================================

high_utilization_low_cost = (
    procedure_segmentation[
        procedure_segmentation[
            "Priority_Profile"
        ]
        == "PRIORITY 3 — HIGH UTILIZATION / LOWER COST"
    ]
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .reset_index(drop=True)
)


# ============================================================================
# 16. 431-DOMINATED PROCEDURES
# ============================================================================

procedures_431_dominated = (
    procedure_segmentation[
        procedure_segmentation[
            "Cost_431_Share"
        ] == 100
    ]
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .reset_index(drop=True)
)


# ============================================================================
# 17. HIGH REPEAT UTILIZATION
# ============================================================================

high_repeat_utilization = (
    procedure_segmentation[
        procedure_segmentation[
            "Procedures_Per_Patient"
        ] >= repeat_q95
    ]
    .sort_values(
        "Procedures_Per_Patient",
        ascending=False
    )
    .reset_index(drop=True)
)


# ============================================================================
# 18. PROCEDURE COST CONCENTRATION
# ============================================================================

procedure_cost_rank = (
    procedure_segmentation
    .sort_values(
        "Non_431_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)

total_non_431_procedure_cost = (
    procedure_cost_rank["Non_431_Cost"].sum()
)

if total_non_431_procedure_cost > 0:

    top10_non431_share = (
        procedure_cost_rank.head(10)[
            "Non_431_Cost"
        ].sum()
        / total_non_431_procedure_cost
        * 100
    )

    top20_non431_share = (
        procedure_cost_rank.head(20)[
            "Non_431_Cost"
        ].sum()
        / total_non_431_procedure_cost
        * 100
    )

else:

    top10_non431_share = 0
    top20_non431_share = 0


# ============================================================================
# 19. UTILIZATION CONCENTRATION
# ============================================================================

procedure_volume_rank = (
    procedure_segmentation
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .reset_index(drop=True)
)

total_volume = (
    procedure_volume_rank[
        "Procedure_Count"
    ].sum()
)

top10_volume_share = (
    procedure_volume_rank.head(10)[
        "Procedure_Count"
    ].sum()
    / total_volume
    * 100
)

top20_volume_share = (
    procedure_volume_rank.head(20)[
        "Procedure_Count"
    ].sum()
    / total_volume
    * 100
)


# ============================================================================
# 20. PRIORITY DISTRIBUTION
# ============================================================================

priority_distribution = (
    procedure_segmentation[
        "Priority_Profile"
    ]
    .value_counts()
    .rename_axis("Priority_Profile")
    .reset_index(
        name="Procedure_Group_Count"
    )
)

priority_distribution[
    "Group_Share_%"
] = (
    priority_distribution[
        "Procedure_Group_Count"
    ]
    / len(procedure_segmentation)
    * 100
)


# ============================================================================
# 21. COST INTENSITY DISTRIBUTION
# ============================================================================

cost_intensity_distribution = (
    procedure_segmentation[
        "Cost_Intensity"
    ]
    .value_counts()
    .rename_axis("Cost_Intensity")
    .reset_index(
        name="Procedure_Group_Count"
    )
)


# ============================================================================
# 22. UTILIZATION INTENSITY DISTRIBUTION
# ============================================================================

utilization_distribution = (
    procedure_segmentation[
        "Utilization_Intensity"
    ]
    .value_counts()
    .rename_axis("Utilization_Intensity")
    .reset_index(
        name="Procedure_Group_Count"
    )
)


# ============================================================================
# 23. KEY METRICS
# ============================================================================

procedure_18f_metrics = pd.DataFrame({
    "Metric": [
        "Total procedure records",
        "Unique procedure codes",
        "Unique original descriptions",
        "Codes with original description variance",
        "Codes with canonical description variance",
        "Records with BASE_COST = 431",
        "431 record share (%)",
        "Total procedure cost",
        "431 procedure cost",
        "Non-431 procedure cost",
        "431 cost share (%)",
        "Non-431 cost share (%)",
        "High cost / high utilization groups",
        "High cost / lower utilization groups",
        "High utilization / lower cost groups",
        "431 dominated groups",
        "Top 10 non-431 procedure cost share (%)",
        "Top 20 non-431 procedure cost share (%)",
        "Top 10 procedure volume share (%)",
        "Top 20 procedure volume share (%)",
        "High repeat utilization groups"
    ],
    "Value": [
        len(df),
        df["CODE"].nunique(),
        df["ORIGINAL_DESCRIPTION"].nunique(),
        len(code_variance),
        len(canonical_variance),
        count_431,
        count_431 / len(df) * 100,
        total_cost,
        cost_431,
        cost_non_431,
        cost_431 / total_cost * 100,
        cost_non_431 / total_cost * 100,
        len(high_cost_high_utilization),
        len(high_cost_low_utilization),
        len(high_utilization_low_cost),
        len(procedures_431_dominated),
        top10_non431_share,
        top20_non431_share,
        top10_volume_share,
        top20_volume_share,
        len(high_repeat_utilization)
    ]
})


# ============================================================================
# 24. DISPLAY RESULTS
# ============================================================================

print("\nPROCEDURE PRIORITY DISTRIBUTION")
print("-" * 70)
print(
    priority_distribution.to_string(index=False)
)


print("\nCOST INTENSITY DISTRIBUTION")
print("-" * 70)
print(
    cost_intensity_distribution.to_string(index=False)
)


print("\nUTILIZATION INTENSITY DISTRIBUTION")
print("-" * 70)
print(
    utilization_distribution.to_string(index=False)
)


print("\nHIGH COST / HIGH UTILIZATION PROCEDURES")
print("-" * 70)

if len(high_cost_high_utilization) > 0:

    print(
        high_cost_high_utilization[
            [
                "CODE",
                "CANONICAL_DESCRIPTION",
                "Procedure_Count",
                "Non_431_Cost",
                "Unique_Patients",
                "Cost_Per_Patient",
                "Procedures_Per_Patient",
                "Cost_431_Share"
            ]
        ]
        .head(20)
        .to_string(index=False)
    )

else:
    print("None identified.")


print("\nHIGH COST / LOWER UTILIZATION PROCEDURES")
print("-" * 70)

if len(high_cost_low_utilization) > 0:

    print(
        high_cost_low_utilization[
            [
                "CODE",
                "CANONICAL_DESCRIPTION",
                "Procedure_Count",
                "Non_431_Cost",
                "Average_Cost",
                "Cost_Per_Patient",
                "Cost_431_Share"
            ]
        ]
        .head(20)
        .to_string(index=False)
    )

else:
    print("None identified.")


print("\nHIGH UTILIZATION / LOWER COST PROCEDURES")
print("-" * 70)

if len(high_utilization_low_cost) > 0:

    print(
        high_utilization_low_cost[
            [
                "CODE",
                "CANONICAL_DESCRIPTION",
                "Procedure_Count",
                "Unique_Patients",
                "Procedures_Per_Patient",
                "Total_Cost",
                "Cost_431_Share"
            ]
        ]
        .head(20)
        .to_string(index=False)
    )

else:
    print("None identified.")


print("\n431-DOMINATED PROCEDURES")
print("-" * 70)

print(
    procedures_431_dominated[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Total_Cost",
            "Cost_431_Share"
        ]
    ]
    .head(20)
    .to_string(index=False)
)


print("\nHIGH REPEAT UTILIZATION")
print("-" * 70)

if len(high_repeat_utilization) > 0:

    print(
        high_repeat_utilization[
            [
                "CODE",
                "CANONICAL_DESCRIPTION",
                "Procedure_Count",
                "Unique_Patients",
                "Procedures_Per_Patient",
                "Unique_Encounters"
            ]
        ]
        .head(20)
        .to_string(index=False)
    )

else:
    print("None identified.")


# ============================================================================
# 25. FINAL VALIDATION
# ============================================================================

validation = {
    "Record count preserved":
        len(df) == source_record_count,

    "Original CODE preserved":
        df["ORIGINAL_CODE"].notna().all(),

    "Original DESCRIPTION preserved":
        df["ORIGINAL_DESCRIPTION"].notna().all(),

    "Canonical description available":
        canonical_quality_pass,

    "431 flag available":
        "IS_431_COST" in df.columns,

    "Non-431 flag available":
        "IS_NON_431_COST" in df.columns,

    "Procedure segmentation created":
        len(procedure_segmentation) > 0,

    "Priority profile created":
        "Priority_Profile" in procedure_segmentation.columns,

    "No records deleted":
        len(df) == source_record_count
}

validation_table = pd.DataFrame({
    "Validation": list(validation.keys()),
    "Result": list(validation.values())
})

print("\nFINAL VALIDATION")
print("-" * 70)
print(
    validation_table.to_string(index=False)
)


# ============================================================================
# 26. CREATE ANALYTICAL DATASETS
# ============================================================================

procedure_f = procedure_segmentation.copy()

procedure_f_priority = procedure_segmentation[
    [
        "CODE",
        "CANONICAL_DESCRIPTION",
        "Procedure_Count",
        "Unique_Patients",
        "Unique_Encounters",
        "Total_Cost",
        "Non_431_Cost",
        "Average_Cost",
        "Median_Cost",
        "Cost_Per_Patient",
        "Procedures_Per_Patient",
        "Procedures_Per_Encounter",
        "Cost_431_Share",
        "Cost_Intensity",
        "Utilization_Intensity",
        "Priority_Profile"
    ]
].copy()


# ============================================================================
# 27. EXPORT / NOTEBOOK OBJECTS
# ============================================================================

procedure_standardization_validation = code_description_summary.copy()

procedure_cost_segmentation = procedure_segmentation.copy()

procedure_priority_matrix = procedure_f_priority.copy()

procedure_f_summary = procedure_18f_metrics.copy()


# ============================================================================
# 28. COMPLETION SUMMARY
# ============================================================================

print("\n" + "=" * 70)
print("STEP 4.18F COMPLETE")
print("=" * 70)

print(f"Total procedure records: {len(df):,}")
print(f"Unique procedure codes: {df['CODE'].nunique():,}")
print(
    f"Unique original descriptions: "
    f"{df['ORIGINAL_DESCRIPTION'].nunique():,}"
)

print(
    f"Codes with original description variance: "
    f"{len(code_variance):,}"
)

print(
    f"Codes with canonical description variance: "
    f"{len(canonical_variance):,}"
)

print(
    f"BASE_COST = 431 records: "
    f"{count_431:,}"
)

print(
    f"431 record share: "
    f"{count_431 / len(df) * 100:.2f}%"
)

print(
    f"Non-431 procedure cost: "
    f"{cost_non_431:,.2f}"
)

print(
    f"Top 10 non-431 cost concentration: "
    f"{top10_non431_share:.2f}%"
)

print(
    f"Top 20 non-431 cost concentration: "
    f"{top20_non431_share:.2f}%"
)

print(
    f"Top 10 procedure volume concentration: "
    f"{top10_volume_share:.2f}%"
)

print(
    f"Top 20 procedure volume concentration: "
    f"{top20_volume_share:.2f}%"
)

print(
    f"Priority 1 groups: "
    f"{len(high_cost_high_utilization):,}"
)

print(
    f"Priority 2 groups: "
    f"{len(high_cost_low_utilization):,}"
)

print(
    f"Priority 3 groups: "
    f"{len(high_utilization_low_cost):,}"
)

print(
    f"431-dominated groups: "
    f"{len(procedures_431_dominated):,}"
)

print("\nANALYTICAL DATASETS CREATED:")
print("  - procedure_f")
print("  - procedure_f_summary")
print("  - procedure_standardization_validation")
print("  - procedure_cost_segmentation")
print("  - procedure_priority_matrix")
print("  - high_cost_high_utilization")
print("  - high_cost_low_utilization")
print("  - high_utilization_low_cost")
print("  - procedures_431_dominated")
print("  - high_repeat_utilization")
print("  - priority_distribution")
print("  - cost_intensity_distribution")
print("  - utilization_distribution")

all_pass = all(validation.values())

print("\nSTATUS:", "PASS" if all_pass else "REVIEW REQUIRED")

print("=" * 70)

======================================================================
STEP 4.18F — PROCEDURE STANDARDIZATION VALIDATION &
CLINICAL/COST SEGMENTATION
======================================================================

SOURCE DATA CHECK
----------------------------------------------------------------------
STATUS: PASS
Procedure records available: 47,701

RECORD PRESERVATION
----------------------------------------------------------------------
Source records: 47,701
Analytical records: 47,701
Record count preserved: True

ORIGINAL VALUE PRESERVATION
----------------------------------------------------------------------
Original CODE preserved: True
Original DESCRIPTION preserved: True

CODE → DESCRIPTION STANDARDIZATION VALIDATION
----------------------------------------------------------------------
Codes with multiple original descriptions: 4
Codes with multiple canonical descriptions: 4

CODES WITH ORIGINAL DESCRIPTION VARIANCE
----------------------------------------------------------------------
     CODE  Unique_Original_Descriptions  Unique_Canonical_Descriptions  Procedure_Count
  5880005                             4                              4              308
 90226004                             2                              2              258
171207006                             2                              2             3804
399208008                             2                              2               90

CODES WITH MULTIPLE CANONICAL DESCRIPTIONS
----------------------------------------------------------------------
     CODE  Unique_Original_Descriptions  Unique_Canonical_Descriptions  Procedure_Count
  5880005                             4                              4              308
 90226004                             2                              2              258
171207006                             2                              2             3804
399208008                             2                              2               90

CANONICAL DESCRIPTION QUALITY
----------------------------------------------------------------------
Missing canonical descriptions: 0
Blank canonical descriptions: 0
Canonical description availability: PASS

KNOWN DESCRIPTION-VARIANT CODES
----------------------------------------------------------------------

CODE: 5880005
Procedure records: 308
Original descriptions:
  - Physical exam following abortion
  - Physical examination
  - Physical examination following birth
  - Physical examination of mother
Canonical descriptions:
  - Physical exam following abortion
  - Physical examination
  - Physical examination following birth
  - Physical examination of mother

CODE: 90226004
Procedure records: 258
Original descriptions:
  - Cytopathology procedure  preparation of smear  genital source
  - Cytopathology procedure  preparation of smear  genital source (procedure)
Canonical descriptions:
  - Cytopathology procedure  preparation of smear  genital source
  - Cytopathology procedure  preparation of smear  genital source (procedure)

CODE: 171207006
Procedure records: 3,804
Original descriptions:
  - Depression screening
  - Depression screening (procedure)
Canonical descriptions:
  - Depression screening
  - Depression screening (procedure)

CODE: 399208008
Procedure records: 90
Original descriptions:
  - Chest X-ray
  - Plain chest X-ray (procedure)
Canonical descriptions:
  - Chest X-ray
  - Plain chest X-ray (procedure)

BASE_COST = 431 SEGMENTATION
----------------------------------------------------------------------
431 records: 30,988
Non-431 records: 16,713
431 record share: 64.96%

COST SEGMENTATION
----------------------------------------------------------------------
Total procedure cost: 105,517,711.00
431 cost: 13,355,828.00
Non-431 cost: 92,161,883.00
431 cost share: 12.66%
Non-431 cost share: 87.34%

PROCEDURE PRIORITY DISTRIBUTION
----------------------------------------------------------------------
                          Priority_Profile  Procedure_Group_Count  Group_Share_%
                                  STANDARD                     78      47.852761
PRIORITY 3 — HIGH UTILIZATION / LOWER COST                     50      30.674847
           PRIORITY 4 — 431 COST DOMINATED                     28      17.177914
PRIORITY 2 — HIGH COST / LOWER UTILIZATION                      4       2.453988
 PRIORITY 1 — HIGH COST / HIGH UTILIZATION                      3       1.840491

COST INTENSITY DISTRIBUTION
----------------------------------------------------------------------
       Cost_Intensity  Procedure_Group_Count
STANDARD_NON_431_COST                     69
        431_DOMINATED                     50
MODERATE_NON_431_COST                     37
    HIGH_NON_431_COST                      5
 EXTREME_NON_431_COST                      2

UTILIZATION INTENSITY DISTRIBUTION
----------------------------------------------------------------------
Utilization_Intensity  Procedure_Group_Count
 STANDARD_UTILIZATION                    110
     HIGH_UTILIZATION                     36
  EXTREME_UTILIZATION                     17

HIGH COST / HIGH UTILIZATION PROCEDURES
----------------------------------------------------------------------
     CODE    CANONICAL_DESCRIPTION  Procedure_Count  Non_431_Cost  Unique_Patients  Cost_Per_Patient  Procedures_Per_Patient  Cost_431_Share
180325003 Electrical cardioversion             1383      35824002               74     484108.135135               18.689189             0.0
305351004 Admit to ICU (procedure)                5       1031302                2     515651.000000                2.500000             0.0
302497006 Hemodialysis (procedure)               27        791088                4     197772.000000                6.750000             0.0

HIGH COST / LOWER UTILIZATION PROCEDURES
----------------------------------------------------------------------
     CODE                                             CANONICAL_DESCRIPTION  Procedure_Count  Non_431_Cost  Average_Cost  Cost_Per_Patient  Cost_431_Share
232717009                                   Coronary artery bypass grafting                9        423773  47085.888889      52971.625000             0.0
 43075005                                        Partial resection of colon                7        176605  25229.285714      25229.285714             0.0
392021009                                  Lumpectomy of breast (procedure)                5        146765  29353.000000      29353.000000             0.0
447365002 Insertion of biventricular implantable cardioverter defibrillator                4        108804  27201.000000      27201.000000             0.0

HIGH UTILIZATION / LOWER COST PROCEDURES
----------------------------------------------------------------------
           CODE                                                                CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Procedures_Per_Patient  Total_Cost  Cost_431_Share
      710824005                               Assessment of health and social care needs (procedure)             4596              509                9.029470     1980876      100.000000
      385763009                                                        Hospice care (regime/therapy)             4098               61               67.180328     1766238      100.000000
      171207006                                                     Depression screening (procedure)             3614              500                7.228000     1557634      100.000000
454711000124102   Depression screening using Patient Health Questionnaire Two-Item score (procedure)             3614              500                7.228000     1557634      100.000000
428211000124100                                              Assessment of substance use (procedure)             2906              436                6.665138     1252486      100.000000
      265764009                                                           Renal dialysis (procedure)             2746                5              549.200000     2757221        0.000000
      762993000                                        Assessment using Morse Fall Scale (procedure)             2422              268                9.037313     1043882      100.000000
      710841007                                                    Assessment of anxiety (procedure)             2288              437                5.235698      986128      100.000000
      430193006                                                Medication Reconciliation (procedure)             2284              418                5.464115     1162840        0.262697
      713106006                                                 Screening for drug abuse (procedure)             1484              333                4.456456      639604      100.000000
      866148006                                             Screening for domestic abuse (procedure)             1432              356                4.022472      617192      100.000000
      763302001 Assessment using Alcohol Use Disorders Identification Test - Consumption (procedure)             1422              331                4.296073      612882      100.000000
      274804006                                                  Evaluation of uterine fundal height             1065               71               15.000000     5631281        0.000000
      225158009                                                      Auscultation of the fetal heart             1065               71               15.000000     5657822        0.000000
      229064008                                                    Movement therapy (regime/therapy)              890               89               10.000000      383590      100.000000
       76601001                                                              Intramuscular injection              522               45               11.600000     1325634        0.000000
      703423002                              Combined chemotherapy and radiation therapy (procedure)              444               21               21.142857     5237596        0.000000
       73761001                                                                          Colonoscopy              424              233                1.819742     5021003        0.000000
       18286008                                                 Catheter ablation of tissue of heart              365               54                6.759259     3405999        0.000000
      371908008                                            Oxygen administration by mask (procedure)              240               41                5.853659      103440      100.000000

431-DOMINATED PROCEDURES
----------------------------------------------------------------------
             CODE                                                                CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Total_Cost  Cost_431_Share
        710824005                               Assessment of health and social care needs (procedure)             4596              509     1980876           100.0
        385763009                                                        Hospice care (regime/therapy)             4098               61     1766238           100.0
        171207006                                                     Depression screening (procedure)             3614              500     1557634           100.0
  454711000124102   Depression screening using Patient Health Questionnaire Two-Item score (procedure)             3614              500     1557634           100.0
  428211000124100                                              Assessment of substance use (procedure)             2906              436     1252486           100.0
        762993000                                        Assessment using Morse Fall Scale (procedure)             2422              268     1043882           100.0
        710841007                                                    Assessment of anxiety (procedure)             2288              437      986128           100.0
        713106006                                                 Screening for drug abuse (procedure)             1484              333      639604           100.0
        866148006                                             Screening for domestic abuse (procedure)             1432              356      617192           100.0
        763302001 Assessment using Alcohol Use Disorders Identification Test - Consumption (procedure)             1422              331      612882           100.0
        229064008                                                    Movement therapy (regime/therapy)              890               89      383590           100.0
        371908008                                            Oxygen administration by mask (procedure)              240               41      103440           100.0
        431182000                                        Placing subject in prone position (procedure)              240               41      103440           100.0
        171207006                                                                 Depression screening              190               82       81890           100.0
        398171003                                                      Hearing examination (procedure)              144                4       62064           100.0
16335031000119100            High resolution computed tomography of chest without contrast (procedure)              144                4       62064           100.0
          5880005                                                 Physical examination following birth              119               68       51289           100.0
          5880005                                                       Physical examination of mother              118               68       50858           100.0
        274474001                                                                  Bone immobilization              118              102       50858           100.0
        271442007                                                                  Fetal anatomy study              116               69       49996           100.0

HIGH REPEAT UTILIZATION
----------------------------------------------------------------------
             CODE                                                     CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Procedures_Per_Patient  Unique_Encounters
        265764009                                                Renal dialysis (procedure)             2746                5              549.200000               2746
        385763009                                             Hospice care (regime/therapy)             4098               61               67.180328                162
        180256009                                                Subcutaneous immunotherapy               54                1               54.000000                 54
        398171003                                           Hearing examination (procedure)              144                4               36.000000                144
16335031000119100 High resolution computed tomography of chest without contrast (procedure)              144                4               36.000000                144
         33195004                                    Teleradiotherapy procedure (procedure)              170                5               34.000000                170
        703423002                   Combined chemotherapy and radiation therapy (procedure)              444               21               21.142857                444
        180325003                                                  Electrical cardioversion             1383               74               18.689189               1383
        274804006                                       Evaluation of uterine fundal height             1065               71               15.000000               1065
        225158009                                           Auscultation of the fetal heart             1065               71               15.000000               1065

FINAL VALIDATION
----------------------------------------------------------------------
                     Validation  Result
         Record count preserved    True
        Original CODE preserved    True
 Original DESCRIPTION preserved    True
Canonical description available    True
             431 flag available    True
         Non-431 flag available    True
 Procedure segmentation created    True
       Priority profile created    True
             No records deleted    True

======================================================================
STEP 4.18F COMPLETE
======================================================================
Total procedure records: 47,701
Unique procedure codes: 157
Unique original descriptions: 163
Codes with original description variance: 4
Codes with canonical description variance: 4
BASE_COST = 431 records: 30,988
431 record share: 64.96%
Non-431 procedure cost: 92,161,883.00
Top 10 non-431 cost concentration: 74.61%
Top 20 non-431 cost concentration: 85.51%
Top 10 procedure volume concentration: 63.00%
Top 20 procedure volume concentration: 81.89%
Priority 1 groups: 3
Priority 2 groups: 4
Priority 3 groups: 50
431-dominated groups: 50

ANALYTICAL DATASETS CREATED:
  - procedure_f
  - procedure_f_summary
  - procedure_standardization_validation
  - procedure_cost_segmentation
  - procedure_priority_matrix
  - high_cost_high_utilization
  - high_cost_low_utilization
  - high_utilization_low_cost
  - procedures_431_dominated
  - high_repeat_utilization
  - priority_distribution
  - cost_intensity_distribution
  - utilization_distribution

STATUS: PASS
======================================================================

In [136]:
# ============================================================================
# STEP 4.18G — PROCEDURE CODE-LEVEL CANONICALIZATION &
#              FINAL ANALYTICAL READINESS
# ============================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.18G — PROCEDURE CODE-LEVEL CANONICALIZATION &")
print("             FINAL ANALYTICAL READINESS")
print("=" * 70)


# ============================================================================
# 1. FIND THE CORRECT ROW-LEVEL SOURCE DATASET
# ============================================================================

print("\nSOURCE DATA DISCOVERY")
print("-" * 70)

# procedure_analysis should contain the original row-level procedure records.
if "procedure_analysis" not in globals():
    raise NameError(
        "procedure_analysis is not available. "
        "Please run STEP 4.18D first."
    )

source_df = procedure_analysis.copy()

print("Using source dataset: procedure_analysis")
print(f"Source records: {len(source_df):,}")


# ============================================================================
# 2. CHECK REQUIRED COLUMNS
# ============================================================================

required_columns = [
    "CODE",
    "DESCRIPTION",
    "BASE_COST",
    "PATIENT",
    "ENCOUNTER"
]

missing_columns = [
    col for col in required_columns
    if col not in source_df.columns
]

if missing_columns:
    print("\nAVAILABLE COLUMNS")
    print("-" * 70)
    print(source_df.columns.tolist())

    raise ValueError(
        f"procedure_analysis is missing required columns: "
        f"{missing_columns}"
    )

print("\nSOURCE DATA CHECK")
print("-" * 70)
print("STATUS: PASS")
print(f"Procedure records available: {len(source_df):,}")


# ============================================================================
# 3. PRESERVE ORIGINAL VALUES
# ============================================================================

procedure_g = source_df.copy()

if "ORIGINAL_CODE" not in procedure_g.columns:
    procedure_g["ORIGINAL_CODE"] = procedure_g["CODE"].copy()

if "ORIGINAL_DESCRIPTION" not in procedure_g.columns:
    procedure_g["ORIGINAL_DESCRIPTION"] = (
        procedure_g["DESCRIPTION"].copy()
    )

print("\nORIGINAL VALUE PRESERVATION")
print("-" * 70)
print("ORIGINAL_CODE available: True")
print("ORIGINAL_DESCRIPTION available: True")


# ============================================================================
# 4. EXPLICIT CODE-LEVEL CANONICAL MAPPING
# ============================================================================

canonical_mapping = {
    "5880005": "Physical examination",
    "171207006": "Depression screening",
    "399208008": "Plain chest X-ray",
    "90226004": (
        "Cytopathology procedure - preparation of smear - genital source"
    )
}

print("\nEXPLICIT CANONICAL MAPPING")
print("-" * 70)

for code, description in canonical_mapping.items():
    print(f"{code} → {description}")


# ============================================================================
# 5. NORMALIZE CODE TYPE FOR MAPPING
# ============================================================================

procedure_g["_CODE_KEY"] = (
    procedure_g["CODE"]
    .astype("string")
    .str.strip()
)


# ============================================================================
# 6. BUILD FALLBACK CODE-LEVEL MAPPING
# ============================================================================
# For codes not explicitly defined above:
# use the most frequent original DESCRIPTION.
# ============================================================================

description_counts = (
    procedure_g
    .groupby(
        ["_CODE_KEY", "ORIGINAL_DESCRIPTION"],
        dropna=False
    )
    .size()
    .reset_index(name="Description_Count")
)

description_counts = description_counts.sort_values(
    [
        "_CODE_KEY",
        "Description_Count",
        "ORIGINAL_DESCRIPTION"
    ],
    ascending=[True, False, True]
)

fallback_mapping = (
    description_counts
    .drop_duplicates(
        subset=["_CODE_KEY"],
        keep="first"
    )
    .set_index("_CODE_KEY")["ORIGINAL_DESCRIPTION"]
    .to_dict()
)


# ============================================================================
# 7. APPLY EXPLICIT + FALLBACK CANONICALIZATION
# ============================================================================

explicit_mapping_normalized = {
    str(code): description
    for code, description in canonical_mapping.items()
}

full_canonical_mapping = fallback_mapping.copy()
full_canonical_mapping.update(
    explicit_mapping_normalized
)

procedure_g["CANONICAL_DESCRIPTION"] = (
    procedure_g["_CODE_KEY"]
    .map(full_canonical_mapping)
)


# ============================================================================
# 8. CANONICAL DESCRIPTION QUALITY
# ============================================================================

missing_canonical = (
    procedure_g["CANONICAL_DESCRIPTION"].isna().sum()
)

blank_canonical = (
    procedure_g["CANONICAL_DESCRIPTION"]
    .astype("string")
    .str.strip()
    .eq("")
    .sum()
)

print("\nCANONICAL DESCRIPTION QUALITY")
print("-" * 70)
print(f"Missing canonical descriptions: {missing_canonical:,}")
print(f"Blank canonical descriptions: {blank_canonical:,}")

if missing_canonical > 0 or blank_canonical > 0:
    raise ValueError(
        "Canonical description mapping is incomplete."
    )

print("STATUS: PASS")


# ============================================================================
# 9. VERIFY ONE CANONICAL DESCRIPTION PER CODE
# ============================================================================

code_canonical_validation = (
    procedure_g
    .groupby("_CODE_KEY")["CANONICAL_DESCRIPTION"]
    .nunique()
    .reset_index(
        name="Unique_Canonical_Descriptions"
    )
)

codes_with_multiple_canonical = (
    code_canonical_validation[
        code_canonical_validation[
            "Unique_Canonical_Descriptions"
        ] > 1
    ]
)

print("\nCODE → CANONICAL DESCRIPTION VALIDATION")
print("-" * 70)
print(
    f"Unique procedure codes: "
    f"{procedure_g['_CODE_KEY'].nunique():,}"
)

print(
    "Codes with multiple canonical descriptions: "
    f"{len(codes_with_multiple_canonical):,}"
)

if len(codes_with_multiple_canonical) > 0:
    print(codes_with_multiple_canonical)

    raise ValueError(
        "Canonicalization failed: one or more procedure "
        "codes still have multiple canonical descriptions."
    )

print(
    "Every CODE has exactly one canonical description: True"
)


# ============================================================================
# 10. VALIDATE THE FOUR KNOWN VARIANT CODES
# ============================================================================

print("\nKNOWN VARIANT CODE VALIDATION")
print("-" * 70)

for code, expected_description in canonical_mapping.items():

    subset = procedure_g[
        procedure_g["_CODE_KEY"] == str(code)
    ]

    actual_values = (
        subset["CANONICAL_DESCRIPTION"]
        .dropna()
        .unique()
        .tolist()
    )

    print(f"\nCODE: {code}")
    print(f"Records: {len(subset):,}")
    print(f"Expected: {expected_description}")
    print(f"Actual: {actual_values}")

    if actual_values != [expected_description]:
        raise ValueError(
            f"Canonical mapping failed for CODE {code}"
        )


# ============================================================================
# 11. RECORD COUNT PRESERVATION
# ============================================================================

record_count_preserved = (
    len(procedure_g) == len(source_df)
)

print("\nRECORD PRESERVATION")
print("-" * 70)
print(f"Source records: {len(source_df):,}")
print(f"Analytical records: {len(procedure_g):,}")
print(
    f"Record count preserved: {record_count_preserved}"
)

if not record_count_preserved:
    raise ValueError(
        "Record count changed during canonicalization."
    )


# ============================================================================
# 12. ORIGINAL VALUE PRESERVATION
# ============================================================================

original_code_preserved = (
    procedure_g["ORIGINAL_CODE"].astype("string").tolist()
    ==
    source_df["ORIGINAL_CODE"].astype("string").tolist()
    if "ORIGINAL_CODE" in source_df.columns
    else
    procedure_g["ORIGINAL_CODE"].astype("string").tolist()
    ==
    source_df["CODE"].astype("string").tolist()
)

original_description_preserved = (
    procedure_g["ORIGINAL_DESCRIPTION"].astype("string").tolist()
    ==
    source_df["ORIGINAL_DESCRIPTION"].astype("string").tolist()
    if "ORIGINAL_DESCRIPTION" in source_df.columns
    else
    procedure_g["ORIGINAL_DESCRIPTION"].astype("string").tolist()
    ==
    source_df["DESCRIPTION"].astype("string").tolist()
)

print("\nORIGINAL VALUES")
print("-" * 70)
print(
    f"Original CODE preserved: "
    f"{original_code_preserved}"
)
print(
    f"Original DESCRIPTION preserved: "
    f"{original_description_preserved}"
)

if not original_code_preserved:
    raise ValueError("Original CODE was not preserved.")

if not original_description_preserved:
    raise ValueError(
        "Original DESCRIPTION was not preserved."
    )


# ============================================================================
# 13. CANONICALIZATION IMPACT
# ============================================================================

procedure_g["DESCRIPTION_STANDARDIZED_FLAG"] = (
    procedure_g["ORIGINAL_DESCRIPTION"].astype("string")
    !=
    procedure_g["CANONICAL_DESCRIPTION"].astype("string")
)

standardized_records = (
    procedure_g["DESCRIPTION_STANDARDIZED_FLAG"].sum()
)

unchanged_records = (
    len(procedure_g) - standardized_records
)

print("\nCANONICALIZATION IMPACT")
print("-" * 70)
print(f"Records standardized: {standardized_records:,}")
print(f"Records unchanged: {unchanged_records:,}")
print(
    f"Standardized record share: "
    f"{standardized_records / len(procedure_g) * 100:.2f}%"
)


# ============================================================================
# 14. DESCRIPTION VARIANCE SUMMARY
# ============================================================================

description_variance_summary = (
    procedure_g
    .groupby("_CODE_KEY")
    .agg(
        Unique_Original_Descriptions=(
            "ORIGINAL_DESCRIPTION",
            "nunique"
        ),
        Unique_Canonical_Descriptions=(
            "CANONICAL_DESCRIPTION",
            "nunique"
        ),
        Procedure_Count=(
            "_CODE_KEY",
            "size"
        )
    )
    .reset_index()
    .rename(columns={"_CODE_KEY": "CODE"})
)

description_variance_summary = (
    description_variance_summary[
        description_variance_summary[
            "Unique_Original_Descriptions"
        ] > 1
    ]
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
)

print("\nDESCRIPTION VARIANCE SUMMARY")
print("-" * 70)
print(
    description_variance_summary.to_string(
        index=False
    )
)


# ============================================================================
# 15. BASE_COST = 431 VALIDATION
# ============================================================================

cost_431_count = (
    procedure_g["BASE_COST"].eq(431).sum()
)

non_431_count = (
    procedure_g["BASE_COST"].ne(431).sum()
)

total_cost = (
    procedure_g["BASE_COST"].sum()
)

cost_431 = (
    procedure_g.loc[
        procedure_g["BASE_COST"] == 431,
        "BASE_COST"
    ].sum()
)

non_431_cost = (
    procedure_g.loc[
        procedure_g["BASE_COST"] != 431,
        "BASE_COST"
    ].sum()
)

print("\nBASE_COST = 431 VALIDATION")
print("-" * 70)
print(f"431 records: {cost_431_count:,}")
print(f"Non-431 records: {non_431_count:,}")
print(
    f"431 record share: "
    f"{cost_431_count / len(procedure_g) * 100:.2f}%"
)
print(f"Total procedure cost: {total_cost:,.2f}")
print(f"431 cost: {cost_431:,.2f}")
print(f"Non-431 cost: {non_431_cost:,.2f}")
print(
    f"431 cost share: "
    f"{cost_431 / total_cost * 100:.2f}%"
)


# ============================================================================
# 16. PROCEDURE CODE SUMMARY
# ============================================================================

procedure_code_summary = (
    procedure_g
    .groupby(
        ["_CODE_KEY", "CANONICAL_DESCRIPTION"],
        dropna=False
    )
    .agg(
        Procedure_Count=("_CODE_KEY", "size"),
        Unique_Patients=("PATIENT", "nunique"),
        Unique_Encounters=("ENCOUNTER", "nunique"),
        Total_Cost=("BASE_COST", "sum"),
        Average_Cost=("BASE_COST", "mean"),
        Median_Cost=("BASE_COST", "median"),
        Cost_431_Count=(
            "BASE_COST",
            lambda x: (x == 431).sum()
        ),
        Non_431_Count=(
            "BASE_COST",
            lambda x: (x != 431).sum()
        )
    )
    .reset_index()
    .rename(columns={"_CODE_KEY": "CODE"})
)

procedure_code_summary["Procedures_Per_Patient"] = (
    procedure_code_summary["Procedure_Count"]
    /
    procedure_code_summary["Unique_Patients"].replace(
        0, np.nan
    )
)

procedure_code_summary["Cost_Per_Patient"] = (
    procedure_code_summary["Total_Cost"]
    /
    procedure_code_summary["Unique_Patients"].replace(
        0, np.nan
    )
)

procedure_code_summary["Cost_431_Share"] = (
    procedure_code_summary["Cost_431_Count"]
    /
    procedure_code_summary["Procedure_Count"].replace(
        0, np.nan
    )
    * 100
)

procedure_code_summary["Non_431_Cost"] = (
    procedure_code_summary["Total_Cost"]
    -
    (
        procedure_code_summary["Cost_431_Count"]
        * 431
    )
)


# ============================================================================
# 17. CLEAN INTERNAL COLUMN
# ============================================================================

procedure_g = procedure_g.drop(
    columns=["_CODE_KEY"]
)


# ============================================================================
# 18. SUMMARY DATASET
# ============================================================================

procedure_g_summary = pd.DataFrame({
    "Metric": [
        "Total procedure records",
        "Unique procedure codes",
        "Unique original descriptions",
        "Unique canonical descriptions",
        "Codes with original description variance",
        "Codes with multiple canonical descriptions",
        "Records standardized",
        "Records with BASE_COST = 431",
        "Non-431 records",
        "Total procedure cost",
        "431 cost",
        "Non-431 cost",
        "431 record share (%)",
        "431 cost share (%)",
        "Missing patients",
        "Missing encounters"
    ],
    "Value": [
        len(procedure_g),
        procedure_g["CODE"].nunique(),
        procedure_g["ORIGINAL_DESCRIPTION"].nunique(),
        procedure_g["CANONICAL_DESCRIPTION"].nunique(),
        len(description_variance_summary),
        len(codes_with_multiple_canonical),
        standardized_records,
        cost_431_count,
        non_431_count,
        total_cost,
        cost_431,
        non_431_cost,
        cost_431_count / len(procedure_g) * 100,
        cost_431 / total_cost * 100,
        procedure_g["PATIENT"].isna().sum(),
        procedure_g["ENCOUNTER"].isna().sum()
    ]
})


# ============================================================================
# 19. FINAL VALIDATION
# ============================================================================

validation = pd.DataFrame({
    "Validation": [
        "Record count preserved",
        "Original CODE preserved",
        "Original DESCRIPTION preserved",
        "Canonical description available",
        "Exactly one canonical description per CODE",
        "431 flag available",
        "Non-431 cost available",
        "Procedure-level summary created",
        "No records deleted"
    ],
    "Result": [
        record_count_preserved,
        original_code_preserved,
        original_description_preserved,
        missing_canonical == 0 and blank_canonical == 0,
        len(codes_with_multiple_canonical) == 0,
        cost_431_count > 0,
        non_431_count > 0,
        len(procedure_code_summary) > 0,
        len(procedure_g) == len(source_df)
    ]
})

print("\nFINAL VALIDATION")
print("-" * 70)
print(validation.to_string(index=False))

if not validation["Result"].all():
    raise ValueError(
        "STEP 4.18G validation failed."
    )


# ============================================================================
# 20. EXPORT DATASETS TO GLOBAL KERNEL
# ============================================================================

canonical_mapping = pd.DataFrame(
    list(full_canonical_mapping.items()),
    columns=["CODE", "CANONICAL_DESCRIPTION"]
)

procedure_g_validation = validation.copy()


# ============================================================================
# 21. FINAL OUTPUT
# ============================================================================

print("\n" + "=" * 70)
print("STEP 4.18G COMPLETE")
print("=" * 70)

print(
    f"Total procedure records: "
    f"{len(procedure_g):,}"
)

print(
    f"Unique procedure codes: "
    f"{procedure_g['CODE'].nunique():,}"
)

print(
    f"Unique original descriptions: "
    f"{procedure_g['ORIGINAL_DESCRIPTION'].nunique():,}"
)

print(
    f"Unique canonical descriptions: "
    f"{procedure_g['CANONICAL_DESCRIPTION'].nunique():,}"
)

print(
    "Codes with original description variance: "
    f"{len(description_variance_summary):,}"
)

print(
    "Codes with multiple canonical descriptions: "
    f"{len(codes_with_multiple_canonical):,}"
)

print(
    f"Records standardized: "
    f"{standardized_records:,}"
)

print(
    f"BASE_COST = 431 records: "
    f"{cost_431_count:,}"
)

print(
    f"431 record share: "
    f"{cost_431_count / len(procedure_g) * 100:.2f}%"
)

print(
    f"Total procedure cost: "
    f"{total_cost:,.2f}"
)

print(
    f"Non-431 procedure cost: "
    f"{non_431_cost:,.2f}"
)

print("\nANALYTICAL DATASETS CREATED:")
print("  - procedure_g")
print("  - procedure_g_summary")
print("  - procedure_code_summary")
print("  - description_variance_summary")
print("  - canonical_mapping")
print("  - procedure_g_validation")

print("\nSTATUS: PASS")
print("=" * 70)

======================================================================
STEP 4.18G — PROCEDURE CODE-LEVEL CANONICALIZATION &
             FINAL ANALYTICAL READINESS
======================================================================

SOURCE DATA DISCOVERY
----------------------------------------------------------------------
Using source dataset: procedure_analysis
Source records: 47,701

SOURCE DATA CHECK
----------------------------------------------------------------------
STATUS: PASS
Procedure records available: 47,701

ORIGINAL VALUE PRESERVATION
----------------------------------------------------------------------
ORIGINAL_CODE available: True
ORIGINAL_DESCRIPTION available: True

EXPLICIT CANONICAL MAPPING
----------------------------------------------------------------------
5880005 → Physical examination
171207006 → Depression screening
399208008 → Plain chest X-ray
90226004 → Cytopathology procedure - preparation of smear - genital source

CANONICAL DESCRIPTION QUALITY
----------------------------------------------------------------------
Missing canonical descriptions: 0
Blank canonical descriptions: 0
STATUS: PASS

CODE → CANONICAL DESCRIPTION VALIDATION
----------------------------------------------------------------------
Unique procedure codes: 157
Codes with multiple canonical descriptions: 0
Every CODE has exactly one canonical description: True

KNOWN VARIANT CODE VALIDATION
----------------------------------------------------------------------

CODE: 5880005
Records: 308
Expected: Physical examination
Actual: ['Physical examination']

CODE: 171207006
Records: 3,804
Expected: Depression screening
Actual: ['Depression screening']

CODE: 399208008
Records: 90
Expected: Plain chest X-ray
Actual: ['Plain chest X-ray']

CODE: 90226004
Records: 258
Expected: Cytopathology procedure - preparation of smear - genital source
Actual: ['Cytopathology procedure - preparation of smear - genital source']

RECORD PRESERVATION
----------------------------------------------------------------------
Source records: 47,701
Analytical records: 47,701
Record count preserved: True

ORIGINAL VALUES
----------------------------------------------------------------------
Original CODE preserved: True
Original DESCRIPTION preserved: True

CANONICALIZATION IMPACT
----------------------------------------------------------------------
Records standardized: 4,231
Records unchanged: 43,470
Standardized record share: 8.87%

DESCRIPTION VARIANCE SUMMARY
----------------------------------------------------------------------
     CODE  Unique_Original_Descriptions  Unique_Canonical_Descriptions  Procedure_Count
171207006                             2                              1             3804
  5880005                             4                              1              308
 90226004                             2                              1              258
399208008                             2                              1               90

BASE_COST = 431 VALIDATION
----------------------------------------------------------------------
431 records: 30,988
Non-431 records: 16,713
431 record share: 64.96%
Total procedure cost: 105,517,711.00
431 cost: 13,355,828.00
Non-431 cost: 92,161,883.00
431 cost share: 12.66%

FINAL VALIDATION
----------------------------------------------------------------------
                                Validation  Result
                    Record count preserved    True
                   Original CODE preserved    True
            Original DESCRIPTION preserved    True
           Canonical description available    True
Exactly one canonical description per CODE    True
                        431 flag available    True
                    Non-431 cost available    True
           Procedure-level summary created    True
                        No records deleted    True

======================================================================
STEP 4.18G COMPLETE
======================================================================
Total procedure records: 47,701
Unique procedure codes: 157
Unique original descriptions: 163
Unique canonical descriptions: 157
Codes with original description variance: 4
Codes with multiple canonical descriptions: 0
Records standardized: 4,231
BASE_COST = 431 records: 30,988
431 record share: 64.96%
Total procedure cost: 105,517,711.00
Non-431 procedure cost: 92,161,883.00

ANALYTICAL DATASETS CREATED:
  - procedure_g
  - procedure_g_summary
  - procedure_code_summary
  - description_variance_summary
  - canonical_mapping
  - procedure_g_validation

STATUS: PASS
======================================================================

In [137]:
# ============================================================================
# STEP 4.18H — PROCEDURE EXECUTIVE ANALYTICS, COST CONCENTRATION &
#              UTILIZATION PRIORITIZATION
# ============================================================================
#
# SOURCE:
#   procedure_g
#
# PURPOSE:
#   Build the final procedure-level analytical and executive insight layer
#   after CODE → canonical description standardization.
#
# DESIGN PRINCIPLES:
#   - Preserve all 47,701 procedure records.
#   - Use procedure_g as the authoritative analytical source.
#   - Do not overwrite ORIGINAL_CODE or ORIGINAL_DESCRIPTION.
#   - Do not re-standardize canonical descriptions.
#   - Separate BASE_COST = 431 from economically meaningful non-431 cost.
#   - Produce cost, utilization, patient-burden and priority analytics.
#   - Create reusable datasets for downstream dashboards/reporting.
#
# ============================================================================

import pandas as pd
import numpy as np

print("=" * 70)
print("STEP 4.18H — PROCEDURE EXECUTIVE ANALYTICS, COST CONCENTRATION &")
print("             UTILIZATION PRIORITIZATION")
print("=" * 70)


# ============================================================================
# 1. SOURCE DATA DISCOVERY
# ============================================================================

print("\nSOURCE DATA DISCOVERY")
print("-" * 70)

if "procedure_g" not in globals():
    raise NameError(
        "procedure_g is not available. "
        "Please run STEP 4.18G successfully before running STEP 4.18H."
    )

source_df = procedure_g.copy()

print("Using source dataset: procedure_g")
print(f"Source records: {len(source_df):,}")


# ============================================================================
# 2. REQUIRED COLUMN VALIDATION
# ============================================================================

required_columns = [
    "CODE",
    "DESCRIPTION",
    "ORIGINAL_CODE",
    "ORIGINAL_DESCRIPTION",
    "CANONICAL_DESCRIPTION",
    "BASE_COST",
    "PATIENT",
    "ENCOUNTER"
]

missing_columns = [
    col for col in required_columns
    if col not in source_df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns in procedure_g: {missing_columns}"
    )

print("\nSOURCE DATA CHECK")
print("-" * 70)
print("STATUS: PASS")
print(f"Procedure records available: {len(source_df):,}")


# ============================================================================
# 3. CREATE ANALYTICAL COPY
# ============================================================================

procedure_h = source_df.copy()


# ============================================================================
# 4. BASIC DATA VALIDATION
# ============================================================================

print("\nANALYTICAL DATASET VALIDATION")
print("-" * 70)

if len(procedure_h) != 47701:
    print(
        f"WARNING: Expected 47,701 records but found "
        f"{len(procedure_h):,}."
    )

unique_codes = procedure_h["CODE"].nunique()
unique_canonical = procedure_h["CANONICAL_DESCRIPTION"].nunique()

print(f"Records: {len(procedure_h):,}")
print(f"Unique procedure codes: {unique_codes:,}")
print(f"Unique canonical descriptions: {unique_canonical:,}")


# ============================================================================
# 5. CANONICALIZATION INTEGRITY CHECK
# ============================================================================

canonical_check = (
    procedure_h
    .groupby("CODE")["CANONICAL_DESCRIPTION"]
    .nunique()
)

multi_canonical_codes = (
    canonical_check[canonical_check > 1]
)

missing_canonical = (
    procedure_h["CANONICAL_DESCRIPTION"].isna().sum()
)

blank_canonical = (
    procedure_h["CANONICAL_DESCRIPTION"]
    .astype("string")
    .str.strip()
    .eq("")
    .sum()
)

print("\nCANONICALIZATION INTEGRITY")
print("-" * 70)
print(f"Missing canonical descriptions: {missing_canonical:,}")
print(f"Blank canonical descriptions: {blank_canonical:,}")
print(
    "Codes with multiple canonical descriptions: "
    f"{len(multi_canonical_codes):,}"
)

if missing_canonical > 0:
    raise ValueError(
        "Missing canonical descriptions detected."
    )

if blank_canonical > 0:
    raise ValueError(
        "Blank canonical descriptions detected."
    )

if len(multi_canonical_codes) > 0:
    raise ValueError(
        "Some procedure codes still have multiple canonical descriptions."
    )

print("Canonicalization integrity: PASS")


# ============================================================================
# 6. BASE COST SEGMENTATION
# ============================================================================

procedure_h["IS_431_COST"] = (
    procedure_h["BASE_COST"] == 431
)

procedure_h["IS_NON_431_COST"] = (
    procedure_h["BASE_COST"] != 431
)

procedure_h["NON_431_COST"] = np.where(
    procedure_h["IS_NON_431_COST"],
    procedure_h["BASE_COST"],
    0
)

procedure_h["COST_431_COMPONENT"] = np.where(
    procedure_h["IS_431_COST"],
    procedure_h["BASE_COST"],
    0
)


# ============================================================================
# 7. TOTAL COST METRICS
# ============================================================================

total_records = len(procedure_h)

total_cost = procedure_h["BASE_COST"].sum()

cost_431 = procedure_h["COST_431_COMPONENT"].sum()

non_431_cost = procedure_h["NON_431_COST"].sum()

records_431 = procedure_h["IS_431_COST"].sum()

records_non_431 = procedure_h["IS_NON_431_COST"].sum()

record_431_share = (
    records_431 / total_records * 100
)

cost_431_share = (
    cost_431 / total_cost * 100
)

non_431_cost_share = (
    non_431_cost / total_cost * 100
)

print("\nBASE_COST SEGMENTATION")
print("-" * 70)
print(f"431 records: {records_431:,}")
print(f"Non-431 records: {records_non_431:,}")
print(f"431 record share: {record_431_share:.2f}%")
print(f"Total procedure cost: {total_cost:,.2f}")
print(f"431 cost: {cost_431:,.2f}")
print(f"Non-431 cost: {non_431_cost:,.2f}")
print(f"431 cost share: {cost_431_share:.2f}%")
print(f"Non-431 cost share: {non_431_cost_share:.2f}%")


# ============================================================================
# 8. PROCEDURE-LEVEL EXECUTIVE SUMMARY
# ============================================================================

procedure_summary = (
    procedure_h
    .groupby(
        ["CODE", "CANONICAL_DESCRIPTION"],
        dropna=False
    )
    .agg(
        Procedure_Count=("CODE", "size"),
        Unique_Patients=("PATIENT", "nunique"),
        Unique_Encounters=("ENCOUNTER", "nunique"),

        Total_Procedure_Cost=("BASE_COST", "sum"),

        Non_431_Count=("IS_NON_431_COST", "sum"),

        Non_431_Total_Cost=("NON_431_COST", "sum"),

        Average_Procedure_Cost=("BASE_COST", "mean"),

        Median_Procedure_Cost=("BASE_COST", "median"),

        Cost_431_Count=("IS_431_COST", "sum"),

        Maximum_Procedure_Cost=("BASE_COST", "max")
    )
    .reset_index()
)

procedure_summary["Procedures_Per_Patient"] = (
    procedure_summary["Procedure_Count"]
    /
    procedure_summary["Unique_Patients"].replace(0, np.nan)
)

procedure_summary["Procedures_Per_Encounter"] = (
    procedure_summary["Procedure_Count"]
    /
    procedure_summary["Unique_Encounters"].replace(0, np.nan)
)

procedure_summary["Cost_Per_Patient"] = (
    procedure_summary["Total_Procedure_Cost"]
    /
    procedure_summary["Unique_Patients"].replace(0, np.nan)
)

procedure_summary["Non_431_Cost_Per_Patient"] = (
    procedure_summary["Non_431_Total_Cost"]
    /
    procedure_summary["Unique_Patients"].replace(0, np.nan)
)

procedure_summary["Cost_431_Share"] = (
    procedure_summary["Cost_431_Count"]
    /
    procedure_summary["Procedure_Count"].replace(0, np.nan)
    * 100
)

procedure_summary["Non_431_Record_Share"] = (
    procedure_summary["Non_431_Count"]
    /
    procedure_summary["Procedure_Count"].replace(0, np.nan)
    * 100
)


# ============================================================================
# 9. COST RANKING
# ============================================================================

procedure_summary["Cost_Rank"] = (
    procedure_summary["Total_Procedure_Cost"]
    .rank(
        method="min",
        ascending=False
    )
)

procedure_summary["Non_431_Cost_Rank"] = (
    procedure_summary["Non_431_Total_Cost"]
    .rank(
        method="min",
        ascending=False
    )
)

procedure_summary["Utilization_Rank"] = (
    procedure_summary["Procedure_Count"]
    .rank(
        method="min",
        ascending=False
    )
)

procedure_summary["Cost_Per_Patient_Rank"] = (
    procedure_summary["Cost_Per_Patient"]
    .rank(
        method="min",
        ascending=False
    )
)


# ============================================================================
# 10. TOP PROCEDURES BY TOTAL COST
# ============================================================================

top_cost_procedures = (
    procedure_summary
    .sort_values(
        "Total_Procedure_Cost",
        ascending=False
    )
    .head(20)
    .copy()
)

print("\nTOP 20 PROCEDURES BY TOTAL COST")
print("-" * 70)

print(
    top_cost_procedures[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Total_Procedure_Cost",
            "Unique_Patients",
            "Cost_Per_Patient",
            "Cost_431_Share"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 11. TOP PROCEDURES BY NON-431 COST
# ============================================================================

top_non_431_cost = (
    procedure_summary
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
    .head(20)
    .copy()
)

print("\nTOP 20 PROCEDURES BY NON-431 COST")
print("-" * 70)

print(
    top_non_431_cost[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Non_431_Count",
            "Non_431_Total_Cost",
            "Average_Procedure_Cost",
            "Unique_Patients",
            "Cost_Per_Patient",
            "Cost_431_Share"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 12. TOP PROCEDURES BY UTILIZATION
# ============================================================================

top_utilization = (
    procedure_summary
    .sort_values(
        [
            "Procedure_Count",
            "Unique_Patients"
        ],
        ascending=[False, False]
    )
    .head(20)
    .copy()
)

print("\nTOP 20 PROCEDURES BY UTILIZATION")
print("-" * 70)

print(
    top_utilization[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Unique_Encounters",
            "Procedures_Per_Patient",
            "Procedures_Per_Encounter",
            "Total_Procedure_Cost",
            "Cost_431_Share"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 13. TOP PROCEDURES BY COST PER PATIENT
# ============================================================================

top_cost_per_patient = (
    procedure_summary[
        procedure_summary["Unique_Patients"] > 0
    ]
    .sort_values(
        "Cost_Per_Patient",
        ascending=False
    )
    .head(20)
    .copy()
)

print("\nTOP 20 PROCEDURES BY COST PER PATIENT")
print("-" * 70)

print(
    top_cost_per_patient[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Total_Procedure_Cost",
            "Cost_Per_Patient",
            "Procedures_Per_Patient",
            "Cost_431_Share"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 14. TOP REPEAT-UTILIZATION PROCEDURES
# ============================================================================

high_repeat_utilization = (
    procedure_summary[
        procedure_summary["Unique_Patients"] > 0
    ]
    .sort_values(
        "Procedures_Per_Patient",
        ascending=False
    )
    .head(20)
    .copy()
)

print("\nTOP 20 PROCEDURES BY PROCEDURES PER PATIENT")
print("-" * 70)

print(
    high_repeat_utilization[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Procedures_Per_Patient",
            "Unique_Encounters",
            "Total_Procedure_Cost",
            "Cost_431_Share"
        ]
    ].to_string(index=False)
)


# ============================================================================
# 15. COST CONCENTRATION
# ============================================================================

cost_ranked = (
    procedure_summary
    .sort_values(
        "Total_Procedure_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)

non_431_cost_ranked = (
    procedure_summary
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)

utilization_ranked = (
    procedure_summary
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .reset_index(drop=True)
)


def concentration_share(df, column, n, denominator):
    if denominator == 0:
        return 0.0

    return (
        df[column]
        .head(n)
        .sum()
        /
        denominator
        * 100
    )


top_5_cost_share = concentration_share(
    cost_ranked,
    "Total_Procedure_Cost",
    5,
    total_cost
)

top_10_cost_share = concentration_share(
    cost_ranked,
    "Total_Procedure_Cost",
    10,
    total_cost
)

top_20_cost_share = concentration_share(
    cost_ranked,
    "Total_Procedure_Cost",
    20,
    total_cost
)

top_5_non_431_share = concentration_share(
    non_431_cost_ranked,
    "Non_431_Total_Cost",
    5,
    non_431_cost
)

top_10_non_431_share = concentration_share(
    non_431_cost_ranked,
    "Non_431_Total_Cost",
    10,
    non_431_cost
)

top_20_non_431_share = concentration_share(
    non_431_cost_ranked,
    "Non_431_Total_Cost",
    20,
    non_431_cost
)


# ============================================================================
# 16. UTILIZATION CONCENTRATION
# ============================================================================

top_5_volume_share = (
    utilization_ranked["Procedure_Count"]
    .head(5)
    .sum()
    /
    total_records
    * 100
)

top_10_volume_share = (
    utilization_ranked["Procedure_Count"]
    .head(10)
    .sum()
    /
    total_records
    * 100
)

top_20_volume_share = (
    utilization_ranked["Procedure_Count"]
    .head(20)
    .sum()
    /
    total_records
    * 100
)

print("\nPROCEDURE COST CONCENTRATION")
print("-" * 70)
print(f"Top 5 total-cost share: {top_5_cost_share:.2f}%")
print(f"Top 10 total-cost share: {top_10_cost_share:.2f}%")
print(f"Top 20 total-cost share: {top_20_cost_share:.2f}%")
print(f"Top 5 non-431 cost share: {top_5_non_431_share:.2f}%")
print(f"Top 10 non-431 cost share: {top_10_non_431_share:.2f}%")
print(f"Top 20 non-431 cost share: {top_20_non_431_share:.2f}%")

print("\nPROCEDURE UTILIZATION CONCENTRATION")
print("-" * 70)
print(f"Top 5 volume share: {top_5_volume_share:.2f}%")
print(f"Top 10 volume share: {top_10_volume_share:.2f}%")
print(f"Top 20 volume share: {top_20_volume_share:.2f}%")


# ============================================================================
# 17. ANALYTICAL THRESHOLDS
# ============================================================================
#
# Thresholds are derived from the procedure-level distribution rather than
# arbitrary absolute values.
# ============================================================================

cost_threshold = (
    procedure_summary["Non_431_Total_Cost"]
    .quantile(0.75)
)

utilization_threshold = (
    procedure_summary["Procedure_Count"]
    .quantile(0.75)
)

cost_per_patient_threshold = (
    procedure_summary["Cost_Per_Patient"]
    .replace([np.inf, -np.inf], np.nan)
    .dropna()
    .quantile(0.75)
)

repeat_utilization_threshold = (
    procedure_summary["Procedures_Per_Patient"]
    .replace([np.inf, -np.inf], np.nan)
    .dropna()
    .quantile(0.75)
)

print("\nANALYTICAL THRESHOLDS")
print("-" * 70)
print(
    f"High non-431 cost threshold: "
    f"{cost_threshold:,.2f}"
)
print(
    f"High utilization threshold: "
    f"{utilization_threshold:,.2f}"
)
print(
    f"High cost-per-patient threshold: "
    f"{cost_per_patient_threshold:,.2f}"
)
print(
    f"High repeat-utilization threshold: "
    f"{repeat_utilization_threshold:,.2f}"
)


# ============================================================================
# 18. COST / UTILIZATION SEGMENTATION
# ============================================================================

def assign_priority(row):

    high_cost = (
        row["Non_431_Total_Cost"]
        >= cost_threshold
    )

    high_utilization = (
        row["Procedure_Count"]
        >= utilization_threshold
    )

    cost_431_dominated = (
        row["Cost_431_Share"] >= 75
    )

    if cost_431_dominated:
        return "PRIORITY 4 — 431 COST DOMINATED"

    if high_cost and high_utilization:
        return "PRIORITY 1 — HIGH COST / HIGH UTILIZATION"

    if high_cost and not high_utilization:
        return "PRIORITY 2 — HIGH COST / LOWER UTILIZATION"

    if not high_cost and high_utilization:
        return "PRIORITY 3 — HIGH UTILIZATION / LOWER COST"

    return "STANDARD"


procedure_summary["Priority_Profile"] = (
    procedure_summary.apply(
        assign_priority,
        axis=1
    )
)


# ============================================================================
# 19. COST INTENSITY
# ============================================================================

def assign_cost_intensity(row):

    if row["Cost_431_Share"] >= 75:
        return "431_DOMINATED"

    if row["Non_431_Total_Cost"] >= (
        procedure_summary["Non_431_Total_Cost"]
        .quantile(0.99)
    ):
        return "EXTREME_NON_431_COST"

    if row["Non_431_Total_Cost"] >= (
        procedure_summary["Non_431_Total_Cost"]
        .quantile(0.90)
    ):
        return "HIGH_NON_431_COST"

    if row["Non_431_Total_Cost"] >= (
        procedure_summary["Non_431_Total_Cost"]
        .quantile(0.75)
    ):
        return "MODERATE_NON_431_COST"

    return "STANDARD_NON_431_COST"


procedure_summary["Cost_Intensity"] = (
    procedure_summary.apply(
        assign_cost_intensity,
        axis=1
    )
)


# ============================================================================
# 20. UTILIZATION INTENSITY
# ============================================================================

utilization_q75 = (
    procedure_summary["Procedure_Count"]
    .quantile(0.75)
)

utilization_q90 = (
    procedure_summary["Procedure_Count"]
    .quantile(0.90)
)

utilization_q99 = (
    procedure_summary["Procedure_Count"]
    .quantile(0.99)
)


def assign_utilization_intensity(row):

    value = row["Procedure_Count"]

    if value >= utilization_q99:
        return "EXTREME_UTILIZATION"

    if value >= utilization_q90:
        return "HIGH_UTILIZATION"

    if value >= utilization_q75:
        return "MODERATE_UTILIZATION"

    return "STANDARD_UTILIZATION"


procedure_summary["Utilization_Intensity"] = (
    procedure_summary.apply(
        assign_utilization_intensity,
        axis=1
    )
)


# ============================================================================
# 21. HIGH COST / HIGH UTILIZATION
# ============================================================================

high_cost_high_utilization = (
    procedure_summary[
        (
            procedure_summary["Non_431_Total_Cost"]
            >= cost_threshold
        )
        &
        (
            procedure_summary["Procedure_Count"]
            >= utilization_threshold
        )
        &
        (
            procedure_summary["Cost_431_Share"] < 75
        )
    ]
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
    .copy()
)

print("\nHIGH COST / HIGH UTILIZATION PROCEDURES")
print("-" * 70)

print(
    high_cost_high_utilization[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Non_431_Total_Cost",
            "Unique_Patients",
            "Cost_Per_Patient",
            "Procedures_Per_Patient",
            "Cost_431_Share"
        ]
    ].head(20).to_string(index=False)
)


# ============================================================================
# 22. HIGH COST / LOW UTILIZATION
# ============================================================================

high_cost_low_utilization = (
    procedure_summary[
        (
            procedure_summary["Non_431_Total_Cost"]
            >= cost_threshold
        )
        &
        (
            procedure_summary["Procedure_Count"]
            < utilization_threshold
        )
        &
        (
            procedure_summary["Cost_431_Share"] < 75
        )
    ]
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
    .copy()
)

print("\nHIGH COST / LOWER UTILIZATION PROCEDURES")
print("-" * 70)

print(
    high_cost_low_utilization[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Non_431_Total_Cost",
            "Average_Procedure_Cost",
            "Cost_Per_Patient",
            "Cost_431_Share"
        ]
    ].head(20).to_string(index=False)
)


# ============================================================================
# 23. HIGH UTILIZATION / LOWER COST
# ============================================================================

high_utilization_low_cost = (
    procedure_summary[
        (
            procedure_summary["Procedure_Count"]
            >= utilization_threshold
        )
        &
        (
            procedure_summary["Non_431_Total_Cost"]
            < cost_threshold
        )
    ]
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .copy()
)

print("\nHIGH UTILIZATION / LOWER NON-431 COST PROCEDURES")
print("-" * 70)

print(
    high_utilization_low_cost[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Procedures_Per_Patient",
            "Total_Procedure_Cost",
            "Non_431_Total_Cost",
            "Cost_431_Share"
        ]
    ].head(20).to_string(index=False)
)


# ============================================================================
# 24. 431-DOMINATED PROCEDURES
# ============================================================================

procedures_431_dominated = (
    procedure_summary[
        procedure_summary["Cost_431_Share"] >= 75
    ]
    .sort_values(
        [
            "Procedure_Count",
            "Total_Procedure_Cost"
        ],
        ascending=[False, False]
    )
    .copy()
)

print("\n431-DOMINATED PROCEDURES")
print("-" * 70)

print(
    procedures_431_dominated[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Total_Procedure_Cost",
            "Cost_431_Share"
        ]
    ].head(20).to_string(index=False)
)


# ============================================================================
# 25. HIGH COST-PER-PATIENT PROCEDURES
# ============================================================================

high_cost_per_patient = (
    procedure_summary[
        (
            procedure_summary["Cost_Per_Patient"]
            >= cost_per_patient_threshold
        )
        &
        (
            procedure_summary["Unique_Patients"] > 0
        )
    ]
    .sort_values(
        "Cost_Per_Patient",
        ascending=False
    )
    .copy()
)

print("\nHIGH COST-PER-PATIENT PROCEDURES")
print("-" * 70)

print(
    high_cost_per_patient[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Total_Procedure_Cost",
            "Cost_Per_Patient",
            "Procedures_Per_Patient",
            "Cost_431_Share"
        ]
    ].head(20).to_string(index=False)
)


# ============================================================================
# 26. HIGH REPEAT UTILIZATION
# ============================================================================

high_repeat_utilization = (
    procedure_summary[
        (
            procedure_summary["Procedures_Per_Patient"]
            >= repeat_utilization_threshold
        )
        &
        (
            procedure_summary["Unique_Patients"] > 0
        )
    ]
    .sort_values(
        "Procedures_Per_Patient",
        ascending=False
    )
    .copy()
)

print("\nHIGH REPEAT UTILIZATION")
print("-" * 70)

print(
    high_repeat_utilization[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Procedures_Per_Patient",
            "Unique_Encounters",
            "Total_Procedure_Cost",
            "Cost_431_Share"
        ]
    ].head(20).to_string(index=False)
)


# ============================================================================
# 27. PRIORITY DISTRIBUTION
# ============================================================================

priority_distribution = (
    procedure_summary
    .groupby("Priority_Profile")
    .size()
    .reset_index(
        name="Procedure_Group_Count"
    )
    .sort_values(
        "Procedure_Group_Count",
        ascending=False
    )
)

priority_distribution["Group_Share_%"] = (
    priority_distribution["Procedure_Group_Count"]
    /
    len(procedure_summary)
    * 100
)

print("\nPROCEDURE PRIORITY DISTRIBUTION")
print("-" * 70)
print(
    priority_distribution.to_string(
        index=False
    )
)


# ============================================================================
# 28. COST INTENSITY DISTRIBUTION
# ============================================================================

cost_intensity_distribution = (
    procedure_summary
    .groupby("Cost_Intensity")
    .size()
    .reset_index(
        name="Procedure_Group_Count"
    )
    .sort_values(
        "Procedure_Group_Count",
        ascending=False
    )
)

cost_intensity_distribution["Group_Share_%"] = (
    cost_intensity_distribution["Procedure_Group_Count"]
    /
    len(procedure_summary)
    * 100
)

print("\nCOST INTENSITY DISTRIBUTION")
print("-" * 70)
print(
    cost_intensity_distribution.to_string(
        index=False
    )
)


# ============================================================================
# 29. UTILIZATION INTENSITY DISTRIBUTION
# ============================================================================

utilization_intensity_distribution = (
    procedure_summary
    .groupby("Utilization_Intensity")
    .size()
    .reset_index(
        name="Procedure_Group_Count"
    )
    .sort_values(
        "Procedure_Group_Count",
        ascending=False
    )
)

utilization_intensity_distribution["Group_Share_%"] = (
    utilization_intensity_distribution["Procedure_Group_Count"]
    /
    len(procedure_summary)
    * 100
)

print("\nUTILIZATION INTENSITY DISTRIBUTION")
print("-" * 70)
print(
    utilization_intensity_distribution.to_string(
        index=False
    )
)


# ============================================================================
# 30. EXECUTIVE INSIGHT METRICS
# ============================================================================

priority_1_count = (
    (
        procedure_summary["Priority_Profile"]
        ==
        "PRIORITY 1 — HIGH COST / HIGH UTILIZATION"
    )
    .sum()
)

priority_2_count = (
    (
        procedure_summary["Priority_Profile"]
        ==
        "PRIORITY 2 — HIGH COST / LOWER UTILIZATION"
    )
    .sum()
)

priority_3_count = (
    (
        procedure_summary["Priority_Profile"]
        ==
        "PRIORITY 3 — HIGH UTILIZATION / LOWER COST"
    )
    .sum()
)

priority_4_count = (
    (
        procedure_summary["Priority_Profile"]
        ==
        "PRIORITY 4 — 431 COST DOMINATED"
    )
    .sum()
)

standard_count = (
    (
        procedure_summary["Priority_Profile"]
        ==
        "STANDARD"
    )
    .sum()
)


# ============================================================================
# 31. EXECUTIVE INSIGHT TABLE
# ============================================================================

procedure_insight_metrics = pd.DataFrame({
    "Metric": [
        "Total procedure records",
        "Unique procedure codes",
        "Unique canonical descriptions",
        "Total observed procedure cost",
        "Total non-431 procedure cost",
        "431 record count",
        "Non-431 record count",
        "431 record share (%)",
        "431 cost share (%)",
        "Non-431 cost share (%)",

        "Top 5 total-cost concentration (%)",
        "Top 10 total-cost concentration (%)",
        "Top 20 total-cost concentration (%)",

        "Top 5 non-431 cost concentration (%)",
        "Top 10 non-431 cost concentration (%)",
        "Top 20 non-431 cost concentration (%)",

        "Top 5 utilization concentration (%)",
        "Top 10 utilization concentration (%)",
        "Top 20 utilization concentration (%)",

        "Priority 1 groups",
        "Priority 2 groups",
        "Priority 3 groups",
        "Priority 4 groups",
        "Standard groups",

        "High cost-per-patient groups",
        "High repeat-utilization groups"
    ],
    "Value": [
        total_records,
        unique_codes,
        unique_canonical,
        total_cost,
        non_431_cost,
        records_431,
        records_non_431,
        record_431_share,
        cost_431_share,
        non_431_cost_share,

        top_5_cost_share,
        top_10_cost_share,
        top_20_cost_share,

        top_5_non_431_share,
        top_10_non_431_share,
        top_20_non_431_share,

        top_5_volume_share,
        top_10_volume_share,
        top_20_volume_share,

        priority_1_count,
        priority_2_count,
        priority_3_count,
        priority_4_count,
        standard_count,

        len(high_cost_per_patient),
        len(high_repeat_utilization)
    ]
})


# ============================================================================
# 32. EXECUTIVE INSIGHT FLAGS
# ============================================================================

procedure_insight_summary = pd.DataFrame({
    "Insight_Category": [
        "Cost concentration",
        "Cost concentration",
        "Cost concentration",
        "Utilization concentration",
        "Utilization concentration",
        "Utilization concentration",
        "431 baseline",
        "431 baseline",
        "Priority",
        "Priority",
        "Priority",
        "Priority",
        "Repeat utilization"
    ],
    "Metric": [
        "Top 10 total-cost concentration",
        "Top 10 non-431 cost concentration",
        "Top 20 non-431 cost concentration",
        "Top 10 procedure volume concentration",
        "Top 20 procedure volume concentration",
        "Total procedure volume",
        "431 record share",
        "431 cost share",
        "Priority 1 groups",
        "Priority 2 groups",
        "Priority 3 groups",
        "431-dominated groups",
        "High repeat-utilization groups"
    ],
    "Value": [
        top_10_cost_share,
        top_10_non_431_share,
        top_20_non_431_share,
        top_10_volume_share,
        top_20_volume_share,
        total_records,
        record_431_share,
        cost_431_share,
        priority_1_count,
        priority_2_count,
        priority_3_count,
        priority_4_count,
        len(high_repeat_utilization)
    ]
})


# ============================================================================
# 33. PROCEDURE PRIORITY MATRIX
# ============================================================================

procedure_priority = (
    procedure_summary[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Unique_Encounters",
            "Total_Procedure_Cost",
            "Non_431_Total_Cost",
            "Average_Procedure_Cost",
            "Cost_Per_Patient",
            "Procedures_Per_Patient",
            "Cost_431_Share",
            "Cost_Intensity",
            "Utilization_Intensity",
            "Priority_Profile"
        ]
    ]
    .sort_values(
        [
            "Priority_Profile",
            "Non_431_Total_Cost",
            "Procedure_Count"
        ],
        ascending=[True, False, False]
    )
    .copy()
)


# ============================================================================
# 34. TOP NON-431 COST CONTRIBUTORS
# ============================================================================

high_cost_non431_procedures = (
    procedure_summary[
        procedure_summary["Non_431_Total_Cost"] > 0
    ]
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
    .head(50)
    .copy()
)


# ============================================================================
# 35. PATIENT BURDEN INSIGHT
# ============================================================================

patient_procedure_summary = (
    procedure_h
    .groupby("PATIENT")
    .agg(
        Procedure_Count=("CODE", "size"),
        Unique_Procedure_Codes=("CODE", "nunique"),
        Unique_Encounters=("ENCOUNTER", "nunique"),
        Total_Procedure_Cost=("BASE_COST", "sum"),
        Non_431_Procedure_Cost=("NON_431_COST", "sum"),
        Cost_431_Count=("IS_431_COST", "sum")
    )
    .reset_index()
)

patient_procedure_summary["Procedures_Per_Encounter"] = (
    patient_procedure_summary["Procedure_Count"]
    /
    patient_procedure_summary["Unique_Encounters"].replace(
        0,
        np.nan
    )
)

patient_procedure_summary["Non_431_Cost_Share"] = (
    patient_procedure_summary["Non_431_Procedure_Cost"]
    /
    patient_procedure_summary["Total_Procedure_Cost"].replace(
        0,
        np.nan
    )
    * 100
)

high_procedure_burden_patients = (
    patient_procedure_summary
    .sort_values(
        [
            "Non_431_Procedure_Cost",
            "Procedure_Count"
        ],
        ascending=[False, False]
    )
    .head(50)
    .copy()
)


# ============================================================================
# 36. PROCEDURE COST BAND
# ============================================================================

procedure_summary["Cost_Band"] = np.select(
    [
        procedure_summary["Cost_431_Share"] >= 75,

        (
            procedure_summary["Non_431_Total_Cost"]
            >= procedure_summary["Non_431_Total_Cost"]
            .quantile(0.99)
        ),

        (
            procedure_summary["Non_431_Total_Cost"]
            >= procedure_summary["Non_431_Total_Cost"]
            .quantile(0.95)
        ),

        (
            procedure_summary["Non_431_Total_Cost"]
            > 0
        )
    ],
    [
        "431 Cost Dominated",
        "Extreme Non-431 Cost",
        "High Non-431 Cost",
        "Standard Non-431 Cost"
    ],
    default="No Non-431 Cost"
)


# ============================================================================
# 37. FINAL DATASET CLEANING
# ============================================================================

# Ensure numerical columns are finite where mathematically appropriate.

for df in [
    procedure_summary,
    procedure_priority,
    high_cost_high_utilization,
    high_cost_low_utilization,
    high_utilization_low_cost,
    high_cost_per_patient,
    high_repeat_utilization
]:

    numeric_columns = df.select_dtypes(
        include=[np.number]
    ).columns

    for col in numeric_columns:
        df[col] = df[col].replace(
            [np.inf, -np.inf],
            np.nan
        )


# ============================================================================
# 38. FINAL VALIDATION
# ============================================================================

record_count_preserved = (
    len(procedure_h) == len(source_df)
)

original_code_preserved = (
    procedure_h["ORIGINAL_CODE"].astype("string").tolist()
    ==
    source_df["ORIGINAL_CODE"].astype("string").tolist()
)

original_description_preserved = (
    procedure_h["ORIGINAL_DESCRIPTION"].astype("string").tolist()
    ==
    source_df["ORIGINAL_DESCRIPTION"].astype("string").tolist()
)

canonical_available = (
    procedure_h["CANONICAL_DESCRIPTION"].notna().all()
)

canonical_unique_per_code = (
    len(multi_canonical_codes) == 0
)

procedure_summary_created = (
    len(procedure_summary) == unique_codes
)

priority_profile_created = (
    procedure_summary["Priority_Profile"].notna().all()
)

no_records_deleted = (
    len(procedure_h) == len(source_df)
)

validation = pd.DataFrame({
    "Validation": [
        "Record count preserved",
        "Original CODE preserved",
        "Original DESCRIPTION preserved",
        "Canonical description available",
        "One canonical description per CODE",
        "431 cost segmentation available",
        "Non-431 cost available",
        "Procedure-level summary created",
        "Priority profile created",
        "Patient-level procedure summary created",
        "Cost concentration calculated",
        "Utilization concentration calculated",
        "No records deleted"
    ],
    "Result": [
        record_count_preserved,
        original_code_preserved,
        original_description_preserved,
        canonical_available,
        canonical_unique_per_code,
        "IS_431_COST" in procedure_h.columns,
        "NON_431_COST" in procedure_h.columns,
        procedure_summary_created,
        priority_profile_created,
        len(patient_procedure_summary) > 0,
        top_10_cost_share >= 0,
        top_10_volume_share >= 0,
        no_records_deleted
    ]
})

print("\nFINAL VALIDATION")
print("-" * 70)
print(
    validation.to_string(index=False)
)

if not validation["Result"].all():
    raise ValueError(
        "STEP 4.18H validation failed."
    )


# ============================================================================
# 39. FINAL EXECUTIVE SUMMARY
# ============================================================================

print("\n" + "=" * 70)
print("STEP 4.18H COMPLETE")
print("=" * 70)

print(
    f"Total procedure records: "
    f"{total_records:,}"
)

print(
    f"Unique procedure codes: "
    f"{unique_codes:,}"
)

print(
    f"Unique canonical descriptions: "
    f"{unique_canonical:,}"
)

print(
    f"Total observed procedure cost: "
    f"{total_cost:,.2f}"
)

print(
    f"Total non-431 procedure cost: "
    f"{non_431_cost:,.2f}"
)

print(
    f"431 record share: "
    f"{record_431_share:.2f}%"
)

print(
    f"431 cost share: "
    f"{cost_431_share:.2f}%"
)

print(
    f"Top 10 total-cost concentration: "
    f"{top_10_cost_share:.2f}%"
)

print(
    f"Top 20 total-cost concentration: "
    f"{top_20_cost_share:.2f}%"
)

print(
    f"Top 10 non-431 cost concentration: "
    f"{top_10_non_431_share:.2f}%"
)

print(
    f"Top 20 non-431 cost concentration: "
    f"{top_20_non_431_share:.2f}%"
)

print(
    f"Top 10 procedure volume concentration: "
    f"{top_10_volume_share:.2f}%"
)

print(
    f"Top 20 procedure volume concentration: "
    f"{top_20_volume_share:.2f}%"
)

print(
    f"Priority 1 groups: "
    f"{priority_1_count}"
)

print(
    f"Priority 2 groups: "
    f"{priority_2_count}"
)

print(
    f"Priority 3 groups: "
    f"{priority_3_count}"
)

print(
    f"431-dominated groups: "
    f"{priority_4_count}"
)

print("\nANALYTICAL DATASETS CREATED:")
print("  - procedure_h")
print("  - procedure_summary")
print("  - top_cost_procedures")
print("  - top_non_431_cost")
print("  - top_utilization")
print("  - top_cost_per_patient")
print("  - high_repeat_utilization")
print("  - high_cost_high_utilization")
print("  - high_cost_low_utilization")
print("  - high_utilization_low_cost")
print("  - procedures_431_dominated")
print("  - high_cost_per_patient")
print("  - high_cost_non431_procedures")
print("  - patient_procedure_summary")
print("  - high_procedure_burden_patients")
print("  - procedure_priority")
print("  - priority_distribution")
print("  - cost_intensity_distribution")
print("  - utilization_intensity_distribution")
print("  - procedure_insight_metrics")
print("  - procedure_insight_summary")
print("  - procedure_g_validation")

print("\nSTATUS: PASS")
print("=" * 70)

======================================================================
STEP 4.18H — PROCEDURE EXECUTIVE ANALYTICS, COST CONCENTRATION &
             UTILIZATION PRIORITIZATION
======================================================================

SOURCE DATA DISCOVERY
----------------------------------------------------------------------
Using source dataset: procedure_g
Source records: 47,701

SOURCE DATA CHECK
----------------------------------------------------------------------
STATUS: PASS
Procedure records available: 47,701

ANALYTICAL DATASET VALIDATION
----------------------------------------------------------------------
Records: 47,701
Unique procedure codes: 157
Unique canonical descriptions: 157

CANONICALIZATION INTEGRITY
----------------------------------------------------------------------
Missing canonical descriptions: 0
Blank canonical descriptions: 0
Codes with multiple canonical descriptions: 0
Canonicalization integrity: PASS

BASE_COST SEGMENTATION
----------------------------------------------------------------------
431 records: 30,988
Non-431 records: 16,713
431 record share: 64.96%
Total procedure cost: 105,517,711.00
431 cost: 13,355,828.00
Non-431 cost: 92,161,883.00
431 cost share: 12.66%
Non-431 cost share: 87.34%

TOP 20 PROCEDURES BY TOTAL COST
----------------------------------------------------------------------
           CODE                                                              CANONICAL_DESCRIPTION  Procedure_Count  Total_Procedure_Cost  Unique_Patients  Cost_Per_Patient  Cost_431_Share
      180325003                                                           Electrical cardioversion             1383              35824002               74     484108.135135        0.000000
      225158009                                                    Auscultation of the fetal heart             1065               5657822               71      79687.633803        0.000000
      274804006                                                Evaluation of uterine fundal height             1065               5631281               71      79313.816901        0.000000
      703423002                            Combined chemotherapy and radiation therapy (procedure)              444               5237596               21     249409.333333        0.000000
       73761001                                                                        Colonoscopy              424               5021003              233      21549.369099        0.000000
       18286008                                               Catheter ablation of tissue of heart              365               3405999               54      63074.055556        0.000000
      265764009                                                         Renal dialysis (procedure)             2746               2757221                5     551444.200000        0.000000
      710824005                             Assessment of health and social care needs (procedure)             4596               1980876              509       3891.701375      100.000000
      312681000                                                      Bone density scan (procedure)              198               1901367              115      16533.626087        0.000000
      385763009                                                      Hospice care (regime/therapy)             4098               1766238               61      28954.721311      100.000000
      169230002                                                Ultrasound scan for fetal viability              184               1693824               81      20911.407407        0.000000
      171207006                                                               Depression screening             3804               1639524              544       3013.830882      100.000000
      127783003                                                             Spirometry (procedure)              209               1628688               23      70812.521739        0.000000
454711000124102 Depression screening using Patient Health Questionnaire Two-Item score (procedure)             3614               1557634              500       3115.268000      100.000000
      228557008                                  Cognitive and behavioral therapy (regime/therapy)              136               1412779               17      83104.647059        0.000000
       76601001                                                            Intramuscular injection              522               1325634               45      29458.533333        0.000000
428211000124100                                            Assessment of substance use (procedure)             2906               1252486              436       2872.674312      100.000000
      430193006                                              Medication Reconciliation (procedure)             2284               1162840              418       2781.913876        0.262697
      433112001    Percutaneous mechanical thrombectomy of portal vein using fluoroscopic guidance               57               1152998               55      20963.600000        0.000000
      762993000                                      Assessment using Morse Fall Scale (procedure)             2422               1043882              268       3895.082090      100.000000

TOP 20 PROCEDURES BY NON-431 COST
----------------------------------------------------------------------
     CODE                                                           CANONICAL_DESCRIPTION  Procedure_Count  Non_431_Count  Non_431_Total_Cost  Average_Procedure_Cost  Unique_Patients  Cost_Per_Patient  Cost_431_Share
180325003                                                        Electrical cardioversion             1383           1383            35824002            25903.110629               74     484108.135135        0.000000
225158009                                                 Auscultation of the fetal heart             1065           1065             5657822             5312.508920               71      79687.633803        0.000000
274804006                                             Evaluation of uterine fundal height             1065           1065             5631281             5287.587793               71      79313.816901        0.000000
703423002                         Combined chemotherapy and radiation therapy (procedure)              444            444             5237596            11796.387387               21     249409.333333        0.000000
 73761001                                                                     Colonoscopy              424            424             5021003            11841.988208              233      21549.369099        0.000000
 18286008                                            Catheter ablation of tissue of heart              365            365             3405999             9331.504110               54      63074.055556        0.000000
265764009                                                      Renal dialysis (procedure)             2746           2746             2757221             1004.086307                5     551444.200000        0.000000
312681000                                                   Bone density scan (procedure)              198            198             1901367             9602.863636              115      16533.626087        0.000000
169230002                                             Ultrasound scan for fetal viability              184            184             1693824             9205.565217               81      20911.407407        0.000000
127783003                                                          Spirometry (procedure)              209            209             1628688             7792.765550               23      70812.521739        0.000000
228557008                               Cognitive and behavioral therapy (regime/therapy)              136            136             1412779            10388.080882               17      83104.647059        0.000000
 76601001                                                         Intramuscular injection              522            522             1325634             2539.528736               45      29458.533333        0.000000
430193006                                           Medication Reconciliation (procedure)             2284           2278             1160254              509.124343              418       2781.913876        0.262697
433112001 Percutaneous mechanical thrombectomy of portal vein using fluoroscopic guidance               57             57             1152998            20228.035088               55      20963.600000        0.000000
305351004                                                        Admit to ICU (procedure)                5              5             1031302           206260.400000                2     515651.000000        0.000000
288086009                                                               Suture open wound              103            103              956599             9287.368932               93      10286.010753        0.000000
252160004                                                         Standard pregnancy test              184            184              955125             5190.896739               81      11791.666667        0.000000
302497006                                                        Hemodialysis (procedure)               27             27              791088            29299.555556                4     197772.000000        0.000000
399208008                                                               Plain chest X-ray               90             90              704168             7824.088889               67      10509.970149        0.000000
180256009                                                      Subcutaneous immunotherapy               54             54              639117            11835.500000                1     639117.000000        0.000000

TOP 20 PROCEDURES BY UTILIZATION
----------------------------------------------------------------------
           CODE                                                                CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Unique_Encounters  Procedures_Per_Patient  Procedures_Per_Encounter  Total_Procedure_Cost  Cost_431_Share
      710824005                               Assessment of health and social care needs (procedure)             4596              509               4596                9.029470                  1.000000               1980876      100.000000
      385763009                                                        Hospice care (regime/therapy)             4098               61                162               67.180328                 25.296296               1766238      100.000000
      171207006                                                                 Depression screening             3804              544               3803                6.992647                  1.000263               1639524      100.000000
454711000124102   Depression screening using Patient Health Questionnaire Two-Item score (procedure)             3614              500               3614                7.228000                  1.000000               1557634      100.000000
428211000124100                                              Assessment of substance use (procedure)             2906              436               2906                6.665138                  1.000000               1252486      100.000000
      265764009                                                           Renal dialysis (procedure)             2746                5               2746              549.200000                  1.000000               2757221        0.000000
      762993000                                        Assessment using Morse Fall Scale (procedure)             2422              268               2422                9.037313                  1.000000               1043882      100.000000
      710841007                                                    Assessment of anxiety (procedure)             2288              437               2288                5.235698                  1.000000                986128      100.000000
      430193006                                                Medication Reconciliation (procedure)             2284              418               2284                5.464115                  1.000000               1162840        0.262697
      713106006                                                 Screening for drug abuse (procedure)             1484              333               1484                4.456456                  1.000000                639604      100.000000
      866148006                                             Screening for domestic abuse (procedure)             1432              356               1432                4.022472                  1.000000                617192      100.000000
      763302001 Assessment using Alcohol Use Disorders Identification Test - Consumption (procedure)             1422              331               1422                4.296073                  1.000000                612882      100.000000
      180325003                                                             Electrical cardioversion             1383               74               1383               18.689189                  1.000000              35824002        0.000000
      225158009                                                      Auscultation of the fetal heart             1065               71               1065               15.000000                  1.000000               5657822        0.000000
      274804006                                                  Evaluation of uterine fundal height             1065               71               1065               15.000000                  1.000000               5631281        0.000000
      229064008                                                    Movement therapy (regime/therapy)              890               89                890               10.000000                  1.000000                383590      100.000000
       76601001                                                              Intramuscular injection              522               45                522               11.600000                  1.000000               1325634        0.000000
      703423002                              Combined chemotherapy and radiation therapy (procedure)              444               21                444               21.142857                  1.000000               5237596        0.000000
       73761001                                                                          Colonoscopy              424              233                424                1.819742                  1.000000               5021003        0.000000
       18286008                                                 Catheter ablation of tissue of heart              365               54                365                6.759259                  1.000000               3405999        0.000000

TOP 20 PROCEDURES BY COST PER PATIENT
----------------------------------------------------------------------
     CODE                                             CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Total_Procedure_Cost  Cost_Per_Patient  Procedures_Per_Patient  Cost_431_Share
180256009                                        Subcutaneous immunotherapy               54                1                639117     639117.000000               54.000000             0.0
265764009                                        Renal dialysis (procedure)             2746                5               2757221     551444.200000              549.200000             0.0
305351004                                          Admit to ICU (procedure)                5                2               1031302     515651.000000                2.500000             0.0
180325003                                          Electrical cardioversion             1383               74              35824002     484108.135135               18.689189             0.0
703423002           Combined chemotherapy and radiation therapy (procedure)              444               21               5237596     249409.333333               21.142857             0.0
302497006                                          Hemodialysis (procedure)               27                4                791088     197772.000000                6.750000             0.0
228557008                 Cognitive and behavioral therapy (regime/therapy)              136               17               1412779      83104.647059                8.000000             0.0
225158009                                   Auscultation of the fetal heart             1065               71               5657822      79687.633803               15.000000             0.0
274804006                               Evaluation of uterine fundal height             1065               71               5631281      79313.816901               15.000000             0.0
127783003                                            Spirometry (procedure)              209               23               1628688      70812.521739                9.086957             0.0
 18286008                              Catheter ablation of tissue of heart              365               54               3405999      63074.055556                6.759259             0.0
232717009                                   Coronary artery bypass grafting                9                8                423773      52971.625000                1.125000             0.0
 33195004                            Teleradiotherapy procedure (procedure)              170                5                169567      33913.400000               34.000000             0.0
 76601001                                           Intramuscular injection              522               45               1325634      29458.533333               11.600000             0.0
392021009                                  Lumpectomy of breast (procedure)                5                5                146765      29353.000000                1.000000             0.0
385763009                                     Hospice care (regime/therapy)             4098               61               1766238      28954.721311               67.180328           100.0
 15081005                         Pulmonary rehabilitation (regime/therapy)              171               12                326546      27212.166667               14.250000             0.0
447365002 Insertion of biventricular implantable cardioverter defibrillator                4                4                108804      27201.000000                1.000000             0.0
 43075005                                        Partial resection of colon                7                7                176605      25229.285714                1.000000             0.0
432231006                 Fine needle aspiration biopsy of lung (procedure)                1                1                 23141      23141.000000                1.000000             0.0

TOP 20 PROCEDURES BY PROCEDURES PER PATIENT
----------------------------------------------------------------------
             CODE                                                     CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Procedures_Per_Patient  Unique_Encounters  Total_Procedure_Cost  Cost_431_Share
        265764009                                                Renal dialysis (procedure)             2746                5              549.200000               2746               2757221             0.0

In [138]:
# ============================================================================
# STEP 4.18I — PROCEDURE EXECUTIVE / CLINICAL INSIGHT &
#              ACTION PRIORITIZATION
# ============================================================================
#
# PURPOSE
# -------
# Build the final procedure-level executive analytics layer on top of
# procedure_h.
#
# Covers:
#   1. Source validation
#   2. Procedure executive scorecard
#   3. Financial concentration
#   4. Volume concentration
#   5. Clinical/utilization burden
#   6. High-cost / high-utilization procedures
#   7. High-cost / lower-utilization procedures
#   8. High-utilization / lower-cost procedures
#   9. High patient-cost procedures
#  10. High repeat-utilization procedures
#  11. BASE_COST = 431 dependency
#  12. Patient-level procedure burden
#  13. Patient concentration
#  14. Executive priority scoring
#  15. Executive action matrix
#  16. Validation
#
# IMPORTANT
# ----------
# High cost, high utilization, or high repeat utilization DOES NOT mean
# clinically inappropriate care.
#
# These are analytical review signals only.
# ============================================================================

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 220)
pd.set_option("display.max_colwidth", 100)


# ============================================================================
# 1. SOURCE DATA DISCOVERY
# ============================================================================

print("=" * 70)
print("STEP 4.18I — PROCEDURE EXECUTIVE / CLINICAL INSIGHT &")
print("             ACTION PRIORITIZATION")
print("=" * 70)

# ---------------------------------------------------------------------------
# Prefer procedure_h because STEP 4.18H is the validated upstream dataset.
# ---------------------------------------------------------------------------

if "procedure_h" in globals():
    source_df = procedure_h.copy()
    source_name = "procedure_h"

elif "procedure_g" in globals():
    # Fallback only if procedure_h is not available.
    source_df = procedure_g.copy()
    source_name = "procedure_g"

elif "procedure_analysis" in globals():
    source_df = procedure_analysis.copy()
    source_name = "procedure_analysis"

else:
    raise NameError(
        "No validated procedure source dataset found. "
        "Expected procedure_h."
    )

print("\nSOURCE DATA DISCOVERY")
print("-" * 70)
print(f"Using source dataset: {source_name}")
print(f"Source records: {len(source_df):,}")


# ============================================================================
# 2. COLUMN RESOLUTION
# ============================================================================
#
# The upstream datasets may contain ORIGINAL_CODE / CODE,
# ORIGINAL_DESCRIPTION / DESCRIPTION / CANONICAL_DESCRIPTION, etc.
#
# We resolve columns without modifying the original dataset.
# ============================================================================

def resolve_column(df, candidates, required=True):
    """
    Return the first matching column from candidates.

    Matching is:
      1. Exact
      2. Case-insensitive
      3. Normalized
    """

    # Exact match
    for col in candidates:
        if col in df.columns:
            return col

    # Case-insensitive match
    lower_map = {str(c).lower(): c for c in df.columns}

    for col in candidates:
        if str(col).lower() in lower_map:
            return lower_map[str(col).lower()]

    # Normalized match
    def normalize_name(x):
        return (
            str(x)
            .strip()
            .upper()
            .replace(" ", "_")
            .replace("-", "_")
        )

    normalized_map = {
        normalize_name(c): c
        for c in df.columns
    }

    for col in candidates:
        key = normalize_name(col)

        if key in normalized_map:
            return normalized_map[key]

    if required:
        raise ValueError(
            f"Required column not found. "
            f"Expected one of: {candidates}\n"
            f"Available columns: {list(df.columns)}"
        )

    return None


CODE_COL = resolve_column(
    source_df,
    [
        "CODE",
        "ORIGINAL_CODE",
        "PROCEDURE_CODE",
    ]
)

ORIGINAL_CODE_COL = resolve_column(
    source_df,
    [
        "ORIGINAL_CODE",
        "CODE",
        "PROCEDURE_CODE",
    ]
)

CANONICAL_DESC_COL = resolve_column(
    source_df,
    [
        "CANONICAL_DESCRIPTION",
        "CANONICAL_DESC",
        "DESCRIPTION_CANONICAL",
        "DESCRIPTION",
        "ORIGINAL_DESCRIPTION",
    ]
)

ORIGINAL_DESC_COL = resolve_column(
    source_df,
    [
        "ORIGINAL_DESCRIPTION",
        "DESCRIPTION",
        "CANONICAL_DESCRIPTION",
    ]
)

PATIENT_COL = resolve_column(
    source_df,
    [
        "PATIENT",
        "PATIENT_ID",
        "PATIENTID",
    ]
)

ENCOUNTER_COL = resolve_column(
    source_df,
    [
        "ENCOUNTER",
        "ENCOUNTER_ID",
        "ENCOUNTERID",
    ]
)

BASE_COST_COL = resolve_column(
    source_df,
    [
        "BASE_COST",
        "Base_Cost",
        "base_cost",
    ]
)

PROCEDURE_COST_COL = resolve_column(
    source_df,
    [
        "PROCEDURE_COST",
        "TOTAL_PROCEDURE_COST",
        "TOTAL_COST",
        "COST",
        "AMOUNT",
        "BASE_COST",
    ]
)


print("\nCOLUMN RESOLUTION")
print("-" * 70)
print(f"CODE:                    {CODE_COL}")
print(f"ORIGINAL_CODE:           {ORIGINAL_CODE_COL}")
print(f"CANONICAL_DESCRIPTION:   {CANONICAL_DESC_COL}")
print(f"ORIGINAL_DESCRIPTION:    {ORIGINAL_DESC_COL}")
print(f"PATIENT:                 {PATIENT_COL}")
print(f"ENCOUNTER:               {ENCOUNTER_COL}")
print(f"BASE_COST:               {BASE_COST_COL}")
print(f"PROCEDURE_COST:          {PROCEDURE_COST_COL}")


# ============================================================================
# 3. CREATE STANDARDIZED INTERNAL ANALYTICAL VIEW
# ============================================================================
#
# Do not overwrite source_df.
# ============================================================================

work = source_df.copy()

work["_CODE"] = work[CODE_COL]
work["_ORIGINAL_CODE"] = work[ORIGINAL_CODE_COL]
work["_CANONICAL_DESCRIPTION"] = work[CANONICAL_DESC_COL]
work["_ORIGINAL_DESCRIPTION"] = work[ORIGINAL_DESC_COL]
work["_PATIENT"] = work[PATIENT_COL]
work["_ENCOUNTER"] = work[ENCOUNTER_COL]

work["_BASE_COST"] = pd.to_numeric(
    work[BASE_COST_COL],
    errors="coerce"
)

work["_PROCEDURE_COST"] = pd.to_numeric(
    work[PROCEDURE_COST_COL],
    errors="coerce"
)

# If procedure cost is missing, fall back to BASE_COST.
work["_PROCEDURE_COST"] = work["_PROCEDURE_COST"].fillna(
    work["_BASE_COST"]
)

# ---------------------------------------------------------------------------
# Validate cost availability.
# ---------------------------------------------------------------------------

if work["_PROCEDURE_COST"].isna().all():
    raise ValueError(
        "No usable procedure cost values were found."
    )

# Missing costs are treated as zero only after reporting the issue.
missing_cost_count = work["_PROCEDURE_COST"].isna().sum()

if missing_cost_count > 0:
    print(
        f"\nWARNING: {missing_cost_count:,} procedure records "
        f"have missing procedure cost. They will be treated as 0 "
        f"for aggregation."
    )

work["_PROCEDURE_COST"] = work["_PROCEDURE_COST"].fillna(0)

# ---------------------------------------------------------------------------
# BASE_COST = 431 flag
# ---------------------------------------------------------------------------

work["_IS_431"] = np.isclose(
    work["_BASE_COST"].fillna(np.nan),
    431
)

work["_IS_NON_431"] = ~work["_IS_431"]


# ============================================================================
# 4. SOURCE DATA CHECK
# ============================================================================

SOURCE_RECORD_COUNT = len(source_df)

print("\nSOURCE DATA CHECK")
print("-" * 70)
print("STATUS:", "PASS" if SOURCE_RECORD_COUNT > 0 else "FAIL")
print(f"Procedure records available: {SOURCE_RECORD_COUNT:,}")


# ============================================================================
# 5. CANONICALIZATION INTEGRITY
# ============================================================================

missing_canonical = work["_CANONICAL_DESCRIPTION"].isna().sum()

blank_canonical = (
    work["_CANONICAL_DESCRIPTION"]
    .astype("string")
    .str.strip()
    .eq("")
    .sum()
)

code_canonical_counts = (
    work.groupby("_CODE")["_CANONICAL_DESCRIPTION"]
    .nunique(dropna=True)
)

multiple_canonical_codes = (
    code_canonical_counts[
        code_canonical_counts > 1
    ]
)

unique_codes = work["_CODE"].nunique()
unique_canonical = work["_CANONICAL_DESCRIPTION"].nunique()

canonical_integrity_pass = (
    missing_canonical == 0
    and blank_canonical == 0
    and len(multiple_canonical_codes) == 0
)

print("\nANALYTICAL DATASET VALIDATION")
print("-" * 70)
print(f"Records: {len(work):,}")
print(f"Unique procedure codes: {unique_codes:,}")
print(f"Unique canonical descriptions: {unique_canonical:,}")

print("\nCANONICALIZATION INTEGRITY")
print("-" * 70)
print(f"Missing canonical descriptions: {missing_canonical:,}")
print(f"Blank canonical descriptions: {blank_canonical:,}")
print(
    f"Codes with multiple canonical descriptions: "
    f"{len(multiple_canonical_codes):,}"
)
print(
    "Canonicalization integrity:",
    "PASS" if canonical_integrity_pass else "FAIL"
)

if not canonical_integrity_pass:
    raise ValueError(
        "Canonicalization integrity failed."
    )


# ============================================================================
# 6. PROCEDURE-LEVEL EXECUTIVE SCORECARD
# ============================================================================

procedure_summary = (
    work.groupby(
        ["_CODE", "_CANONICAL_DESCRIPTION"],
        dropna=False
    )
    .agg(
        Procedure_Count=("_CODE", "size"),
        Unique_Patients=("_PATIENT", "nunique"),
        Unique_Encounters=("_ENCOUNTER", "nunique"),
        Total_Procedure_Cost=("_PROCEDURE_COST", "sum"),
        Cost_431=(
            "_PROCEDURE_COST",
            lambda x: x[work.loc[x.index, "_IS_431"]].sum()
        ),
        Non_431_Total_Cost=(
            "_PROCEDURE_COST",
            lambda x: x[work.loc[x.index, "_IS_NON_431"]].sum()
        ),
        Cost_431_Count=(
            "_IS_431",
            "sum"
        ),
    )
    .reset_index()
)

procedure_summary.rename(
    columns={
        "_CODE": "CODE",
        "_CANONICAL_DESCRIPTION": "CANONICAL_DESCRIPTION",
    },
    inplace=True
)

procedure_summary["Average_Procedure_Cost"] = np.where(
    procedure_summary["Procedure_Count"] > 0,
    procedure_summary["Total_Procedure_Cost"]
    / procedure_summary["Procedure_Count"],
    0
)

procedure_summary["Cost_Per_Patient"] = np.where(
    procedure_summary["Unique_Patients"] > 0,
    procedure_summary["Total_Procedure_Cost"]
    / procedure_summary["Unique_Patients"],
    0
)

procedure_summary["Cost_Per_Encounter"] = np.where(
    procedure_summary["Unique_Encounters"] > 0,
    procedure_summary["Total_Procedure_Cost"]
    / procedure_summary["Unique_Encounters"],
    0
)

procedure_summary["Procedures_Per_Patient"] = np.where(
    procedure_summary["Unique_Patients"] > 0,
    procedure_summary["Procedure_Count"]
    / procedure_summary["Unique_Patients"],
    0
)

procedure_summary["Procedures_Per_Encounter"] = np.where(
    procedure_summary["Unique_Encounters"] > 0,
    procedure_summary["Procedure_Count"]
    / procedure_summary["Unique_Encounters"],
    0
)

procedure_summary["Cost_431_Share"] = np.where(
    procedure_summary["Total_Procedure_Cost"] > 0,
    procedure_summary["Cost_431"]
    / procedure_summary["Total_Procedure_Cost"]
    * 100,
    0
)

procedure_summary["Non_431_Cost_Share"] = np.where(
    procedure_summary["Total_Procedure_Cost"] > 0,
    procedure_summary["Non_431_Total_Cost"]
    / procedure_summary["Total_Procedure_Cost"]
    * 100,
    0
)


# ============================================================================
# 7. GLOBAL EXECUTIVE TOTALS
# ============================================================================

TOTAL_COST = work["_PROCEDURE_COST"].sum()
TOTAL_431_COST = work.loc[
    work["_IS_431"],
    "_PROCEDURE_COST"
].sum()

TOTAL_NON_431_COST = work.loc[
    work["_IS_NON_431"],
    "_PROCEDURE_COST"
].sum()

RECORDS_431 = int(work["_IS_431"].sum())
RECORDS_NON_431 = int(work["_IS_NON_431"].sum())

RECORD_SHARE_431 = (
    RECORDS_431 / len(work) * 100
    if len(work) > 0 else 0
)

COST_SHARE_431 = (
    TOTAL_431_COST / TOTAL_COST * 100
    if TOTAL_COST > 0 else 0
)

COST_SHARE_NON_431 = (
    TOTAL_NON_431_COST / TOTAL_COST * 100
    if TOTAL_COST > 0 else 0
)


print("\nPROCEDURE EXECUTIVE KPIs")
print("-" * 70)
print(f"Total procedure records: {len(work):,}")
print(f"Unique procedure codes: {unique_codes:,}")
print(f"Unique canonical descriptions: {unique_canonical:,}")
print(f"Unique patients: {work['_PATIENT'].nunique():,}")
print(f"Unique encounters: {work['_ENCOUNTER'].nunique():,}")

print(f"\nTotal procedure cost: {TOTAL_COST:,.2f}")
print(f"431 cost: {TOTAL_431_COST:,.2f}")
print(f"Non-431 cost: {TOTAL_NON_431_COST:,.2f}")

print(f"\n431 record share: {RECORD_SHARE_431:.2f}%")
print(f"431 cost share: {COST_SHARE_431:.2f}%")
print(f"Non-431 cost share: {COST_SHARE_NON_431:.2f}%")


# ============================================================================
# 8. COST AND VOLUME CONCENTRATION
# ============================================================================

procedure_summary = procedure_summary.sort_values(
    "Total_Procedure_Cost",
    ascending=False
).reset_index(drop=True)

procedure_summary["Cost_Concentration_Share"] = (
    procedure_summary["Total_Procedure_Cost"]
    / TOTAL_COST
    * 100
    if TOTAL_COST > 0 else 0
)

procedure_summary["Cumulative_Cost_Share"] = (
    procedure_summary["Cost_Concentration_Share"]
    .cumsum()
)

procedure_summary["Volume_Concentration_Share"] = (
    procedure_summary["Procedure_Count"]
    / len(work)
    * 100
)

procedure_summary["Cumulative_Volume_Share"] = (
    procedure_summary["Volume_Concentration_Share"]
    .cumsum()
)


def concentration_share(df, metric, n):
    if len(df) == 0:
        return 0

    return (
        df.nlargest(n, metric)[metric].sum()
        / df[metric].sum()
        * 100
        if df[metric].sum() > 0 else 0
    )


top1_cost_share = concentration_share(
    procedure_summary,
    "Total_Procedure_Cost",
    1
)

top5_cost_share = concentration_share(
    procedure_summary,
    "Total_Procedure_Cost",
    5
)

top10_cost_share = concentration_share(
    procedure_summary,
    "Total_Procedure_Cost",
    10
)

top20_cost_share = concentration_share(
    procedure_summary,
    "Total_Procedure_Cost",
    20
)

top5_volume_share = concentration_share(
    procedure_summary,
    "Procedure_Count",
    5
)

top10_volume_share = concentration_share(
    procedure_summary,
    "Procedure_Count",
    10
)

top20_volume_share = concentration_share(
    procedure_summary,
    "Procedure_Count",
    20
)

top5_non431_share = concentration_share(
    procedure_summary,
    "Non_431_Total_Cost",
    5
)

top10_non431_share = concentration_share(
    procedure_summary,
    "Non_431_Total_Cost",
    10
)

top20_non431_share = concentration_share(
    procedure_summary,
    "Non_431_Total_Cost",
    20
)

print("\nPROCEDURE COST CONCENTRATION")
print("-" * 70)
print(f"Top 1 total-cost share: {top1_cost_share:.2f}%")
print(f"Top 5 total-cost share: {top5_cost_share:.2f}%")
print(f"Top 10 total-cost share: {top10_cost_share:.2f}%")
print(f"Top 20 total-cost share: {top20_cost_share:.2f}%")

print(f"\nTop 5 non-431 cost share: {top5_non431_share:.2f}%")
print(f"Top 10 non-431 cost share: {top10_non431_share:.2f}%")
print(f"Top 20 non-431 cost share: {top20_non431_share:.2f}%")

print("\nPROCEDURE VOLUME CONCENTRATION")
print("-" * 70)
print(f"Top 5 volume share: {top5_volume_share:.2f}%")
print(f"Top 10 volume share: {top10_volume_share:.2f}%")
print(f"Top 20 volume share: {top20_volume_share:.2f}%")


# ============================================================================
# 9. RANKINGS
# ============================================================================

procedure_summary["Cost_Rank"] = (
    procedure_summary["Total_Procedure_Cost"]
    .rank(method="min", ascending=False)
    .astype(int)
)

procedure_summary["Non_431_Cost_Rank"] = (
    procedure_summary["Non_431_Total_Cost"]
    .rank(method="min", ascending=False)
    .astype(int)
)

procedure_summary["Utilization_Rank"] = (
    procedure_summary["Procedure_Count"]
    .rank(method="min", ascending=False)
    .astype(int)
)

procedure_summary["Cost_Per_Patient_Rank"] = (
    procedure_summary["Cost_Per_Patient"]
    .rank(method="min", ascending=False)
    .astype(int)
)

procedure_summary["Repeat_Utilization_Rank"] = (
    procedure_summary["Procedures_Per_Patient"]
    .rank(method="min", ascending=False)
    .astype(int)
)


# ============================================================================
# 10. BASE_COST DEPENDENCY CLASSIFICATION
# ============================================================================

def classify_431_dependency(row):

    share = row["Cost_431_Share"]

    if share >= 90:
        return "431_DOMINATED"

    elif share <= 10:
        return "NON_431_DOMINATED"

    else:
        return "MIXED_431_NON431"


procedure_summary["431_Dependency"] = (
    procedure_summary.apply(
        classify_431_dependency,
        axis=1
    )
)


# ============================================================================
# 11. ANALYTICAL THRESHOLDS
# ============================================================================
#
# Reuse the validated 4.18H methodology where possible.
#
# Quantile thresholds provide robust relative prioritization and avoid
# arbitrary absolute cutoffs.
# ============================================================================

high_non431_cost_threshold = (
    procedure_summary["Non_431_Total_Cost"]
    .quantile(0.75)
)

high_utilization_threshold = (
    procedure_summary["Procedure_Count"]
    .quantile(0.75)
)

high_cost_per_patient_threshold = (
    procedure_summary["Cost_Per_Patient"]
    .quantile(0.75)
)

high_repeat_threshold = (
    procedure_summary["Procedures_Per_Patient"]
    .quantile(0.75)
)

extreme_non431_cost_threshold = (
    procedure_summary["Non_431_Total_Cost"]
    .quantile(0.90)
)

extreme_utilization_threshold = (
    procedure_summary["Procedure_Count"]
    .quantile(0.90)
)

extreme_cost_per_patient_threshold = (
    procedure_summary["Cost_Per_Patient"]
    .quantile(0.90)
)

extreme_repeat_threshold = (
    procedure_summary["Procedures_Per_Patient"]
    .quantile(0.90)
)


print("\nANALYTICAL THRESHOLDS")
print("-" * 70)
print(
    f"High non-431 cost threshold: "
    f"{high_non431_cost_threshold:,.2f}"
)

print(
    f"High utilization threshold: "
    f"{high_utilization_threshold:,.2f}"
)

print(
    f"High cost-per-patient threshold: "
    f"{high_cost_per_patient_threshold:,.2f}"
)

print(
    f"High repeat-utilization threshold: "
    f"{high_repeat_threshold:,.2f}"
)

print(
    f"Extreme non-431 cost threshold: "
    f"{extreme_non431_cost_threshold:,.2f}"
)

print(
    f"Extreme utilization threshold: "
    f"{extreme_utilization_threshold:,.2f}"
)


# ============================================================================
# 12. EXECUTIVE PRIORITY SCORE
# ============================================================================
#
# Score components:
#
#   Financial exposure       0–30
#   Utilization burden       0–25
#   Patient cost exposure    0–20
#   Repeat utilization       0–15
#   Concentration contribution 0–10
#
# Maximum = 100
#
# BASE_COST dependency is deliberately NOT used as a penalty. It is
# reported separately so that high activity is not incorrectly interpreted
# as high financial exposure.
# ============================================================================

# Financial component
procedure_summary["Financial_Score"] = np.select(
    [
        procedure_summary["Non_431_Total_Cost"]
        >= extreme_non431_cost_threshold,

        procedure_summary["Non_431_Total_Cost"]
        >= high_non431_cost_threshold
    ],
    [
        30,
        20
    ],
    default=5
)

# Utilization component
procedure_summary["Utilization_Score"] = np.select(
    [
        procedure_summary["Procedure_Count"]
        >= extreme_utilization_threshold,

        procedure_summary["Procedure_Count"]
        >= high_utilization_threshold
    ],
    [
        25,
        17
    ],
    default=5
)

# Patient cost component
procedure_summary["Patient_Cost_Score"] = np.select(
    [
        procedure_summary["Cost_Per_Patient"]
        >= extreme_cost_per_patient_threshold,

        procedure_summary["Cost_Per_Patient"]
        >= high_cost_per_patient_threshold
    ],
    [
        20,
        13
    ],
    default=4
)

# Repeat utilization component
procedure_summary["Repeat_Score"] = np.select(
    [
        procedure_summary["Procedures_Per_Patient"]
        >= extreme_repeat_threshold,

        procedure_summary["Procedures_Per_Patient"]
        >= high_repeat_threshold
    ],
    [
        15,
        10
    ],
    default=3
)

# Concentration component
procedure_summary["Concentration_Score"] = np.select(
    [
        procedure_summary["Cost_Concentration_Share"]
        >= 5,

        procedure_summary["Cost_Concentration_Share"]
        >= 2
    ],
    [
        10,
        6
    ],
    default=2
)

procedure_summary["Executive_Score"] = (
    procedure_summary["Financial_Score"]
    + procedure_summary["Utilization_Score"]
    + procedure_summary["Patient_Cost_Score"]
    + procedure_summary["Repeat_Score"]
    + procedure_summary["Concentration_Score"]
)


# ============================================================================
# 13. EXECUTIVE PRIORITY PROFILE
# ============================================================================

def classify_priority(row):

    cost = row["Non_431_Total_Cost"]
    utilization = row["Procedure_Count"]
    patient_cost = row["Cost_Per_Patient"]
    repeat = row["Procedures_Per_Patient"]
    dependency = row["431_Dependency"]

    extreme_cost = cost >= extreme_non431_cost_threshold
    high_cost = cost >= high_non431_cost_threshold

    extreme_util = utilization >= extreme_utilization_threshold
    high_util = utilization >= high_utilization_threshold

    extreme_patient_cost = (
        patient_cost >= extreme_cost_per_patient_threshold
    )

    high_patient_cost = (
        patient_cost >= high_cost_per_patient_threshold
    )

    extreme_repeat = (
        repeat >= extreme_repeat_threshold
    )

    high_repeat = (
        repeat >= high_repeat_threshold
    )

    # Highest priority: extreme cost + extreme utilization
    if extreme_cost and extreme_util:
        return "CRITICAL_FINANCIAL_PRIORITY"

    # High cost + high utilization
    if high_cost and high_util:
        return "HIGH_FINANCIAL_PRIORITY"

    # Very high patient cost
    if extreme_patient_cost:
        return "HIGH_PATIENT_COST"

    # High repeat burden
    if extreme_repeat:
        return "HIGH_REPEAT_BURDEN"

    # High utilization without high financial exposure
    if high_util:
        return "HIGH_UTILIZATION_PRIORITY"

    # 431-dominated activity
    if dependency == "431_DOMINATED":
        return "431_DOMINATED"

    # Moderate financial attention
    if high_cost:
        return "HIGH_FINANCIAL_PRIORITY"

    return "STANDARD"


procedure_summary["Executive_Priority"] = (
    procedure_summary.apply(
        classify_priority,
        axis=1
    )
)


# ============================================================================
# 14. PROCEDURE EXECUTIVE SCORECARD
# ============================================================================

procedure_executive_scorecard = procedure_summary[
    [
        "CODE",
        "CANONICAL_DESCRIPTION",
        "Procedure_Count",
        "Unique_Patients",
        "Unique_Encounters",
        "Total_Procedure_Cost",
        "Non_431_Total_Cost",
        "Cost_431",
        "Cost_431_Share",
        "Non_431_Cost_Share",
        "Average_Procedure_Cost",
        "Cost_Per_Patient",
        "Cost_Per_Encounter",
        "Procedures_Per_Patient",
        "Procedures_Per_Encounter",
        "Cost_Concentration_Share",
        "Volume_Concentration_Share",
        "Cost_Rank",
        "Non_431_Cost_Rank",
        "Utilization_Rank",
        "Cost_Per_Patient_Rank",
        "Repeat_Utilization_Rank",
        "431_Dependency",
        "Executive_Score",
        "Executive_Priority"
    ]
].copy()

procedure_executive_scorecard = (
    procedure_executive_scorecard
    .sort_values(
        [
            "Executive_Score",
            "Non_431_Total_Cost"
        ],
        ascending=False
    )
    .reset_index(drop=True)
)


# ============================================================================
# 15. TOP PROCEDURE TABLES
# ============================================================================

top_cost_procedures = (
    procedure_summary
    .nlargest(20, "Total_Procedure_Cost")
    .copy()
)

top_non_431_cost = (
    procedure_summary
    .nlargest(20, "Non_431_Total_Cost")
    .copy()
)

top_utilization = (
    procedure_summary
    .nlargest(20, "Procedure_Count")
    .copy()
)

top_cost_per_patient = (
    procedure_summary
    .nlargest(20, "Cost_Per_Patient")
    .copy()
)

high_cost_per_patient = (
    procedure_summary[
        procedure_summary["Cost_Per_Patient"]
        >= high_cost_per_patient_threshold
    ]
    .sort_values(
        "Cost_Per_Patient",
        ascending=False
    )
    .copy()
)


# ============================================================================
# 16. HIGH COST / HIGH UTILIZATION
# ============================================================================

high_cost_high_utilization_i = procedure_summary[
    (
        procedure_summary["Non_431_Total_Cost"]
        >= high_non431_cost_threshold
    )
    &
    (
        procedure_summary["Procedure_Count"]
        >= high_utilization_threshold
    )
].copy()

high_cost_high_utilization_i = (
    high_cost_high_utilization_i
    .sort_values(
        [
            "Non_431_Total_Cost",
            "Procedure_Count"
        ],
        ascending=False
    )
)


# ============================================================================
# 17. HIGH COST / LOWER UTILIZATION
# ============================================================================

high_cost_low_utilization_i = procedure_summary[
    (
        procedure_summary["Non_431_Total_Cost"]
        >= high_non431_cost_threshold
    )
    &
    (
        procedure_summary["Procedure_Count"]
        < high_utilization_threshold
    )
].copy()

high_cost_low_utilization_i = (
    high_cost_low_utilization_i
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
)


# ============================================================================
# 18. HIGH UTILIZATION / LOWER NON-431 COST
# ============================================================================

high_utilization_low_cost_i = procedure_summary[
    (
        procedure_summary["Procedure_Count"]
        >= high_utilization_threshold
    )
    &
    (
        procedure_summary["Non_431_Total_Cost"]
        < high_non431_cost_threshold
    )
].copy()

high_utilization_low_cost_i = (
    high_utilization_low_cost_i
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
)


# ============================================================================
# 19. HIGH PATIENT-COST PROCEDURES
# ============================================================================

high_patient_cost_i = procedure_summary[
    procedure_summary["Cost_Per_Patient"]
    >= high_cost_per_patient_threshold
].copy()

high_patient_cost_i = (
    high_patient_cost_i
    .sort_values(
        "Cost_Per_Patient",
        ascending=False
    )
)


# ============================================================================
# 20. HIGH REPEAT-UTILIZATION PROCEDURES
# ============================================================================

high_repeat_procedures_i = procedure_summary[
    procedure_summary["Procedures_Per_Patient"]
    >= high_repeat_threshold
].copy()

high_repeat_procedures_i = (
    high_repeat_procedures_i
    .sort_values(
        [
            "Procedures_Per_Patient",
            "Procedure_Count"
        ],
        ascending=False
    )
)


# ============================================================================
# 21. 431 DEPENDENCY ANALYSIS
# ============================================================================

procedure_431_dependency = (
    procedure_summary[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Total_Procedure_Cost",
            "Cost_431",
            "Non_431_Total_Cost",
            "Cost_431_Share",
            "Non_431_Cost_Share",
            "431_Dependency",
            "Executive_Priority"
        ]
    ]
    .sort_values(
        [
            "431_Dependency",
            "Total_Procedure_Cost"
        ],
        ascending=[True, False]
    )
    .copy()
)


# ============================================================================
# 22. HIGH PROCEDURE BURDEN AT PATIENT LEVEL
# ============================================================================

patient_procedure_summary = (
    work.groupby(
        "_PATIENT",
        dropna=False
    )
    .agg(
        Procedure_Count=("_CODE", "size"),
        Unique_Procedure_Codes=("_CODE", "nunique"),
        Unique_Encounters=("_ENCOUNTER", "nunique"),
        Total_Procedure_Cost=("_PROCEDURE_COST", "sum"),
        Non_431_Cost=(
            "_PROCEDURE_COST",
            lambda x: x[work.loc[x.index, "_IS_NON_431"]].sum()
        ),
        Cost_431=(
            "_PROCEDURE_COST",
            lambda x: x[work.loc[x.index, "_IS_431"]].sum()
        ),
    )
    .reset_index()
)

patient_procedure_summary.rename(
    columns={
        "_PATIENT": "PATIENT"
    },
    inplace=True
)

patient_procedure_summary["Procedures_Per_Encounter"] = np.where(
    patient_procedure_summary["Unique_Encounters"] > 0,
    patient_procedure_summary["Procedure_Count"]
    / patient_procedure_summary["Unique_Encounters"],
    0
)

patient_procedure_summary["Procedures_Per_Code"] = np.where(
    patient_procedure_summary["Unique_Procedure_Codes"] > 0,
    patient_procedure_summary["Procedure_Count"]
    / patient_procedure_summary["Unique_Procedure_Codes"],
    0
)

patient_procedure_summary["Cost_431_Share"] = np.where(
    patient_procedure_summary["Total_Procedure_Cost"] > 0,
    patient_procedure_summary["Cost_431"]
    / patient_procedure_summary["Total_Procedure_Cost"]
    * 100,
    0
)

patient_procedure_summary["Non_431_Cost_Share"] = np.where(
    patient_procedure_summary["Total_Procedure_Cost"] > 0,
    patient_procedure_summary["Non_431_Cost"]
    / patient_procedure_summary["Total_Procedure_Cost"]
    * 100,
    0
)


# ============================================================================
# 23. IDENTIFY HIGHEST-COST PROCEDURE PER PATIENT
# ============================================================================

patient_procedure_lookup = (
    work.groupby(
        [
            "_PATIENT",
            "_CODE",
            "_CANONICAL_DESCRIPTION"
        ],
        dropna=False
    )
    .agg(
        Procedure_Count=("_CODE", "size"),
        Procedure_Cost=("_PROCEDURE_COST", "sum")
    )
    .reset_index()
)

idx_highest_patient_procedure = (
    patient_procedure_lookup
    .groupby("_PATIENT")["Procedure_Cost"]
    .idxmax()
)

highest_patient_procedure = (
    patient_procedure_lookup
    .loc[idx_highest_patient_procedure]
    .copy()
)

highest_patient_procedure.rename(
    columns={
        "_PATIENT": "PATIENT",
        "_CODE": "Highest_Cost_Procedure_Code",
        "_CANONICAL_DESCRIPTION":
            "Highest_Cost_Procedure",
        "Procedure_Cost":
            "Highest_Procedure_Cost"
    },
    inplace=True
)

patient_procedure_summary = patient_procedure_summary.merge(
    highest_patient_procedure[
        [
            "PATIENT",
            "Highest_Cost_Procedure_Code",
            "Highest_Cost_Procedure",
            "Highest_Procedure_Cost"
        ]
    ],
    on="PATIENT",
    how="left"
)


# ============================================================================
# 24. PATIENT PROCEDURE BURDEN THRESHOLDS
# ============================================================================

patient_count_threshold = (
    patient_procedure_summary["Procedure_Count"]
    .quantile(0.90)
)

patient_cost_threshold = (
    patient_procedure_summary["Total_Procedure_Cost"]
    .quantile(0.90)
)

patient_encounter_burden_threshold = (
    patient_procedure_summary["Procedures_Per_Encounter"]
    .quantile(0.90)
)

high_procedure_burden_patients = (
    patient_procedure_summary[
        (
            patient_procedure_summary["Procedure_Count"]
            >= patient_count_threshold
        )
        |
        (
            patient_procedure_summary["Total_Procedure_Cost"]
            >= patient_cost_threshold
        )
    ]
    .sort_values(
        [
            "Total_Procedure_Cost",
            "Procedure_Count"
        ],
        ascending=False
    )
    .copy()
)


# ============================================================================
# 25. PATIENT COST CONCENTRATION
# ============================================================================

def patient_concentration_share(df, n):

    total = df["Total_Procedure_Cost"].sum()

    if total <= 0:
        return 0

    return (
        df.nlargest(
            min(n, len(df)),
            "Total_Procedure_Cost"
        )["Total_Procedure_Cost"].sum()
        / total
        * 100
    )


patient_top1_cost_share = patient_concentration_share(
    patient_procedure_summary,
    1
)

patient_top5_cost_share = patient_concentration_share(
    patient_procedure_summary,
    5
)

patient_top10_cost_share = patient_concentration_share(
    patient_procedure_summary,
    10
)

patient_top20_cost_share = patient_concentration_share(
    patient_procedure_summary,
    20
)

patient_count = len(patient_procedure_summary)

top_1_percent_n = max(
    1,
    int(np.ceil(patient_count * 0.01))
)

top_5_percent_n = max(
    1,
    int(np.ceil(patient_count * 0.05))
)

top_10_percent_n = max(
    1,
    int(np.ceil(patient_count * 0.10))
)

top_20_percent_n = max(
    1,
    int(np.ceil(patient_count * 0.20))
)

patient_top1_percent_share = (
    patient_concentration_share(
        patient_procedure_summary,
        top_1_percent_n
    )
)

patient_top5_percent_share = (
    patient_concentration_share(
        patient_procedure_summary,
        top_5_percent_n
    )
)

patient_top10_percent_share = (
    patient_concentration_share(
        patient_procedure_summary,
        top_10_percent_n
    )
)

patient_top20_percent_share = (
    patient_concentration_share(
        patient_procedure_summary,
        top_20_percent_n
    )
)


# ============================================================================
# 26. EXECUTIVE ACTION MATRIX
# ============================================================================

def determine_primary_signal(row):

    if row["Executive_Priority"] == "CRITICAL_FINANCIAL_PRIORITY":
        return "CRITICAL_COST_AND_UTILIZATION"

    if row["Executive_Priority"] == "HIGH_FINANCIAL_PRIORITY":
        return "HIGH_FINANCIAL_EXPOSURE"

    if row["Executive_Priority"] == "HIGH_PATIENT_COST":
        return "HIGH_PATIENT_COST"

    if row["Executive_Priority"] == "HIGH_REPEAT_BURDEN":
        return "HIGH_REPEAT_UTILIZATION"

    if row["Executive_Priority"] == "HIGH_UTILIZATION_PRIORITY":
        return "HIGH_UTILIZATION"

    if row["Executive_Priority"] == "431_DOMINATED":
        return "431_COST_DEPENDENCY"

    if row["431_Dependency"] == "NON_431_DOMINATED":
        return "NON_431_FINANCIAL_EXPOSURE"

    return "STANDARD"


def determine_action(row):

    signal = row["Primary_Signal"]

    if signal == "CRITICAL_COST_AND_UTILIZATION":
        return (
            "Immediate clinical and financial review; "
            "assess utilization pattern, cost drivers and "
            "patient complexity."
        )

    if signal == "HIGH_FINANCIAL_EXPOSURE":
        return (
            "Prioritize financial and clinical pathway review."
        )

    if signal == "HIGH_PATIENT_COST":
        return (
            "Review patient-level cost concentration and "
            "clinical context."
        )

    if signal == "HIGH_REPEAT_UTILIZATION":
        return (
            "Review repeat utilization patterns and "
            "clinical pathway context."
        )

    if signal == "HIGH_UTILIZATION":
        return (
            "Review operational volume, workflow and "
            "utilization patterns."
        )

    if signal == "431_COST_DEPENDENCY":
        return (
            "Monitor activity and distinguish service volume "
            "from direct financial exposure."
        )

    if signal == "NON_431_FINANCIAL_EXPOSURE":
        return (
            "Monitor non-431 financial exposure and "
            "cost drivers."
        )

    return (
        "Routine monitoring."
    )


procedure_action_matrix = procedure_executive_scorecard[
    [
        "CODE",
        "CANONICAL_DESCRIPTION",
        "Procedure_Count",
        "Unique_Patients",
        "Unique_Encounters",
        "Total_Procedure_Cost",
        "Non_431_Total_Cost",
        "Cost_Per_Patient",
        "Procedures_Per_Patient",
        "Cost_431_Share",
        "431_Dependency",
        "Executive_Score",
        "Executive_Priority"
    ]
].copy()

procedure_action_matrix["Primary_Signal"] = (
    procedure_action_matrix.apply(
        determine_primary_signal,
        axis=1
    )
)

procedure_action_matrix["Financial_Exposure"] = np.where(
    procedure_action_matrix["Non_431_Total_Cost"]
    >= high_non431_cost_threshold,
    "HIGH",
    "STANDARD"
)

procedure_action_matrix["Utilization_Burden"] = np.where(
    procedure_action_matrix["Procedure_Count"]
    >= high_utilization_threshold,
    "HIGH",
    "STANDARD"
)

procedure_action_matrix["Patient_Burden"] = np.where(
    procedure_action_matrix["Cost_Per_Patient"]
    >= high_cost_per_patient_threshold,
    "HIGH",
    "STANDARD"
)

procedure_action_matrix["Recommended_Review"] = (
    procedure_action_matrix.apply(
        determine_action,
        axis=1
    )
)

procedure_action_matrix = (
    procedure_action_matrix
    .sort_values(
        [
            "Executive_Score",
            "Non_431_Total_Cost"
        ],
        ascending=False
    )
    .reset_index(drop=True)
)


# ============================================================================
# 27. PRIORITY DISTRIBUTION
# ============================================================================

priority_distribution = (
    procedure_summary["Executive_Priority"]
    .value_counts()
    .rename_axis("Executive_Priority")
    .reset_index(name="Procedure_Group_Count")
)

priority_distribution["Group_Share_%"] = (
    priority_distribution["Procedure_Group_Count"]
    / len(procedure_summary)
    * 100
)

priority_distribution = priority_distribution.sort_values(
    "Procedure_Group_Count",
    ascending=False
).reset_index(drop=True)


# ============================================================================
# 28. PROCEDURE INSIGHT KPIs
# ============================================================================

executive_procedure_kpis = pd.DataFrame(
    {
        "Metric": [
            "Total Procedure Records",
            "Unique Procedure Codes",
            "Unique Canonical Descriptions",
            "Unique Patients",
            "Unique Encounters",
            "Total Procedure Cost",
            "431 Cost",
            "Non-431 Cost",
            "431 Record Share %",
            "431 Cost Share %",
            "Non-431 Cost Share %",
            "Top 1 Total Cost Share %",
            "Top 5 Total Cost Share %",
            "Top 10 Total Cost Share %",
            "Top 20 Total Cost Share %",
            "Top 5 Non-431 Cost Share %",
            "Top 10 Non-431 Cost Share %",
            "Top 20 Non-431 Cost Share %",
            "Top 5 Volume Share %",
            "Top 10 Volume Share %",
            "Top 20 Volume Share %",
            "High Procedure Burden Patients",
            "Top 1% Patient Procedure Cost Share %",
            "Top 5% Patient Procedure Cost Share %",
            "Top 10% Patient Procedure Cost Share %",
            "Top 20% Patient Procedure Cost Share %",
            "431-Dominated Procedure Groups",
            "Mixed 431/Non-431 Procedure Groups",
            "Non-431-Dominated Procedure Groups",
        ],
        "Value": [
            len(work),
            unique_codes,
            unique_canonical,
            work["_PATIENT"].nunique(),
            work["_ENCOUNTER"].nunique(),
            TOTAL_COST,
            TOTAL_431_COST,
            TOTAL_NON_431_COST,
            RECORD_SHARE_431,
            COST_SHARE_431,
            COST_SHARE_NON_431,
            top1_cost_share,
            top5_cost_share,
            top10_cost_share,
            top20_cost_share,
            top5_non431_share,
            top10_non431_share,
            top20_non431_share,
            top5_volume_share,
            top10_volume_share,
            top20_volume_share,
            len(high_procedure_burden_patients),
            patient_top1_percent_share,
            patient_top5_percent_share,
            patient_top10_percent_share,
            patient_top20_percent_share,
            (
                procedure_summary["431_Dependency"]
                .eq("431_DOMINATED")
                .sum()
            ),
            (
                procedure_summary["431_Dependency"]
                .eq("MIXED_431_NON431")
                .sum()
            ),
            (
                procedure_summary["431_Dependency"]
                .eq("NON_431_DOMINATED")
                .sum()
            ),
        ]
    }
)


# ============================================================================
# 29. HUMAN-READABLE EXECUTIVE INSIGHT SUMMARY
# ============================================================================

procedure_insight_summary = pd.DataFrame(
    {
        "Insight_Area": [
            "Cost Concentration",
            "Non-431 Cost Concentration",
            "Volume Concentration",
            "431 Dependency",
            "High-Cost/High-Utilization",
            "High-Cost/Low-Utilization",
            "High-Utilization/Lower-Cost",
            "High Patient Cost",
            "High Repeat Utilization",
            "Patient Procedure Burden",
        ],
        "Finding": [
            (
                f"Top 10 procedures account for "
                f"{top10_cost_share:.2f}% of total observed procedure cost."
            ),
            (
                f"Top 10 procedures account for "
                f"{top10_non431_share:.2f}% of non-431 procedure cost."
            ),
            (
                f"Top 10 procedures account for "
                f"{top10_volume_share:.2f}% of procedure volume."
            ),
            (
                f"{RECORD_SHARE_431:.2f}% of records are BASE_COST=431, "
                f"while 431 represents only {COST_SHARE_431:.2f}% "
                f"of total procedure cost."
            ),
            (
                f"{len(high_cost_high_utilization_i)} procedure groups "
                f"meet both high-cost and high-utilization criteria."
            ),
            (
                f"{len(high_cost_low_utilization_i)} procedure groups "
                f"meet high-cost/lower-utilization criteria."
            ),
            (
                f"{len(high_utilization_low_cost_i)} procedure groups "
                f"meet high-utilization/lower-cost criteria."
            ),
            (
                f"{len(high_patient_cost_i)} procedure groups exceed "
                f"the high cost-per-patient threshold."
            ),
            (
                f"{len(high_repeat_procedures_i)} procedure groups exceed "
                f"the high repeat-utilization threshold."
            ),
            (
                f"{len(high_procedure_burden_patients):,} patients "
                f"meet the high procedure-burden criteria."
            ),
        ]
    }
)


# ============================================================================
# 30. TOP EXECUTIVE PRIORITY PROCEDURES
# ============================================================================

critical_procedure_priority = (
    procedure_executive_scorecard[
        procedure_executive_scorecard["Executive_Priority"]
        == "CRITICAL_FINANCIAL_PRIORITY"
    ]
    .copy()
)

high_financial_priority = (
    procedure_executive_scorecard[
        procedure_executive_scorecard["Executive_Priority"]
        == "HIGH_FINANCIAL_PRIORITY"
    ]
    .copy()
)


# ============================================================================
# 31. PRINT EXECUTIVE TABLES
# ============================================================================

display_columns = [
    "CODE",
    "CANONICAL_DESCRIPTION",
    "Procedure_Count",
    "Unique_Patients",
    "Total_Procedure_Cost",
    "Non_431_Total_Cost",
    "Cost_Per_Patient",
    "Procedures_Per_Patient",
    "Cost_431_Share",
    "Executive_Priority"
]

print("\nTOP EXECUTIVE PRIORITY PROCEDURES")
print("-" * 70)

print(
    procedure_executive_scorecard[
        display_columns
    ].head(20).to_string(index=False)
)


print("\nHIGH COST / HIGH UTILIZATION")
print("-" * 70)

print(
    high_cost_high_utilization_i[
        display_columns
    ].to_string(index=False)
)


print("\nHIGH COST / LOWER UTILIZATION")
print("-" * 70)

print(
    high_cost_low_utilization_i[
        display_columns
    ].head(20).to_string(index=False)
)


print("\nHIGH UTILIZATION / LOWER NON-431 COST")
print("-" * 70)

print(
    high_utilization_low_cost_i[
        display_columns
    ].head(20).to_string(index=False)
)


print("\nHIGH PATIENT-COST PROCEDURES")
print("-" * 70)

print(
    high_patient_cost_i[
        display_columns
    ].head(20).to_string(index=False)
)


print("\nHIGH REPEAT-UTILIZATION PROCEDURES")
print("-" * 70)

print(
    high_repeat_procedures_i[
        display_columns
    ].head(20).to_string(index=False)
)


# ============================================================================
# 32. 431 DEPENDENCY SUMMARY
# ============================================================================

dependency_counts = (
    procedure_summary["431_Dependency"]
    .value_counts()
)

print("\n431 COST DEPENDENCY")
print("-" * 70)

print(
    f"431-dominated procedures: "
    f"{dependency_counts.get('431_DOMINATED', 0):,}"
)

print(
    f"Mixed 431/non-431 procedures: "
    f"{dependency_counts.get('MIXED_431_NON431', 0):,}"
)

print(
    f"Non-431-dominated procedures: "
    f"{dependency_counts.get('NON_431_DOMINATED', 0):,}"
)


# ============================================================================
# 33. PATIENT BURDEN SUMMARY
# ============================================================================

print("\nPATIENT PROCEDURE BURDEN")
print("-" * 70)

print(
    f"Patients analyzed: "
    f"{len(patient_procedure_summary):,}"
)

print(
    f"High procedure-burden patients: "
    f"{len(high_procedure_burden_patients):,}"
)

print(
    f"Top 1% patient procedure-cost share: "
    f"{patient_top1_percent_share:.2f}%"
)

print(
    f"Top 5% patient procedure-cost share: "
    f"{patient_top5_percent_share:.2f}%"
)

print(
    f"Top 10% patient procedure-cost share: "
    f"{patient_top10_percent_share:.2f}%"
)

print(
    f"Top 20% patient procedure-cost share: "
    f"{patient_top20_percent_share:.2f}%"
)


# ============================================================================
# 34. KEY EXECUTIVE INSIGHTS
# ============================================================================

print("\nKEY EXECUTIVE INSIGHTS")
print("-" * 70)

print(
    f"1. Procedure expenditure is concentrated: "
    f"the top 10 procedures represent "
    f"{top10_cost_share:.2f}% of total observed procedure cost."
)

print(
    f"2. Non-431 procedures are the principal direct cost driver: "
    f"they represent {COST_SHARE_NON_431:.2f}% of total procedure cost."
)

print(
    f"3. A relatively small set of procedures combine material "
    f"financial exposure and utilization: "
    f"{len(high_cost_high_utilization_i)} groups meet both criteria."
)

print(
    f"4. {len(high_repeat_procedures_i)} procedure groups demonstrate "
    f"high repeat utilization based on the analytical threshold."
)

print(
    f"5. {len(high_patient_cost_i)} procedure groups demonstrate "
    f"high cost per patient."
)

print(
    f"6. BASE_COST=431 represents {RECORD_SHARE_431:.2f}% of procedure "
    f"records but only {COST_SHARE_431:.2f}% of procedure cost."
)

print(
    f"7. The top 10 procedures represent "
    f"{top10_volume_share:.2f}% of procedure volume."
)

print(
    f"8. Patient-level procedure costs are concentrated in the "
    f"highest-cost patient groups; this should be interpreted "
    f"alongside patient complexity and clinical context."
)


# ============================================================================
# 35. CLINICAL INTERPRETATION SAFEGUARD
# ============================================================================

print("\nCLINICAL INTERPRETATION SAFEGUARD")
print("-" * 70)

print(
    "No procedure has been classified as clinically inappropriate "
    "solely from cost or utilization data."
)

print(
    "High utilization does not equal inappropriate utilization."
)

print(
    "High cost does not equal inappropriate care."
)

print(
    "High repeat utilization does not equal unnecessary care."
)

print(
    "Findings represent analytical review priorities requiring "
    "clinical, operational and contextual validation."
)


# ============================================================================
# 36. FINAL VALIDATION
# ============================================================================

validation_results = {
    "Record count preserved":
        len(work) == SOURCE_RECORD_COUNT,

    "Original CODE preserved":
        ORIGINAL_CODE_COL in source_df.columns,

    "Original DESCRIPTION preserved":
        ORIGINAL_DESC_COL in source_df.columns,

    "Canonical description available":
        missing_canonical == 0
        and blank_canonical == 0,

    "One canonical description per CODE":
        len(multiple_canonical_codes) == 0,

    "431 cost segmentation available":
        "_IS_431" in work.columns,

    "Non-431 cost available":
        "Non_431_Total_Cost" in procedure_summary.columns,

    "Procedure executive scorecard created":
        isinstance(
            procedure_executive_scorecard,
            pd.DataFrame
        ),

    "Procedure priority created":
        "Executive_Priority"
        in procedure_executive_scorecard.columns,

    "Patient procedure summary created":
        isinstance(
            patient_procedure_summary,
            pd.DataFrame
        ),

    "Cost concentration calculated":
        "Cost_Concentration_Share"
        in procedure_summary.columns,

    "Volume concentration calculated":
        "Volume_Concentration_Share"
        in procedure_summary.columns,

    "Repeat utilization analysis created":
        isinstance(
            high_repeat_procedures_i,
            pd.DataFrame
        ),

    "Patient burden analysis created":
        isinstance(
            high_procedure_burden_patients,
            pd.DataFrame
        ),

    "Executive action matrix created":
        isinstance(
            procedure_action_matrix,
            pd.DataFrame
        ),

    "No records deleted":
        len(work) == len(source_df)
}

procedure_i_validation = pd.DataFrame(
    {
        "Validation": list(validation_results.keys()),
        "Result": list(validation_results.values())
    }
)

print("\nFINAL VALIDATION")
print("-" * 70)
print(
    procedure_i_validation.to_string(index=False)
)

validation_pass = all(
    validation_results.values()
)

if not validation_pass:
    raise ValueError(
        "STEP 4.18I validation FAILED. "
        "Review the validation table above."
    )


# ============================================================================
# 37. FINAL DATASET REGISTRY
# ============================================================================
#
# These are the principal analytical outputs of STEP 4.18I.
# ============================================================================

# Main dataset
procedure_i = work.copy()

# Executive datasets
procedure_executive_priority = (
    procedure_executive_scorecard.copy()
)

procedure_financial_concentration = (
    procedure_summary[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Total_Procedure_Cost",
            "Non_431_Total_Cost",
            "Cost_Concentration_Share",
            "Cumulative_Cost_Share",
            "Cost_Rank"
        ]
    ]
    .sort_values(
        "Total_Procedure_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)

procedure_volume_concentration = (
    procedure_summary[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Unique_Encounters",
            "Volume_Concentration_Share",
            "Cumulative_Volume_Share",
            "Utilization_Rank"
        ]
    ]
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .reset_index(drop=True)
)

procedure_cost_patient_analysis = (
    procedure_summary[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Total_Procedure_Cost",
            "Cost_Per_Patient",
            "Cost_Per_Encounter",
            "Procedures_Per_Patient"
        ]
    ]
    .sort_values(
        "Cost_Per_Patient",
        ascending=False
    )
    .reset_index(drop=True)
)

procedure_utilization_burden = (
    procedure_summary[
        [
            "CODE",
            "CANONICAL_DESCRIPTION",
            "Procedure_Count",
            "Unique_Patients",
            "Unique_Encounters",
            "Procedures_Per_Patient",
            "Procedures_Per_Encounter",
            "Total_Procedure_Cost"
        ]
    ]
    .sort_values(
        "Procedures_Per_Patient",
        ascending=False
    )
    .reset_index(drop=True)
)

procedure_repeat_analysis = high_repeat_procedures_i.copy()


# ============================================================================
# 38. FINAL OUTPUT REPORT
# ============================================================================

print("\n" + "=" * 70)
print("STEP 4.18I COMPLETE")
print("=" * 70)

print(f"Total procedure records: {len(work):,}")
print(f"Unique procedure codes: {unique_codes:,}")
print(f"Unique canonical descriptions: {unique_canonical:,}")

print(f"Total observed procedure cost: {TOTAL_COST:,.2f}")
print(f"Total non-431 procedure cost: {TOTAL_NON_431_COST:,.2f}")

print(f"431 record share: {RECORD_SHARE_431:.2f}%")
print(f"431 cost share: {COST_SHARE_431:.2f}%")

print(
    f"Top 10 total-cost concentration: "
    f"{top10_cost_share:.2f}%"
)

print(
    f"Top 20 total-cost concentration: "
    f"{top20_cost_share:.2f}%"
)

print(
    f"Top 10 non-431 cost concentration: "
    f"{top10_non431_share:.2f}%"
)

print(
    f"Top 20 non-431 cost concentration: "
    f"{top20_non431_share:.2f}%"
)

print(
    f"Top 10 procedure volume concentration: "
    f"{top10_volume_share:.2f}%"
)

print(
    f"Top 20 procedure volume concentration: "
    f"{top20_volume_share:.2f}%"
)

print(
    f"Critical financial priority groups: "
    f"{len(critical_procedure_priority):,}"
)

print(
    f"High financial priority groups: "
    f"{len(high_financial_priority):,}"
)

print(
    f"High patient-cost groups: "
    f"{len(high_patient_cost_i):,}"
)

print(
    f"High repeat-utilization groups: "
    f"{len(high_repeat_procedures_i):,}"
)

print(
    f"431-dominated groups: "
    f"{dependency_counts.get('431_DOMINATED', 0):,}"
)

print("\nANALYTICAL DATASETS CREATED:")
print("  - procedure_i")
print("  - procedure_executive_scorecard")
print("  - procedure_executive_priority")
print("  - procedure_financial_concentration")
print("  - procedure_volume_concentration")
print("  - procedure_cost_patient_analysis")
print("  - procedure_utilization_burden")
print("  - procedure_repeat_analysis")
print("  - procedure_431_dependency")
print("  - procedure_action_matrix")
print("  - patient_procedure_summary")
print("  - high_procedure_burden_patients")
print("  - critical_procedure_priority")
print("  - high_financial_priority")
print("  - high_cost_high_utilization_i")
print("  - high_cost_low_utilization_i")
print("  - high_utilization_low_cost_i")
print("  - high_patient_cost_i")
print("  - high_repeat_procedures_i")
print("  - high_cost_per_patient")
print("  - procedure_431_dependency")
print("  - priority_distribution")
print("  - executive_procedure_kpis")
print("  - procedure_insight_summary")
print("  - procedure_i_validation")

print("\nSTATUS: PASS");
print("=" * 70)

======================================================================
STEP 4.18I — PROCEDURE EXECUTIVE / CLINICAL INSIGHT &
             ACTION PRIORITIZATION
======================================================================

SOURCE DATA DISCOVERY
----------------------------------------------------------------------
Using source dataset: procedure_h
Source records: 47,701

COLUMN RESOLUTION
----------------------------------------------------------------------
CODE:                    CODE
ORIGINAL_CODE:           ORIGINAL_CODE
CANONICAL_DESCRIPTION:   CANONICAL_DESCRIPTION
ORIGINAL_DESCRIPTION:    ORIGINAL_DESCRIPTION
PATIENT:                 PATIENT
ENCOUNTER:               ENCOUNTER
BASE_COST:               BASE_COST
PROCEDURE_COST:          BASE_COST

SOURCE DATA CHECK
----------------------------------------------------------------------
STATUS: PASS
Procedure records available: 47,701

ANALYTICAL DATASET VALIDATION
----------------------------------------------------------------------
Records: 47,701
Unique procedure codes: 157
Unique canonical descriptions: 157

CANONICALIZATION INTEGRITY
----------------------------------------------------------------------
Missing canonical descriptions: 0
Blank canonical descriptions: 0
Codes with multiple canonical descriptions: 0
Canonicalization integrity: PASS

PROCEDURE EXECUTIVE KPIs
----------------------------------------------------------------------
Total procedure records: 47,701
Unique procedure codes: 157
Unique canonical descriptions: 157
Unique patients: 793
Unique encounters: 14,670

Total procedure cost: 105,517,711.00
431 cost: 13,355,828.00
Non-431 cost: 92,161,883.00

431 record share: 64.96%
431 cost share: 12.66%
Non-431 cost share: 87.34%

PROCEDURE COST CONCENTRATION
----------------------------------------------------------------------
Top 1 total-cost share: 33.95%
Top 5 total-cost share: 54.37%
Top 10 total-cost share: 65.57%
Top 20 total-cost share: 78.71%

Top 5 non-431 cost share: 62.25%
Top 10 non-431 cost share: 74.61%
Top 20 non-431 cost share: 85.60%

PROCEDURE VOLUME CONCENTRATION
----------------------------------------------------------------------
Top 5 volume share: 39.87%
Top 10 volume share: 63.40%
Top 20 volume share: 82.29%

ANALYTICAL THRESHOLDS
----------------------------------------------------------------------
High non-431 cost threshold: 241,246.00
High utilization threshold: 121.00
High cost-per-patient threshold: 11,643.45
High repeat-utilization threshold: 3.04
Extreme non-431 cost threshold: 955,714.60
Extreme utilization threshold: 669.20

TOP EXECUTIVE PRIORITY PROCEDURES
----------------------------------------------------------------------
     CODE                                   CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Total_Procedure_Cost  Non_431_Total_Cost  Cost_Per_Patient  Procedures_Per_Patient  Cost_431_Share          Executive_Priority
180325003                                Electrical cardioversion             1383               74              35824002            35824002     484108.135135               18.689189        0.000000 CRITICAL_FINANCIAL_PRIORITY
225158009                         Auscultation of the fetal heart             1065               71               5657822             5657822      79687.633803               15.000000        0.000000 CRITICAL_FINANCIAL_PRIORITY
274804006                     Evaluation of uterine fundal height             1065               71               5631281             5631281      79313.816901               15.000000        0.000000 CRITICAL_FINANCIAL_PRIORITY
265764009                              Renal dialysis (procedure)             2746                5               2757221             2757221     551444.200000              549.200000        0.000000 CRITICAL_FINANCIAL_PRIORITY
703423002 Combined chemotherapy and radiation therapy (procedure)              444               21               5237596             5237596     249409.333333               21.142857        0.000000     HIGH_FINANCIAL_PRIORITY
127783003                                  Spirometry (procedure)              209               23               1628688             1628688      70812.521739                9.086957        0.000000     HIGH_FINANCIAL_PRIORITY
 76601001                                 Intramuscular injection              522               45               1325634             1325634      29458.533333               11.600000        0.000000     HIGH_FINANCIAL_PRIORITY
 18286008                    Catheter ablation of tissue of heart              365               54               3405999             3405999      63074.055556                6.759259        0.000000     HIGH_FINANCIAL_PRIORITY
228557008       Cognitive and behavioral therapy (regime/therapy)              136               17               1412779             1412779      83104.647059                8.000000        0.000000     HIGH_FINANCIAL_PRIORITY
430193006                   Medication Reconciliation (procedure)             2284              418               1162840             1160254       2781.913876                5.464115        0.222387 CRITICAL_FINANCIAL_PRIORITY
 73761001                                             Colonoscopy              424              233               5021003             5021003      21549.369099                1.819742        0.000000     HIGH_FINANCIAL_PRIORITY
 15081005               Pulmonary rehabilitation (regime/therapy)              171               12                326546              326546      27212.166667               14.250000        0.000000     HIGH_FINANCIAL_PRIORITY
385763009                           Hospice care (regime/therapy)             4098               61               1766238                   0      28954.721311               67.180328      100.000000           HIGH_PATIENT_COST
312681000                           Bone density scan (procedure)              198              115               1901367             1901367      16533.626087                1.721739        0.000000     HIGH_FINANCIAL_PRIORITY
169230002                     Ultrasound scan for fetal viability              184               81               1693824             1693824      20911.407407                2.271605        0.000000     HIGH_FINANCIAL_PRIORITY
180256009                              Subcutaneous immunotherapy               54                1                639117              639117     639117.000000               54.000000        0.000000           HIGH_PATIENT_COST
305351004                                Admit to ICU (procedure)                5                2               1031302             1031302     515651.000000                2.500000        0.000000           HIGH_PATIENT_COST
 33195004                  Teleradiotherapy procedure (procedure)              170                5                169567              169567      33913.400000               34.000000        0.000000           HIGH_PATIENT_COST
302497006                                Hemodialysis (procedure)               27                4                791088              791088     197772.000000                6.750000        0.000000           HIGH_PATIENT_COST
252160004                                 Standard pregnancy test              184               81                955125              955125      11791.666667                2.271605        0.000000     HIGH_FINANCIAL_PRIORITY

HIGH COST / HIGH UTILIZATION
----------------------------------------------------------------------
     CODE                                           CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Total_Procedure_Cost  Non_431_Total_Cost  Cost_Per_Patient  Procedures_Per_Patient  Cost_431_Share          Executive_Priority
180325003                                        Electrical cardioversion             1383               74              35824002            35824002     484108.135135               18.689189        0.000000 CRITICAL_FINANCIAL_PRIORITY
225158009                                 Auscultation of the fetal heart             1065               71               5657822             5657822      79687.633803               15.000000        0.000000 CRITICAL_FINANCIAL_PRIORITY
274804006                             Evaluation of uterine fundal height             1065               71               5631281             5631281      79313.816901               15.000000        0.000000 CRITICAL_FINANCIAL_PRIORITY
703423002         Combined chemotherapy and radiation therapy (procedure)              444               21               5237596             5237596     249409.333333               21.142857        0.000000     HIGH_FINANCIAL_PRIORITY
 73761001                                                     Colonoscopy              424              233               5021003             5021003      21549.369099                1.819742        0.000000     HIGH_FINANCIAL_PRIORITY
 18286008                            Catheter ablation of tissue of heart              365               54               3405999             3405999      63074.055556                6.759259        0.000000     HIGH_FINANCIAL_PRIORITY
265764009                                      Renal dialysis (procedure)             2746                5               2757221             2757221     551444.200000              549.200000        0.000000 CRITICAL_FINANCIAL_PRIORITY
312681000                                   Bone density scan (procedure)              198              115               1901367             1901367      16533.626087                1.721739        0.000000     HIGH_FINANCIAL_PRIORITY
169230002                             Ultrasound scan for fetal viability              184               81               1693824             1693824      20911.407407                2.271605        0.000000     HIGH_FINANCIAL_PRIORITY
127783003                                          Spirometry (procedure)              209               23               1628688             1628688      70812.521739                9.086957        0.000000     HIGH_FINANCIAL_PRIORITY
228557008               Cognitive and behavioral therapy (regime/therapy)              136               17               1412779             1412779      83104.647059                8.000000        0.000000     HIGH_FINANCIAL_PRIORITY
 76601001                                         Intramuscular injection              522               45               1325634             1325634      29458.533333               11.600000        0.000000     HIGH_FINANCIAL_PRIORITY
430193006                           Medication Reconciliation (procedure)             2284              418               1162840             1160254       2781.913876                5.464115        0.222387 CRITICAL_FINANCIAL_PRIORITY
252160004                                         Standard pregnancy test              184               81                955125              955125      11791.666667                2.271605        0.000000     HIGH_FINANCIAL_PRIORITY
 90226004 Cytopathology procedure - preparation of smear - genital source              258               85                516527              516527       6076.788235                3.035294        0.000000     HIGH_FINANCIAL_PRIORITY
104091002                        Hemoglobin / Hematocrit / Platelet count              237               71                480661              480661       6769.873239                3.338028        0.000000     HIGH_FINANCIAL_PRIORITY
 15081005                       Pulmonary rehabilitation (regime/therapy)              171               12                326546              326546      27212.166667               14.250000        0.000000     HIGH_FINANCIAL_PRIORITY
443529005 Screening for chromosomal aneuploidy in prenatal amniotic fluid              121               69                242841              242841       3519.434783                1.753623        0.000000     HIGH_FINANCIAL_PRIORITY

HIGH COST / LOWER UTILIZATION
----------------------------------------------------------------------
     CODE                                                           CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Total_Procedure_Cost  Non_431_Total_Cost  Cost_Per_Patient  Procedures_Per_Patient  Cost_431_Share      Executive_Priority
433112001 Percutaneous mechanical thrombectomy of portal vein using fluoroscopic guidance               57               55               1152998             1152998      20963.600000                1.036364             0.0 HIGH_FINANCIAL_PRIORITY
305351004                                                        Admit to ICU (procedure)                5                2               1031302             1031302     515651.000000                2.500000             0.0       HIGH_PATIENT_COST
288086009                                                               Suture open wound              103               93                956599              956599      10286.010753                1.107527             0.0 HIGH_FINANCIAL_PRIORITY
302497006                                                        Hemodialysis (procedure)               27                4                791088              791088     197772.000000                6.750000             0.0       HIGH_PATIENT_COST
399208008                                                               Plain chest X-ray               90               67                704168              704168      10509.970149                1.343284             0.0 HIGH_FINANCIAL_PRIORITY
180256009                                                      Subcutaneous immunotherapy               54                1                639117              639117     639117.000000               54.000000             0.0       HIGH_PATIENT_COST
274031008                                                              Rectal polypectomy               61               52                624125              624125      12002.403846                1.173077             0.0 HIGH_FINANCIAL_PRIORITY
 65200003                                  Insertion of intrauterine contraceptive device               66               46                593949              593949      12911.934783                1.434783             0.0 HIGH_FINANCIAL_PRIORITY
169553002                                         Insertion of subcutaneous contraceptive               62               42                548328              548328      13055.428571                1.476190             0.0 HIGH_FINANCIAL_PRIORITY
 46706006                                Replacement of contraceptive intrauterine device               61               38                511534              511534      13461.421053                1.605263             0.0 HIGH_FINANCIAL_PRIORITY
269911007                                                  Sputum examination (procedure)               71               68                456479              456479       6712.926471                1.044118             0.0 HIGH_FINANCIAL_PRIORITY
232717009                                                 Coronary artery bypass grafting                9                8                423773              423773      52971.625000                1.125000             0.0       HIGH_PATIENT_COST
301807007                                           Removal of subcutaneous contraceptive               39               26                367162              367162      14121.615385                1.500000             0.0 HIGH_FINANCIAL_PRIORITY
 68254000                                                  Removal of intrauterine device               38               31                360947              360947      11643.451613                1.225806             0.0 HIGH_FINANCIAL_PRIORITY
399014008                              Vaccination for diphtheria  pertussis  and tetanus              119               70                311798              311798       4454.257143                1.700000             0.0 HIGH_FINANCIAL_PRIORITY
104435004                                 Screening for occult blood in feces (procedure)               49               49                309715              309715       6320.714286                1.000000             0.0 HIGH_FINANCIAL_PRIORITY
714812005                                                Induced termination of pregnancy               32               23                308512              308512      13413.565217                1.391304             0.0 HIGH_FINANCIAL_PRIORITY
268556000                                                     Urine screening for glucose              119               70                250845              250845       3583.500000                1.700000             0.0 HIGH_FINANCIAL_PRIORITY
275833003                                                          Alpha-fetoprotein test              116               69                242197              242197       3510.101449                1.681159             0.0 HIGH_FINANCIAL_PRIORITY
117010004                                                                   Urine culture              118               68                242047              242047       3559.514706                1.735294             0.0 HIGH_FINANCIAL_PRIORITY

HIGH UTILIZATION / LOWER NON-431 COST
----------------------------------------------------------------------
             CODE                                                                CANONICAL_DESCRIPTION  Procedure_Count  Unique_Patients  Total_Procedure_Cost  Non_431_Total_Cost  Cost_Per_Patient  Procedures_Per_Patient  Cost_431_Share        Executive_Priority
        710824005                               Assessment of health and social care needs (procedure)             4596              509               1980876                   0       3891.701375                9.029470           100.0 HIGH_UTILIZATION_PRIORITY
        385763009                                                        Hospice care (regime/therapy)             4098               61               1766238                   0      28954.721311               67.180328           100.0         HIGH_PATIENT_COST
        171207006                                                                 Depression screening             3804              544               1639524                   0       3013.830882                6.992647           100.0 HIGH_UTILIZATION_PRIORITY
  454711000124102   Depression screening using Patient Health Questionnaire Two-Item score (procedure)             3614              500               1557634                   0       3115.268000                7.228000           100.0 HIGH_UTILIZATION_PRIORITY
  428211000124100                                              Assessment of substance use (procedure)             2906              436               1252486                   0       2872.674312                6.665138           100.0 HIGH_UTILIZATION_PRIORITY
        762993000                                        Assessment using Morse Fall Scale (procedure)             2422              268               1043882                   0       3895.082090                9.037313           100.0 HIGH_UTILIZATION_PRIORITY
        710841007                                                    Assessment of anxiety (procedure)             2288              437                986128                   0       2256.585812                5.235698           100.0 HIGH_UTILIZATION_PRIORITY
        713106006                                                 Screening for drug abuse (procedure)             1484              333                639604                   0       1920.732733                4.456456           100.0 HIGH_UTILIZATION_PRIORITY

In [139]:
# ======================================================================
# STEP 4.18I — PROCEDURE-LEVEL EXECUTIVE / CLINICAL INSIGHT ENGINE
#              COST • UTILIZATION • PATIENT BURDEN • REPEAT USE
#              OUTLIERS • CONCENTRATION • 431/NON-431 • PRIORITIZATION
# ======================================================================

import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
pd.set_option("display.width", 240)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")


# ======================================================================
# 1. SOURCE DATA DISCOVERY
# ======================================================================

print("=" * 70)
print("STEP 4.18I — PROCEDURE-LEVEL EXECUTIVE / CLINICAL INSIGHT ENGINE")
print("=" * 70)

# Use existing Step 4.18H analytical dataset
if "procedure_h" in globals():
    source_df = procedure_h.copy()
    source_name = "procedure_h"

elif "procedure_g" in globals():
    source_df = procedure_g.copy()
    source_name = "procedure_g"

else:
    raise ValueError(
        "Neither 'procedure_h' nor 'procedure_g' exists. "
        "Run Step 4.18H or Step 4.18G first."
    )

print("\nSOURCE DATA DISCOVERY")
print("-" * 70)
print(f"Using source dataset: {source_name}")
print(f"Source records: {len(source_df):,}")


# ======================================================================
# 2. SOURCE COLUMN VALIDATION
# ======================================================================

required_columns = [
    "CODE",
    "DESCRIPTION",
    "CANONICAL_DESCRIPTION",
    "BASE_COST",
    "PATIENT",
    "ENCOUNTER"
]

missing_columns = [
    col for col in required_columns
    if col not in source_df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

print("\nSOURCE DATA CHECK")
print("-" * 70)
print("STATUS: PASS")
print(f"Procedure records available: {len(source_df):,}")


# ======================================================================
# 3. RECORD PRESERVATION
# ======================================================================

original_record_count = len(source_df)

procedure_i = source_df.copy()

if len(procedure_i) != original_record_count:
    raise ValueError("Record count changed during source preparation.")

print("\nRECORD PRESERVATION")
print("-" * 70)
print(f"Source records: {original_record_count:,}")
print(f"Analytical records: {len(procedure_i):,}")
print(f"Record count preserved: {len(procedure_i) == original_record_count}")


# ======================================================================
# 4. ORIGINAL VALUE PRESERVATION
# ======================================================================

procedure_i["ORIGINAL_CODE"] = procedure_i["CODE"]
procedure_i["ORIGINAL_DESCRIPTION"] = procedure_i["DESCRIPTION"]

print("\nORIGINAL VALUE PRESERVATION")
print("-" * 70)
print(
    f"Original CODE preserved: "
    f"{procedure_i['ORIGINAL_CODE'].equals(procedure_i['CODE'])}"
)

print(
    f"Original DESCRIPTION preserved: "
    f"{procedure_i['ORIGINAL_DESCRIPTION'].equals(procedure_i['DESCRIPTION'])}"
)


# ======================================================================
# 5. DATA TYPE STANDARDIZATION
# ======================================================================

procedure_i["CODE"] = procedure_i["CODE"].astype(str).str.strip()

procedure_i["CANONICAL_DESCRIPTION"] = (
    procedure_i["CANONICAL_DESCRIPTION"]
    .astype(str)
    .str.strip()
)

procedure_i["PATIENT"] = procedure_i["PATIENT"].astype(str).str.strip()
procedure_i["ENCOUNTER"] = procedure_i["ENCOUNTER"].astype(str).str.strip()

procedure_i["BASE_COST"] = pd.to_numeric(
    procedure_i["BASE_COST"],
    errors="coerce"
)

if procedure_i["BASE_COST"].isna().any():
    raise ValueError(
        "BASE_COST contains missing or non-numeric values."
    )


# ======================================================================
# 6. BASE COST SEGMENTATION
# ======================================================================

procedure_i["IS_431"] = (
    procedure_i["BASE_COST"] == 431
)

procedure_i["IS_NON_431"] = (
    procedure_i["BASE_COST"] != 431
)

procedure_i["NON_431_COST"] = np.where(
    procedure_i["IS_NON_431"],
    procedure_i["BASE_COST"],
    0
)

total_records = len(procedure_i)

records_431 = int(procedure_i["IS_431"].sum())
records_non_431 = int(procedure_i["IS_NON_431"].sum())

total_cost = procedure_i["BASE_COST"].sum()
cost_431 = procedure_i.loc[
    procedure_i["IS_431"], "BASE_COST"
].sum()

non_431_cost = procedure_i["NON_431_COST"].sum()

print("\nBASE_COST SEGMENTATION")
print("-" * 70)
print(f"431 records: {records_431:,}")
print(f"Non-431 records: {records_non_431:,}")
print(f"431 record share: {(records_431 / total_records) * 100:.2f}%")
print(f"Total procedure cost: {total_cost:,.2f}")
print(f"431 cost: {cost_431:,.2f}")
print(f"Non-431 cost: {non_431_cost:,.2f}")
print(f"431 cost share: {(cost_431 / total_cost) * 100:.2f}%")
print(f"Non-431 cost share: {(non_431_cost / total_cost) * 100:.2f}%")


# ======================================================================
# 7. PROCEDURE-LEVEL EXECUTIVE SUMMARY
# ======================================================================

procedure_summary = (
    procedure_i
    .groupby(
        ["CODE", "CANONICAL_DESCRIPTION"],
        dropna=False
    )
    .agg(
        Procedure_Count=("CODE", "size"),
        Unique_Patients=("PATIENT", "nunique"),
        Unique_Encounters=("ENCOUNTER", "nunique"),
        Total_Procedure_Cost=("BASE_COST", "sum"),
        Non_431_Total_Cost=("NON_431_COST", "sum"),
        Cost_431=("IS_431", "sum")
    )
    .reset_index()
)

procedure_summary["Average_Procedure_Cost"] = (
    procedure_summary["Total_Procedure_Cost"]
    / procedure_summary["Procedure_Count"]
)

procedure_summary["Cost_Per_Patient"] = np.where(
    procedure_summary["Unique_Patients"] > 0,
    procedure_summary["Total_Procedure_Cost"]
    / procedure_summary["Unique_Patients"],
    0
)

procedure_summary["Non_431_Cost_Per_Patient"] = np.where(
    procedure_summary["Unique_Patients"] > 0,
    procedure_summary["Non_431_Total_Cost"]
    / procedure_summary["Unique_Patients"],
    0
)

procedure_summary["Procedures_Per_Patient"] = np.where(
    procedure_summary["Unique_Patients"] > 0,
    procedure_summary["Procedure_Count"]
    / procedure_summary["Unique_Patients"],
    0
)

procedure_summary["Procedures_Per_Encounter"] = np.where(
    procedure_summary["Unique_Encounters"] > 0,
    procedure_summary["Procedure_Count"]
    / procedure_summary["Unique_Encounters"],
    0
)

procedure_summary["Cost_431_Share"] = np.where(
    procedure_summary["Total_Procedure_Cost"] > 0,
    (
        procedure_summary["Cost_431"]
        * 431
        / procedure_summary["Total_Procedure_Cost"]
    ) * 100,
    0
)

procedure_summary["Non_431_Cost_Share"] = np.where(
    procedure_summary["Total_Procedure_Cost"] > 0,
    (
        procedure_summary["Non_431_Total_Cost"]
        / procedure_summary["Total_Procedure_Cost"]
    ) * 100,
    0
)


# ======================================================================
# 8. COST CONCENTRATION
# ======================================================================

cost_ranked = procedure_summary.sort_values(
    "Total_Procedure_Cost",
    ascending=False
).reset_index(drop=True)

cost_ranked["Cumulative_Cost"] = (
    cost_ranked["Total_Procedure_Cost"].cumsum()
)

cost_ranked["Cumulative_Cost_Share"] = (
    cost_ranked["Cumulative_Cost"]
    / total_cost
) * 100

top_5_cost_share = (
    cost_ranked.head(5)["Total_Procedure_Cost"].sum()
    / total_cost
) * 100

top_10_cost_share = (
    cost_ranked.head(10)["Total_Procedure_Cost"].sum()
    / total_cost
) * 100

top_20_cost_share = (
    cost_ranked.head(20)["Total_Procedure_Cost"].sum()
    / total_cost
) * 100


# ======================================================================
# 9. NON-431 COST CONCENTRATION
# ======================================================================

non431_ranked = procedure_summary.sort_values(
    "Non_431_Total_Cost",
    ascending=False
).reset_index(drop=True)

non431_ranked["Cumulative_Non_431_Cost"] = (
    non431_ranked["Non_431_Total_Cost"].cumsum()
)

non431_ranked["Cumulative_Non_431_Cost_Share"] = np.where(
    non_431_cost > 0,
    (
        non431_ranked["Cumulative_Non_431_Cost"]
        / non_431_cost
    ) * 100,
    0
)

top_5_non431_share = (
    non431_ranked.head(5)["Non_431_Total_Cost"].sum()
    / non_431_cost
) * 100

top_10_non431_share = (
    non431_ranked.head(10)["Non_431_Total_Cost"].sum()
    / non_431_cost
) * 100

top_20_non431_share = (
    non431_ranked.head(20)["Non_431_Total_Cost"].sum()
    / non_431_cost
) * 100


# ======================================================================
# 10. UTILIZATION CONCENTRATION
# ======================================================================

util_ranked = procedure_summary.sort_values(
    "Procedure_Count",
    ascending=False
).reset_index(drop=True)

util_ranked["Cumulative_Volume"] = (
    util_ranked["Procedure_Count"].cumsum()
)

util_ranked["Cumulative_Volume_Share"] = (
    util_ranked["Cumulative_Volume"]
    / total_records
) * 100

top_5_volume_share = (
    util_ranked.head(5)["Procedure_Count"].sum()
    / total_records
) * 100

top_10_volume_share = (
    util_ranked.head(10)["Procedure_Count"].sum()
    / total_records
) * 100

top_20_volume_share = (
    util_ranked.head(20)["Procedure_Count"].sum()
    / total_records
) * 100


# ======================================================================
# 11. PATIENT-LEVEL PROCEDURE BURDEN
# ======================================================================

patient_procedure_summary = (
    procedure_i
    .groupby("PATIENT")
    .agg(
        Total_Procedures=("CODE", "size"),
        Unique_Procedure_Types=("CODE", "nunique"),
        Unique_Encounters=("ENCOUNTER", "nunique"),
        Total_Procedure_Cost=("BASE_COST", "sum"),
        Non_431_Procedure_Cost=("NON_431_COST", "sum"),
        Procedure_431_Count=("IS_431", "sum")
    )
    .reset_index()
)

patient_procedure_summary["Procedures_Per_Encounter"] = np.where(
    patient_procedure_summary["Unique_Encounters"] > 0,
    patient_procedure_summary["Total_Procedures"]
    / patient_procedure_summary["Unique_Encounters"],
    0
)

patient_procedure_summary["Non_431_Cost_Share"] = np.where(
    patient_procedure_summary["Total_Procedure_Cost"] > 0,
    (
        patient_procedure_summary["Non_431_Procedure_Cost"]
        / patient_procedure_summary["Total_Procedure_Cost"]
    ) * 100,
    0
)


# ======================================================================
# 12. PATIENT BURDEN THRESHOLDS
# ======================================================================

burden_procedure_threshold = (
    patient_procedure_summary["Total_Procedures"].quantile(0.95)
)

burden_cost_threshold = (
    patient_procedure_summary["Total_Procedure_Cost"].quantile(0.95)
)

high_procedure_burden_patients = (
    patient_procedure_summary[
        (
            patient_procedure_summary["Total_Procedures"]
            >= burden_procedure_threshold
        )
        |
        (
            patient_procedure_summary["Total_Procedure_Cost"]
            >= burden_cost_threshold
        )
    ]
    .sort_values(
        ["Total_Procedure_Cost", "Total_Procedures"],
        ascending=False
    )
    .reset_index(drop=True)
)


# ======================================================================
# 13. REPEAT UTILIZATION
# ======================================================================

procedure_summary["Repeat_Utilization_Flag"] = (
    procedure_summary["Procedures_Per_Patient"]
    > 1
)

repeat_ranked = procedure_summary.sort_values(
    "Procedures_Per_Patient",
    ascending=False
).reset_index(drop=True)

high_repeat_threshold = (
    procedure_summary["Procedures_Per_Patient"]
    .quantile(0.90)
)

high_repeat_utilization = (
    procedure_summary[
        procedure_summary["Procedures_Per_Patient"]
        >= high_repeat_threshold
    ]
    .sort_values(
        "Procedures_Per_Patient",
        ascending=False
    )
    .reset_index(drop=True)
)


# ======================================================================
# 14. COST-PER-PATIENT OUTLIERS
# ======================================================================

cost_per_patient_threshold = (
    procedure_summary["Cost_Per_Patient"]
    .quantile(0.90)
)

high_cost_per_patient = (
    procedure_summary[
        procedure_summary["Cost_Per_Patient"]
        >= cost_per_patient_threshold
    ]
    .sort_values(
        "Cost_Per_Patient",
        ascending=False
    )
    .reset_index(drop=True)
)


# ======================================================================
# 15. NON-431 COST OUTLIERS
# ======================================================================

non431_cost_threshold = (
    procedure_summary["Non_431_Total_Cost"]
    .quantile(0.90)
)

high_cost_non431_procedures = (
    procedure_summary[
        procedure_summary["Non_431_Total_Cost"]
        >= non431_cost_threshold
    ]
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)


# ======================================================================
# 16. 431-DOMINATED PROCEDURES
# ======================================================================

procedures_431_dominated = (
    procedure_summary[
        procedure_summary["Cost_431_Share"] >= 90
    ]
    .sort_values(
        "Total_Procedure_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)


# ======================================================================
# 17. HIGH VOLUME / LOW COST
# ======================================================================

utilization_threshold = (
    procedure_summary["Procedure_Count"]
    .quantile(0.90)
)

high_utilization_low_cost = (
    procedure_summary[
        (
            procedure_summary["Procedure_Count"]
            >= utilization_threshold
        )
        &
        (
            procedure_summary["Non_431_Total_Cost"]
            < non431_cost_threshold
        )
    ]
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .reset_index(drop=True)
)


# ======================================================================
# 18. HIGH COST / LOW UTILIZATION
# ======================================================================

high_cost_low_utilization = (
    procedure_summary[
        (
            procedure_summary["Non_431_Total_Cost"]
            >= non431_cost_threshold
        )
        &
        (
            procedure_summary["Procedure_Count"]
            < utilization_threshold
        )
    ]
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)


# ======================================================================
# 19. HIGH COST / HIGH UTILIZATION
# ======================================================================

high_cost_high_utilization = (
    procedure_summary[
        (
            procedure_summary["Non_431_Total_Cost"]
            >= non431_cost_threshold
        )
        &
        (
            procedure_summary["Procedure_Count"]
            >= utilization_threshold
        )
    ]
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)


# ======================================================================
# 20. PROCEDURE BURDEN / COST EFFICIENCY PROFILE
# ======================================================================

procedure_summary["Cost_Burden_Index"] = np.where(
    total_cost > 0,
    (
        procedure_summary["Total_Procedure_Cost"]
        / total_cost
    ) * 100,
    0
)

procedure_summary["Volume_Burden_Index"] = (
    procedure_summary["Procedure_Count"]
    / total_records
) * 100

procedure_summary["Cost_vs_Volume_Ratio"] = np.where(
    procedure_summary["Volume_Burden_Index"] > 0,
    procedure_summary["Cost_Burden_Index"]
    / procedure_summary["Volume_Burden_Index"],
    0
)


# ======================================================================
# 21. COST/VOLUME IMBALANCE FLAGS
# ======================================================================

procedure_summary["Cost_Volume_Profile"] = np.select(
    [
        (
            procedure_summary["Cost_Burden_Index"]
            >= procedure_summary["Cost_Burden_Index"].quantile(0.75)
        )
        &
        (
            procedure_summary["Volume_Burden_Index"]
            >= procedure_summary["Volume_Burden_Index"].quantile(0.75)
        ),

        (
            procedure_summary["Cost_Burden_Index"]
            >= procedure_summary["Cost_Burden_Index"].quantile(0.75)
        )
        &
        (
            procedure_summary["Volume_Burden_Index"]
            < procedure_summary["Volume_Burden_Index"].quantile(0.75)
        ),

        (
            procedure_summary["Volume_Burden_Index"]
            >= procedure_summary["Volume_Burden_Index"].quantile(0.75)
        )
        &
        (
            procedure_summary["Cost_Burden_Index"]
            < procedure_summary["Cost_Burden_Index"].quantile(0.75)
        )
    ],
    [
        "HIGH_COST_HIGH_VOLUME",
        "HIGH_COST_LOW_VOLUME",
        "HIGH_VOLUME_LOW_COST"
    ],
    default="STANDARD"
)


# ======================================================================
# 22. EXECUTIVE PRIORITY SCORE
# ======================================================================

def percentile_score(series):
    return series.rank(pct=True) * 100


procedure_summary["Cost_Priority_Score"] = percentile_score(
    procedure_summary["Non_431_Total_Cost"]
)

procedure_summary["Volume_Priority_Score"] = percentile_score(
    procedure_summary["Procedure_Count"]
)

procedure_summary["Patient_Cost_Score"] = percentile_score(
    procedure_summary["Cost_Per_Patient"]
)

procedure_summary["Repeat_Use_Score"] = percentile_score(
    procedure_summary["Procedures_Per_Patient"]
)

procedure_summary["Priority_Score"] = (
    procedure_summary["Cost_Priority_Score"] * 0.35
    +
    procedure_summary["Volume_Priority_Score"] * 0.25
    +
    procedure_summary["Patient_Cost_Score"] * 0.20
    +
    procedure_summary["Repeat_Use_Score"] * 0.20
)


# ======================================================================
# 23. EXECUTIVE PRIORITY BANDS
# ======================================================================

procedure_summary["Executive_Priority"] = pd.cut(
    procedure_summary["Priority_Score"],
    bins=[-np.inf, 40, 60, 80, np.inf],
    labels=[
        "STANDARD",
        "MONITOR",
        "HIGH PRIORITY",
        "CRITICAL PRIORITY"
    ]
)


# ======================================================================
# 24. CLINICAL / OPERATIONAL INSIGHT FLAGS
# ======================================================================

procedure_summary["Insight_Flags"] = ""

def add_flag(df, condition, flag):
    df.loc[
        condition,
        "Insight_Flags"
    ] = np.where(
        df.loc[condition, "Insight_Flags"].eq(""),
        flag,
        df.loc[condition, "Insight_Flags"] + " | " + flag
    )


add_flag(
    procedure_summary,
    procedure_summary["Cost_Burden_Index"]
    >= procedure_summary["Cost_Burden_Index"].quantile(0.90),
    "TOP_COST_DRIVER"
)

add_flag(
    procedure_summary,
    procedure_summary["Volume_Burden_Index"]
    >= procedure_summary["Volume_Burden_Index"].quantile(0.90),
    "TOP_VOLUME_DRIVER"
)

add_flag(
    procedure_summary,
    procedure_summary["Cost_Per_Patient"]
    >= cost_per_patient_threshold,
    "HIGH_PATIENT_COST"
)

add_flag(
    procedure_summary,
    procedure_summary["Procedures_Per_Patient"]
    >= high_repeat_threshold,
    "HIGH_REPEAT_USE"
)

add_flag(
    procedure_summary,
    procedure_summary["Cost_431_Share"] >= 90,
    "431_DOMINATED"
)

add_flag(
    procedure_summary,
    (
        procedure_summary["Non_431_Total_Cost"]
        >= non431_cost_threshold
    )
    &
    (
        procedure_summary["Procedure_Count"]
        < utilization_threshold
    ),
    "HIGH_COST_LOW_VOLUME"
)

add_flag(
    procedure_summary,
    (
        procedure_summary["Procedure_Count"]
        >= utilization_threshold
    )
    &
    (
        procedure_summary["Non_431_Total_Cost"]
        < non431_cost_threshold
    ),
    "HIGH_VOLUME_LOW_COST"
)


# ======================================================================
# 25. PROCEDURE PRIORITY DATASET
# ======================================================================

procedure_priority = (
    procedure_summary
    .sort_values(
        [
            "Priority_Score",
            "Non_431_Total_Cost",
            "Procedure_Count"
        ],
        ascending=False
    )
    .reset_index(drop=True)
)

procedure_priority["Priority_Rank"] = (
    procedure_priority.index + 1
)


# ======================================================================
# 26. TOP EXECUTIVE PROCEDURES
# ======================================================================

top_executive_procedures = (
    procedure_priority
    .head(25)
    .copy()
)


# ======================================================================
# 27. EXECUTIVE INSIGHT METRICS
# ======================================================================

priority_counts = (
    procedure_summary["Executive_Priority"]
    .value_counts()
)

insight_metrics = pd.DataFrame({
    "Metric": [
        "Total Procedure Records",
        "Unique Procedure Codes",
        "Unique Canonical Procedures",
        "Total Procedure Cost",
        "431 Record Share",
        "431 Cost Share",
        "Non-431 Cost Share",
        "Top 5 Total Cost Concentration",
        "Top 10 Total Cost Concentration",
        "Top 20 Total Cost Concentration",
        "Top 5 Non-431 Cost Concentration",
        "Top 10 Non-431 Cost Concentration",
        "Top 20 Non-431 Cost Concentration",
        "Top 5 Procedure Volume Concentration",
        "Top 10 Procedure Volume Concentration",
        "Top 20 Procedure Volume Concentration",
        "High Repeat Utilization Procedures",
        "High Cost Per Patient Procedures",
        "431-Dominated Procedures",
        "High Cost / High Utilization Procedures",
        "High Cost / Low Utilization Procedures",
        "High Utilization / Lower Cost Procedures",
        "High Procedure-Burden Patients",
        "Critical Priority Procedures",
        "High Priority Procedures"
    ],
    "Value": [
        total_records,
        procedure_summary["CODE"].nunique(),
        procedure_summary["CANONICAL_DESCRIPTION"].nunique(),
        total_cost,
        (records_431 / total_records) * 100,
        (cost_431 / total_cost) * 100,
        (non_431_cost / total_cost) * 100,
        top_5_cost_share,
        top_10_cost_share,
        top_20_cost_share,
        top_5_non431_share,
        top_10_non431_share,
        top_20_non431_share,
        top_5_volume_share,
        top_10_volume_share,
        top_20_volume_share,
        len(high_repeat_utilization),
        len(high_cost_per_patient),
        len(procedures_431_dominated),
        len(high_cost_high_utilization),
        len(high_cost_low_utilization),
        len(high_utilization_low_cost),
        len(high_procedure_burden_patients),
        int(priority_counts.get("CRITICAL PRIORITY", 0)),
        int(priority_counts.get("HIGH PRIORITY", 0))
    ]
})


# ======================================================================
# 28. AUTOMATED EXECUTIVE INSIGHT SUMMARY
# ======================================================================

executive_insights = []

# Cost concentration
if top_10_non431_share >= 70:
    executive_insights.append(
        f"Non-431 procedure expenditure is highly concentrated: "
        f"the top 10 procedures account for {top_10_non431_share:.2f}% "
        f"of non-431 procedure cost."
    )
else:
    executive_insights.append(
        f"Non-431 procedure expenditure is moderately distributed: "
        f"the top 10 procedures account for {top_10_non431_share:.2f}% "
        f"of non-431 procedure cost."
    )

# Volume concentration
if top_10_volume_share >= 60:
    executive_insights.append(
        f"Procedure utilization is concentrated: the top 10 procedure "
        f"types account for {top_10_volume_share:.2f}% of all procedure records."
    )

# 431
if (cost_431 / total_cost) < (records_431 / total_records):
    executive_insights.append(
        "BASE_COST = 431 procedures represent a larger share of records "
        "than of total cost, indicating that this segment is relatively "
        "low-cost per observed procedure."
    )

# High cost/high utilization
if len(high_cost_high_utilization) > 0:
    executive_insights.append(
        f"{len(high_cost_high_utilization)} procedure groups meet both "
        "high-cost and high-utilization criteria and should receive "
        "priority operational and clinical review."
    )

# Repeat utilization
if len(high_repeat_utilization) > 0:
    executive_insights.append(
        f"{len(high_repeat_utilization)} procedure groups show unusually "
        "high repeat utilization relative to the procedure population."
    )

# Patient burden
if len(high_procedure_burden_patients) > 0:
    executive_insights.append(
        f"{len(high_procedure_burden_patients)} patients fall into the "
        "high procedure-burden segment based on the 95th-percentile "
        "procedure-volume or cost threshold."
    )

# 431 dominated
if len(procedures_431_dominated) > 0:
    executive_insights.append(
        f"{len(procedures_431_dominated)} procedure groups are "
        "431-cost dominated and should be interpreted separately from "
        "non-431 expenditure drivers."
    )

procedure_insight_summary = pd.DataFrame({
    "Insight_ID": range(1, len(executive_insights) + 1),
    "Executive_Insight": executive_insights
})


# ======================================================================
# 29. CLINICAL / OPERATIONAL WATCHLIST
# ======================================================================

procedure_watchlist = (
    procedure_summary[
        procedure_summary["Insight_Flags"] != ""
    ]
    .sort_values(
        [
            "Priority_Score",
            "Non_431_Total_Cost",
            "Procedure_Count"
        ],
        ascending=False
    )
    .reset_index(drop=True)
)

procedure_watchlist["Watchlist_Rank"] = (
    procedure_watchlist.index + 1
)


# ======================================================================
# 30. TOP COST PROCEDURES
# ======================================================================

top_cost_procedures = (
    procedure_summary
    .sort_values(
        "Total_Procedure_Cost",
        ascending=False
    )
    .head(20)
    .reset_index(drop=True)
)


# ======================================================================
# 31. TOP NON-431 COST
# ======================================================================

top_non_431_cost = (
    procedure_summary
    .sort_values(
        "Non_431_Total_Cost",
        ascending=False
    )
    .head(20)
    .reset_index(drop=True)
)


# ======================================================================
# 32. TOP UTILIZATION
# ======================================================================

top_utilization = (
    procedure_summary
    .sort_values(
        "Procedure_Count",
        ascending=False
    )
    .head(20)
    .reset_index(drop=True)
)


# ======================================================================
# 33. COST PER PATIENT
# ======================================================================

top_cost_per_patient = (
    procedure_summary
    .sort_values(
        "Cost_Per_Patient",
        ascending=False
    )
    .head(20)
    .reset_index(drop=True)
)


# ======================================================================
# 34. COST INTENSITY DISTRIBUTION
# ======================================================================

procedure_summary["Cost_Intensity"] = pd.cut(
    procedure_summary["Non_431_Total_Cost"],
    bins=[
        -np.inf,
        0,
        procedure_summary["Non_431_Total_Cost"].quantile(0.50),
        procedure_summary["Non_431_Total_Cost"].quantile(0.75),
        procedure_summary["Non_431_Total_Cost"].quantile(0.90),
        np.inf
    ],
    labels=[
        "431_DOMINATED",
        "STANDARD_NON_431_COST",
        "MODERATE_NON_431_COST",
        "HIGH_NON_431_COST",
        "EXTREME_NON_431_COST"
    ],
    include_lowest=True
)

cost_intensity_distribution = (
    procedure_summary["Cost_Intensity"]
    .value_counts(dropna=False)
    .rename_axis("Cost_Intensity")
    .reset_index(name="Procedure_Group_Count")
)

cost_intensity_distribution["Group_Share_%"] = (
    cost_intensity_distribution["Procedure_Group_Count"]
    / len(procedure_summary)
) * 100


# ======================================================================
# 35. UTILIZATION INTENSITY
# ======================================================================

procedure_summary["Utilization_Intensity"] = pd.cut(
    procedure_summary["Procedure_Count"],
    bins=[
        -np.inf,
        procedure_summary["Procedure_Count"].quantile(0.50),
        procedure_summary["Procedure_Count"].quantile(0.75),
        procedure_summary["Procedure_Count"].quantile(0.90),
        np.inf
    ],
    labels=[
        "STANDARD_UTILIZATION",
        "MODERATE_UTILIZATION",
        "HIGH_UTILIZATION",
        "EXTREME_UTILIZATION"
    ],
    include_lowest=True
)

utilization_intensity_distribution = (
    procedure_summary["Utilization_Intensity"]
    .value_counts(dropna=False)
    .rename_axis("Utilization_Intensity")
    .reset_index(name="Procedure_Group_Count")
)

utilization_intensity_distribution["Group_Share_%"] = (
    utilization_intensity_distribution["Procedure_Group_Count"]
    / len(procedure_summary)
) * 100


# ======================================================================
# 36. EXECUTIVE PRIORITY DISTRIBUTION
# ======================================================================

priority_distribution = (
    procedure_summary["Executive_Priority"]
    .value_counts()
    .rename_axis("Executive_Priority")
    .reset_index(name="Procedure_Group_Count")
)

priority_distribution["Group_Share_%"] = (
    priority_distribution["Procedure_Group_Count"]
    / len(procedure_summary)
) * 100


# ======================================================================
# 37. CONCENTRATION DATASET
# ======================================================================

procedure_concentration = procedure_summary[
    [
        "CODE",
        "CANONICAL_DESCRIPTION",
        "Procedure_Count",
        "Total_Procedure_Cost",
        "Non_431_Total_Cost"
    ]
].copy()

procedure_concentration = procedure_concentration.sort_values(
    "Total_Procedure_Cost",
    ascending=False
).reset_index(drop=True)

procedure_concentration["Cost_Rank"] = (
    procedure_concentration.index + 1
)

procedure_concentration["Cumulative_Cost"] = (
    procedure_concentration["Total_Procedure_Cost"].cumsum()
)

procedure_concentration["Cumulative_Cost_Share"] = (
    procedure_concentration["Cumulative_Cost"]
    / total_cost
) * 100

procedure_concentration["Cumulative_Volume"] = (
    procedure_concentration["Procedure_Count"].cumsum()
)

procedure_concentration["Cumulative_Volume_Share"] = (
    procedure_concentration["Cumulative_Volume"]
    / total_records
) * 100


# ======================================================================
# 38. FINAL VALIDATION
# ======================================================================

validation_results = {
    "Record count preserved":
        len(procedure_i) == original_record_count,

    "Original CODE preserved":
        procedure_i["ORIGINAL_CODE"].equals(
            source_df["CODE"]
        ),

    "Original DESCRIPTION preserved":
        procedure_i["ORIGINAL_DESCRIPTION"].equals(
            source_df["DESCRIPTION"]
        ),

    "Canonical descriptions available":
        procedure_i["CANONICAL_DESCRIPTION"]
        .notna()
        .all(),

    "No blank canonical descriptions":
        ~procedure_i["CANONICAL_DESCRIPTION"]
        .astype(str)
        .str.strip()
        .eq("")
        .any(),

    "One canonical description per CODE":
        procedure_i.groupby("CODE")[
            "CANONICAL_DESCRIPTION"
        ].nunique().max() == 1,

    "431 segmentation available":
        procedure_i["IS_431"].notna().all(),

    "Non-431 cost available":
        procedure_i["NON_431_COST"].notna().all(),

    "Procedure summary created":
        len(procedure_summary) > 0,

    "Patient procedure summary created":
        len(patient_procedure_summary) > 0,

    "Cost concentration calculated":
        len(procedure_concentration) > 0,

    "Priority score created":
        procedure_summary["Priority_Score"].notna().all(),

    "Executive priority created":
        procedure_summary["Executive_Priority"].notna().all(),

    "No records deleted":
        len(procedure_i) == original_record_count
}

procedure_i_validation = pd.DataFrame(
    list(validation_results.items()),
    columns=["Validation", "Result"]
)

print("\nFINAL VALIDATION")
print("-" * 70)
print(procedure_i_validation.to_string(index=False))


if not procedure_i_validation["Result"].all():
    raise ValueError(
        "STEP 4.18I validation failed. "
        "Review procedure_i_validation."
    )


# ======================================================================
# 39. FINAL EXECUTIVE OUTPUT
# ======================================================================

print("\n")
print("=" * 70)
print("STEP 4.18I COMPLETE")
print("=" * 70)

print(f"Total procedure records: {len(procedure_i):,}")
print(
    f"Unique procedure codes: "
    f"{procedure_summary['CODE'].nunique():,}"
)
print(
    f"Unique canonical descriptions: "
    f"{procedure_summary['CANONICAL_DESCRIPTION'].nunique():,}"
)

print(f"Total observed procedure cost: {total_cost:,.2f}")
print(f"Total non-431 procedure cost: {non_431_cost:,.2f}")

print(
    f"431 record share: "
    f"{(records_431 / total_records) * 100:.2f}%"
)

print(
    f"431 cost share: "
    f"{(cost_431 / total_cost) * 100:.2f}%"
)

print(
    f"Top 10 total-cost concentration: "
    f"{top_10_cost_share:.2f}%"
)

print(
    f"Top 20 total-cost concentration: "
    f"{top_20_cost_share:.2f}%"
)

print(
    f"Top 10 non-431 cost concentration: "
    f"{top_10_non431_share:.2f}%"
)

print(
    f"Top 20 non-431 cost concentration: "
    f"{top_20_non431_share:.2f}%"
)

print(
    f"Top 10 procedure-volume concentration: "
    f"{top_10_volume_share:.2f}%"
)

print(
    f"Top 20 procedure-volume concentration: "
    f"{top_20_volume_share:.2f}%"
)

print(
    f"High repeat-utilization procedures: "
    f"{len(high_repeat_utilization):,}"
)

print(
    f"High cost-per-patient procedures: "
    f"{len(high_cost_per_patient):,}"
)

print(
    f"High cost/high utilization procedures: "
    f"{len(high_cost_high_utilization):,}"
)

print(
    f"High cost/lower utilization procedures: "
    f"{len(high_cost_low_utilization):,}"
)

print(
    f"High utilization/lower cost procedures: "
    f"{len(high_utilization_low_cost):,}"
)

print(
    f"431-dominated procedures: "
    f"{len(procedures_431_dominated):,}"
)

print(
    f"High procedure-burden patients: "
    f"{len(high_procedure_burden_patients):,}"
)

print(
    f"Critical priority procedures: "
    f"{int(priority_counts.get('CRITICAL PRIORITY', 0)):,}"
)

print(
    f"High priority procedures: "
    f"{int(priority_counts.get('HIGH PRIORITY', 0)):,}"
)


# ======================================================================
# 40. DATASETS CREATED
# ======================================================================

print("\nANALYTICAL DATASETS CREATED:")
print("  - procedure_i")
print("  - procedure_summary")
print("  - top_cost_procedures")
print("  - top_non_431_cost")
print("  - top_utilization")
print("  - top_cost_per_patient")
print("  - high_repeat_utilization")
print("  - high_cost_per_patient")
print("  - high_cost_non431_procedures")
print("  - high_cost_high_utilization")
print("  - high_cost_low_utilization")
print("  - high_utilization_low_cost")
print("  - procedures_431_dominated")
print("  - patient_procedure_summary")
print("  - high_procedure_burden_patients")
print("  - procedure_concentration")
print("  - procedure_priority")
print("  - procedure_watchlist")
print("  - top_executive_procedures")
print("  - priority_distribution")
print("  - cost_intensity_distribution")
print("  - utilization_intensity_distribution")
print("  - insight_metrics")
print("  - procedure_insight_summary")
print("  - procedure_i_validation")

print("\nSTATUS: PASS")
print("=" * 70)

======================================================================
STEP 4.18I — PROCEDURE-LEVEL EXECUTIVE / CLINICAL INSIGHT ENGINE
======================================================================

SOURCE DATA DISCOVERY
----------------------------------------------------------------------
Using source dataset: procedure_h
Source records: 47,701

SOURCE DATA CHECK
----------------------------------------------------------------------
STATUS: PASS
Procedure records available: 47,701

RECORD PRESERVATION
----------------------------------------------------------------------
Source records: 47,701
Analytical records: 47,701
Record count preserved: True

ORIGINAL VALUE PRESERVATION
----------------------------------------------------------------------
Original CODE preserved: True
Original DESCRIPTION preserved: True

BASE_COST SEGMENTATION
----------------------------------------------------------------------
431 records: 30,988
Non-431 records: 16,713
431 record share: 64.96%
Total procedure cost: 105,517,711.00
431 cost: 13,355,828.00
Non-431 cost: 92,161,883.00
431 cost share: 12.66%
Non-431 cost share: 87.34%

FINAL VALIDATION
----------------------------------------------------------------------
                        Validation  Result
            Record count preserved    True
           Original CODE preserved    True
    Original DESCRIPTION preserved    True
  Canonical descriptions available    True
   No blank canonical descriptions    True
One canonical description per CODE    True
        431 segmentation available    True
            Non-431 cost available    True
         Procedure summary created    True
 Patient procedure summary created    True
     Cost concentration calculated    True
            Priority score created    True
        Executive priority created    True
                No records deleted    True


======================================================================
STEP 4.18I COMPLETE
======================================================================
Total procedure records: 47,701
Unique procedure codes: 157
Unique canonical descriptions: 157
Total observed procedure cost: 105,517,711.00
Total non-431 procedure cost: 92,161,883.00
431 record share: 64.96%
431 cost share: 12.66%
Top 10 total-cost concentration: 65.57%
Top 20 total-cost concentration: 78.71%
Top 10 non-431 cost concentration: 74.61%
Top 20 non-431 cost concentration: 85.60%
Top 10 procedure-volume concentration: 63.40%
Top 20 procedure-volume concentration: 82.29%
High repeat-utilization procedures: 16
High cost-per-patient procedures: 16
High cost/high utilization procedures: 5
High cost/lower utilization procedures: 11
High utilization/lower cost procedures: 11
431-dominated procedures: 46
High procedure-burden patients: 68
Critical priority procedures: 15
High priority procedures: 41

ANALYTICAL DATASETS CREATED:
  - procedure_i
  - procedure_summary
  - top_cost_procedures
  - top_non_431_cost
  - top_utilization
  - top_cost_per_patient
  - high_repeat_utilization
  - high_cost_per_patient
  - high_cost_non431_procedures
  - high_cost_high_utilization
  - high_cost_low_utilization
  - high_utilization_low_cost
  - procedures_431_dominated
  - patient_procedure_summary
  - high_procedure_burden_patients
  - procedure_concentration
  - procedure_priority
  - procedure_watchlist
  - top_executive_procedures
  - priority_distribution
  - cost_intensity_distribution
  - utilization_intensity_distribution
  - insight_metrics
  - procedure_insight_summary
  - procedure_i_validation

STATUS: PASS
======================================================================

In [140]:
# ============================================================
# STAGE 4.2 — CREATE AGE GROUPS
# ============================================================

encounters_clean["AGE_GROUP"] = pd.cut(
    encounters_clean["AGE_AT_ENCOUNTER"],
    bins=[-1, 17, 34, 49, 64, 79, float("inf")],
    labels=[
        "0–17",
        "18–34",
        "35–49",
        "50–64",
        "65–79",
        "80+"
    ],
    include_lowest=True
)

print("\nAGE GROUP DISTRIBUTION")
print("-" * 60)
print(
    encounters_clean["AGE_GROUP"]
    .value_counts()
    .sort_index()
)

AGE GROUP DISTRIBUTION
------------------------------------------------------------
AGE_GROUP
0–17         0
18–34     2085
35–49     3211
50–64     3504
65–79     4821
80+      14270
Name: count, dtype: int64

In [141]:
# ============================================================
# STAGE 4.2.1 — AGE GROUP QUALITY CHECK
# ============================================================

print("Total encounters:", len(encounters_clean))

print(
    "Age groups assigned:",
    encounters_clean["AGE_GROUP"].notna().sum()
)

print(
    "Missing age groups:",
    encounters_clean["AGE_GROUP"].isna().sum()
)

print("\nAge group percentages:")

age_group_summary = (
    encounters_clean["AGE_GROUP"]
    .value_counts(dropna=False)
    .sort_index()
    .to_frame("Encounter_Count")
)

age_group_summary["Percentage"] = (
    age_group_summary["Encounter_Count"]
    / len(encounters_clean)
    * 100
).round(2)

print(age_group_summary)

Total encounters: 27891
Age groups assigned: 27891
Missing age groups: 0

Age group percentages:
           Encounter_Count  Percentage
AGE_GROUP
0–17                     0        0.00
18–34                 2085        7.48
35–49                 3211       11.51
50–64                 3504       12.56
65–79                 4821       17.29
80+                  14270       51.16

In [142]:
encounter_volume = (
    encounters_clean["ENCOUNTERCLASS"]
    .value_counts()
    .reset_index()
)

encounter_volume.columns = [
    "Encounter_Type",
    "Encounters"
]

encounter_volume["Percentage"] = (
    encounter_volume["Encounters"]
    / len(encounters_clean)
    * 100
).round(2)

encounter_volume

  Encounter_Type  Encounters  Percentage
0     ambulatory       12537       44.95
1     outpatient        6300       22.59
2     urgentcare        3666       13.14
3      emergency        2322        8.33
4       wellness        1931        6.92
5      inpatient        1135        4.07

In [143]:
# ============================================================
# STAGE 4.3.1 — PATIENT AGE AT DEATH
# ============================================================

patients_clean["AGE_AT_DEATH"] = (
    patients_clean["DEATHDATE"] - patients_clean["BIRTHDATE"]
).dt.days / 365.25

patients_clean["AGE_AT_DEATH"] = (
    patients_clean["AGE_AT_DEATH"].round(1)
)

print("Age at death calculated successfully.")

print(
    patients_clean[
        ["Id", "BIRTHDATE", "DEATHDATE", "AGE_AT_DEATH"]
    ].head(10)
)

Age at death calculated successfully.
                                     Id  BIRTHDATE  DEATHDATE  AGE_AT_DEATH
0  5605b66b-e92d-c16c-1b83-b8bf7040d51f 1977-03-19        NaT           NaN
1  6e5ae27c-8038-7988-e2c0-25a103f01bfa 1940-02-19        NaT           NaN
2  8123d076-0886-9007-e956-d5864aa121a7 1958-06-04        NaT           NaN
3  770518e4-6133-648e-60c9-071eb2f0e2ce 1928-12-25 2017-09-29         88.80
4  f96addf5-81b9-0aab-7855-d208d3d352c5 1928-12-25 2014-02-23         85.20
5  8e9650d1-788a-78f9-4a28-d08f7f95354a 1928-12-25        NaT           NaN
6  183df435-4190-060e-8f8e-bf63c572b266 1957-11-08        NaT           NaN
7  720560d4-51da-c38c-ee90-c15935278df1 1972-06-27        NaT           NaN
8  217851b0-5f47-d376-18b9-0fe4ba77207e 1954-03-06        NaT           NaN
9  ff331e5c-ab16-e218-f39a-63e11de1ed75 1927-07-10        NaT           NaN

In [144]:
# ============================================================
# STAGE 4.3.2 — DECEASED INDICATOR
# ============================================================

patients_clean["IS_DECEASED"] = (
    patients_clean["DEATHDATE"].notna()
)

print(
    patients_clean["IS_DECEASED"]
    .value_counts()
)

IS_DECEASED
False    820
True     154
Name: count, dtype: int64

In [145]:
# ============================================================
# STAGE 4.3.3 — AGE AT DEATH QUALITY CHECK
# ============================================================

print("Patients:", len(patients_clean))

print(
    "Patients with death date:",
    patients_clean["DEATHDATE"].notna().sum()
)

print(
    "Patients with calculated age at death:",
    patients_clean["AGE_AT_DEATH"].notna().sum()
)

print(
    "Negative age at death:",
    (patients_clean["AGE_AT_DEATH"] < 0).sum()
)

print("\nAge at death statistics:")
print(
    patients_clean["AGE_AT_DEATH"].describe()
)

Patients: 974
Patients with death date: 154
Patients with calculated age at death: 154
Negative age at death: 0

Age at death statistics:
count   154.00
mean     79.85
std      14.73
min      26.20
25%      78.00
50%      84.55
75%      88.80
max      97.60
Name: AGE_AT_DEATH, dtype: float64

In [146]:
# ============================================================
# STAGE 4.4 — PATIENT AGE GROUP
# ============================================================

patients_clean["AGE_GROUP"] = pd.cut(
    patients_clean["AGE_AT_DEATH"],
    bins=[-1, 17, 34, 49, 64, 79, float("inf")],
    labels=[
        "0–17",
        "18–34",
        "35–49",
        "50–64",
        "65–79",
        "80+"
    ]
)

print(
    patients_clean["AGE_GROUP"]
    .value_counts(dropna=False)
    .sort_index()
)

AGE_GROUP
0–17       0
18–34      2
35–49      8
50–64     10
65–79     19
80+      115
NaN      820
Name: count, dtype: int64

In [147]:
# ============================================================
# STAGE 4.4 — PATIENT AGE GROUP AT DEATH
# ============================================================

patients_clean["AGE_GROUP_AT_DEATH"] = pd.cut(
    patients_clean["AGE_AT_DEATH"],
    bins=[-1, 17, 34, 49, 64, 79, float("inf")],
    labels=[
        "0–17",
        "18–34",
        "35–49",
        "50–64",
        "65–79",
        "80+"
    ]
)

print("Age group at death distribution:")
print(
    patients_clean["AGE_GROUP_AT_DEATH"]
    .value_counts(dropna=False)
    .sort_index()
)

Age group at death distribution:
AGE_GROUP_AT_DEATH
0–17       0
18–34      2
35–49      8
50–64     10
65–79     19
80+      115
NaN      820
Name: count, dtype: int64

In [148]:
# ============================================================
# STAGE 4.4.1 — AGE GROUP VALIDATION
# ============================================================

print("Total patients:", len(patients_clean))

print(
    "Patients with death date:",
    patients_clean["DEATHDATE"].notna().sum()
)

print(
    "Patients assigned an age group:",
    patients_clean["AGE_GROUP_AT_DEATH"].notna().sum()
)

print(
    "Missing age groups:",
    patients_clean["AGE_GROUP_AT_DEATH"].isna().sum()
)

Total patients: 974
Patients with death date: 154
Patients assigned an age group: 154
Missing age groups: 820

In [149]:
encounter_description = (
    encounters_clean["DESCRIPTION"]
    .value_counts()
    .reset_index()
)

encounter_description.columns = [
    "Description",
    "Encounters"
]

encounter_description.head(15)

                                                         Description  Encounters
0                                  Encounter for problem (procedure)        4308
1                                     Urgent care clinic (procedure)        3633
2                                 Encounter for check up (procedure)        2950
3                         General examination of patient (procedure)        1880
4                                              Encounter for symptom        1824
5                                                Follow-up encounter        1565
6                             Telemedicine consultation with patient        1548
7                                                Emergency Encounter        1475
8                            Patient encounter procedure (procedure)        1059
9                                                     Prenatal visit        1026
10  Administration of vaccine to produce active immunity (procedure)        1003
11                                             Encounter for problem         959
12                                       Patient encounter procedure         681
13                                          Encounter for 'check-up'         678
14                              Emergency room admission (procedure)         472

In [150]:
patient_utilization = (
    encounters_clean
    .groupby("PATIENT")
    .agg(
        Encounter_Count=("Id", "count"),
        Total_Encounter_Cost=("TOTAL_CLAIM_COST", "sum"),
        Total_Payer_Coverage=("PAYER_COVERAGE", "sum"),
        Average_Encounter_Cost=("TOTAL_CLAIM_COST", "mean")
    )
    .reset_index()
)

patient_utilization.head()

                                PATIENT  Encounter_Count  Total_Encounter_Cost  Total_Payer_Coverage  Average_Encounter_Cost
0  002bc307-2fff-04ba-161b-98cce123e226               46             13,742.67              9,509.86                  298.75
1  0034fe01-207f-275f-6b4b-821f7b0af044               75            548,667.37              5,494.56                7,315.56
2  00abe029-00fa-a666-34f5-258a36978f6d               22             48,334.27              6,384.67                2,197.01
3  010ff9c1-564b-6e32-09f4-29cb4224bba9                4             26,367.50             19,475.04                6,591.88
4  01274098-150f-8211-6150-29f2a2da266c                1                  0.00                  0.00                    0.00

In [151]:
patient_utilization["Encounter_Count"].describe()

count     974.00
mean       28.64
std        73.04
min         1.00
25%         4.00
50%        14.00
75%        28.00
max     1,381.00
Name: Encounter_Count, dtype: float64

In [152]:
top_utilizers = (
    patient_utilization
    .sort_values(
        "Encounter_Count",
        ascending=False
    )
    .head(10)
)

top_utilizers

                                  PATIENT  Encounter_Count  Total_Encounter_Cost  Total_Payer_Coverage  Average_Encounter_Cost
85   1712d26d-822d-1e3a-2267-0a9dba31d7c8             1381          2,437,415.31                  0.00                1,764.96
371  5e055638-0dad-dfd5-005d-1e74b6fd29ac              887            844,913.74            628,529.62                  952.55
240  3de74169-7f67-9304-91d4-757e0f3a14d2              877            819,279.19                  0.00                  934.18
245  3f523789-55f3-bb31-2757-4803ca6a9c2a              447          9,932,262.99                  0.00               22,219.83
370  5dcb295d-92df-a147-ebcc-aa49b6262830              441            105,080.78             44,171.55                  238.28
275  442dc617-c7f2-0513-15cd-c35c4efdba73              392            156,858.67             23,241.99                  400.15
694  b4ab9ab3-f52a-751e-a990-3bd5654d5870              383            124,858.48             41,136.64                  326.00
600  9b8ae606-5059-b3a6-19c7-c812901898bb              364            187,907.26            133,760.63                  516.23
693  b4671e80-7e87-9260-ca31-6a9397d465d1              296             65,245.84             40,333.20                  220.43
973  ff331e5c-ab16-e218-f39a-63e11de1ed75              291          6,356,665.66            845,233.69               21,844.21

In [153]:
cost_summary = encounters_clean[
    [
        "BASE_ENCOUNTER_COST",
        "TOTAL_CLAIM_COST",
        "PAYER_COVERAGE"
    ]
].describe()

cost_summary

       BASE_ENCOUNTER_COST  TOTAL_CLAIM_COST  PAYER_COVERAGE
count            27,891.00         27,891.00       27,891.00
mean                116.18          3,639.68        1,114.97
std                  28.41          9,205.60        4,768.62
min                  85.55              0.00            0.00
25%                  85.55            142.58            0.00
50%                 136.80            278.58           28.44
75%                 142.58          1,412.53          155.77
max                 146.18        641,882.70      247,751.42

In [154]:
print(
    "Total claim cost:",
    round(encounters_clean["TOTAL_CLAIM_COST"].sum(), 2)
)

print(
    "Total payer coverage:",
    round(encounters_clean["PAYER_COVERAGE"].sum(), 2)
)

print(
    "Average claim cost:",
    round(encounters_clean["TOTAL_CLAIM_COST"].mean(), 2)
)

print(
    "Average payer coverage:",
    round(encounters_clean["PAYER_COVERAGE"].mean(), 2)
)

Total claim cost: 101514375.52
Total payer coverage: 31097506.99
Average claim cost: 3639.68
Average payer coverage: 1114.97

In [155]:
encounters_clean["PATIENT_RESPONSIBILITY"] = (
    encounters_clean["TOTAL_CLAIM_COST"]
    - encounters_clean["PAYER_COVERAGE"]
)

encounters_clean[
    "PATIENT_RESPONSIBILITY"
].describe()

count    27,891.00
mean      2,524.72
std       7,661.01
min           0.00
25%          85.55
50%         172.59
75%       1,004.63
max     641,882.70
Name: PATIENT_RESPONSIBILITY, dtype: float64

In [156]:
encounters_clean["PATIENT_RESPONSIBILITY"] = (
    encounters_clean["TOTAL_CLAIM_COST"]
    - encounters_clean["PAYER_COVERAGE"]
)

encounters_clean[
    "PATIENT_RESPONSIBILITY"
].describe()

count    27,891.00
mean      2,524.72
std       7,661.01
min           0.00
25%          85.55
50%         172.59
75%       1,004.63
max     641,882.70
Name: PATIENT_RESPONSIBILITY, dtype: float64

In [157]:
print(
    "Negative patient responsibility:",
    (
        encounters_clean["PATIENT_RESPONSIBILITY"] < 0
    ).sum()
)

Negative patient responsibility: 0

In [158]:
payer_analysis = (
    encounters_clean
    .groupby("PAYER")
    .agg(
        Encounters=("Id", "count"),
        Total_Claim_Cost=("TOTAL_CLAIM_COST", "sum"),
        Total_Payer_Coverage=("PAYER_COVERAGE", "sum"),
        Average_Claim_Cost=("TOTAL_CLAIM_COST", "mean")
    )
    .reset_index()
)

payer_analysis

                                  PAYER  Encounters  Total_Claim_Cost  Total_Payer_Coverage  Average_Claim_Cost
0  047f6ec3-6215-35eb-9608-f9dda363a44c         809      2,424,532.96                968.35            2,996.95
1  42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a         704      2,982,715.05                  0.00            4,236.81
2  4d71f845-a6a9-3c39-b242-14d25ef86a8d         936      2,589,956.10              1,780.16            2,767.05
3  5059a55e-5d6e-34d1-b6cb-d83d16e57bcf         900      2,563,507.98              3,937.32            2,848.34
4  6e2f1a2d-27bd-3701-8d08-dae202c58632         925      3,002,166.01          2,074,496.34            3,245.58
5  7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a        1443      8,954,131.02          8,417,973.72            6,205.22
6  7caa7254-5050-3b5e-9eae-bd5ea30e809c       11371     24,647,228.89         19,215,691.37            2,167.55
7  b1c428d6-4f07-31e0-90f0-68ffa6ff8c76        8807     49,259,290.16                  0.00            5,593.20
8  b3221cfc-24fb-339e-823d-bc4136cbc4ed         912      1,546,925.99          1,380,705.87            1,696.19
9  d47b3510-2895-3b70-9897-342d681c769d        1084      3,543,921.36              1,953.86            3,269.30

In [159]:
payer_analysis = payer_analysis.merge(
    payers_clean[["Id", "NAME"]],
    left_on="PAYER",
    right_on="Id",
    how="left"
)

payer_analysis = payer_analysis.drop(
    columns=["Id"]
)

payer_analysis

                                  PAYER  Encounters  Total_Claim_Cost  Total_Payer_Coverage  Average_Claim_Cost                    NAME
0  047f6ec3-6215-35eb-9608-f9dda363a44c         809      2,424,532.96                968.35            2,996.95            Cigna Health
1  42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a         704      2,982,715.05                  0.00            4,236.81                  Anthem
2  4d71f845-a6a9-3c39-b242-14d25ef86a8d         936      2,589,956.10              1,780.16            2,767.05                   Aetna
3  5059a55e-5d6e-34d1-b6cb-d83d16e57bcf         900      2,563,507.98              3,937.32            2,848.34        UnitedHealthcare
4  6e2f1a2d-27bd-3701-8d08-dae202c58632         925      3,002,166.01          2,074,496.34            3,245.58  Blue Cross Blue Shield
5  7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a        1443      8,954,131.02          8,417,973.72            6,205.22                Medicaid
6  7caa7254-5050-3b5e-9eae-bd5ea30e809c       11371     24,647,228.89         19,215,691.37            2,167.55                Medicare
7  b1c428d6-4f07-31e0-90f0-68ffa6ff8c76        8807     49,259,290.16                  0.00            5,593.20            NO_INSURANCE
8  b3221cfc-24fb-339e-823d-bc4136cbc4ed         912      1,546,925.99          1,380,705.87            1,696.19           Dual Eligible
9  d47b3510-2895-3b70-9897-342d681c769d        1084      3,543,921.36              1,953.86            3,269.30                  Humana

In [160]:
payer_analysis["Coverage_Rate"] = (
    payer_analysis["Total_Payer_Coverage"]
    / payer_analysis["Total_Claim_Cost"]
    * 100
).round(2)

payer_analysis.sort_values(
    "Coverage_Rate",
    ascending=False
)

                                  PAYER  Encounters  Total_Claim_Cost  Total_Payer_Coverage  Average_Claim_Cost                    NAME  Coverage_Rate
5  7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a        1443      8,954,131.02          8,417,973.72            6,205.22                Medicaid          94.01
8  b3221cfc-24fb-339e-823d-bc4136cbc4ed         912      1,546,925.99          1,380,705.87            1,696.19           Dual Eligible          89.25
6  7caa7254-5050-3b5e-9eae-bd5ea30e809c       11371     24,647,228.89         19,215,691.37            2,167.55                Medicare          77.96
4  6e2f1a2d-27bd-3701-8d08-dae202c58632         925      3,002,166.01          2,074,496.34            3,245.58  Blue Cross Blue Shield          69.10
3  5059a55e-5d6e-34d1-b6cb-d83d16e57bcf         900      2,563,507.98              3,937.32            2,848.34        UnitedHealthcare           0.15
2  4d71f845-a6a9-3c39-b242-14d25ef86a8d         936      2,589,956.10              1,780.16            2,767.05                   Aetna           0.07
9  d47b3510-2895-3b70-9897-342d681c769d        1084      3,543,921.36              1,953.86            3,269.30                  Humana           0.06
0  047f6ec3-6215-35eb-9608-f9dda363a44c         809      2,424,532.96                968.35            2,996.95            Cigna Health           0.04
1  42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a         704      2,982,715.05                  0.00            4,236.81                  Anthem           0.00
7  b1c428d6-4f07-31e0-90f0-68ffa6ff8c76        8807     49,259,290.16                  0.00            5,593.20            NO_INSURANCE           0.00

In [161]:
procedure_summary = (
    procedures_clean["DESCRIPTION"]
    .value_counts()
    .reset_index()
)

procedure_summary.columns = [
    "Procedure",
    "Procedure_Count"
]

procedure_summary.head(20)

                                                                               Procedure  Procedure_Count
0                                 Assessment of health and social care needs (procedure)             4596
1                                                          Hospice care (regime/therapy)             4098
2                                                       Depression screening (procedure)             3614
3     Depression screening using Patient Health Questionnaire Two-Item score (procedure)             3614
4                                                Assessment of substance use (procedure)             2906
5                                                             Renal dialysis (procedure)             2746
6                                          Assessment using Morse Fall Scale (procedure)             2422
7                                                      Assessment of anxiety (procedure)             2288
8                                                  Medication Reconciliation (procedure)             2284
9                                                   Screening for drug abuse (procedure)             1484
10                                              Screening for domestic abuse (procedure)             1432
11  Assessment using Alcohol Use Disorders Identification Test - Consumption (procedure)             1422
12                                                              Electrical cardioversion             1383
13                                                   Evaluation of uterine fundal height             1065
14                                                       Auscultation of the fetal heart             1065
15                                                     Movement therapy (regime/therapy)              890
16                                                               Intramuscular injection              522
17                               Combined chemotherapy and radiation therapy (procedure)              444
18                                                                           Colonoscopy              424
19                                                  Catheter ablation of tissue of heart              365

In [162]:
procedure_cost = (
    procedures_clean
    .groupby("DESCRIPTION")
    .agg(
        Procedure_Count=("CODE", "count"),
        Total_Cost=("BASE_COST", "sum"),
        Average_Cost=("BASE_COST", "mean")
    )
    .reset_index()
)

procedure_cost = procedure_cost.sort_values(
    "Total_Cost",
    ascending=False
)

procedure_cost.head(20)

                                                                            DESCRIPTION  Procedure_Count  Total_Cost  Average_Cost
50                                                             Electrical cardioversion             1383    35824002     25,903.11
17                                                      Auscultation of the fetal heart             1065     5657822      5,312.51
54                                                  Evaluation of uterine fundal height             1065     5631281      5,287.59
36                              Combined chemotherapy and radiation therapy (procedure)              444     5237596     11,796.39
35                                                                          Colonoscopy              424     5021003     11,841.99
27                                                 Catheter ablation of tissue of heart              365     3405999      9,331.50
124                                                          Renal dialysis (procedure)             2746     2757221      1,004.09
11                               Assessment of health and social care needs (procedure)             4596     1980876        431.00
23                                                        Bone density scan (procedure)              198     1901367      9,602.86
69                                                        Hospice care (regime/therapy)             4098     1766238        431.00
154                                                 Ultrasound scan for fetal viability              184     1693824      9,205.57
137                                                              Spirometry (procedure)              209     1628688      7,792.77
44                                                     Depression screening (procedure)             3614     1557634        431.00
46   Depression screening using Patient Health Questionnaire Two-Item score (procedure)             3614     1557634        431.00
34                                    Cognitive and behavioral therapy (regime/therapy)              136     1412779     10,388.08
81                                                              Intramuscular injection              522     1325634      2,539.53
12                                              Assessment of substance use (procedure)             2906     1252486        431.00
95                                                Medication Reconciliation (procedure)             2284     1162840        509.12
107     Percutaneous mechanical thrombectomy of portal vein using fluoroscopic guidance               57     1152998     20,228.04
14                                        Assessment using Morse Fall Scale (procedure)             2422     1043882        431.00

In [163]:
patient_procedures = (
    procedures_clean
    .groupby("PATIENT")
    .agg(
        Procedure_Count=("CODE", "count"),
        Procedure_Cost=("BASE_COST", "sum")
    )
    .reset_index()
)

patient_procedures.head()

                                PATIENT  Procedure_Count  Procedure_Cost
0  002bc307-2fff-04ba-161b-98cce123e226               11           12414
1  0034fe01-207f-275f-6b4b-821f7b0af044              156          541708
2  00abe029-00fa-a666-34f5-258a36978f6d               21           58619
3  010ff9c1-564b-6e32-09f4-29cb4224bba9                5           27319
4  01296e88-f6d9-1c18-cf91-87523325e034               96          884074

In [164]:
patient_procedures["Procedure_Count"].describe()

count     793.00
mean       60.15
std       125.36
min         1.00
25%         7.00
50%        20.00
75%        64.00
max     1,783.00
Name: Procedure_Count, dtype: float64

In [165]:
encounters_clean["YEAR"] = (
    encounters_clean["START"].dt.year
)

encounters_clean["MONTH"] = (
    encounters_clean["START"].dt.month
)

encounters_clean["YEAR_MONTH"] = (
    encounters_clean["START"]
    .dt.to_period("M")
    .astype(str)
)

C:\Users\Olayinka\AppData\Local\Temp\ipykernel_1864\647032155.py:11: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  .dt.to_period("M")

In [166]:
monthly_encounters = (
    encounters_clean
    .groupby("YEAR_MONTH")
    .size()
    .reset_index(name="Encounters")
)

monthly_encounters.head(15)

   YEAR_MONTH  Encounters
0     2011-01          86
1     2011-02          86
2     2011-03         129
3     2011-04         113
4     2011-05         131
5     2011-06         131
6     2011-07         124
7     2011-08         115
8     2011-09         124
9     2011-10          84
10    2011-11         100
11    2011-12         113
12    2012-01         116
13    2012-02         170
14    2012-03         183

In [167]:
annual_encounters = (
    encounters_clean
    .groupby("YEAR")
    .agg(
        Encounters=("Id", "count"),
        Total_Claim_Cost=("TOTAL_CLAIM_COST", "sum"),
        Average_Claim_Cost=("TOTAL_CLAIM_COST", "mean")
    )
    .reset_index()
)

annual_encounters

    YEAR  Encounters  Total_Claim_Cost  Average_Claim_Cost
0   2011        1336      4,405,936.73            3,297.86
1   2012        2106      9,058,314.10            4,301.19
2   2013        2495     10,105,272.87            4,050.21
3   2014        3885     12,011,662.17            3,091.80
4   2015        2469     10,124,652.89            4,100.71
5   2016        2451      8,386,701.12            3,421.75
6   2017        2360      9,596,894.47            4,066.48
7   2018        2292      8,746,818.37            3,816.24
8   2019        2228      8,915,338.78            4,001.50
9   2020        2519     10,294,077.96            4,086.57
10  2021        3530      9,177,232.00            2,599.78
11  2022         220        691,474.06            3,143.06

In [168]:
procedures_clean["START"] = pd.to_datetime(
    procedures_clean["START"],
    errors="coerce"
)

procedures_clean["YEAR"] = (
    procedures_clean["START"].dt.year
)

annual_procedures = (
    procedures_clean
    .groupby("YEAR")
    .agg(
        Procedures=("CODE", "count"),
        Procedure_Cost=("BASE_COST", "sum")
    )
    .reset_index()
)

annual_procedures

    YEAR  Procedures  Procedure_Cost
0   2011        1184         2756770
1   2012        4456         9431106
2   2013        4998        10859501
3   2014        6292        12538073
4   2015        4656        10593719
5   2016        4143         8840739
6   2017        4585        10197041
7   2018        3880         9179212
8   2019        4378         9639011
9   2020        4451        11255330
10  2021        4410         9511924
11  2022         268          715285

In [169]:
duration_by_type = (
    encounters_clean
    .groupby("ENCOUNTERCLASS")
    .agg(
        Encounter_Count=("Id", "count"),
        Average_Duration_Min=("ENCOUNTER_DURATION_MIN", "mean"),
        Median_Duration_Min=("ENCOUNTER_DURATION_MIN", "median"),
        Total_Claim_Cost=("TOTAL_CLAIM_COST", "sum")
    )
    .reset_index()
)

duration_by_type

  ENCOUNTERCLASS  Encounter_Count  Average_Duration_Min  Median_Duration_Min  Total_Claim_Cost
0     ambulatory            12537                568.77                15.00     36,283,440.84
1      emergency             2322                 92.51                60.00     10,750,051.53
2      inpatient             1135              2,210.50             1,440.00      8,809,134.34
3     outpatient             6300                352.55                15.00     14,094,967.12
4     urgentcare             3666                 15.00                15.00     23,349,349.96
5       wellness             1931                 15.00                15.00      8,227,431.73

Data quality/business rule observation: A small number of encounters have unusually long recorded durations. These may represent longitudinal or recurring follow-up records rather than continuous physical stays. Duration metrics should therefore be interpreted according to encounter class and clinical context.

In [170]:
print(encounters_clean.columns.tolist())

['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION', 'Encounter_Year', 'Encounter_Month', 'Encounter_Month_Name', 'Encounter_Quarter', 'Encounter_Year_Month', 'Encounter_Day', 'Encounter_Day_Name', 'Encounter_Week', 'ENCOUNTER_DURATION_MIN', 'ENCOUNTER_DURATION_HOURS', 'DURATION_DAYS', 'DURATION_FLAG', 'AGE_AT_ENCOUNTER', 'PATIENT_RESPONSIBILITY', 'FINANCIAL_RECONCILIATION_DIFF', 'AGE_GROUP', 'YEAR', 'MONTH', 'YEAR_MONTH']

In [171]:
print(encounters_clean[["START", "STOP"]].head())

                      START                      STOP
0 2011-01-02 09:26:36+00:00 2011-01-02 12:58:36+00:00
1 2011-01-03 05:44:39+00:00 2011-01-03 06:01:42+00:00
2 2011-01-03 14:32:11+00:00 2011-01-03 14:47:11+00:00
3 2011-01-03 16:24:45+00:00 2011-01-03 16:39:45+00:00
4 2011-01-03 17:36:53+00:00 2011-01-03 17:51:53+00:00

In [172]:
# ============================================================
# STEP 4.5 — ENCOUNTER DURATION
# ============================================================

encounters_clean["START"] = pd.to_datetime(
    encounters_clean["START"],
    errors="coerce"
)

encounters_clean["STOP"] = pd.to_datetime(
    encounters_clean["STOP"],
    errors="coerce"
)

encounters_clean["DURATION_DAYS"] = (
    encounters_clean["STOP"] - encounters_clean["START"]
).dt.total_seconds() / (24 * 60 * 60)

print("DURATION_DAYS created successfully.")
print(encounters_clean["DURATION_DAYS"].describe())

DURATION_DAYS created successfully.
count   27,891.00
mean         0.30
std         16.60
min          0.01
25%          0.01
50%          0.01
75%          0.04
max      1,872.08
Name: DURATION_DAYS, dtype: float64

In [173]:
# ============================================================
# STEP 4.5 — ENCOUNTER DURATION IN DAYS
# ============================================================

encounters_clean["DURATION_DAYS"] = (
    encounters_clean["ENCOUNTER_DURATION_MIN"] / (60 * 24)
).round(2)

print("DURATION_DAYS created successfully.")

encounters_clean[
    ["Id", "START", "STOP", "ENCOUNTER_DURATION_MIN", "DURATION_DAYS"]
].head(10)

DURATION_DAYS created successfully.

                                     Id                     START                      STOP  ENCOUNTER_DURATION_MIN  DURATION_DAYS
0  32c84703-2481-49cd-d571-3899d5820253 2011-01-02 09:26:36+00:00 2011-01-02 12:58:36+00:00                  212.00           0.15
1  c98059da-320a-c0a6-fced-c8815f3e3f39 2011-01-03 05:44:39+00:00 2011-01-03 06:01:42+00:00                   17.05           0.01
2  4ad28a3a-2479-782b-f29c-d5b3f41a001e 2011-01-03 14:32:11+00:00 2011-01-03 14:47:11+00:00                   15.00           0.01
3  c3f4da61-e4b4-21d5-587a-fbc89943bc19 2011-01-03 16:24:45+00:00 2011-01-03 16:39:45+00:00                   15.00           0.01
4  a9183b4f-2572-72ea-54c2-b3cd038b4be7 2011-01-03 17:36:53+00:00 2011-01-03 17:51:53+00:00                   15.00           0.01
5  c4923a74-3e40-8b0c-cf73-05b9c0390621 2011-01-03 19:08:16+00:00 2011-01-03 19:23:16+00:00                   15.00           0.01
6  c140ed81-040e-8319-e860-f72b4738ed22 2011-01-03 22:39:50+00:00 2011-01-03 22:54:50+00:00                   15.00           0.01
7  2cfd4ddd-ad13-fe1e-528b-15051cea2ec3 2011-01-04 14:49:55+00:00 2011-01-04 15:04:55+00:00                   15.00           0.01
8  16bdc066-886f-34e1-38fa-afb85090b637 2011-01-04 15:13:10+00:00 2011-01-04 15:28:10+00:00                   15.00           0.01
9  17966936-0878-f4db-128b-a43ae10d0878 2011-01-05 04:02:09+00:00 2011-01-05 04:17:09+00:00                   15.00           0.01

In [174]:
print("Missing duration days:",
      encounters_clean["DURATION_DAYS"].isna().sum())

print("Negative duration days:",
      (encounters_clean["DURATION_DAYS"] < 0).sum())

print("\nDuration days statistics:")
print(encounters_clean["DURATION_DAYS"].describe())

Missing duration days: 0
Negative duration days: 0

Duration days statistics:
count   27,891.00
mean         0.30
std         16.60
min          0.01
25%          0.01
50%          0.01
75%          0.04
max      1,872.08
Name: DURATION_DAYS, dtype: float64

In [175]:
# ============================================================
# STEP 4.6 — LONG ENCOUNTER IDENTIFICATION
# ============================================================

long_encounters = (
    encounters_clean[
        encounters_clean["DURATION_DAYS"] > 7
    ]
    [
        [
            "Id",
            "PATIENT",
            "ENCOUNTERCLASS",
            "DESCRIPTION",
            "START",
            "STOP",
            "DURATION_DAYS"
        ]
    ]
    .sort_values(
        "DURATION_DAYS",
        ascending=False
    )
)

print("Long encounters (>7 days):", len(long_encounters))

long_encounters.head(20)

Long encounters (>7 days): 31

                                         Id                               PATIENT ENCOUNTERCLASS                                                             DESCRIPTION                     START                      STOP  DURATION_DAYS
9704   fc2c2add-0b55-e300-5cea-8f43044eb330  5d47b9ac-3f37-f400-1747-c6c6f92130aa     ambulatory                                         Follow-up encounter (procedure) 2014-12-17 11:49:08+00:00 2020-02-01 13:49:08+00:00       1,872.08
7735   2cb41a50-819c-ef7e-87df-b5b47b2e01a1  09e0ec41-cd4c-50b2-b425-824013777beb     ambulatory                                         Follow-up encounter (procedure) 2014-03-27 00:33:14+00:00 2019-03-13 15:33:14+00:00       1,812.62
7805   7a19a260-e4a9-7b81-3f93-e07144d634d9  8885aba5-afce-9e3b-0c1d-a684a347b5fb     ambulatory                                         Follow-up encounter (procedure) 2014-04-02 22:26:28+00:00 2015-07-02 13:44:57+00:00         455.64
6116   3cf29374-f91a-5877-9356-87792501d225  a12541db-140e-8189-070c-dc9f4815f40f     outpatient                                       Encounter for problem (procedure) 2014-01-31 02:29:54+00:00 2015-04-22 02:29:54+00:00         446.00
6371   63b7c71f-23f5-32dc-b63a-cca7bf5625a2  6e8e0498-187a-d038-c7af-716b12e70455     outpatient                                       Encounter for problem (procedure) 2014-02-06 02:17:34+00:00 2015-01-20 02:17:34+00:00         348.00
18343  4079872d-73da-3b52-5306-2a978c6f5c8c  54889029-0a1e-0b75-5980-1c091dd4bc0e      inpatient  Periodic reevaluation and management of healthy individual (procedure) 2018-07-18 23:56:20+00:00 2019-06-27 17:56:35+00:00         343.75
6380   110777dd-6aca-3c9c-7119-ab2494c0665e  0ec939a0-559c-7bc9-db9c-a7feae58634a     outpatient                                       Encounter for problem (procedure) 2014-02-06 04:57:58+00:00 2015-01-13 04:57:58+00:00         341.00
7832   04df7388-7a70-3e99-c0fe-7f7ddd062931  ea9d6669-efc3-3c16-4f70-70cc1c1659d7     ambulatory                                         Follow-up encounter (procedure) 2014-04-04 22:41:46+00:00 2015-01-31 13:54:32+00:00         301.63
6125   d0476a31-1524-f23f-fb79-290ecd6206aa  f6932663-d920-6e76-89e1-21a6b43cf03b     outpatient                                       Encounter for problem (procedure) 2014-01-31 11:10:57+00:00 2014-06-25 11:10:57+00:00         145.00
6138   1123fed5-342e-f49b-4ab9-91f153b9e474  d40ba361-8192-a8e6-b75c-5def4758fe3f     outpatient                                       Encounter for problem (procedure) 2014-01-31 20:39:04+00:00 2014-04-09 20:39:04+00:00          68.00
6332   dcc730d3-4d74-5e75-ae03-cd23c0ee742c  60d2d35e-bd32-36df-b8e0-b64a3494f0e8     outpatient                                       Encounter for problem (procedure) 2014-02-05 08:41:28+00:00 2014-04-14 08:41:28+00:00          68.00
16504  0b29bad1-7b3c-2585-1b31-c3dd7a6ec36a  a96d5031-46d5-e3f6-ec67-81f8edd48aa8      inpatient  Periodic reevaluation and management of healthy individual (procedure) 2017-09-30 13:44:27+00:00 2017-11-25 13:44:27+00:00          56.00
6145   6053724d-e3b1-0449-402d-3090d3514389  f21a9c39-abd4-4e57-575d-83e1c29484da     outpatient                                       Encounter for problem (procedure) 2014-01-31 23:35:27+00:00 2014-03-26 23:35:27+00:00          54.00
8980   9741be00-49a5-f25a-a59b-ea46ffbad229  77dedc66-369c-bb18-940d-0db841255ef7     ambulatory                                         Follow-up encounter (procedure) 2014-09-14 10:42:36+00:00 2014-10-11 21:42:36+00:00          27.46
23048  6c108963-2fda-815b-3813-a424b3533127  01296e88-f6d9-1c18-cf91-87523325e034      emergency                                                   Encounter for problem 2020-08-15 04:52:21+00:00 2020-09-08 17:52:21+00:00          24.54
5457   d5c42fa8-f110-b714-d89a-04ec57038a58  0226f105-2572-1c6f-15f0-1aa0438e40d0      inpatient                                       Encounter for symptom (procedure) 2013-10-22 00:16:17+00:00 2013-11-14 00:16:17+00:00          23.00
14807  6fc6cbfc-ade5-c9ec-721c-4f71d9a1a815  2f6c035b-a11d-9373-89af-0cb2195592d2      emergency                                    Emergency room admission (procedure) 2017-01-11 09:03:19+00:00 2017-01-27 09:03:19+00:00          16.00
24226  96f41ac9-60c0-d035-249b-ea9f68dfb7da  2999ffe8-ab8a-3afa-ab9e-aa40fa162e8c      inpatient                            Hospital admission for isolation (procedure) 2021-01-12 14:24:46+00:00 2021-01-25 15:06:45+00:00          13.03
24155  49a58342-2bed-0dec-5581-f12474408881  7811ad1e-3baf-5d00-6664-01c7396f67c9      inpatient                            Hospital admission for isolation (procedure) 2021-01-03 03:22:46+00:00 2021-01-16 04:02:42+00:00          13.03
23972  d12cbc08-c639-0917-6250-66eca2e6995f  97c4cfee-e860-e908-1797-8da4dc241ec4      inpatient                            Hospital admission for isolation (procedure) 2020-12-12 19:05:25+00:00 2020-12-25 19:32:34+00:00          13.02

In [176]:
long_encounters["ENCOUNTERCLASS"].value_counts()

ENCOUNTERCLASS
inpatient     17
outpatient     7
ambulatory     5
emergency      2
Name: count, dtype: int64

In [177]:
procedures_per_encounter = (
    procedures_clean
    .groupby("ENCOUNTER")
    .size()
    .reset_index(name="Procedure_Count")
)

procedures_per_encounter["Procedure_Count"].describe()

count   14,670.00
mean         3.25
std          5.16
min          1.00
25%          1.00
50%          2.00
75%          5.00
max        186.00
Name: Procedure_Count, dtype: float64

In [178]:
procedures_per_encounter.head()

                              ENCOUNTER  Procedure_Count
0  000cc8f4-f2c7-5cf3-419d-13be23d959da                6
1  0011d269-53cb-06c9-e0df-10f3d01d8c47                8
2  00169f6a-632c-357a-3cb2-a91a71c48f11                1
3  0019dbc5-e696-1444-d988-6ae5907580a4                2
4  001fb5d9-0c4a-3e8f-bd27-5c8317674632                1

In [179]:
procedure_encounter_check = procedures_clean[
    ~procedures_clean["ENCOUNTER"].isin(
        encounters_clean["Id"]
    )
]

print(
    "Procedures without valid encounters:",
    len(procedure_encounter_check)
)

Procedures without valid encounters: 0

In [180]:
patients_without_encounters = patients_clean[
    ~patients_clean["Id"].isin(
        encounters_clean["PATIENT"]
    )
]

print(
    "Patients with no encounters:",
    len(patients_without_encounters)
)

Patients with no encounters: 0

In [181]:
patients_without_encounters[
    [
        "Id",
        "BIRTHDATE",
        "GENDER",
        "RACE",
        "ETHNICITY"
    ]
].head()

Empty DataFrame
Columns: [Id, BIRTHDATE, GENDER, RACE, ETHNICITY]
Index: []

In [182]:
eda_findings = pd.DataFrame({
    "Area": [
        "Patient Population",
        "Encounter Utilization",
        "Procedure Utilization",
        "Healthcare Costs",
        "Payer Coverage",
        "Encounter Duration",
        "Data Quality"
    ],
    "Finding": [
        "To be completed after demographic analysis",
        "To be completed after encounter analysis",
        "To be completed after procedure analysis",
        "To be completed after cost analysis",
        "To be completed after payer analysis",
        "A small number of encounters have unusually long recorded durations",
        "Referential integrity checks passed"
    ],
    "Business_Question": [
        "Which patient groups account for the largest healthcare utilization?",
        "Which encounter types drive healthcare activity?",
        "Which procedures are most frequent and most costly?",
        "Which encounter types and patient groups drive costs?",
        "Which payers provide the highest coverage?",
        "Do unusually long durations reflect specific encounter types?",
        "Can the dataset be trusted for relational analysis?"
    ]
})

eda_findings

                    Area                                                              Finding                                                     Business_Question
0     Patient Population                           To be completed after demographic analysis  Which patient groups account for the largest healthcare utilization?
1  Encounter Utilization                             To be completed after encounter analysis                      Which encounter types drive healthcare activity?
2  Procedure Utilization                             To be completed after procedure analysis                   Which procedures are most frequent and most costly?
3       Healthcare Costs                                  To be completed after cost analysis                 Which encounter types and patient groups drive costs?
4         Payer Coverage                                 To be completed after payer analysis                            Which payers provide the highest coverage?
5     Encounter Duration  A small number of encounters have unusually long recorded durations         Do unusually long durations reflect specific encounter types?
6           Data Quality                                  Referential integrity checks passed                   Can the dataset be trusted for relational analysis?

In [183]:
# ============================================================
# STEP 4.5 — ENCOUNTER DURATION OUTLIER VALIDATION
# ============================================================

duration_outliers = (
    encounters_clean[
        encounters_clean["DURATION_DAYS"] > 7
    ]
    [
        [
            "Id",
            "PATIENT",
            "ENCOUNTERCLASS",
            "DESCRIPTION",
            "START",
            "STOP",
            "DURATION_DAYS",
            "TOTAL_CLAIM_COST",
            "PAYER_COVERAGE",
            "PATIENT_RESPONSIBILITY"
        ]
    ]
    .sort_values(
        "DURATION_DAYS",
        ascending=False
    )
)

print("Long encounters (>7 days):", len(duration_outliers))

duration_outliers.head(20)

Long encounters (>7 days): 31

,Id,PATIENT,ENCOUNTERCLASS,DESCRIPTION,START,STOP,DURATION_DAYS,TOTAL_CLAIM_COST,PAYER_COVERAGE,PATIENT_RESPONSIBILITY
9704,fc2c2add-0b55-e300-5cea-8f43044eb330,5d47b9ac-3f37-f400-1747-c6c6f92130aa,ambulatory,Follow-up encounter (procedure),2014-12-17 11:49:08+00:00,2020-02-01 13:49:08+00:00,"1,872.08",85.55,0.00,85.55
7735,2cb41a50-819c-ef7e-87df-b5b47b2e01a1,09e0ec41-cd4c-50b2-b425-824013777beb,ambulatory,Follow-up encounter (procedure),2014-03-27 00:33:14+00:00,2019-03-13 15:33:14+00:00,"1,812.62",85.55,7.91,77.64
7805,7a19a260-e4a9-7b81-3f93-e07144d634d9,8885aba5-afce-9e3b-0c1d-a684a347b5fb,ambulatory,Follow-up encounter (procedure),2014-04-02 22:26:28+00:00,2015-07-02 13:44:57+00:00,455.64,85.55,24.27,61.28
6116,3cf29374-f91a-5877-9356-87792501d225,a12541db-140e-8189-070c-dc9f4815f40f,outpatient,Encounter for problem (procedure),2014-01-31 02:29:54+00:00,2015-04-22 02:29:54+00:00,446.00,85.55,36.44,49.11
6371,63b7c71f-23f5-32dc-b63a-cca7bf5625a2,6e8e0498-187a-d038-c7af-716b12e70455,outpatient,Encounter for problem (procedure),2014-02-06 02:17:34+00:00,2015-01-20 02:17:34+00:00,348.00,85.55,0.00,85.55
18343,4079872d-73da-3b52-5306-2a978c6f5c8c,54889029-0a1e-0b75-5980-1c091dd4bc0e,inpatient,Periodic reevaluation and management of healthy individual (procedure),2018-07-18 23:56:20+00:00,2019-06-27 17:56:35+00:00,343.75,"7,093.85","5,643.08","1,450.77"
6380,110777dd-6aca-3c9c-7119-ab2494c0665e,0ec939a0-559c-7bc9-db9c-a7feae58634a,outpatient,Encounter for problem (procedure),2014-02-06 04:57:58+00:00,2015-01-13 04:57:58+00:00,341.00,85.55,0.00,85.55
7832,04df7388-7a70-3e99-c0fe-7f7ddd062931,ea9d6669-efc3-3c16-4f70-70cc1c1659d7,ambulatory,Follow-up encounter (procedure),2014-04-04 22:41:46+00:00,2015-01-31 13:54:32+00:00,301.63,85.55,0.00,85.55
6125,d0476a31-1524-f23f-fb79-290ecd6206aa,f6932663-d920-6e76-89e1-21a6b43cf03b,outpatient,Encounter for problem (procedure),2014-01-31 11:10:57+00:00,2014-06-25 11:10:57+00:00,145.00,85.55,0.00,85.55
6138,1123fed5-342e-f49b-4ab9-91f153b9e474,d40ba361-8192-a8e6-b75c-5def4758fe3f,outpatient,Encounter for problem (procedure),2014-01-31 20:39:04+00:00,2014-04-09 20:39:04+00:00,68.00,85.55,36.44,49.11
6332,dcc730d3-4d74-5e75-ae03-cd23c0ee742c,60d2d35e-bd32-36df-b8e0-b64a3494f0e8,outpatient,Encounter for problem (procedure),2014-02-05 08:41:28+00:00,2014-04-14 08:41:28+00:00,68.00,85.55,0.00,85.55
16504,0b29bad1-7b3c-2585-1b31-c3dd7a6ec36a,a96d5031-46d5-e3f6-ec67-81f8edd48aa8,inpatient,Periodic reevaluation and management of healthy individual (procedure),2017-09-30 13:44:27+00:00,2017-11-25 13:44:27+00:00,56.00,"6,102.44",0.00,"6,102.44"
6145,6053724d-e3b1-0449-402d-3090d3514389,f21a9c39-abd4-4e57-575d-83e1c29484da,outpatient,Encounter for problem (procedure),2014-01-31 23:35:27+00:00,2014-03-26 23:35:27+00:00,54.00,85.55,0.00,85.55
8980,9741be00-49a5-f25a-a59b-ea46ffbad229,77dedc66-369c-bb18-940d-0db841255ef7,ambulatory,Follow-up encounter (procedure),2014-09-14 10:42:36+00:00,2014-10-11 21:42:36+00:00,27.46,85.55,7.91,77.64
23048,6c108963-2fda-815b-3813-a424b3533127,01296e88-f6d9-1c18-cf91-87523325e034,emergency,Encounter for problem,2020-08-15 04:52:21+00:00,2020-09-08 17:52:21+00:00,24.54,"641,882.70",0.00,"641,882.70"
5457,d5c42fa8-f110-b714-d89a-04ec57038a58,0226f105-2572-1c6f-15f0-1aa0438e40d0,inpatient,Encounter for symptom (procedure),2013-10-22 00:16:17+00:00,2013-11-14 00:16:17+00:00,23.00,"7,664.97",0.00,"7,664.97"
14807,6fc6cbfc-ade5-c9ec-721c-4f71d9a1a815,2f6c035b-a11d-9373-89af-0cb2195592d2,emergency,Emergency room admission (procedure),2017-01-11 09:03:19+00:00,2017-01-27 09:03:19+00:00,16.00,"1,036.94",0.00,"1,036.94"
24226,96f41ac9-60c0-d035-249b-ea9f68dfb7da,2999ffe8-ab8a-3afa-ab9e-aa40fa162e8c,inpatient,Hospital admission for isolation (procedure),2021-01-12 14:24:46+00:00,2021-01-25 15:06:45+00:00,13.03,"22,821.65","18,216.54","4,605.11"
24155,49a58342-2bed-0dec-5581-f12474408881,7811ad1e-3baf-5d00-6664-01c7396f67c9,inpatient,Hospital admission for isolation (procedure),2021-01-03 03:22:46+00:00,2021-01-16 04:02:42+00:00,13.03,"21,146.49",0.00,"21,146.49"
23972,d12cbc08-c639-0917-6250-66eca2e6995f,97c4cfee-e860-e908-1797-8da4dc241ec4,inpatient,Hospital admission for isolation (procedure),2020-12-12 19:05:25+00:00,2020-12-25 19:32:34+00:00,13.02,"25,195.93","20,084.51","5,111.42"

In [184]:
# ============================================================
# LONG ENCOUNTERS BY ENCOUNTER TYPE
# ============================================================

long_duration_by_type = (
    duration_outliers
    .groupby("ENCOUNTERCLASS")
    .agg(
        Long_Encounter_Count=("Id", "count"),
        Average_Duration_Days=("DURATION_DAYS", "mean"),
        Maximum_Duration_Days=("DURATION_DAYS", "max"),
        Total_Claim_Cost=("TOTAL_CLAIM_COST", "sum")
    )
    .sort_values(
        "Long_Encounter_Count",
        ascending=False
    )
)

long_duration_by_type

                Long_Encounter_Count  Average_Duration_Days  Maximum_Duration_Days  Total_Claim_Cost
ENCOUNTERCLASS
inpatient                         17                  33.62                 343.75        610,676.76
outpatient                         7                 210.00                 446.00            598.85
ambulatory                         5                 893.89               1,872.08            427.75
emergency                          2                  20.27                  24.54        642,919.64

In [185]:
# ============================================================
# DURATION OUTLIER SEVERITY
# ============================================================

duration_outliers["DURATION_CATEGORY"] = pd.cut(
    duration_outliers["DURATION_DAYS"],
    bins=[0, 1, 7, 30, 90, 365, float("inf")],
    labels=[
        "≤1 day",
        "2–7 days",
        "8–30 days",
        "31–90 days",
        "91–365 days",
        ">365 days"
    ],
    include_lowest=True
)

duration_outlier_summary = (
    duration_outliers["DURATION_CATEGORY"]
    .value_counts()
    .sort_index()
)

duration_outlier_summary

DURATION_CATEGORY
≤1 day          0
2–7 days        0
8–30 days      18
31–90 days      4
91–365 days     5
>365 days       4
Name: count, dtype: int64

In [186]:
# ============================================================
# STEP 4.6 — ENCOUNTER DURATION QUALITY FLAG
# ============================================================

encounters_clean["DURATION_FLAG"] = pd.cut(
    encounters_clean["DURATION_DAYS"],
    bins=[
        -float("inf"),
        1,
        7,
        30,
        90,
        365,
        float("inf")
    ],
    labels=[
        "Normal: ≤1 day",
        "Extended: 2–7 days",
        "Long: 8–30 days",
        "Very Long: 31–90 days",
        "Extreme: 91–365 days",
        "Extreme: >365 days"
    ]
)

duration_flag_summary = (
    encounters_clean["DURATION_FLAG"]
    .value_counts()
    .sort_index()
)

duration_flag_summary

DURATION_FLAG
Normal: ≤1 day           27816
Extended: 2–7 days          44
Long: 8–30 days             18
Very Long: 31–90 days        4
Extreme: 91–365 days         5
Extreme: >365 days           4
Name: count, dtype: int64

In [187]:
# ============================================================
# DURATION FLAG PERCENTAGES
# ============================================================

duration_flag_percentages = (
    encounters_clean["DURATION_FLAG"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .sort_index()
)

duration_flag_percentages

DURATION_FLAG
Normal: ≤1 day          99.73
Extended: 2–7 days       0.16
Long: 8–30 days          0.06
Very Long: 31–90 days    0.01
Extreme: 91–365 days     0.02
Extreme: >365 days       0.01
Name: proportion, dtype: float64

In [188]:
# ============================================================
# STEP 4.7 — DURATION PROFILE BY ENCOUNTER TYPE
# ============================================================

duration_profile = (
    encounters_clean
    .groupby("ENCOUNTERCLASS")
    .agg(
        Encounter_Count=("Id", "count"),
        Average_Duration_Days=("DURATION_DAYS", "mean"),
        Median_Duration_Days=("DURATION_DAYS", "median"),
        P95_Duration_Days=(
            "DURATION_DAYS",
            lambda x: x.quantile(0.95)
        ),
        Maximum_Duration_Days=("DURATION_DAYS", "max"),
        Total_Claim_Cost=("TOTAL_CLAIM_COST", "sum")
    )
    .sort_values(
        "Median_Duration_Days",
        ascending=False
    )
)

duration_profile.round(2)

                Encounter_Count  Average_Duration_Days  Median_Duration_Days  P95_Duration_Days  Maximum_Duration_Days  Total_Claim_Cost
ENCOUNTERCLASS
inpatient                  1135                   1.54                  1.00               1.03                 343.75      8,809,134.34
emergency                  2322                   0.06                  0.04               0.04                  24.54     10,750,051.53
ambulatory                12537                   0.39                  0.01               0.15               1,872.08     36,283,440.84
outpatient                 6300                   0.24                  0.01               0.01                 446.00     14,094,967.12
urgentcare                 3666                   0.01                  0.01               0.01                   0.01     23,349,349.96
wellness                   1931                   0.01                  0.01               0.01                   0.01      8,227,431.73

In [189]:
# ============================================================
# STEP 4.8 — DATA QUALITY SUMMARY
# ============================================================

data_quality_summary = pd.DataFrame({
    "Check": [
        "Patients",
        "Encounters",
        "Procedures",
        "Payers",
        "Organizations",
        "Missing age at encounter",
        "Negative age at encounter",
        "Missing age groups",
        "Patients with death dates",
        "Negative age at death",
        "Long encounters >7 days",
        "Procedures without valid encounters",
        "Patients with no encounters",
        "Negative patient responsibility"
    ],
    "Result": [
        len(patients_clean),
        len(encounters_clean),
        len(procedures_clean),
        len(payers_clean),
        len(organizations_clean),
        encounters_clean["AGE_AT_ENCOUNTER"].isna().sum(),
        (encounters_clean["AGE_AT_ENCOUNTER"] < 0).sum(),
        encounters_clean["AGE_GROUP"].isna().sum(),
        patients_clean["DEATHDATE"].notna().sum(),
        (patients_clean["AGE_AT_DEATH"] < 0).sum(),
        (encounters_clean["DURATION_DAYS"] > 7).sum(),
        0,
        0,
        (encounters_clean["PATIENT_RESPONSIBILITY"] < 0).sum()
    ]
})

data_quality_summary

                                  Check  Result
0                              Patients     974
1                            Encounters   27891
2                            Procedures   47701
3                                Payers      10
4                         Organizations       1
5              Missing age at encounter       0
6             Negative age at encounter       0
7                    Missing age groups       0
8             Patients with death dates     154
9                 Negative age at death       0
10              Long encounters >7 days      31
11  Procedures without valid encounters       0
12          Patients with no encounters       0
13      Negative patient responsibility       0

In [190]:
# ============================================================
# STEP 4.13 — PATIENT-LEVEL CLINICAL UTILIZATION
# ============================================================

patient_utilization = (
    encounters_clean
    .groupby("PATIENT")
    .agg(
        Encounter_Count=("Id", "count"),
        Total_Encounter_Cost=("TOTAL_CLAIM_COST", "sum"),
        Total_Payer_Coverage=("PAYER_COVERAGE", "sum"),
        Total_Patient_Responsibility=("PATIENT_RESPONSIBILITY", "sum"),
        Inpatient_Encounters=(
            "ENCOUNTERCLASS",
            lambda x: (x == "inpatient").sum()
        ),
        Emergency_Encounters=(
            "ENCOUNTERCLASS",
            lambda x: (x == "emergency").sum()
        ),
        Outpatient_Encounters=(
            "ENCOUNTERCLASS",
            lambda x: (x == "outpatient").sum()
        ),
        Ambulatory_Encounters=(
            "ENCOUNTERCLASS",
            lambda x: (x == "ambulatory").sum()
        ),
        UrgentCare_Encounters=(
            "ENCOUNTERCLASS",
            lambda x: (x == "urgentcare").sum()
        ),
        Wellness_Encounters=(
            "ENCOUNTERCLASS",
            lambda x: (x == "wellness").sum()
        )
    )
    .reset_index()
)

patient_utilization.head()

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters
0,002bc307-2fff-04ba-161b-98cce123e226,46,"13,742.67","9,509.86","4,232.81",2,3,38,3,0,0
1,0034fe01-207f-275f-6b4b-821f7b0af044,75,"548,667.37","5,494.56","543,172.81",4,6,33,32,0,0
2,00abe029-00fa-a666-34f5-258a36978f6d,22,"48,334.27","6,384.67","41,949.60",0,1,5,16,0,0
3,010ff9c1-564b-6e32-09f4-29cb4224bba9,4,"26,367.50","19,475.04","6,892.46",0,0,1,3,0,0
4,01274098-150f-8211-6150-29f2a2da266c,1,0.00,0.00,0.00,1,0,0,0,0,0

In [191]:
# ============================================================
# STEP 4.13.1 — HIGHEST-UTILIZATION PATIENTS
# ============================================================

high_utilization_patients = (
    patient_utilization[
        [
            "PATIENT",
            "Encounter_Count",
            "Inpatient_Encounters",
            "Emergency_Encounters",
            "Outpatient_Encounters",
            "Ambulatory_Encounters",
            "UrgentCare_Encounters",
            "Wellness_Encounters",
            "Total_Encounter_Cost",
            "Total_Patient_Responsibility"
        ]
    ]
    .sort_values(
        "Encounter_Count",
        ascending=False
    )
)

high_utilization_patients.head(20)

,PATIENT,Encounter_Count,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters,Total_Encounter_Cost,Total_Patient_Responsibility
85,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,0,0,77,1304,0,0,"2,437,415.31","2,437,415.31"
371,5e055638-0dad-dfd5-005d-1e74b6fd29ac,887,0,17,92,778,0,0,"844,913.74","216,384.12"
240,3de74169-7f67-9304-91d4-757e0f3a14d2,877,0,49,35,786,0,7,"819,279.19","819,279.19"
245,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,0,172,48,3,213,11,"9,932,262.99","9,932,262.99"
370,5dcb295d-92df-a147-ebcc-aa49b6262830,441,0,0,5,436,0,0,"105,080.78","60,909.23"
275,442dc617-c7f2-0513-15cd-c35c4efdba73,392,0,77,83,13,208,11,"156,858.67","133,616.68"
694,b4ab9ab3-f52a-751e-a990-3bd5654d5870,383,0,79,90,5,198,11,"124,858.48","83,721.84"
600,9b8ae606-5059-b3a6-19c7-c812901898bb,364,0,144,70,150,0,0,"187,907.26","54,146.63"
693,b4671e80-7e87-9260-ca31-6a9397d465d1,296,0,19,77,14,176,10,"65,245.84","24,912.64"
973,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,0,0,72,2,206,11,"6,356,665.66","5,511,431.97"
224,381e16cd-86c8-d369-cd76-2dd9e0b5faf5,268,0,200,50,7,0,11,"128,142.11","37,655.75"
685,b17ffd11-c8c2-28aa-0c26-8ddc6bc5957d,246,0,181,0,54,0,11,"109,461.36","31,800.45"
832,dabb67a9-bc4b-bc40-696e-65546a548d39,239,3,0,0,230,0,6,"61,730.59","19,835.16"
631,a31f5105-476f-b129-fb9a-514cf45a34ac,232,0,133,75,13,0,11,"110,636.64","37,957.36"
844,df607b64-3d5e-5795-1646-edd2ccf55192,217,0,0,0,0,217,0,"31,891.86","29,416.56"
839,de60a9e4-1334-6078-c1f1-e5083bb20361,210,0,9,64,6,120,11,"60,363.48","31,478.69"
393,6443e813-1b9b-620c-f7de-af77f9d02733,197,0,0,0,0,197,0,"28,768.26","12,058.44"
436,71da4401-2034-80cb-d797-ad90cee5649e,188,0,4,71,26,87,0,"180,967.41","180,967.41"
409,6a377869-21cd-94d2-395d-155b999f4eac,186,0,0,0,0,186,0,"27,879.88","24,466.18"
486,7c96fd5c-ae3d-308a-a9ee-948ab47860f9,184,0,6,75,11,92,0,"54,681.10","40,919.30"

In [192]:
print("Total patients:", len(patient_utilization))
print("Average encounters per patient:",
      round(patient_utilization["Encounter_Count"].mean(), 2))
print("Median encounters per patient:",
      patient_utilization["Encounter_Count"].median())
print("Maximum encounters for one patient:",
      patient_utilization["Encounter_Count"].max())

Total patients: 974
Average encounters per patient: 28.64
Median encounters per patient: 14.0
Maximum encounters for one patient: 1381

In [193]:
# ============================================================
# STEP 4.13.2 — UTILIZATION CONCENTRATION
# ============================================================

total_encounters = patient_utilization["Encounter_Count"].sum()

patient_utilization_ranked = (
    patient_utilization
    .sort_values("Encounter_Count", ascending=False)
    .reset_index(drop=True)
)

concentration_results = []

for pct in [0.01, 0.05, 0.10, 0.25]:
    
    n_patients = max(1, round(len(patient_utilization_ranked) * pct))
    
    top_encounters = (
        patient_utilization_ranked
        .head(n_patients)["Encounter_Count"]
        .sum()
    )
    
    encounter_share = (
        top_encounters / total_encounters
    ) * 100
    
    concentration_results.append({
        "Patient_Segment": f"Top {pct:.0%}",
        "Patients": n_patients,
        "Encounters": top_encounters,
        "Encounter_Share_Percentage": round(encounter_share, 2)
    })

utilization_concentration = pd.DataFrame(
    concentration_results
)

utilization_concentration

  Patient_Segment  Patients  Encounters  Encounter_Share_Percentage
0          Top 1%        10        5759                       20.65
1          Top 5%        49       11562                       41.45
2         Top 10%        97       14819                       53.13
3         Top 25%       244       20418                       73.21

In [194]:
print("Total encounters:", total_encounters)
print("Total patients:", len(patient_utilization))

Total encounters: 27891
Total patients: 974

In [195]:
# ============================================================
# STEP 4.13.3 — CLINICAL UTILIZATION INTENSITY
# ============================================================

patient_utilization["High_Acuity_Encounters"] = (
    patient_utilization["Inpatient_Encounters"]
    + patient_utilization["Emergency_Encounters"]
)

patient_utilization["Emergency_Rate"] = (
    patient_utilization["Emergency_Encounters"]
    / patient_utilization["Encounter_Count"]
    * 100
).round(2)

patient_utilization["Inpatient_Rate"] = (
    patient_utilization["Inpatient_Encounters"]
    / patient_utilization["Encounter_Count"]
    * 100
).round(2)

patient_utilization["High_Acuity_Rate"] = (
    patient_utilization["High_Acuity_Encounters"]
    / patient_utilization["Encounter_Count"]
    * 100
).round(2)

patient_utilization[
    [
        "PATIENT",
        "Encounter_Count",
        "Inpatient_Encounters",
        "Emergency_Encounters",
        "High_Acuity_Encounters",
        "Emergency_Rate",
        "Inpatient_Rate",
        "High_Acuity_Rate"
    ]
].sort_values(
    "High_Acuity_Rate",
    ascending=False
).head(20)

                                  PATIENT  Encounter_Count  Inpatient_Encounters  Emergency_Encounters  High_Acuity_Encounters  Emergency_Rate  Inpatient_Rate  High_Acuity_Rate
836  dccaefe2-518c-a083-d4ab-cea270ce521d               34                     0                    34                      34          100.00            0.00            100.00
893  eadeadde-1b80-76cc-6558-2b5b511be15a                1                     0                     1                       1          100.00            0.00            100.00
947  f95b336a-ec12-455f-b118-7c7ccc965806                1                     0                     1                       1          100.00            0.00            100.00
51   0ecff71d-c81d-3bef-9769-eba85ea6c82a                2                     0                     2                       2          100.00            0.00            100.00
691  b3089b6e-7e37-1385-3bb9-566694b36c1b                1                     0                     1                       1          100.00            0.00            100.00
641  a6997da1-705f-96f8-909b-c421ad97f928                1                     0                     1                       1          100.00            0.00            100.00
636  a59dbbd5-98e9-d341-9ed2-c01010910165                1                     0                     1                       1          100.00            0.00            100.00
774  ca46c770-710c-6cfc-b02f-152f7d6a9de0                2                     0                     2                       2          100.00            0.00            100.00
101  1a3939a9-e4f0-2a02-7697-8ae70501501b                3                     0                     3                       3          100.00            0.00            100.00
107  1bfeb285-817e-4eda-6fbb-609706127115                3                     0                     3                       3          100.00            0.00            100.00
649  a74f1065-3d40-3806-48b1-53d1a8ec72a0                5                     0                     5                       5          100.00            0.00            100.00
92   187dd60c-abb1-c51d-c8b4-f86c06d4e34d                2                     0                     2                       2          100.00            0.00            100.00
785  cea45305-4183-2e9b-f4c8-37220071f61d                1                     0                     1                       1          100.00            0.00            100.00
56   103d9313-a3f2-ce7f-c7c4-613dd9d51b3b                1                     0                     1                       1          100.00            0.00            100.00
804  d3212224-2a5f-6a90-e111-4de13c97882f                2                     0                     2                       2          100.00            0.00            100.00
429  6f54d177-0d59-257b-8cd8-96d7c2254a04                2                     0                     2                       2          100.00            0.00            100.00
427  6e5ae27c-8038-7988-e2c0-25a103f01bfa                1                     0                     1                       1          100.00            0.00            100.00
598  9b7cfa36-1dda-ce55-7c2a-a9a332a5777b                1                     0                     1                       1          100.00            0.00            100.00
16   050a0341-c954-2856-b3a6-580f8a3aaf84                2                     0                     2                       2          100.00            0.00            100.00
391  63ebbeb6-3160-da00-76a3-11888839703a                1                     1                     0                       1            0.00          100.00            100.00

In [196]:
print(
    "Patients with at least one high-acuity encounter:",
    (
        patient_utilization["High_Acuity_Encounters"] > 0
    ).sum()
)

print(
    "Total high-acuity encounters:",
    patient_utilization["High_Acuity_Encounters"].sum()
)

print(
    "Overall high-acuity encounter rate:",
    round(
        patient_utilization["High_Acuity_Encounters"].sum()
        / patient_utilization["Encounter_Count"].sum()
        * 100,
        2
    ),
    "%"
)

Patients with at least one high-acuity encounter: 522
Total high-acuity encounters: 3457
Overall high-acuity encounter rate: 12.39 %

In [197]:
top_cost_patients = (
    patient_utilization
    [
        [
            "PATIENT",
            "Encounter_Count",
            "Total_Encounter_Cost",
            "Total_Payer_Coverage",
            "Total_Patient_Responsibility",
            "Inpatient_Encounters",
            "Emergency_Encounters",
            "Outpatient_Encounters",
            "Ambulatory_Encounters",
            "UrgentCare_Encounters",
            "Wellness_Encounters"
        ]
    ]
    .sort_values(
        "Total_Encounter_Cost",
        ascending=False
    )
    .head(20)
)

top_cost_patients

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters
245,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,"9,932,262.99",0.00,"9,932,262.99",0,172,48,3,213,11
973,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,"6,356,665.66","845,233.69","5,511,431.97",0,0,72,2,206,11
647,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,"3,014,121.02",0.00,"3,014,121.02",0,6,0,15,121,0
174,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,"2,699,823.10",0.00,"2,699,823.10",0,0,0,0,120,0
85,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,"2,437,415.31",0.00,"2,437,415.31",0,0,77,1304,0,0
900,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,"2,090,033.12",0.00,"2,090,033.12",0,0,0,0,94,0
221,37448778-ee2f-f420-1dc0-cb6b5e147025,53,"1,206,558.16",0.00,"1,206,558.16",0,0,0,0,53,0
970,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,"1,181,185.96",0.00,"1,181,185.96",0,4,12,90,0,0
9,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,"1,127,635.83",0.00,"1,127,635.83",52,16,65,36,0,11
70,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,"1,030,983.91","54,044.35","976,939.56",0,0,99,1,0,11
555,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,"1,024,237.46","397,776.45","626,461.01",63,3,43,14,0,9
406,6961609b-1268-6292-9c09-90355f9e73a9,51,"1,002,661.70","347,176.99","655,484.71",0,0,0,0,51,0
444,7412b008-76f9-b713-c514-2a5d82e3b39e,59,"983,828.37",0.00,"983,828.37",54,1,4,0,0,0
5,01296e88-f6d9-1c18-cf91-87523325e034,35,"882,324.24",0.00,"882,324.24",1,2,9,23,0,0
879,e7eaf3df-a981-d555-12d6-fdd50fa2631e,66,"863,712.20","152,955.97","710,756.23",48,2,4,3,1,8
371,5e055638-0dad-dfd5-005d-1e74b6fd29ac,887,"844,913.74","628,529.62","216,384.12",0,17,92,778,0,0
240,3de74169-7f67-9304-91d4-757e0f3a14d2,877,"819,279.19",0.00,"819,279.19",0,49,35,786,0,7
768,c83e8f1b-8f35-5855-0d38-6ea6509ec619,38,"784,682.44","626,448.92","158,233.52",0,0,0,0,38,0
337,5427845a-82ab-b6c9-e70b-aeb672ddd5d7,149,"707,094.17","560,859.04","146,235.13",0,0,0,0,149,0
294,49bc1d54-ed70-7ec5-02cb-76c178292427,42,"704,403.97","559,834.49","144,569.48",27,0,5,3,4,3

In [198]:
# Define high-utilization and high-cost thresholds

high_utilization_threshold = patient_utilization["Encounter_Count"].quantile(0.90)

high_cost_threshold = patient_utilization["Total_Encounter_Cost"].quantile(0.90)

print("High-utilization threshold:", high_utilization_threshold)
print("High-cost threshold:", high_cost_threshold)

High-utilization threshold: 54.700000000000045
High-cost threshold: 241747.92799999999

In [199]:
high_util_high_cost = (
    patient_utilization[
        (patient_utilization["Encounter_Count"] > high_utilization_threshold) &
        (patient_utilization["Total_Encounter_Cost"] > high_cost_threshold)
    ]
    [
        [
            "PATIENT",
            "Encounter_Count",
            "Total_Encounter_Cost",
            "Total_Payer_Coverage",
            "Total_Patient_Responsibility",
            "Inpatient_Encounters",
            "Emergency_Encounters",
            "Outpatient_Encounters",
            "Ambulatory_Encounters",
            "UrgentCare_Encounters",
            "Wellness_Encounters"
        ]
    ]
    .sort_values(
        ["Total_Encounter_Cost", "Encounter_Count"],
        ascending=False
    )
)

print("High-utilization + high-cost patients:", len(high_util_high_cost))

high_util_high_cost

High-utilization + high-cost patients: 36

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters
245,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,"9,932,262.99",0.00,"9,932,262.99",0,172,48,3,213,11
973,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,"6,356,665.66","845,233.69","5,511,431.97",0,0,72,2,206,11
647,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,"3,014,121.02",0.00,"3,014,121.02",0,6,0,15,121,0
174,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,"2,699,823.10",0.00,"2,699,823.10",0,0,0,0,120,0
85,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,"2,437,415.31",0.00,"2,437,415.31",0,0,77,1304,0,0
900,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,"2,090,033.12",0.00,"2,090,033.12",0,0,0,0,94,0
970,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,"1,181,185.96",0.00,"1,181,185.96",0,4,12,90,0,0
9,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,"1,127,635.83",0.00,"1,127,635.83",52,16,65,36,0,11
70,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,"1,030,983.91","54,044.35","976,939.56",0,0,99,1,0,11
555,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,"1,024,237.46","397,776.45","626,461.01",63,3,43,14,0,9
444,7412b008-76f9-b713-c514-2a5d82e3b39e,59,"983,828.37",0.00,"983,828.37",54,1,4,0,0,0
879,e7eaf3df-a981-d555-12d6-fdd50fa2631e,66,"863,712.20","152,955.97","710,756.23",48,2,4,3,1,8
371,5e055638-0dad-dfd5-005d-1e74b6fd29ac,887,"844,913.74","628,529.62","216,384.12",0,17,92,778,0,0
240,3de74169-7f67-9304-91d4-757e0f3a14d2,877,"819,279.19",0.00,"819,279.19",0,49,35,786,0,7
337,5427845a-82ab-b6c9-e70b-aeb672ddd5d7,149,"707,094.17","560,859.04","146,235.13",0,0,0,0,149,0
652,a80b1160-93f0-db7e-9f23-04ea6fdddfaf,59,"636,438.70",0.00,"636,438.70",53,0,1,0,0,5
491,7f0dc5c3-f35c-df5b-8564-95aa38b575d6,83,"625,019.99","352,791.27","272,228.72",1,4,16,62,0,0
972,ff1b3c26-53a6-4590-ce79-a3f7269274ea,72,"616,543.65","16,531.38","600,012.27",0,3,22,37,0,10
564,9279705f-2e5c-2792-ae20-7a77b5b04015,67,"598,712.31","350,771.01","247,941.30",0,3,7,57,0,0
682,b0c95bfd-adc4-8910-a75d-e208879c975d,96,"580,593.75","457,700.11","122,893.64",0,8,67,11,0,10
870,e54023a5-ae9a-fea9-3ad3-08989ea5b5aa,57,"580,149.36",0.00,"580,149.36",0,3,20,34,0,0
229,394f3e43-784c-b938-adb6-4b69efd46bbf,63,"567,891.96","23,888.10","544,003.86",1,4,16,42,0,0
163,283af64b-5b12-f971-6129-f638491a4a5b,55,"563,662.84","447,003.17","116,659.67",35,2,3,7,0,8
1,0034fe01-207f-275f-6b4b-821f7b0af044,75,"548,667.37","5,494.56","543,172.81",4,6,33,32,0,0
239,3d17f121-e015-683b-df1e-21e1ddbaab9c,60,"535,232.95","133,071.21","402,161.74",1,7,11,41,0,0
612,9eb99e6f-21e9-c2dc-835f-13c6a53f9a16,76,"515,240.44","485,089.33","30,151.11",2,7,30,34,3,0
955,fa53fdfe-9fb4-a535-b49b-3ce0fd0998cd,106,"500,872.65","469,666.19","31,206.46",12,1,40,53,0,0
960,fb77a596-afb5-6e06-8cb9-f9ca44b21b78,60,"436,282.34","410,426.02","25,856.32",0,4,16,40,0,0
499,817efce8-3d2a-48a1-6d79-8505d24df078,64,"402,049.48","319,024.86","83,024.62",0,3,32,17,1,11
344,55ae23ff-e1b5-2722-0304-85667b3dad8b,62,"399,008.53","160,447.05","238,561.48",0,5,19,27,0,11
891,ea9d6669-efc3-3c16-4f70-70cc1c1659d7,65,"366,385.72","144,886.50","221,499.22",0,3,12,41,0,9
390,63dd8d79-f75f-a1b2-2d68-9a5840f469ce,66,"343,544.91","74,733.70","268,811.21",0,1,44,21,0,0
67,12f0d3df-7ea9-3005-ea7e-a4c829536a12,73,"331,058.64","289,187.66","41,870.98",49,5,0,19,0,0
316,4f966eb8-d93f-fbfc-298e-8a90ebdeafbe,76,"294,777.26","275,286.88","19,490.38",2,3,54,16,1,0
346,56355c60-1f3a-03ef-57d6-0d9ca841df12,74,"287,108.54","56,603.42","230,505.12",0,1,51,22,0,0
280,45143d96-1165-e949-2c51-422c2df7c679,56,"281,683.11","155,911.38","125,771.73",0,2,42,12,0,0

In [200]:
# Show DataFrame variables currently available in the notebook

df_variables = {
    name: type(obj).__name__
    for name, obj in globals().items()
    if hasattr(obj, "columns")
}

df_variables

{'__': 'DataFrame',
 '___': 'DataFrame',
 'patients': 'DataFrame',
 'encounters': 'DataFrame',
 'procedures': 'DataFrame',
 'payers': 'DataFrame',
 'organizations': 'DataFrame',
 '_2': 'DataFrame',
 '_3': 'DataFrame',
 '_4': 'DataFrame',
 '_5': 'DataFrame',
 '_6': 'DataFrame',
 'df': 'DataFrame',
 'missing': 'DataFrame',
 'procedure_check': 'DataFrame',
 'mismatches': 'DataFrame',
 'dictionary': 'DataFrame',
 'profile': 'DataFrame',
 'patients_clean': 'DataFrame',
 'encounters_clean': 'DataFrame',
 'procedures_clean': 'DataFrame',
 'payers_clean': 'DataFrame',
 'organizations_clean': 'DataFrame',
 'missing_value_audit': 'DataFrame',
 'data': 'DataFrame',
 '_46': 'DataFrame',
 'missing_summary': 'DataFrame',
 '_47': 'DataFrame',
 'post_treatment_missing': 'DataFrame',
 '_50': 'DataFrame',
 'row_count_check': 'DataFrame',
 '_51': 'DataFrame',
 'missing_treatment_log': 'DataFrame',
 '_52': 'DataFrame',
 'encounter_duration_validation': 'DataFrame',
 'procedure_duration_validation': 'DataFrame',
 'encounter_duration_anomalies': 'DataFrame',
 'procedure_duration_anomalies': 'DataFrame',
 'dataset_counts': 'DataFrame',
 'duplicate_summary': 'DataFrame',
 'encounter_date_validation': 'DataFrame',
 'procedure_date_validation': 'DataFrame',
 'quality_checks': 'DataFrame',
 '_75': 'DataFrame',
 '_76': 'DataFrame',
 '_77': 'DataFrame',
 'invalid_death_dates': 'DataFrame',
 '_79': 'DataFrame',
 'invalid_encounter_dates': 'DataFrame',
 'zero_duration_encounters': 'DataFrame',
 'invalid_procedure_dates': 'DataFrame',
 'zero_duration_procedures': 'DataFrame',
 'encounter_patient_dates': 'DataFrame',
 'invalid_birth_encounters': 'DataFrame',
 'procedure_patient_dates': 'DataFrame',
 'invalid_birth_procedures': 'DataFrame',
 '_88': 'DataFrame',
 'negative_duration': 'DataFrame',
 'zero_duration': 'DataFrame',
 'longest_encounters': 'DataFrame',
 '_95': 'DataFrame',
 '_96': 'DataFrame',
 'duration_distribution': 'DataFrame',
 '_97': 'DataFrame',
 'long_encounters': 'DataFrame',
 '_98': 'DataFrame',
 'eda_summary': 'DataFrame',
 '_99': 'DataFrame',
 'gender_distribution': 'DataFrame',
 '_100': 'DataFrame',
 'race_distribution': 'DataFrame',
 'ethnicity_distribution': 'DataFrame',
 '_102': 'DataFrame',
 'marital_distribution': 'DataFrame',
 '_103': 'DataFrame',
 'patients_age': 'DataFrame',
 '_104': 'DataFrame',
 'encounter_class_distribution': 'DataFrame',
 'patient_clinical_utilization': 'DataFrame',
 'rate_validation': 'DataFrame',
 'patient_financial_burden': 'DataFrame',
 'patient_procedure_cost': 'DataFrame',
 'financial_validation': 'DataFrame',
 'obj': 'DataFrame',
 'patient_demographics': 'DataFrame',
 'patient_demographic_utilization': 'DataFrame',
 '_115': 'DataFrame',
 'gender_utilization': 'DataFrame',
 'race_utilization': 'DataFrame',
 'ethnicity_utilization': 'DataFrame',
 'marital_utilization': 'DataFrame',
 'summary': 'DataFrame',
 'demographic_encounter_validation': 'DataFrame',
 'high_acuity_validation': 'DataFrame',
 'emergency_validation': 'DataFrame',
 'encounter_type_cost': 'DataFrame',
 'encounter_type_cost_summary': 'DataFrame',
 'encounter_type_cost_validation': 'DataFrame',
 'payer_distribution': 'DataFrame',
 'payer_patient_responsibility': 'DataFrame',
 'payer_financial_validation': 'DataFrame',
 'procedure_code_distribution': 'DataFrame',
 'procedure_cost_summary': 'DataFrame',
 'top_procedures_by_cost': 'DataFrame',
 'top_procedures_by_frequency': 'DataFrame',
 'top_procedures_by_average_cost': 'DataFrame',
 'high_utilization_procedures': 'DataFrame',
 'procedure_cost_metrics': 'DataFrame',
 'procedure_summary': 'DataFrame',
 'procedure_analysis': 'DataFrame',
 'high_cost_procedures': 'DataFrame',
 'high_unit_cost_procedures': 'DataFrame',
 'high_cost_per_patient': 'DataFrame',
 'high_repeat_procedures': 'DataFrame',
 'profile_counts': 'DataFrame',
 'high_cost_high_utilization': 'DataFrame',
 'high_cost_low_utilization': 'DataFrame',
 'low_cost_high_utilization': 'DataFrame',
 'low_cost_low_utilization': 'DataFrame',
 'overall_metrics': 'DataFrame',
 'procedure_cost_utilization_analysis': 'DataFrame',
 'cost_frequency': 'DataFrame',
 'procedure_quality': 'DataFrame',
 'non_431': 'DataFrame',
 'high_cost_95': 'DataFrame',
 'high_cost_99': 'DataFrame',
 'top_individual_costs': 'DataFrame',
 'procedure_431_analysis': 'DataFrame',
 'procedure_cost_quality_metrics': 'DataFrame',
 'cost_band_summary': 'DataFrame',
 'standardized_codes': 'DataFrame',
 'procedure_431_summary': 'DataFrame',
 'all_431_procedures': 'DataFrame',
 'high_cost_non_431': 'DataFrame',
 'procedure_analytical_summary': 'DataFrame',
 'procedure_e': 'DataFrame',
 'procedure_insight_summary': 'DataFrame',
 'high_cost_non431_procedures': 'DataFrame',
 'high_utilization_procedure_insights': 'DataFrame',
 'high_cost_per_patient_insights': 'DataFrame',
 'high_repeat_utilization': 'DataFrame',
 'procedures_100pct_431': 'DataFrame',
 'procedure_priority': 'DataFrame',
 'procedure_insight_metrics': 'DataFrame',
 'code_description_summary': 'DataFrame',
 'code_variance': 'DataFrame',
 'canonical_variance': 'DataFrame',
 'variant_review': 'DataFrame',
 'procedure_segmentation': 'DataFrame',
 'high_utilization_low_cost': 'DataFrame',
 'procedures_431_dominated': 'DataFrame',
 'procedure_cost_rank': 'DataFrame',
 'procedure_volume_rank': 'DataFrame',
 'priority_distribution': 'DataFrame',
 'cost_intensity_distribution': 'DataFrame',
 'utilization_distribution': 'DataFrame',
 'procedure_18f_metrics': 'DataFrame',
 'validation': 'DataFrame',
 'validation_table': 'DataFrame',
 'procedure_f': 'DataFrame',
 'procedure_f_priority': 'DataFrame',
 'procedure_standardization_validation': 'DataFrame',
 'procedure_cost_segmentation': 'DataFrame',
 'procedure_priority_matrix': 'DataFrame',
 'procedure_f_summary': 'DataFrame',
 'source_df': 'DataFrame',
 'procedure_g': 'DataFrame',
 'canonical_mapping': 'DataFrame',
 'description_counts': 'DataFrame',
 'code_canonical_validation': 'DataFrame',
 'codes_with_multiple_canonical': 'DataFrame',
 'subset': 'DataFrame',
 'description_variance_summary': 'DataFrame',
 'procedure_code_summary': 'DataFrame',
 'procedure_g_summary': 'DataFrame',
 'procedure_g_validation': 'DataFrame',
 'procedure_h': 'DataFrame',
 'top_cost_procedures': 'DataFrame',
 'top_non_431_cost': 'DataFrame',
 'top_utilization': 'DataFrame',
 'top_cost_per_patient': 'DataFrame',
 'cost_ranked': 'DataFrame',
 'non_431_cost_ranked': 'DataFrame',
 'utilization_ranked': 'DataFrame',
 'utilization_intensity_distribution': 'DataFrame',
 'patient_procedure_summary': 'DataFrame',
 'high_procedure_burden_patients': 'DataFrame',
 'work': 'DataFrame',
 'procedure_executive_scorecard': 'DataFrame',
 'high_cost_high_utilization_i': 'DataFrame',
 'high_cost_low_utilization_i': 'DataFrame',
 'high_utilization_low_cost_i': 'DataFrame',
 'high_patient_cost_i': 'DataFrame',
 'high_repeat_procedures_i': 'DataFrame',
 'procedure_431_dependency': 'DataFrame',
 'patient_procedure_lookup': 'DataFrame',
 'highest_patient_procedure': 'DataFrame',
 'procedure_action_matrix': 'DataFrame',
 'executive_procedure_kpis': 'DataFrame',
 'critical_procedure_priority': 'DataFrame',
 'high_financial_priority': 'DataFrame',
 'procedure_i_validation': 'DataFrame',
 'procedure_i': 'DataFrame',
 'procedure_executive_priority': 'DataFrame',
 'procedure_financial_concentration': 'DataFrame',
 'procedure_volume_concentration': 'DataFrame',
 'procedure_cost_patient_analysis': 'DataFrame',
 'procedure_utilization_burden': 'DataFrame',
 'procedure_repeat_analysis': 'DataFrame',
 'non431_ranked': 'DataFrame',
 'util_ranked': 'DataFrame',
 'repeat_ranked': 'DataFrame',
 'top_executive_procedures': 'DataFrame',
 'insight_metrics': 'DataFrame',
 'procedure_watchlist': 'DataFrame',
 'procedure_concentration': 'DataFrame',
 'age_group_summary': 'DataFrame',
 'encounter_volume': 'DataFrame',
 '_142': 'DataFrame',
 'encounter_description': 'DataFrame',
 '_149': 'DataFrame',
 'patient_utilization': 'DataFrame',
 '_150': 'DataFrame',
 'top_utilizers': 'DataFrame',
 '_152': 'DataFrame',
 'cost_summary': 'DataFrame',
 '_153': 'DataFrame',
 'payer_analysis': 'DataFrame',
 '_158': 'DataFrame',
 '_159': 'DataFrame',
 '_160': 'DataFrame',
 '_161': 'DataFrame',
 'procedure_cost': 'DataFrame',
 '_162': 'DataFrame',
 'patient_procedures': 'DataFrame',
 '_163': 'DataFrame',
 'monthly_encounters': 'DataFrame',
 '_166': 'DataFrame',
 'annual_encounters': 'DataFrame',
 '_167': 'DataFrame',
 'annual_procedures': 'DataFrame',
 '_168': 'DataFrame',
 'duration_by_type': 'DataFrame',
 '_169': 'DataFrame',
 '_173': 'DataFrame',
 '_175': 'DataFrame',
 'procedures_per_encounter': 'DataFrame',
 '_178': 'DataFrame',
 'procedure_encounter_check': 'DataFrame',
 'patients_without_encounters': 'DataFrame',
 '_181': 'DataFrame',
 'eda_findings': 'DataFrame',
 '_182': 'DataFrame',
 'duration_outliers': 'DataFrame',
 '_183': 'DataFrame',
 'long_duration_by_type': 'DataFrame',
 '_184': 'DataFrame',
 'duration_profile': 'DataFrame',
 '_188': 'DataFrame',
 'data_quality_summary': 'DataFrame',
 '_189': 'DataFrame',
 '_190': 'DataFrame',
 'high_utilization_patients': 'DataFrame',
 '_191': 'DataFrame',
 'patient_utilization_ranked': 'DataFrame',
 'utilization_concentration': 'DataFrame',
 '_193': 'DataFrame',
 '_195': 'DataFrame',
 'top_cost_patients': 'DataFrame',
 '_197': 'DataFrame',
 'high_util_high_cost': 'DataFrame',
 '_199': 'DataFrame'}

In [201]:
# Profile high-utilization + high-cost patients

high_risk_high_cost = high_util_high_cost.copy()

high_risk_high_cost = high_risk_high_cost.sort_values(
    ["Total_Encounter_Cost", "Encounter_Count"],
    ascending=False
)

high_risk_high_cost.head(20)

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters
245,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,"9,932,262.99",0.00,"9,932,262.99",0,172,48,3,213,11
973,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,"6,356,665.66","845,233.69","5,511,431.97",0,0,72,2,206,11
647,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,"3,014,121.02",0.00,"3,014,121.02",0,6,0,15,121,0
174,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,"2,699,823.10",0.00,"2,699,823.10",0,0,0,0,120,0
85,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,"2,437,415.31",0.00,"2,437,415.31",0,0,77,1304,0,0
900,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,"2,090,033.12",0.00,"2,090,033.12",0,0,0,0,94,0
970,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,"1,181,185.96",0.00,"1,181,185.96",0,4,12,90,0,0
9,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,"1,127,635.83",0.00,"1,127,635.83",52,16,65,36,0,11
70,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,"1,030,983.91","54,044.35","976,939.56",0,0,99,1,0,11
555,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,"1,024,237.46","397,776.45","626,461.01",63,3,43,14,0,9
444,7412b008-76f9-b713-c514-2a5d82e3b39e,59,"983,828.37",0.00,"983,828.37",54,1,4,0,0,0
879,e7eaf3df-a981-d555-12d6-fdd50fa2631e,66,"863,712.20","152,955.97","710,756.23",48,2,4,3,1,8
371,5e055638-0dad-dfd5-005d-1e74b6fd29ac,887,"844,913.74","628,529.62","216,384.12",0,17,92,778,0,0
240,3de74169-7f67-9304-91d4-757e0f3a14d2,877,"819,279.19",0.00,"819,279.19",0,49,35,786,0,7
337,5427845a-82ab-b6c9-e70b-aeb672ddd5d7,149,"707,094.17","560,859.04","146,235.13",0,0,0,0,149,0
652,a80b1160-93f0-db7e-9f23-04ea6fdddfaf,59,"636,438.70",0.00,"636,438.70",53,0,1,0,0,5
491,7f0dc5c3-f35c-df5b-8564-95aa38b575d6,83,"625,019.99","352,791.27","272,228.72",1,4,16,62,0,0
972,ff1b3c26-53a6-4590-ce79-a3f7269274ea,72,"616,543.65","16,531.38","600,012.27",0,3,22,37,0,10
564,9279705f-2e5c-2792-ae20-7a77b5b04015,67,"598,712.31","350,771.01","247,941.30",0,3,7,57,0,0
682,b0c95bfd-adc4-8910-a75d-e208879c975d,96,"580,593.75","457,700.11","122,893.64",0,8,67,11,0,10

In [202]:
# Financial concentration of high-utilization + high-cost patients

total_patients = patient_utilization["PATIENT"].nunique()
total_cost = patient_utilization["Total_Encounter_Cost"].sum()

high_risk_patients = len(high_risk_high_cost)
high_risk_cost = high_risk_high_cost["Total_Encounter_Cost"].sum()

high_risk_patient_share = (
    high_risk_patients / total_patients * 100
)

high_risk_cost_share = (
    high_risk_cost / total_cost * 100
)

print(f"Total patients: {total_patients:,}")
print(f"High-utilization + high-cost patients: {high_risk_patients:,}")
print(f"High-risk patient share: {high_risk_patient_share:.2f}%")
print(f"Total healthcare cost: ${total_cost:,.2f}")
print(f"High-risk patient cost: ${high_risk_cost:,.2f}")
print(f"High-risk cost share: {high_risk_cost_share:.2f}%")

Total patients: 974
High-utilization + high-cost patients: 36
High-risk patient share: 3.70%
Total healthcare cost: $101,514,375.52
High-risk patient cost: $45,124,116.53
High-risk cost share: 44.45%

In [203]:
# Cost composition of high-utilization + high-cost patients

high_risk_patient_ids = high_risk_high_cost["PATIENT"]

high_risk_encounters = encounters_clean[
    encounters_clean["PATIENT"].isin(high_risk_patient_ids)
].copy()

cost_by_encounter_type = (
    high_risk_encounters
    .groupby("ENCOUNTERCLASS")
    .agg(
        Encounter_Count=("Id", "count"),
        Total_Cost=("TOTAL_CLAIM_COST", "sum"),
        Patient_Responsibility=("PATIENT_RESPONSIBILITY", "sum")
    )
    .sort_values("Total_Cost", ascending=False)
)

cost_by_encounter_type["Cost_Share_Percentage"] = (
    cost_by_encounter_type["Total_Cost"]
    / cost_by_encounter_type["Total_Cost"].sum()
    * 100
)

cost_by_encounter_type

                Encounter_Count    Total_Cost  Patient_Responsibility  Cost_Share_Percentage
ENCOUNTERCLASS
urgentcare                  909 17,782,386.89           16,626,093.73                  39.41
ambulatory                 3657 10,466,022.18            7,136,803.70                  23.19
outpatient                 1087  6,769,495.68            5,728,593.42                  15.00
emergency                   345  4,684,205.82            4,529,636.40                  10.38
inpatient                   377  4,220,883.03            3,038,838.30                   9.35
wellness                    132  1,201,122.93              796,238.06                   2.66

In [204]:
# Calculate average cost and patient responsibility per encounter type

cost_intensity = (
    high_risk_encounters
    .groupby("ENCOUNTERCLASS")
    .agg(
        Encounter_Count=("Id", "count"),
        Total_Cost=("TOTAL_CLAIM_COST", "sum"),
        Total_Patient_Responsibility=("PATIENT_RESPONSIBILITY", "sum")
    )
)

cost_intensity["Average_Cost_Per_Encounter"] = (
    cost_intensity["Total_Cost"]
    / cost_intensity["Encounter_Count"]
)

cost_intensity["Average_Patient_Responsibility_Per_Encounter"] = (
    cost_intensity["Total_Patient_Responsibility"]
    / cost_intensity["Encounter_Count"]
)

cost_intensity = cost_intensity.sort_values(
    "Average_Cost_Per_Encounter",
    ascending=False
)

cost_intensity

                Encounter_Count    Total_Cost  Total_Patient_Responsibility  Average_Cost_Per_Encounter  Average_Patient_Responsibility_Per_Encounter
ENCOUNTERCLASS
urgentcare                  909 17,782,386.89                 16,626,093.73                   19,562.58                                     18,290.53
emergency                   345  4,684,205.82                  4,529,636.40                   13,577.41                                     13,129.38
inpatient                   377  4,220,883.03                  3,038,838.30                   11,195.98                                      8,060.58
wellness                    132  1,201,122.93                    796,238.06                    9,099.42                                      6,032.11
outpatient                 1087  6,769,495.68                  5,728,593.42                    6,227.69                                      5,270.10
ambulatory                 3657 10,466,022.18                  7,136,803.70                    2,861.91                                      1,951.55

In [205]:
# Rank high-utilization + high-cost patients by financial burden

financial_burden_high_risk = (
    high_risk_high_cost[
        [
            "PATIENT",
            "Encounter_Count",
            "Total_Encounter_Cost",
            "Total_Payer_Coverage",
            "Total_Patient_Responsibility"
        ]
    ]
    .copy()
)

financial_burden_high_risk["Patient_Responsibility_Rate"] = (
    financial_burden_high_risk["Total_Patient_Responsibility"]
    / financial_burden_high_risk["Total_Encounter_Cost"]
    * 100
)

financial_burden_high_risk = (
    financial_burden_high_risk
    .sort_values(
        "Total_Patient_Responsibility",
        ascending=False
    )
)

financial_burden_high_risk.head(20)

                                  PATIENT  Encounter_Count  Total_Encounter_Cost  Total_Payer_Coverage  Total_Patient_Responsibility  Patient_Responsibility_Rate
245  3f523789-55f3-bb31-2757-4803ca6a9c2a              447          9,932,262.99                  0.00                  9,932,262.99                       100.00
973  ff331e5c-ab16-e218-f39a-63e11de1ed75              291          6,356,665.66            845,233.69                  5,511,431.97                        86.70
647  a733bbc1-cbdf-992f-f1b7-bd230028fc4f              142          3,014,121.02                  0.00                  3,014,121.02                       100.00
174  2aa3ac2a-88c6-3253-547d-6d8ed69790a3              120          2,699,823.10                  0.00                  2,699,823.10                       100.00
85   1712d26d-822d-1e3a-2267-0a9dba31d7c8             1381          2,437,415.31                  0.00                  2,437,415.31                       100.00
900  eda6bc14-b236-e8c6-509a-b293e9cc688b               94          2,090,033.12                  0.00                  2,090,033.12                       100.00
970  fea2a30d-f7c9-eeb0-9aad-5c711f55574f              106          1,181,185.96                  0.00                  1,181,185.96                       100.00
9    0226f105-2572-1c6f-15f0-1aa0438e40d0              180          1,127,635.83                  0.00                  1,127,635.83                       100.00
444  7412b008-76f9-b713-c514-2a5d82e3b39e               59            983,828.37                  0.00                    983,828.37                       100.00
70   1375a6a6-5638-8af1-dc4f-2aa58220d36d              111          1,030,983.91             54,044.35                    976,939.56                        94.76
240  3de74169-7f67-9304-91d4-757e0f3a14d2              877            819,279.19                  0.00                    819,279.19                       100.00
879  e7eaf3df-a981-d555-12d6-fdd50fa2631e               66            863,712.20            152,955.97                    710,756.23                        82.29
652  a80b1160-93f0-db7e-9f23-04ea6fdddfaf               59            636,438.70                  0.00                    636,438.70                       100.00
555  905d0433-9ca3-4883-cbd4-3df36fd5f1c6              132          1,024,237.46            397,776.45                    626,461.01                        61.16
972  ff1b3c26-53a6-4590-ce79-a3f7269274ea               72            616,543.65             16,531.38                    600,012.27                        97.32
870  e54023a5-ae9a-fea9-3ad3-08989ea5b5aa               57            580,149.36                  0.00                    580,149.36                       100.00
229  394f3e43-784c-b938-adb6-4b69efd46bbf               63            567,891.96             23,888.10                    544,003.86                        95.79
1    0034fe01-207f-275f-6b4b-821f7b0af044               75            548,667.37              5,494.56                    543,172.81                        99.00
239  3d17f121-e015-683b-df1e-21e1ddbaab9c               60            535,232.95            133,071.21                    402,161.74                        75.14
491  7f0dc5c3-f35c-df5b-8564-95aa38b575d6               83            625,019.99            352,791.27                    272,228.72                        43.56

In [206]:
# Aggregate financial burden among high-utilization + high-cost patients

high_risk_total_cost = high_risk_high_cost["Total_Encounter_Cost"].sum()
high_risk_payer_coverage = high_risk_high_cost["Total_Payer_Coverage"].sum()
high_risk_patient_responsibility = (
    high_risk_high_cost["Total_Patient_Responsibility"].sum()
)

high_risk_patient_responsibility_rate = (
    high_risk_patient_responsibility
    / high_risk_total_cost
    * 100
)

print(f"High-risk total cost: ${high_risk_total_cost:,.2f}")
print(f"High-risk payer coverage: ${high_risk_payer_coverage:,.2f}")
print(
    f"High-risk patient responsibility: "
    f"${high_risk_patient_responsibility:,.2f}"
)
print(
    f"High-risk patient responsibility rate: "
    f"{high_risk_patient_responsibility_rate:.2f}%"
)

High-risk total cost: $45,124,116.53
High-risk payer coverage: $7,267,912.92
High-risk patient responsibility: $37,856,203.61
High-risk patient responsibility rate: 83.89%

In [207]:
patient_utilization.columns.tolist()

['PATIENT',
 'Encounter_Count',
 'Total_Encounter_Cost',
 'Total_Payer_Coverage',
 'Total_Patient_Responsibility',
 'Inpatient_Encounters',
 'Emergency_Encounters',
 'Outpatient_Encounters',
 'Ambulatory_Encounters',
 'UrgentCare_Encounters',
 'Wellness_Encounters',
 'High_Acuity_Encounters',
 'Emergency_Rate',
 'Inpatient_Rate',
 'High_Acuity_Rate']

In [208]:
patient_utilization.head()

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters,High_Acuity_Encounters,Emergency_Rate,Inpatient_Rate,High_Acuity_Rate
0,002bc307-2fff-04ba-161b-98cce123e226,46,"13,742.67","9,509.86","4,232.81",2,3,38,3,0,0,5,6.52,4.35,10.87
1,0034fe01-207f-275f-6b4b-821f7b0af044,75,"548,667.37","5,494.56","543,172.81",4,6,33,32,0,0,10,8.00,5.33,13.33
2,00abe029-00fa-a666-34f5-258a36978f6d,22,"48,334.27","6,384.67","41,949.60",0,1,5,16,0,0,1,4.55,0.00,4.55
3,010ff9c1-564b-6e32-09f4-29cb4224bba9,4,"26,367.50","19,475.04","6,892.46",0,0,1,3,0,0,0,0.00,0.00,0.00
4,01274098-150f-8211-6150-29f2a2da266c,1,0.00,0.00,0.00,1,0,0,0,0,0,1,0.00,100.00,100.00

In [209]:
import numpy as np

In [210]:
np.__version__

'2.5.1'

In [211]:
# Segment patients by utilization and cost

patient_risk_segments = patient_utilization.copy()

patient_risk_segments["Risk_Segment"] = np.select(
    [
        (patient_risk_segments["Encounter_Count"] > high_utilization_threshold) &
        (patient_risk_segments["Total_Encounter_Cost"] > high_cost_threshold),

        (patient_risk_segments["Encounter_Count"] > high_utilization_threshold) &
        (patient_risk_segments["Total_Encounter_Cost"] <= high_cost_threshold),

        (patient_risk_segments["Encounter_Count"] <= high_utilization_threshold) &
        (patient_risk_segments["Total_Encounter_Cost"] > high_cost_threshold),

        (patient_risk_segments["Encounter_Count"] <= high_utilization_threshold) &
        (patient_risk_segments["Total_Encounter_Cost"] <= high_cost_threshold)
    ],
    [
        "High Utilization + High Cost",
        "High Utilization + Lower Cost",
        "Lower Utilization + High Cost",
        "Lower Utilization + Lower Cost"
    ],
    default="Unclassified"
)

risk_segment_summary = (
    patient_risk_segments
    .groupby("Risk_Segment")
    .agg(
        Patients=("PATIENT", "count"),
        Total_Encounters=("Encounter_Count", "sum"),
        Total_Cost=("Total_Encounter_Cost", "sum"),
        Total_Patient_Responsibility=("Total_Patient_Responsibility", "sum")
    )
    .sort_values("Total_Cost", ascending=False)
)

risk_segment_summary["Patient_Share_Percentage"] = (
    risk_segment_summary["Patients"] /
    len(patient_risk_segments) * 100
).round(2)

risk_segment_summary["Cost_Share_Percentage"] = (
    risk_segment_summary["Total_Cost"] /
    risk_segment_summary["Total_Cost"].sum() * 100
).round(2)

risk_segment_summary

                                Patients  Total_Encounters    Total_Cost  Total_Patient_Responsibility  Patient_Share_Percentage  Cost_Share_Percentage
Risk_Segment
High Utilization + High Cost          36              6507 45,124,116.53                 37,856,203.61                      3.70                  44.45
Lower Utilization + High Cost         62              2256 26,436,255.87                 16,374,185.97                      6.37                  26.04
Lower Utilization + Lower Cost       814             10761 25,199,883.60                 13,302,562.58                     83.57                  24.82
High Utilization + Lower Cost         62              8367  4,754,119.52                  2,883,916.37                      6.37                   4.68

In [212]:
# Profile the high-utilization + high-cost patient segment

high_risk_profile = patient_utilization[
    (patient_utilization["Encounter_Count"] > high_utilization_threshold) &
    (patient_utilization["Total_Encounter_Cost"] > high_cost_threshold)
].copy()

high_risk_profile_summary = pd.DataFrame({
    "Metric": [
        "Patients",
        "Average Encounters per Patient",
        "Median Encounters per Patient",
        "Average Total Cost per Patient",
        "Median Total Cost per Patient",
        "Average Patient Responsibility",
        "Median Patient Responsibility",
        "Average High-Acuity Rate"
    ],
    "Value": [
        len(high_risk_profile),
        high_risk_profile["Encounter_Count"].mean(),
        high_risk_profile["Encounter_Count"].median(),
        high_risk_profile["Total_Encounter_Cost"].mean(),
        high_risk_profile["Total_Encounter_Cost"].median(),
        high_risk_profile["Total_Patient_Responsibility"].mean(),
        high_risk_profile["Total_Patient_Responsibility"].median(),
        high_risk_profile["High_Acuity_Rate"].mean()
    ]
})

high_risk_profile_summary

                           Metric        Value
0                        Patients        36.00
1  Average Encounters per Patient       180.75
2   Median Encounters per Patient        75.50
3  Average Total Cost per Patient 1,253,447.68
4   Median Total Cost per Patient   607,627.98
5  Average Patient Responsibility 1,051,561.21
6   Median Patient Responsibility   472,667.28
7        Average High-Acuity Rate        18.50

In [213]:
# Top 10 high-utilization + high-cost patients by total cost

top_high_risk_cost = (
    high_risk_profile[
        [
            "PATIENT",
            "Encounter_Count",
            "Total_Encounter_Cost",
            "Total_Payer_Coverage",
            "Total_Patient_Responsibility",
            "High_Acuity_Encounters",
            "High_Acuity_Rate"
        ]
    ]
    .sort_values(
        "Total_Encounter_Cost",
        ascending=False
    )
    .head(10)
)

top_high_risk_cost

                                  PATIENT  Encounter_Count  Total_Encounter_Cost  Total_Payer_Coverage  Total_Patient_Responsibility  High_Acuity_Encounters  High_Acuity_Rate
245  3f523789-55f3-bb31-2757-4803ca6a9c2a              447          9,932,262.99                  0.00                  9,932,262.99                     172             38.48
973  ff331e5c-ab16-e218-f39a-63e11de1ed75              291          6,356,665.66            845,233.69                  5,511,431.97                       0              0.00
647  a733bbc1-cbdf-992f-f1b7-bd230028fc4f              142          3,014,121.02                  0.00                  3,014,121.02                       6              4.23
174  2aa3ac2a-88c6-3253-547d-6d8ed69790a3              120          2,699,823.10                  0.00                  2,699,823.10                       0              0.00
85   1712d26d-822d-1e3a-2267-0a9dba31d7c8             1381          2,437,415.31                  0.00                  2,437,415.31                       0              0.00
900  eda6bc14-b236-e8c6-509a-b293e9cc688b               94          2,090,033.12                  0.00                  2,090,033.12                       0              0.00
970  fea2a30d-f7c9-eeb0-9aad-5c711f55574f              106          1,181,185.96                  0.00                  1,181,185.96                       4              3.77
9    0226f105-2572-1c6f-15f0-1aa0438e40d0              180          1,127,635.83                  0.00                  1,127,635.83                      68             37.78
70   1375a6a6-5638-8af1-dc4f-2aa58220d36d              111          1,030,983.91             54,044.35                    976,939.56                       0              0.00
555  905d0433-9ca3-4883-cbd4-3df36fd5f1c6              132          1,024,237.46            397,776.45                    626,461.01                      66             50.00

In [214]:
# Calculate cost concentration among the top 10 high-risk patients

top_10_high_risk_cost = top_high_risk_cost["Total_Encounter_Cost"].sum()

high_risk_total_cost = high_risk_profile["Total_Encounter_Cost"].sum()

top_10_cost_share = (
    top_10_high_risk_cost / high_risk_total_cost
) * 100

print(f"High-risk total cost: ${high_risk_total_cost:,.2f}")
print(f"Top 10 high-risk patient cost: ${top_10_high_risk_cost:,.2f}")
print(f"Top 10 cost share of high-risk group: {top_10_cost_share:.2f}%")

High-risk total cost: $45,124,116.53
Top 10 high-risk patient cost: $30,894,364.36
Top 10 cost share of high-risk group: 68.47%

In [215]:
# Analyze relationship between utilization and cost
# among high-utilization + high-cost patients

high_risk_correlation = high_risk_profile[
    [
        "Encounter_Count",
        "Total_Encounter_Cost",
        "Total_Patient_Responsibility",
        "High_Acuity_Rate"
    ]
].corr()

high_risk_correlation

                              Encounter_Count  Total_Encounter_Cost  Total_Patient_Responsibility  High_Acuity_Rate
Encounter_Count                          1.00                  0.29                          0.29             -0.18
Total_Encounter_Cost                     0.29                  1.00                          0.99              0.00
Total_Patient_Responsibility             0.29                  0.99                          1.00              0.01
High_Acuity_Rate                        -0.18                  0.00                          0.01              1.00

In [216]:
# Final high-risk patient dataset

high_risk_final = (
    high_risk_profile[
        [
            "PATIENT",
            "Encounter_Count",
            "Total_Encounter_Cost",
            "Total_Payer_Coverage",
            "Total_Patient_Responsibility",
            "Inpatient_Encounters",
            "Emergency_Encounters",
            "Outpatient_Encounters",
            "Ambulatory_Encounters",
            "UrgentCare_Encounters",
            "Wellness_Encounters",
            "High_Acuity_Encounters",
            "Emergency_Rate",
            "Inpatient_Rate",
            "High_Acuity_Rate"
        ]
    ]
    .sort_values(
        "Total_Encounter_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)

high_risk_final.head(10)

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters,High_Acuity_Encounters,Emergency_Rate,Inpatient_Rate,High_Acuity_Rate
0,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,"9,932,262.99",0.00,"9,932,262.99",0,172,48,3,213,11,172,38.48,0.00,38.48
1,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,"6,356,665.66","845,233.69","5,511,431.97",0,0,72,2,206,11,0,0.00,0.00,0.00
2,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,"3,014,121.02",0.00,"3,014,121.02",0,6,0,15,121,0,6,4.23,0.00,4.23
3,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,"2,699,823.10",0.00,"2,699,823.10",0,0,0,0,120,0,0,0.00,0.00,0.00
4,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,"2,437,415.31",0.00,"2,437,415.31",0,0,77,1304,0,0,0,0.00,0.00,0.00
5,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,"2,090,033.12",0.00,"2,090,033.12",0,0,0,0,94,0,0,0.00,0.00,0.00
6,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,"1,181,185.96",0.00,"1,181,185.96",0,4,12,90,0,0,4,3.77,0.00,3.77
7,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,"1,127,635.83",0.00,"1,127,635.83",52,16,65,36,0,11,68,8.89,28.89,37.78
8,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,"1,030,983.91","54,044.35","976,939.56",0,0,99,1,0,11,0,0.00,0.00,0.00
9,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,"1,024,237.46","397,776.45","626,461.01",63,3,43,14,0,9,66,2.27,47.73,50.00

Patient utilization and cost were highly concentrated. Only 3.70% of patients were classified as high-utilization/high-cost, yet they accounted for 44.45% of total healthcare expenditure. A further 6.37% of patients were lower-utilization but high-cost, contributing another 26.04% of total costs. Combined, approximately 10% of patients generated over 70% of total healthcare costs. Meanwhile, high-utilization/low-cost patients represented 6.37% of the population and approximately 30% of encounters but only 4.68% of total costs. This demonstrates that healthcare utilization volume alone is insufficient for identifying financially high-impact patients and supports a segmented approach to care management and resource allocation.

In [217]:
# STEP 6.1 — Rebuild high-risk patients using the current patient_utilization

high_util_high_cost = patient_utilization[
    (patient_utilization["Encounter_Count"] > high_utilization_threshold) &
    (patient_utilization["Total_Encounter_Cost"] > high_cost_threshold)
].copy()

# Create the business summary
high_risk_business_summary = high_util_high_cost[
    [
        "PATIENT",
        "Encounter_Count",
        "Total_Encounter_Cost",
        "Total_Payer_Coverage",
        "Total_Patient_Responsibility",
        "High_Acuity_Encounters",
        "High_Acuity_Rate"
    ]
].sort_values(
    "Total_Encounter_Cost",
    ascending=False
).reset_index(drop=True)

high_risk_business_summary.head(10)

                                PATIENT  Encounter_Count  Total_Encounter_Cost  Total_Payer_Coverage  Total_Patient_Responsibility  High_Acuity_Encounters  High_Acuity_Rate
0  3f523789-55f3-bb31-2757-4803ca6a9c2a              447          9,932,262.99                  0.00                  9,932,262.99                     172             38.48
1  ff331e5c-ab16-e218-f39a-63e11de1ed75              291          6,356,665.66            845,233.69                  5,511,431.97                       0              0.00
2  a733bbc1-cbdf-992f-f1b7-bd230028fc4f              142          3,014,121.02                  0.00                  3,014,121.02                       6              4.23
3  2aa3ac2a-88c6-3253-547d-6d8ed69790a3              120          2,699,823.10                  0.00                  2,699,823.10                       0              0.00
4  1712d26d-822d-1e3a-2267-0a9dba31d7c8             1381          2,437,415.31                  0.00                  2,437,415.31                       0              0.00
5  eda6bc14-b236-e8c6-509a-b293e9cc688b               94          2,090,033.12                  0.00                  2,090,033.12                       0              0.00
6  fea2a30d-f7c9-eeb0-9aad-5c711f55574f              106          1,181,185.96                  0.00                  1,181,185.96                       4              3.77
7  0226f105-2572-1c6f-15f0-1aa0438e40d0              180          1,127,635.83                  0.00                  1,127,635.83                      68             37.78
8  1375a6a6-5638-8af1-dc4f-2aa58220d36d              111          1,030,983.91             54,044.35                    976,939.56                       0              0.00
9  905d0433-9ca3-4883-cbd4-3df36fd5f1c6              132          1,024,237.46            397,776.45                    626,461.01                      66             50.00

In [218]:
print(patient_utilization.columns.tolist())

['PATIENT', 'Encounter_Count', 'Total_Encounter_Cost', 'Total_Payer_Coverage', 'Total_Patient_Responsibility', 'Inpatient_Encounters', 'Emergency_Encounters', 'Outpatient_Encounters', 'Ambulatory_Encounters', 'UrgentCare_Encounters', 'Wellness_Encounters', 'High_Acuity_Encounters', 'Emergency_Rate', 'Inpatient_Rate', 'High_Acuity_Rate']

In [219]:
# ============================================================
# STEP 4.8 — DATA QUALITY SUMMARY
# ============================================================

data_quality_summary = pd.DataFrame({
    "Check": [
        "Patients",
        "Encounters",
        "Procedures",
        "Payers",
        "Organizations",
        "Missing age at encounter",
        "Negative age at encounter",
        "Missing age groups",
        "Patients with death dates",
        "Negative age at death",
        "Long encounters >7 days",
        "Procedures without valid encounters",
        "Patients with no encounters",
        "Negative patient responsibility"
    ],
    "Result": [
        len(patients_clean),
        len(encounters_clean),
        len(procedures_clean),
        len(payers_clean),
        len(organizations_clean),
        encounters_clean["AGE_AT_ENCOUNTER"].isna().sum(),
        (encounters_clean["AGE_AT_ENCOUNTER"] < 0).sum(),
        encounters_clean["AGE_GROUP"].isna().sum(),
        patients_clean["DEATHDATE"].notna().sum(),
        (patients_clean["AGE_AT_DEATH"] < 0).sum(),
        (encounters_clean["DURATION_DAYS"] > 7).sum(),
        0,
        0,
        (encounters_clean["PATIENT_RESPONSIBILITY"] < 0).sum()
    ]
})

data_quality_summary

                                  Check  Result
0                              Patients     974
1                            Encounters   27891
2                            Procedures   47701
3                                Payers      10
4                         Organizations       1
5              Missing age at encounter       0
6             Negative age at encounter       0
7                    Missing age groups       0
8             Patients with death dates     154
9                 Negative age at death       0
10              Long encounters >7 days      31
11  Procedures without valid encounters       0
12          Patients with no encounters       0
13      Negative patient responsibility       0

In [220]:
# STEP 6.4 — Overall financial burden and high-risk comparison

overall_financial_summary = pd.DataFrame({
    "Metric": [
        "Total Healthcare Cost",
        "Total Payer Coverage",
        "Total Patient Responsibility",
        "Overall Patient Responsibility Rate",
        "High-Risk Healthcare Cost",
        "High-Risk Payer Coverage",
        "High-Risk Patient Responsibility",
        "High-Risk Patient Responsibility Rate"
    ],
    "Value": [
        patient_utilization["Total_Encounter_Cost"].sum(),
        patient_utilization["Total_Payer_Coverage"].sum(),
        patient_utilization["Total_Patient_Responsibility"].sum(),
        (
            patient_utilization["Total_Patient_Responsibility"].sum()
            / patient_utilization["Total_Encounter_Cost"].sum()
            * 100
        ),
        high_util_high_cost["Total_Encounter_Cost"].sum(),
        high_util_high_cost["Total_Payer_Coverage"].sum(),
        high_util_high_cost["Total_Patient_Responsibility"].sum(),
        (
            high_util_high_cost["Total_Patient_Responsibility"].sum()
            / high_util_high_cost["Total_Encounter_Cost"].sum()
            * 100
        )
    ]
})

overall_financial_summary

                                  Metric          Value
0                  Total Healthcare Cost 101,514,375.52
1                   Total Payer Coverage  31,097,506.99
2           Total Patient Responsibility  70,416,868.53
3    Overall Patient Responsibility Rate          69.37
4              High-Risk Healthcare Cost  45,124,116.53
5               High-Risk Payer Coverage   7,267,912.92
6       High-Risk Patient Responsibility  37,856,203.61
7  High-Risk Patient Responsibility Rate          83.89

In [221]:
# STEP 6.5 — Cost concentration among high-cost patients

high_cost_segments = patient_risk_segments[
    patient_risk_segments["Risk_Segment"].isin([
        "High Utilization + High Cost",
        "Lower Utilization + High Cost"
    ])
].copy()

high_cost_concentration = pd.DataFrame({
    "Metric": [
        "Total Patients",
        "Patient Share (%)",
        "Total Healthcare Cost",
        "Cost Share (%)"
    ],
    "Value": [
        high_cost_segments["PATIENT"].nunique(),
        (
            high_cost_segments["PATIENT"].nunique()
            / patient_risk_segments["PATIENT"].nunique()
            * 100
        ),
        high_cost_segments["Total_Encounter_Cost"].sum(),
        (
            high_cost_segments["Total_Encounter_Cost"].sum()
            / patient_risk_segments["Total_Encounter_Cost"].sum()
            * 100
        )
    ]
})

high_cost_concentration

                  Metric         Value
0         Total Patients         98.00
1      Patient Share (%)         10.06
2  Total Healthcare Cost 71,560,372.40
3         Cost Share (%)         70.49

In [222]:
# STEP 6.6 — Profile the four patient risk segments

risk_segment_profile = (
    patient_risk_segments
    .groupby("Risk_Segment")
    .agg(
        Patients=("PATIENT", "nunique"),
        Avg_Encounters_Per_Patient=("Encounter_Count", "mean"),
        Median_Encounters_Per_Patient=("Encounter_Count", "median"),
        Avg_Healthcare_Cost=("Total_Encounter_Cost", "mean"),
        Median_Healthcare_Cost=("Total_Encounter_Cost", "median"),
        Avg_Patient_Responsibility=("Total_Patient_Responsibility", "mean"),
        Median_Patient_Responsibility=("Total_Patient_Responsibility", "median"),
        Avg_High_Acuity_Rate=("High_Acuity_Rate", "mean")
    )
    .reset_index()
)

risk_segment_profile

                     Risk_Segment  Patients  Avg_Encounters_Per_Patient  Median_Encounters_Per_Patient  Avg_Healthcare_Cost  Median_Healthcare_Cost  Avg_Patient_Responsibility  Median_Patient_Responsibility  Avg_High_Acuity_Rate
0    High Utilization + High Cost        36                      180.75                          75.50         1,253,447.68              607,627.98                1,051,561.21                     472,667.28                 18.50
1   High Utilization + Lower Cost        62                      134.95                          99.50            76,679.35               63,488.22                   46,514.78                      34,609.34                 15.83
2   Lower Utilization + High Cost        62                       36.39                          37.00           426,391.22              372,800.90                  264,099.77                     248,128.73                 10.94
3  Lower Utilization + Lower Cost       814                       13.22                          10.00            30,958.09               17,046.51                   16,342.21                       5,246.17                 11.30

In [223]:
# STEP 6.2 — High-Risk Patient Characteristics

# Identify the 36 high-utilization + high-cost patients
high_risk_patients = patient_utilization[
    (patient_utilization["Encounter_Count"] > high_utilization_threshold) &
    (patient_utilization["Total_Encounter_Cost"] > high_cost_threshold)
].copy()

# Create a profile of the high-risk group
high_risk_profile = pd.DataFrame({
    "Metric": [
        "Patients",
        "Average Encounters",
        "Median Encounters",
        "Average Healthcare Cost",
        "Median Healthcare Cost",
        "Average Patient Responsibility",
        "Average Emergency Rate",
        "Average Inpatient Rate",
        "Average High-Acuity Rate"
    ],
    "Value": [
        len(high_risk_patients),
        high_risk_patients["Encounter_Count"].mean(),
        high_risk_patients["Encounter_Count"].median(),
        high_risk_patients["Total_Encounter_Cost"].mean(),
        high_risk_patients["Total_Encounter_Cost"].median(),
        high_risk_patients["Total_Patient_Responsibility"].mean(),
        high_risk_patients["Emergency_Rate"].mean(),
        high_risk_patients["Inpatient_Rate"].mean(),
        high_risk_patients["High_Acuity_Rate"].mean()
    ]
})

high_risk_profile

                           Metric        Value
0                        Patients        36.00
1              Average Encounters       180.75
2               Median Encounters        75.50
3         Average Healthcare Cost 1,253,447.68
4          Median Healthcare Cost   607,627.98
5  Average Patient Responsibility 1,051,561.21
6          Average Emergency Rate         4.95
7          Average Inpatient Rate        13.55
8        Average High-Acuity Rate        18.50

In [224]:
# Create comparison group
non_high_risk = patient_utilization[
    ~patient_utilization["PATIENT"].isin(high_risk_patients["PATIENT"])
].copy()

comparison = pd.DataFrame({
    "Metric": [
        "Average Encounters",
        "Average Healthcare Cost",
        "Average Patient Responsibility",
        "Average Emergency Rate",
        "Average Inpatient Rate",
        "Average High-Acuity Rate"
    ],
    "High_Risk": [
        high_risk_patients["Encounter_Count"].mean(),
        high_risk_patients["Total_Encounter_Cost"].mean(),
        high_risk_patients["Total_Patient_Responsibility"].mean(),
        high_risk_patients["Emergency_Rate"].mean(),
        high_risk_patients["Inpatient_Rate"].mean(),
        high_risk_patients["High_Acuity_Rate"].mean()
    ],
    "Other_Patients": [
        non_high_risk["Encounter_Count"].mean(),
        non_high_risk["Total_Encounter_Cost"].mean(),
        non_high_risk["Total_Patient_Responsibility"].mean(),
        non_high_risk["Emergency_Rate"].mean(),
        non_high_risk["Inpatient_Rate"].mean(),
        non_high_risk["High_Acuity_Rate"].mean()
    ]
})

comparison

                           Metric    High_Risk  Other_Patients
0              Average Encounters       180.75           22.80
1         Average Healthcare Cost 1,253,447.68       60,117.55
2  Average Patient Responsibility 1,051,561.21       34,712.86
3          Average Emergency Rate         4.95            8.77
4          Average Inpatient Rate        13.55            2.81
5        Average High-Acuity Rate        18.50           11.58

In [225]:
# STEP 6.3 — High-Risk Encounter Mix and Cost Drivers

# Get all encounters belonging to high-risk patients
high_risk_ids = high_risk_patients["PATIENT"]

high_risk_encounters = encounters_clean[
    encounters_clean["PATIENT"].isin(high_risk_ids)
].copy()

# Summarize encounter types
high_risk_encounter_mix = (
    high_risk_encounters
    .groupby("ENCOUNTERCLASS")
    .agg(
        Encounter_Count=("Id", "count"),
        Total_Cost=("TOTAL_CLAIM_COST", "sum"),
        Patient_Responsibility=("PATIENT_RESPONSIBILITY", "sum")
    )
    .reset_index()
)

# Calculate percentages
high_risk_encounter_mix["Encounter_Share_Percentage"] = (
    high_risk_encounter_mix["Encounter_Count"]
    / high_risk_encounter_mix["Encounter_Count"].sum()
    * 100
)

high_risk_encounter_mix["Cost_Share_Percentage"] = (
    high_risk_encounter_mix["Total_Cost"]
    / high_risk_encounter_mix["Total_Cost"].sum()
    * 100
)

# Average cost per encounter
high_risk_encounter_mix["Average_Cost_Per_Encounter"] = (
    high_risk_encounter_mix["Total_Cost"]
    / high_risk_encounter_mix["Encounter_Count"]
)

high_risk_encounter_mix.sort_values(
    "Total_Cost",
    ascending=False
)

  ENCOUNTERCLASS  Encounter_Count    Total_Cost  Patient_Responsibility  Encounter_Share_Percentage  Cost_Share_Percentage  Average_Cost_Per_Encounter
4     urgentcare              909 17,782,386.89           16,626,093.73                       13.97                  39.41                   19,562.58
0     ambulatory             3657 10,466,022.18            7,136,803.70                       56.20                  23.19                    2,861.91
3     outpatient             1087  6,769,495.68            5,728,593.42                       16.71                  15.00                    6,227.69
1      emergency              345  4,684,205.82            4,529,636.40                        5.30                  10.38                   13,577.41
2      inpatient              377  4,220,883.03            3,038,838.30                        5.79                   9.35                   11,195.98
5       wellness              132  1,201,122.93              796,238.06                        2.03                   2.66                    9,099.42

In [226]:
# STEP 6.4 — Highest-Burden High-Risk Patients

high_risk_patient_profile = high_risk_patients[
    [
        "PATIENT",
        "Encounter_Count",
        "Total_Encounter_Cost",
        "Total_Payer_Coverage",
        "Total_Patient_Responsibility",
        "Inpatient_Encounters",
        "Emergency_Encounters",
        "Outpatient_Encounters",
        "Ambulatory_Encounters",
        "UrgentCare_Encounters",
        "Wellness_Encounters",
        "High_Acuity_Encounters",
        "Emergency_Rate",
        "Inpatient_Rate",
        "High_Acuity_Rate"
    ]
].copy()

# Rank by total healthcare cost
high_risk_patient_profile = (
    high_risk_patient_profile
    .sort_values(
        "Total_Encounter_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)

high_risk_patient_profile.head(10)

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters,High_Acuity_Encounters,Emergency_Rate,Inpatient_Rate,High_Acuity_Rate
0,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,"9,932,262.99",0.00,"9,932,262.99",0,172,48,3,213,11,172,38.48,0.00,38.48
1,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,"6,356,665.66","845,233.69","5,511,431.97",0,0,72,2,206,11,0,0.00,0.00,0.00
2,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,"3,014,121.02",0.00,"3,014,121.02",0,6,0,15,121,0,6,4.23,0.00,4.23
3,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,"2,699,823.10",0.00,"2,699,823.10",0,0,0,0,120,0,0,0.00,0.00,0.00
4,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,"2,437,415.31",0.00,"2,437,415.31",0,0,77,1304,0,0,0,0.00,0.00,0.00
5,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,"2,090,033.12",0.00,"2,090,033.12",0,0,0,0,94,0,0,0.00,0.00,0.00
6,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,"1,181,185.96",0.00,"1,181,185.96",0,4,12,90,0,0,4,3.77,0.00,3.77
7,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,"1,127,635.83",0.00,"1,127,635.83",52,16,65,36,0,11,68,8.89,28.89,37.78
8,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,"1,030,983.91","54,044.35","976,939.56",0,0,99,1,0,11,0,0.00,0.00,0.00
9,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,"1,024,237.46","397,776.45","626,461.01",63,3,43,14,0,9,66,2.27,47.73,50.00

In [227]:
# Top 10 high-risk patient cost concentration

top_10_cost = high_risk_patient_profile.head(10)["Total_Encounter_Cost"].sum()

high_risk_total_cost = high_risk_patient_profile[
    "Total_Encounter_Cost"
].sum()

top_10_cost_share = (
    top_10_cost / high_risk_total_cost
) * 100

print(f"Top 10 high-risk patient cost: ${top_10_cost:,.2f}")
print(f"High-risk total cost: ${high_risk_total_cost:,.2f}")
print(f"Top 10 cost share: {top_10_cost_share:.2f}%")

Top 10 high-risk patient cost: $30,894,364.36
High-risk total cost: $45,124,116.53
Top 10 cost share: 68.47%

In [228]:
# STEP 6.5 — High-Risk Utilization Summary

high_risk_summary = pd.DataFrame({
    "Metric": [
        "High-Risk Patients",
        "High-Risk Patient Share",
        "High-Risk Total Cost",
        "High-Risk Cost Share",
        "High-Risk Patient Responsibility",
        "High-Risk Patient Responsibility Rate",
        "Top 10 High-Risk Cost",
        "Top 10 Cost Share of High-Risk Group",
        "Average Encounters per High-Risk Patient",
        "Average Healthcare Cost per High-Risk Patient",
        "Average Patient Responsibility per High-Risk Patient",
        "Average High-Acuity Rate"
    ],
    "Value": [
        len(high_risk_patients),
        len(high_risk_patients) / len(patient_utilization) * 100,
        high_risk_patients["Total_Encounter_Cost"].sum(),
        high_risk_patients["Total_Encounter_Cost"].sum()
        / patient_utilization["Total_Encounter_Cost"].sum() * 100,
        high_risk_patients["Total_Patient_Responsibility"].sum(),
        high_risk_patients["Total_Patient_Responsibility"].sum()
        / high_risk_patients["Total_Encounter_Cost"].sum() * 100,
        high_risk_patient_profile.head(10)["Total_Encounter_Cost"].sum(),
        high_risk_patient_profile.head(10)["Total_Encounter_Cost"].sum()
        / high_risk_patients["Total_Encounter_Cost"].sum() * 100,
        high_risk_patients["Encounter_Count"].mean(),
        high_risk_patients["Total_Encounter_Cost"].mean(),
        high_risk_patients["Total_Patient_Responsibility"].mean(),
        high_risk_patients["High_Acuity_Rate"].mean()
    ]
})

high_risk_summary

                                                  Metric         Value
0                                     High-Risk Patients         36.00
1                                High-Risk Patient Share          3.70
2                                   High-Risk Total Cost 45,124,116.53
3                                   High-Risk Cost Share         44.45
4                       High-Risk Patient Responsibility 37,856,203.61
5                  High-Risk Patient Responsibility Rate         83.89
6                                  Top 10 High-Risk Cost 30,894,364.36
7                   Top 10 Cost Share of High-Risk Group         68.47
8               Average Encounters per High-Risk Patient        180.75
9          Average Healthcare Cost per High-Risk Patient  1,253,447.68
10  Average Patient Responsibility per High-Risk Patient  1,051,561.21
11                              Average High-Acuity Rate         18.50

In [229]:
# STEP 7.1 — High-risk encounter-type cost analysis

# Get encounter IDs belonging to high-risk patients
high_risk_patient_ids = high_util_high_cost["PATIENT"]

# Filter encounter-level data
high_risk_encounters = encounters_clean[
    encounters_clean["PATIENT"].isin(high_risk_patient_ids)
].copy()

# Analyze encounter class
high_risk_encounter_class = (
    high_risk_encounters
    .groupby("ENCOUNTERCLASS")
    .agg(
        Encounter_Count=("ENCOUNTERCLASS", "size"),
        Total_Cost=("TOTAL_CLAIM_COST", "sum"),
        Patient_Responsibility=("TOTAL_CLAIM_COST", "sum")
    )
    .sort_values("Total_Cost", ascending=False)
)

# Calculate percentages
high_risk_encounter_class["Encounter_Share_Percentage"] = (
    high_risk_encounter_class["Encounter_Count"]
    / high_risk_encounter_class["Encounter_Count"].sum()
    * 100
)

high_risk_encounter_class["Cost_Share_Percentage"] = (
    high_risk_encounter_class["Total_Cost"]
    / high_risk_encounter_class["Total_Cost"].sum()
    * 100
)

high_risk_encounter_class["Average_Cost_Per_Encounter"] = (
    high_risk_encounter_class["Total_Cost"]
    / high_risk_encounter_class["Encounter_Count"]
)

high_risk_encounter_class

                Encounter_Count    Total_Cost  Patient_Responsibility  Encounter_Share_Percentage  Cost_Share_Percentage  Average_Cost_Per_Encounter
ENCOUNTERCLASS
urgentcare                  909 17,782,386.89           17,782,386.89                       13.97                  39.41                   19,562.58
ambulatory                 3657 10,466,022.18           10,466,022.18                       56.20                  23.19                    2,861.91
outpatient                 1087  6,769,495.68            6,769,495.68                       16.71                  15.00                    6,227.69
emergency                   345  4,684,205.82            4,684,205.82                        5.30                  10.38                   13,577.41
inpatient                   377  4,220,883.03            4,220,883.03                        5.79                   9.35                   11,195.98
wellness                    132  1,201,122.93            1,201,122.93                        2.03                   2.66                    9,099.42

In [230]:
# STEP 7.2 — High-risk utilization profile

high_risk_utilization_profile = high_util_high_cost[
    [
        "PATIENT",
        "Encounter_Count",
        "Total_Encounter_Cost",
        "Total_Patient_Responsibility",
        "Inpatient_Encounters",
        "Emergency_Encounters",
        "Outpatient_Encounters",
        "Ambulatory_Encounters",
        "UrgentCare_Encounters",
        "Wellness_Encounters",
        "High_Acuity_Encounters",
        "Emergency_Rate",
        "Inpatient_Rate",
        "High_Acuity_Rate"
    ]
].copy()

high_risk_utilization_profile.head(10)

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters,High_Acuity_Encounters,Emergency_Rate,Inpatient_Rate,High_Acuity_Rate
1,0034fe01-207f-275f-6b4b-821f7b0af044,75,"548,667.37","543,172.81",4,6,33,32,0,0,10,8.00,5.33,13.33
9,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,"1,127,635.83","1,127,635.83",52,16,65,36,0,11,68,8.89,28.89,37.78
67,12f0d3df-7ea9-3005-ea7e-a4c829536a12,73,"331,058.64","41,870.98",49,5,0,19,0,0,54,6.85,67.12,73.97
70,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,"1,030,983.91","976,939.56",0,0,99,1,0,11,0,0.00,0.00,0.00
85,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,"2,437,415.31","2,437,415.31",0,0,77,1304,0,0,0,0.00,0.00,0.00
163,283af64b-5b12-f971-6129-f638491a4a5b,55,"563,662.84","116,659.67",35,2,3,7,0,8,37,3.64,63.64,67.27
174,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,"2,699,823.10","2,699,823.10",0,0,0,0,120,0,0,0.00,0.00,0.00
229,394f3e43-784c-b938-adb6-4b69efd46bbf,63,"567,891.96","544,003.86",1,4,16,42,0,0,5,6.35,1.59,7.94
239,3d17f121-e015-683b-df1e-21e1ddbaab9c,60,"535,232.95","402,161.74",1,7,11,41,0,0,8,11.67,1.67,13.33
240,3de74169-7f67-9304-91d4-757e0f3a14d2,877,"819,279.19","819,279.19",0,49,35,786,0,7,49,5.59,0.00,5.59

In [231]:
# Aggregate encounter types across high-risk patients

high_risk_utilization_by_type = pd.DataFrame({
    "Encounter_Type": [
        "Inpatient",
        "Emergency",
        "Outpatient",
        "Ambulatory",
        "Urgent Care",
        "Wellness"
    ],
    "Encounter_Count": [
        high_util_high_cost["Inpatient_Encounters"].sum(),
        high_util_high_cost["Emergency_Encounters"].sum(),
        high_util_high_cost["Outpatient_Encounters"].sum(),
        high_util_high_cost["Ambulatory_Encounters"].sum(),
        high_util_high_cost["UrgentCare_Encounters"].sum(),
        high_util_high_cost["Wellness_Encounters"].sum()
    ]
})

high_risk_utilization_by_type["Utilization_Share_Percentage"] = (
    high_risk_utilization_by_type["Encounter_Count"]
    / high_risk_utilization_by_type["Encounter_Count"].sum()
    * 100
)

high_risk_utilization_by_type = (
    high_risk_utilization_by_type
    .sort_values("Encounter_Count", ascending=False)
    .reset_index(drop=True)
)

high_risk_utilization_by_type

  Encounter_Type  Encounter_Count  Utilization_Share_Percentage
0     Ambulatory             3657                         56.20
1     Outpatient             1087                         16.71
2    Urgent Care              909                         13.97
3      Inpatient              377                          5.79
4      Emergency              345                          5.30
5       Wellness              132                          2.03

In [232]:
# Check that high-risk encounter counts reconcile
print(
    "Total high-risk encounters:",
    high_risk_utilization_by_type["Encounter_Count"].sum()
)

print(
    "Expected high-risk encounters:",
    high_util_high_cost["Encounter_Count"].sum()
)

Total high-risk encounters: 6507
Expected high-risk encounters: 6507

In [233]:
# Executive summary of high-risk patient burden

high_risk_executive_summary = pd.DataFrame({
    "Metric": [
        "High-Risk Patients",
        "High-Risk Patient Share",
        "High-Risk Healthcare Cost",
        "High-Risk Cost Share",
        "High-Risk Patient Responsibility",
        "Patient Responsibility Rate",
        "Top 10 Cost Share",
        "Average Encounters per High-Risk Patient",
        "Average Healthcare Cost per High-Risk Patient",
        "Average Patient Responsibility per High-Risk Patient",
        "Average High-Acuity Rate"
    ],
    "Value": [
        len(high_util_high_cost),
        len(high_util_high_cost) / len(patient_utilization) * 100,
        high_util_high_cost["Total_Encounter_Cost"].sum(),
        high_util_high_cost["Total_Encounter_Cost"].sum()
            / patient_utilization["Total_Encounter_Cost"].sum() * 100,
        high_util_high_cost["Total_Patient_Responsibility"].sum(),
        high_util_high_cost["Total_Patient_Responsibility"].sum()
            / high_util_high_cost["Total_Encounter_Cost"].sum() * 100,
        top_10_cost_share,
        high_util_high_cost["Encounter_Count"].mean(),
        high_util_high_cost["Total_Encounter_Cost"].mean(),
        high_util_high_cost["Total_Patient_Responsibility"].mean(),
        high_util_high_cost["High_Acuity_Rate"].mean()
    ]
})

high_risk_executive_summary

                                                  Metric         Value
0                                     High-Risk Patients         36.00
1                                High-Risk Patient Share          3.70
2                              High-Risk Healthcare Cost 45,124,116.53
3                                   High-Risk Cost Share         44.45
4                       High-Risk Patient Responsibility 37,856,203.61
5                            Patient Responsibility Rate         83.89
6                                      Top 10 Cost Share         68.47
7               Average Encounters per High-Risk Patient        180.75
8          Average Healthcare Cost per High-Risk Patient  1,253,447.68
9   Average Patient Responsibility per High-Risk Patient  1,051,561.21
10                              Average High-Acuity Rate         18.50

In [234]:
top_10_cost = high_util_high_cost.nlargest(
    10, "Total_Encounter_Cost"
)["Total_Encounter_Cost"].sum()

high_risk_total_cost = high_util_high_cost["Total_Encounter_Cost"].sum()

top_10_cost_share = (
    top_10_cost / high_risk_total_cost * 100
)

top_10_cost_share

np.float64(68.46530577382143)