In [3]:
import pandas as pd

patients = pd.read_csv("../../data/raw/patients.csv")
encounters = pd.read_csv("../../data/raw/encounters.csv")
procedures = pd.read_csv("../../data/raw/procedures.csv")
payers = pd.read_csv("../../data/raw/payers.csv")
organizations = pd.read_csv("../../data/raw/organizations.csv")

In [4]:
procedures.head()

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,REASONCODE,REASONDESCRIPTION
0,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,32c84703-2481-49cd-d571-3899d5820253,265764009,Renal dialysis (procedure),903,NaN,NaN
1,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,d9ec2e44-32e9-9148-179a-1653348cc4e2,c98059da-320a-c0a6-fced-c8815f3e3f39,76601001,Intramuscular injection,2477,NaN,NaN
2,2011-01-04T14:49:55Z,2011-01-04T15:04:55Z,d856d6e6-4c98-e7a2-129b-44076c63d008,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,703423002,Combined chemotherapy and radiation therapy (p...,11620,363406005.0,Malignant tumor of colon
3,2011-01-05T04:02:09Z,2011-01-05T04:17:09Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,17966936-0878-f4db-128b-a43ae10d0878,173160006,Diagnostic fiberoptic bronchoscopy (procedure),9796,162573006.0,Suspected lung cancer (situation)
4,2011-01-05T12:58:36Z,2011-01-05T16:42:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,9de5f0b0-4ba4-ce6f-45fb-b55c202f31a5,265764009,Renal dialysis (procedure),1255,NaN,NaN

In [5]:
patients.head()

,Id,BIRTHDATE,DEATHDATE,PREFIX,FIRST,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,ZIP,LAT,LON
0,5605b66b-e92d-c16c-1b83-b8bf7040d51f,1977-03-19,NaN,Mrs.,Nikita578,Erdman779,NaN,Leannon79,M,white,nonhispanic,F,Wakefield Massachusetts US,510 Little Station Unit 69,Quincy,Massachusetts,Norfolk County,2186.0,42.290937,-70.975503
1,6e5ae27c-8038-7988-e2c0-25a103f01bfa,1940-02-19,NaN,Mr.,Zane918,Hodkiewicz467,NaN,NaN,M,white,nonhispanic,M,Brookline Massachusetts US,747 Conn Throughway,Boston,Massachusetts,Suffolk County,2135.0,42.308831,-71.063162
2,8123d076-0886-9007-e956-d5864aa121a7,1958-06-04,NaN,Mr.,Quinn173,Marquardt819,NaN,NaN,M,white,nonhispanic,M,Gardner Massachusetts US,816 Okuneva Extension Apt 91,Quincy,Massachusetts,Norfolk County,2170.0,42.265177,-70.967085
3,770518e4-6133-648e-60c9-071eb2f0e2ce,1928-12-25,2017-09-29,Mr.,Abel832,Smitham825,NaN,NaN,M,white,hispanic,M,Randolph Massachusetts US,127 Cole Way Unit 95,Boston,Massachusetts,Suffolk County,2118.0,42.334304,-71.066801
4,f96addf5-81b9-0aab-7855-d208d3d352c5,1928-12-25,2014-02-23,Mr.,Edwin773,Labadie908,NaN,NaN,M,white,hispanic,M,Stow Massachusetts US,976 Ziemann Gateway,Boston,Massachusetts,Suffolk County,2125.0,42.346771,-71.058813

In [6]:
procedures.head()

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,REASONCODE,REASONDESCRIPTION
0,2011-01-02T09:26:36Z,2011-01-02T12:58:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,32c84703-2481-49cd-d571-3899d5820253,265764009,Renal dialysis (procedure),903,NaN,NaN
1,2011-01-03T05:44:39Z,2011-01-03T06:01:42Z,d9ec2e44-32e9-9148-179a-1653348cc4e2,c98059da-320a-c0a6-fced-c8815f3e3f39,76601001,Intramuscular injection,2477,NaN,NaN
2,2011-01-04T14:49:55Z,2011-01-04T15:04:55Z,d856d6e6-4c98-e7a2-129b-44076c63d008,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,703423002,Combined chemotherapy and radiation therapy (p...,11620,363406005.0,Malignant tumor of colon
3,2011-01-05T04:02:09Z,2011-01-05T04:17:09Z,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,17966936-0878-f4db-128b-a43ae10d0878,173160006,Diagnostic fiberoptic bronchoscopy (procedure),9796,162573006.0,Suspected lung cancer (situation)
4,2011-01-05T12:58:36Z,2011-01-05T16:42:36Z,3de74169-7f67-9304-91d4-757e0f3a14d2,9de5f0b0-4ba4-ce6f-45fb-b55c202f31a5,265764009,Renal dialysis (procedure),1255,NaN,NaN

In [7]:
payers.head()

,Id,NAME,ADDRESS,CITY,STATE_HEADQUARTERED,ZIP,PHONE
0,b3221cfc-24fb-339e-823d-bc4136cbc4ed,Dual Eligible,7500 Security Blvd,Baltimore,MD,21244.0,1-877-267-2323
1,7caa7254-5050-3b5e-9eae-bd5ea30e809c,Medicare,7500 Security Blvd,Baltimore,MD,21244.0,1-800-633-4227
2,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,Medicaid,7500 Security Blvd,Baltimore,MD,21244.0,1-877-267-2323
3,d47b3510-2895-3b70-9897-342d681c769d,Humana,500 West Main St,Louisville,KY,40018.0,1-844-330-7799
4,6e2f1a2d-27bd-3701-8d08-dae202c58632,Blue Cross Blue Shield,Michigan Plaza,Chicago,IL,60007.0,1-800-262-2583

In [8]:
organizations.head()

,Id,NAME,ADDRESS,CITY,STATE,ZIP,LAT,LON
0,d78e84ec-30aa-3bba-a33a-f29a3a454662,MASSACHUSETTS GENERAL HOSPITAL,55 FRUIT STREET,BOSTON,MA,2114,42.362813,-71.069187

In [9]:
patients.info()

<class 'pandas.DataFrame'>
RangeIndex: 974 entries, 0 to 973
Data columns (total 20 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Id          974 non-null    str
 1   BIRTHDATE   974 non-null    str
 2   DEATHDATE   154 non-null    str
 3   PREFIX      974 non-null    str
 4   FIRST       974 non-null    str
 5   LAST        974 non-null    str
 6   SUFFIX      21 non-null     str
 7   MAIDEN      386 non-null    str
 8   MARITAL     973 non-null    str
 9   RACE        974 non-null    str
 10  ETHNICITY   974 non-null    str
 11  GENDER      974 non-null    str
 12  BIRTHPLACE  974 non-null    str
 13  ADDRESS     974 non-null    str
 14  CITY        974 non-null    str
 15  STATE       974 non-null    str
 16  COUNTY      974 non-null    str
 17  ZIP         832 non-null    float64
 18  LAT         974 non-null    float64
 19  LON         974 non-null    float64
dtypes: float64(3), str(17)
memory usage: 152.3 KB

In [10]:
tables = {
    "patients": patients,
    "encounters": encounters,
    "procedures": procedures,
    "payers": payers,
    "organizations": organizations
}

for name, df in tables.items():
    print(f"{name}: {df.shape}")

patients: (974, 20)
encounters: (27891, 14)
procedures: (47701, 9)
payers: (10, 7)
organizations: (1, 8)

In [11]:
for name, df in tables.items():
    print(f"\n===== {name.upper()} =====")
    print(df.columns.tolist())

===== PATIENTS =====
['Id', 'BIRTHDATE', 'DEATHDATE', 'PREFIX', 'FIRST', 'LAST', 'SUFFIX', 'MAIDEN', 'MARITAL', 'RACE', 'ETHNICITY', 'GENDER', 'BIRTHPLACE', 'ADDRESS', 'CITY', 'STATE', 'COUNTY', 'ZIP', 'LAT', 'LON']

===== ENCOUNTERS =====
['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION']

===== PROCEDURES =====
['START', 'STOP', 'PATIENT', 'ENCOUNTER', 'CODE', 'DESCRIPTION', 'BASE_COST', 'REASONCODE', 'REASONDESCRIPTION']

===== PAYERS =====
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE_HEADQUARTERED', 'ZIP', 'PHONE']

===== ORGANIZATIONS =====
['Id', 'NAME', 'ADDRESS', 'CITY', 'STATE', 'ZIP', 'LAT', 'LON']

In [12]:
for name, df in tables.items():
    print(f"\n===== {name.upper()} =====")
    print(df.dtypes)

===== PATIENTS =====
Id                str
BIRTHDATE         str
DEATHDATE         str
PREFIX            str
FIRST             str
LAST              str
SUFFIX            str
MAIDEN            str
MARITAL           str
RACE              str
ETHNICITY         str
GENDER            str
BIRTHPLACE        str
ADDRESS           str
CITY              str
STATE             str
COUNTY            str
ZIP           float64
LAT           float64
LON           float64
dtype: object

===== ENCOUNTERS =====
Id                         str
START                      str
STOP                       str
PATIENT                    str
ORGANIZATION               str
PAYER                      str
ENCOUNTERCLASS             str
CODE                     int64
DESCRIPTION                str
BASE_ENCOUNTER_COST    float64
TOTAL_CLAIM_COST       float64
PAYER_COVERAGE         float64
REASONCODE             float64
REASONDESCRIPTION          str
dtype: object

===== PROCEDURES =====
START                    str
STOP                     str
PATIENT                  str
ENCOUNTER                str
CODE                   int64
DESCRIPTION              str
BASE_COST              int64
REASONCODE           float64
REASONDESCRIPTION        str
dtype: object

===== PAYERS =====
Id                         str
NAME                       str
ADDRESS                    str
CITY                       str
STATE_HEADQUARTERED        str
ZIP                    float64
PHONE                      str
dtype: object

===== ORGANIZATIONS =====
Id             str
NAME           str
ADDRESS        str
CITY           str
STATE          str
ZIP          int64
LAT        float64
LON        float64
dtype: object

In [13]:
for name, df in tables.items():
    print(f"\n===== {name.upper()} =====")
    print(df.isnull().sum())

===== PATIENTS =====
Id              0
BIRTHDATE       0
DEATHDATE     820
PREFIX          0
FIRST           0
LAST            0
SUFFIX        953
MAIDEN        588
MARITAL         1
RACE            0
ETHNICITY       0
GENDER          0
BIRTHPLACE      0
ADDRESS         0
CITY            0
STATE           0
COUNTY          0
ZIP           142
LAT             0
LON             0
dtype: int64

===== ENCOUNTERS =====
Id                         0
START                      0
STOP                       0
PATIENT                    0
ORGANIZATION               0
PAYER                      0
ENCOUNTERCLASS             0
CODE                       0
DESCRIPTION                0
BASE_ENCOUNTER_COST        0
TOTAL_CLAIM_COST           0
PAYER_COVERAGE             0
REASONCODE             19541
REASONDESCRIPTION      19541
dtype: int64

===== PROCEDURES =====
START                    0
STOP                     0
PATIENT                  0
ENCOUNTER                0
CODE                     0
DESCRIPTION              0
BASE_COST                0
REASONCODE           36945
REASONDESCRIPTION    36945
dtype: int64

===== PAYERS =====
Id                     0
NAME                   0
ADDRESS                1
CITY                   1
STATE_HEADQUARTERED    1
ZIP                    1
PHONE                  1
dtype: int64

===== ORGANIZATIONS =====
Id         0
NAME       0
ADDRESS    0
CITY       0
STATE      0
ZIP        0
LAT        0
LON        0
dtype: int64

In [14]:
for name, df in tables.items():

    missing = (
        df.isnull()
        .sum()
        .to_frame("Missing_Count")
    )

    missing["Missing_Percentage"] = (
        missing["Missing_Count"] / len(df) * 100
    )

    print(f"\n===== {name.upper()} =====")
    print(missing.sort_values(
        "Missing_Percentage",
        ascending=False
    ))

===== PATIENTS =====
            Missing_Count  Missing_Percentage
SUFFIX                953           97.843943
DEATHDATE             820           84.188912
MAIDEN                588           60.369610
ZIP                   142           14.579055
MARITAL                 1            0.102669
PREFIX                  0            0.000000
Id                      0            0.000000
BIRTHDATE               0            0.000000
FIRST                   0            0.000000
RACE                    0            0.000000
ETHNICITY               0            0.000000
LAST                    0            0.000000
GENDER                  0            0.000000
BIRTHPLACE              0            0.000000
CITY                    0            0.000000
ADDRESS                 0            0.000000
STATE                   0            0.000000
COUNTY                  0            0.000000
LAT                     0            0.000000
LON                     0            0.000000

===== ENCOUNTERS =====
                     Missing_Count  Missing_Percentage
REASONDESCRIPTION            19541           70.062027
REASONCODE                   19541           70.062027
STOP                             0            0.000000
PATIENT                          0            0.000000
Id                               0            0.000000
START                            0            0.000000
PAYER                            0            0.000000
ORGANIZATION                     0            0.000000
ENCOUNTERCLASS                   0            0.000000
CODE                             0            0.000000
BASE_ENCOUNTER_COST              0            0.000000
DESCRIPTION                      0            0.000000
PAYER_COVERAGE                   0            0.000000
TOTAL_CLAIM_COST                 0            0.000000

===== PROCEDURES =====
                   Missing_Count  Missing_Percentage
REASONCODE                 36945           77.451206
REASONDESCRIPTION          36945           77.451206
START                          0            0.000000
STOP                           0            0.000000
PATIENT                        0            0.000000
CODE                           0            0.000000
ENCOUNTER                      0            0.000000
BASE_COST                      0            0.000000
DESCRIPTION                    0            0.000000

===== PAYERS =====
                     Missing_Count  Missing_Percentage
ADDRESS                          1                10.0
STATE_HEADQUARTERED              1                10.0
CITY                             1                10.0
ZIP                              1                10.0
PHONE                            1                10.0
NAME                             0                 0.0
Id                               0                 0.0

===== ORGANIZATIONS =====
         Missing_Count  Missing_Percentage
Id                   0                 0.0
NAME                 0                 0.0
ADDRESS              0                 0.0
CITY                 0                 0.0
STATE                0                 0.0
ZIP                  0                 0.0
LAT                  0                 0.0
LON                  0                 0.0

In [15]:
for name, df in tables.items():

    print(f"\n{name.upper()}")

    for column in df.columns:

        unique = df[column].nunique()
        rows = len(df)

        if unique == rows:
            print(f"{column}: Potential Primary Key")

PATIENTS
Id: Potential Primary Key
ADDRESS: Potential Primary Key
LAT: Potential Primary Key
LON: Potential Primary Key

ENCOUNTERS
Id: Potential Primary Key

PROCEDURES

PAYERS
Id: Potential Primary Key
NAME: Potential Primary Key

ORGANIZATIONS
Id: Potential Primary Key
NAME: Potential Primary Key
ADDRESS: Potential Primary Key
CITY: Potential Primary Key
STATE: Potential Primary Key
ZIP: Potential Primary Key
LAT: Potential Primary Key
LON: Potential Primary Key

Validate Patient → Encounter

In [16]:
invalid_patients = encounters.loc[
    ~encounters["PATIENT"].isin(patients["Id"]),
    "PATIENT"
]

print("Invalid patient references:", invalid_patients.nunique())
print("Invalid encounter rows:", len(invalid_patients))

Invalid patient references: 0
Invalid encounter rows: 0

In [17]:
print("Invalid encounter rows:", len(invalid_patients))

Invalid encounter rows: 0

Validate Encounter → Procedure

In [18]:
invalid_encounters = procedures.loc[
    ~procedures["ENCOUNTER"].isin(encounters["Id"]),
    "ENCOUNTER"
]

print("Invalid encounter references:", invalid_encounters.nunique())
print("Invalid procedure rows:", len(invalid_encounters))

Invalid encounter references: 0
Invalid procedure rows: 0

Validate Encounter → Payer

In [19]:
invalid_payers = encounters.loc[
    ~encounters["PAYER"].isin(payers["Id"]),
    "PAYER"
]

print("Invalid payer references:", invalid_payers.nunique())
print("Invalid encounter rows:", len(invalid_payers))

Invalid payer references: 0
Invalid encounter rows: 0

Validate Encounter → Organization

In [20]:
invalid_organizations = encounters.loc[
    ~encounters["ORGANIZATION"].isin(organizations["Id"]),
    "ORGANIZATION"
]

print("Invalid organization references:", invalid_organizations.nunique())
print("Invalid encounter rows:", len(invalid_organizations))

Invalid organization references: 0
Invalid encounter rows: 0

Validate Procedure → Patient

In [21]:
invalid_procedure_patients = procedures.loc[
    ~procedures["PATIENT"].isin(patients["Id"]),
    "PATIENT"
]

print(
    "Invalid procedure patient references:",
    invalid_procedure_patients.nunique()
)

print(
    "Invalid procedure rows:",
    len(invalid_procedure_patients)
)

Invalid procedure patient references: 0
Invalid procedure rows: 0

Test the Direct Patient/Encounter Consistency

In [22]:
procedure_check = procedures.merge(
    encounters[["Id", "PATIENT"]],
    left_on="ENCOUNTER",
    right_on="Id",
    how="left",
    suffixes=("_procedure", "_encounter")
)

mismatches = procedure_check[
    procedure_check["PATIENT_procedure"] !=
    procedure_check["PATIENT_encounter"]
]

print("Patient/encounter mismatches:", len(mismatches))

Patient/encounter mismatches: 0

Check Whether Procedures Have Duplicate Records

In [23]:
print("Total procedure rows:", len(procedures))
print(
    "Exact duplicate rows:",
    procedures.duplicated().sum()
)

Total procedure rows: 47701
Exact duplicate rows: 0

In [24]:
procedure_key = [
    "PATIENT",
    "ENCOUNTER",
    "START",
    "STOP",
    "CODE"
]

print(
    "Duplicate logical procedure records:",
    procedures.duplicated(
        subset=procedure_key
    ).sum()
)

Duplicate logical procedure records: 0

Check Encounter IDs

In [25]:
print("Total encounters:", len(encounters))

print(
    "Unique encounter IDs:",
    encounters["Id"].nunique()
)

print(
    "Duplicate encounter IDs:",
    encounters["Id"].duplicated().sum()
)

Total encounters: 27891
Unique encounter IDs: 27891
Duplicate encounter IDs: 0

encounters.Id = Primary Key

Check Patient IDs

In [26]:
print("Total patients:", len(patients))

print(
    "Unique patient IDs:",
    patients["Id"].nunique()
)

print(
    "Duplicate patient IDs:",
    patients["Id"].duplicated().sum()
)

Total patients: 974
Unique patient IDs: 974
Duplicate patient IDs: 0

Check Payer IDs

In [27]:
print("Total payers:", len(payers))

print(
    "Unique payer IDs:",
    payers["Id"].nunique()
)

print(
    "Duplicate payer IDs:",
    payers["Id"].duplicated().sum()
)

Total payers: 10
Unique payer IDs: 10
Duplicate payer IDs: 0

Check Organization IDs

In [28]:
print("Total organizations:", len(organizations))

print(
    "Unique organization IDs:",
    organizations["Id"].nunique()
)

print(
    "Duplicate organization IDs:",
    organizations["Id"].duplicated().sum()
)

Total organizations: 1
Unique organization IDs: 1
Duplicate organization IDs: 0

Checking For Null Foreign Keys

In [29]:
foreign_key_columns = {
    "encounters.PATIENT": encounters["PATIENT"],
    "encounters.PAYER": encounters["PAYER"],
    "encounters.ORGANIZATION": encounters["ORGANIZATION"],
    "procedures.PATIENT": procedures["PATIENT"],
    "procedures.ENCOUNTER": procedures["ENCOUNTER"]
}

for name, series in foreign_key_columns.items():
    print(
        f"{name}: "
        f"{series.isna().sum()} nulls "
        f"({series.isna().mean() * 100:.2f}%)"
    )

encounters.PATIENT: 0 nulls (0.00%)
encounters.PAYER: 0 nulls (0.00%)
encounters.ORGANIZATION: 0 nulls (0.00%)
procedures.PATIENT: 0 nulls (0.00%)
procedures.ENCOUNTER: 0 nulls (0.00%)

In [30]:
invalid_patients = encounters.loc[
    ~encounters["PATIENT"].isin(patients["Id"]),
    "PATIENT"
]

print("Invalid patient references:", invalid_patients.nunique())
print("Invalid encounter rows:", len(invalid_patients))

Invalid patient references: 0
Invalid encounter rows: 0

In [31]:
invalid_encounters = procedures.loc[
    ~procedures["ENCOUNTER"].isin(encounters["Id"]),
    "ENCOUNTER"
]

print("Invalid encounter references:", invalid_encounters.nunique())
print("Invalid procedure rows:", len(invalid_encounters))

Invalid encounter references: 0
Invalid procedure rows: 0

In [32]:
invalid_payers = encounters.loc[
    ~encounters["PAYER"].isin(payers["Id"]),
    "PAYER"
]

print("Invalid payer references:", invalid_payers.nunique())
print("Invalid encounter rows:", len(invalid_payers))

Invalid payer references: 0
Invalid encounter rows: 0

In [33]:
invalid_organizations = encounters.loc[
    ~encounters["ORGANIZATION"].isin(organizations["Id"]),
    "ORGANIZATION"
]

print("Invalid organization references:", invalid_organizations.nunique())
print("Invalid encounter rows:", len(invalid_organizations))

Invalid organization references: 0
Invalid encounter rows: 0

In [34]:
procedure_check = procedures.merge(
    encounters[["Id", "PATIENT"]],
    left_on="ENCOUNTER",
    right_on="Id",
    how="left",
    suffixes=("_procedure", "_encounter")
)

mismatches = procedure_check[
    procedure_check["PATIENT_procedure"] !=
    procedure_check["PATIENT_encounter"]
]

print("Patient/encounter mismatches:", len(mismatches))

Patient/encounter mismatches: 0

In [35]:
print("Total procedure rows:", len(procedures))
print("Exact duplicate rows:", procedures.duplicated().sum())

procedure_key = [
    "PATIENT",
    "ENCOUNTER",
    "START",
    "STOP",
    "CODE"
]

print(
    "Duplicate logical procedure records:",
    procedures.duplicated(subset=procedure_key).sum()
)

Total procedure rows: 47701
Exact duplicate rows: 0
Duplicate logical procedure records: 0

In [36]:
foreign_key_columns = {
    "encounters.PATIENT": encounters["PATIENT"],
    "encounters.PAYER": encounters["PAYER"],
    "encounters.ORGANIZATION": encounters["ORGANIZATION"],
    "procedures.PATIENT": procedures["PATIENT"],
    "procedures.ENCOUNTER": procedures["ENCOUNTER"]
}

for name, series in foreign_key_columns.items():
    print(
        f"{name}: "
        f"{series.isna().sum()} nulls "
        f"({series.isna().mean() * 100:.2f}%)"
    )

encounters.PATIENT: 0 nulls (0.00%)
encounters.PAYER: 0 nulls (0.00%)
encounters.ORGANIZATION: 0 nulls (0.00%)
procedures.PATIENT: 0 nulls (0.00%)
procedures.ENCOUNTER: 0 nulls (0.00%)

In [37]:
for name, df in tables.items():

    print(f"\n===== {name.upper()} =====")

    dictionary = pd.DataFrame({
        "Column": df.columns,
        "Data_Type": df.dtypes.astype(str).values,
        "Null_Count": df.isnull().sum().values,
        "Null_Percentage": (
            df.isnull().mean() * 100
        ).round(2).values,
        "Unique_Values": [
            df[col].nunique(dropna=True)
            for col in df.columns
        ]
    })

    display(dictionary)

===== PATIENTS =====

        Column Data_Type  Null_Count  Null_Percentage  Unique_Values
0           Id       str           0             0.00            974
1    BIRTHDATE       str           0             0.00            880
2    DEATHDATE       str         820            84.19            148
3       PREFIX       str           0             0.00              3
4        FIRST       str           0             0.00            842
5         LAST       str           0             0.00            498
6       SUFFIX       str         953            97.84              3
7       MAIDEN       str         588            60.37            279
8      MARITAL       str           1             0.10              2
9         RACE       str           0             0.00              6
10   ETHNICITY       str           0             0.00              2
11      GENDER       str           0             0.00              2
12  BIRTHPLACE       str           0             0.00            297
13     ADDRESS       str           0             0.00            974
14        CITY       str           0             0.00             29
15       STATE       str           0             0.00              1
16      COUNTY       str           0             0.00              5
17         ZIP   float64         142            14.58             70
18         LAT   float64           0             0.00            974
19         LON   float64           0             0.00            974

===== ENCOUNTERS =====

                 Column Data_Type  Null_Count  Null_Percentage  Unique_Values
0                    Id       str           0             0.00          27891
1                 START       str           0             0.00          27541
2                  STOP       str           0             0.00          27765
3               PATIENT       str           0             0.00            974
4          ORGANIZATION       str           0             0.00              1
5                 PAYER       str           0             0.00             10
6        ENCOUNTERCLASS       str           0             0.00              6
7                  CODE     int64           0             0.00             45
8           DESCRIPTION       str           0             0.00             53
9   BASE_ENCOUNTER_COST   float64           0             0.00              5
10     TOTAL_CLAIM_COST   float64           0             0.00          13529
11       PAYER_COVERAGE   float64           0             0.00           5606
12           REASONCODE   float64       19541            70.06             73
13    REASONDESCRIPTION       str       19541            70.06             73

===== PROCEDURES =====

              Column Data_Type  Null_Count  Null_Percentage  Unique_Values
0              START       str           0             0.00          39251
1               STOP       str           0             0.00          42263
2            PATIENT       str           0             0.00            793
3          ENCOUNTER       str           0             0.00          14670
4               CODE     int64           0             0.00            157
5        DESCRIPTION       str           0             0.00            163
6          BASE_COST     int64           0             0.00           8268
7         REASONCODE   float64       36945            77.45             46
8  REASONDESCRIPTION       str       36945            77.45             46

===== PAYERS =====

                Column Data_Type  Null_Count  Null_Percentage  Unique_Values
0                   Id       str           0              0.0             10
1                 NAME       str           0              0.0             10
2              ADDRESS       str           1             10.0              7
3                 CITY       str           1             10.0              7
4  STATE_HEADQUARTERED       str           1             10.0              6
5                  ZIP   float64           1             10.0              7
6                PHONE       str           1             10.0              8

===== ORGANIZATIONS =====

    Column Data_Type  Null_Count  Null_Percentage  Unique_Values
0       Id       str           0              0.0              1
1     NAME       str           0              0.0              1
2  ADDRESS       str           0              0.0              1
3     CITY       str           0              0.0              1
4    STATE       str           0              0.0              1
5      ZIP     int64           0              0.0              1
6      LAT   float64           0              0.0              1
7      LON   float64           0              0.0              1

Final PK Verification

In [38]:
primary_key_candidates = {
    "patients": "Id",
    "encounters": "Id",
    "payers": "Id",
    "organizations": "Id"
}

for table_name, column in primary_key_candidates.items():

    df = tables[table_name]

    print(f"\n{table_name}.{column}")

    print("Total rows:", len(df))
    print("Unique values:", df[column].nunique())
    print("Null values:", df[column].isna().sum())
    print("Duplicate values:", df[column].duplicated().sum())
    print("Is unique:", df[column].is_unique)

patients.Id
Total rows: 974
Unique values: 974
Null values: 0
Duplicate values: 0
Is unique: True

encounters.Id
Total rows: 27891
Unique values: 27891
Null values: 0
Duplicate values: 0
Is unique: True

payers.Id
Total rows: 10
Unique values: 10
Null values: 0
Duplicate values: 0
Is unique: True

organizations.Id
Total rows: 1
Unique values: 1
Null values: 0
Duplicate values: 0
Is unique: True

In [39]:
procedure_grain = procedures.groupby(
    ["PATIENT", "ENCOUNTER", "START", "STOP", "CODE"]
).size()

print(procedure_grain.describe())

count    47701.0
mean         1.0
std          0.0
min          1.0
25%          1.0
50%          1.0
75%          1.0
max          1.0
dtype: float64

In [40]:
print(
    "Maximum records sharing the same logical key:",
    procedure_grain.max()
)

Maximum records sharing the same logical key: 1

The procedures dataset does not contain an explicit primary-key field. A composite business key consisting of patient, encounter, timestamps, and procedure code was assessed for uniqueness and produced no duplicate records.

In [41]:
for name, df in tables.items():

    print(f"\n{'=' * 60}")
    print(name.upper())
    print(f"{'=' * 60}")

    profile = pd.DataFrame({
        "Data_Type": df.dtypes.astype(str),
        "Null_Count": df.isnull().sum(),
        "Null_Percentage": (
            df.isnull().mean() * 100
        ).round(2),
        "Unique_Values": [
            df[col].nunique(dropna=True)
            for col in df.columns
        ]
    })

    print(profile.to_string())

============================================================
PATIENTS
============================================================
           Data_Type  Null_Count  Null_Percentage  Unique_Values
Id               str           0             0.00            974
BIRTHDATE        str           0             0.00            880
DEATHDATE        str         820            84.19            148
PREFIX           str           0             0.00              3
FIRST            str           0             0.00            842
LAST             str           0             0.00            498
SUFFIX           str         953            97.84              3
MAIDEN           str         588            60.37            279
MARITAL          str           1             0.10              2
RACE             str           0             0.00              6
ETHNICITY        str           0             0.00              2
GENDER           str           0             0.00              2
BIRTHPLACE       str           0             0.00            297
ADDRESS          str           0             0.00            974
CITY             str           0             0.00             29
STATE            str           0             0.00              1
COUNTY           str           0             0.00              5
ZIP          float64         142            14.58             70
LAT          float64           0             0.00            974
LON          float64           0             0.00            974

============================================================
ENCOUNTERS
============================================================
                    Data_Type  Null_Count  Null_Percentage  Unique_Values
Id                        str           0             0.00          27891
START                     str           0             0.00          27541
STOP                      str           0             0.00          27765
PATIENT                   str           0             0.00            974
ORGANIZATION              str           0             0.00              1
PAYER                     str           0             0.00             10
ENCOUNTERCLASS            str           0             0.00              6
CODE                    int64           0             0.00             45
DESCRIPTION               str           0             0.00             53
BASE_ENCOUNTER_COST   float64           0             0.00              5
TOTAL_CLAIM_COST      float64           0             0.00          13529
PAYER_COVERAGE        float64           0             0.00           5606
REASONCODE            float64       19541            70.06             73
REASONDESCRIPTION         str       19541            70.06             73

============================================================
PROCEDURES
============================================================
                  Data_Type  Null_Count  Null_Percentage  Unique_Values
START                   str           0             0.00          39251
STOP                    str           0             0.00          42263
PATIENT                 str           0             0.00            793
ENCOUNTER               str           0             0.00          14670
CODE                  int64           0             0.00            157
DESCRIPTION             str           0             0.00            163
BASE_COST             int64           0             0.00           8268
REASONCODE          float64       36945            77.45             46
REASONDESCRIPTION       str       36945            77.45             46

============================================================
PAYERS
============================================================
                    Data_Type  Null_Count  Null_Percentage  Unique_Values
Id                        str           0              0.0             10
NAME                      str           0              0.0             10
ADDRESS                   str           1             10.0              7
CITY                      str           1             10.0              7
STATE_HEADQUARTERED       str           1             10.0              6
ZIP                   float64           1             10.0              7
PHONE                     str           1             10.0              8

============================================================
ORGANIZATIONS
============================================================
        Data_Type  Null_Count  Null_Percentage  Unique_Values
Id            str           0              0.0              1
NAME          str           0              0.0              1
ADDRESS       str           0              0.0              1
CITY          str           0              0.0              1
STATE         str           0              0.0              1
ZIP         int64           0              0.0              1
LAT       float64           0              0.0              1
LON       float64           0              0.0              1

In [42]:
date_columns = {
    "patients": ["BIRTHDATE", "DEATHDATE"],
    "encounters": ["START", "STOP"],
    "procedures": ["START", "STOP"]
}

for table_name, columns in date_columns.items():

    print(f"\n===== {table_name.upper()} =====")

    for column in columns:
        print(
            f"{column}: "
            f"{tables[table_name][column].dtype}"
        )

===== PATIENTS =====
BIRTHDATE: str
DEATHDATE: str

===== ENCOUNTERS =====
START: str
STOP: str

===== PROCEDURES =====
START: str
STOP: str

In [43]:
# ============================================================
# STAGE 3 — DATA CLEANING & PREPARATION
# STEP 3.1 — CREATE CLEANING WORKING COPIES
# ============================================================

# Create independent working copies of the raw datasets
patients_clean = patients.copy()
encounters_clean = encounters.copy()
procedures_clean = procedures.copy()
payers_clean = payers.copy()
organizations_clean = organizations.copy()

# Store cleaned working tables in a dictionary
clean_tables = {
    "patients": patients_clean,
    "encounters": encounters_clean,
    "procedures": procedures_clean,
    "payers": payers_clean,
    "organizations": organizations_clean
}

print("Cleaning working copies created successfully.")

Cleaning working copies created successfully.

In [44]:
clean_tables = {
    "patients": patients_clean,
    "encounters": encounters_clean,
    "procedures": procedures_clean,
    "payers": payers_clean,
    "organizations": organizations_clean
}

In [45]:
for name, df in clean_tables.items():
    print(f"{name}_clean: {df.shape}")

patients_clean: (974, 20)
encounters_clean: (27891, 14)
procedures_clean: (47701, 9)
payers_clean: (10, 7)
organizations_clean: (1, 8)

In [46]:
print(
    "Raw patients:",
    patients.shape
)

print(
    "Clean patients:",
    patients_clean.shape
)

Raw patients: (974, 20)
Clean patients: (974, 20)

In [47]:
print("Raw BIRTHDATE type:", patients["BIRTHDATE"].dtype)
print("Clean BIRTHDATE type:", patients_clean["BIRTHDATE"].dtype)

Raw BIRTHDATE type: str
Clean BIRTHDATE type: str

In [48]:
# ============================================================
# STEP 3.2.1 — CONVERT PATIENT DATE COLUMNS
# ============================================================

patients_clean["BIRTHDATE"] = pd.to_datetime(
    patients_clean["BIRTHDATE"],
    errors="coerce"
)

patients_clean["DEATHDATE"] = pd.to_datetime(
    patients_clean["DEATHDATE"],
    errors="coerce"
)

print("Patient date conversion completed.")

Patient date conversion completed.

In [49]:
# ============================================================
# STEP 3.2.2 — CONVERT ENCOUNTER DATETIME COLUMNS
# ============================================================

encounters_clean["START"] = pd.to_datetime(
    encounters_clean["START"],
    errors="coerce",
    utc=True
)

encounters_clean["STOP"] = pd.to_datetime(
    encounters_clean["STOP"],
    errors="coerce",
    utc=True
)

print("Encounter datetime conversion completed.")

Encounter datetime conversion completed.

In [50]:
# ============================================================
# STEP 3.2.3 — CONVERT PROCEDURE DATETIME COLUMNS
# ============================================================

procedures_clean["START"] = pd.to_datetime(
    procedures_clean["START"],
    errors="coerce",
    utc=True
)

procedures_clean["STOP"] = pd.to_datetime(
    procedures_clean["STOP"],
    errors="coerce",
    utc=True
)

print("Procedure datetime conversion completed.")

Procedure datetime conversion completed.

In [51]:
# ============================================================
# STEP 3.2.4 — VERIFY DATE TYPES
# ============================================================

print("PATIENTS")
print("BIRTHDATE:", patients_clean["BIRTHDATE"].dtype)
print("DEATHDATE:", patients_clean["DEATHDATE"].dtype)

print("\nENCOUNTERS")
print("START:", encounters_clean["START"].dtype)
print("STOP:", encounters_clean["STOP"].dtype)

print("\nPROCEDURES")
print("START:", procedures_clean["START"].dtype)
print("STOP:", procedures_clean["STOP"].dtype)

PATIENTS
BIRTHDATE: datetime64[us]
DEATHDATE: datetime64[us]

ENCOUNTERS
START: datetime64[us, UTC]
STOP: datetime64[us, UTC]

PROCEDURES
START: datetime64[us, UTC]
STOP: datetime64[us, UTC]

In [52]:
# ============================================================
# STEP 3.2.5 — CHECK FOR INVALID DATE CONVERSIONS
# ============================================================

date_columns = {
    "patients": ["BIRTHDATE", "DEATHDATE"],
    "encounters": ["START", "STOP"],
    "procedures": ["START", "STOP"]
}

for table_name, columns in date_columns.items():

    print(f"\n===== {table_name.upper()} =====")

    df = clean_tables[table_name]

    for column in columns:
        print(
            f"{column}: "
            f"{df[column].isna().sum()} missing"
        )

===== PATIENTS =====
BIRTHDATE: 0 missing
DEATHDATE: 820 missing

===== ENCOUNTERS =====
START: 0 missing
STOP: 0 missing

===== PROCEDURES =====
START: 0 missing
STOP: 0 missing

In [53]:
# ============================================================
# STEP 3.2.6 — BEFORE vs AFTER DATE VALIDATION
# ============================================================

date_comparison = {
    "patients.BIRTHDATE": (
        patients["BIRTHDATE"].isna().sum(),
        patients_clean["BIRTHDATE"].isna().sum()
    ),

    "patients.DEATHDATE": (
        patients["DEATHDATE"].isna().sum(),
        patients_clean["DEATHDATE"].isna().sum()
    ),

    "encounters.START": (
        encounters["START"].isna().sum(),
        encounters_clean["START"].isna().sum()
    ),

    "encounters.STOP": (
        encounters["STOP"].isna().sum(),
        encounters_clean["STOP"].isna().sum()
    ),

    "procedures.START": (
        procedures["START"].isna().sum(),
        procedures_clean["START"].isna().sum()
    ),

    "procedures.STOP": (
        procedures["STOP"].isna().sum(),
        procedures_clean["STOP"].isna().sum()
    )
}

for column, (before, after) in date_comparison.items():

    print(
        f"{column}: "
        f"Before = {before}, "
        f"After = {after}"
    )

patients.BIRTHDATE: Before = 0, After = 0
patients.DEATHDATE: Before = 820, After = 820
encounters.START: Before = 0, After = 0
encounters.STOP: Before = 0, After = 0
procedures.START: Before = 0, After = 0
procedures.STOP: Before = 0, After = 0

In [54]:
patients_clean[
    ["Id", "BIRTHDATE", "DEATHDATE"]
].head(10)

                                     Id  BIRTHDATE  DEATHDATE
0  5605b66b-e92d-c16c-1b83-b8bf7040d51f 1977-03-19        NaT
1  6e5ae27c-8038-7988-e2c0-25a103f01bfa 1940-02-19        NaT
2  8123d076-0886-9007-e956-d5864aa121a7 1958-06-04        NaT
3  770518e4-6133-648e-60c9-071eb2f0e2ce 1928-12-25 2017-09-29
4  f96addf5-81b9-0aab-7855-d208d3d352c5 1928-12-25 2014-02-23
5  8e9650d1-788a-78f9-4a28-d08f7f95354a 1928-12-25        NaT
6  183df435-4190-060e-8f8e-bf63c572b266 1957-11-08        NaT
7  720560d4-51da-c38c-ee90-c15935278df1 1972-06-27        NaT
8  217851b0-5f47-d376-18b9-0fe4ba77207e 1954-03-06        NaT
9  ff331e5c-ab16-e218-f39a-63e11de1ed75 1927-07-10        NaT

In [55]:
encounters_clean[
    ["Id", "START", "STOP"]
].head(10)

,Id,START,STOP
0,32c84703-2481-49cd-d571-3899d5820253,2011-01-02 09:26:36+00:00,2011-01-02 12:58:36+00:00
1,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03 05:44:39+00:00,2011-01-03 06:01:42+00:00
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,2011-01-03 14:32:11+00:00,2011-01-03 14:47:11+00:00
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,2011-01-03 16:24:45+00:00,2011-01-03 16:39:45+00:00
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03 17:36:53+00:00,2011-01-03 17:51:53+00:00
5,c4923a74-3e40-8b0c-cf73-05b9c0390621,2011-01-03 19:08:16+00:00,2011-01-03 19:23:16+00:00
6,c140ed81-040e-8319-e860-f72b4738ed22,2011-01-03 22:39:50+00:00,2011-01-03 22:54:50+00:00
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04 14:49:55+00:00,2011-01-04 15:04:55+00:00
8,16bdc066-886f-34e1-38fa-afb85090b637,2011-01-04 15:13:10+00:00,2011-01-04 15:28:10+00:00
9,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05 04:02:09+00:00,2011-01-05 04:17:09+00:00

In [56]:
procedures_clean[
    ["PATIENT", "ENCOUNTER", "START", "STOP"]
].head(10)

,PATIENT,ENCOUNTER,START,STOP
0,3de74169-7f67-9304-91d4-757e0f3a14d2,32c84703-2481-49cd-d571-3899d5820253,2011-01-02 09:26:36+00:00,2011-01-02 12:58:36+00:00
1,d9ec2e44-32e9-9148-179a-1653348cc4e2,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03 05:44:39+00:00,2011-01-03 06:01:42+00:00
2,d856d6e6-4c98-e7a2-129b-44076c63d008,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04 14:49:55+00:00,2011-01-04 15:04:55+00:00
3,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05 04:02:09+00:00,2011-01-05 04:17:09+00:00
4,3de74169-7f67-9304-91d4-757e0f3a14d2,9de5f0b0-4ba4-ce6f-45fb-b55c202f31a5,2011-01-05 12:58:36+00:00,2011-01-05 16:42:36+00:00
5,712e95dd-f313-39c7-1fc9-8463c15c105f,44057ea7-178f-c3c3-965a-78e4521fa43b,2011-01-06 18:12:41+00:00,2011-01-06 18:17:12+00:00
6,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,4b6a38e6-7df9-2d75-d850-6bd662f3d05b,2011-01-07 21:02:09+00:00,2011-01-07 22:39:45+00:00
7,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,cc36dc26-6019-94a5-93b7-7bbf312e6fc4,2011-01-07 22:39:45+00:00,2011-01-07 23:00:45+00:00
8,3de74169-7f67-9304-91d4-757e0f3a14d2,03f54837-bfc8-81aa-4905-f74ceb35162f,2011-01-08 16:42:36+00:00,2011-01-08 20:15:36+00:00
9,f4cde0dc-db22-5d98-5228-55121ae74cad,17d162fa-fc25-b3c5-5e72-20287a55eaf1,2011-01-09 16:11:28+00:00,2011-01-09 16:51:19+00:00

In [57]:
# ============================================================
# STEP 3.3.1 — VALIDATE PATIENT BIRTH/DEATH DATE LOGIC
# ============================================================

invalid_death_dates = patients_clean[
    patients_clean["DEATHDATE"].notna() &
    (patients_clean["DEATHDATE"] < patients_clean["BIRTHDATE"])
]

print("Patients with death date before birth date:",
      len(invalid_death_dates))

Patients with death date before birth date: 0

In [58]:
invalid_death_dates[
    ["Id", "BIRTHDATE", "DEATHDATE"]
].head()

Empty DataFrame
Columns: [Id, BIRTHDATE, DEATHDATE]
Index: []

In [59]:
# ============================================================
# STEP 3.3.2 — VALIDATE ENCOUNTER DATE LOGIC
# ============================================================

invalid_encounter_dates = encounters_clean[
    encounters_clean["STOP"] < encounters_clean["START"]
]

print(
    "Encounters with STOP before START:",
    len(invalid_encounter_dates)
)

Encounters with STOP before START: 0

In [60]:
zero_duration_encounters = encounters_clean[
    encounters_clean["STOP"] == encounters_clean["START"]
]

print(
    "Encounters with zero duration:",
    len(zero_duration_encounters)
)

Encounters with zero duration: 0

In [61]:
# ============================================================
# STEP 3.3.3 — VALIDATE PROCEDURE DATE LOGIC
# ============================================================

invalid_procedure_dates = procedures_clean[
    procedures_clean["STOP"] < procedures_clean["START"]
]

print(
    "Procedures with STOP before START:",
    len(invalid_procedure_dates)
)

Procedures with STOP before START: 0

In [62]:
zero_duration_procedures = procedures_clean[
    procedures_clean["STOP"] == procedures_clean["START"]
]

print(
    "Procedures with zero duration:",
    len(zero_duration_procedures)
)

Procedures with zero duration: 2

In [63]:
# ============================================================
# STEP 3.3.4 — CHECK ENCOUNTERS AGAINST PATIENT BIRTHDATES
# ============================================================

encounter_patient_dates = encounters_clean[
    ["Id", "PATIENT", "START"]
].merge(
    patients_clean[
        ["Id", "BIRTHDATE"]
    ],
    left_on="PATIENT",
    right_on="Id",
    how="left",
    suffixes=("_ENCOUNTER", "_PATIENT")
)

invalid_birth_encounters = encounter_patient_dates[
    encounter_patient_dates["START"].dt.date <
    encounter_patient_dates["BIRTHDATE"].dt.date
]

print(
    "Encounters occurring before patient birth:",
    len(invalid_birth_encounters)
)

Encounters occurring before patient birth: 0

In [64]:
# ============================================================
# STEP 3.3.5 — CHECK PROCEDURES AGAINST PATIENT BIRTHDATES
# ============================================================

procedure_patient_dates = procedures_clean[
    ["PATIENT", "ENCOUNTER", "START"]
].merge(
    patients_clean[
        ["Id", "BIRTHDATE"]
    ],
    left_on="PATIENT",
    right_on="Id",
    how="left"
)

invalid_birth_procedures = procedure_patient_dates[
    procedure_patient_dates["START"].dt.date <
    procedure_patient_dates["BIRTHDATE"].dt.date
]

print(
    "Procedures occurring before patient birth:",
    len(invalid_birth_procedures)
)

Procedures occurring before patient birth: 0

In [65]:
# ============================================================
# STEP 3.3.6 — DATE VALIDATION SUMMARY
# ============================================================

print("==============================================")
print("DATE VALIDATION SUMMARY")
print("==============================================")

print(
    "Invalid patient death dates:",
    len(invalid_death_dates)
)

print(
    "Invalid encounter date ranges:",
    len(invalid_encounter_dates)
)

print(
    "Zero-duration encounters:",
    len(zero_duration_encounters)
)

print(
    "Invalid procedure date ranges:",
    len(invalid_procedure_dates)
)

print(
    "Zero-duration procedures:",
    len(zero_duration_procedures)
)

print(
    "Encounters before patient birth:",
    len(invalid_birth_encounters)
)

print(
    "Procedures before patient birth:",
    len(invalid_birth_procedures)
)

==============================================
DATE VALIDATION SUMMARY
==============================================
Invalid patient death dates: 0
Invalid encounter date ranges: 0
Zero-duration encounters: 0
Invalid procedure date ranges: 0
Zero-duration procedures: 2
Encounters before patient birth: 0
Procedures before patient birth: 0

In [66]:
# ============================================================
# STAGE 3.4 — CREATE ENCOUNTER DURATION
# ============================================================

encounters_clean["ENCOUNTER_DURATION_MIN"] = (
    encounters_clean["STOP"] - encounters_clean["START"]
).dt.total_seconds() / 60

print("Encounter duration created successfully.")

Encounter duration created successfully.

In [67]:
encounters_clean[
    ["Id", "START", "STOP", "ENCOUNTER_DURATION_MIN"]
].head(10)

,Id,START,STOP,ENCOUNTER_DURATION_MIN
0,32c84703-2481-49cd-d571-3899d5820253,2011-01-02 09:26:36+00:00,2011-01-02 12:58:36+00:00,212.00
1,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03 05:44:39+00:00,2011-01-03 06:01:42+00:00,17.05
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,2011-01-03 14:32:11+00:00,2011-01-03 14:47:11+00:00,15.00
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,2011-01-03 16:24:45+00:00,2011-01-03 16:39:45+00:00,15.00
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03 17:36:53+00:00,2011-01-03 17:51:53+00:00,15.00
5,c4923a74-3e40-8b0c-cf73-05b9c0390621,2011-01-03 19:08:16+00:00,2011-01-03 19:23:16+00:00,15.00
6,c140ed81-040e-8319-e860-f72b4738ed22,2011-01-03 22:39:50+00:00,2011-01-03 22:54:50+00:00,15.00
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04 14:49:55+00:00,2011-01-04 15:04:55+00:00,15.00
8,16bdc066-886f-34e1-38fa-afb85090b637,2011-01-04 15:13:10+00:00,2011-01-04 15:28:10+00:00,15.00
9,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05 04:02:09+00:00,2011-01-05 04:17:09+00:00,15.00

In [68]:
encounters_clean["ENCOUNTER_DURATION_HOURS"] = (
    encounters_clean["ENCOUNTER_DURATION_MIN"] / 60
)

print("Encounter duration in hours created.")

Encounter duration in hours created.

In [69]:
encounters_clean[
    "ENCOUNTER_DURATION_MIN"
].describe()

count    2.789100e+04
mean     4.359597e+02
std      2.389942e+04
min      1.500000e+01
25%      1.500000e+01
50%      1.500000e+01
75%      5.185000e+01
max      2.695800e+06
Name: ENCOUNTER_DURATION_MIN, dtype: float64

In [70]:
negative_duration = encounters_clean[
    encounters_clean["ENCOUNTER_DURATION_MIN"] < 0
]

print(
    "Negative encounter durations:",
    len(negative_duration)
)

Negative encounter durations: 0

In [71]:
zero_duration = encounters_clean[
    encounters_clean["ENCOUNTER_DURATION_MIN"] == 0
]

print(
    "Zero-duration encounters:",
    len(zero_duration)
)

Zero-duration encounters: 0

In [72]:
missing_duration = encounters_clean[
    "ENCOUNTER_DURATION_MIN"
].isna().sum()

print(
    "Missing encounter durations:",
    missing_duration
)

Missing encounter durations: 0

In [73]:
# ============================================================
# ENCOUNTER DURATION QUALITY CHECK
# ============================================================

print("==============================================")
print("ENCOUNTER DURATION QUALITY CHECK")
print("==============================================")

print(
    "Total encounters:",
    len(encounters_clean)
)

print(
    "Missing durations:",
    encounters_clean["ENCOUNTER_DURATION_MIN"].isna().sum()
)

print(
    "Negative durations:",
    (encounters_clean["ENCOUNTER_DURATION_MIN"] < 0).sum()
)

print(
    "Zero-duration encounters:",
    (encounters_clean["ENCOUNTER_DURATION_MIN"] == 0).sum()
)

print(
    "\nDuration statistics (minutes):"
)

print(
    encounters_clean["ENCOUNTER_DURATION_MIN"].describe()
)

==============================================
ENCOUNTER DURATION QUALITY CHECK
==============================================
Total encounters: 27891
Missing durations: 0
Negative durations: 0
Zero-duration encounters: 0

Duration statistics (minutes):
count    2.789100e+04
mean     4.359597e+02
std      2.389942e+04
min      1.500000e+01
25%      1.500000e+01
50%      1.500000e+01
75%      5.185000e+01
max      2.695800e+06
Name: ENCOUNTER_DURATION_MIN, dtype: float64

In [74]:
# ============================================================
# STEP 3.4.9 — INVESTIGATE EXTREME ENCOUNTER DURATIONS
# ============================================================

longest_encounters = encounters_clean.sort_values(
    "ENCOUNTER_DURATION_MIN",
    ascending=False
)[[
    "Id",
    "PATIENT",
    "START",
    "STOP",
    "ENCOUNTERCLASS",
    "DESCRIPTION",
    "ENCOUNTER_DURATION_MIN",
    "BASE_ENCOUNTER_COST",
    "TOTAL_CLAIM_COST",
    "PAYER_COVERAGE",
    "REASONDESCRIPTION"
]]

longest_encounters.head(10)

,Id,PATIENT,START,STOP,ENCOUNTERCLASS,DESCRIPTION,ENCOUNTER_DURATION_MIN,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONDESCRIPTION
9704,fc2c2add-0b55-e300-5cea-8f43044eb330,5d47b9ac-3f37-f400-1747-c6c6f92130aa,2014-12-17 11:49:08+00:00,2020-02-01 13:49:08+00:00,ambulatory,Follow-up encounter (procedure),2.695800e+06,85.55,85.55,0.00,NaN
7735,2cb41a50-819c-ef7e-87df-b5b47b2e01a1,09e0ec41-cd4c-50b2-b425-824013777beb,2014-03-27 00:33:14+00:00,2019-03-13 15:33:14+00:00,ambulatory,Follow-up encounter (procedure),2.610180e+06,85.55,85.55,7.91,NaN
7805,7a19a260-e4a9-7b81-3f93-e07144d634d9,8885aba5-afce-9e3b-0c1d-a684a347b5fb,2014-04-02 22:26:28+00:00,2015-07-02 13:44:57+00:00,ambulatory,Follow-up encounter (procedure),6.561185e+05,85.55,85.55,24.27,NaN
6116,3cf29374-f91a-5877-9356-87792501d225,a12541db-140e-8189-070c-dc9f4815f40f,2014-01-31 02:29:54+00:00,2015-04-22 02:29:54+00:00,outpatient,Encounter for problem (procedure),6.422400e+05,85.55,85.55,36.44,NaN
6371,63b7c71f-23f5-32dc-b63a-cca7bf5625a2,6e8e0498-187a-d038-c7af-716b12e70455,2014-02-06 02:17:34+00:00,2015-01-20 02:17:34+00:00,outpatient,Encounter for problem (procedure),5.011200e+05,85.55,85.55,0.00,NaN
18343,4079872d-73da-3b52-5306-2a978c6f5c8c,54889029-0a1e-0b75-5980-1c091dd4bc0e,2018-07-18 23:56:20+00:00,2019-06-27 17:56:35+00:00,inpatient,Periodic reevaluation and management of health...,4.950002e+05,146.18,7093.85,5643.08,NaN
6380,110777dd-6aca-3c9c-7119-ab2494c0665e,0ec939a0-559c-7bc9-db9c-a7feae58634a,2014-02-06 04:57:58+00:00,2015-01-13 04:57:58+00:00,outpatient,Encounter for problem (procedure),4.910400e+05,85.55,85.55,0.00,NaN
7832,04df7388-7a70-3e99-c0fe-7f7ddd062931,ea9d6669-efc3-3c16-4f70-70cc1c1659d7,2014-04-04 22:41:46+00:00,2015-01-31 13:54:32+00:00,ambulatory,Follow-up encounter (procedure),4.343528e+05,85.55,85.55,0.00,NaN
6125,d0476a31-1524-f23f-fb79-290ecd6206aa,f6932663-d920-6e76-89e1-21a6b43cf03b,2014-01-31 11:10:57+00:00,2014-06-25 11:10:57+00:00,outpatient,Encounter for problem (procedure),2.088000e+05,85.55,85.55,0.00,NaN
6332,dcc730d3-4d74-5e75-ae03-cd23c0ee742c,60d2d35e-bd32-36df-b8e0-b64a3494f0e8,2014-02-05 08:41:28+00:00,2014-04-14 08:41:28+00:00,outpatient,Encounter for problem (procedure),9.792000e+04,85.55,85.55,0.00,NaN

In [75]:
# ============================================================
# STEP 3.4.10 — VIEW EXTREME DURATIONS IN DAYS
# ============================================================

longest_encounters = longest_encounters.copy()

longest_encounters["DURATION_DAYS"] = (
    longest_encounters["ENCOUNTER_DURATION_MIN"] / (60 * 24)
)

longest_encounters.head(10)

,Id,PATIENT,START,STOP,ENCOUNTERCLASS,DESCRIPTION,ENCOUNTER_DURATION_MIN,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONDESCRIPTION,DURATION_DAYS
9704,fc2c2add-0b55-e300-5cea-8f43044eb330,5d47b9ac-3f37-f400-1747-c6c6f92130aa,2014-12-17 11:49:08+00:00,2020-02-01 13:49:08+00:00,ambulatory,Follow-up encounter (procedure),2.695800e+06,85.55,85.55,0.00,NaN,1872.083333
7735,2cb41a50-819c-ef7e-87df-b5b47b2e01a1,09e0ec41-cd4c-50b2-b425-824013777beb,2014-03-27 00:33:14+00:00,2019-03-13 15:33:14+00:00,ambulatory,Follow-up encounter (procedure),2.610180e+06,85.55,85.55,7.91,NaN,1812.625000
7805,7a19a260-e4a9-7b81-3f93-e07144d634d9,8885aba5-afce-9e3b-0c1d-a684a347b5fb,2014-04-02 22:26:28+00:00,2015-07-02 13:44:57+00:00,ambulatory,Follow-up encounter (procedure),6.561185e+05,85.55,85.55,24.27,NaN,455.637836
6116,3cf29374-f91a-5877-9356-87792501d225,a12541db-140e-8189-070c-dc9f4815f40f,2014-01-31 02:29:54+00:00,2015-04-22 02:29:54+00:00,outpatient,Encounter for problem (procedure),6.422400e+05,85.55,85.55,36.44,NaN,446.000000
6371,63b7c71f-23f5-32dc-b63a-cca7bf5625a2,6e8e0498-187a-d038-c7af-716b12e70455,2014-02-06 02:17:34+00:00,2015-01-20 02:17:34+00:00,outpatient,Encounter for problem (procedure),5.011200e+05,85.55,85.55,0.00,NaN,348.000000
18343,4079872d-73da-3b52-5306-2a978c6f5c8c,54889029-0a1e-0b75-5980-1c091dd4bc0e,2018-07-18 23:56:20+00:00,2019-06-27 17:56:35+00:00,inpatient,Periodic reevaluation and management of health...,4.950002e+05,146.18,7093.85,5643.08,NaN,343.750174
6380,110777dd-6aca-3c9c-7119-ab2494c0665e,0ec939a0-559c-7bc9-db9c-a7feae58634a,2014-02-06 04:57:58+00:00,2015-01-13 04:57:58+00:00,outpatient,Encounter for problem (procedure),4.910400e+05,85.55,85.55,0.00,NaN,341.000000
7832,04df7388-7a70-3e99-c0fe-7f7ddd062931,ea9d6669-efc3-3c16-4f70-70cc1c1659d7,2014-04-04 22:41:46+00:00,2015-01-31 13:54:32+00:00,ambulatory,Follow-up encounter (procedure),4.343528e+05,85.55,85.55,0.00,NaN,301.633866
6125,d0476a31-1524-f23f-fb79-290ecd6206aa,f6932663-d920-6e76-89e1-21a6b43cf03b,2014-01-31 11:10:57+00:00,2014-06-25 11:10:57+00:00,outpatient,Encounter for problem (procedure),2.088000e+05,85.55,85.55,0.00,NaN,145.000000
6332,dcc730d3-4d74-5e75-ae03-cd23c0ee742c,60d2d35e-bd32-36df-b8e0-b64a3494f0e8,2014-02-05 08:41:28+00:00,2014-04-14 08:41:28+00:00,outpatient,Encounter for problem (procedure),9.792000e+04,85.55,85.55,0.00,NaN,68.000000

In [76]:
# ============================================================
# STEP 3.4.11 — ENCOUNTER DURATION DISTRIBUTION
# ============================================================

duration_ranges = pd.cut(
    encounters_clean["ENCOUNTER_DURATION_MIN"],
    bins=[
        0,
        30,
        60,
        120,
        360,
        1440,
        10080,
        float("inf")
    ],
    labels=[
        "0–30 minutes",
        "31–60 minutes",
        "61–120 minutes",
        "121–360 minutes",
        "6–24 hours",
        "1–7 days",
        "Over 7 days"
    ],
    include_lowest=True
)

duration_distribution = (
    duration_ranges
    .value_counts()
    .sort_index()
    .to_frame("Encounter_Count")
)

duration_distribution["Percentage"] = (
    duration_distribution["Encounter_Count"]
    / len(encounters_clean)
    * 100
)

duration_distribution

                        Encounter_Count  Percentage
ENCOUNTER_DURATION_MIN
0–30 minutes                      19958   71.557133
31–60 minutes                      3852   13.810907
61–120 minutes                      194    0.695565
121–360 minutes                    2733    9.798860
6–24 hours                         1079    3.868631
1–7 days                             44    0.157757
Over 7 days                          31    0.111147

In [77]:
# ============================================================
# STEP 3.4.12 — INVESTIGATE LONG ENCOUNTERS
# ============================================================

long_encounters = encounters_clean[
    encounters_clean["ENCOUNTER_DURATION_MIN"] > 7 * 24 * 60
].copy()

long_encounters["DURATION_DAYS"] = (
    long_encounters["ENCOUNTER_DURATION_MIN"] / (60 * 24)
)

print(
    "Encounters longer than 7 days:",
    len(long_encounters)
)

long_encounters[
    [
        "Id",
        "PATIENT",
        "START",
        "STOP",
        "ENCOUNTERCLASS",
        "DESCRIPTION",
        "DURATION_DAYS"
    ]
].sort_values(
    "DURATION_DAYS",
    ascending=False
).head(20)

Encounters longer than 7 days: 31

,Id,PATIENT,START,STOP,ENCOUNTERCLASS,DESCRIPTION,DURATION_DAYS
9704,fc2c2add-0b55-e300-5cea-8f43044eb330,5d47b9ac-3f37-f400-1747-c6c6f92130aa,2014-12-17 11:49:08+00:00,2020-02-01 13:49:08+00:00,ambulatory,Follow-up encounter (procedure),1872.083333
7735,2cb41a50-819c-ef7e-87df-b5b47b2e01a1,09e0ec41-cd4c-50b2-b425-824013777beb,2014-03-27 00:33:14+00:00,2019-03-13 15:33:14+00:00,ambulatory,Follow-up encounter (procedure),1812.625000
7805,7a19a260-e4a9-7b81-3f93-e07144d634d9,8885aba5-afce-9e3b-0c1d-a684a347b5fb,2014-04-02 22:26:28+00:00,2015-07-02 13:44:57+00:00,ambulatory,Follow-up encounter (procedure),455.637836
6116,3cf29374-f91a-5877-9356-87792501d225,a12541db-140e-8189-070c-dc9f4815f40f,2014-01-31 02:29:54+00:00,2015-04-22 02:29:54+00:00,outpatient,Encounter for problem (procedure),446.000000
6371,63b7c71f-23f5-32dc-b63a-cca7bf5625a2,6e8e0498-187a-d038-c7af-716b12e70455,2014-02-06 02:17:34+00:00,2015-01-20 02:17:34+00:00,outpatient,Encounter for problem (procedure),348.000000
18343,4079872d-73da-3b52-5306-2a978c6f5c8c,54889029-0a1e-0b75-5980-1c091dd4bc0e,2018-07-18 23:56:20+00:00,2019-06-27 17:56:35+00:00,inpatient,Periodic reevaluation and management of health...,343.750174
6380,110777dd-6aca-3c9c-7119-ab2494c0665e,0ec939a0-559c-7bc9-db9c-a7feae58634a,2014-02-06 04:57:58+00:00,2015-01-13 04:57:58+00:00,outpatient,Encounter for problem (procedure),341.000000
7832,04df7388-7a70-3e99-c0fe-7f7ddd062931,ea9d6669-efc3-3c16-4f70-70cc1c1659d7,2014-04-04 22:41:46+00:00,2015-01-31 13:54:32+00:00,ambulatory,Follow-up encounter (procedure),301.633866
6125,d0476a31-1524-f23f-fb79-290ecd6206aa,f6932663-d920-6e76-89e1-21a6b43cf03b,2014-01-31 11:10:57+00:00,2014-06-25 11:10:57+00:00,outpatient,Encounter for problem (procedure),145.000000
6138,1123fed5-342e-f49b-4ab9-91f153b9e474,d40ba361-8192-a8e6-b75c-5def4758fe3f,2014-01-31 20:39:04+00:00,2014-04-09 20:39:04+00:00,outpatient,Encounter for problem (procedure),68.000000
6332,dcc730d3-4d74-5e75-ae03-cd23c0ee742c,60d2d35e-bd32-36df-b8e0-b64a3494f0e8,2014-02-05 08:41:28+00:00,2014-04-14 08:41:28+00:00,outpatient,Encounter for problem (procedure),68.000000
16504,0b29bad1-7b3c-2585-1b31-c3dd7a6ec36a,a96d5031-46d5-e3f6-ec67-81f8edd48aa8,2017-09-30 13:44:27+00:00,2017-11-25 13:44:27+00:00,inpatient,Periodic reevaluation and management of health...,56.000000
6145,6053724d-e3b1-0449-402d-3090d3514389,f21a9c39-abd4-4e57-575d-83e1c29484da,2014-01-31 23:35:27+00:00,2014-03-26 23:35:27+00:00,outpatient,Encounter for problem (procedure),54.000000
8980,9741be00-49a5-f25a-a59b-ea46ffbad229,77dedc66-369c-bb18-940d-0db841255ef7,2014-09-14 10:42:36+00:00,2014-10-11 21:42:36+00:00,ambulatory,Follow-up encounter (procedure),27.458333
23048,6c108963-2fda-815b-3813-a424b3533127,01296e88-f6d9-1c18-cf91-87523325e034,2020-08-15 04:52:21+00:00,2020-09-08 17:52:21+00:00,emergency,Encounter for problem,24.541667
5457,d5c42fa8-f110-b714-d89a-04ec57038a58,0226f105-2572-1c6f-15f0-1aa0438e40d0,2013-10-22 00:16:17+00:00,2013-11-14 00:16:17+00:00,inpatient,Encounter for symptom (procedure),23.000000
14807,6fc6cbfc-ade5-c9ec-721c-4f71d9a1a815,2f6c035b-a11d-9373-89af-0cb2195592d2,2017-01-11 09:03:19+00:00,2017-01-27 09:03:19+00:00,emergency,Emergency room admission (procedure),16.000000
24226,96f41ac9-60c0-d035-249b-ea9f68dfb7da,2999ffe8-ab8a-3afa-ab9e-aa40fa162e8c,2021-01-12 14:24:46+00:00,2021-01-25 15:06:45+00:00,inpatient,Hospital admission for isolation (procedure),13.029155
24155,49a58342-2bed-0dec-5581-f12474408881,7811ad1e-3baf-5d00-6664-01c7396f67c9,2021-01-03 03:22:46+00:00,2021-01-16 04:02:42+00:00,inpatient,Hospital admission for isolation (procedure),13.027731
23972,d12cbc08-c639-0917-6250-66eca2e6995f,97c4cfee-e860-e908-1797-8da4dc241ec4,2020-12-12 19:05:25+00:00,2020-12-25 19:32:34+00:00,inpatient,Hospital admission for isolation (procedure),13.018854

# Stage 4 — Exploratory Data Analysis (EDA)

## Objectives

- Understand patient demographics
- Understand healthcare utilization patterns
- Analyze encounter types and volumes
- Examine procedure activity
- Explore healthcare costs and payer coverage
- Identify temporal trends
- Identify unusual patterns and potential business questions

## EDA Principle

EDA is exploratory rather than conclusive. Findings from this stage will be used to formulate business questions for deeper analysis.

In [78]:
# ============================================================
# STEP 4.2 — DATASET SUMMARY
# ============================================================

eda_summary = pd.DataFrame({
    "Dataset": [
        "Patients",
        "Encounters",
        "Procedures",
        "Payers",
        "Organizations"
    ],
    "Rows": [
        len(patients_clean),
        len(encounters_clean),
        len(procedures_clean),
        len(payers_clean),
        len(organizations_clean)
    ],
    "Columns": [
        len(patients_clean.columns),
        len(encounters_clean.columns),
        len(procedures_clean.columns),
        len(payers_clean.columns),
        len(organizations_clean.columns)
    ]
})

eda_summary

         Dataset   Rows  Columns
0       Patients    974       20
1     Encounters  27891       16
2     Procedures  47701        9
3         Payers     10        7
4  Organizations      1        8

In [79]:
# ============================================================
# 4.3.1 Gender Distribution
# ============================================================

gender_distribution = (
    patients_clean["GENDER"]
    .value_counts()
    .reset_index()
)

gender_distribution.columns = ["Gender", "Patients"]

gender_distribution["Percentage"] = (
    gender_distribution["Patients"]
    / len(patients_clean)
    * 100
).round(2)

gender_distribution

  Gender  Patients  Percentage
0      M       494       50.72
1      F       480       49.28

In [80]:
# ============================================================
# 4.3.2 Race Distribution
# ============================================================

race_distribution = (
    patients_clean["RACE"]
    .value_counts()
    .reset_index()
)

race_distribution.columns = ["Race", "Patients"]

race_distribution["Percentage"] = (
    race_distribution["Patients"]
    / len(patients_clean)
    * 100
).round(2)

In [81]:


# ============================================================
# Ethnicity Distribution
# ============================================================
ethnicity_distribution = (
    patients_clean["ETHNICITY"]
    .value_counts()
    .reset_index()
)

ethnicity_distribution.columns = ["Ethnicity", "Patients"]

ethnicity_distribution["Percentage"] = (
    ethnicity_distribution["Patients"]
    / len(patients_clean)
    * 100
).round(2)

ethnicity_distribution

     Ethnicity  Patients  Percentage
0  nonhispanic       783       80.39
1     hispanic       191       19.61

In [82]:
# ============================================================
# 4.3.4 Marital Status
# ============================================================

marital_distribution = (
    patients_clean["MARITAL"]
    .fillna("Unknown")
    .value_counts()
    .reset_index()
)

marital_distribution.columns = ["Marital_Status", "Patients"]

marital_distribution["Percentage"] = (
    marital_distribution["Patients"]
    / len(patients_clean)
    * 100
).round(2)

marital_distribution

  Marital_Status  Patients  Percentage
0              M       784       80.49
1              S       189       19.40
2        Unknown         1        0.10

In [83]:
# ============================================================
# STAGE 4.1 — STANDARDIZE DATE TIMEZONE BEFORE AGE CALCULATION
# ============================================================

# Make patient birthdates timezone-aware (UTC)
patients_age = patients_clean.copy()

patients_age["BIRTHDATE"] = pd.to_datetime(
    patients_age["BIRTHDATE"],
    errors="coerce",
    utc=True
)

# Make encounter START timezone-aware (UTC)
encounters_clean["START"] = pd.to_datetime(
    encounters_clean["START"],
    errors="coerce",
    utc=True
)

# Create birthdate lookup
birthdate_lookup = patients_age.set_index("Id")["BIRTHDATE"]

# Match each encounter to the patient's birthdate
encounter_birthdates = encounters_clean["PATIENT"].map(
    birthdate_lookup
)

# Calculate age at encounter
encounters_clean["AGE_AT_ENCOUNTER"] = (
    encounters_clean["START"] - encounter_birthdates
).dt.days / 365.25

# Round age
encounters_clean["AGE_AT_ENCOUNTER"] = (
    encounters_clean["AGE_AT_ENCOUNTER"].round(1)
)

print("Age calculation completed successfully.")

encounters_clean[
    ["Id", "PATIENT", "START", "AGE_AT_ENCOUNTER"]
].head(10)

Age calculation completed successfully.

,Id,PATIENT,START,AGE_AT_ENCOUNTER
0,32c84703-2481-49cd-d571-3899d5820253,3de74169-7f67-9304-91d4-757e0f3a14d2,2011-01-02 09:26:36+00:00,82.4
1,c98059da-320a-c0a6-fced-c8815f3e3f39,d9ec2e44-32e9-9148-179a-1653348cc4e2,2011-01-03 05:44:39+00:00,47.0
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,73babadf-5b2b-fee7-189e-6f41ff213e01,2011-01-03 14:32:11+00:00,86.5
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,3b46a0b7-0f34-9b9a-c319-ace4a1f58c0b,2011-01-03 16:24:45+00:00,87.6
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,fa006887-d93c-d302-8b89-f3c25f88c0e1,2011-01-03 17:36:53+00:00,58.2
5,c4923a74-3e40-8b0c-cf73-05b9c0390621,823c6b40-9dbe-e463-310b-ea2b23b23b48,2011-01-03 19:08:16+00:00,88.2
6,c140ed81-040e-8319-e860-f72b4738ed22,9c616fc0-00ea-249f-d073-1f3bb15d41fa,2011-01-03 22:39:50+00:00,25.3
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,d856d6e6-4c98-e7a2-129b-44076c63d008,2011-01-04 14:49:55+00:00,56.4
8,16bdc066-886f-34e1-38fa-afb85090b637,a80b1160-93f0-db7e-9f23-04ea6fdddfaf,2011-01-04 15:13:10+00:00,82.5
9,17966936-0878-f4db-128b-a43ae10d0878,bc9d59c3-0a30-6e3b-f47d-022e4f03c8de,2011-01-05 04:02:09+00:00,81.2

In [84]:
print("Missing ages:", encounters_clean["AGE_AT_ENCOUNTER"].isna().sum())
print("Negative ages:", (encounters_clean["AGE_AT_ENCOUNTER"] < 0).sum())

print("\nAge statistics:")
print(encounters_clean["AGE_AT_ENCOUNTER"].describe())

Missing ages: 0
Negative ages: 0

Age statistics:
count    27891.000000
mean        71.172819
std         20.304932
min         19.900000
25%         56.300000
50%         79.700000
75%         86.900000
max         99.300000
Name: AGE_AT_ENCOUNTER, dtype: float64

In [85]:
# ============================================================
# STAGE 4.2 — CREATE AGE GROUPS
# ============================================================

bins = [-1, 17, 34, 49, 64, 79, float("inf")]

labels = [
    "0–17",
    "18–34",
    "35–49",
    "50–64",
    "65–79",
    "80+"
]

encounters_clean["AGE_GROUP"] = pd.cut(
    encounters_clean["AGE_AT_ENCOUNTER"],
    bins=bins,
    labels=labels
)

print(encounters_clean["AGE_GROUP"].value_counts().sort_index())

AGE_GROUP
0–17         0
18–34     2085
35–49     3211
50–64     3504
65–79     4821
80+      14270
Name: count, dtype: int64

In [86]:
# ============================================================
# STAGE 4.2.1 — AGE GROUP QUALITY CHECK
# ============================================================

print("Total encounters:", len(encounters_clean))

print(
    "Age groups assigned:",
    encounters_clean["AGE_GROUP"].notna().sum()
)

print(
    "Missing age groups:",
    encounters_clean["AGE_GROUP"].isna().sum()
)

print("\nAge group percentages:")

age_group_summary = (
    encounters_clean["AGE_GROUP"]
    .value_counts(dropna=False)
    .sort_index()
    .to_frame("Encounter_Count")
)

age_group_summary["Percentage"] = (
    age_group_summary["Encounter_Count"]
    / len(encounters_clean)
    * 100
).round(2)

print(age_group_summary)

Total encounters: 27891
Age groups assigned: 27891
Missing age groups: 0

Age group percentages:
           Encounter_Count  Percentage
AGE_GROUP
0–17                     0        0.00
18–34                 2085        7.48
35–49                 3211       11.51
50–64                 3504       12.56
65–79                 4821       17.29
80+                  14270       51.16

In [87]:
encounter_volume = (
    encounters_clean["ENCOUNTERCLASS"]
    .value_counts()
    .reset_index()
)

encounter_volume.columns = [
    "Encounter_Type",
    "Encounters"
]

encounter_volume["Percentage"] = (
    encounter_volume["Encounters"]
    / len(encounters_clean)
    * 100
).round(2)

encounter_volume

  Encounter_Type  Encounters  Percentage
0     ambulatory       12537       44.95
1     outpatient        6300       22.59
2     urgentcare        3666       13.14
3      emergency        2322        8.33
4       wellness        1931        6.92
5      inpatient        1135        4.07

In [88]:
# ============================================================
# STAGE 4.3.1 — PATIENT AGE AT DEATH
# ============================================================

patients_clean["AGE_AT_DEATH"] = (
    patients_clean["DEATHDATE"] - patients_clean["BIRTHDATE"]
).dt.days / 365.25

patients_clean["AGE_AT_DEATH"] = (
    patients_clean["AGE_AT_DEATH"].round(1)
)

print("Age at death calculated successfully.")

print(
    patients_clean[
        ["Id", "BIRTHDATE", "DEATHDATE", "AGE_AT_DEATH"]
    ].head(10)
)

Age at death calculated successfully.
                                     Id  BIRTHDATE  DEATHDATE  AGE_AT_DEATH
0  5605b66b-e92d-c16c-1b83-b8bf7040d51f 1977-03-19        NaT           NaN
1  6e5ae27c-8038-7988-e2c0-25a103f01bfa 1940-02-19        NaT           NaN
2  8123d076-0886-9007-e956-d5864aa121a7 1958-06-04        NaT           NaN
3  770518e4-6133-648e-60c9-071eb2f0e2ce 1928-12-25 2017-09-29          88.8
4  f96addf5-81b9-0aab-7855-d208d3d352c5 1928-12-25 2014-02-23          85.2
5  8e9650d1-788a-78f9-4a28-d08f7f95354a 1928-12-25        NaT           NaN
6  183df435-4190-060e-8f8e-bf63c572b266 1957-11-08        NaT           NaN
7  720560d4-51da-c38c-ee90-c15935278df1 1972-06-27        NaT           NaN
8  217851b0-5f47-d376-18b9-0fe4ba77207e 1954-03-06        NaT           NaN
9  ff331e5c-ab16-e218-f39a-63e11de1ed75 1927-07-10        NaT           NaN

In [89]:
# ============================================================
# STAGE 4.3.2 — DECEASED INDICATOR
# ============================================================

patients_clean["IS_DECEASED"] = (
    patients_clean["DEATHDATE"].notna()
)

print(
    patients_clean["IS_DECEASED"]
    .value_counts()
)

IS_DECEASED
False    820
True     154
Name: count, dtype: int64

In [90]:
# ============================================================
# STAGE 4.3.3 — AGE AT DEATH QUALITY CHECK
# ============================================================

print("Patients:", len(patients_clean))

print(
    "Patients with death date:",
    patients_clean["DEATHDATE"].notna().sum()
)

print(
    "Patients with calculated age at death:",
    patients_clean["AGE_AT_DEATH"].notna().sum()
)

print(
    "Negative age at death:",
    (patients_clean["AGE_AT_DEATH"] < 0).sum()
)

print("\nAge at death statistics:")
print(
    patients_clean["AGE_AT_DEATH"].describe()
)

Patients: 974
Patients with death date: 154
Patients with calculated age at death: 154
Negative age at death: 0

Age at death statistics:
count    154.000000
mean      79.846104
std       14.725822
min       26.200000
25%       78.000000
50%       84.550000
75%       88.800000
max       97.600000
Name: AGE_AT_DEATH, dtype: float64

In [91]:
# ============================================================
# STAGE 4.4 — PATIENT AGE GROUP
# ============================================================

patients_clean["AGE_GROUP"] = pd.cut(
    patients_clean["AGE_AT_DEATH"],
    bins=[-1, 17, 34, 49, 64, 79, float("inf")],
    labels=[
        "0–17",
        "18–34",
        "35–49",
        "50–64",
        "65–79",
        "80+"
    ]
)

print(
    patients_clean["AGE_GROUP"]
    .value_counts(dropna=False)
    .sort_index()
)

AGE_GROUP
0–17       0
18–34      2
35–49      8
50–64     10
65–79     19
80+      115
NaN      820
Name: count, dtype: int64

In [92]:
# ============================================================
# STAGE 4.4 — PATIENT AGE GROUP AT DEATH
# ============================================================

patients_clean["AGE_GROUP_AT_DEATH"] = pd.cut(
    patients_clean["AGE_AT_DEATH"],
    bins=[-1, 17, 34, 49, 64, 79, float("inf")],
    labels=[
        "0–17",
        "18–34",
        "35–49",
        "50–64",
        "65–79",
        "80+"
    ]
)

print("Age group at death distribution:")
print(
    patients_clean["AGE_GROUP_AT_DEATH"]
    .value_counts(dropna=False)
    .sort_index()
)

Age group at death distribution:
AGE_GROUP_AT_DEATH
0–17       0
18–34      2
35–49      8
50–64     10
65–79     19
80+      115
NaN      820
Name: count, dtype: int64

In [93]:
# ============================================================
# STAGE 4.4.1 — AGE GROUP VALIDATION
# ============================================================

print("Total patients:", len(patients_clean))

print(
    "Patients with death date:",
    patients_clean["DEATHDATE"].notna().sum()
)

print(
    "Patients assigned an age group:",
    patients_clean["AGE_GROUP_AT_DEATH"].notna().sum()
)

print(
    "Missing age groups:",
    patients_clean["AGE_GROUP_AT_DEATH"].isna().sum()
)

Total patients: 974
Patients with death date: 154
Patients assigned an age group: 154
Missing age groups: 820

In [94]:
encounter_description = (
    encounters_clean["DESCRIPTION"]
    .value_counts()
    .reset_index()
)

encounter_description.columns = [
    "Description",
    "Encounters"
]

encounter_description.head(15)

                                          Description  Encounters
0                   Encounter for problem (procedure)        4308
1                      Urgent care clinic (procedure)        3633
2                  Encounter for check up (procedure)        2950
3          General examination of patient (procedure)        1880
4                               Encounter for symptom        1824
5                                 Follow-up encounter        1565
6              Telemedicine consultation with patient        1548
7                                 Emergency Encounter        1475
8             Patient encounter procedure (procedure)        1059
9                                      Prenatal visit        1026
10  Administration of vaccine to produce active im...        1003
11                              Encounter for problem         959
12                        Patient encounter procedure         681
13                           Encounter for 'check-up'         678
14               Emergency room admission (procedure)         472

In [95]:
patient_utilization = (
    encounters_clean
    .groupby("PATIENT")
    .agg(
        Encounter_Count=("Id", "count"),
        Total_Encounter_Cost=("TOTAL_CLAIM_COST", "sum"),
        Total_Payer_Coverage=("PAYER_COVERAGE", "sum"),
        Average_Encounter_Cost=("TOTAL_CLAIM_COST", "mean")
    )
    .reset_index()
)

patient_utilization.head()

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Average_Encounter_Cost
0,002bc307-2fff-04ba-161b-98cce123e226,46,13742.67,9509.86,298.753696
1,0034fe01-207f-275f-6b4b-821f7b0af044,75,548667.37,5494.56,7315.564933
2,00abe029-00fa-a666-34f5-258a36978f6d,22,48334.27,6384.67,2197.012273
3,010ff9c1-564b-6e32-09f4-29cb4224bba9,4,26367.50,19475.04,6591.875000
4,01274098-150f-8211-6150-29f2a2da266c,1,0.00,0.00,0.000000

In [96]:
patient_utilization["Encounter_Count"].describe()

count     974.000000
mean       28.635524
std        73.035671
min         1.000000
25%         4.000000
50%        14.000000
75%        28.000000
max      1381.000000
Name: Encounter_Count, dtype: float64

In [97]:
top_utilizers = (
    patient_utilization
    .sort_values(
        "Encounter_Count",
        ascending=False
    )
    .head(10)
)

top_utilizers

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Average_Encounter_Cost
85,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,2437415.31,0.00,1764.964019
371,5e055638-0dad-dfd5-005d-1e74b6fd29ac,887,844913.74,628529.62,952.552131
240,3de74169-7f67-9304-91d4-757e0f3a14d2,877,819279.19,0.00,934.183797
245,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,9932262.99,0.00,22219.827718
370,5dcb295d-92df-a147-ebcc-aa49b6262830,441,105080.78,44171.55,238.278413
275,442dc617-c7f2-0513-15cd-c35c4efdba73,392,156858.67,23241.99,400.149668
694,b4ab9ab3-f52a-751e-a990-3bd5654d5870,383,124858.48,41136.64,326.001253
600,9b8ae606-5059-b3a6-19c7-c812901898bb,364,187907.26,133760.63,516.228736
693,b4671e80-7e87-9260-ca31-6a9397d465d1,296,65245.84,40333.20,220.425135
973,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,6356665.66,845233.69,21844.211890

In [98]:
cost_summary = encounters_clean[
    [
        "BASE_ENCOUNTER_COST",
        "TOTAL_CLAIM_COST",
        "PAYER_COVERAGE"
    ]
].describe()

cost_summary

       BASE_ENCOUNTER_COST  TOTAL_CLAIM_COST  PAYER_COVERAGE
count         27891.000000      27891.000000    27891.000000
mean            116.181614       3639.682174     1114.965652
std              28.410082       9205.595748     4768.615576
min              85.550000          0.000000        0.000000
25%              85.550000        142.580000        0.000000
50%             136.800000        278.580000       28.440000
75%             142.580000       1412.530000      155.770000
max             146.180000     641882.700000   247751.420000

In [99]:
print(
    "Total claim cost:",
    round(encounters_clean["TOTAL_CLAIM_COST"].sum(), 2)
)

print(
    "Total payer coverage:",
    round(encounters_clean["PAYER_COVERAGE"].sum(), 2)
)

print(
    "Average claim cost:",
    round(encounters_clean["TOTAL_CLAIM_COST"].mean(), 2)
)

print(
    "Average payer coverage:",
    round(encounters_clean["PAYER_COVERAGE"].mean(), 2)
)

Total claim cost: 101514375.52
Total payer coverage: 31097506.99
Average claim cost: 3639.68
Average payer coverage: 1114.97

In [100]:
encounters_clean["PATIENT_RESPONSIBILITY"] = (
    encounters_clean["TOTAL_CLAIM_COST"]
    - encounters_clean["PAYER_COVERAGE"]
)

encounters_clean[
    "PATIENT_RESPONSIBILITY"
].describe()

count     27891.000000
mean       2524.716523
std        7661.005002
min           0.000000
25%          85.550000
50%         172.590000
75%        1004.630000
max      641882.700000
Name: PATIENT_RESPONSIBILITY, dtype: float64

In [101]:
encounters_clean["PATIENT_RESPONSIBILITY"] = (
    encounters_clean["TOTAL_CLAIM_COST"]
    - encounters_clean["PAYER_COVERAGE"]
)

encounters_clean[
    "PATIENT_RESPONSIBILITY"
].describe()

count     27891.000000
mean       2524.716523
std        7661.005002
min           0.000000
25%          85.550000
50%         172.590000
75%        1004.630000
max      641882.700000
Name: PATIENT_RESPONSIBILITY, dtype: float64

In [102]:
print(
    "Negative patient responsibility:",
    (
        encounters_clean["PATIENT_RESPONSIBILITY"] < 0
    ).sum()
)

Negative patient responsibility: 0

In [103]:
payer_analysis = (
    encounters_clean
    .groupby("PAYER")
    .agg(
        Encounters=("Id", "count"),
        Total_Claim_Cost=("TOTAL_CLAIM_COST", "sum"),
        Total_Payer_Coverage=("PAYER_COVERAGE", "sum"),
        Average_Claim_Cost=("TOTAL_CLAIM_COST", "mean")
    )
    .reset_index()
)

payer_analysis

,PAYER,Encounters,Total_Claim_Cost,Total_Payer_Coverage,Average_Claim_Cost
0,047f6ec3-6215-35eb-9608-f9dda363a44c,809,2424532.96,968.35,2996.950507
1,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,704,2982715.05,0.00,4236.811151
2,4d71f845-a6a9-3c39-b242-14d25ef86a8d,936,2589956.10,1780.16,2767.047115
3,5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,900,2563507.98,3937.32,2848.342200
4,6e2f1a2d-27bd-3701-8d08-dae202c58632,925,3002166.01,2074496.34,3245.584876
5,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,1443,8954131.02,8417973.72,6205.219002
6,7caa7254-5050-3b5e-9eae-bd5ea30e809c,11371,24647228.89,19215691.37,2167.551569
7,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,8807,49259290.16,0.00,5593.197475
8,b3221cfc-24fb-339e-823d-bc4136cbc4ed,912,1546925.99,1380705.87,1696.190779
9,d47b3510-2895-3b70-9897-342d681c769d,1084,3543921.36,1953.86,3269.300148

In [104]:
payer_analysis = payer_analysis.merge(
    payers_clean[["Id", "NAME"]],
    left_on="PAYER",
    right_on="Id",
    how="left"
)

payer_analysis = payer_analysis.drop(
    columns=["Id"]
)

payer_analysis

,PAYER,Encounters,Total_Claim_Cost,Total_Payer_Coverage,Average_Claim_Cost,NAME
0,047f6ec3-6215-35eb-9608-f9dda363a44c,809,2424532.96,968.35,2996.950507,Cigna Health
1,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,704,2982715.05,0.00,4236.811151,Anthem
2,4d71f845-a6a9-3c39-b242-14d25ef86a8d,936,2589956.10,1780.16,2767.047115,Aetna
3,5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,900,2563507.98,3937.32,2848.342200,UnitedHealthcare
4,6e2f1a2d-27bd-3701-8d08-dae202c58632,925,3002166.01,2074496.34,3245.584876,Blue Cross Blue Shield
5,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,1443,8954131.02,8417973.72,6205.219002,Medicaid
6,7caa7254-5050-3b5e-9eae-bd5ea30e809c,11371,24647228.89,19215691.37,2167.551569,Medicare
7,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,8807,49259290.16,0.00,5593.197475,NO_INSURANCE
8,b3221cfc-24fb-339e-823d-bc4136cbc4ed,912,1546925.99,1380705.87,1696.190779,Dual Eligible
9,d47b3510-2895-3b70-9897-342d681c769d,1084,3543921.36,1953.86,3269.300148,Humana

In [105]:
payer_analysis["Coverage_Rate"] = (
    payer_analysis["Total_Payer_Coverage"]
    / payer_analysis["Total_Claim_Cost"]
    * 100
).round(2)

payer_analysis.sort_values(
    "Coverage_Rate",
    ascending=False
)

,PAYER,Encounters,Total_Claim_Cost,Total_Payer_Coverage,Average_Claim_Cost,NAME,Coverage_Rate
5,7c4411ce-02f1-39b5-b9ec-dfbea9ad3c1a,1443,8954131.02,8417973.72,6205.219002,Medicaid,94.01
8,b3221cfc-24fb-339e-823d-bc4136cbc4ed,912,1546925.99,1380705.87,1696.190779,Dual Eligible,89.25
6,7caa7254-5050-3b5e-9eae-bd5ea30e809c,11371,24647228.89,19215691.37,2167.551569,Medicare,77.96
4,6e2f1a2d-27bd-3701-8d08-dae202c58632,925,3002166.01,2074496.34,3245.584876,Blue Cross Blue Shield,69.10
3,5059a55e-5d6e-34d1-b6cb-d83d16e57bcf,900,2563507.98,3937.32,2848.342200,UnitedHealthcare,0.15
2,4d71f845-a6a9-3c39-b242-14d25ef86a8d,936,2589956.10,1780.16,2767.047115,Aetna,0.07
9,d47b3510-2895-3b70-9897-342d681c769d,1084,3543921.36,1953.86,3269.300148,Humana,0.06
0,047f6ec3-6215-35eb-9608-f9dda363a44c,809,2424532.96,968.35,2996.950507,Cigna Health,0.04
1,42c4fca7-f8a9-3cd1-982a-dd9751bf3e2a,704,2982715.05,0.00,4236.811151,Anthem,0.00
7,b1c428d6-4f07-31e0-90f0-68ffa6ff8c76,8807,49259290.16,0.00,5593.197475,NO_INSURANCE,0.00

In [106]:
procedure_summary = (
    procedures_clean["DESCRIPTION"]
    .value_counts()
    .reset_index()
)

procedure_summary.columns = [
    "Procedure",
    "Procedure_Count"
]

procedure_summary.head(20)

                                            Procedure  Procedure_Count
0   Assessment of health and social care needs (pr...             4596
1                       Hospice care (regime/therapy)             4098
2                    Depression screening (procedure)             3614
3   Depression screening using Patient Health Ques...             3614
4             Assessment of substance use (procedure)             2906
5                          Renal dialysis (procedure)             2746
6       Assessment using Morse Fall Scale (procedure)             2422
7                   Assessment of anxiety (procedure)             2288
8               Medication Reconciliation (procedure)             2284
9                Screening for drug abuse (procedure)             1484
10           Screening for domestic abuse (procedure)             1432
11  Assessment using Alcohol Use Disorders Identif...             1422
12                           Electrical cardioversion             1383
13                Evaluation of uterine fundal height             1065
14                    Auscultation of the fetal heart             1065
15                  Movement therapy (regime/therapy)              890
16                            Intramuscular injection              522
17  Combined chemotherapy and radiation therapy (p...              444
18                                        Colonoscopy              424
19               Catheter ablation of tissue of heart              365

In [107]:
procedure_cost = (
    procedures_clean
    .groupby("DESCRIPTION")
    .agg(
        Procedure_Count=("CODE", "count"),
        Total_Cost=("BASE_COST", "sum"),
        Average_Cost=("BASE_COST", "mean")
    )
    .reset_index()
)

procedure_cost = procedure_cost.sort_values(
    "Total_Cost",
    ascending=False
)

procedure_cost.head(20)

,DESCRIPTION,Procedure_Count,Total_Cost,Average_Cost
50,Electrical cardioversion,1383,35824002,25903.110629
17,Auscultation of the fetal heart,1065,5657822,5312.508920
54,Evaluation of uterine fundal height,1065,5631281,5287.587793
36,Combined chemotherapy and radiation therapy (p...,444,5237596,11796.387387
35,Colonoscopy,424,5021003,11841.988208
27,Catheter ablation of tissue of heart,365,3405999,9331.504110
124,Renal dialysis (procedure),2746,2757221,1004.086307
11,Assessment of health and social care needs (pr...,4596,1980876,431.000000
23,Bone density scan (procedure),198,1901367,9602.863636
69,Hospice care (regime/therapy),4098,1766238,431.000000
154,Ultrasound scan for fetal viability,184,1693824,9205.565217
137,Spirometry (procedure),209,1628688,7792.765550
44,Depression screening (procedure),3614,1557634,431.000000
46,Depression screening using Patient Health Ques...,3614,1557634,431.000000
34,Cognitive and behavioral therapy (regime/therapy),136,1412779,10388.080882
81,Intramuscular injection,522,1325634,2539.528736
12,Assessment of substance use (procedure),2906,1252486,431.000000
95,Medication Reconciliation (procedure),2284,1162840,509.124343
107,Percutaneous mechanical thrombectomy of portal...,57,1152998,20228.035088
14,Assessment using Morse Fall Scale (procedure),2422,1043882,431.000000

In [108]:
patient_procedures = (
    procedures_clean
    .groupby("PATIENT")
    .agg(
        Procedure_Count=("CODE", "count"),
        Procedure_Cost=("BASE_COST", "sum")
    )
    .reset_index()
)

patient_procedures.head()

                                PATIENT  Procedure_Count  Procedure_Cost
0  002bc307-2fff-04ba-161b-98cce123e226               11           12414
1  0034fe01-207f-275f-6b4b-821f7b0af044              156          541708
2  00abe029-00fa-a666-34f5-258a36978f6d               21           58619
3  010ff9c1-564b-6e32-09f4-29cb4224bba9                5           27319
4  01296e88-f6d9-1c18-cf91-87523325e034               96          884074

In [109]:
patient_procedures["Procedure_Count"].describe()

count     793.000000
mean       60.152585
std       125.363837
min         1.000000
25%         7.000000
50%        20.000000
75%        64.000000
max      1783.000000
Name: Procedure_Count, dtype: float64

In [110]:
encounters_clean["YEAR"] = (
    encounters_clean["START"].dt.year
)

encounters_clean["MONTH"] = (
    encounters_clean["START"].dt.month
)

encounters_clean["YEAR_MONTH"] = (
    encounters_clean["START"]
    .dt.to_period("M")
    .astype(str)
)

C:\Users\Olayinka\AppData\Local\Temp\ipykernel_14140\647032155.py:11: UserWarning: Converting to PeriodArray/Index representation will drop timezone information.
  .dt.to_period("M")

In [111]:
monthly_encounters = (
    encounters_clean
    .groupby("YEAR_MONTH")
    .size()
    .reset_index(name="Encounters")
)

monthly_encounters.head(15)

   YEAR_MONTH  Encounters
0     2011-01          86
1     2011-02          86
2     2011-03         129
3     2011-04         113
4     2011-05         131
5     2011-06         131
6     2011-07         124
7     2011-08         115
8     2011-09         124
9     2011-10          84
10    2011-11         100
11    2011-12         113
12    2012-01         116
13    2012-02         170
14    2012-03         183

In [112]:
annual_encounters = (
    encounters_clean
    .groupby("YEAR")
    .agg(
        Encounters=("Id", "count"),
        Total_Claim_Cost=("TOTAL_CLAIM_COST", "sum"),
        Average_Claim_Cost=("TOTAL_CLAIM_COST", "mean")
    )
    .reset_index()
)

annual_encounters

    YEAR  Encounters  Total_Claim_Cost  Average_Claim_Cost
0   2011        1336        4405936.73         3297.856834
1   2012        2106        9058314.10         4301.193780
2   2013        2495       10105272.87         4050.209567
3   2014        3885       12011662.17         3091.804934
4   2015        2469       10124652.89         4100.709959
5   2016        2451        8386701.12         3421.746683
6   2017        2360        9596894.47         4066.480708
7   2018        2292        8746818.37         3816.238381
8   2019        2228        8915338.78         4001.498555
9   2020        2519       10294077.96         4086.573227
10  2021        3530        9177232.00         2599.782436
11  2022         220         691474.06         3143.063909

In [113]:
procedures_clean["START"] = pd.to_datetime(
    procedures_clean["START"],
    errors="coerce"
)

procedures_clean["YEAR"] = (
    procedures_clean["START"].dt.year
)

annual_procedures = (
    procedures_clean
    .groupby("YEAR")
    .agg(
        Procedures=("CODE", "count"),
        Procedure_Cost=("BASE_COST", "sum")
    )
    .reset_index()
)

annual_procedures

    YEAR  Procedures  Procedure_Cost
0   2011        1184         2756770
1   2012        4456         9431106
2   2013        4998        10859501
3   2014        6292        12538073
4   2015        4656        10593719
5   2016        4143         8840739
6   2017        4585        10197041
7   2018        3880         9179212
8   2019        4378         9639011
9   2020        4451        11255330
10  2021        4410         9511924
11  2022         268          715285

In [114]:
duration_by_type = (
    encounters_clean
    .groupby("ENCOUNTERCLASS")
    .agg(
        Encounter_Count=("Id", "count"),
        Average_Duration_Min=("ENCOUNTER_DURATION_MIN", "mean"),
        Median_Duration_Min=("ENCOUNTER_DURATION_MIN", "median"),
        Total_Claim_Cost=("TOTAL_CLAIM_COST", "sum")
    )
    .reset_index()
)

duration_by_type

,ENCOUNTERCLASS,Encounter_Count,Average_Duration_Min,Median_Duration_Min,Total_Claim_Cost
0,ambulatory,12537,568.765058,15.0,36283440.84
1,emergency,2322,92.505319,60.0,10750051.53
2,inpatient,1135,2210.495154,1440.0,8809134.34
3,outpatient,6300,352.552317,15.0,14094967.12
4,urgentcare,3666,15.000000,15.0,23349349.96
5,wellness,1931,15.000000,15.0,8227431.73

Data quality/business rule observation: A small number of encounters have unusually long recorded durations. These may represent longitudinal or recurring follow-up records rather than continuous physical stays. Duration metrics should therefore be interpreted according to encounter class and clinical context.

In [115]:
print(encounters_clean.columns.tolist())

['Id', 'START', 'STOP', 'PATIENT', 'ORGANIZATION', 'PAYER', 'ENCOUNTERCLASS', 'CODE', 'DESCRIPTION', 'BASE_ENCOUNTER_COST', 'TOTAL_CLAIM_COST', 'PAYER_COVERAGE', 'REASONCODE', 'REASONDESCRIPTION', 'ENCOUNTER_DURATION_MIN', 'ENCOUNTER_DURATION_HOURS', 'AGE_AT_ENCOUNTER', 'AGE_GROUP', 'PATIENT_RESPONSIBILITY', 'YEAR', 'MONTH', 'YEAR_MONTH']

In [116]:
print(encounters_clean[["START", "STOP"]].head())

                      START                      STOP
0 2011-01-02 09:26:36+00:00 2011-01-02 12:58:36+00:00
1 2011-01-03 05:44:39+00:00 2011-01-03 06:01:42+00:00
2 2011-01-03 14:32:11+00:00 2011-01-03 14:47:11+00:00
3 2011-01-03 16:24:45+00:00 2011-01-03 16:39:45+00:00
4 2011-01-03 17:36:53+00:00 2011-01-03 17:51:53+00:00

In [117]:
# ============================================================
# STEP 4.5 — ENCOUNTER DURATION
# ============================================================

encounters_clean["START"] = pd.to_datetime(
    encounters_clean["START"],
    errors="coerce"
)

encounters_clean["STOP"] = pd.to_datetime(
    encounters_clean["STOP"],
    errors="coerce"
)

encounters_clean["DURATION_DAYS"] = (
    encounters_clean["STOP"] - encounters_clean["START"]
).dt.total_seconds() / (24 * 60 * 60)

print("DURATION_DAYS created successfully.")
print(encounters_clean["DURATION_DAYS"].describe())

DURATION_DAYS created successfully.
count    27891.000000
mean         0.302750
std         16.596818
min          0.010417
25%          0.010417
50%          0.010417
75%          0.036007
max       1872.083333
Name: DURATION_DAYS, dtype: float64

In [118]:
# ============================================================
# STEP 4.5 — ENCOUNTER DURATION IN DAYS
# ============================================================

encounters_clean["DURATION_DAYS"] = (
    encounters_clean["ENCOUNTER_DURATION_MIN"] / (60 * 24)
).round(2)

print("DURATION_DAYS created successfully.")

encounters_clean[
    ["Id", "START", "STOP", "ENCOUNTER_DURATION_MIN", "DURATION_DAYS"]
].head(10)

DURATION_DAYS created successfully.

,Id,START,STOP,ENCOUNTER_DURATION_MIN,DURATION_DAYS
0,32c84703-2481-49cd-d571-3899d5820253,2011-01-02 09:26:36+00:00,2011-01-02 12:58:36+00:00,212.00,0.15
1,c98059da-320a-c0a6-fced-c8815f3e3f39,2011-01-03 05:44:39+00:00,2011-01-03 06:01:42+00:00,17.05,0.01
2,4ad28a3a-2479-782b-f29c-d5b3f41a001e,2011-01-03 14:32:11+00:00,2011-01-03 14:47:11+00:00,15.00,0.01
3,c3f4da61-e4b4-21d5-587a-fbc89943bc19,2011-01-03 16:24:45+00:00,2011-01-03 16:39:45+00:00,15.00,0.01
4,a9183b4f-2572-72ea-54c2-b3cd038b4be7,2011-01-03 17:36:53+00:00,2011-01-03 17:51:53+00:00,15.00,0.01
5,c4923a74-3e40-8b0c-cf73-05b9c0390621,2011-01-03 19:08:16+00:00,2011-01-03 19:23:16+00:00,15.00,0.01
6,c140ed81-040e-8319-e860-f72b4738ed22,2011-01-03 22:39:50+00:00,2011-01-03 22:54:50+00:00,15.00,0.01
7,2cfd4ddd-ad13-fe1e-528b-15051cea2ec3,2011-01-04 14:49:55+00:00,2011-01-04 15:04:55+00:00,15.00,0.01
8,16bdc066-886f-34e1-38fa-afb85090b637,2011-01-04 15:13:10+00:00,2011-01-04 15:28:10+00:00,15.00,0.01
9,17966936-0878-f4db-128b-a43ae10d0878,2011-01-05 04:02:09+00:00,2011-01-05 04:17:09+00:00,15.00,0.01

In [119]:
print("Missing duration days:",
      encounters_clean["DURATION_DAYS"].isna().sum())

print("Negative duration days:",
      (encounters_clean["DURATION_DAYS"] < 0).sum())

print("\nDuration days statistics:")
print(encounters_clean["DURATION_DAYS"].describe())

Missing duration days: 0
Negative duration days: 0

Duration days statistics:
count    27891.000000
mean         0.302297
std         16.596792
min          0.010000
25%          0.010000
50%          0.010000
75%          0.040000
max       1872.080000
Name: DURATION_DAYS, dtype: float64

In [120]:
# ============================================================
# STEP 4.6 — LONG ENCOUNTER IDENTIFICATION
# ============================================================

long_encounters = (
    encounters_clean[
        encounters_clean["DURATION_DAYS"] > 7
    ]
    [
        [
            "Id",
            "PATIENT",
            "ENCOUNTERCLASS",
            "DESCRIPTION",
            "START",
            "STOP",
            "DURATION_DAYS"
        ]
    ]
    .sort_values(
        "DURATION_DAYS",
        ascending=False
    )
)

print("Long encounters (>7 days):", len(long_encounters))

long_encounters.head(20)

Long encounters (>7 days): 31

,Id,PATIENT,ENCOUNTERCLASS,DESCRIPTION,START,STOP,DURATION_DAYS
9704,fc2c2add-0b55-e300-5cea-8f43044eb330,5d47b9ac-3f37-f400-1747-c6c6f92130aa,ambulatory,Follow-up encounter (procedure),2014-12-17 11:49:08+00:00,2020-02-01 13:49:08+00:00,1872.08
7735,2cb41a50-819c-ef7e-87df-b5b47b2e01a1,09e0ec41-cd4c-50b2-b425-824013777beb,ambulatory,Follow-up encounter (procedure),2014-03-27 00:33:14+00:00,2019-03-13 15:33:14+00:00,1812.62
7805,7a19a260-e4a9-7b81-3f93-e07144d634d9,8885aba5-afce-9e3b-0c1d-a684a347b5fb,ambulatory,Follow-up encounter (procedure),2014-04-02 22:26:28+00:00,2015-07-02 13:44:57+00:00,455.64
6116,3cf29374-f91a-5877-9356-87792501d225,a12541db-140e-8189-070c-dc9f4815f40f,outpatient,Encounter for problem (procedure),2014-01-31 02:29:54+00:00,2015-04-22 02:29:54+00:00,446.00
6371,63b7c71f-23f5-32dc-b63a-cca7bf5625a2,6e8e0498-187a-d038-c7af-716b12e70455,outpatient,Encounter for problem (procedure),2014-02-06 02:17:34+00:00,2015-01-20 02:17:34+00:00,348.00
18343,4079872d-73da-3b52-5306-2a978c6f5c8c,54889029-0a1e-0b75-5980-1c091dd4bc0e,inpatient,Periodic reevaluation and management of health...,2018-07-18 23:56:20+00:00,2019-06-27 17:56:35+00:00,343.75
6380,110777dd-6aca-3c9c-7119-ab2494c0665e,0ec939a0-559c-7bc9-db9c-a7feae58634a,outpatient,Encounter for problem (procedure),2014-02-06 04:57:58+00:00,2015-01-13 04:57:58+00:00,341.00
7832,04df7388-7a70-3e99-c0fe-7f7ddd062931,ea9d6669-efc3-3c16-4f70-70cc1c1659d7,ambulatory,Follow-up encounter (procedure),2014-04-04 22:41:46+00:00,2015-01-31 13:54:32+00:00,301.63
6125,d0476a31-1524-f23f-fb79-290ecd6206aa,f6932663-d920-6e76-89e1-21a6b43cf03b,outpatient,Encounter for problem (procedure),2014-01-31 11:10:57+00:00,2014-06-25 11:10:57+00:00,145.00
6138,1123fed5-342e-f49b-4ab9-91f153b9e474,d40ba361-8192-a8e6-b75c-5def4758fe3f,outpatient,Encounter for problem (procedure),2014-01-31 20:39:04+00:00,2014-04-09 20:39:04+00:00,68.00
6332,dcc730d3-4d74-5e75-ae03-cd23c0ee742c,60d2d35e-bd32-36df-b8e0-b64a3494f0e8,outpatient,Encounter for problem (procedure),2014-02-05 08:41:28+00:00,2014-04-14 08:41:28+00:00,68.00
16504,0b29bad1-7b3c-2585-1b31-c3dd7a6ec36a,a96d5031-46d5-e3f6-ec67-81f8edd48aa8,inpatient,Periodic reevaluation and management of health...,2017-09-30 13:44:27+00:00,2017-11-25 13:44:27+00:00,56.00
6145,6053724d-e3b1-0449-402d-3090d3514389,f21a9c39-abd4-4e57-575d-83e1c29484da,outpatient,Encounter for problem (procedure),2014-01-31 23:35:27+00:00,2014-03-26 23:35:27+00:00,54.00
8980,9741be00-49a5-f25a-a59b-ea46ffbad229,77dedc66-369c-bb18-940d-0db841255ef7,ambulatory,Follow-up encounter (procedure),2014-09-14 10:42:36+00:00,2014-10-11 21:42:36+00:00,27.46
23048,6c108963-2fda-815b-3813-a424b3533127,01296e88-f6d9-1c18-cf91-87523325e034,emergency,Encounter for problem,2020-08-15 04:52:21+00:00,2020-09-08 17:52:21+00:00,24.54
5457,d5c42fa8-f110-b714-d89a-04ec57038a58,0226f105-2572-1c6f-15f0-1aa0438e40d0,inpatient,Encounter for symptom (procedure),2013-10-22 00:16:17+00:00,2013-11-14 00:16:17+00:00,23.00
14807,6fc6cbfc-ade5-c9ec-721c-4f71d9a1a815,2f6c035b-a11d-9373-89af-0cb2195592d2,emergency,Emergency room admission (procedure),2017-01-11 09:03:19+00:00,2017-01-27 09:03:19+00:00,16.00
24226,96f41ac9-60c0-d035-249b-ea9f68dfb7da,2999ffe8-ab8a-3afa-ab9e-aa40fa162e8c,inpatient,Hospital admission for isolation (procedure),2021-01-12 14:24:46+00:00,2021-01-25 15:06:45+00:00,13.03
24155,49a58342-2bed-0dec-5581-f12474408881,7811ad1e-3baf-5d00-6664-01c7396f67c9,inpatient,Hospital admission for isolation (procedure),2021-01-03 03:22:46+00:00,2021-01-16 04:02:42+00:00,13.03
23972,d12cbc08-c639-0917-6250-66eca2e6995f,97c4cfee-e860-e908-1797-8da4dc241ec4,inpatient,Hospital admission for isolation (procedure),2020-12-12 19:05:25+00:00,2020-12-25 19:32:34+00:00,13.02

In [121]:
long_encounters["ENCOUNTERCLASS"].value_counts()

ENCOUNTERCLASS
inpatient     17
outpatient     7
ambulatory     5
emergency      2
Name: count, dtype: int64

In [122]:
procedures_per_encounter = (
    procedures_clean
    .groupby("ENCOUNTER")
    .size()
    .reset_index(name="Procedure_Count")
)

procedures_per_encounter["Procedure_Count"].describe()

count    14670.000000
mean         3.251602
std          5.161026
min          1.000000
25%          1.000000
50%          2.000000
75%          5.000000
max        186.000000
Name: Procedure_Count, dtype: float64

In [123]:
procedures_per_encounter.head()

                              ENCOUNTER  Procedure_Count
0  000cc8f4-f2c7-5cf3-419d-13be23d959da                6
1  0011d269-53cb-06c9-e0df-10f3d01d8c47                8
2  00169f6a-632c-357a-3cb2-a91a71c48f11                1
3  0019dbc5-e696-1444-d988-6ae5907580a4                2
4  001fb5d9-0c4a-3e8f-bd27-5c8317674632                1

In [124]:
procedure_encounter_check = procedures_clean[
    ~procedures_clean["ENCOUNTER"].isin(
        encounters_clean["Id"]
    )
]

print(
    "Procedures without valid encounters:",
    len(procedure_encounter_check)
)

Procedures without valid encounters: 0

In [125]:
patients_without_encounters = patients_clean[
    ~patients_clean["Id"].isin(
        encounters_clean["PATIENT"]
    )
]

print(
    "Patients with no encounters:",
    len(patients_without_encounters)
)

Patients with no encounters: 0

In [126]:
patients_without_encounters[
    [
        "Id",
        "BIRTHDATE",
        "GENDER",
        "RACE",
        "ETHNICITY"
    ]
].head()

Empty DataFrame
Columns: [Id, BIRTHDATE, GENDER, RACE, ETHNICITY]
Index: []

In [127]:
eda_findings = pd.DataFrame({
    "Area": [
        "Patient Population",
        "Encounter Utilization",
        "Procedure Utilization",
        "Healthcare Costs",
        "Payer Coverage",
        "Encounter Duration",
        "Data Quality"
    ],
    "Finding": [
        "To be completed after demographic analysis",
        "To be completed after encounter analysis",
        "To be completed after procedure analysis",
        "To be completed after cost analysis",
        "To be completed after payer analysis",
        "A small number of encounters have unusually long recorded durations",
        "Referential integrity checks passed"
    ],
    "Business_Question": [
        "Which patient groups account for the largest healthcare utilization?",
        "Which encounter types drive healthcare activity?",
        "Which procedures are most frequent and most costly?",
        "Which encounter types and patient groups drive costs?",
        "Which payers provide the highest coverage?",
        "Do unusually long durations reflect specific encounter types?",
        "Can the dataset be trusted for relational analysis?"
    ]
})

eda_findings

,Area,Finding,Business_Question
0,Patient Population,To be completed after demographic analysis,Which patient groups account for the largest h...
1,Encounter Utilization,To be completed after encounter analysis,Which encounter types drive healthcare activity?
2,Procedure Utilization,To be completed after procedure analysis,Which procedures are most frequent and most co...
3,Healthcare Costs,To be completed after cost analysis,Which encounter types and patient groups drive...
4,Payer Coverage,To be completed after payer analysis,Which payers provide the highest coverage?
5,Encounter Duration,A small number of encounters have unusually lo...,Do unusually long durations reflect specific e...
6,Data Quality,Referential integrity checks passed,Can the dataset be trusted for relational anal...

In [128]:
# ============================================================
# STEP 4.5 — ENCOUNTER DURATION OUTLIER VALIDATION
# ============================================================

duration_outliers = (
    encounters_clean[
        encounters_clean["DURATION_DAYS"] > 7
    ]
    [
        [
            "Id",
            "PATIENT",
            "ENCOUNTERCLASS",
            "DESCRIPTION",
            "START",
            "STOP",
            "DURATION_DAYS",
            "TOTAL_CLAIM_COST",
            "PAYER_COVERAGE",
            "PATIENT_RESPONSIBILITY"
        ]
    ]
    .sort_values(
        "DURATION_DAYS",
        ascending=False
    )
)

print("Long encounters (>7 days):", len(duration_outliers))

duration_outliers.head(20)

Long encounters (>7 days): 31

,Id,PATIENT,ENCOUNTERCLASS,DESCRIPTION,START,STOP,DURATION_DAYS,TOTAL_CLAIM_COST,PAYER_COVERAGE,PATIENT_RESPONSIBILITY
9704,fc2c2add-0b55-e300-5cea-8f43044eb330,5d47b9ac-3f37-f400-1747-c6c6f92130aa,ambulatory,Follow-up encounter (procedure),2014-12-17 11:49:08+00:00,2020-02-01 13:49:08+00:00,1872.08,85.55,0.00,85.55
7735,2cb41a50-819c-ef7e-87df-b5b47b2e01a1,09e0ec41-cd4c-50b2-b425-824013777beb,ambulatory,Follow-up encounter (procedure),2014-03-27 00:33:14+00:00,2019-03-13 15:33:14+00:00,1812.62,85.55,7.91,77.64
7805,7a19a260-e4a9-7b81-3f93-e07144d634d9,8885aba5-afce-9e3b-0c1d-a684a347b5fb,ambulatory,Follow-up encounter (procedure),2014-04-02 22:26:28+00:00,2015-07-02 13:44:57+00:00,455.64,85.55,24.27,61.28
6116,3cf29374-f91a-5877-9356-87792501d225,a12541db-140e-8189-070c-dc9f4815f40f,outpatient,Encounter for problem (procedure),2014-01-31 02:29:54+00:00,2015-04-22 02:29:54+00:00,446.00,85.55,36.44,49.11
6371,63b7c71f-23f5-32dc-b63a-cca7bf5625a2,6e8e0498-187a-d038-c7af-716b12e70455,outpatient,Encounter for problem (procedure),2014-02-06 02:17:34+00:00,2015-01-20 02:17:34+00:00,348.00,85.55,0.00,85.55
18343,4079872d-73da-3b52-5306-2a978c6f5c8c,54889029-0a1e-0b75-5980-1c091dd4bc0e,inpatient,Periodic reevaluation and management of health...,2018-07-18 23:56:20+00:00,2019-06-27 17:56:35+00:00,343.75,7093.85,5643.08,1450.77
6380,110777dd-6aca-3c9c-7119-ab2494c0665e,0ec939a0-559c-7bc9-db9c-a7feae58634a,outpatient,Encounter for problem (procedure),2014-02-06 04:57:58+00:00,2015-01-13 04:57:58+00:00,341.00,85.55,0.00,85.55
7832,04df7388-7a70-3e99-c0fe-7f7ddd062931,ea9d6669-efc3-3c16-4f70-70cc1c1659d7,ambulatory,Follow-up encounter (procedure),2014-04-04 22:41:46+00:00,2015-01-31 13:54:32+00:00,301.63,85.55,0.00,85.55
6125,d0476a31-1524-f23f-fb79-290ecd6206aa,f6932663-d920-6e76-89e1-21a6b43cf03b,outpatient,Encounter for problem (procedure),2014-01-31 11:10:57+00:00,2014-06-25 11:10:57+00:00,145.00,85.55,0.00,85.55
6138,1123fed5-342e-f49b-4ab9-91f153b9e474,d40ba361-8192-a8e6-b75c-5def4758fe3f,outpatient,Encounter for problem (procedure),2014-01-31 20:39:04+00:00,2014-04-09 20:39:04+00:00,68.00,85.55,36.44,49.11
6332,dcc730d3-4d74-5e75-ae03-cd23c0ee742c,60d2d35e-bd32-36df-b8e0-b64a3494f0e8,outpatient,Encounter for problem (procedure),2014-02-05 08:41:28+00:00,2014-04-14 08:41:28+00:00,68.00,85.55,0.00,85.55
16504,0b29bad1-7b3c-2585-1b31-c3dd7a6ec36a,a96d5031-46d5-e3f6-ec67-81f8edd48aa8,inpatient,Periodic reevaluation and management of health...,2017-09-30 13:44:27+00:00,2017-11-25 13:44:27+00:00,56.00,6102.44,0.00,6102.44
6145,6053724d-e3b1-0449-402d-3090d3514389,f21a9c39-abd4-4e57-575d-83e1c29484da,outpatient,Encounter for problem (procedure),2014-01-31 23:35:27+00:00,2014-03-26 23:35:27+00:00,54.00,85.55,0.00,85.55
8980,9741be00-49a5-f25a-a59b-ea46ffbad229,77dedc66-369c-bb18-940d-0db841255ef7,ambulatory,Follow-up encounter (procedure),2014-09-14 10:42:36+00:00,2014-10-11 21:42:36+00:00,27.46,85.55,7.91,77.64
23048,6c108963-2fda-815b-3813-a424b3533127,01296e88-f6d9-1c18-cf91-87523325e034,emergency,Encounter for problem,2020-08-15 04:52:21+00:00,2020-09-08 17:52:21+00:00,24.54,641882.70,0.00,641882.70
5457,d5c42fa8-f110-b714-d89a-04ec57038a58,0226f105-2572-1c6f-15f0-1aa0438e40d0,inpatient,Encounter for symptom (procedure),2013-10-22 00:16:17+00:00,2013-11-14 00:16:17+00:00,23.00,7664.97,0.00,7664.97
14807,6fc6cbfc-ade5-c9ec-721c-4f71d9a1a815,2f6c035b-a11d-9373-89af-0cb2195592d2,emergency,Emergency room admission (procedure),2017-01-11 09:03:19+00:00,2017-01-27 09:03:19+00:00,16.00,1036.94,0.00,1036.94
24226,96f41ac9-60c0-d035-249b-ea9f68dfb7da,2999ffe8-ab8a-3afa-ab9e-aa40fa162e8c,inpatient,Hospital admission for isolation (procedure),2021-01-12 14:24:46+00:00,2021-01-25 15:06:45+00:00,13.03,22821.65,18216.54,4605.11
24155,49a58342-2bed-0dec-5581-f12474408881,7811ad1e-3baf-5d00-6664-01c7396f67c9,inpatient,Hospital admission for isolation (procedure),2021-01-03 03:22:46+00:00,2021-01-16 04:02:42+00:00,13.03,21146.49,0.00,21146.49
23972,d12cbc08-c639-0917-6250-66eca2e6995f,97c4cfee-e860-e908-1797-8da4dc241ec4,inpatient,Hospital admission for isolation (procedure),2020-12-12 19:05:25+00:00,2020-12-25 19:32:34+00:00,13.02,25195.93,20084.51,5111.42

In [129]:
# ============================================================
# LONG ENCOUNTERS BY ENCOUNTER TYPE
# ============================================================

long_duration_by_type = (
    duration_outliers
    .groupby("ENCOUNTERCLASS")
    .agg(
        Long_Encounter_Count=("Id", "count"),
        Average_Duration_Days=("DURATION_DAYS", "mean"),
        Maximum_Duration_Days=("DURATION_DAYS", "max"),
        Total_Claim_Cost=("TOTAL_CLAIM_COST", "sum")
    )
    .sort_values(
        "Long_Encounter_Count",
        ascending=False
    )
)

long_duration_by_type

,Long_Encounter_Count,Average_Duration_Days,Maximum_Duration_Days,Total_Claim_Cost
ENCOUNTERCLASS,,,,
inpatient,17,33.624118,343.75,610676.76
outpatient,7,210.000000,446.00,598.85
ambulatory,5,893.886000,1872.08,427.75
emergency,2,20.270000,24.54,642919.64

In [130]:
# ============================================================
# DURATION OUTLIER SEVERITY
# ============================================================

duration_outliers["DURATION_CATEGORY"] = pd.cut(
    duration_outliers["DURATION_DAYS"],
    bins=[0, 1, 7, 30, 90, 365, float("inf")],
    labels=[
        "≤1 day",
        "2–7 days",
        "8–30 days",
        "31–90 days",
        "91–365 days",
        ">365 days"
    ],
    include_lowest=True
)

duration_outlier_summary = (
    duration_outliers["DURATION_CATEGORY"]
    .value_counts()
    .sort_index()
)

duration_outlier_summary

DURATION_CATEGORY
≤1 day          0
2–7 days        0
8–30 days      18
31–90 days      4
91–365 days     5
>365 days       4
Name: count, dtype: int64

In [131]:
# ============================================================
# STEP 4.6 — ENCOUNTER DURATION QUALITY FLAG
# ============================================================

encounters_clean["DURATION_FLAG"] = pd.cut(
    encounters_clean["DURATION_DAYS"],
    bins=[
        -float("inf"),
        1,
        7,
        30,
        90,
        365,
        float("inf")
    ],
    labels=[
        "Normal: ≤1 day",
        "Extended: 2–7 days",
        "Long: 8–30 days",
        "Very Long: 31–90 days",
        "Extreme: 91–365 days",
        "Extreme: >365 days"
    ]
)

duration_flag_summary = (
    encounters_clean["DURATION_FLAG"]
    .value_counts()
    .sort_index()
)

duration_flag_summary

DURATION_FLAG
Normal: ≤1 day           27816
Extended: 2–7 days          44
Long: 8–30 days             18
Very Long: 31–90 days        4
Extreme: 91–365 days         5
Extreme: >365 days           4
Name: count, dtype: int64

In [132]:
# ============================================================
# DURATION FLAG PERCENTAGES
# ============================================================

duration_flag_percentages = (
    encounters_clean["DURATION_FLAG"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
    .sort_index()
)

duration_flag_percentages

DURATION_FLAG
Normal: ≤1 day           99.73
Extended: 2–7 days        0.16
Long: 8–30 days           0.06
Very Long: 31–90 days     0.01
Extreme: 91–365 days      0.02
Extreme: >365 days        0.01
Name: proportion, dtype: float64

In [133]:
# ============================================================
# STEP 4.7 — DURATION PROFILE BY ENCOUNTER TYPE
# ============================================================

duration_profile = (
    encounters_clean
    .groupby("ENCOUNTERCLASS")
    .agg(
        Encounter_Count=("Id", "count"),
        Average_Duration_Days=("DURATION_DAYS", "mean"),
        Median_Duration_Days=("DURATION_DAYS", "median"),
        P95_Duration_Days=(
            "DURATION_DAYS",
            lambda x: x.quantile(0.95)
        ),
        Maximum_Duration_Days=("DURATION_DAYS", "max"),
        Total_Claim_Cost=("TOTAL_CLAIM_COST", "sum")
    )
    .sort_values(
        "Median_Duration_Days",
        ascending=False
    )
)

duration_profile.round(2)

,Encounter_Count,Average_Duration_Days,Median_Duration_Days,P95_Duration_Days,Maximum_Duration_Days,Total_Claim_Cost
ENCOUNTERCLASS,,,,,,
inpatient,1135,1.54,1.00,1.03,343.75,8809134.34
emergency,2322,0.06,0.04,0.04,24.54,10750051.53
ambulatory,12537,0.39,0.01,0.15,1872.08,36283440.84
outpatient,6300,0.24,0.01,0.01,446.00,14094967.12
urgentcare,3666,0.01,0.01,0.01,0.01,23349349.96
wellness,1931,0.01,0.01,0.01,0.01,8227431.73

In [134]:
# ============================================================
# STEP 4.8 — DATA QUALITY SUMMARY
# ============================================================

data_quality_summary = pd.DataFrame({
    "Check": [
        "Patients",
        "Encounters",
        "Procedures",
        "Payers",
        "Organizations",
        "Missing age at encounter",
        "Negative age at encounter",
        "Missing age groups",
        "Patients with death dates",
        "Negative age at death",
        "Long encounters >7 days",
        "Procedures without valid encounters",
        "Patients with no encounters",
        "Negative patient responsibility"
    ],
    "Result": [
        len(patients_clean),
        len(encounters_clean),
        len(procedures_clean),
        len(payers_clean),
        len(organizations_clean),
        encounters_clean["AGE_AT_ENCOUNTER"].isna().sum(),
        (encounters_clean["AGE_AT_ENCOUNTER"] < 0).sum(),
        encounters_clean["AGE_GROUP"].isna().sum(),
        patients_clean["DEATHDATE"].notna().sum(),
        (patients_clean["AGE_AT_DEATH"] < 0).sum(),
        (encounters_clean["DURATION_DAYS"] > 7).sum(),
        0,
        0,
        (encounters_clean["PATIENT_RESPONSIBILITY"] < 0).sum()
    ]
})

data_quality_summary

                                  Check  Result
0                              Patients     974
1                            Encounters   27891
2                            Procedures   47701
3                                Payers      10
4                         Organizations       1
5              Missing age at encounter       0
6             Negative age at encounter       0
7                    Missing age groups       0
8             Patients with death dates     154
9                 Negative age at death       0
10              Long encounters >7 days      31
11  Procedures without valid encounters       0
12          Patients with no encounters       0
13      Negative patient responsibility       0

In [135]:
# ============================================================
# STEP 4.13 — PATIENT-LEVEL CLINICAL UTILIZATION
# ============================================================

patient_utilization = (
    encounters_clean
    .groupby("PATIENT")
    .agg(
        Encounter_Count=("Id", "count"),
        Total_Encounter_Cost=("TOTAL_CLAIM_COST", "sum"),
        Total_Payer_Coverage=("PAYER_COVERAGE", "sum"),
        Total_Patient_Responsibility=("PATIENT_RESPONSIBILITY", "sum"),
        Inpatient_Encounters=(
            "ENCOUNTERCLASS",
            lambda x: (x == "inpatient").sum()
        ),
        Emergency_Encounters=(
            "ENCOUNTERCLASS",
            lambda x: (x == "emergency").sum()
        ),
        Outpatient_Encounters=(
            "ENCOUNTERCLASS",
            lambda x: (x == "outpatient").sum()
        ),
        Ambulatory_Encounters=(
            "ENCOUNTERCLASS",
            lambda x: (x == "ambulatory").sum()
        ),
        UrgentCare_Encounters=(
            "ENCOUNTERCLASS",
            lambda x: (x == "urgentcare").sum()
        ),
        Wellness_Encounters=(
            "ENCOUNTERCLASS",
            lambda x: (x == "wellness").sum()
        )
    )
    .reset_index()
)

patient_utilization.head()

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters
0,002bc307-2fff-04ba-161b-98cce123e226,46,13742.67,9509.86,4232.81,2,3,38,3,0,0
1,0034fe01-207f-275f-6b4b-821f7b0af044,75,548667.37,5494.56,543172.81,4,6,33,32,0,0
2,00abe029-00fa-a666-34f5-258a36978f6d,22,48334.27,6384.67,41949.60,0,1,5,16,0,0
3,010ff9c1-564b-6e32-09f4-29cb4224bba9,4,26367.50,19475.04,6892.46,0,0,1,3,0,0
4,01274098-150f-8211-6150-29f2a2da266c,1,0.00,0.00,0.00,1,0,0,0,0,0

In [136]:
# ============================================================
# STEP 4.13.1 — HIGHEST-UTILIZATION PATIENTS
# ============================================================

high_utilization_patients = (
    patient_utilization[
        [
            "PATIENT",
            "Encounter_Count",
            "Inpatient_Encounters",
            "Emergency_Encounters",
            "Outpatient_Encounters",
            "Ambulatory_Encounters",
            "UrgentCare_Encounters",
            "Wellness_Encounters",
            "Total_Encounter_Cost",
            "Total_Patient_Responsibility"
        ]
    ]
    .sort_values(
        "Encounter_Count",
        ascending=False
    )
)

high_utilization_patients.head(20)

,PATIENT,Encounter_Count,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters,Total_Encounter_Cost,Total_Patient_Responsibility
85,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,0,0,77,1304,0,0,2437415.31,2437415.31
371,5e055638-0dad-dfd5-005d-1e74b6fd29ac,887,0,17,92,778,0,0,844913.74,216384.12
240,3de74169-7f67-9304-91d4-757e0f3a14d2,877,0,49,35,786,0,7,819279.19,819279.19
245,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,0,172,48,3,213,11,9932262.99,9932262.99
370,5dcb295d-92df-a147-ebcc-aa49b6262830,441,0,0,5,436,0,0,105080.78,60909.23
275,442dc617-c7f2-0513-15cd-c35c4efdba73,392,0,77,83,13,208,11,156858.67,133616.68
694,b4ab9ab3-f52a-751e-a990-3bd5654d5870,383,0,79,90,5,198,11,124858.48,83721.84
600,9b8ae606-5059-b3a6-19c7-c812901898bb,364,0,144,70,150,0,0,187907.26,54146.63
693,b4671e80-7e87-9260-ca31-6a9397d465d1,296,0,19,77,14,176,10,65245.84,24912.64
973,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,0,0,72,2,206,11,6356665.66,5511431.97
224,381e16cd-86c8-d369-cd76-2dd9e0b5faf5,268,0,200,50,7,0,11,128142.11,37655.75
685,b17ffd11-c8c2-28aa-0c26-8ddc6bc5957d,246,0,181,0,54,0,11,109461.36,31800.45
832,dabb67a9-bc4b-bc40-696e-65546a548d39,239,3,0,0,230,0,6,61730.59,19835.16
631,a31f5105-476f-b129-fb9a-514cf45a34ac,232,0,133,75,13,0,11,110636.64,37957.36
844,df607b64-3d5e-5795-1646-edd2ccf55192,217,0,0,0,0,217,0,31891.86,29416.56
839,de60a9e4-1334-6078-c1f1-e5083bb20361,210,0,9,64,6,120,11,60363.48,31478.69
393,6443e813-1b9b-620c-f7de-af77f9d02733,197,0,0,0,0,197,0,28768.26,12058.44
436,71da4401-2034-80cb-d797-ad90cee5649e,188,0,4,71,26,87,0,180967.41,180967.41
409,6a377869-21cd-94d2-395d-155b999f4eac,186,0,0,0,0,186,0,27879.88,24466.18
486,7c96fd5c-ae3d-308a-a9ee-948ab47860f9,184,0,6,75,11,92,0,54681.10,40919.30

In [137]:
print("Total patients:", len(patient_utilization))
print("Average encounters per patient:",
      round(patient_utilization["Encounter_Count"].mean(), 2))
print("Median encounters per patient:",
      patient_utilization["Encounter_Count"].median())
print("Maximum encounters for one patient:",
      patient_utilization["Encounter_Count"].max())

Total patients: 974
Average encounters per patient: 28.64
Median encounters per patient: 14.0
Maximum encounters for one patient: 1381

In [138]:
# ============================================================
# STEP 4.13.2 — UTILIZATION CONCENTRATION
# ============================================================

total_encounters = patient_utilization["Encounter_Count"].sum()

patient_utilization_ranked = (
    patient_utilization
    .sort_values("Encounter_Count", ascending=False)
    .reset_index(drop=True)
)

concentration_results = []

for pct in [0.01, 0.05, 0.10, 0.25]:
    
    n_patients = max(1, round(len(patient_utilization_ranked) * pct))
    
    top_encounters = (
        patient_utilization_ranked
        .head(n_patients)["Encounter_Count"]
        .sum()
    )
    
    encounter_share = (
        top_encounters / total_encounters
    ) * 100
    
    concentration_results.append({
        "Patient_Segment": f"Top {pct:.0%}",
        "Patients": n_patients,
        "Encounters": top_encounters,
        "Encounter_Share_Percentage": round(encounter_share, 2)
    })

utilization_concentration = pd.DataFrame(
    concentration_results
)

utilization_concentration

  Patient_Segment  Patients  Encounters  Encounter_Share_Percentage
0          Top 1%        10        5759                       20.65
1          Top 5%        49       11562                       41.45
2         Top 10%        97       14819                       53.13
3         Top 25%       244       20418                       73.21

In [139]:
print("Total encounters:", total_encounters)
print("Total patients:", len(patient_utilization))

Total encounters: 27891
Total patients: 974

In [140]:
# ============================================================
# STEP 4.13.3 — CLINICAL UTILIZATION INTENSITY
# ============================================================

patient_utilization["High_Acuity_Encounters"] = (
    patient_utilization["Inpatient_Encounters"]
    + patient_utilization["Emergency_Encounters"]
)

patient_utilization["Emergency_Rate"] = (
    patient_utilization["Emergency_Encounters"]
    / patient_utilization["Encounter_Count"]
    * 100
).round(2)

patient_utilization["Inpatient_Rate"] = (
    patient_utilization["Inpatient_Encounters"]
    / patient_utilization["Encounter_Count"]
    * 100
).round(2)

patient_utilization["High_Acuity_Rate"] = (
    patient_utilization["High_Acuity_Encounters"]
    / patient_utilization["Encounter_Count"]
    * 100
).round(2)

patient_utilization[
    [
        "PATIENT",
        "Encounter_Count",
        "Inpatient_Encounters",
        "Emergency_Encounters",
        "High_Acuity_Encounters",
        "Emergency_Rate",
        "Inpatient_Rate",
        "High_Acuity_Rate"
    ]
].sort_values(
    "High_Acuity_Rate",
    ascending=False
).head(20)

,PATIENT,Encounter_Count,Inpatient_Encounters,Emergency_Encounters,High_Acuity_Encounters,Emergency_Rate,Inpatient_Rate,High_Acuity_Rate
836,dccaefe2-518c-a083-d4ab-cea270ce521d,34,0,34,34,100.0,0.0,100.0
893,eadeadde-1b80-76cc-6558-2b5b511be15a,1,0,1,1,100.0,0.0,100.0
947,f95b336a-ec12-455f-b118-7c7ccc965806,1,0,1,1,100.0,0.0,100.0
51,0ecff71d-c81d-3bef-9769-eba85ea6c82a,2,0,2,2,100.0,0.0,100.0
691,b3089b6e-7e37-1385-3bb9-566694b36c1b,1,0,1,1,100.0,0.0,100.0
641,a6997da1-705f-96f8-909b-c421ad97f928,1,0,1,1,100.0,0.0,100.0
636,a59dbbd5-98e9-d341-9ed2-c01010910165,1,0,1,1,100.0,0.0,100.0
774,ca46c770-710c-6cfc-b02f-152f7d6a9de0,2,0,2,2,100.0,0.0,100.0
101,1a3939a9-e4f0-2a02-7697-8ae70501501b,3,0,3,3,100.0,0.0,100.0
107,1bfeb285-817e-4eda-6fbb-609706127115,3,0,3,3,100.0,0.0,100.0
649,a74f1065-3d40-3806-48b1-53d1a8ec72a0,5,0,5,5,100.0,0.0,100.0
92,187dd60c-abb1-c51d-c8b4-f86c06d4e34d,2,0,2,2,100.0,0.0,100.0
785,cea45305-4183-2e9b-f4c8-37220071f61d,1,0,1,1,100.0,0.0,100.0
56,103d9313-a3f2-ce7f-c7c4-613dd9d51b3b,1,0,1,1,100.0,0.0,100.0
804,d3212224-2a5f-6a90-e111-4de13c97882f,2,0,2,2,100.0,0.0,100.0
429,6f54d177-0d59-257b-8cd8-96d7c2254a04,2,0,2,2,100.0,0.0,100.0
427,6e5ae27c-8038-7988-e2c0-25a103f01bfa,1,0,1,1,100.0,0.0,100.0
598,9b7cfa36-1dda-ce55-7c2a-a9a332a5777b,1,0,1,1,100.0,0.0,100.0
16,050a0341-c954-2856-b3a6-580f8a3aaf84,2,0,2,2,100.0,0.0,100.0
391,63ebbeb6-3160-da00-76a3-11888839703a,1,1,0,1,0.0,100.0,100.0

In [141]:
print(
    "Patients with at least one high-acuity encounter:",
    (
        patient_utilization["High_Acuity_Encounters"] > 0
    ).sum()
)

print(
    "Total high-acuity encounters:",
    patient_utilization["High_Acuity_Encounters"].sum()
)

print(
    "Overall high-acuity encounter rate:",
    round(
        patient_utilization["High_Acuity_Encounters"].sum()
        / patient_utilization["Encounter_Count"].sum()
        * 100,
        2
    ),
    "%"
)

Patients with at least one high-acuity encounter: 522
Total high-acuity encounters: 3457
Overall high-acuity encounter rate: 12.39 %

In [142]:
top_cost_patients = (
    patient_utilization
    [
        [
            "PATIENT",
            "Encounter_Count",
            "Total_Encounter_Cost",
            "Total_Payer_Coverage",
            "Total_Patient_Responsibility",
            "Inpatient_Encounters",
            "Emergency_Encounters",
            "Outpatient_Encounters",
            "Ambulatory_Encounters",
            "UrgentCare_Encounters",
            "Wellness_Encounters"
        ]
    ]
    .sort_values(
        "Total_Encounter_Cost",
        ascending=False
    )
    .head(20)
)

top_cost_patients

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters
245,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,9932262.99,0.00,9932262.99,0,172,48,3,213,11
973,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,6356665.66,845233.69,5511431.97,0,0,72,2,206,11
647,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,3014121.02,0.00,3014121.02,0,6,0,15,121,0
174,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,2699823.10,0.00,2699823.10,0,0,0,0,120,0
85,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,2437415.31,0.00,2437415.31,0,0,77,1304,0,0
900,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,2090033.12,0.00,2090033.12,0,0,0,0,94,0
221,37448778-ee2f-f420-1dc0-cb6b5e147025,53,1206558.16,0.00,1206558.16,0,0,0,0,53,0
970,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,1181185.96,0.00,1181185.96,0,4,12,90,0,0
9,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,1127635.83,0.00,1127635.83,52,16,65,36,0,11
70,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,1030983.91,54044.35,976939.56,0,0,99,1,0,11
555,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,1024237.46,397776.45,626461.01,63,3,43,14,0,9
406,6961609b-1268-6292-9c09-90355f9e73a9,51,1002661.70,347176.99,655484.71,0,0,0,0,51,0
444,7412b008-76f9-b713-c514-2a5d82e3b39e,59,983828.37,0.00,983828.37,54,1,4,0,0,0
5,01296e88-f6d9-1c18-cf91-87523325e034,35,882324.24,0.00,882324.24,1,2,9,23,0,0
879,e7eaf3df-a981-d555-12d6-fdd50fa2631e,66,863712.20,152955.97,710756.23,48,2,4,3,1,8
371,5e055638-0dad-dfd5-005d-1e74b6fd29ac,887,844913.74,628529.62,216384.12,0,17,92,778,0,0
240,3de74169-7f67-9304-91d4-757e0f3a14d2,877,819279.19,0.00,819279.19,0,49,35,786,0,7
768,c83e8f1b-8f35-5855-0d38-6ea6509ec619,38,784682.44,626448.92,158233.52,0,0,0,0,38,0
337,5427845a-82ab-b6c9-e70b-aeb672ddd5d7,149,707094.17,560859.04,146235.13,0,0,0,0,149,0
294,49bc1d54-ed70-7ec5-02cb-76c178292427,42,704403.97,559834.49,144569.48,27,0,5,3,4,3

In [143]:
# Define high-utilization and high-cost thresholds

high_utilization_threshold = patient_utilization["Encounter_Count"].quantile(0.90)

high_cost_threshold = patient_utilization["Total_Encounter_Cost"].quantile(0.90)

print("High-utilization threshold:", high_utilization_threshold)
print("High-cost threshold:", high_cost_threshold)

High-utilization threshold: 54.700000000000045
High-cost threshold: 241747.92799999999

In [144]:
high_util_high_cost = (
    patient_utilization[
        (patient_utilization["Encounter_Count"] > high_utilization_threshold) &
        (patient_utilization["Total_Encounter_Cost"] > high_cost_threshold)
    ]
    [
        [
            "PATIENT",
            "Encounter_Count",
            "Total_Encounter_Cost",
            "Total_Payer_Coverage",
            "Total_Patient_Responsibility",
            "Inpatient_Encounters",
            "Emergency_Encounters",
            "Outpatient_Encounters",
            "Ambulatory_Encounters",
            "UrgentCare_Encounters",
            "Wellness_Encounters"
        ]
    ]
    .sort_values(
        ["Total_Encounter_Cost", "Encounter_Count"],
        ascending=False
    )
)

print("High-utilization + high-cost patients:", len(high_util_high_cost))

high_util_high_cost

High-utilization + high-cost patients: 36

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters
245,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,9932262.99,0.00,9932262.99,0,172,48,3,213,11
973,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,6356665.66,845233.69,5511431.97,0,0,72,2,206,11
647,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,3014121.02,0.00,3014121.02,0,6,0,15,121,0
174,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,2699823.10,0.00,2699823.10,0,0,0,0,120,0
85,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,2437415.31,0.00,2437415.31,0,0,77,1304,0,0
900,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,2090033.12,0.00,2090033.12,0,0,0,0,94,0
970,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,1181185.96,0.00,1181185.96,0,4,12,90,0,0
9,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,1127635.83,0.00,1127635.83,52,16,65,36,0,11
70,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,1030983.91,54044.35,976939.56,0,0,99,1,0,11
555,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,1024237.46,397776.45,626461.01,63,3,43,14,0,9
444,7412b008-76f9-b713-c514-2a5d82e3b39e,59,983828.37,0.00,983828.37,54,1,4,0,0,0
879,e7eaf3df-a981-d555-12d6-fdd50fa2631e,66,863712.20,152955.97,710756.23,48,2,4,3,1,8
371,5e055638-0dad-dfd5-005d-1e74b6fd29ac,887,844913.74,628529.62,216384.12,0,17,92,778,0,0
240,3de74169-7f67-9304-91d4-757e0f3a14d2,877,819279.19,0.00,819279.19,0,49,35,786,0,7
337,5427845a-82ab-b6c9-e70b-aeb672ddd5d7,149,707094.17,560859.04,146235.13,0,0,0,0,149,0
652,a80b1160-93f0-db7e-9f23-04ea6fdddfaf,59,636438.70,0.00,636438.70,53,0,1,0,0,5
491,7f0dc5c3-f35c-df5b-8564-95aa38b575d6,83,625019.99,352791.27,272228.72,1,4,16,62,0,0
972,ff1b3c26-53a6-4590-ce79-a3f7269274ea,72,616543.65,16531.38,600012.27,0,3,22,37,0,10
564,9279705f-2e5c-2792-ae20-7a77b5b04015,67,598712.31,350771.01,247941.30,0,3,7,57,0,0
682,b0c95bfd-adc4-8910-a75d-e208879c975d,96,580593.75,457700.11,122893.64,0,8,67,11,0,10
870,e54023a5-ae9a-fea9-3ad3-08989ea5b5aa,57,580149.36,0.00,580149.36,0,3,20,34,0,0
229,394f3e43-784c-b938-adb6-4b69efd46bbf,63,567891.96,23888.10,544003.86,1,4,16,42,0,0
163,283af64b-5b12-f971-6129-f638491a4a5b,55,563662.84,447003.17,116659.67,35,2,3,7,0,8
1,0034fe01-207f-275f-6b4b-821f7b0af044,75,548667.37,5494.56,543172.81,4,6,33,32,0,0
239,3d17f121-e015-683b-df1e-21e1ddbaab9c,60,535232.95,133071.21,402161.74,1,7,11,41,0,0
612,9eb99e6f-21e9-c2dc-835f-13c6a53f9a16,76,515240.44,485089.33,30151.11,2,7,30,34,3,0
955,fa53fdfe-9fb4-a535-b49b-3ce0fd0998cd,106,500872.65,469666.19,31206.46,12,1,40,53,0,0
960,fb77a596-afb5-6e06-8cb9-f9ca44b21b78,60,436282.34,410426.02,25856.32,0,4,16,40,0,0
499,817efce8-3d2a-48a1-6d79-8505d24df078,64,402049.48,319024.86,83024.62,0,3,32,17,1,11
344,55ae23ff-e1b5-2722-0304-85667b3dad8b,62,399008.53,160447.05,238561.48,0,5,19,27,0,11
891,ea9d6669-efc3-3c16-4f70-70cc1c1659d7,65,366385.72,144886.50,221499.22,0,3,12,41,0,9
390,63dd8d79-f75f-a1b2-2d68-9a5840f469ce,66,343544.91,74733.70,268811.21,0,1,44,21,0,0
67,12f0d3df-7ea9-3005-ea7e-a4c829536a12,73,331058.64,289187.66,41870.98,49,5,0,19,0,0
316,4f966eb8-d93f-fbfc-298e-8a90ebdeafbe,76,294777.26,275286.88,19490.38,2,3,54,16,1,0
346,56355c60-1f3a-03ef-57d6-0d9ca841df12,74,287108.54,56603.42,230505.12,0,1,51,22,0,0
280,45143d96-1165-e949-2c51-422c2df7c679,56,281683.11,155911.38,125771.73,0,2,42,12,0,0

In [145]:
# Show DataFrame variables currently available in the notebook

df_variables = {
    name: type(obj).__name__
    for name, obj in globals().items()
    if hasattr(obj, "columns")
}

df_variables

{'_': 'DataFrame',
 '__': 'DataFrame',
 '___': 'DataFrame',
 'patients': 'DataFrame',
 'encounters': 'DataFrame',
 'procedures': 'DataFrame',
 'payers': 'DataFrame',
 'organizations': 'DataFrame',
 '_4': 'DataFrame',
 '_5': 'DataFrame',
 '_6': 'DataFrame',
 '_7': 'DataFrame',
 '_8': 'DataFrame',
 'df': 'DataFrame',
 'missing': 'DataFrame',
 'procedure_check': 'DataFrame',
 'mismatches': 'DataFrame',
 'dictionary': 'DataFrame',
 'profile': 'DataFrame',
 'patients_clean': 'DataFrame',
 'encounters_clean': 'DataFrame',
 'procedures_clean': 'DataFrame',
 'payers_clean': 'DataFrame',
 'organizations_clean': 'DataFrame',
 '_54': 'DataFrame',
 '_55': 'DataFrame',
 '_56': 'DataFrame',
 'invalid_death_dates': 'DataFrame',
 '_58': 'DataFrame',
 'invalid_encounter_dates': 'DataFrame',
 'zero_duration_encounters': 'DataFrame',
 'invalid_procedure_dates': 'DataFrame',
 'zero_duration_procedures': 'DataFrame',
 'encounter_patient_dates': 'DataFrame',
 'invalid_birth_encounters': 'DataFrame',
 'procedure_patient_dates': 'DataFrame',
 'invalid_birth_procedures': 'DataFrame',
 '_67': 'DataFrame',
 'negative_duration': 'DataFrame',
 'zero_duration': 'DataFrame',
 'longest_encounters': 'DataFrame',
 '_74': 'DataFrame',
 '_75': 'DataFrame',
 'duration_distribution': 'DataFrame',
 '_76': 'DataFrame',
 'long_encounters': 'DataFrame',
 '_77': 'DataFrame',
 'eda_summary': 'DataFrame',
 '_78': 'DataFrame',
 'gender_distribution': 'DataFrame',
 '_79': 'DataFrame',
 'race_distribution': 'DataFrame',
 'ethnicity_distribution': 'DataFrame',
 '_81': 'DataFrame',
 'marital_distribution': 'DataFrame',
 '_82': 'DataFrame',
 'patients_age': 'DataFrame',
 '_83': 'DataFrame',
 'age_group_summary': 'DataFrame',
 'encounter_volume': 'DataFrame',
 '_87': 'DataFrame',
 'encounter_description': 'DataFrame',
 '_94': 'DataFrame',
 'patient_utilization': 'DataFrame',
 '_95': 'DataFrame',
 'top_utilizers': 'DataFrame',
 '_97': 'DataFrame',
 'cost_summary': 'DataFrame',
 '_98': 'DataFrame',
 'payer_analysis': 'DataFrame',
 '_103': 'DataFrame',
 '_104': 'DataFrame',
 '_105': 'DataFrame',
 'procedure_summary': 'DataFrame',
 '_106': 'DataFrame',
 'procedure_cost': 'DataFrame',
 '_107': 'DataFrame',
 'patient_procedures': 'DataFrame',
 '_108': 'DataFrame',
 'monthly_encounters': 'DataFrame',
 '_111': 'DataFrame',
 'annual_encounters': 'DataFrame',
 '_112': 'DataFrame',
 'annual_procedures': 'DataFrame',
 '_113': 'DataFrame',
 'duration_by_type': 'DataFrame',
 '_114': 'DataFrame',
 '_118': 'DataFrame',
 '_120': 'DataFrame',
 'procedures_per_encounter': 'DataFrame',
 '_123': 'DataFrame',
 'procedure_encounter_check': 'DataFrame',
 'patients_without_encounters': 'DataFrame',
 '_126': 'DataFrame',
 'eda_findings': 'DataFrame',
 '_127': 'DataFrame',
 'duration_outliers': 'DataFrame',
 '_128': 'DataFrame',
 'long_duration_by_type': 'DataFrame',
 '_129': 'DataFrame',
 'duration_profile': 'DataFrame',
 '_133': 'DataFrame',
 'data_quality_summary': 'DataFrame',
 '_134': 'DataFrame',
 '_135': 'DataFrame',
 'high_utilization_patients': 'DataFrame',
 '_136': 'DataFrame',
 'patient_utilization_ranked': 'DataFrame',
 'utilization_concentration': 'DataFrame',
 '_138': 'DataFrame',
 '_140': 'DataFrame',
 'top_cost_patients': 'DataFrame',
 '_142': 'DataFrame',
 'high_util_high_cost': 'DataFrame',
 '_144': 'DataFrame'}

In [146]:
# Profile high-utilization + high-cost patients

high_risk_high_cost = high_util_high_cost.copy()

high_risk_high_cost = high_risk_high_cost.sort_values(
    ["Total_Encounter_Cost", "Encounter_Count"],
    ascending=False
)

high_risk_high_cost.head(20)

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters
245,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,9932262.99,0.00,9932262.99,0,172,48,3,213,11
973,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,6356665.66,845233.69,5511431.97,0,0,72,2,206,11
647,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,3014121.02,0.00,3014121.02,0,6,0,15,121,0
174,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,2699823.10,0.00,2699823.10,0,0,0,0,120,0
85,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,2437415.31,0.00,2437415.31,0,0,77,1304,0,0
900,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,2090033.12,0.00,2090033.12,0,0,0,0,94,0
970,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,1181185.96,0.00,1181185.96,0,4,12,90,0,0
9,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,1127635.83,0.00,1127635.83,52,16,65,36,0,11
70,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,1030983.91,54044.35,976939.56,0,0,99,1,0,11
555,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,1024237.46,397776.45,626461.01,63,3,43,14,0,9
444,7412b008-76f9-b713-c514-2a5d82e3b39e,59,983828.37,0.00,983828.37,54,1,4,0,0,0
879,e7eaf3df-a981-d555-12d6-fdd50fa2631e,66,863712.20,152955.97,710756.23,48,2,4,3,1,8
371,5e055638-0dad-dfd5-005d-1e74b6fd29ac,887,844913.74,628529.62,216384.12,0,17,92,778,0,0
240,3de74169-7f67-9304-91d4-757e0f3a14d2,877,819279.19,0.00,819279.19,0,49,35,786,0,7
337,5427845a-82ab-b6c9-e70b-aeb672ddd5d7,149,707094.17,560859.04,146235.13,0,0,0,0,149,0
652,a80b1160-93f0-db7e-9f23-04ea6fdddfaf,59,636438.70,0.00,636438.70,53,0,1,0,0,5
491,7f0dc5c3-f35c-df5b-8564-95aa38b575d6,83,625019.99,352791.27,272228.72,1,4,16,62,0,0
972,ff1b3c26-53a6-4590-ce79-a3f7269274ea,72,616543.65,16531.38,600012.27,0,3,22,37,0,10
564,9279705f-2e5c-2792-ae20-7a77b5b04015,67,598712.31,350771.01,247941.30,0,3,7,57,0,0
682,b0c95bfd-adc4-8910-a75d-e208879c975d,96,580593.75,457700.11,122893.64,0,8,67,11,0,10

In [147]:
# Financial concentration of high-utilization + high-cost patients

total_patients = patient_utilization["PATIENT"].nunique()
total_cost = patient_utilization["Total_Encounter_Cost"].sum()

high_risk_patients = len(high_risk_high_cost)
high_risk_cost = high_risk_high_cost["Total_Encounter_Cost"].sum()

high_risk_patient_share = (
    high_risk_patients / total_patients * 100
)

high_risk_cost_share = (
    high_risk_cost / total_cost * 100
)

print(f"Total patients: {total_patients:,}")
print(f"High-utilization + high-cost patients: {high_risk_patients:,}")
print(f"High-risk patient share: {high_risk_patient_share:.2f}%")
print(f"Total healthcare cost: ${total_cost:,.2f}")
print(f"High-risk patient cost: ${high_risk_cost:,.2f}")
print(f"High-risk cost share: {high_risk_cost_share:.2f}%")

Total patients: 974
High-utilization + high-cost patients: 36
High-risk patient share: 3.70%
Total healthcare cost: $101,514,375.52
High-risk patient cost: $45,124,116.53
High-risk cost share: 44.45%

In [148]:
# Cost composition of high-utilization + high-cost patients

high_risk_patient_ids = high_risk_high_cost["PATIENT"]

high_risk_encounters = encounters_clean[
    encounters_clean["PATIENT"].isin(high_risk_patient_ids)
].copy()

cost_by_encounter_type = (
    high_risk_encounters
    .groupby("ENCOUNTERCLASS")
    .agg(
        Encounter_Count=("Id", "count"),
        Total_Cost=("TOTAL_CLAIM_COST", "sum"),
        Patient_Responsibility=("PATIENT_RESPONSIBILITY", "sum")
    )
    .sort_values("Total_Cost", ascending=False)
)

cost_by_encounter_type["Cost_Share_Percentage"] = (
    cost_by_encounter_type["Total_Cost"]
    / cost_by_encounter_type["Total_Cost"].sum()
    * 100
)

cost_by_encounter_type

,Encounter_Count,Total_Cost,Patient_Responsibility,Cost_Share_Percentage
ENCOUNTERCLASS,,,,
urgentcare,909,17782386.89,16626093.73,39.407723
ambulatory,3657,10466022.18,7136803.70,23.193855
outpatient,1087,6769495.68,5728593.42,15.001946
emergency,345,4684205.82,4529636.40,10.380715
inpatient,377,4220883.03,3038838.30,9.353941
wellness,132,1201122.93,796238.06,2.661820

In [149]:
# Calculate average cost and patient responsibility per encounter type

cost_intensity = (
    high_risk_encounters
    .groupby("ENCOUNTERCLASS")
    .agg(
        Encounter_Count=("Id", "count"),
        Total_Cost=("TOTAL_CLAIM_COST", "sum"),
        Total_Patient_Responsibility=("PATIENT_RESPONSIBILITY", "sum")
    )
)

cost_intensity["Average_Cost_Per_Encounter"] = (
    cost_intensity["Total_Cost"]
    / cost_intensity["Encounter_Count"]
)

cost_intensity["Average_Patient_Responsibility_Per_Encounter"] = (
    cost_intensity["Total_Patient_Responsibility"]
    / cost_intensity["Encounter_Count"]
)

cost_intensity = cost_intensity.sort_values(
    "Average_Cost_Per_Encounter",
    ascending=False
)

cost_intensity

,Encounter_Count,Total_Cost,Total_Patient_Responsibility,Average_Cost_Per_Encounter,Average_Patient_Responsibility_Per_Encounter
ENCOUNTERCLASS,,,,,
urgentcare,909,17782386.89,16626093.73,19562.581837,18290.532156
emergency,345,4684205.82,4529636.40,13577.408174,13129.380870
inpatient,377,4220883.03,3038838.30,11195.976207,8060.579045
wellness,132,1201122.93,796238.06,9099.416136,6032.106515
outpatient,1087,6769495.68,5728593.42,6227.686918,5270.095143
ambulatory,3657,10466022.18,7136803.70,2861.914733,1951.545994

In [150]:
# Rank high-utilization + high-cost patients by financial burden

financial_burden_high_risk = (
    high_risk_high_cost[
        [
            "PATIENT",
            "Encounter_Count",
            "Total_Encounter_Cost",
            "Total_Payer_Coverage",
            "Total_Patient_Responsibility"
        ]
    ]
    .copy()
)

financial_burden_high_risk["Patient_Responsibility_Rate"] = (
    financial_burden_high_risk["Total_Patient_Responsibility"]
    / financial_burden_high_risk["Total_Encounter_Cost"]
    * 100
)

financial_burden_high_risk = (
    financial_burden_high_risk
    .sort_values(
        "Total_Patient_Responsibility",
        ascending=False
    )
)

financial_burden_high_risk.head(20)

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Patient_Responsibility_Rate
245,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,9932262.99,0.00,9932262.99,100.000000
973,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,6356665.66,845233.69,5511431.97,86.703191
647,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,3014121.02,0.00,3014121.02,100.000000
174,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,2699823.10,0.00,2699823.10,100.000000
85,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,2437415.31,0.00,2437415.31,100.000000
900,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,2090033.12,0.00,2090033.12,100.000000
970,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,1181185.96,0.00,1181185.96,100.000000
9,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,1127635.83,0.00,1127635.83,100.000000
444,7412b008-76f9-b713-c514-2a5d82e3b39e,59,983828.37,0.00,983828.37,100.000000
70,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,1030983.91,54044.35,976939.56,94.757983
240,3de74169-7f67-9304-91d4-757e0f3a14d2,877,819279.19,0.00,819279.19,100.000000
879,e7eaf3df-a981-d555-12d6-fdd50fa2631e,66,863712.20,152955.97,710756.23,82.290864
652,a80b1160-93f0-db7e-9f23-04ea6fdddfaf,59,636438.70,0.00,636438.70,100.000000
555,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,1024237.46,397776.45,626461.01,61.163649
972,ff1b3c26-53a6-4590-ce79-a3f7269274ea,72,616543.65,16531.38,600012.27,97.318701
870,e54023a5-ae9a-fea9-3ad3-08989ea5b5aa,57,580149.36,0.00,580149.36,100.000000
229,394f3e43-784c-b938-adb6-4b69efd46bbf,63,567891.96,23888.10,544003.86,95.793548
1,0034fe01-207f-275f-6b4b-821f7b0af044,75,548667.37,5494.56,543172.81,98.998563
239,3d17f121-e015-683b-df1e-21e1ddbaab9c,60,535232.95,133071.21,402161.74,75.137702
491,7f0dc5c3-f35c-df5b-8564-95aa38b575d6,83,625019.99,352791.27,272228.72,43.555202

In [151]:
# Aggregate financial burden among high-utilization + high-cost patients

high_risk_total_cost = high_risk_high_cost["Total_Encounter_Cost"].sum()
high_risk_payer_coverage = high_risk_high_cost["Total_Payer_Coverage"].sum()
high_risk_patient_responsibility = (
    high_risk_high_cost["Total_Patient_Responsibility"].sum()
)

high_risk_patient_responsibility_rate = (
    high_risk_patient_responsibility
    / high_risk_total_cost
    * 100
)

print(f"High-risk total cost: ${high_risk_total_cost:,.2f}")
print(f"High-risk payer coverage: ${high_risk_payer_coverage:,.2f}")
print(
    f"High-risk patient responsibility: "
    f"${high_risk_patient_responsibility:,.2f}"
)
print(
    f"High-risk patient responsibility rate: "
    f"{high_risk_patient_responsibility_rate:.2f}%"
)

High-risk total cost: $45,124,116.53
High-risk payer coverage: $7,267,912.92
High-risk patient responsibility: $37,856,203.61
High-risk patient responsibility rate: 83.89%

In [152]:
patient_utilization.columns.tolist()

['PATIENT',
 'Encounter_Count',
 'Total_Encounter_Cost',
 'Total_Payer_Coverage',
 'Total_Patient_Responsibility',
 'Inpatient_Encounters',
 'Emergency_Encounters',
 'Outpatient_Encounters',
 'Ambulatory_Encounters',
 'UrgentCare_Encounters',
 'Wellness_Encounters',
 'High_Acuity_Encounters',
 'Emergency_Rate',
 'Inpatient_Rate',
 'High_Acuity_Rate']

In [153]:
patient_utilization.head()

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters,High_Acuity_Encounters,Emergency_Rate,Inpatient_Rate,High_Acuity_Rate
0,002bc307-2fff-04ba-161b-98cce123e226,46,13742.67,9509.86,4232.81,2,3,38,3,0,0,5,6.52,4.35,10.87
1,0034fe01-207f-275f-6b4b-821f7b0af044,75,548667.37,5494.56,543172.81,4,6,33,32,0,0,10,8.00,5.33,13.33
2,00abe029-00fa-a666-34f5-258a36978f6d,22,48334.27,6384.67,41949.60,0,1,5,16,0,0,1,4.55,0.00,4.55
3,010ff9c1-564b-6e32-09f4-29cb4224bba9,4,26367.50,19475.04,6892.46,0,0,1,3,0,0,0,0.00,0.00,0.00
4,01274098-150f-8211-6150-29f2a2da266c,1,0.00,0.00,0.00,1,0,0,0,0,0,1,0.00,100.00,100.00

In [154]:
import numpy as np

In [155]:
np.__version__

'2.5.1'

In [156]:
# Segment patients by utilization and cost

patient_risk_segments = patient_utilization.copy()

patient_risk_segments["Risk_Segment"] = np.select(
    [
        (patient_risk_segments["Encounter_Count"] > high_utilization_threshold) &
        (patient_risk_segments["Total_Encounter_Cost"] > high_cost_threshold),

        (patient_risk_segments["Encounter_Count"] > high_utilization_threshold) &
        (patient_risk_segments["Total_Encounter_Cost"] <= high_cost_threshold),

        (patient_risk_segments["Encounter_Count"] <= high_utilization_threshold) &
        (patient_risk_segments["Total_Encounter_Cost"] > high_cost_threshold),

        (patient_risk_segments["Encounter_Count"] <= high_utilization_threshold) &
        (patient_risk_segments["Total_Encounter_Cost"] <= high_cost_threshold)
    ],
    [
        "High Utilization + High Cost",
        "High Utilization + Lower Cost",
        "Lower Utilization + High Cost",
        "Lower Utilization + Lower Cost"
    ],
    default="Unclassified"
)

risk_segment_summary = (
    patient_risk_segments
    .groupby("Risk_Segment")
    .agg(
        Patients=("PATIENT", "count"),
        Total_Encounters=("Encounter_Count", "sum"),
        Total_Cost=("Total_Encounter_Cost", "sum"),
        Total_Patient_Responsibility=("Total_Patient_Responsibility", "sum")
    )
    .sort_values("Total_Cost", ascending=False)
)

risk_segment_summary["Patient_Share_Percentage"] = (
    risk_segment_summary["Patients"] /
    len(patient_risk_segments) * 100
).round(2)

risk_segment_summary["Cost_Share_Percentage"] = (
    risk_segment_summary["Total_Cost"] /
    risk_segment_summary["Total_Cost"].sum() * 100
).round(2)

risk_segment_summary

,Patients,Total_Encounters,Total_Cost,Total_Patient_Responsibility,Patient_Share_Percentage,Cost_Share_Percentage
Risk_Segment,,,,,,
High Utilization + High Cost,36,6507,45124116.53,37856203.61,3.70,44.45
Lower Utilization + High Cost,62,2256,26436255.87,16374185.97,6.37,26.04
Lower Utilization + Lower Cost,814,10761,25199883.60,13302562.58,83.57,24.82
High Utilization + Lower Cost,62,8367,4754119.52,2883916.37,6.37,4.68

In [157]:
# Profile the high-utilization + high-cost patient segment

high_risk_profile = patient_utilization[
    (patient_utilization["Encounter_Count"] > high_utilization_threshold) &
    (patient_utilization["Total_Encounter_Cost"] > high_cost_threshold)
].copy()

high_risk_profile_summary = pd.DataFrame({
    "Metric": [
        "Patients",
        "Average Encounters per Patient",
        "Median Encounters per Patient",
        "Average Total Cost per Patient",
        "Median Total Cost per Patient",
        "Average Patient Responsibility",
        "Median Patient Responsibility",
        "Average High-Acuity Rate"
    ],
    "Value": [
        len(high_risk_profile),
        high_risk_profile["Encounter_Count"].mean(),
        high_risk_profile["Encounter_Count"].median(),
        high_risk_profile["Total_Encounter_Cost"].mean(),
        high_risk_profile["Total_Encounter_Cost"].median(),
        high_risk_profile["Total_Patient_Responsibility"].mean(),
        high_risk_profile["Total_Patient_Responsibility"].median(),
        high_risk_profile["High_Acuity_Rate"].mean()
    ]
})

high_risk_profile_summary

                           Metric         Value
0                        Patients  3.600000e+01
1  Average Encounters per Patient  1.807500e+02
2   Median Encounters per Patient  7.550000e+01
3  Average Total Cost per Patient  1.253448e+06
4   Median Total Cost per Patient  6.076280e+05
5  Average Patient Responsibility  1.051561e+06
6   Median Patient Responsibility  4.726673e+05
7        Average High-Acuity Rate  1.849556e+01

In [158]:
# Top 10 high-utilization + high-cost patients by total cost

top_high_risk_cost = (
    high_risk_profile[
        [
            "PATIENT",
            "Encounter_Count",
            "Total_Encounter_Cost",
            "Total_Payer_Coverage",
            "Total_Patient_Responsibility",
            "High_Acuity_Encounters",
            "High_Acuity_Rate"
        ]
    ]
    .sort_values(
        "Total_Encounter_Cost",
        ascending=False
    )
    .head(10)
)

top_high_risk_cost

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,High_Acuity_Encounters,High_Acuity_Rate
245,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,9932262.99,0.00,9932262.99,172,38.48
973,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,6356665.66,845233.69,5511431.97,0,0.00
647,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,3014121.02,0.00,3014121.02,6,4.23
174,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,2699823.10,0.00,2699823.10,0,0.00
85,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,2437415.31,0.00,2437415.31,0,0.00
900,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,2090033.12,0.00,2090033.12,0,0.00
970,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,1181185.96,0.00,1181185.96,4,3.77
9,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,1127635.83,0.00,1127635.83,68,37.78
70,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,1030983.91,54044.35,976939.56,0,0.00
555,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,1024237.46,397776.45,626461.01,66,50.00

In [159]:
# Calculate cost concentration among the top 10 high-risk patients

top_10_high_risk_cost = top_high_risk_cost["Total_Encounter_Cost"].sum()

high_risk_total_cost = high_risk_profile["Total_Encounter_Cost"].sum()

top_10_cost_share = (
    top_10_high_risk_cost / high_risk_total_cost
) * 100

print(f"High-risk total cost: ${high_risk_total_cost:,.2f}")
print(f"Top 10 high-risk patient cost: ${top_10_high_risk_cost:,.2f}")
print(f"Top 10 cost share of high-risk group: {top_10_cost_share:.2f}%")

High-risk total cost: $45,124,116.53
Top 10 high-risk patient cost: $30,894,364.36
Top 10 cost share of high-risk group: 68.47%

In [160]:
# Analyze relationship between utilization and cost
# among high-utilization + high-cost patients

high_risk_correlation = high_risk_profile[
    [
        "Encounter_Count",
        "Total_Encounter_Cost",
        "Total_Patient_Responsibility",
        "High_Acuity_Rate"
    ]
].corr()

high_risk_correlation

,Encounter_Count,Total_Encounter_Cost,Total_Patient_Responsibility,High_Acuity_Rate
Encounter_Count,1.000000,0.291034,0.289736,-0.175179
Total_Encounter_Cost,0.291034,1.000000,0.992812,0.001768
Total_Patient_Responsibility,0.289736,0.992812,1.000000,0.012944
High_Acuity_Rate,-0.175179,0.001768,0.012944,1.000000

In [161]:
# Final high-risk patient dataset

high_risk_final = (
    high_risk_profile[
        [
            "PATIENT",
            "Encounter_Count",
            "Total_Encounter_Cost",
            "Total_Payer_Coverage",
            "Total_Patient_Responsibility",
            "Inpatient_Encounters",
            "Emergency_Encounters",
            "Outpatient_Encounters",
            "Ambulatory_Encounters",
            "UrgentCare_Encounters",
            "Wellness_Encounters",
            "High_Acuity_Encounters",
            "Emergency_Rate",
            "Inpatient_Rate",
            "High_Acuity_Rate"
        ]
    ]
    .sort_values(
        "Total_Encounter_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)

high_risk_final.head(10)

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters,High_Acuity_Encounters,Emergency_Rate,Inpatient_Rate,High_Acuity_Rate
0,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,9932262.99,0.00,9932262.99,0,172,48,3,213,11,172,38.48,0.00,38.48
1,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,6356665.66,845233.69,5511431.97,0,0,72,2,206,11,0,0.00,0.00,0.00
2,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,3014121.02,0.00,3014121.02,0,6,0,15,121,0,6,4.23,0.00,4.23
3,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,2699823.10,0.00,2699823.10,0,0,0,0,120,0,0,0.00,0.00,0.00
4,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,2437415.31,0.00,2437415.31,0,0,77,1304,0,0,0,0.00,0.00,0.00
5,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,2090033.12,0.00,2090033.12,0,0,0,0,94,0,0,0.00,0.00,0.00
6,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,1181185.96,0.00,1181185.96,0,4,12,90,0,0,4,3.77,0.00,3.77
7,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,1127635.83,0.00,1127635.83,52,16,65,36,0,11,68,8.89,28.89,37.78
8,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,1030983.91,54044.35,976939.56,0,0,99,1,0,11,0,0.00,0.00,0.00
9,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,1024237.46,397776.45,626461.01,63,3,43,14,0,9,66,2.27,47.73,50.00

Patient utilization and cost were highly concentrated. Only 3.70% of patients were classified as high-utilization/high-cost, yet they accounted for 44.45% of total healthcare expenditure. A further 6.37% of patients were lower-utilization but high-cost, contributing another 26.04% of total costs. Combined, approximately 10% of patients generated over 70% of total healthcare costs. Meanwhile, high-utilization/low-cost patients represented 6.37% of the population and approximately 30% of encounters but only 4.68% of total costs. This demonstrates that healthcare utilization volume alone is insufficient for identifying financially high-impact patients and supports a segmented approach to care management and resource allocation.

In [162]:
# STEP 6.1 — Rebuild high-risk patients using the current patient_utilization

high_util_high_cost = patient_utilization[
    (patient_utilization["Encounter_Count"] > high_utilization_threshold) &
    (patient_utilization["Total_Encounter_Cost"] > high_cost_threshold)
].copy()

# Create the business summary
high_risk_business_summary = high_util_high_cost[
    [
        "PATIENT",
        "Encounter_Count",
        "Total_Encounter_Cost",
        "Total_Payer_Coverage",
        "Total_Patient_Responsibility",
        "High_Acuity_Encounters",
        "High_Acuity_Rate"
    ]
].sort_values(
    "Total_Encounter_Cost",
    ascending=False
).reset_index(drop=True)

high_risk_business_summary.head(10)

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,High_Acuity_Encounters,High_Acuity_Rate
0,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,9932262.99,0.00,9932262.99,172,38.48
1,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,6356665.66,845233.69,5511431.97,0,0.00
2,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,3014121.02,0.00,3014121.02,6,4.23
3,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,2699823.10,0.00,2699823.10,0,0.00
4,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,2437415.31,0.00,2437415.31,0,0.00
5,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,2090033.12,0.00,2090033.12,0,0.00
6,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,1181185.96,0.00,1181185.96,4,3.77
7,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,1127635.83,0.00,1127635.83,68,37.78
8,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,1030983.91,54044.35,976939.56,0,0.00
9,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,1024237.46,397776.45,626461.01,66,50.00

In [163]:
print(patient_utilization.columns.tolist())

['PATIENT', 'Encounter_Count', 'Total_Encounter_Cost', 'Total_Payer_Coverage', 'Total_Patient_Responsibility', 'Inpatient_Encounters', 'Emergency_Encounters', 'Outpatient_Encounters', 'Ambulatory_Encounters', 'UrgentCare_Encounters', 'Wellness_Encounters', 'High_Acuity_Encounters', 'Emergency_Rate', 'Inpatient_Rate', 'High_Acuity_Rate']

In [164]:
# ============================================================
# STEP 4.8 — DATA QUALITY SUMMARY
# ============================================================

data_quality_summary = pd.DataFrame({
    "Check": [
        "Patients",
        "Encounters",
        "Procedures",
        "Payers",
        "Organizations",
        "Missing age at encounter",
        "Negative age at encounter",
        "Missing age groups",
        "Patients with death dates",
        "Negative age at death",
        "Long encounters >7 days",
        "Procedures without valid encounters",
        "Patients with no encounters",
        "Negative patient responsibility"
    ],
    "Result": [
        len(patients_clean),
        len(encounters_clean),
        len(procedures_clean),
        len(payers_clean),
        len(organizations_clean),
        encounters_clean["AGE_AT_ENCOUNTER"].isna().sum(),
        (encounters_clean["AGE_AT_ENCOUNTER"] < 0).sum(),
        encounters_clean["AGE_GROUP"].isna().sum(),
        patients_clean["DEATHDATE"].notna().sum(),
        (patients_clean["AGE_AT_DEATH"] < 0).sum(),
        (encounters_clean["DURATION_DAYS"] > 7).sum(),
        0,
        0,
        (encounters_clean["PATIENT_RESPONSIBILITY"] < 0).sum()
    ]
})

data_quality_summary

                                  Check  Result
0                              Patients     974
1                            Encounters   27891
2                            Procedures   47701
3                                Payers      10
4                         Organizations       1
5              Missing age at encounter       0
6             Negative age at encounter       0
7                    Missing age groups       0
8             Patients with death dates     154
9                 Negative age at death       0
10              Long encounters >7 days      31
11  Procedures without valid encounters       0
12          Patients with no encounters       0
13      Negative patient responsibility       0

In [165]:
# STEP 6.4 — Overall financial burden and high-risk comparison

overall_financial_summary = pd.DataFrame({
    "Metric": [
        "Total Healthcare Cost",
        "Total Payer Coverage",
        "Total Patient Responsibility",
        "Overall Patient Responsibility Rate",
        "High-Risk Healthcare Cost",
        "High-Risk Payer Coverage",
        "High-Risk Patient Responsibility",
        "High-Risk Patient Responsibility Rate"
    ],
    "Value": [
        patient_utilization["Total_Encounter_Cost"].sum(),
        patient_utilization["Total_Payer_Coverage"].sum(),
        patient_utilization["Total_Patient_Responsibility"].sum(),
        (
            patient_utilization["Total_Patient_Responsibility"].sum()
            / patient_utilization["Total_Encounter_Cost"].sum()
            * 100
        ),
        high_util_high_cost["Total_Encounter_Cost"].sum(),
        high_util_high_cost["Total_Payer_Coverage"].sum(),
        high_util_high_cost["Total_Patient_Responsibility"].sum(),
        (
            high_util_high_cost["Total_Patient_Responsibility"].sum()
            / high_util_high_cost["Total_Encounter_Cost"].sum()
            * 100
        )
    ]
})

overall_financial_summary

                                  Metric         Value
0                  Total Healthcare Cost  1.015144e+08
1                   Total Payer Coverage  3.109751e+07
2           Total Patient Responsibility  7.041687e+07
3    Overall Patient Responsibility Rate  6.936640e+01
4              High-Risk Healthcare Cost  4.512412e+07
5               High-Risk Payer Coverage  7.267913e+06
6       High-Risk Patient Responsibility  3.785620e+07
7  High-Risk Patient Responsibility Rate  8.389351e+01

In [166]:
# STEP 6.5 — Cost concentration among high-cost patients

high_cost_segments = patient_risk_segments[
    patient_risk_segments["Risk_Segment"].isin([
        "High Utilization + High Cost",
        "Lower Utilization + High Cost"
    ])
].copy()

high_cost_concentration = pd.DataFrame({
    "Metric": [
        "Total Patients",
        "Patient Share (%)",
        "Total Healthcare Cost",
        "Cost Share (%)"
    ],
    "Value": [
        high_cost_segments["PATIENT"].nunique(),
        (
            high_cost_segments["PATIENT"].nunique()
            / patient_risk_segments["PATIENT"].nunique()
            * 100
        ),
        high_cost_segments["Total_Encounter_Cost"].sum(),
        (
            high_cost_segments["Total_Encounter_Cost"].sum()
            / patient_risk_segments["Total_Encounter_Cost"].sum()
            * 100
        )
    ]
})

high_cost_concentration

                  Metric         Value
0         Total Patients  9.800000e+01
1      Patient Share (%)  1.006160e+01
2  Total Healthcare Cost  7.156037e+07
3         Cost Share (%)  7.049285e+01

In [167]:
# STEP 6.6 — Profile the four patient risk segments

risk_segment_profile = (
    patient_risk_segments
    .groupby("Risk_Segment")
    .agg(
        Patients=("PATIENT", "nunique"),
        Avg_Encounters_Per_Patient=("Encounter_Count", "mean"),
        Median_Encounters_Per_Patient=("Encounter_Count", "median"),
        Avg_Healthcare_Cost=("Total_Encounter_Cost", "mean"),
        Median_Healthcare_Cost=("Total_Encounter_Cost", "median"),
        Avg_Patient_Responsibility=("Total_Patient_Responsibility", "mean"),
        Median_Patient_Responsibility=("Total_Patient_Responsibility", "median"),
        Avg_High_Acuity_Rate=("High_Acuity_Rate", "mean")
    )
    .reset_index()
)

risk_segment_profile

,Risk_Segment,Patients,Avg_Encounters_Per_Patient,Median_Encounters_Per_Patient,Avg_Healthcare_Cost,Median_Healthcare_Cost,Avg_Patient_Responsibility,Median_Patient_Responsibility,Avg_High_Acuity_Rate
0,High Utilization + High Cost,36,180.750000,75.5,1.253448e+06,607627.980,1.051561e+06,472667.275,18.495556
1,High Utilization + Lower Cost,62,134.951613,99.5,7.667935e+04,63488.215,4.651478e+04,34609.340,15.830000
2,Lower Utilization + High Cost,62,36.387097,37.0,4.263912e+05,372800.900,2.640998e+05,248128.730,10.940645
3,Lower Utilization + Lower Cost,814,13.219902,10.0,3.095809e+04,17046.510,1.634221e+04,5246.165,11.301499

In [168]:
# STEP 6.2 — High-Risk Patient Characteristics

# Identify the 36 high-utilization + high-cost patients
high_risk_patients = patient_utilization[
    (patient_utilization["Encounter_Count"] > high_utilization_threshold) &
    (patient_utilization["Total_Encounter_Cost"] > high_cost_threshold)
].copy()

# Create a profile of the high-risk group
high_risk_profile = pd.DataFrame({
    "Metric": [
        "Patients",
        "Average Encounters",
        "Median Encounters",
        "Average Healthcare Cost",
        "Median Healthcare Cost",
        "Average Patient Responsibility",
        "Average Emergency Rate",
        "Average Inpatient Rate",
        "Average High-Acuity Rate"
    ],
    "Value": [
        len(high_risk_patients),
        high_risk_patients["Encounter_Count"].mean(),
        high_risk_patients["Encounter_Count"].median(),
        high_risk_patients["Total_Encounter_Cost"].mean(),
        high_risk_patients["Total_Encounter_Cost"].median(),
        high_risk_patients["Total_Patient_Responsibility"].mean(),
        high_risk_patients["Emergency_Rate"].mean(),
        high_risk_patients["Inpatient_Rate"].mean(),
        high_risk_patients["High_Acuity_Rate"].mean()
    ]
})

high_risk_profile

                           Metric         Value
0                        Patients  3.600000e+01
1              Average Encounters  1.807500e+02
2               Median Encounters  7.550000e+01
3         Average Healthcare Cost  1.253448e+06
4          Median Healthcare Cost  6.076280e+05
5  Average Patient Responsibility  1.051561e+06
6          Average Emergency Rate  4.945000e+00
7          Average Inpatient Rate  1.355111e+01
8        Average High-Acuity Rate  1.849556e+01

In [169]:
# Create comparison group
non_high_risk = patient_utilization[
    ~patient_utilization["PATIENT"].isin(high_risk_patients["PATIENT"])
].copy()

comparison = pd.DataFrame({
    "Metric": [
        "Average Encounters",
        "Average Healthcare Cost",
        "Average Patient Responsibility",
        "Average Emergency Rate",
        "Average Inpatient Rate",
        "Average High-Acuity Rate"
    ],
    "High_Risk": [
        high_risk_patients["Encounter_Count"].mean(),
        high_risk_patients["Total_Encounter_Cost"].mean(),
        high_risk_patients["Total_Patient_Responsibility"].mean(),
        high_risk_patients["Emergency_Rate"].mean(),
        high_risk_patients["Inpatient_Rate"].mean(),
        high_risk_patients["High_Acuity_Rate"].mean()
    ],
    "Other_Patients": [
        non_high_risk["Encounter_Count"].mean(),
        non_high_risk["Total_Encounter_Cost"].mean(),
        non_high_risk["Total_Patient_Responsibility"].mean(),
        non_high_risk["Emergency_Rate"].mean(),
        non_high_risk["Inpatient_Rate"].mean(),
        non_high_risk["High_Acuity_Rate"].mean()
    ]
})

comparison

                           Metric     High_Risk  Other_Patients
0              Average Encounters  1.807500e+02       22.797441
1         Average Healthcare Cost  1.253448e+06    60117.546898
2  Average Patient Responsibility  1.051561e+06    34712.862388
3          Average Emergency Rate  4.945000e+00        8.770629
4          Average Inpatient Rate  1.355111e+01        2.806269
5        Average High-Acuity Rate  1.849556e+01       11.576972

In [170]:
# STEP 6.3 — High-Risk Encounter Mix and Cost Drivers

# Get all encounters belonging to high-risk patients
high_risk_ids = high_risk_patients["PATIENT"]

high_risk_encounters = encounters_clean[
    encounters_clean["PATIENT"].isin(high_risk_ids)
].copy()

# Summarize encounter types
high_risk_encounter_mix = (
    high_risk_encounters
    .groupby("ENCOUNTERCLASS")
    .agg(
        Encounter_Count=("Id", "count"),
        Total_Cost=("TOTAL_CLAIM_COST", "sum"),
        Patient_Responsibility=("PATIENT_RESPONSIBILITY", "sum")
    )
    .reset_index()
)

# Calculate percentages
high_risk_encounter_mix["Encounter_Share_Percentage"] = (
    high_risk_encounter_mix["Encounter_Count"]
    / high_risk_encounter_mix["Encounter_Count"].sum()
    * 100
)

high_risk_encounter_mix["Cost_Share_Percentage"] = (
    high_risk_encounter_mix["Total_Cost"]
    / high_risk_encounter_mix["Total_Cost"].sum()
    * 100
)

# Average cost per encounter
high_risk_encounter_mix["Average_Cost_Per_Encounter"] = (
    high_risk_encounter_mix["Total_Cost"]
    / high_risk_encounter_mix["Encounter_Count"]
)

high_risk_encounter_mix.sort_values(
    "Total_Cost",
    ascending=False
)

,ENCOUNTERCLASS,Encounter_Count,Total_Cost,Patient_Responsibility,Encounter_Share_Percentage,Cost_Share_Percentage,Average_Cost_Per_Encounter
4,urgentcare,909,17782386.89,16626093.73,13.969571,39.407723,19562.581837
0,ambulatory,3657,10466022.18,7136803.70,56.201014,23.193855,2861.914733
3,outpatient,1087,6769495.68,5728593.42,16.705087,15.001946,6227.686918
1,emergency,345,4684205.82,4529636.40,5.301982,10.380715,13577.408174
2,inpatient,377,4220883.03,3038838.30,5.793761,9.353941,11195.976207
5,wellness,132,1201122.93,796238.06,2.028585,2.661820,9099.416136

In [171]:
# STEP 6.4 — Highest-Burden High-Risk Patients

high_risk_patient_profile = high_risk_patients[
    [
        "PATIENT",
        "Encounter_Count",
        "Total_Encounter_Cost",
        "Total_Payer_Coverage",
        "Total_Patient_Responsibility",
        "Inpatient_Encounters",
        "Emergency_Encounters",
        "Outpatient_Encounters",
        "Ambulatory_Encounters",
        "UrgentCare_Encounters",
        "Wellness_Encounters",
        "High_Acuity_Encounters",
        "Emergency_Rate",
        "Inpatient_Rate",
        "High_Acuity_Rate"
    ]
].copy()

# Rank by total healthcare cost
high_risk_patient_profile = (
    high_risk_patient_profile
    .sort_values(
        "Total_Encounter_Cost",
        ascending=False
    )
    .reset_index(drop=True)
)

high_risk_patient_profile.head(10)

,PATIENT,Encounter_Count,Total_Encounter_Cost,Total_Payer_Coverage,Total_Patient_Responsibility,Inpatient_Encounters,Emergency_Encounters,Outpatient_Encounters,Ambulatory_Encounters,UrgentCare_Encounters,Wellness_Encounters,High_Acuity_Encounters,Emergency_Rate,Inpatient_Rate,High_Acuity_Rate
0,3f523789-55f3-bb31-2757-4803ca6a9c2a,447,9932262.99,0.00,9932262.99,0,172,48,3,213,11,172,38.48,0.00,38.48
1,ff331e5c-ab16-e218-f39a-63e11de1ed75,291,6356665.66,845233.69,5511431.97,0,0,72,2,206,11,0,0.00,0.00,0.00
2,a733bbc1-cbdf-992f-f1b7-bd230028fc4f,142,3014121.02,0.00,3014121.02,0,6,0,15,121,0,6,4.23,0.00,4.23
3,2aa3ac2a-88c6-3253-547d-6d8ed69790a3,120,2699823.10,0.00,2699823.10,0,0,0,0,120,0,0,0.00,0.00,0.00
4,1712d26d-822d-1e3a-2267-0a9dba31d7c8,1381,2437415.31,0.00,2437415.31,0,0,77,1304,0,0,0,0.00,0.00,0.00
5,eda6bc14-b236-e8c6-509a-b293e9cc688b,94,2090033.12,0.00,2090033.12,0,0,0,0,94,0,0,0.00,0.00,0.00
6,fea2a30d-f7c9-eeb0-9aad-5c711f55574f,106,1181185.96,0.00,1181185.96,0,4,12,90,0,0,4,3.77,0.00,3.77
7,0226f105-2572-1c6f-15f0-1aa0438e40d0,180,1127635.83,0.00,1127635.83,52,16,65,36,0,11,68,8.89,28.89,37.78
8,1375a6a6-5638-8af1-dc4f-2aa58220d36d,111,1030983.91,54044.35,976939.56,0,0,99,1,0,11,0,0.00,0.00,0.00
9,905d0433-9ca3-4883-cbd4-3df36fd5f1c6,132,1024237.46,397776.45,626461.01,63,3,43,14,0,9,66,2.27,47.73,50.00

In [172]:
# Top 10 high-risk patient cost concentration

top_10_cost = high_risk_patient_profile.head(10)["Total_Encounter_Cost"].sum()

high_risk_total_cost = high_risk_patient_profile[
    "Total_Encounter_Cost"
].sum()

top_10_cost_share = (
    top_10_cost / high_risk_total_cost
) * 100

print(f"Top 10 high-risk patient cost: ${top_10_cost:,.2f}")
print(f"High-risk total cost: ${high_risk_total_cost:,.2f}")
print(f"Top 10 cost share: {top_10_cost_share:.2f}%")

Top 10 high-risk patient cost: $30,894,364.36
High-risk total cost: $45,124,116.53
Top 10 cost share: 68.47%